### ISSUE TITLE
I can suspend an Actor

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10006]
**Description**

In order to not implement pausing and resuming in multiple places like Processor, Exporter etc. It would be really useful if we could suspend an Actor, which means that the Actor and all his jobs/subscriptions are not executed until it is woken up again.

related to #9962 
related to https://github.com/camunda/zeebe/issues/10002
related to #9630 

- [ ] Introduce new lifecycle phase
- [ ] define what this means when closed or not opened
- [ ] reject new jobs if suspended
- [ ] define what happens when close is called on suspended actor
- [ ] define what happens when fail is called on suspended actor
- [ ] write tests

**Comment by oleschoenburg** [comment]
What happens for externally submitted jobs? I guess they need to be rejected because we don't want to buffer jobs?

**Comment by Zelldon** [comment]
I guess this is discussable. Since we have queues we could also enqueue it. :shrug:

**Comment by Zelldon** [comment]
But sure we could also reject it, but what would it look like? Exception? For using Actor#call it would be simpler since we can complete the future exceptionally.

**Comment by Zelldon** [comment]
Do we exepect many jobs to be enqueued? Depends I guess on how long the suspend is done and which actor is suspended.

**Comment by oleschoenburg** [comment]
> Do we exepect many jobs to be enqueued? Depends I guess on how long the suspend is done and which actor is suspended.

As there's no telling how long the actor is suspended (and we might end up using it for the `pauseProcessing`, so for disaster recovery the actor might end up paused for hours) I think we can't buffer jobs. Maybe just dropping them without feedback is fine? We're already dropping jobs from the fastLane on close.

**Comment by Zelldon** [comment]
Hm, I don't know I would like to have not again something which fails silently. I guess if we would follow real actor model it might make sense since we would retry at some point, but currently, we don't do that afaik.

From the interface side I would expect that everything which is submitted from outside the actor, #call should be used where we can then fail the resulting future. And if other methods are used, which not return a future we throw an exception. We could check then after implementing whether it fails somewhere already and iterator over it. Wdyt?

**Comment by oleschoenburg** [comment]
> Hm, I don't know I would like to have not again something which fails silently

Agreed, if we can get away with throwing then we should do it :+1:

**Comment by Zelldon** [comment]
Due to recent discussions https://camunda.slack.com/archives/C037RS2JHB8/p1660574327627559?thread_ts=1659692897.136569&cid=C037RS2JHB8

I will close this issue since we right now don't need that feature as it was planned. For example, for the StreamProcessor (where the feature was planned to be used) we still want to schedule some work. 

See also summary here https://camunda.slack.com/archives/C03HW6MG3Q9/p1660805629211279
