### ISSUE TITLE
Backport GitHub CI to stable/8.0 branch

### ISSUE THREAD

**Issue by menski** [camunda/zeebe#10009]
**Description**

In the `main` branch we migrated our CI from Jenkins to GitHub Actions. Right now other branches are still using Jenkins as CI. To align our CI and reduce the maintenance efforts we would like to also use GitHub Actions for our stable branch CI.

This issue is about backporting the GitHub CI to the `stable/8.0` branch.

blocking #9137 and #9138

**Comment by oleschoenburg** [comment]
I'll work on this once https://github.com/camunda/zeebe/pull/10616 is merged

**Comment by oleschoenburg** [comment]
nevermind, it's very difficult to merge stuff to stable/8.0 currently and backporting is easy enough to do right now.
