### ISSUE TITLE
Create ResultBuilder in Engine

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10003]
**Description**

blocked by https://github.com/camunda/zeebe/issues/10001

After the BufferedProcessingResultBuilder is finalized and we can create the ResultBuilder without LogStream dependencies, that means we can create the Builder in the Engine implementation and remove it from the StreamProcessor.

This allows us to remove the builder from the RecordProcessor interface and return only the Result. This should simplify the interface.

related to https://github.com/camunda/zeebe/issues/9998

**Comment by megglos** [comment]
@Zelldon unblocked?

**Comment by Zelldon** [comment]
Actually we can close this issue. This is no longer possible it was not expected in august that we need it like it currently is.

Short Explanation:

The ProcessingStateMachine need to create the ResultBuilder and pass it to the RecordProcessor, because we need to make sure that it has the RecordBatch limit check ( which is based on the maxMessageSize). To hide that mostly from the Engine, we create the ResultBuilder here https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/streamprocessor/ProcessingStateMachine.java#L246 and give it the RecordProcessor here https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/streamprocessor/ProcessingStateMachine.java#L261
