### ISSUE TITLE
MultiPartitionDeploymentLifecycleTest flaky

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#10029]
**Summary**

- How often does the test fail? once on main today; reproducible in IDEA with run until failure; failed after 40 runs 
- Does it block your work? yes
- Do we suspect that it is a real failure? unknown

Failure on mian: https://github.com/camunda/zeebe/runs/7725057586?check_suite_focus=true

Note: not reported as flaky test, because the slow tests are run just once.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>

java.lang.AssertionError: 
Actual and expected have the same elements but not in the same order, at index 6 actual element was:
  (COMPLETED, EVENT)
whereas expected element was:
  (COMPLETE, COMMAND)
</pre>
</details>

**Logs**

<details><summary>Logs</summary>
<pre>
14:57:14.225 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
14:57:14.325 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	[Partition] ['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
1 C DEPLOYMENT              CREATE       - #1->-1   -1 - 
1 E PROC                    CREATED      - #2->#1 P1K1 - process.bpmn -> "shouldR..ecovery" (version:1)
1 E DEPLOYMENT              CREATED      - #3->#1 P1K2 - process.bpmn
1 E DEPLOYMENT_DISTRIBUTION DISTRIBUTING - #4->#1 P1K2 - DeploymentDistributionRecord {"partitionId":2}
1 E DEPLOYMENT_DISTRIBUTION DISTRIBUTING - #5->#1 P1K2 - DeploymentDistributionRecord {"partitionId":3}
1 C DEPLOYMENT_DISTRIBUTION COMPLETE     - #6->-1 P1K2 - DeploymentDistributionRecord {"partitionId":2}
1 E DEPLOYMENT_DISTRIBUTION COMPLETED    - #7->#6 P1K2 - DeploymentDistributionRecord {"partitionId":2}
1 C DEPLOYMENT_DISTRIBUTION COMPLETE     - #8->-1 P1K2 - DeploymentDistributionRecord {"partitionId":3}
1 E DEPLOYMENT_DISTRIBUTION COMPLETED    - #9->#8 P1K2 - DeploymentDistributionRecord {"partitionId":3}
1 E DEPLOYMENT              FULLY_DISTR  - #10->#8 P1K2 - 
2 C DEPLOYMENT              DISTRIBUTE   - #1->-1 P1K2 - process.bpmn
2 E DEPLOYMENT              DISTR        - #2->#1 P1K2 - process.bpmn
3 C DEPLOYMENT              DISTRIBUTE   - #1->-1 P1K2 - process.bpmn
3 E DEPLOYMENT              DISTR        - #2->#1 P1K2 - process.bpmn

-------------- Deployed Processes ----------------------process.bpmn -> "shouldR..ecovery" (version:1)[P1K1] ------

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="definitions_ed5e2b12-8ee5-4993-8ce6-5eff773885ad" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="shouldReDistributeAfterRecovery" isExecutable="true">
    <startEvent id="startEvent_528d7228-e930-4f91-85c6-44d5f2f8d7f0">
      <outgoing>sequenceFlow_d5dc1800-c9cf-439a-be00-7210b122b40d</outgoing>
    </startEvent>
    <endEvent id="endEvent_f1626633-3788-4fba-afdf-0410efe713e2">
      <incoming>sequenceFlow_d5dc1800-c9cf-439a-be00-7210b122b40d</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_d5dc1800-c9cf-439a-be00-7210b122b40d" sourceRef="startEvent_528d7228-e930-4f91-85c6-44d5f2f8d7f0" targetRef="endEvent_f1626633-3788-4fba-afdf-0410efe713e2"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_413c3f86-8e51-4fba-8b5f-5382a5d81f95">
    <bpmndi:BPMNPlane bpmnElement="shouldReDistributeAfterRecovery" id="BPMNPlane_d9833812-57d2-42ad-91ae-2afde9eef45e">
      <bpmndi:BPMNShape bpmnElement="startEvent_528d7228-e930-4f91-85c6-44d5f2f8d7f0" id="BPMNShape_94735918-79a3-47e2-8286-a2a77c7a85d0">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_f1626633-3788-4fba-afdf-0410efe713e2" id="BPMNShape_cab6afd3-9863-4c43-805e-caa824dbd963">
        <dc:Bounds height="36.0" width="36.0" x="186.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_d5dc1800-c9cf-439a-be00-7210b122b40d" id="BPMNEdge_efc478f2-9a6c-4c47-a052-ef5bf91ba591">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

--------------- Decomposed keys (for debugging) -----------------
  -1 <-> -1
P1K1 <-> 2251799813685249
P1K2 <-> 2251799813685250

14:57:14.325 [] DEBUG io.camunda.zeebe.broker.logstreams - Close stream processor
14:57:14.325 [Broker-0-StreamProcessor-3] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-3.
14:57:14.343 [] DEBUG io.camunda.zeebe.broker.logstreams - Close stream processor
14:57:14.343 [Broker-0-StreamProcessor-2] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-2.
14:57:14.361 [] DEBUG io.camunda.zeebe.broker.logstreams - Close stream processor
14:57:14.361 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
14:57:14.379 [Broker-0-LogStream-3] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-3
14:57:14.380 [stream-3-write-buffer] DEBUG io.camunda.zeebe.dispatcher - Dispatcher closed
14:57:14.380 [Broker-0-LogStream-3] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-3 close 2 readers
14:57:14.380 [Broker-0-LogStream-2] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-2
14:57:14.380 [stream-2-write-buffer] DEBUG io.camunda.zeebe.dispatcher - Dispatcher closed
14:57:14.380 [Broker-0-LogStream-2] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-2 close 2 readers
14:57:14.380 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-1
14:57:14.380 [stream-1-write-buffer] DEBUG io.camunda.zeebe.dispatcher - Dispatcher closed
14:57:14.380 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-1 close 2 readers
14:57:14.380 [] DEBUG io.camunda.zeebe.broker.test - Clean up test files on path /tmp/junit17167369628247916039
14:57:14.380 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
14:57:14.380 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
14:57:14.380 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
14:57:14.381 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
14:57:14.381 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
14:57:14.382 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	[Partition] ['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
1 C DEPLOYMENT              CREATE       - #1->-1   -1 - 
1 E PROC                    CREATED      - #2->#1 P1K1 - process.bpmn -> "shouldR..ecovery" (version:1)
1 E DEPLOYMENT              CREATED      - #3->#1 P1K2 - process.bpmn
1 E DEPLOYMENT_DISTRIBUTION DISTRIBUTING - #4->#1 P1K2 - DeploymentDistributionRecord {"partitionId":2}
1 E DEPLOYMENT_DISTRIBUTION DISTRIBUTING - #5->#1 P1K2 - DeploymentDistributionRecord {"partitionId":3}
1 C DEPLOYMENT_DISTRIBUTION COMPLETE     - #6->-1 P1K2 - DeploymentDistributionRecord {"partitionId":2}
1 E DEPLOYMENT_DISTRIBUTION COMPLETED    - #7->#6 P1K2 - DeploymentDistributionRecord {"partitionId":2}
1 C DEPLOYMENT_DISTRIBUTION COMPLETE     - #8->-1 P1K2 - DeploymentDistributionRecord {"partitionId":3}
1 E DEPLOYMENT_DISTRIBUTION COMPLETED    - #9->#8 P1K2 - DeploymentDistributionRecord {"partitionId":3}
1 E DEPLOYMENT              FULLY_DISTR  - #10->#8 P1K2 - 
2 C DEPLOYMENT              DISTRIBUTE   - #1->-1 P1K2 - process.bpmn
2 E DEPLOYMENT              DISTR        - #2->#1 P1K2 - process.bpmn
3 C DEPLOYMENT              DISTRIBUTE   - #1->-1 P1K2 - process.bpmn
3 E DEPLOYMENT              DISTR        - #2->#1 P1K2 - process.bpmn

-------------- Deployed Processes ----------------------
process.bpmn -> "shouldR..ecovery" (version:1)[P1K1] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="definitions_ed5e2b12-8ee5-4993-8ce6-5eff773885ad" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="shouldReDistributeAfterRecovery" isExecutable="true">
    <startEvent id="startEvent_528d7228-e930-4f91-85c6-44d5f2f8d7f0">
      <outgoing>sequenceFlow_d5dc1800-c9cf-439a-be00-7210b122b40d</outgoing>
    </startEvent>
    <endEvent id="endEvent_f1626633-3788-4fba-afdf-0410efe713e2">
      <incoming>sequenceFlow_d5dc1800-c9cf-439a-be00-7210b122b40d</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_d5dc1800-c9cf-439a-be00-7210b122b40d" sourceRef="startEvent_528d7228-e930-4f91-85c6-44d5f2f8d7f0" targetRef="endEvent_f1626633-3788-4fba-afdf-0410efe713e2"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_413c3f86-8e51-4fba-8b5f-5382a5d81f95">
    <bpmndi:BPMNPlane bpmnElement="shouldReDistributeAfterRecovery" id="BPMNPlane_d9833812-57d2-42ad-91ae-2afde9eef45e">
      <bpmndi:BPMNShape bpmnElement="startEvent_528d7228-e930-4f91-85c6-44d5f2f8d7f0" id="BPMNShape_94735918-79a3-47e2-8286-a2a77c7a85d0">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_f1626633-3788-4fba-afdf-0410efe713e2" id="BPMNShape_cab6afd3-9863-4c43-805e-caa824dbd963">
        <dc:Bounds height="36.0" width="36.0" x="186.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_d5dc1800-c9cf-439a-be00-7210b122b40d" id="BPMNEdge_efc478f2-9a6c-4c47-a052-ef5bf91ba591">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

--------------- Decomposed keys (for debugging) -----------------
  -1 <-> -1
P1K1 <-> 2251799813685249
P1K2 <-> 2251799813685250

java.lang.AssertionError: 
Actual and expected have the same elements but not in the same order, at index 6 actual element was:
  (COMPLETED, EVENT)
whereas expected element was:
  (COMPLETE, COMMAND)
</pre>
</details>

**Comment by oleschoenburg** [comment]
Same as https://github.com/camunda/zeebe/issues/9964 I guess?

**Comment by pihme** [comment]
Yes. Why didn't I find this with the search :thinking:
