### ISSUE TITLE
Clarify DEAD state in Grafana dashboard

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#10043]
**Description**

The Grafana Zeebe Overview dashboard has a panel that shows the pod partition health.

A partition on a pod can be either HEALTHY, UNHEALTHY or DEAD. The HEALTHY and UNHEALTHY states are nicely described in text, but the DEAD state is marked as -1.

We should clarify this state using text in a similar fashion as the other states.

Mirrors https://github.com/camunda-cloud/zeebe-team/issues/14

**Comment by multani** [comment]
@korthout let me know if you need help with that :wave:

**Comment by korthout** [comment]
Thanks @multani, but I've already opened #10046. I just need to resolve the open discussions
