### ISSUE TITLE
Replace direct reset with buffered writers

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#10047]
**Description**

This is a follow-up of #10018. 

>Chris wants to remove the reset method altogether. And once we have the new implementation, which is based on buffered writers, the reset will no longer be necessary, as creating a new ProcessingResultBuilder will also create a new, empty buffer

See https://github.com/camunda/zeebe/pull/10018#discussion_r941259792

**Comment by menski** [comment]
@Zelldon is that something you would pick up while you are working on the buffered writers?

**Comment by Zelldon** [comment]
Yes @menski
