### ISSUE TITLE
Add new utility module specifically for QA tests

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10089]
**Description**

The QA module (and sub-modules) are meant to test the overall project as whole. They pull in most of it as dependencies, but should never be pulled in themselves. This allows us to test the project holistically (can you even say that? :smile:).

We currently have a `zeebe-test-util` module which is in used in various places in the project, including in the QA tests. In there, there are a few utilities which are specifically only used for QA. The downside here is that these QA-specific utilities are included in other sub-modules, and this could eventually introduce cyclical dependencies depending on the kind of utilities we wish to use.

For QA specific utilities, this is limitation is more of a burden than anything. I would propose we create a new module for QA utilities, move any existing ones there (such as QoL extensions to Testcontainers, actuator related utilities, etc.), and we can later expand and add new ones there as well (e.g. helpers when using `zeebe-process-test`, `zeebe-test-container`, etc.).

EDIT: It's also not straight-forward to just move them to a QA module, as we have both `zeebe-qa-update-tests` and `zeebe-qa-integration-tests`, and the utilities are used in both, and adding a dependency between them wouldn't make much sense (but is possible if we think it's worth avoiding adding a new module).

**Comment by Zelldon** [comment]
If they are only used in QA why not move them there? Do we need another module right now?

**Comment by npepinpe** [comment]
Because we have two modules in QA, and they are used in both.

**Comment by Zelldon** [comment]
Ok thanks that was not fully clear to me sorry :) 

I guess not.

**Comment by Zelldon** [comment]
So the proposal is to have the following structure?

```
qa:
\---utils
\---intergration-tests
\---upgrade-tests
```

If this is the case then count my vote for it :)
