### ISSUE TITLE
Remove environments from Dockerfile

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10104]
**Description**

Once we have Kubernetes 1.23+ in all the stages, it would be great to simplify our Dockerfile and remove the `APP_ENV` usage. We won't really need the development version of the image anymore since we will have access to ephemeral containers, letting us attach an image with all our utilities as a sidecar container of our production image.

**Comment by menski** [comment]
> Once we have Kubernetes 1.23+ in all the stages
Might not be needed for SaaS as we don't have the dev image there

We would only need to wait for our zeebe-io cluster. Until then we need this as a way to have the dev container available.

**Comment by megglos** [comment]
@npepinpe how should we best inform the whole team about this change, is everyone already familiar with ephemeral container usage?
Currently checking https://iximiuz.com/en/posts/kubernetes-ephemeral-containers myself.

**Comment by npepinpe** [comment]
I could do a short intro to ephemeral containers. I don't think there's enough to make a full techtalk (e.g. 1h of contents), but if there's no topic we could use that slot for a presentation.

**Comment by npepinpe** [comment]
I think anyway only Chris uses the dev image, so at the moment he would be the only one impacted

**Comment by npepinpe** [comment]
Of course, as you're doing this, you could also consider doing the intro to ephemeral containers yourself if you'd like :)

**Comment by megglos** [comment]
With the changes I tried debugging via ephemeral containers on a benchmark.

```
kubectl -n <ns> debug -it -c debugger --image=eclipse-temurin:17-jdk-focal <pod>
```

However the processes of the other containers are actually not visible 🙃 :
```
root@meg-10104-ephemeral-benchmark-zeebe-0:/# ps x
    PID TTY      STAT   TIME COMMAND
      1 pts/0    Ss     0:00 bash
     10 pts/0    R+     0:00 ps x
```

Thanks to [this](https://iximiuz.com/en/posts/kubernetes-ephemeral-containers/) I learned that this will require setting 
```
kind: Pod
spec:
  shareProcessNamespace: true
```
also see https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/ .

did that via
```
kubectl -n <ns> patch statefulset <deployment> --patch '
spec:
  template:
    spec:
      shareProcessNamespace: true'
```

which of course recreates all pods, bit interfering with debugging interests if we do that on demand 😅 

We thus would need to already set this flag with the initial deployment of the helm charts to be useful, would hesitate to merge https://github.com/camunda/zeebe/pull/10286 until this is done. We should at best first introduce this param to the helmchart to deploy it in a "debug" mode.

wdyt @npepinpe ?

**Comment by megglos** [comment]
With the changes I tried debugging via ephemeral containers on a benchmark.

```
kubectl -n <ns> debug -it -c debugger --image=eclipse-temurin:17-jdk-focal --target=zeebe <pod>
```

which resulted in 
```
Targeting container "zeebe". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
If you don't see a command prompt, try pressing enter.
root@meg-10104-ephemeral-benchmark-zeebe-0:/# ps x
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 tini -- /usr/local/bin/startup.sh
      7 ?        Sl     4:48 /opt/java/openjdk/bin/java -Xms128m -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8 -classpath /usr/local/zeebe/config:/usr/local/zeebe/lib/* -Dapp.name=b
    178 pts/0    Ss     0:00 bash
    187 pts/0    R+     0:00 ps x
```
