### ISSUE TITLE
Backup store can save snapshot files

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10110]
Snapshot files will be uploaded as objects under `checkpointId/partitionId/nodeId/snapshot/*`.

**Comment by oleschoenburg** [comment]
Simple `PutObject` request have a limit of 5GB per object, I'll have to check if that is a problem.

**Comment by oleschoenburg** [comment]
I'd like to use the `TransferManager` preview feature for that: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html

The reason is that this makes multi-part uploads very easy use. This is beneficial because it uses the available bandwidth more efficiently and frees us from worrying about file sizes.

@deepthidevaki I'm not sure who else to ask but could you give an opinion on using this preview feature? It's been in preview for 1 year so far, but supposedly almost finished now: https://github.com/aws/aws-sdk-java-v2/issues/37#issuecomment-1162060981. I'm not a fan of using it but I think it's stable enough for now.

I'll also have to double-check that this works with minio.

**Comment by deepthidevaki** [comment]
@oleschoenburg I think you could give it a try. According to this doc https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-upload-object.html it looks like convenient wrapper on top of the already existing low level api https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html . As far as I know this is already a long supported api. You could test it against minio just to check if it is also supported outside of AWS.

**Comment by oleschoenburg** [comment]
It appears like the TransferManager is not usable with locally running S3 clones because the underlying http client can't be configured properly, see https://github.com/aws/aws-sdk-java-v2/issues/2945

I think that's a dealbreaker for us so I'll just use the regular client with simple PUT requests and hope that no objects are over the maximum size :crossed_fingers:

**Comment by deepthidevaki** [comment]
> I think that's a dealbreaker for us so I'll just use the regular client with simple putObject requests and hope that no objects are over the maximum size crossed_fingers

Somewhere we are configuring maximum filesize in rocksdb. May be you can verify that to ensure that it is not bigger than what is supported in the backup.

Alternately, I think you can still use the low level multi-part upload api.

**Comment by Zelldon** [comment]
Isn't there a filesize limit of 2 gig (because of integer) in some filesystems? @oleschoenburg ? So we could restrict that already right?

**Comment by oleschoenburg** [comment]
That seems to be no longer the case: https://en.wikipedia.org/wiki/Large-file_support

In any case, as it depends on filesystem and OS, I think that's something we shouldn't restrict artificially.

**Comment by Zelldon** [comment]
I see no benefit in having such big files and I think it makes sense to be sometimes more restrictive since you can calculate with these limits at least. 

Related https://github.com/camunda/zeebe/issues/3014

**Comment by oleschoenburg** [comment]
Alright, we shortly discussed this and decided to not handle this for now. We can relatively safely assume that individual files won't be over 5GiB. If there were any, the backup would fail. Once the TransferManager is stable enough we can switch to that so that we would benefit from increased upload performance and automatic handling of multi-part uploads.
