### ISSUE TITLE
Zeebe cluster mode is deployed, but high availability is not achieved

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#10197]
When referring to this document https://github.com/camunda-community-hub/zeebe-docker-compose/blob/master/cluster/docker-compose.yml Deploy the Zeebe cluster, and the cluster newtopologyrequest result is
```
{
  "partitionsCount": 1,
  "replicationFactor": 2,
  "brokers": [
    {
      "partitions": [
        {
          "leader": true,
          "role": "LEADER",
          "partitionId": 1,
          "health": "HEALTHY"
        }
      ],
      "address": "10.0.1.114:26501",
      "port": 26501,
      "host": "10.0.1.114",
      "nodeId": 1,
      "version": "1.0.0"
    },
    {
      "partitions": [
        
      ],
      "address": "10.0.1.115:26501",
      "port": 26501,
      "host": "10.0.1.115",
      "nodeId": 2,
      "version": "1.0.0"
    },
    {
      "partitions": [
        {
          "leader": false,
          "role": "FOLLOWER",
          "partitionId": 1,
          "health": "HEALTHY"
        }
      ],
      "address": "10.0.1.116:26501",
      "port": 26501,
      "host": "10.0.1.116",
      "nodeId": 0,
      "version": "1.0.0"
    }
  ],
  "gatewayVersion": "1.0.0",
  "clusterSize": 3
}
```

When the leader node nodeid1 service is turned off, the cluster is unavailable。

**Comment by saig0** [comment]
@bugbugmaker note that the repository is achieved and deprecated. Instead, please have a look at https://github.com/camunda/camunda-platform and our [documentation](https://docs.camunda.io/docs/self-managed/platform-deployment/platform-8-deployment/).

Regarding the availability of the cluster, the replication count is set to `2`. In this configuration, the cluster is expected to be unavailable because it requires a majority of nodes to make progress. It is recommended to set the replication to `3`.

**Comment by bugbugmaker** [comment]
> @bugbugmaker note that the repository is achieved and deprecated. Instead, please have a look at https://github.com/camunda/camunda-platform and our [documentation](https://docs.camunda.io/docs/self-managed/platform-deployment/platform-8-deployment/).
> 
> Regarding the availability of the cluster, the replication count is set to `2`. In this configuration, the cluster is expected to be unavailable because it requires a majority of nodes to make progress. It is recommended to set the replication to `3`.

How to configure Zeebe when the number of nodes is fixed_ BROKER_ CLUSTER_ PARTITIONSCOUNT，ZEEBE_ BROKER_ CLUSTER_ Is there any standard or reference for replication factor?

**Comment by bugbugmaker** [comment]
> @bugbugmaker note that the repository is achieved and deprecated. Instead, please have a look at https://github.com/camunda/camunda-platform and our [documentation](https://docs.camunda.io/docs/self-managed/platform-deployment/platform-8-deployment/).
> 
> Regarding the availability of the cluster, the replication count is set to `2`. In this configuration, the cluster is expected to be unavailable because it requires a majority of nodes to make progress. It is recommended to set the replication to `3`.

How to configure Zeebe when the number of nodes is fixed_ BROKER_ CLUSTER_ PARTITIONSCOUNT，ZEEBE_ BROKER_ CLUSTER_ REPLICATIONFACTOR？ Is there any standard or reference?

**Comment by saig0** [comment]
Please have a look at the documentation: https://docs.camunda.io/docs/self-managed/platform-deployment/platform-8-deployment/

It describes how to set up Camunda 8 in a self-managed environment. If you have any problems then please reach out to the forum: https://forum.camunda.io/new. 

The GitHub issues should be mainly used for bug reports and feature requests. Questions and help requests are best placed in the forum.

**Comment by bugbugmaker** [comment]
> Please have a look at the documentation: https://docs.camunda.io/docs/self-managed/platform-deployment/platform-8-deployment/
> 
> It describes how to set up Camunda 8 in a self-managed environment. If you have any problems then please reach out to the forum: https://forum.camunda.io/new.
> 
> The GitHub issues should be mainly used for bug reports and feature requests. Questions and help requests are best placed in the forum.

Sorry, I don't have permission to camunda platform 8. I only have the Zeebe installation package and want to implement the Zeebe cluster deployment
