### ISSUE TITLE
`AbstractBackupStoreIT` tests are detected as duplicate test runs

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10254]
On Jenkins we run a script to detect duplicate test runs. The `S3BackupStoreIT` tests are abstract and run for two S3 implementations. This is then detected as duplicate runs which makes the Jenkins pipeline fail.

Open questions:
* Do we want to use the same script on GHA?
* Does failsafe handle this correctly so that one test run doesn't overwrite the other?

**Comment by megglos** [comment]
Triage:
Nicolas: should be add duplicate detection to GHA => YES
@npepinpe will create a follow-up issue
