### ISSUE TITLE
Migrate to managed prometheus and simplify test monitoring stack

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10257]
**Description**

We recently upgraded our monitoring stack in our testing clusters, and this highlighted some issues:

- We're several (> 10) versions behind the latest chart version
- Upgrading chart versions is tedious and time consuming
- The chart installs several components, making it complex to maintain: prometheus-operator, Grafana, Alertmanager, kube-state-metrics, a certificate manager, a TLS proxy, etc.

The proposal is to migrate to [managed prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus), which can be shared by all clusters, and we only have to deploy a single Grafana chart. This greatly simplifies our monitoring setup. No need to run upgrades except on Grafana, and no need to know about any other services than Grafana.

The biggest downside here is that managed Prometheus does not use the `ServiceMonitor` CRD, but instead uses a custom `PodMonitoring` CRD, which our charts are not compatible with :( See: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-servicemonitor

Part of this issue would be to figure out how we could solve this problem. Another part is to figure out if both teams are OK with data loss from previous benchmarks. It'll be so much easier to do this if we don't have to migrate our existing data.

I would propose we create everything fresh, but keep the old installations around for now for reference, and delete them in 30 days (which is our retention time in our existing Prometheus).

**Comment by oleschoenburg** [comment]
Another thing to keep in mind is that Grafana needs an authentication proxy to connect to the managed prometheus: https://cloud.google.com/stackdriver/docs/managed-prometheus/query#grafana-oauth

**Comment by megglos** [comment]
Triage: Cost/Benefit needs to be evaluated. 5 sequential updates took 2h done by Nicolas.
In the past the old prometheus operator was e.g. blocking a k8s update.
SaaS is using newer versions already.

**Comment by Zelldon** [comment]
@npepinpe I think we can close this?

**Comment by npepinpe** [comment]
Yes, it's done :+1:
