### ISSUE TITLE
RandomizedRaftTest.consistencyTestWithSnapshot failed with IllegalStateException

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#10256]
**Summary**

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.IllegalStateException: Expected to delete index after 195, but it is lower than the commit index 305. Deleting committed entries can lead to inconsistencies and is prohibited.
	at io.atomix.raft.storage.log.RaftLog.deleteAfter(RaftLog.java:187)
	at io.atomix.raft.roles.PassiveRole.replaceExistingEntry(PassiveRole.java:623)
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:562)
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:514)
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:370)
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:50)
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:187)
</pre>
</details>

**Hypotheses**

- This is a bug in the test setup. The compaction is not done in the raft thread context. This violates some ordering assumptions we have in raft regarding when snapshot listener is invoked and when the log is compacted. Raft learns about the new snapshot via SnapshotListener which is asynchronously called after a snapshot is committed. In production, the compaction is also scheduled on the raft thread, which will be executed on the raft thread after the snapshot listener is executed. But, in the test we compacted immediately after the snapshot is committed, but before the listener is executed in raft thread.

**Logs**

https://github.com/camunda/zeebe/runs/8134617288?check_suite_focus=true  

Was able to reproduce the failure with seed="-3302510092818335244"

<details><summary>Relevant logs that may explain the issue</summary>
<pre>

12:05:14.485 [] INFO  io.atomix.raft.RandomizedRaftTest - Take snapshot on 0
12:05:14.485 [] INFO  TEST - Snapshot taken at index 195. Current commit index is 196
12:05:14.485 [] DEBUG io.camunda.zeebe.journal.file.SegmentsManager - No segments can be deleted with index < 195 (first log index: 105)

12:05:14.510 [] INFO  io.atomix.raft.RandomizedRaftTest - Take snapshot on 0
12:05:14.510 [] INFO  TEST - Snapshot taken at index 668. Current commit index is 795
12:05:14.510 [] DEBUG io.camunda.zeebe.journal.file.SegmentsManager - atomix - Deleting log up from 105 up to 521 (removing 5 segments)

12:05:14.514 [] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{0-partition-1} - Received AppendResponse{status=OK, term=15, succeeded=false, lastLogIndex=389, lastSnapshotIndex=304} from 1
12:05:14.514 [] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{0-partition-1} - Reset next index for RaftMemberContext{member=1, term=15, configIndex=0, snapshotIndex=304, nextSnapshotIndex=0, nextSnapshotChunk=null, matchIndex=305, heartbeatTime=1662033914481, appending=0, appendSucceeded=false, appendTime=1662033914489, configuring=false, installing=false, failures=0} to 390
12:05:14.514 [] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{0-partition-1} - Sending AppendRequest{term=15, leader=0, prevLogIndex=195, prevLogTerm=4, entries=179, commitIndex=795} to 1

12:05:14.519 [] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Received AppendRequest{term=15, leader=0, prevLogIndex=195, prevLogTerm=4, entries=179, commitIndex=795}
12:05:14.519 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1-partition-1} - Found leader 0
12:05:14.519 [] TRACE io.atomix.raft.impl.RaftContext - RaftServer{1-partition-1} - Set leader 0
java.lang.IllegalStateException: Expected to delete index after 195, but it is lower than the commit index 305. Deleting committed entries can lead to inconsistencies and is prohibited

</pre>
</details>

Here, after reset the next index, the previous index is determined from an older snapshot (=195). Although there is already a new snapshot.

**Comment by megglos** [comment]
I also encountered this with the seed `6855894370710051590`
