### ISSUE TITLE
Zeebe broker can restore from a backup

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#10263]
- User can specify which backup to restore from
- A broker restores all partitions that it should replicate from the specific backup
- Whether restore is successful or failed must be observable
- After a restore is successful, the broker data directory must contains the restored data.

Restore process is specified in [ZEP.](https://github.com/zeebe-io/enhancements/blob/master/ZEP008-hot-backup.md#on-restore)

**Comment by deepthidevaki** [comment]
Option 1:
- A new application similar to StandaloneBroker and StandaloneGateway will be provided for restore
- User must run this application on every broker node with the same config as the broker.
- Application must be run before a zeebe broker is started.
- This application will download the given backup and restores the states to the configured data directory.
- It restores state of all partition that the broker should replicate as specified in the configuration.

Option 2:
- Zeebe exposes a rest endpoint to restore from a backup
- User can restore the cluster while it is running
- Once the restore is completed, cluster continues processing with the restored state.

Although Option 2 is more user friendly, it is quite complex to implement. We must ensure that the broker is not processing while restoring. The brokers must also coordinate to ensure that all brokers successfully restored from the backup before it can continue processing. If some brokers succeed and some failed, it might end up in an inconsistent state.

We could provide something like Option 2 eventually. But for now I suggest to go with Option 1, where coordinating restore in a cluster is a manual process. The users must restore each broker individually and ensure that all brokers have restores before starting the cluster.

**Comment by npepinpe** [comment]
What about a flag to start Zeebe itself in restore mode, such that before it starts, it first restores from backup? There's also two options there, i.e. 1) restore, then start, or 2) restore, then stop (and await manual restart without flag)

The downside with a restore command where you auto start after is that it's dangerous, the user has to remember to remove the extra flag or something to avoid restarts causing a new restore (and thus data loss).

Anyway, I think option 1 is probably best for now. I'm a bit unsure about how to implement it best, but I assume you already have some thoughts :)

**Comment by deepthidevaki** [comment]
> The downside with a restore command where you auto start after is that it's dangerous, the user has to remember to remove the extra flag or something to avoid restarts causing a new restore (and thus data loss).

Yes. This would be a problem. Especially, if it restore and then continue. We wouldn't know when it restarts next time.

> 2) restore, then stop (and await manual restart without flag)

This would be similar to first running a restore application, and then start zeebe.

**Comment by deepthidevaki** [comment]
So, we will go with first solution, where there will be a standalone restore app which users must run on all brokers. 

- [ ] A restore service that can restore a single partition. This would be similar to `BackupService` which manages everything related to restoring the backup of one partition to one broker. This will be the core of the restore process. It find a valid backup, downloads it to the brokers data directory and reset the log to the checkpoint position.
- [ ] Another service that manages restoring all partitions that are owned by this broker. It finds which partitions need to restored based on the cluster configuration, and restores all of them.
- [ ] Package all of them into a standalone app
