### ISSUE TITLE
Detect duplicate test runs in GHA

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10260]
**Description**

In our Jenkins pipeline, we had an extra step to detect duplicate test runs. This was added because we root caused corrupted test reports to being due to the same tests being ran twice in parallel. It would be useful to keep this check to ensure this never happens again, at least while we're running multiple test engines as well.

**Comment by megglos** [comment]
Decided to work on it as @megglos is learning about the CI anyway.

**Comment by megglos** [comment]
encountered f[alse-positive](https://github.com/camunda/zeebe/pull/10389) and the fact that tee swallowed the maven exit
