### ISSUE TITLE
Remove the additional submit

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10291]
**Description**

In the ProcessingScheduleServiceImpl we have a method, [which submits a task to our scheduling queue](https://github.com/camunda/zeebe/blame/main/engine/src/main/java/io/camunda/zeebe/streamprocessor/ProcessingScheduleServiceImpl.java#L71) (before it will be really submitted, like for run delayed).

This is somehow unexpected and can cause race conditions (it will slow down the execution). It looks like it was added only for testability https://github.com/camunda/zeebe/commit/f99a9a46a0c32eba51d0b5d3942a7014d6243209 But we can achieve this also differently, by using an Actor in our tests.

**Comment by megglos** [comment]
@Zelldon is this a potential regression?

We put it into ready/upcoming so we clarify the urgency within the next two weeks.
