### ISSUE TITLE
ZeebeDbInconsistentException INCIDENT_JOBS already exists

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#10309]
**Describe the bug**

An error was reported indicating that 1 of 3 partitions (partition 2) is marked as DEAD, due to a consistency check that safeguards against corrupted data. This is likely due to a bug.

The impact is that all processing on that partition stops, and all process instances on that partition can no longer make progress. Instances on the partitions are unaffected.

The reported error was:

> Broker-2-StreamProcessor-2 failed, marking it as dead: Broker-2-StreamProcessor-2{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{4503599721837837}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda$1437/0x00000008014656c8@4febef84] in ColumnFamily INCIDENT_JOBS already exists, cause=null]}

The specific case has been resolved by disabling the consistency check and allowing the additional incident to be written for the job. However, the root cause has not been resolved.

**To Reproduce**

- unclear at this time

**Expected behavior**

Only a single incident should exist for a job at any time

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2022-09-08 13:28:35.272 CEST
zeebe
Received new exporter state {elasticsearch=194625463, MetricsExporter=194625463}
2022-09-08 13:28:38.649 CEST
zeebe
Received new exporter state {elasticsearch=189124268, MetricsExporter=189124268}
2022-09-08 13:28:38.649 CEST
zeebe
Received new exporter state {elasticsearch=189124268, MetricsExporter=189124268}
2022-09-08 13:28:40.758 CEST
zeebe
Actor Broker-1-StreamProcessor-2 failed in phase STARTED.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.761 CEST
zeebe
Broker-1-StreamProcessor-2 failed, marking it as dead: Broker-1-StreamProcessor-2{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{4503599721837837}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda$1445/0x000000080146f118@1b83e0ac] in ColumnFamily INCIDENT_JOBS already exists, cause=null]}
2022-09-08 13:28:40.764 CEST
zeebe
Detected 'DEAD' components. The current health status of components: [ZeebePartition-2{status=HEALTHY}, Broker-1-Exporter-2{status=HEALTHY}, raft-partition-partition-2{status=HEALTHY}, Broker-1-LogStream-2{status=HEALTHY}, Broker-1-SnapshotDirector-2{status=HEALTHY}, Broker-1-StreamProcessor-2{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{4503599721837837}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda$1445/0x000000080146f118@1b83e0ac] in ColumnFamily INCIDENT_JOBS already exists, cause=null]}]
2022-09-08 13:28:40.835 CEST
zeebe
Transition to INACTIVE on term 5 requested.
2022-09-08 13:28:40.836 CEST
zeebe
Partition-2 failed, marking it as dead: Broker-1-ZeebePartition-2{status=DEAD, issue=HealthIssue[message=null, throwable=null, cause=null]}
```

</p>
</details>

**Environment:**
- Instance: `807c46c7-9459-4ac8-bacb-e71c45d9e897`
- Zeebe Version: 8.0.5
- Configuration: G3-Trial cluster

**Comment by korthout** [comment]
Lowering the severity to high, because inconsistency checks are enabled by default. On SaaS we have it enabled, but we can re-act on it and have a workaround for this specific case in place (i.e. temporarily disable the check).

**Comment by korthout** [comment]
We expect that this is the root cause:
- https://github.com/camunda/zeebe/issues/10308

**Comment by korthout** [comment]
To find the root cause, please analyse the relevant data https://github.com/camunda-cloud/team-sre/issues/204

**Comment by deepthidevaki** [comment]
Occured again in 8.1.2 
```
io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{6755399459364280}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda$1558/0x000000080147a300@40f43a14] in ColumnFamily INCIDENT_JOBS already exists
```
[logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-28T15:10:08.398660410Z;pinnedLogId=2022-10-28T15:10:08.398660410Z%2Fpb3opmoja2saorg1;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.namespace_name%3D%22127b23b9-2e94-42e9-bf29-20e506998ffe-zeebe%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Atimestamp%3D%222022-10-28T15:10:08.398660410Z%22%0AinsertId%3D%22pb3opmoja2saorg1%22;timeRange=2022-10-28T14:40:38.399Z%2F2022-10-28T15:40:38.399Z?project=camunda-cloud-240911)

**Comment by saig0** [comment]
@oleschoenburg we assume that the issue is caused by #10308. We plan to work on the issue soon. :+1:

**Comment by Zelldon** [comment]
Happened again https://console.cloud.google.com/monitoring/alerting/incidents/0.mp9s8mf5qia4?project=camunda-cloud-240911

**Comment by deepthidevaki** [comment]
A cluster on version 8.0.4 affected by this bug is updated to 8.1.5. But the partition is still dead after the update. Is that expected?

**Comment by korthout** [comment]
This issue was about multiple incidents being created for the same job.

Thanks to
- #11109 

the root cause of this issue has been resolved, and this issue should no longer pop up in the future. However, for existing cases, it changes nothing. 

A workaround is to temporarily disable the consistency checks. A backup is recommended to make sure it does not lead to actual inconsistencies.
