### ISSUE TITLE
Add 'Docker checks' to bors required checks

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10301]
**Description**

We recently added some Docker checks to our code quality workflow. This should be added to the checks required by bors to merge, as this is important for any PR which ends up modifying the Docker image.

**Comment by npepinpe** [comment]
@megglos this is something you might be interested in as you did the latest changes, and it gets you a bit more into our CI (e.g. Docker linting, how bors interacts with our CI, etc.)

To change the bors checks, you need to do this via the `.bors.toml` file in the root of the project. If you have any questions, you can ask me or korthout about it.

**Comment by megglos** [comment]
docker checks are already part of Test Summary which is checked by bors
