### ISSUE TITLE
Automate the update of the base image digest in the Dockerfile

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#10304]
**Description**

Since https://github.com/camunda/zeebe/commit/9c4fb57516fe1720561d45abcdabbe0abc0b978f the base image digest is pinned in order to have reproducible docker builds.
To update the image manually created update PRs are needed as of now.
This should get automated with suitable tooling like dependabot or renovate going forward.

Hint:
The identity team already did that using [renovate](https://github.com/camunda-cloud/identity/pull/97).

**Comment by megglos** [comment]
Setting up Snyk first would be more urgent to be aware of issues first.
Put this into the backlog as it's not urgent to autmate but more urgent to setup vulnerability detection.

Putting to backlog for now.

**Comment by korthout** [comment]
Having seen [this older issue](https://github.com/dependabot/dependabot-core/issues/2962), I think Dependabot can also do this if we have the dependency already pinned to a hash. Note that Dependabot [does not support upgrading from version pinning to hash pinning automatically](https://github.com/dependabot/dependabot-core/issues/3699)

**Comment by megglos** [comment]
@megglos link the pending holisticon PR that might conflict again one this is done

**Comment by menski** [comment]
I would also be interested that we resolve this issue, as of now we are receiving more and more CVE requests, which are "automatically" resolving in other projects which are not pinning the image, and are not requiring manual effort on Zeebe to keep the base image updated.

**Comment by oleschoenburg** [comment]
We now define the digests as args: https://github.com/camunda/zeebe/blob/4f32709181f7b5c9f98af902e8ce91ffff01de9c/Dockerfile#L4-L5

I don't think either renovate or dependabot support this atm. @megglos Do you remember if there were any alternatives to defining the digests as args or was this the only way we could make it work?

**Comment by megglos** [comment]
identity actually does the same and it [seems renovate can deal with it](https://github.com/camunda-cloud/identity/commit/03bdeeb945ec8413019431e55faa4c56ceb6e398)

**Comment by oleschoenburg** [comment]
Thanks, that makes it easy :+1:

**Comment by oleschoenburg** [comment]
Renovate is enabled for this repo now, waiting for the onboarding PR.

**Comment by megglos** [comment]
@oleschoenburg can this be closed now?
