### ISSUE TITLE
Using modification, I can't get the right loopCounter if a parallel multi instance user task was triggered

### ISSUE THREAD

**Issue by skayliu** [camunda/zeebe#10396]
**Describe the bug**

When using modification modify a multi-instance, I get the wrong loopCounter

**To Reproduce**
1、Set the multi-instance input collection `assigneeList` for `["demo1","demo2"]`, then we get the max loopCounter is **2**.

2、Run the below code, then we get the another max loopCounter is **3**.
`
final Map<String, Object> vars = new HashMap<>();
final List<String> list = new ArrayList<>();
    list.add("demo3");
    list.add("demo4");
    list.add("demo5");
    vars.put("assigneeList",list);
    zeebeClient.newModifyProcessInstanceCommand(task.getProcessInstanceKey())
            .activateElement(task.getElementId())
            .withVariables(vars,task.getElementId())
            .send()
            .join();`

![2022-09-19_155450](https://user-images.githubusercontent.com/26370117/190973140-ec7db7d6-da71-48b1-9ec6-c6fe07ea4371.png)

**Expected behavior**

In this test case, we should get the max loopCounter is **5**.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS:  Linux
- Zeebe Version: 8.1-alpha5
- Configuration:

**Comment by saig0** [comment]
@skayliu thank you for reporting. :+1: 

The behavior is expected. Let's have a deeper look at the processing of the modification command:
1. it writes an `activate` command for the multi-instance use task
2. it updates the variable `assigneeList` and sets it to `["demo3", "demo4", "demo5"]`

As a result, the process instance creates a new instance of the multi-instance user task with the updated input collection. The input collection contains 3 elements. So, the process instance creates 3 inner instances of the user task. 

Keep in mind that the modification creates a **new instance** of the multi-instance but doesn't modify the existing one. And the input collection contains only 3 elements. 

Does this make sense for you?

**Comment by skayliu** [comment]
@saig0 thank you for explaination, I got it.

Here is my question,  you can look up at the code, I didn't add `.terminateElement(task.getElementInstanceKey())`,
What if we don't add '.terminateElement(task.getElementInstanceKey())', can it do the update way?  so that we can add others to do approval purpose. If add this, then do the way you said.
I want it do the same way as C7 does, especially for the multi-instance use task.

**Comment by saig0** [comment]
Modifying an active multi-instance (like it is described [here](https://docs.camunda.org/manual/7.17/user-guide/process-engine/process-instance-modification/#modify-multi-instance-activity-instances)) is currently not possible. This feature was not part of our initial scope.

With version `8.1`, we can only terminate the multi-instance activity and activate a new instance of the multi-instance activity. So, starting the whole multi-instance again, for example, with an updated input collection.

**Comment by menski** [comment]
As discussed this is expected behavior at the moment, therefore we are closing this issue.
