### ISSUE TITLE
ActorFrameworkIntegrationTest causes SIGSEG

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10407]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far
- Does it block your work? not sure
- Do we suspect that it is a real failure? kind of

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 s - in io.camunda.zeebe.dispatcher.AtomicPositionTest
[INFO] Running io.camunda.zeebe.dispatcher.integration.ActorFrameworkIntegrationTest
Aborted (core dumped)
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
Warning:  Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/zeebe/zeebe/dispatcher/target/surefire-reports/2022-09-20T07-11-50_009-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.263 s
[INFO] Finished at: 2022-09-20T07:12:12Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project zeebe-dispatcher: 
Error:  
Error:  Please refer to /home/runner/work/zeebe/zeebe/dispatcher/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/home/runner/work/zeebe/zeebe/dispatcher' && '/usr/lib/jvm/temurin-17-jdk-amd64/bin/java' '-javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/home/runner/work/zeebe/zeebe/dispatcher/target/jacoco.exec' '-jar' '/home/runner/work/zeebe/zeebe/dispatcher/target/surefire/surefirebooter-20220920071152080_3.jar' '/home/runner/work/zeebe/zeebe/dispatcher/target/surefire' '2022-09-20T07-11-50_009-jvmRun1' 'surefire-20220920071152080_1tmp' 'surefire_0-20220920071152080_2tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.dispatcher.integration.ActorFrameworkIntegrationTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/home/runner/work/zeebe/zeebe/dispatcher' && '/usr/lib/jvm/temurin-17-jdk-amd64/bin/java' '-javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/home/runner/work/zeebe/zeebe/dispatcher/target/jacoco.exec' '-jar' '/home/runner/work/zeebe/zeebe/dispatcher/target/surefire/surefirebooter-20220920071152080_3.jar' '/home/runner/work/zeebe/zeebe/dispatcher/target/surefire' '2022-09-20T07-11-50_009-jvmRun1' 'surefire-20220920071152080_1tmp' 'surefire_0-20220920071152080_2tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.dispatcher.integration.ActorFrameworkIntegrationTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:714)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:[165](https://github.com/camunda/zeebe/actions/runs/3088106271/jobs/4994204500#step:5:166))
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
</pre>
</details>

**Hypotheses**

I think it is related to freeing again the internal dispatcher buffer, which was introduce with https://github.com/camunda/zeebe/pull/10381. The test might access still an buffer, which was already freed.

> List any hypotheses if you have one; can be ommitted

**Logs**

[hs_err_pid1970.log](https://github.com/camunda/zeebe/files/9605180/hs_err_pid1970.log)

**Comment by npepinpe** [comment]
I think I know why this happened. We replaced `runUntilDone` with submits in that test' classes, and they weren't written to handle this. So when a job is re-submitted, it's possible the the `BlockPeek` it's submitted with points to a freed buffer.

**Comment by oleschoenburg** [comment]
Looks like it happened again: https://github.com/camunda/zeebe/actions/runs/3272388341/jobs/5383333737
This time the stack trace is slightly different but similar enough that I suspect it's the same issue.

[hs_err_pid6188.log](https://github.com/camunda/zeebe/files/9809330/hs_err_pid6188.log)

**Comment by npepinpe** [comment]
I think I have some idea of what's happening.

When the dispatcher is closed, it closes the subscriptions. The subscriptions' close mechanism is simply a volatile boolean. If the poll task was already enqueued before the dispatcher was closed, then it's possible that it read that `isClosed` flag right before it is set to true by the dispatcher close. At which point, it may try to read from the freed buffer, depending on thread scheduling.

To prevent this, the subscription has to "lock" on its buffer while it's consuming it, or vice-versa, the subscription has to be locked while it's closing.

It's unclear if this could be a problem in production.

**Comment by npepinpe** [comment]
We can see when the actor task is closed, then signaling via the condition should do nothing, as it's scheduling state would be `TERMINATED`.

```java
  public boolean tryWakeup() {
    boolean didWakeup = false;

    if (casState(TaskSchedulingState.WAITING, TaskSchedulingState.WAKING_UP)) {
      resubmit();
      didWakeup = true;
    }

    return didWakeup;
  }
```

**Comment by npepinpe** [comment]
Copied from the PR:

We didn't fully root cause the issue, as from what we gather, the dispatcher should be closed only when all actors are closed, which means the `Consumer#consume` method should never be called after the dispatcher is closed.

It's a bit hard to say that's true with 100% certainty with how complex the scheduling is, and all the possible race conditions, so for now I added a wrapper in the consume method and more logging. If this occurs again, then we have more info.

In the meantime, possibly we replace the dispatcher with something much simpler, so this can then be closed at that time.

I'll put this back in the backlog and unassign myself. We should close this either when find a bug in the scheduler (and then create a new issue) or when we replace the dispatcher.

**Comment by megglos** [comment]
closing as stale

**Comment by berkaycanbc** [comment]
We faced with a similar issue in one of our builds.

<details><summary>Stacktrace</summary>
<pre>
io.camunda.zeebe.engine.processing.bpmn.subprocess.InterruptingEventSubprocessTest
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:456)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:358)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:296)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1203)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1055)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:871)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
</pre>
</details>

Logs:
[unit_tests.txt](https://github.com/camunda/zeebe/files/11771136/1_Unit.tests.txt)

@megglos

**Comment by oleschoenburg** [comment]
@berkaycanbc Usually this would definitely require a new issue. However, I'm 99% sure that this is related to an issue that @korthout is currently looking into and creating a GH issue for. So no need to create one now.

**Comment by korthout** [comment]
The issue is:
- #13164
