### ISSUE TITLE
Allow configuring the max message size of the gateway

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10417]
**Description**

We currently have a configuration option for the max message size on the broker side. This is helpful for users who want to deploy large processes/DMN models. Unfortunately, there is a limit in the gRPC gateway of 4MB, and this is not currently configurable. So in a sense, from a user point of view, configuring the max broker message size doesn't do what it should do.

As a user, I would expect that I can configure both such that, if I choose to deploy a 50MB process, I can.

**Comment by megglos** [comment]
Put into ready as low hanging fruit and to avoid issues resulting of users changing the mac message side on the broker.
