### ISSUE TITLE
After restore, a completed backup is marked as failed

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#10430]
**Describe the bug**

Observed this behavior when testing restore: 
After restore, the backup service attempt to take the backup  with the same id (from which it restored from). Since the backup already exists, backup store throws an exception and marks it as failed(?). 

**To Reproduce**

`BackupTest` added in #10412 can reproduce this. The test does not fail, but it logs a bunch of exception.

**Expected behavior**

1. After a restore, BackupService should not attempt to take the same backup again.
2. BackupStore should not mark a completed backup as failed.

**Comment by oleschoenburg** [comment]
>Since the backup already exists, backup store throws an exception and marks it as failed(?).

Ouch, that's my bad. Good that you found it now :+1: 

https://github.com/camunda/zeebe/blob/8a9f8406cadf0110aaa28d0221cc0d8fc7004809/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/S3BackupStore.java#L173-L177

This error handling is too generic and we should bail out early if the backup status is not `DOES_NOT_EXIST` at the start of taking a backup.
