### ISSUE TITLE
Recurring failing builds due to maven connection timeouts

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10447]
**Description**

It happens semi-frequently that our builds fail because in one or more jobs, maven timed out fetching dependencies from Maven repository.

From looking around, it seems there are some known issues with:

1. [maven with GitHub hosted runners](https://github.com/actions/runner-images/issues/1499)
2. [maven generally on Azure VMs](https://issues.apache.org/jira/browse/WAGON-486)

Several projects have tried different approaches to fix it, but most boil down to the following:

1. Use a pull-through cache/mirror (e.g. Nexus)
2. Configure Wagon (the Maven transport) with appropriate retries, timeouts, disabling/minimizing pooling, and reducing keep alive

There also seems to be reports on macOS specifically of some issues without network time outs in general (note: the macOS VMs do not run on Azure but on in a special data center, I don't know much more but they are definitely different than the others which simply run on Azure).

## Examples:

- [Apache Pulsar CI](https://github.com/apache/pulsar/blob/3d47ee8ab6a2d39017413b21160a21067cf7439b/.github/workflows/pulsar-ci.yaml#L32)
- [Apache IoTDB](https://github.com/apache/iotdb/blob/0d65058b359fc0dccb0ff030e6cfc9be25c7a9d2/.github/workflows/main-unix.yml#L29)
- [Apache Linkis](https://github.com/apache/incubator-linkis/blob/5a5efe117a2f180f431a6aeca2c10719802c89ac/.github/workflows/build-backend.yml#L23)
- [macOS network tuning](https://github.com/actions/runner-images/issues/1187#issuecomment-778503839)

## Context
- [Maven HTTP Tuning Guide](https://maven.apache.org/guides/mini/guide-http-settings.html)
- [Maven Wagon Configuration](https://maven.apache.org/wagon/wagon-providers/wagon-http/)

**Comment by npepinpe** [comment]
Is this still happening with the self hosted runners? I assume not, actually. Should we close this?

**Comment by npepinpe** [comment]
I'm leaving this opened for now, as this might still be an issue on the smoke tests (e.g. mac and windows), but it's much less of an issue, but we can decide in the next planning meeting if we just close it.

**Comment by menski** [comment]
Closing for now after the move to self-hosted runners. We didn't observed this problem for a while.
