### ISSUE TITLE
`BackupService#failInProgressBackup` should use `BackupStore#list`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10444]
**Describe the bug**

Similar to #10380, marking a backup as failed should mark all backups with matching checkpoint and partitionId as failed, not just one from the current broker.

Consider https://github.com/camunda/zeebe/pull/10432#discussion_r977407280 and https://github.com/camunda/zeebe/pull/10432#discussion_r977314896 when implementing this.

**Comment by deepthidevaki** [comment]
It already does that, but it is not using the `list`, instead iterating over all broker ids.
