### ISSUE TITLE
`ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries` is flaky

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10487]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? At least once
- Does it block your work? 
- Do we suspect that it is a real failure? Maybe?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Verification in order failure</summary>
<pre>
Error:  Failures: 
Error:    ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries:277 
Verification in order failure
Wanted but not invoked:
logEntryBuilder.key(2L);
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries(ProcessingScheduleServiceTest.java:277)
Wanted anywhere AFTER following interaction:
logStreamBatchWriter.event();
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$4(ProcessingScheduleServiceImpl.java:159)
</pre>
</details>

See https://github.com/camunda/zeebe/actions/runs/3127245149/jobs/5073659606

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by Zelldon** [comment]
Looking into it

**Comment by Zelldon** [comment]
I run it now 1,300 times and it hasn't failed :smiling_face_with_tear:

**Comment by oleschoenburg** [comment]
Happened again: https://github.com/camunda/zeebe/actions/runs/3128063833/jobs/5075430308

**Comment by Zelldon** [comment]
[io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.txt](https://github.com/camunda/zeebe/files/9646908/io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.txt)
[io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest-output.txt](https://github.com/camunda/zeebe/files/9646909/io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest-output.txt)

**Comment by Zelldon** [comment]
The log is hard to read, since all tests are printed in the same file :smiling_face_with_tear: 

Looks like that the second timer is not executed which would speak for #10306 OR it is scheduled during not open phase (which we see in the log), but I'm not sure whether it is from another test case.

**Comment by Zelldon** [comment]
I think this is fixed by https://github.com/camunda/zeebe/pull/10557 please reopen if it occurs again.
