### ISSUE TITLE
Auto merge fails because of unexpected check outcome

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10503]
**Description**

The auto merge for dependabot fails with:

```
CodeQL: completed (neutral)
Java checks: completed (success)
Go linting: completed (success)
CodeQL: completed (success)
Docker checks: completed (success)
The conclusion of one or more checks were not allowed. Allowed conclusions are: success, skipped. This can be configured with the 'allowed-conclusions' param.
```

https://github.com/camunda/zeebe/actions/runs/3132750067/jobs/5085412200

**Comment by megglos** [comment]
There is an issue with CodeQL as it runs part of the deploy and test workflow. @oleschoenburg already has an idea on how to fix it.

**Comment by megglos** [comment]
Alternative: Instead of fixing the CodeQL issue it would also be fine for the auto merge to allow `neutral`
