### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Collector already registered that provides name: zeebe_elasticsearch_exporter_flush_duration_seconds_count

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#10511]
2022-09-27 16:17:19.548 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO
      io.camunda.zeebe.processor - Processor finished reprocessing at event position 73
Exception in thread "Broker-0-zb-fs-workers-9" java.lang.ExceptionInInitializerError
        at io.camunda.zeebe.exporter.ElasticsearchClient.index(ElasticsearchClient.java:86)
        at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:83)
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:151)
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:138)
        at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:425)
        at io.camunda.zeebe.util.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51)
        at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73)
        at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39)
        at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)
        at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94)
        at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78)
        at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191)
Caused by: java.lang.IllegalArgumentException: Collector already registered that provides name: zeebe_elasticsearch_exporter_flush_duration_seconds_count
        at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
        at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:259)
        at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:251)
        at io.camunda.zeebe.exporter.ElasticsearchMetrics.<clinit>(ElasticsearchMetrics.java:21)
        ... 12 more

**Comment by npepinpe** [comment]
Can you provide more information on how you ran into this? This can happen if you stop/start the application within the same JVM instance, as the collectors are registered statically. From your stack trace, it looks like the broker was starting - were you running it before, or any other instance, or any other Spring Boot or Micrometer applications in the same JVM?

**Comment by npepinpe** [comment]
To clarify, the steps to reproduce are:

1. Configure Elasticsearch exporter in the brokers
2. Generate some data (e.g. deploy a process, start an instance, etc.)
3. Manually delete the indices in Elasticsearch
4. Generate more data (causing more exports)

Can you confirm this? I tried it and nothing happened. 

- Which version of Zeebe are you using?
- Are you restarting Zeebe at any point in between?
- How are you deploying Zeebe - using the official Docker image, or bare metal via the TAR ball or JAR? If bare metal, which JVM are you running?

Regarding the error itself: the collector is registered when the class is initially loaded (the `ElasticsearchMetrics` class). That's done once, the first time an Elasticsearch exporter instance is created and used. So it seems unlikely for this to happen at any other time than when the exporter is initially loaded at start up.

That said, I'm not dismissing it, but it's important to know exactly how to reproduce it so we can figure out what went wrong.

**Comment by bugbugmaker** [comment]
> To clarify, the steps to reproduce are:
> 
> 1. Configure Elasticsearch exporter in the brokers
> 2. Generate some data (e.g. deploy a process, start an instance, etc.)
> 3. Manually delete the indices in Elasticsearch
> 4. Generate more data (causing more exports)
> 
> Can you confirm this? I tried it and nothing happened.
> 
> * Which version of Zeebe are you using?
> * Are you restarting Zeebe at any point in between?
> * How are you deploying Zeebe - using the official Docker image, or bare metal via the TAR ball or JAR? If bare metal, which JVM are you running?
> 
> Regarding the error itself: the collector is registered when the class is initially loaded (the `ElasticsearchMetrics` class). That's done once, the first time an Elasticsearch exporter instance is created and used. So it seems unlikely for this to happen at any other time than when the exporter is initially loaded at start up.
> 
> That said, I'm not dismissing it, but it's important to know exactly how to reproduce it so we can figure out what went wrong.

> To clarify, the steps to reproduce are:
> 
> 1. Configure Elasticsearch exporter in the brokers
> 2. Generate some data (e.g. deploy a process, start an instance, etc.)
> 3. Manually delete the indices in Elasticsearch
> 4. Generate more data (causing more exports)
> 
> Can you confirm this? I tried it and nothing happened.
> 
> * Which version of Zeebe are you using?
> * Are you restarting Zeebe at any point in between?
> * How are you deploying Zeebe - using the official Docker image, or bare metal via the TAR ball or JAR? If bare metal, which JVM are you running?
> 
> Regarding the error itself: the collector is registered when the class is initially loaded (the `ElasticsearchMetrics` class). That's done once, the first time an Elasticsearch exporter instance is created and used. So it seems unlikely for this to happen at any other time than when the exporter is initially loaded at start up.
> 
> That said, I'm not dismissing it, but it's important to know exactly how to reproduce it so we can figure out what went wrong.

camunda-cloud-zeebe-1.0.0.
elasticsearch-7.12.1-windows-x86_64.zip
jdk11

`
      # Zeebe Standalone Broker configuration file (with embedded gateway)
      
      # This file is based on broker.standalone.yaml.template but stripped down to contain only a limited
      # set of configuration options. These are a good starting point to get to know Zeebe.
      # For advanced configuration options, have a look at the templates in this folder.
      
      # !!! Note that this configuration is not suitable for running a standalone gateway. !!!
      # If you want to run a standalone gateway node, please have a look at gateway.yaml.template
      
      # ----------------------------------------------------
      # Byte sizes
      # For buffers and others must be specified as strings and follow the following
      # format: "10U" where U (unit) must be replaced with KB = Kilobytes, MB = Megabytes or GB = Gigabytes.
      # If unit is omitted then the default unit is simply bytes.
      # Example:
      # sendBufferSize = "16MB" (creates a buffer of 16 Megabytes)
      #
      # Time units
      # Timeouts, intervals, and the likes, must be specified either in the standard ISO-8601 format used
      # by java.time.Duration, or as strings with the following format: "VU", where:
      #   - V is a numerical value (e.g. 1, 5, 10, etc.)
      #   - U is the unit, one of: ms = Millis, s = Seconds, m = Minutes, or h = Hours
      #
      # Paths:
      # Relative paths are resolved relative to the installation directory of the broker.
      # ----------------------------------------------------
      
      zeebe:
        broker:
          gateway:
            # Enable the embedded gateway to start on broker startup.
            # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_ENABLE.
            enable: true
      
            network:
              # Sets the port the embedded gateway binds to.
              # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_NETWORK_PORT.
              port: 26500
      
            security:
              # Enables TLS authentication between clients and the gateway
              # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED.
              enabled: false
      
          network:
            # Controls the default host the broker should bind to. Can be overwritten on a
            # per binding basis for client, management and replication
            # This setting can also be overridden using the environment variable ZEEBE_BROKER_NETWORK_HOST.
            host: localhost
            maxMessageSize: 8MB
      
          data:
            # Specify a directory in which data is stored.
            # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_DIRECTORY.
            directory: data
            # The size of data log segment files.
            # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_LOGSEGMENTSIZE.
            logSegmentSize: 512MB
            # How often we take snapshots of streams (time unit)
            # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_SNAPSHOTPERIOD.
            snapshotPeriod: 15m
      
          cluster:
            # Specifies the Zeebe cluster size.
            # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_CLUSTERSIZE.
            clusterSize: 1
            # Controls the replication factor, which defines the count of replicas per partition.
            # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR.
            replicationFactor: 1
            # Controls the number of partitions, which should exist in the cluster.
            # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT.
            partitionsCount: 1
      
          threads:
            # Controls the number of non-blocking CPU threads to be used.
            # WARNING: You should never specify a value that is larger than the number of physical cores
            # available. Good practice is to leave 1-2 cores for ioThreads and the operating
            # system (it has to run somewhere). For example, when running Zeebe on a machine
            # which has 4 cores, a good value would be 2.
            # This setting can also be overridden using the environment variable ZEEBE_BROKER_THREADS_CPUTHREADCOUNT
            cpuThreadCount: 8
            # Controls the number of io threads to be used.
            # This setting can also be overridden using the environment variable ZEEBE_BROKER_THREADS_IOTHREADCOUNT
            ioThreadCount: 16
            
          exporters:
            elasticsearch:
               jarPath: exporters/zeebe-elasticsearch-exporter-1.0.0.jar
               className: io.camunda.zeebe.exporter.ElasticsearchExporter
               args:
                 url: http://localhost:9200
                 bulk:
                   delay: 5
                   size: 1000
               index:
                 prefix: zeebe-record
                 createTemplate: true
                 command: true
                 event: true
                 rejection: true
                 deployment: true
                 process: true
                 error: true
                 incident: true
                 job: true
                 jobBatch: true
                 message: true
                 messageSubscription: true
                 variable: true
                 variableDocument: true
                 processInstance: true
                 processInstanceCreation: true
                 processMessageSubscription: true

`

**Comment by npepinpe** [comment]
As this is an old version which is not supported anymore, I would recommend upgrading to any 8.x, and see if the problem occurs again.
