### ISSUE TITLE
Scheduler Tasks can't be canceled on the ProcessingScheduleService

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10541]
**Describe the bug**

In the previous version we used to schedule work the Actor of the StreamProcessor, with that we also used features like canceling timers. 

This is especially useful if you want to cancel a previous task, because you want to trigger earlier. E.g. this case exists for DueDateChecker. https://github.com/camunda/zeebe/blob/8.0.6/engine/src/main/java/io/camunda/zeebe/engine/processing/scheduled/DueDateChecker.java#L52

With the new ProcessingScheduleService abstraction around the Actor we no longer support that feature. This means if we schedule Tasks for earlier deadline, like here https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/scheduled/DueDateChecker.java#L55-L57 we will not cancel the existing timers. 

In general if both timers are have a high difference it is not really an issue, since the timers are no longer in the state. If we have really small difference then it might be an issue, since we trigger the same timers twice. 

Since the case is rather unlikely, because the next timer always needs to be smaller to have an affect I mark the severity as mid.

**To Reproduce**
Schedule multiple timers, always a smaller then the previous one. 

**Expected behavior**
No multiple timers are scheduled. Or at least the previous one is canceled, which we need to add as feature to the ScheduleService.

**Environment:**
- OS: 
- Zeebe Version: 8.1 
- Configuration:

**Comment by megglos** [comment]
The problem is not so likely to happen (assumption).
Put it into ready as it is a regression.

**Comment by megglos** [comment]
Due to changed priorities we would move this into the backlog.

**Comment by Zelldon** [comment]
Would be a great thing to do, especially for pausing and resume processing etc.

**Comment by Zelldon** [comment]
@oleschoenburg wasn't this fixed?

**Comment by megglos** [comment]
@oleschoenburg this is fixed in all the latest patches from 8.1+, right? I can add the labels then

**Comment by oleschoenburg** [comment]
@megglos Yes! Thanks for adding them :heart:
