### ISSUE TITLE
Unnecessary future usage in ProcessingScheduleService

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10543]
**Description**

Each Task execution in the ProcessingScheduleService registers a new future on writing the result. See here https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/streamprocessor/ProcessingScheduleServiceImpl.java#L170-L179

Since we retry the writing with an AbortableStrategy, this adds other jobs and work on the Actor which can't be used for processing.

The RetryStrategy can't fail with an exception, since the tryWrite can't fail. 

My question would be whether we want to keep it like that or just remove it? In worst case if the writing fails, it will at some point be retried, because the in state still the timers exist. 

Anyone an opinion? We could benchmark what difference it makes when removing it.

**Comment by megglos** [comment]
Closing it as the overhead should be minimal and with the log we have visibility if something is off.
