### ISSUE TITLE
Backport dependency updates

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10553]
**Description**

I think we should configure dependabot to also run against the stable branches such that we can backport dependency updates as well. This allows to also backport security fixes and other bugs etc.

It makes also it easier to backport fixes and tests since otherwise we might run into situation where the dependency of an earlier version doesn't behave like it does on main, see for example this PR https://github.com/camunda/zeebe/pull/10494 where we had to adjust the test because of an older assertj version.

**Comment by megglos** [comment]
Would be worth evaluating this in relation to migrating to renovate.

We intended to evaluate snyk to determine whether backports are needed.
Automatic backporting of patch releases to maintenance branches seems worth doing and a low hanging fruit.

**Comment by npepinpe** [comment]
I think we can close this now, correct? I see it was moved to done, but I guess it didn't close the issue ;)
