### ISSUE TITLE
 How to build the project？

### ISSUE THREAD

**Issue by aisong** [camunda/zeebe#10551]
Hi，

I want to build the project locally.And have download the sourcecodes of the latest version.
But a huge number of errors occurred when open the project in vscode.It looks like a lot of classes are missing.You can take a look at my IDE screenshot.

Am I missing something?What should I do? Please tell me,thank you！

<img width="1512" alt="QQ20220929-150156@2x" src="https://user-images.githubusercontent.com/8147898/192962462-98ba5a08-6a21-45dc-819c-710eea885f13.png">

**Comment by Zelldon** [comment]
Hey @aisong these classes are generated classes (generated by SBE). You have to build it first with maven, which will generate the classes for your. Hope this helps.

**Comment by aisong** [comment]
> Hey @aisong these classes are generated classes (generated by SBE). You have to build it first with maven, which will generate the classes for your. Hope this helps.

@Zelldon Thank you very much for you reply！

I don't know how to use SBE in this project.  😥  Can you tell me more information about it? Or some related docs?

Thank you!

**Comment by Zelldon** [comment]
In general you don't need to know much about it if you just want to build it: run `mvn install -DskipTests` and the classes should be generated.

**Comment by aisong** [comment]
OK, thank you！！！

I have tried it.And got a error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.3.0:analyze-only (analyze-dependencies) on project zeebe-client-java: Dependency problems found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.3.0:analyze-only (analyze-dependencies) on project zeebe-client-java: Dependency problems found


I try to fix it :)

**Comment by Zelldon** [comment]
I will close this for now
