### ISSUE TITLE
Mixed benchmarks always fall in a weird state after several hours

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10552]
**Describe the bug**

I have mentioned earlier, that for me it looks like the mixed benchmarks are in a weird state. We can see always really high backpressure which is from my side not expected.

![mixed](https://user-images.githubusercontent.com/2758593/192966759-759fbd75-fd99-40d2-9488-8ef025fe151c.png)

The Interesting is that this only happens after several hours of execution.

![mixed-prev](https://user-images.githubusercontent.com/2758593/192967022-b693de74-8057-43ec-b0d3-3999056f5686.png)

Furthermore, this also happens even after fixing #10532 so this seem to be not related!

We can see this behavior on all our recent mixed benchmarks.

The following processes are executed in them.

![msg_one_task](https://user-images.githubusercontent.com/2758593/192967741-ad42b992-242f-49bb-ac87-9e06b35f9c1e.png)
![one_task](https://user-images.githubusercontent.com/2758593/192967744-cb6e8d47-84b7-4ab6-9be9-3f1822679672.png)
![timerProcess](https://user-images.githubusercontent.com/2758593/192967747-38f2d37e-a13d-4bbc-b36f-eb07b4992426.png)

[With that load:](https://github.com/camunda/zeebe/blob/medic-cw-benchmarks/setupKWBenchmark.sh#L57-L67)

```
# reduce the load ~ so we roughly reach 200 PI
sed_inplace "s/rate=100/rate=50/" timer.yaml
sed_inplace "s/rate=100/rate=50/" publisher.yaml
sed_inplace "s/rate=200/rate=100/" starter.yaml
```

**To Reproduce**
Take the part from the Medic benchmark creation:

https://github.com/camunda/zeebe/blob/medic-cw-benchmarks/setupKWBenchmark.sh#L57-L67

It seems to always happen after 5 hours !

**Expected behavior**
We have the same backpressure and processing as in the first ~5 hours.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.1.x 
- Configuration:

**Comment by megglos** [comment]
Will start a mixed benchmark with 8.0.x to verify whether it's a regression or not.

**Comment by megglos** [comment]
http://34.77.165.228/d/NzsO1mUnk/zeebe-overview?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=benchmark-issue-10552-806-mixed&var-pod=All&var-partition=All

**Comment by Zelldon** [comment]
After ~3 hours it looks still okisch.

What we can see is that has now multiple times spikes in the processing queue with and distance of 30 minutes

![spike](https://user-images.githubusercontent.com/2758593/193028516-2ba3f7d0-d691-4251-9ad0-1e9ffe83e014.png)

**Comment by Zelldon** [comment]
It seems to happen slower on 8.0.x or at least right now we don't see the same backpressure. 

What we can see is that ALL followers are unhealthy right now, and that for around 2 hours the processing completely stopped, which is even worse than with our current version.

![mixed](https://user-images.githubusercontent.com/2758593/193199768-cd41df9a-33ea-4463-b857-c56e2ae12957.png)

**Comment by Zelldon** [comment]
It looks like that the same issue happens also now on the normal benchmarks, see last medic week benchmark

![medic](https://user-images.githubusercontent.com/2758593/193213353-1d7b541a-70d3-4fd7-92c4-8a9917308441.png)

This is concerning.

**Comment by megglos** [comment]
> It looks like that the same issue happens also now on the normal benchmarks, see last medic week benchmark
> 
> [![medic](https://user-images.githubusercontent.com/2758593/193213353-1d7b541a-70d3-4fd7-92c4-8a9917308441.png)](http://34.77.165.228/d/NzsO1mUnk/zeebe-overview?orgId=1&refresh=10s&from=now-1h&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=medic-cw-39-35300146bd-benchmark&var-pod=All&var-partition=All)
> 
> This is concerning.

this benchmark lacks the recent timer fixes though?

**Comment by Zelldon** [comment]
That is true, but here are no timers executed at all.

**Comment by Zelldon** [comment]
@npepinpe @romansmirnov can this be related to https://github.com/camunda/zeebe/issues/9862 ?

**Comment by megglos** [comment]
We decided to move this to ready to root-cause these issues rather sooner than later as they indicate potential production issues.

**Comment by Zelldon** [comment]
I investigated that issue (with the failing weekly benchmark) further, and I think it is unrelated to the mixed benchmarks issue.



### Investigation

In the medic benchmark, we can see that when the performance dropped

![general](https://user-images.githubusercontent.com/2758593/193241422-861e61c3-4e48-4097-ba24-26cff83cfb8d.png)

That at the same time the record writes and commit latency went up significantly. This indicates an IO throttling (writing) issue, also described here https://github.com/camunda/zeebe/issues/8551 in more detail.

![latency](https://user-images.githubusercontent.com/2758593/193241447-7bfadf52-d2a6-4120-9405-214602f82210.png)



Looking at the node where the leader of the partitions is scheduled we can see that it has to share resources with another benchmark.

```
$ k describe pod medic-cw-39-35300146bd-benchmark-zeebe-0
Node:             gke-zeebe-cluster-default-pool-1f44de48-bxlk/10.132.0.72

$ k describe node gke-zeebe-cluster-default-pool-1f44de48-bxlk

...


  Namespace                               Name                                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                               ----                                                               ------------  ----------  ---------------  -------------  ---
  356ec583-1717-45ae-a4a1-541c0c883e8a    benchmark-worker-6995c6fc8-hk72p                                   500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     13h
  backup-qa-testing                       elasticsearch-master-0                                             3 (18%)       3 (18%)     8Gi (14%)        8Gi (14%)      13h
  default                                 metrics-prometheus-node-exporter-xns9d                             100m (0%)     0 (0%)      0 (0%)           0 (0%)         13h
  kube-system                             fluentbit-gke-5zx9q                                                100m (0%)     0 (0%)      200Mi (0%)       500Mi (0%)     36h
  kube-system                             gke-metrics-agent-47mhf                                            3m (0%)       0 (0%)      50Mi (0%)        50Mi (0%)      13h
  kube-system                             kube-proxy-gke-zeebe-cluster-default-pool-1f44de48-bxlk            100m (0%)     0 (0%)      0 (0%)           0 (0%)         13h
  kube-system                             pdcsi-node-dkt5s                                                   10m (0%)      0 (0%)      20Mi (0%)        100Mi (0%)     13h
  medic-cw-37-de38e9e086-benchmark-mixed  medic-cw-37-de38e9e086-benchmark-mixed-zeebe-1                     5 (31%)       5 (31%)     4Gi (7%)         4Gi (7%)       13h
  medic-cw-39-35300146bd-benchmark        medic-cw-39-35300146bd-benchmark-zeebe-0                           5 (31%)       5 (31%)     4Gi (7%)         4Gi (7%)       13h
  medic-cw-39-35300146bd-benchmark        medic-cw-39-35300146bd-benchmark-zeebe-gateway-7c97f68bc4-pkkk7    1 (6%)        1 (6%)      512Mi (0%)       512Mi (0%)     13h
  medic-cw-39-35300146bd-benchmark        worker-6bf6c8f8bb-fpzrq                                            500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     13h

```

After taking the node down, we can see that the throughput comes back.

```
$ zbchaos terminate --nodeId 0
Terminated medic-cw-39-35300146bd-benchmark-zeebe-0
```

![general-improved](https://user-images.githubusercontent.com/2758593/193241535-3c7955e1-133f-4130-be33-d74706ad39fe.png)

Furthermore, the latency goes back to "normal"

![latency-improved](https://user-images.githubusercontent.com/2758593/193241603-ce6d65e6-ed06-402e-ba67-dac7fbfc0dd5.png)

Related to that the scheduling on the node looks better.

```

$ k describe pod medic-cw-39-35300146bd-benchmark-zeebe-2

Node:             gke-zeebe-cluster-default-pool-1f44de48-tkzm/10.132.0.134


  Namespace                               Name                                                       CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                               ----                                                       ------------  ----------  ---------------  -------------  ---
  356ec583-1717-45ae-a4a1-541c0c883e8a    benchmark-worker-6995c6fc8-cvv7m                           500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     4h30m
  63d7a39b-b474-43a3-aaa1-836d544d8b38    benchmark-worker-b8c58ff5-m958h                            500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     4h30m
  b559b987-e007-4d2c-8fee-3492023a35cb    benchmark-worker-5db7f9c8cf-hps7j                          500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     4h30m
  benchmark-issue-10552-806-mixed         worker-77d568ffd8-r9nb6                                    500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     4h30m
  default                                 metrics-prometheus-node-exporter-5bz2w                     100m (0%)     0 (0%)      0 (0%)           0 (0%)         5h7m
  kube-system                             fluentbit-gke-d87gc                                        100m (0%)     0 (0%)      200Mi (0%)       500Mi (0%)     5h7m
  kube-system                             gke-metrics-agent-fh6pd                                    3m (0%)       0 (0%)      50Mi (0%)        50Mi (0%)      5h7m
  kube-system                             konnectivity-agent-746f79f589-lmqn5                        10m (0%)      0 (0%)      30Mi (0%)        125Mi (0%)     4h40m
  kube-system                             kube-proxy-gke-zeebe-cluster-default-pool-1f44de48-tkzm    100m (0%)     0 (0%)      0 (0%)           0 (0%)         5h7m
  kube-system                             metrics-server-v0.5.2-5d9f64c946-ltznw                     70m (0%)      65m (0%)    281Mi (0%)       531Mi (0%)     4h30m
  kube-system                             pdcsi-node-zqs9j                                           10m (0%)      0 (0%)      20Mi (0%)        100Mi (0%)     5h7m
  medic-cw-38-f22c68c563-benchmark-mixed  elasticsearch-master-1                                     3 (18%)       3 (18%)     8Gi (14%)        8Gi (14%)      4h30m
  medic-cw-38-f22c68c563-benchmark-mixed  publisher-5ff4dfbb4d-lgj96                                 250m (1%)     250m (1%)   256Mi (0%)       256Mi (0%)     4h30m
  medic-cw-38-f22c68c563-benchmark        worker-6cd88b8b9b-9lx7v                                    500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     4h40m
  medic-cw-39-35300146bd-benchmark        medic-cw-39-35300146bd-benchmark-zeebe-2                   5 (31%)       5 (31%)     4Gi (7%)         4Gi (7%)       5h8m
  minio-backup-store                      minio-backup-store-pool-0-0                                4 (25%)       0 (0%)      8Gi (14%)        0 (0%)         5h7m
  zell-rm-submit                          worker-59d8d79d68-4zmjr                                    500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     130m

```

There are also several pods from different namespaces BUT no other broker is running on that machine, which would compete with the disk/network throughput

### Further details

I also took heap dump, flamegraph and copied the gc.log. But not much stands out here.


[flamegraph.html.zip](https://github.com/camunda/zeebe/files/9682896/flamegraph.html.zip)
[gc.log.zip](https://github.com/camunda/zeebe/files/9682897/gc.log.zip)
[heap.dump.zip](https://github.com/camunda/zeebe/files/9682898/heap.dump.zip)

**Comment by Zelldon** [comment]
After the restart of the leader the backpressure doesn't change and the commit latency still looks the similar or the same.


![restart](https://user-images.githubusercontent.com/2758593/193275263-320fea5e-c261-4063-bab6-fabbe4a3b764.png)
![restart-latency](https://user-images.githubusercontent.com/2758593/193275267-ef585346-5797-4c8f-935a-6487b48c0739.png)


```
$ zbchaos topology
Node      |Partition 1         |Partition 2         |Partition 3
0         |LEADER (HEALTHY)    |FOLLOWER (HEALTHY)  |FOLLOWER (HEALTHY)
2         |FOLLOWER (HEALTHY)  |LEADER (HEALTHY)    |LEADER (HEALTHY)
1         |FOLLOWER (HEALTHY)  |FOLLOWER (HEALTHY)  |FOLLOWER (HEALTHY)
$ k describe pod medic-cw-39-35300146bd-benchmark-mixed-zeebe-2 | grep Node
Node:             gke-zeebe-cluster-default-pool-1f44de48-j976/10.132.0.74
...


$ k describe node gke-zeebe-cluster-default-pool-1f44de48-j976
....
 Namespace                                                        Name                                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                                                        ----                                                               ------------  ----------  ---------------  -------------  ---
  camunda-platform-cxw4yq-d2085cbf911d3a2143d438ecc7e9ce9728caad0  elasticsearch-master-0                                             1 (6%)        2 (12%)     1Gi (1%)         2Gi (3%)       17h
  camunda-platform-ispzer-92c06c37732f399f595246a27168f9c32610951  elasticsearch-master-0                                             1 (6%)        2 (12%)     1Gi (1%)         2Gi (3%)       15h
  default                                                          metrics-prometheus-node-exporter-bqml6                             100m (0%)     0 (0%)      0 (0%)           0 (0%)         17h
  kube-system                                                      fluentbit-gke-gfqg6                                                100m (0%)     0 (0%)      200Mi (0%)       500Mi (0%)     2d3h
  kube-system                                                      gke-metrics-agent-g45zz                                            3m (0%)       0 (0%)      50Mi (0%)        50Mi (0%)      17h
  kube-system                                                      kube-proxy-gke-zeebe-cluster-default-pool-1f44de48-j976            100m (0%)     0 (0%)      0 (0%)           0 (0%)         27h
  kube-system                                                      pdcsi-node-skmn6                                                   10m (0%)      0 (0%)      20Mi (0%)        100Mi (0%)     17h
  kube-system                                                      tiller-deploy-8557598fbc-44kvh                                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         17h
  medic-cw-36-104d78ae31-benchmark-mixed                           worker-5666b95d58-zvc6v                                            500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     17h
  medic-cw-36-104d78ae31-benchmark                                 worker-5c8f7544d-7gtkk                                             500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     17h
  medic-cw-37-de38e9e086-benchmark-mixed                           worker-55776f8cd-2nlds                                             500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     17h
  medic-cw-37-de38e9e086-benchmark                                 worker-86655845b-zfq5l                                             500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     17h
  medic-cw-38-f22c68c563-benchmark-mixed                           elasticsearch-master-2                                             3 (18%)       3 (18%)     8Gi (14%)        8Gi (14%)      17h
  medic-cw-38-f22c68c563-benchmark-mixed                           starter-c9db48c56-mwxzd                                            250m (1%)     250m (1%)   256Mi (0%)       256Mi (0%)     17h
  medic-cw-38-f22c68c563-benchmark-mixed                           worker-5dc7489778-26hnm                                            500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     17h
  medic-cw-39-35300146bd-benchmark-mixed                           medic-cw-39-35300146bd-benchmark-mixed-zeebe-2                     5 (31%)       5 (31%)     4Gi (7%)         4Gi (7%)       17h
  medic-cw-39-35300146bd-benchmark-mixed                           medic-cw-39-35300146bd-benchmark-mixed-zeebe-gateway-6c858xxg8c    1 (6%)        1 (6%)      512Mi (0%)       512Mi (0%)     17h
  medic-cw-39-35300146bd-benchmark-mixed                           publisher-79c9f65666-2jvzg                                         250m (1%)     250m (1%)   256Mi (0%)       256Mi (0%)     17h
  medic-cw-39-35300146bd-benchmark                                 worker-6bf6c8f8bb-c7j85                                            500m (3%)     500m (3%)   256Mi (0%)       256Mi (0%)     17h

```

This time the node has no other brokers running (some elastic, but they have not that highload e.g. camunda-platform- test has no much traffic.

So I think it is not related here to the node and write throttling it has to be something different.

**Comment by Zelldon** [comment]
I took an flamegraph 
![flame](https://user-images.githubusercontent.com/2758593/193283484-fa660215-b9ee-4e8b-9a43-91463ef8787c.png)


and it looks like most of the time is spend in processing in general, which is of course great and expected. 

Taking a more detailed look, it seem to be that most time is spent on retrieving data from RocksDB, maybe still expected (?).
![flame-detail](https://user-images.githubusercontent.com/2758593/193284011-1f96f4ce-588b-49f0-b4b6-f58874ea5e4d.png)

~40% of the time is about getting a value from RocksDb, and half of it is because of asserting whether the Key already exists. 
![flame-assertkeys](https://user-images.githubusercontent.com/2758593/193284325-7ba92025-068b-4a0f-a869-7cc131277ac2.png)

almost another half is seeking the column families 
![flame-seek](https://user-images.githubusercontent.com/2758593/193284742-c871c5b9-18d9-4535-8b28-b978821ce30b.png)

I'm not sure yet but maybe it is related to what @romansmirnov described in https://github.com/camunda/zeebe/issues/9862#issuecomment-1225584671 that maybe that we have too many cache missed after a while running. Meaning RocksDB needs longer now to retrieve the data. 

@romansmirnov can we verify that somehow? Based on metrics or rocksdb logs?

**Comment by Zelldon** [comment]
I spent the last day investigating this further. :male_detective: 

I discussed with @romansmirnov  this issue and he also thought that it might be related to the pointed issue with RocksDB we can see here #9862. 

In order to verify that I created [a new branch](https://github.com/camunda/zeebe/tree/zell-investigate-mixed), which contained some[ new metrics for RocksDB ](https://github.com/camunda/zeebe/commit/4c1e5b2cc549b3109bb50ceec2f965cbdbd63e30)(created by @romansmirnov ). Furthermore, some metrics show the actual process instance and job count.  

## Benchmark

We can see after several hours of running that the backpressure goes again pretty high (~80%).

![general](https://user-images.githubusercontent.com/2758593/194598003-448d5e46-f648-4fe1-a9fe-7cee38555727.png)

When we now take a look at the RocksDB metrics (especially at the cache miss hit ratios) we can directly see that If the Block cache filter miss ratio increases our Backpressure goes also up.

![backpressure](https://user-images.githubusercontent.com/2758593/194598488-37144f23-33bd-472c-a243-c5fc05b089ef.png)

That can be seen also much better if we take a look at one specific partition, e.g. partition 2 (no explicit reason to pick this partition)

![backpressure-p2-b2](https://user-images.githubusercontent.com/2758593/194598601-15dbc949-4dcc-4627-8e83-d7698c14eccd.png)

We can see that the metrics for the actual running process instance and jobs are almost stable or in a constance range ~100-200 instances.

![state-size](https://user-images.githubusercontent.com/2758593/194598940-9dee2ce9-79e6-4954-a737-983972ff4ffb.png)


But the snapshot size, which means also the general RocksDB seems to increase 
![snapshot-size](https://user-images.githubusercontent.com/2758593/194599001-f23fb133-82de-464e-8496-0fbc59ab30f9.png)

This might be the reason why our cache misses are happening. 

If the take a look at other benchmarks, like the mixed benchmark for last week we also see that it has a pretty huge state already

![snapshot-other-mixed-size](https://user-images.githubusercontent.com/2758593/194599146-c8ee1eef-7dce-4a5f-87a3-0cbfcc734d7e.png)


There seems to be something leaking, or better say something not cleaned up correctly! :point_up: 

:next_track_button: I want to add some more metrics for the count of keys per column family, which might help us here.

**Comment by Zelldon** [comment]
I added a decorator for the  ZeebeDD in order to count the the keys for each ColumnFamily, see https://github.com/camunda/zeebe/commit/547bf9c845b4b26ea3d4ceb375131f3d5b5c8c21

This allowed now to see that multiple messages column families are not cleaned up!!

![messages](https://user-images.githubusercontent.com/2758593/194691243-909417da-6479-4e80-8061-c0104ac2d8a5.png)

**Comment by menski** [comment]
We assume this is related to #10643
