### ISSUE TITLE
Support undefined tasks

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#10562]
**Is your feature request related to a problem? Please describe.**
When I start modeling a process, I don't define the types of tasks (i.e. service task, user task, etc.). Initially, all tasks are undefined,  also called abstract tasks. Later in the modeling, I will define the types task-by-task.

But I can't deploy my process until all tasks have a supported type. 

**Describe the solution you'd like**

I can deploy a process that contains undefined tasks. For example, the following process:

![image](https://user-images.githubusercontent.com/4305769/193023197-dce236ea-4d42-4523-9160-8bb325e74d23.png)

I can create an instance of this process. The process instance can activate and complete the undefined tasks in a pass-through semantic. So, the task is activated and immediately completed without additional logic. Similar to [manual tasks](https://docs.camunda.io/docs/components/modeler/bpmn/manual-tasks/). 

**Describe alternatives you've considered**
I use manual tasks instead of undefined tasks. So, I can deploy and execute my process. But on the modeling, I need additional clicks for each task. 

**Additional context**
The undefined task should behave exactly like a manual task.

(BPMN 2.0, chapter 13.2.3, page 430)

![image](https://user-images.githubusercontent.com/4305769/193024429-1988ff2c-33d8-419f-b164-73b6bbedb91b.png)

New contributors could watch the [video](https://www.twitch.tv/videos/1584245006) on how to implement a new BPMN symbol.

**Comment by nikku** [comment]
Is there any operational differences between manual and abstract tasks?

**Comment by nikku** [comment]
Did you already settle on a naming? If not I'd encourage you to call this thing _undefined_ task. This would mirror how we call it in our modeling tools. We can obviously decide to move to "abstract task" as a name. Our research revealed that there is no clear winner in terms of naming (abstract vs. undefined vs. blank).

**Comment by saig0** [comment]
I like "undefined task". Let's go for it. :+1:

**Comment by remcowesterhoud** [comment]
> Is there any operational differences between manual and abstract tasks?

@nikku Sorry, I missed this question earlier. There is no operational difference between the two of them.

**Comment by christian-konrad** [comment]
Finally, this resolves soooo much pain, and actually allows us to say that we support "iterative modeling+implementation"!
It is also a huge accelerator for https://github.com/camunda/product-hub/issues/144 (the modeling-only use case), since it allows to start with a strategical model without being punished by 10s of error messages for undefined tasks once you switch to "implement" mode (to build the operational model).

**Comment by nikku** [comment]
Agreed upon the name (2022-10-12): We call it `Undefined Task`.
