### ISSUE TITLE
Support link events

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#10563]
**Is your feature request related to a problem? Please describe.**
I want to use link events in my process. They can be handy for large processes, for example, to split the process visually, or to avoid long sequence flows.

![image](https://user-images.githubusercontent.com/4305769/193029472-f901e469-4e4b-43c3-a40d-937b1971c454.png)

**Describe the solution you'd like**
I can deploy a process that contains link throw or catch events. 

I can create an instance of the process. When the process instance enters the link throw event, it activates and completes the throw event in a pass-through semantic (i.e. without applying additional logic). After the throw event is completed, the process instance continues at the referenced link catch event. The catch event is also activated and completed in a pass-through semantic. After the catch event is completed, the process instance takes the outgoing sequence flow(s). 

**Describe alternatives you've considered**
I use sequence flows instead of link events. They are easy to follow but it gets messier in large processes. 

**Additional context**
The link event should behave similarly to Camunda Platform 7. See the related documentation [here](https://docs.camunda.org/manual/7.17/reference/bpmn20/events/link-events/). 

(BPMN 2.0, chapter 10.4.4, page 253)

![image](https://user-images.githubusercontent.com/4305769/193027022-18a25391-a18a-4df1-a81c-82f5b0b9e215.png)

New contributors could watch the [video](https://www.twitch.tv/videos/1584245006) on how to implement a new BPMN symbol.

**Comment by skayliu** [comment]
Hi,@saig0, I'd love to make a PR for this, may i?

**Comment by saig0** [comment]
@skayliu awesome. :tada: I'm looking forward to your PR. :rocket: 

If you want to participate in the [Hacktoberfest](https://camunda.com/hacktoberfest2022/) then you should wait until the 1st of October.

**Comment by skayliu** [comment]
Well, I've implemented the bpmn model  part of validate the link events, and soon i'll implementate the engine part, may be i can make the PR before 1st of October.

**Comment by skayliu** [comment]
@saig0, Do we need to impleate a Fluent Builder API in bpmn-model  for link catch event? I didn't see these api in C7.

**Comment by skayliu** [comment]
@saig0, Do we need to impleate a Fluent Builder API in bpmn-model  for link catch event? I didn't see these api in C7. 

It seems like that link events in C7 are modeled by camunda modeler, and can't model by  Fluent Builder API.

**Comment by saig0** [comment]
> Do we need to implement a Fluent Builder API in bpmn-model for link catch event?

Yes. We use the Model API in our tests, for example, in the workflow engine. This allows having the process and the test code in one place.

The adjustments in the Model API could be a separate PR. Small PRs are easier to review.

**Comment by skayliu** [comment]
Hi,@tobiasschaefer, here it is.

**Comment by korthout** [comment]
The pull request is currently in review by @saig0, so I'm changing the assignee. This allows the team to better track who is doing what.

**Comment by lzgabel** [comment]
Hi @saig0. Since Thobias doesn't have time to implement the engine behavior at the moment, I'm taking over it now. And @skayliu has submitted bpmn-model api related [PR #10635](https://github.com/camunda/zeebe/pull/10635), so you can assign this task to me and @skayliu

**Comment by saig0** [comment]
@lzgabel super. Go for it. :rocket:

**Comment by lzgabel** [comment]
Hi @saig0. Please reopen this issue. I'll submit the behavior of engine part soon. 🙇
