### ISSUE TITLE
Maven release plugin doesn't work with sort plugin

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10602]
**Describe the bug**

The release plugin updates the version in the pom file during the jenkins release pipeline. It will change some formating of the pom and will cause the sort plugin to fail. See related PR. https://github.com/camunda/zeebe/actions/runs/3180846815/jobs/5184904296

```
Error:  Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.27.1:check (spotless-check) on project zeebe-bom: The following files had format violations:
Error:      pom.xml
Error:          @@ -8,7 +8,7 @@
Error:           ····<artifactId>camunda-release-parent</artifactId>
Error:           ····<version>3.9.1</version>
Error:           ····<!--·do·not·remove·empty·tag·-·[http://jira.codehaus.org/browse/MNG-4687·--](http://jira.codehaus.org/browse/MNG-4687%C2%B7--)>
Error:          -····<relativePath·/>
Error:          +····<relativePath></relativePath>
Error:           ··</parent>
Error:           
Error:           ··<groupId>io.camunda</groupId>
Error:          @@ -128,7 +128,7 @@
Error:           ··········<configuration>
Error:           ············<pom>
Error:           ··············<!--·[https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md#sortpom·--](https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md#sortpom%C2%B7--)>
Error:          -··············<sortPom·/>
Error:          +··············<sortPom></sortPom>
Error:           ············</pom>
Error:           ··········</configuration>
Error:           ········</plugin>
Error:  Run 'mvn spotless:apply' to fix these violations.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

See related change which causes this https://github.com/camunda/zeebe/pull/10599/commits/e8e98560ab7123d3cdbdd4fdf63b5934cd251813#diff-954221b717ff3d93b2f171be5b7d728359dfa4ebee98e8e5691c0697682d247eL131

**To Reproduce**

Build a release

**Expected behavior**
No issues with sort plugin

**Log/Stacktrace**
https://github.com/camunda/zeebe/actions/runs/3180846815/jobs/5184904296

**Comment by megglos** [comment]
Related maven release plugin issueL https://issues.apache.org/jira/browse/MRELEASE-1008

Seems like there is no intention to fix that.

**Comment by npepinpe** [comment]
I guess we run the auto formatting immediately after? :shrug:

**Comment by menski** [comment]
Next step: add the formatting command to the release pipeline

**Comment by npepinpe** [comment]
I'm not familiar with completion goals, so I don't know. But yes we added that then specifically because it would auto format before the release, and then fail because of uncommitted changes. I think it sort of makes sense not to run any checks anyway on the release, but it's a really minor thing so if it helps, just remove it.
