### ISSUE TITLE
FailJob with retry backoff response is not communicated to client

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#10612]
**Describe the bug**

This bug only exists on 8.0.x and 1.3.x, as it was already fixed in:
- https://github.com/camunda/zeebe/pull/9389

Specifically, the response writer's flush is overwritten. So the response is not communicated. This was fixed in a7195f7750670e41ac0e42da8d170ffedfed9757.

**To Reproduce**

Use the new java client (> 8.1) or the nodejs client to fail a job with a retry backoff that exceeds the gateway-broker request timeout. Notice that the client's request is responded with a timeout exceeded error.

**Expected behavior**

The FailJob request should be responded to immediately with a successful response.

**Comment by korthout** [comment]
Note that it's not possible to write a QA test for this because the Java and Go clients only support the retry backoff from 8.1 onwards; and the qa tests couple the broker's version and the client's version.

**Comment by menski** [comment]
we will only backport this to 8.0 as with 8.1 the 1.3 EOL was reached.

**Comment by korthout** [comment]
Short update: 
- only backport of a7195f7 to `stable/8.0` is needed
