### ISSUE TITLE
None end events calculation of output parameters

### ISSUE THREAD

**Issue by hmeniz** [camunda/zeebe#10613]
**Is your feature request related to a problem? Please describe.**

Process does not calculate output parameters in “none end event”. Is there a chance to calculate these output parameters and put them in the process values without using the “message end event”?

**Describe the solution you'd like**

The process instance applies the output mappings when a none end event is reached. Similar to message end events.

![image](https://user-images.githubusercontent.com/27866285/194079003-0ed2a436-3e5d-4bf7-9044-5d6b33358139.png)

**Describe alternatives you've considered**
For now, using "none throw event" or "message end event" for calculate output parameters are alternative solutions.

**Additional context**
We are using Camunda Platform 8 Self Managed and Desktop Modeler

Related camunda forum link: https://forum.camunda.io/t/camunda-8-end-event-output-parameters/40136

The following class controls the behavior of the event events: [EndEventProcessor](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/event/EndEventProcessor.java)

New contributors could watch the [video](https://www.twitch.tv/videos/1584245006) to learn more about how to extend the behavior of the end events.

**Comment by skayliu** [comment]
Hi, @saig0, I've implemented this, please review it, thank you.
