### ISSUE TITLE
`ExportingEndpointIT.shouldResumeExporting` is flaky

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10628]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far
- Does it block your work? No
- Do we suspect that it is a real failure? Maybe?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:    Run 1: ExportingEndpointIT.shouldResumeExporting:103->startProcess:131 ? ClientStatus Command 'CREATE_WITH_AWAITING_RESULT' rejected with code 'NOT_FOUND': Expected to find process definition with process ID 'processId', but none found
</pre>
</details>

**Hypotheses**

No idea, test looks correct and like it couldn't fail in this way.

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
06:22:25.304 [] [ForkJoinPool-3-worker-1] INFO  io.camunda.zeebe.test.util.SocketUtil - Choosing next port 1232 for test fork 2 with range PortRange{host='localhost', basePort=1225, maxOffset=100, currentOffset=8}
06:22:25.306 [] [ForkJoinPool-3-worker-1] INFO  io.zeebe.containers.cluster.ZeebeCluster - Starting cluster zeebe-cluster with 2 brokers, 2 gateways, 2 partitions, and a replication factor of 1
06:22:25.307 [] [testcontainers-lifecycle-0] INFO  docker[localhost:5000/camunda/zeebe:current-test] - Creating container for image: localhost:5000/camunda/zeebe:current-test
06:22:25.307 [] [testcontainers-lifecycle-2] INFO  docker[localhost:5000/camunda/zeebe:current-test] - Creating container for image: localhost:5000/camunda/zeebe:current-test
06:22:25.402 [] [testcontainers-lifecycle-0] INFO  docker[localhost:5000/camunda/zeebe:current-test] - Container localhost:5000/camunda/zeebe:current-test is starting: 7e57ba67130ef25409bde8ac22a2ef34f013312498770e08eeb67be9bd0969f7
06:22:25.447 [] [testcontainers-lifecycle-2] INFO  docker[localhost:5000/camunda/zeebe:current-test] - Container localhost:5000/camunda/zeebe:current-test is starting: 36383c1e568ea5551e92acd6d1f6a1657b49f9c47d08cea95fa3fdac45e97738
06:22:33.373 [] [ducttape-1] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /elastic_greider: Waiting for 120 seconds for URL: http://localhost:49234/ready (where port 49234 maps to container port 9600)
06:22:33.958 [] [ducttape-3] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /festive_buck: Waiting for 120 seconds for URL: http://localhost:49238/ready (where port 49238 maps to container port 9600)
06:22:37.756 [] [ducttape-1] INFO  io.zeebe.containers.ZeebeTopologyWaitStrategy - /elastic_greider: Waiting for PT2M for topology to have at least 2 brokers, 2 partitions with 1 replicas, and each partition to have a leader
06:22:37.939 [] [ducttape-3] INFO  io.zeebe.containers.ZeebeTopologyWaitStrategy - /festive_buck: Waiting for PT2M for topology to have at least 2 brokers, 2 partitions with 1 replicas, and each partition to have a leader
06:22:38.889 [] [ducttape-0] TRACE io.zeebe.containers.ZeebeTopologyWaitStrategy - /elastic_greider: Topology: TopologyImpl{brokers=[BrokerInfoImpl{nodeId=1, host='zeebe-broker-1', port=26501, version=8.2.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=2, role=LEADER, health=HEALTHY}]}, BrokerInfoImpl{nodeId=0, host='zeebe-broker-0', port=26501, version=8.2.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=LEADER, health=HEALTHY}]}], clusterSize=2, partitionsCount=2, replicationFactor=1, gatewayVersion=8.2.0-SNAPSHOT}
06:22:38.891 [] [testcontainers-lifecycle-0] INFO  docker[localhost:5000/camunda/zeebe:current-test] - Container localhost:5000/camunda/zeebe:current-test started in PT13.583746734S
06:22:39.162 [] [ducttape-2] TRACE io.zeebe.containers.ZeebeTopologyWaitStrategy - /festive_buck: Topology: TopologyImpl{brokers=[BrokerInfoImpl{nodeId=0, host='zeebe-broker-0', port=26501, version=8.2.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=LEADER, health=HEALTHY}]}, BrokerInfoImpl{nodeId=1, host='zeebe-broker-1', port=26501, version=8.2.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=2, role=LEADER, health=HEALTHY}]}], clusterSize=2, partitionsCount=2, replicationFactor=1, gatewayVersion=8.2.0-SNAPSHOT}
06:22:39.164 [] [testcontainers-lifecycle-2] INFO  docker[localhost:5000/camunda/zeebe:current-test] - Container localhost:5000/camunda/zeebe:current-test started in PT13.85725724S
</pre>
</details>

**Comment by oleschoenburg** [comment]
I'm closing this for now, please reopen if it reappears.

The flaky test dashboard (from Jenkins) does not include this test, I haven't seen it fail on GHA recently and I don't see how this test could fail in this way.

**Comment by nicpuppa** [comment]
This test failed again [here](https://github.com/camunda/zeebe/actions/runs/5725689276/job/15514660263)

[logs_82100.zip](https://github.com/camunda/zeebe/files/12227500/logs_82100.zip)

**Comment by Zelldon** [comment]
happened again on main https://github.com/camunda/zeebe/actions/runs/5853086673/job/15866421098
