### ISSUE TITLE
Backport fix to preserve output of flaky test runs to `stable/8.0`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10637]
With https://github.com/camunda/zeebe/issues/10009 done, we should also backport https://github.com/camunda/zeebe/pull/10520 to the `stable/8.0` branch, otherwise we won't have good information to diagnose flaky tests on that branch.

Unfortunately, backporting is not trivial because of dependency convergence issues. https://github.com/camunda/zeebe/pull/10520 requires surefire 3.0.0-M7 but 8.0 is on 3.0.0-M5. Just backporting https://github.com/camunda/zeebe/pull/9049 too is not enough, the maven plugin versions have drifted quite far and there are other changes to our POMs.

**Comment by megglos** [comment]
Putting into backlog for now as it makes sense but is not urgent right now, given that we usually invesigate flaky tests on main, where we have this already.

**Comment by npepinpe** [comment]
Will do this to be able to later fix https://github.com/camunda/zeebe/issues/10954
