### ISSUE TITLE
Backport action fails on changes to GHA workflows

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10672]
When trying to backport changes to some GHA workflows, the backport action fails: https://github.com/camunda/zeebe/actions/runs/3225346166/jobs/5277543018

Previous attempts to fix this: https://github.com/camunda/zeebe/pull/10670 (reverted in https://github.com/camunda/zeebe/pull/10671).
Relevant discussion regarding permissions: https://github.com/orgs/community/discussions/27072#discussioncomment-3254515

**Comment by megglos** [comment]
Impact: Workflow changes have to get backported manually
We put it into ready to investigate and get to a conclusion on whether there is chance to fix it.

**Comment by megglos** [comment]
hint: dependabot might also be affected

**Comment by oleschoenburg** [comment]
@korthout and I looked into this a bit more and came to the conclusion that we should be able to get this working if we use a PAT of the @backport-action user again (like we already tried in #10670) but this time give the user write access to this repo.

**Comment by oleschoenburg** [comment]
For additional background: If we don't set a custom PAT, the backport action will push with the default credentials from the workflow which GitHub has setup so that it can't make changes to workflows itself. There's no way around that, it's a security feature. That's why we need to use a PAT from the @backport-action user.
