### ISSUE TITLE
Needs to set the variables locally when failing a job with variables

### ISSUE THREAD

**Issue by skayliu** [camunda/zeebe#10698]
**Is your feature request related to a problem? Please describe.**

If a failling job has variables, then the variables needs to be set locally

`client.newFailCommand(...).variables(...) `

**Describe the solution you'd like**

Set the variables only locally when failing a job has variables.

**Describe alternatives you've considered**

If you want to variables globally, then you should  `newSetVariablesCommand`, also it can set locally.

- for locally
   `.newSetVariablesCommand(job.getElementInstanceKey()).variables(Map.of("key2", "value2")).local(true).send().join();`
- for globally 
   `.newSetVariablesCommand(job.getElementInstanceKey()).variables(Map.of("key2", "value2").send().join();`

**Additional context**

Related #9404

**Comment by korthout** [comment]
Thanks @skayliu 🚀 

For completeness, the reason to only support locally set variables is described in:
- https://github.com/camunda/zeebe/issues/9404#issuecomment-1274264402

>I suggest that the job fail command sets the variables only locally. No option to set global variables.
> 
> The reason is variable propagation. Similar to the job complete command, we don't set the variable globally but we propagate the variables from the related task to the upper scopes. If the task has an output mapping then the mapping is applied. If the output mappings can't be applied then we would need to create an incident.
> 
> This would be more complex. So, I prefer to set the variables only locally in the scope of the task.

**Comment by skayliu** [comment]
Hi, @korthout, you can assignee this to me, I'm making a PR for this.
