### ISSUE TITLE
Fail to export the process instance modification record to Elasticsearch

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#10732]
**Describe the bug**

Since version `8.1.1`, we can't export the process instance modification record to Elasticsearch anymore. This is a regression to the previous version `8.1.0`. 

In bug fix #10609, we updated the record. But we forgot to update the ES template.

If a process instance modification is applied then the ES exporter tries to export the record and fails. As a result, no other records can be exported anymore.

**To Reproduce**

1. Apply a process instance modification in Operate, for example, activate an element
2. Verify that the result of the modification is not shown in Operate and an error is logged for the Zeebe broker

**Expected behavior**

The ES exporter can export process instance modification records.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: `8.1.1`
- Configuration:

**Comment by npepinpe** [comment]
If we're now exporting everything, please update integration tests to test for all records - when we initially implemented it, we excluded some value types since not everything was exported to ES at the time.

**Comment by remcowesterhoud** [comment]
This apparently didn't catch this problem. Modification records are part of the list that's returned here.

**Comment by npepinpe** [comment]
Then my guess is it's with the protocol factory which does not generate the record in a way to trigger the bug =/

**Comment by remcowesterhoud** [comment]
I agree, ignoring it makes sense. It's only used internally

**Comment by npepinpe** [comment]
On thing we could do to keep serialization on par with the API, is instead of using `toJson`, use a specific writer for the value type, e.g. `new ObjectMapper().writerFor(ProcessInstanceModificationRecordValue.class).writeValueAsString(myRecord)`. This will ignore properties not on the interface type (assuming this is what we want ofc).
