### ISSUE TITLE
Add escalation events to the randomized property tests

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#10768]
## Description

We should add escalation events to the randomized process generator that is being used in the randomized property tests.

- Introduce a new `BlockBuilder` for escalation events
- This `BlockBuilder` should randomly decide if it will escalate from a subprocess or from a called activity
- The `BlockBuilder` should randomly decide if it will use an interrupting or a non-interrupting boundary event
- The `BlockBuilder` should randomly decide if it will throw using an intermediate throw event or an end event

The `BlockBuilder` will generate one of the following blocks:

**Subprocess**
Note the difference between exclusive and parallel gateways depending on the interruption of the boundary event.
<img width="661" alt="image" src="https://user-images.githubusercontent.com/5787702/196681469-e129b951-8176-4b44-9db4-877f8bea1d5d.png">

**Call Activity**
The non-coloured parts show what the called process should look like. Note the difference between exclusive and parallel gateways depending on the interruption of the boundary event.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/5787702/196682568-bebc6574-7baa-43c7-b60e-d3ff5d4671ff.png">

**Comment by remcowesterhoud** [comment]
@lzgabel I don't know if you were planning to work on this issue, but I'd like to ask you to leave it for now. I want to see if someone within the team wants to pick this up as it's a good one for some knowledge sharing 😄

**Comment by lzgabel** [comment]
@remcowesterhoud. Okay, I would like to ask if there is a plan for the team's sharing to be made public. 😄

**Comment by remcowesterhoud** [comment]
I don't think we'll do a big meeting regarding this. More of a short pair-programming session.

I do have plans to write something about the randomized process generation/execution and put in our [docs](https://github.com/camunda/zeebe/tree/main/docs) though.

**Comment by remcowesterhoud** [comment]
@koevskinikola I have assigned you to this. For now I have put it in blocked, we should wait until #10595 is merged before we start.
