### ISSUE TITLE
`ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries` is flaky 

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#10887]
**Summary**

- How often does the test fail? I saw it once, [while merging 8.1.3 into stable/8.1](https://github.com/camunda/zeebe/actions/runs/3371280196/jobs/5593288862)
- Does it block your work? it blocked a merge
- Do we suspect that it is a real failure? I'm unsure

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.369 s <<< FAILURE! - in io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest
Error:  io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries  Time elapsed: 3.937 s  <<< FAILURE!
org.mockito.exceptions.verification.VerificationInOrderFailure: 

Verification in order failure:
logStreamBatchWriter.tryWrite();
Wanted 5000 times:
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries(ProcessingScheduleServiceTest.java:275)
But was 2091 times:
</pre>
</details>

**Hypotheses**

I have none so far

**Logs**

<details><summary>Logs</summary>
<pre>
Error:  Failures: 
Error:    ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries:275 
Verification in order failure:
logStreamBatchWriter.tryWrite();
Wanted 5000 times:
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries(ProcessingScheduleServiceTest.java:275)
But was 2091 times:
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
...
</pre>
</details>

**Comment by korthout** [comment]
Seems that it's a different error as:
- https://github.com/camunda/zeebe/issues/10487

**Comment by Zelldon** [comment]
Might be related to https://github.com/camunda/zeebe/pull/10866 \cc @npepinpe

**Comment by npepinpe** [comment]
I mean, you can see from the comment, it was bound to become flaky :smile: 

```
              // wait a sufficiently high enough invocation count to ensure the second timer is
              // expired, gets scheduled, and then the executions are interleaved. this is quite
              // hard to do in a deterministic controlled way because of the way our timers are
              // scheduled
              if (invocationCount < 5000) {
                return -1L;
              }
```

I think we just need to find a better way of writing this test.

**Comment by npepinpe** [comment]
Furthermore, I don't think the test explicitly waits for both timers to be invoked. Instead, the wait happens when it's waiting for the invocation count of tryWrite to hit at least 5000 within 2 seconds. We could instead force it to wait until both timers are executed, though...I don't know, 2 seconds should normally be enough of a timeout. Unless it hit some unfortunate GC pause? :thinking:

**Comment by deepthidevaki** [comment]
I have opened a PR that increases the timeout and wait for the timers to be executed before verifying. This does not improve determinism. I was wondering if `ControlledActorSchueduler` would be better suitable for these tests?

**Comment by npepinpe** [comment]
It might. I had a quick look I think, but since `workUntilDone` doesn't consider timers, it wasn't super straightforward. But maybe a combination of modifying the clock and workUntilDone would work.
