### ISSUE TITLE
Set Escalation BpmnEventType

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#10890]
## Description
We should make sure we export the correct event type for Escalation events.

- Set the event type to Escalation in the `StartEventTransformer`
- Set the event type to Escalation in the `BoundaryEventTransformer`
- Set the event type to Escalation in the `IntermediateThrowEventTransformer`
- Set the event type to Escalation in the `EndEventTransformer`
- Set the event type to Escalation int he `CatchEventTransformer`
- Expand the `BpmnEventTypeTest` with testcases for all these cases

**Comment by skayliu** [comment]
Hi, @remcowesterhoud, the `CatchEventTransformer` is missed.

**Comment by remcowesterhoud** [comment]
@skayliu Good catch! I'll add it to the issue
