### ISSUE TITLE
Allow 8.0 patch releases to skip docker verify step

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#10895]
**Description**
The release pipeline has as the last step to build, verify and upload a docker image. The verify step is simply a shell script that is executed, but this file is missing from the 8.0 branch.

>15:32:53 + ./docker/test/verify.sh camunda/zeebe:8.0.8
>15:32:53 /home/jenkins/agent/workspace/zeebe-docker@tmp/durable->02e9a64f/script.sh: line 1: ./docker/test/verify.sh: not found

This blocked the release of 8.0.8, but I was able to circumvent the problem by  starting the 'Docker Image' pipeline manually with parameters (where I was able to skip the verify step).

Note that Jenkins doesn't use the pipeline code from the stable/8.0 branch when starting the docker image step, but it uses the code from `main`. This is why the verification is not skipped, even though [this line](https://github.com/camunda/zeebe/blob/stable/8.0/.ci/pipelines/release_zeebe.groovy#L156) exists.

Failed pipelines:
- https://ci.zeebe.camunda.cloud/job/zeebe-release/297/
- https://ci.zeebe.camunda.cloud/job/zeebe-docker/2895/

**Comment by remcowesterhoud** [comment]
For some reason the merged PR didn't close this one 😱
