### ISSUE TITLE
I can set  Input/output variable mappings in Manual Task and Undefined Task

### ISSUE THREAD

**Issue by skayliu** [camunda/zeebe#10901]
**Is your feature request related to a problem? Please describe.**
As a user, I want to set  `Input/output variable mappings` in `Manual Task` and `Undefined Task` just like we did in C7 (e.g. Initialize Variables ).

And in C8, all the other tasks can set `Input/output variable mappings`.

**Describe the solution you'd like**
Allow to set  `Input/output variable mappings` in `Manual Task` and `Undefined Task` in C8 as others task did.

**Describe alternatives you've considered**
Use start event or the other tasks

**Additional context**
[C7: input/output mapping for all tasks](https://docs.camunda.org/manual/latest/reference/bpmn20/custom-extensions/extension-elements/#inputoutput)
[C8: service-tasks/#variable-mappings](https://docs.camunda.io/docs/components/modeler/bpmn/service-tasks/#variable-mappings)

**Comment by felix-mueller** [comment]
From BPMN perspective I find it a bit strange to add / edit variables in Undefined Tasks / Manual Tasks. 
Wouldnt it be better to make this mapping / transformation explicit or alternatively use e.g. a Script Task Input/Output?

**Comment by skayliu** [comment]
>Wouldnt it be better to make this mapping / transformation explicit or alternatively use e.g. a Script Task Input/Output?

Hey, @felix-mueller , with [feat(engine): support feel expression bpmn script tasks #10775](https://github.com/camunda/zeebe/pull/10775) feature, we can  use  `Script Task` .

**Comment by felix-mueller** [comment]
> Hey, @felix-mueller , with https://github.com/camunda/zeebe/pull/10775 feature, we can use Script Task .

Does this mean we should close it? :)

**Comment by skayliu** [comment]
Yes, Let's close it.
