### ISSUE TITLE
Daily QA is not run for stable branches

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#10915]
We are still running daily QA test for [stable/1.3](https://bru-3.operate.ultrawombat.com/7b2cd3f5-cfcc-4a65-ab22-0ccaa071e68e/processes?process=qa-protocol&version=1&active=true&incidents=true&completed=true&canceled=true&sort=endDate%2Bdesc&variableName=branch&variableValue=%22stable%2F1.3%22). But found no tests for stable/8.0 and [stable/8.1](https://bru-3.operate.ultrawombat.com/7b2cd3f5-cfcc-4a65-ab22-0ccaa071e68e/processes?process=qa-protocol&version=1&active=true&incidents=true&completed=true&canceled=true&sort=endDate%2Bdesc&variableName=branch&variableValue=%22stable%2F8.1%22)

**Comment by npepinpe** [comment]
Proposal:

- [ ] Disable QA for stable/1.3 by removing the cron trigger in Jenkins
- [ ] Transform `qa-testbench` and `e2e-testbench` to be matrix jobs over specific branches, starting with `main`, `stable/8.0`, and `stable/8.1`
- [ ] Update release process to add a task to update these branches on minor/major releases

Let me know if this doesn't make sense

**Comment by deepthidevaki** [comment]
We can make these workflows on stable branches as well, right? What are the consequences of it? If we want to trigger on-demand QA on specific branch, wouldn't it use the workflow from that branch? Or would it use the workflow from the main and use a specific input field to choose the branch to run the qa?

**Comment by npepinpe** [comment]
I think it becomes more of a problem with reusable action. As soon as you do a checkout of a different branch, then it will look up the action in that branch, and not the branch which triggered the initial workflow run.

**Comment by npepinpe** [comment]
It seems you can specify the branch you want for the reused workflow/action. I'm still not sure what's the expectation here :thinking: Would you expect the workflow/reusable action definition to be:

1. From the branch which triggered the workflow (e.g. main)
2. From the branch which you want to build/test (e.g. stable/8.1)

:thinking:

**Comment by npepinpe** [comment]
To simplify things, I will focus on the daily QA here, so the plan is:

- [ ] Add a new daily-qa workflow which controls the scheduling of the `qa-testbench` workflow
- [ ] New workflow automatically computes the latest stable versions
- [ ] Runs the `qa-testbench` with appropriate params for each stable branches, once a day
- [ ] Scheduling is removed from `qa-testbench`, which can now only be started explicitly
- [ ] Follow up issue to adapt e2e-testbench to this

The reason I'm splitting it out is that they're both configured differently but have a lot of overlap, so instead I would propose a follow up which streamlines the qa-testbench and e2e-testbench workflows, then adds the e2e to the daily QA. And in the first PR we can focus on just the daily QA and fixing the immediate problem.

**Comment by npepinpe** [comment]
Follow up issue: https://github.com/camunda/zeebe/issues/11021
