### ISSUE TITLE
Cannot change gateway config with environment variables

### ISSUE THREAD

**Issue by hmeniz** [camunda/zeebe#10927]
**Describe the bug**

We can't change gateway configs with environment variables which created with docker compose.

**To Reproduce**

docker-compose file zeebe
zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    container_name: zeebe
    restart: on-failure
    ports:
      - "26500:26500"
      - "9600:9600"
    environment: # https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/environment-variables/
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      # allow running with low disk space
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
      - ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS=4
      - ZEEBE_BROKER_THREADS_CPUTHREADCOUNT=4
      - ZEEBE_BROKER_THREADS_IOTHREADCOUNT=4
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=4
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=4
      - ZEEBE_GATEWAY_LONGPOLLING_ENABLED=false
    volumes:
      - zeebe:/usr/local/zeebe/data
    networks:
      - camunda-platform
    depends_on:
      - elasticsearch

**Expected behavior**

It should be longpolling false and managementthreads 4, but they are same as default.

**Log/Stacktrace**

2022-11-07 09:29:05.363 [] [main] INFO 
      io.camunda.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "172.18.0.4",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "172.18.0.4",
    "commandApi" : {
      "host" : "172.18.0.4",
      "port" : 26501,
      "advertisedHost" : "172.18.0.4",
      "advertisedPort" : 26501,
      "address" : "172.18.0.4:26501",
      "advertisedAddress" : "172.18.0.4:26501"
    },
    "internalApi" : {
      "host" : "172.18.0.4",
      "port" : 26502,
      "advertisedHost" : "172.18.0.4",
      "advertisedPort" : 26502,
      "address" : "172.18.0.4:26502",
      "advertisedAddress" : "172.18.0.4:26502"
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1, 2, 3, 4 ],
    "nodeId" : 0,
    "partitionsCount" : 4,
    "replicationFactor" : 1,
    "clusterSize" : 4,
    "clusterName" : "zeebe-cluster",
    "heartbeatInterval" : "PT0.25S",
    "electionTimeout" : "PT2.5S",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    },
    "raft" : {
      "enablePriorityElection" : true
    },
    "messageCompression" : "NONE"
  },
  "threads" : {
    "cpuThreadCount" : 4,
    "ioThreadCount" : 4
  },
  "data" : {
    "directory" : "/usr/local/zeebe/data",
    "logSegmentSize" : "128MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.999,
    "diskUsageCommandWatermark" : 0.998,
    "diskUsageMonitoringInterval" : "PT1S",
    "backup" : {
      "store" : "NONE",
      "s3" : {
        "bucketName" : null,
        "endpoint" : null,
        "region" : null,
        "accessKey" : null,
        "secretKey" : null,
        "apiCallTimeout" : "PT3M"
      }
    },
    "logSegmentSizeInBytes" : 134217728,
    "freeDiskSpaceCommandWatermark" : 538980786,
    "freeDiskSpaceReplicationWatermark" : 269490393
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.camunda.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "bulk" : {
          "size" : "1"
        },
        "url" : "http://elasticsearch:9200"
      },
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "initialContactPoints" : [ "172.18.0.4:26502" ],
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "172.18.0.4",
      "advertisedHost" : "172.18.0.4",
      "port" : 26502,
      "advertisedPort" : 26502,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      },
      "security" : {
        "enabled" : false,
        "certificateChainPath" : null,
        "privateKeyPath" : null
      },
      "messageCompression" : "NONE"
    },
    "threads" : {
      "managementThreads" : 1
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "interceptors" : [ ],
    "initialized" : true,
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "32KB",
    "disableExplicitRaftFlush" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "enableStatistics" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1,
      "maxWriteBufferNumber" : 6,
      "minWriteBufferNumberToMerge" : 3,
      "ioRateBytesPerSecond" : 0,
      "disableWal" : false
    },
    "raft" : {
      "requestTimeout" : "PT5S",
      "maxQuorumResponseTimeout" : "PT0S",
      "minStepDownFailureCount" : 3,
      "preferSnapshotReplicationThreshold" : 100,
      "preallocateSegmentFiles" : true
    },
    "partitioning" : {
      "scheme" : "ROUND_ROBIN",
      "fixed" : [ ]
    },
    "queryApi" : {
      "enabled" : false
    },
    "consistencyChecks" : {
      "enablePreconditions" : false,
      "enableForeignKeyChecks" : false,
      "settings" : {
        "enablePreconditions" : false,
        "enableForeignKeyChecks" : false
      }
    },
    "features" : {
      "enableYieldingDueDateChecker" : false,
      "enableActorMetrics" : false,
      "enableBackup" : false
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "executionMetricsExporterEnabled" : false
}

**Environment:**
- OS: Docker Desktop 4.13.1
- Zeebe Version: 8.1.3
- Configuration: 
-
[docker-compose.zip](https://github.com/camunda/zeebe/files/9950137/docker-compose.zip)

**Comment by npepinpe** [comment]
Hi @hmeniz, if you're using the embedded gateway, then you should use the prefix `ZEEBE_BROKER_GATEWAY` for the gateway config. `ZEEBE_GATEWAY` as a prefix is for the standalone gateway. So:

```yaml
ZEEBE_BROKER_GATEWAY_LONGPOLLING_ENABLED: false
ZEEBE_BROKER_GATEWAY_THREADS_MANAGEMENTTHREADS: 4
```

Let me know if that helps.

**Comment by hmeniz** [comment]
Thank you, it worked :) It might be helpful to have it in the gateway.yaml.template file.
