### ISSUE TITLE
`LogStreamWriter#tryWrite` should accept records and record batches directly

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10924]
`tryWrite` should accept record and record batches, types that are already defined in the engine as [`ImmutableRecordBatch`](https://github.com/camunda/zeebe/blob/adfa3427857e33d8b26d89cdfeb6a2ea2afd8122/engine/src/main/java/io/camunda/zeebe/engine/api/records/ImmutableRecordBatch.java) and  [`ImmutableRecordBatchEntry`](https://github.com/camunda/zeebe/blob/adfa3427857e33d8b26d89cdfeb6a2ea2afd8122/engine/src/main/java/io/camunda/zeebe/engine/api/records/ImmutableRecordBatchEntry.java).

This way, the `LogStreamWriter` implementation doesn't have to buffer batch entries until `tryWrite` is called.

**Comment by oleschoenburg** [comment]
https://github.com/camunda/zeebe/pull/10979 introduces such a module. We can wait for it to be merged before working on this issue.

**Comment by Zelldon** [comment]
We could also merge logstreams with streamplatform

**Comment by npepinpe** [comment]
I'd propose keeping them separate until the shape of the stream platform module is clear. I think it probably makes sense, but it's not 100% clear to me yet, so we'll need some solution already now before this happens :smile:

**Comment by Zelldon** [comment]
>  until the shape of the stream platform module is clear

Maybe you could clarify what is not clear :D than we could maybe go directly in that direction.

**Comment by npepinpe** [comment]
It's not clear to me, maybe it's already clear to everyone else :smile: 

Correct me if I'm wrong:

1. The journal is the "bottom" most module, i.e. the one which knows nothing about anyone, and is the lowest layer of persistence, sitting right on top of the file system/OS. It supports multiple readers, but only a single writer.
2. Then we have the Raft module which is the only writer/appended to the journal, and also reads from it (but independently from others). It adds its own Raft specific data framing to each entry in the journal, and allows reading it back.
3. Next we have the log stream, which sits on top of the Raft module (indirectly). With the replacement of the dispatcher, the log stream will know provide a many-to-one interface to read and write from the Raft log. It also performs (de)serialization of application entries.
4. Finally the stream platform. It provides the "motor" to continuously process/replay the logstream.

I do think the responsibilities are quite distinct between the stream platform (i.e. continuous streaming) and the log stream (i.e. another framing layer on top of the Raft log which unwraps the application entries), so to me it makes sense they're separate. But like I said, after all this refactoring, it feels like I'm missing a bit of the big picture.

**Comment by npepinpe** [comment]
As the `ImmutableBatchRecordEntry` is only used by the stream platform, we'll move it to the logstream. The engine still isn't using it regardless.
