### ISSUE TITLE
`LogStorageAppender` should use `Sequencer` and `Serializer` instead of `Dispatcher`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10921]

**Comment by npepinpe** [comment]
As part of this, or as a sub task, we should adapt the serializer introduced in #11117 so that it works without the dispatcher, but keeps the framing around as padding to be backwards compatible.

**Comment by npepinpe** [comment]
Blocked by:

- https://github.com/camunda/zeebe/issues/10924
- https://github.com/camunda/zeebe/issues/10919
- https://github.com/camunda/zeebe/issues/10920
