### ISSUE TITLE
Define an escalation code statically or as expression

### ISSUE THREAD

**Issue by lzgabel** [camunda/zeebe#10973]
**Is your feature request related to a problem? Please describe.**
 For an escalation intermediate/end event, I can define the `escalationCode` as a string or dynamically as an expression.

**Describe the solution you'd like** 
Same as in #3792.
 
**Additional context** 
Currently, escalation catch events are not materialized as subscriptions in the state. When an escalation is thrown then the handler walks through the scope hierarchy and checks the escalation codes. In order to be consistent with timer and message events, the `escalation` expression must be evaluated when the event scope is activated.

**Comment by menski** [comment]
@felix-mueller we can see the use case for throwing events having the support of an expression, for catching events we are unsure if this is a valid use case. It will increase the complexity implementation, and might be something we could evaluate after the first iteration if we receive feedback from customers about there use cases.

@lzgabel thanks for raising it. We don't see it at the moment in the scope of the first iteration, therefore would not prioritize it at this moment. If you have a specific use case for this feature it would be great if you could share this with us to better understand the requirements.

**Comment by lzgabel** [comment]
Hi @menski. Thanks for your reply. Let me clarify my usage scenario, I hope that after `Task A` is completed, the corresponding escalation catch event can be selected to activate according to the evaluation variables.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/24605947/201318247-e8f4f934-f195-454d-80a6-521383e22597.png">

---

Of course, we can currently achieve this requirement by using an exclusive gateway, but if this feature can be implemented, the modeling complexity will be greatly reduced.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/24605947/201318509-7064a2f0-025b-46ff-8502-b46b53d125b8.png">

**Comment by menski** [comment]
Thanks for the input @lzgabel, based on the use case you shared I assume that your feature request is mainly focused on throwing error events, and not the catch/boundary event, to eliminate the need of the exclusive gateway. Is that assumption correct?

**Comment by lzgabel** [comment]
> focused on throwing error events, and not the catch/boundary event, to eliminate the need of the exclusive gateway. Is that assumption correct?

👍 Yes, at the moment, in my case, the priority of the catch/boundary event can be lowered. 

Hopefully the team can assess the scope that needs to be supported in this iteration. (feel free to change the scope of this issue. )

---

As always, I can contribute to this. :beer:

**Comment by remcowesterhoud** [comment]
@lzgabel we are happy to support expressions for throw events

**Comment by lzgabel** [comment]
Great! 💯 

@remcowesterhoud Thanks for your reply. 🤝   I'll submit a pr soon. 🥇
