### ISSUE TITLE
Throw error with variables from go client

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#11019]
**Is your feature request related to a problem? Please describe.**
It's possible to pass variables along when throwing an error for a job in the java-client, but this is not yet available in the go client.

**Describe the solution you'd like**
Provide the same support from the go client, by allowing users to pass variables along with the thrown error.

Variables can already be passed along for job completion and failure, so this can be used as an implementation example.

**Describe alternatives you've considered**
🤷 

**Additional context**
- #10882
- https://github.com/camunda/zeebe/issues/4337
- https://github.com/camunda/zeebe/issues/9473
- https://github.com/camunda/zeebe/issues/4080
- https://github.com/camunda/product-hub/issues/243

**Comment by lzgabel** [comment]
Hi @korthout. Please assign this task to me, thanks. ❤️
