### ISSUE TITLE
FolderPrefixes for Hot Backups

### ISSUE THREAD

**Issue by Sijoma** [camunda/zeebe#11018]
**Is your feature request related to a problem? Please describe.**
Creating a new bucket for every Zeebe Cluster that I provision is painful. As this means I need to adjust my cloud infrastructure while I deploy the application to Kubernetes.

**Describe the solution you'd like**
Zeebe should support a folderPrefix / basePath for the backup configuration. This would then allow to split the backups in the same bucket. Consequently, I would only need to create a single bucket for all my Zeebe instances. 

**Describe alternatives you've considered**
-

**Additional context**
Elasticsearch does this with a "basePath" on the repository: https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-s3.html#repository-s3-repository

**Comment by felix-mueller** [comment]
@megglos @deepthidevaki do you think this is sth. we could do still in this iteration or next?
