### ISSUE TITLE
Streamline Testbench based workflows

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11021]
**Description**

We currently have two workflows which run different test suites/processes on Testbench. They share quite a lot of overlap:

- Set up the same environment
- Set up shared environment variables
- Building a Zeebe Docker image out of a specific branch
- Authenticating to GCR
- Authenticating to Testbench
- Starting a process instance of a specific process in Testbench with a specific payload

Deepthi already started some effort in that direction by introducing a reusable action, but it's only used in the `e2e-testbench` workflow, which means changes still need to be done in both.

Once this is done, we should also run the E2E tests as part of the Daily QA workflow.

**Comment by megglos** [comment]
@npepinpe let's follow-up on Monday

**Comment by megglos** [comment]
It seems like it would be most promising to setup one workflow to "rule them all" meaning whether qa and/or e2e are run would be controllable via inputs but than can be figured out when we actually work on it.
@deepthidevaki does that sound reasonable from your perspective as well?

**Comment by deepthidevaki** [comment]
> It seems like it would be most promising to setup one workflow to "rule them all" meaning whether qa and/or e2e are run would be controllable via inputs but than can be figured out when we actually work on it. @deepthidevaki does that sound reasonable from your perspective as well?

:+1:
