### ISSUE TITLE
i got a problem when i compile zeebe project

### ISSUE THREAD

**Issue by gakkiyomi** [camunda/zeebe#11030]
i want to try compile zeebe project,but i got a error when mvn tasking

environment:
1.os:  macOS Monterey
2. jdk version:      OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)
3. source code : branch main

i to try execute mvn command
`mvn clean install -Dpmd.skip=true -Dcheckstyle.skip=true -DskipTests`

got a error in my console
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java (default) on project zeebe-protocol: Execution default of goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java failed: Plugin org.codehaus.mojo:exec-maven-plugin:3.1.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:exec-maven-plugin:jar:3.1.0 -> uk.co.real-logic:sbe-tool:jar:1.27.0 -> org.agrona:agrona:jar:[1.17.1,2.0): No versions available for org.agrona:agrona:jar:[1.17.1,2.0) within specified range -> [Help 1]
`
![image](https://user-images.githubusercontent.com/41406557/202425632-50049652-53f6-4c91-a9a5-1f7479655494.png)

**Comment by gakkiyomi** [comment]
i need help

**Comment by saig0** [comment]
@gakkiyomi this is a known Maven issue. Try to delete the folder `~/.m2/repository/org/agrona/` and rebuilt the project.

**Comment by megglos** [comment]
closing as a potential fix was suggested.

@gakkiyomi hope you got unblocked by @saig0 here, please feel free to ping if you still need help! :)
