### ISSUE TITLE
After unrecoverable errors, `ZeebePartition` accesses closed raft context

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11070]
**Describe the bug**

When handling unrecoverable errors, `ZeebePartition` shuts down the raft context:
https://github.com/camunda/zeebe/blob/e15428b1c94bf7e0f7d5c234b7b5543daccf2adb/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java#L377

which triggers an async transition to inactive: https://github.com/camunda/zeebe/blob/ae10d8f6d99a6402564f6e8bab56dc3f22e2e36a/atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java#L135

Because this transition is async, the `ZeebePartition` continues to run on a closed raft context which can cause various issues, for example attempts to access a closed journal. This can then cause further issues, for example failed transitions.

**Expected behavior**

When the `ZeebePartition` decides to close the raft context, it should first remove itself as a role change listener, trigger the transition to `INACTIVE` itself and only close the raft context on completion of the transition.

related to #10776

**Comment by megglos** [comment]
Impact: as of now Log noise if a partition is dead, potential for critical bugs
Will put into ready to get it solved before it becomes an issue.
