### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11106]
**Describe the bug**

During my medic shift I checked the recent medic week benchmarks and observed that we might have a new memory leak. The process memory seem to always increase but never goes back and we have some benchmarks where pods have been restarted due to OOM.

I think it already started in week 43 (this is the last benchmark I can see)
![mem43](https://user-images.githubusercontent.com/2758593/204228605-4fb51247-4118-45a4-9b58-93fb8277dcb3.png)

In Week 46 we can see a pod restart due to OOM.
![mem46](https://user-images.githubusercontent.com/2758593/204228610-05e2f4a2-a83d-4ef9-af33-a736dc3bc70c.png)
In the mixed benchmark as well.
![mem46-mixed](https://user-images.githubusercontent.com/2758593/204228621-b380f543-bfa5-4ac7-b045-b6cef81ba83e.png)

In the last week benchmark (47) we can still see that the memory consumption just grows.
![mem47](https://user-images.githubusercontent.com/2758593/204228624-f696afd3-2fd0-43d4-8a50-3a50350a5732.png)

Taking a look at the memory details there is not really something we can pin point, but we can see it is constantly growing until restart.
![mem46-detail](https://user-images.githubusercontent.com/2758593/204228613-255a2757-66f9-4f90-a24d-88b403cf42d3.png)

The only thing I can see that we do install requests at the same time, which might be related.
![mem46-install](https://user-images.githubusercontent.com/2758593/204228616-8b339f7d-ad2f-4929-af50-d550ecb2e892.png)

**To Reproduce**

Run the benchmarks.

**Expected behavior**

That memory consumption is stable and no OOM.

**Log/Stacktrace**
None

**Environment:**
Medic benchmark

**Comment by fvogl** [comment]
We are affected by this also at version 8.1.4.

**Comment by Zelldon** [comment]
This wasn't observed in the recent medic benchmarks (last 4 weeks) so I will close it for now.
