### ISSUE TITLE
Anomalous execution time metrics reported in medic benchmarks

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11107]
**Describe the bug**

In our most recent benchmarks we can see a really high process instance execution and job activation latency, which look a bit unreal and wrong.

**Medic Benchmark 46**
![latency-46](https://user-images.githubusercontent.com/2758593/204238216-057b5c18-a162-49d9-be54-a12ab4554b30.png)
**Medic Benchmark 46 Mixed**
![latency-46-mixed](https://user-images.githubusercontent.com/2758593/204238219-a65c443e-f93a-4891-b07d-671190b45d5d.png)
**Medic Benchmark 47 Mixed**
![latency-47-mixed](https://user-images.githubusercontent.com/2758593/204238222-989b093c-d19c-45f6-864d-e02352445a63.png)

I'm not sure but it might be related to the exporters not keeping up with the data, since the metrics are collected by the metric exporter.

**Medic Benchmark 46**
![latency-46-export](https://user-images.githubusercontent.com/2758593/204238428-16bc6dea-772d-4f76-8505-7bb7aad8928d.png)

**Medic Benchmark 46 Mixed**
![latency-46-mixed-export](https://user-images.githubusercontent.com/2758593/204238432-00c9d293-3196-448e-89ec-9bbf0e52e539.png)

**Medic Benchmark 47 Mixed**
![latency-47-mixed-export](https://user-images.githubusercontent.com/2758593/204238435-8cd87d27-e586-489d-91d8-1539674e4c23.png)

Furthermore, it looks like the elastic search exporter latency (flush issues) can influence our latency metrics which we collect via the metric exporter. Since if one of the exporters gets stuck all stuck, and only continues when elastic is available or accepts new commands.

**To Reproduce**

Not sure. I guess running a benchmark.

**Expected behavior**

Not that high latency.

**Log/Stacktrace**
None
**Environment:**
Medic benchmarks

**Comment by Zelldon** [comment]
This is likely due to elastic search unavailability and the metrics exporter not being able to exporter more metrics. 

Might make sense to think again about that how we export, or how we collect these metrics.

**Comment by Zelldon** [comment]
So it is indeed something related to pod restarts and what has been described here https://github.com/camunda/zeebe/issues/11814 by @npepinpe 

If we find an fix with https://github.com/camunda/zeebe/issues/11814 we should also resolve this one, which is why I will put it back into the backlog again.

**Comment by npepinpe** [comment]
There is a quick fix, which is to suffix all histogram queries with `!= 0` to filter out buckets with no samples.

**Comment by npepinpe** [comment]
Done via https://github.com/zeebe-io/infra/pull/42
