### ISSUE TITLE
Support the on-boarding project by introducing forms to Zeebe-Play 

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#11228]
**Description**

A task to support the onboarding project. In the [current experiment](https://github.com/camunda/product-hub/issues/729), the team wants to integrate user task forms into Zeebe-Play. The goal is to empower human task orchestration.

As a dev of the Zeebe team and author/maintainer of the related community projects, I can help to team to make rapid progress.  

Related product hub issue: https://github.com/camunda/product-hub/issues/729

**Comment by Zelldon** [comment]
@saig0 do we need this issue here?

**Comment by saig0** [comment]
The issue was created to track my work. Since I finished this part, I can close the issue. :+1:
