### ISSUE TITLE
Fail command requests on log stream writer error

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11242]
**Description**

We currently silently drop the command requests on log stream errors:

https://github.com/camunda/zeebe/blob/336a7544104683f188d3c7fa83ed5e6d07e10b47/broker/src/main/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiRequestHandler.java#L114-L125

This is completely unobservable behavior - no metrics, no logging, etc., to indicate the request is lost. The gateway will then "timeout" on this request, which is poor UX.

It's unclear to me what the proper behavior should be OTOH, but at the very least we should be able to observe a request being dropped to avoid wasting time debugging the wrong thing.

**Comment by Zelldon** [comment]
I have added just for visibility logging on my benchmark branch and was able to see that one request was dropped.



[NOT WRITTEN ACTIVATE for partition 2, requestId 91, metadata RecordMetadata{recordType=COMMAND, intentValue=0, intent=ACTIVATE, requestStreamId=2, requestId=91, protocolVersion=3, valueType=JOB_BATCH, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.2.0}](https://console.cloud.google.com/logs/query;query=error_group%2528%22COO5guijibqJtgE%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.namespace_name%3D%2258d3904b-96c5-4593-879e-b0fc84b806db-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22;timeRange=2022-12-15T14:05:10.392Z%2F2022-12-15T15:05:10.392Z;cursorTimestamp=2022-12-15T14:34:40.392951899Z?project=camunda-cloud-240911)

**Comment by deepthidevaki** [comment]
This is covered in https://github.com/camunda/zeebe/pull/12676.
