### ISSUE TITLE
Scheduled release dry runs to verify the release workflow works with main and all stable branches

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#11259]
In order to continuously ensure our release workflow is functional, nightly dry runs should be performed based on the following branches:

- [x] main
- [x] all stable branches currently supported

That leaves still some "blind spots" being the actual credential setup to push to remote (git, create github release, dockerhub) but it can be argued these are acceptable. Also considering that some shared credentials are used by other jobs already (nexus & dockerhub by deploying snapshot artifacts) and that maven central credentials originate from a secret vault that is used by multiple camunda teams already.

**Comment by Zelldon** [comment]
Makes sense just wanted to bring it up early :)
