### ISSUE TITLE
Support catch-all and code-specific Escalation catch events on the same scope

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#11265]
**Is your feature request related to a problem? Please describe.**
Currently, a catch-all Escalation catch event is mutually exclusive with code-specific Escalation catch events on the same scope, i.e. you can use one or the other.

**Describe the solution you'd like**
As a user, in a given scope, I can define:
* A single Escalation catch event with no escalation code defined (a catch-all Escalation event).
* Multiple Escalation catch events with a defined escalation code.

**Describe alternatives you've considered**
/

**Additional context**
The behavior would enable the following use-case:
As a user, I can define a specific response for a known escalation code, and a general response for unknown escalation codes.

**Comment by lzgabel** [comment]
Hi @koevskinikola. Please assign this task to me. :bow:

**Comment by koevskinikola** [comment]
:information_source: The change doesn't require any changes from downstream projects.

Catch-all Escalation events already exist. With the changes from this issues, we allow catch-all and code-specific Escalation events to be created on the same scope.
