### ISSUE TITLE
Possible to open multiple message subscriptions for the same event

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#11308]
**Describe the bug**

When a user deploys the same process multiple times without changes, additional message start event subscriptions are opened, if there are top-level message start events present in the process.

This does not lead to issues because published messages only create a single instance, but strangely, additional message subscriptions are opened.

<img width="1904" alt="Screen Shot 2022-12-20 at 18 18 03" src="https://user-images.githubusercontent.com/3511026/208727774-06cf7c07-4dd2-4dd2-90c1-7def0b4d5ce6.png">

<img width="1904" alt="Screen Shot 2022-12-20 at 18 22 43" src="https://user-images.githubusercontent.com/3511026/208727888-a5cef004-2293-4c24-8874-eed8e9de8f86.png">

**To Reproduce**

- run Zeebe Play
- deploy a simple process with a top-level message start event
- deploy the same process again
- in Zeebe Play, notice the secondary message subscription

**Expected behavior**

Only a single message subscription exist for any message event at any time.

**Comment by korthout** [comment]
I'm giving this low severity because there is no user impact.

**Comment by skayliu** [comment]
Hey, @korthout, i dig a little bit, when deploy the same process again, we can find the `processesMetadata.duplicate` is `true`.

We have check top-level time start event `isDuplicate` at [DeploymentCreateProcessor.java#L129](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java#L129), bud the others are not.

```        
"processesMetadata":[
            {
                "version":6,
                "bpmnProcessId":"Process_0k1nnh5",
                "processDefinitionKey":2251799813685489,
                "checksum":"+tH+Q1NPNoxIlEKqMgHBQw==",
                "resourceName":"Process_0k1nnh5.bpmn",
                "duplicate":true
            }
        ]
```

**Comment by korthout** [comment]
@skayliu Thanks for looking into this.

>We have check top-level time start event isDuplicate at [DeploymentCreateProcessor.java#L129](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java#L129), bud the others are not.

👍 Good find! Adding that check for the other start event subscriptions could be a good solution.

- #6314 

This is not related.

- #6480 

This is not caused by this, but could probably be solved similarly using your suggestion.
