### ISSUE TITLE
One gateway is always prefered

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11310]
**Describe the bug**

During investigating https://github.com/zeebe-io/zeebe-chaos/issues/294 I introduced several metrics to see where request go etc. I have seen during observing the metrics that often only one gateway is preferred when sending requests to the Zeebe cluster. I was not sure where to create this issue tbh, and whether it is a problem at all. For me, it feels a bit awkward that we can have multiple gateways but no real load balancing happens. I have seen this in a self-managed environment and in SaaS. 

I think it might be related to how we wrote out clients? We create one channel and keep that open during the time of using the client. Maybe this is related.

![requests](https://user-images.githubusercontent.com/2758593/208758685-0550ee7f-024e-4da4-9f5e-8aadbc59f6f4.png)

![requests-gw](https://user-images.githubusercontent.com/2758593/208759353-a0689286-cd06-440b-a1c9-cc3331aa7929.png)

**To Reproduce**

I will add sone metrics to the network layer, then you can just run a benchmark and will see it.

**Expected behavior**
There is an even distribution of requests to the gateways.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by megglos** [comment]
Relates to Helm Charts, Distribution Team as well as SRE.
@megglos reaches out to them

**Comment by Zelldon** [comment]
Opened https://github.com/camunda/camunda-platform-helm/issues/561 on helm charts

**Comment by npepinpe** [comment]
Can we close this? I think this is pretty specific to our Helm chart and set up, and not a Zeebe/gateway specific thing.
