### ISSUE TITLE
ARM64 image troubleshooting guide

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#11318]
With the addition of arm64 images in the context of #10986 it was raised that some instructions on how to run/debug arm64 images locally on non arm64 platforms would be worth adding.

**Comment by felix-mueller** [comment]
@megglos can I just run them with docker-compose or kind or do I need to adjust anything?

**Comment by megglos** [comment]
@felix-mueller if you just use docker-compose or any other docker commands the docker client will automatically use the image that fits your platform, without further ado.

This task is about instructions on how to instruct docker to use a specific platform image, different from the host. So just for engineers to be able to investigate if there are any issues with just a specific platform.

**Comment by felix-mueller** [comment]
thanks for the additional context :) @megglos this helps!
