### ISSUE TITLE
Wrong QA Run failure reports

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11328]
**Description**

Right now we run several QA run's nightly, for the last versions: 8.0, 8.1 and main. They are started in parallel and waiting for a result from testbench to report whether they are succeeded or not. 

In order to communicate with testbench they are try to activate an job and retrieve the details/results as variables. The issue is that all started jobs using the same job type, which means it is not guaranteed whether the same github job, which started an instance for a version retrieves the same zeebe job with an equal version.

Recently it happened that we got an error message, reported for main, but at the end it turned out it was for the 8.0 branch, because an fix was not yet backported. See https://camunda.slack.com/archives/C013MEVQ4M9/p1671693210017859

**Possible solutions**

* Use a more unique job type, but it looks like we are not able to retrieve the job id during running the job (at least not on a easy way) https://stackoverflow.com/questions/71240338/obtain-job-id-from-a-workflow-run-using-contexts
* Remove this part of waiting for the result, and just rely on testbench notifications. Maybe add to testbench that it also notifies on success

**Comment by korthout** [comment]
@Zelldon How do you feel about having our medic look into this issue?

**Comment by Zelldon** [comment]
Would be fine by me @korthout :+1:

**Comment by deepthidevaki** [comment]
This should not be a problem anymore with the recent changes to the workflow #11508

**Comment by Zelldon** [comment]
@deepthidevaki can you elaborate a bit? Did we removed the await result now?

**Comment by deepthidevaki** [comment]
The [task is replaced by a slack connector](https://github.com/camunda/zeebe/pull/11508#discussion_r1093314412) which notifies about success or failure. So no need to wait for it in the github action.
The [PR for it is awaiting your review](https://github.com/zeebe-io/zeebe-cluster-testbench/pull/754), btw.

**Comment by Zelldon** [comment]
Thanks
