### ISSUE TITLE
Potential leak in Gateway "LEAK: ByteBuf.release() was not called before it's garbage-collected"

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#11329]
**Describe the bug**

Observed in medic-cw-47 benchmark gateway: 
```
LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.AbstractByteBufAllocator.compositeDirectBuffer(AbstractByteBufAllocator.java:224)
	io.netty.buffer.AbstractByteBufAllocator.compositeBuffer(AbstractByteBufAllocator.java:202)
	io.grpc.netty.NettyAdaptiveCumulator.cumulate(NettyAdaptiveCumulator.java:86)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Unknown Source)
```
Followed by
```
Terminating due to java.lang.OutOfMemoryError: Java heap space
```
[Logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-12-18T18:21:31.013806899Z;pinnedLogId=2022-12-18T18:21:31.013806899Z%2F4htofvepfwx2bvsf;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.namespace_name%3D%22medic-cw-47-e9a0ad0a19-benchmark%22%0Aresource.labels.container_name%3D%22zeebe-gateway%22%0Aresource.labels.pod_name%3D%22medic-cw-47-e9a0ad0a19-benchmark-zeebe-gateway-794f577676-5ptrw%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Atimestamp%3D%222022-12-18T18:21:31.013806899Z%22%0AinsertId%3D%224htofvepfwx2bvsf%22;timeRange=2022-12-18T17:52:01.013Z%2F2022-12-18T18:52:01.013Z?project=zeebe-io)

**To Reproduce**

Run medic benchmark with following configuration:
(Configuration taken from cw-48 benchmark. cw-47 was already deleted).

Gateway resource:
```
    Limits:
      cpu:     450m
      memory:  400Mi
    Requests:
      cpu:      450m
      memory:   400Mi
```
Starter : `-Dapp.starter.rate=75`

Broker resources:
```
    Limits:
      cpu:     960m
      memory:  4Gi
    Requests:
      cpu:      800m
      memory:   2Gi
```

Observed only twice so far. So not sure how easy to reproduce it.

**Comment by deepthidevaki** [comment]
To debug we can run a benchmark by setting `-Dio.netty.leakDetection.level=advanced` or `paranoid` https://netty.io/wiki/reference-counted-objects.html#troubleshooting-buffer-leaks

**Comment by megglos** [comment]
we should validate if there were recent occurrences, @deepthidevaki can you please check?

**Comment by deepthidevaki** [comment]
There were no occurrence of this error in last 30 days.
