### ISSUE TITLE
Conditional expression behaves unexpected on `-` in variable name

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11350]
**Describe the bug**

I run into this when improving the QA process automation https://github.com/zeebe-io/zeebe-engineering-processes/pull/261

It looks like that when using a variable name with `-` the feel expression can't be evaluated and the default sequence flow is taken on an XOR gateway.

When using a variable:
```
{
 "response": { "status": 204 }
}
```
And expression `=response.status = 204` everything works fine
![normal-var](https://user-images.githubusercontent.com/2758593/209928103-fb64e643-8844-4e6b-802c-dcd2fb666288.png)

But if we change the variable name to `response-x` then the condition can't be evaluated.
Creating an instance with
```
{
 "response-x": { "status": 204 }
}
```
And expression `=response-x.status = 204` fails
![minus-var](https://user-images.githubusercontent.com/2758593/209928099-bf568422-7390-49bd-bdfa-4d3a3444ffbb.png)

**Workaround** Rename the variable, but of course, this is not optimal since this can be long undetected in the process.

**To Reproduce**
See the following BPMN models

[minus.bpmn.txt](https://github.com/camunda/zeebe/files/10318530/minus.bpmn.txt)
[normal.bpmn.txt](https://github.com/camunda/zeebe/files/10318531/normal.bpmn.txt)

**Expected behavior**

The variable name doesn't matter I can evaluate my expressions.

**Log/Stacktrace**

In the logs we can see the following line, logged by the feel engine: `Suppressed failure: no variable found for name 'response'`

**Environment:**
- OS: 
- Zeebe Version: 8.2.0-SNAPSHOT
- Configuration: G3-S

**Comment by korthout** [comment]
This FEEL expression contains a minus operator `-`, which is not allowed in variable names in both [Zeebe](https://docs.camunda.io/docs/next/components/concepts/variables/#variable-names) as well as in [FEEL-scala](https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-variables#variable-names).

Closing this as it is documented in the very first paragraph about [variable names](https://docs.camunda.io/docs/next/components/concepts/variables/#variable-names).

>The name of a variable can be any alphanumeric string including the `_` symbol. For a combination of words, it's recommended to use the camelCase or the snake_case format. The kebab-case format is not allowed because it contains the operator `-`.
