### ISSUE TITLE
Command rejections are not counted towards backpressure

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11352]
**Description**

I randomly happened across the `getOnProcessedListener` implementation in the `CommandApiServiceImpl`, where we mark a request limiter listener as finished when a command is processed.

That said, it seems we only process the records of type `COMMAND`, and ignore `COMMAND_REJECTION`. I'm not 100% sure of the consequences, but I didn't want to forget it.

**Comment by npepinpe** [comment]
@deepthidevaki - do you recall any specific reasons to not count rejections into backpressure, and of the top of your head, do you know what the consequences would be of not doing that? (no need to dig into it, if you're not sure, we can do that as part of this issue)

**Comment by deepthidevaki** [comment]
Only external requests are relevant for backpressure. `COMMAND_REJECTION` is a follow up event, right? Why should it be included in the backpressure?

**Comment by npepinpe** [comment]
Ugh, you're right, haha. I was think it's the response, which it is, but it doesn't matter for the on processed listener :see_no_evil:

My bad
