### ISSUE TITLE
k8s  Not enough disk space available

### ISSUE THREAD

**Issue by marunrun** [camunda/zeebe#11389]
**Describe the bug**

deploy with k8s   cephfs  pvc

the `df` command describe
```
 882G  787G   96G  90% /usr/local/zeebe/data
```

i get the warn 

```
 Out of disk space. Current available 103876132864 bytes. Minimum needed 142022698598 bytes.
ZeebePartition-2 failed, marking it as unhealthy: Partition-2{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=ZeebePartition-2{status=UNHEALTHY, issue=HealthIssue[message=Not enough disk space available, throwable=null, cause=null]}]}
```

**To Reproduce**

how can i resolve it ?

change the `ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK` ?  

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
{
   "network" : {
     "host" : "0.0.0.0",
     "portOffset" : 0,
     "maxMessageSize" : "4MB",
     "advertisedHost" : "platform-8-zeebe-0.platform-8-zeebe.workflow.svc",
     "commandApi" : {
       "host" : "0.0.0.0",
       "port" : 26501,
       "advertisedHost" : "platform-8-zeebe-0.platform-8-zeebe.workflow.svc",
       "advertisedPort" : 26501,
       "address" : "0.0.0.0:26501",
       "advertisedAddress" : "platform-8-zeebe-0.platform-8-zeebe.workflow.svc:26501"
     },
     "internalApi" : {
       "host" : "0.0.0.0",
       "port" : 26502,
       "advertisedHost" : "platform-8-zeebe-0.platform-8-zeebe.workflow.svc",
       "advertisedPort" : 26502,
       "address" : "0.0.0.0:26502",
       "advertisedAddress" : "platform-8-zeebe-0.platform-8-zeebe.workflow.svc:26502"
     },
     "security" : {
       "enabled" : false,
       "certificateChainPath" : null,
       "privateKeyPath" : null
     },
     "maxMessageSizeInBytes" : 4194304
   },
   "cluster" : {
     "initialContactPoints" : [ "platform-8-zeebe-0.platform-8-zeebe.workflow.svc:26502", "platform-8-zeebe-1.platform-8-zeebe.workflow.svc:26502", "platform-8-zeebe-2.platform-8-zeebe.workflow.svc:26502" ],
     "partitionIds" : [ 1, 2, 3 ],
     "nodeId" : 0,
     "partitionsCount" : 3,
     "replicationFactor" : 3,
     "clusterSize" : 3,
     "clusterName" : "platform-8-zeebe",
     "heartbeatInterval" : "PT0.25S",
     "electionTimeout" : "PT2.5S",
     "membership" : {
       "broadcastUpdates" : false,
       "broadcastDisputes" : true,
       "notifySuspect" : false,
       "gossipInterval" : "PT0.25S",
       "gossipFanout" : 2,
       "probeInterval" : "PT1S",
       "probeTimeout" : "PT0.1S",
       "suspectProbes" : 3,
       "failureTimeout" : "PT10S",
       "syncInterval" : "PT10S"
     },
     "raft" : {
       "enablePriorityElection" : true
     },
     "messageCompression" : "NONE"
   },
   "threads" : {
     "cpuThreadCount" : 3,
     "ioThreadCount" : 3
   },
   "data" : {
     "directory" : "/usr/local/zeebe/data",
     "logSegmentSize" : "128MB",
     "snapshotPeriod" : "PT5M",
     "logIndexDensity" : 100,
     "diskUsageMonitoringEnabled" : true,
     "diskUsageReplicationWatermark" : 0.87,
     "diskUsageCommandWatermark" : 0.1,
     "diskUsageMonitoringInterval" : "PT1S",
     "backup" : {
       "store" : "NONE",
       "s3" : {
         "bucketName" : null,
         "endpoint" : null,
         "region" : null,
         "accessKey" : null,
         "secretKey" : null,
         "apiCallTimeout" : "PT3M"
       }
     },
     "logSegmentSizeInBytes" : 134217728,
     "freeDiskSpaceCommandWatermark" : 852128641843,
     "freeDiskSpaceReplicationWatermark" : 123085248266
   },
   "exporters" : {
     "elasticsearch" : {
       "jarPath" : null,
       "className" : "io.camunda.zeebe.exporter.ElasticsearchExporter",
       "args" : {
         "url" : "http://elasticsearch-master:9200"
       },
       "external" : false
     }
   },
   "gateway" : {
     "network" : {
       "host" : "0.0.0.0",
       "port" : 26500,
       "minKeepAliveInterval" : "PT30S"
     },
     "cluster" : {
       "initialContactPoints" : [ "0.0.0.0:26502" ],
       "requestTimeout" : "PT15S",
       "clusterName" : "zeebe-cluster",
       "memberId" : "gateway",
       "host" : "0.0.0.0",
       "advertisedHost" : "0.0.0.0",
       "port" : 26502,
       "advertisedPort" : 26502,
       "membership" : {
         "broadcastUpdates" : false,
         "broadcastDisputes" : true,
         "notifySuspect" : false,
         "gossipInterval" : "PT0.25S",
         "gossipFanout" : 2,
         "probeInterval" : "PT1S",
         "probeTimeout" : "PT0.1S",
         "suspectProbes" : 3,
         "failureTimeout" : "PT10S",
         "syncInterval" : "PT10S"
       },
       "security" : {
         "enabled" : false,
         "certificateChainPath" : null,
         "privateKeyPath" : null
       },
       "messageCompression" : "NONE"
     },
     "threads" : {
       "managementThreads" : 1
     },
     "security" : {
       "enabled" : false,
       "certificateChainPath" : null,
       "privateKeyPath" : null
     },
     "longPolling" : {
       "enabled" : true
     },
     "interceptors" : [ ],
     "initialized" : true,
     "enable" : false
   },
   "backpressure" : {
     "enabled" : true,
     "algorithm" : "VEGAS",
     "aimd" : {
       "requestTimeout" : "PT1S",
       "initialLimit" : 100,
       "minLimit" : 1,
       "maxLimit" : 1000,
       "backoffRatio" : 0.9
     },
     "fixed" : {
       "limit" : 20
     },
     "vegas" : {
       "alpha" : 3,
       "beta" : 6,
       "initialLimit" : 20
     },
     "gradient" : {
       "minLimit" : 10,
       "initialLimit" : 20,
       "rttTolerance" : 2.0
     },
     "gradient2" : {
       "minLimit" : 10,
       "initialLimit" : 20,
       "rttTolerance" : 2.0,
       "longWindow" : 600
     }
   },
   "experimental" : {
     "maxAppendsPerFollower" : 2,
     "maxAppendBatchSize" : "32KB",
     "disableExplicitRaftFlush" : false,
     "rocksdb" : {
       "columnFamilyOptions" : { },
       "enableStatistics" : false,
       "memoryLimit" : "512MB",
       "maxOpenFiles" : -1,
       "maxWriteBufferNumber" : 6,
       "minWriteBufferNumberToMerge" : 3,
       "ioRateBytesPerSecond" : 0,
       "disableWal" : false
     },
     "raft" : {
       "requestTimeout" : "PT5S",
       "maxQuorumResponseTimeout" : "PT0S",
       "minStepDownFailureCount" : 3,
       "preferSnapshotReplicationThreshold" : 100,
       "preallocateSegmentFiles" : true
     },
     "partitioning" : {
       "scheme" : "ROUND_ROBIN",
       "fixed" : [ ]
     },
     "queryApi" : {
       "enabled" : false
     },
     "consistencyChecks" : {
       "enablePreconditions" : false,
       "enableForeignKeyChecks" : false,
       "settings" : {
         "enablePreconditions" : false,
         "enableForeignKeyChecks" : false
       }
     },
     "features" : {
       "enableYieldingDueDateChecker" : false,
       "enableActorMetrics" : false,
       "enableBackup" : false
     },
     "maxAppendBatchSizeInBytes" : 32768
   },
   "executionMetricsExporterEnabled" : false
 }

 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS:  amd64 
- Zeebe Version:    camunda/zeebe:8.1.5
- Configuration:

**Comment by megglos** [comment]
Hey @marunrun,
thanks for reaching out on this!

As of now the disk watermark thresholds are relative, you would indeed need to adjust them to resolve this issue, also see the docs on [Disc space](https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/disk-space/).

As a heads-up with https://github.com/camunda/zeebe/issues/8149 recently merged a new config with absolute values is around the corner for the upcoming 8.2.0 release.

Please let me know if you could resolve the issue.

Best
Sebastian

**Comment by megglos** [comment]
Hey @marunrun ,
I'll close this issue now due to inactivity, in case you have further information, feel free to reopen anytime.
