### ISSUE TITLE
Add additional performance metrics

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11418]
**Description**

Please add more I/O performance metrics, namely:

- [x] Read IOPS over time
- [x] Write IOPS over time
- [x] Size distribution in KB of the Raft append requests
- [x] Time segment allocation isolated from segment creation
- [x] Time distribution of the meta store flush, notably setLastWrittenIndex, separated from the normal flush
- [x] Append data rate, i.e. rate in KiB of how fast we append data on followers
- [x] Append rate, i.e. rate of how many entries we append on followers per second
- [x] Commit rate, i.e. rate of how many entries we commit per second
- [x] Journal append latency
- [x] Journal append data rate
- [x] Number of records not replicated
- [x] Number of records not committed
- [ ] Add p95 and p99 quantile to most latency measuring diagrams

**Comment by Zelldon** [comment]
> Size distribution in KB of the Raft append requests

I think this we have via the messaging metrics https://github.com/camunda/zeebe/pull/11353
