### ISSUE TITLE
Calling Rebalance API causes short disruption

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11415]
**Describe the bug**

Based on our last hack week, we added new functionality (cronjob) to our benchmarks setup, which triggers the rebalance API continuously https://github.com/zeebe-io/benchmark-helm/pull/7 so we are sure that we have always good leader distribution.

I have run a test benchmark for a while and we can see that every API call triggers disruption, still the avg performance looks ok, the processing execution latency is also highly impacted. We should investigate this further, because it looks for me that most of the time the leadership was already well distributed, so I would expect no impact.

**General**
![general](https://user-images.githubusercontent.com/2758593/212684575-0352facc-603c-4258-a8fe-58bb54f16f3c.png)

**Raft**

We can see in the Raft metrics, that the Raft request are going down for a short period of time. Furthermore, we see only two places were really leader changes were happening. The heartbeat misses are likely to caused by the drop of append requests.

![raft](https://user-images.githubusercontent.com/2758593/212684593-4254a4c0-27d6-43a6-9884-9a465f845fb4.png)
![raft2](https://user-images.githubusercontent.com/2758593/212684595-b85ddb6f-8cc1-485d-86e2-5b7c20eafc42.png)

**Latency**
The process execution latency goes up to 10s, potentially due to the append request drop.

![latency](https://user-images.githubusercontent.com/2758593/212684889-4ece829f-cff9-4acc-94bc-5c0786f14b99.png)

**To Reproduce**

Run a benchmark with the most recent changes https://github.com/zeebe-io/benchmark-helm/pull/7

**Expected behavior**

If the leader distribution is already well distributed we shouldn't see any impact.

**Environment:**
- OS: 
- Zeebe Version: 8.1.x, 8.2
- Configuration:

**Comment by oleschoenburg** [comment]
Pretty sure that I found the bug :facepalm: 

https://github.com/camunda/zeebe/blob/346ce3400c25afa468744748ff506e039c267fd7/atomix/cluster/src/main/java/io/atomix/raft/partition/RaftPartition.java#L246
That should be a call to `equals`, not an object identity comparison. In effect, rebalancing would always force partition leaders to step down.
