### ISSUE TITLE
Asynchronously prepare next segment to reduce peak write latency

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11444]
In order to avoid spikes in our p95 and p99 latency due to segment creation, we should prototype creating (and pre-allocating) the next segment asynchronously. 

We can do this at various points in time. The easiest option is probably to trigger pre-creation whenever we need to create a new segment. Another, more advanced option, is to start pre-creating a segment when the writer has filled x% of the current segment.

# Support
- SUPPORT-15889

**Comment by megglos** [comment]
relates to https://github.com/camunda/product-hub/issues/642

**Comment by megglos** [comment]
reopening for backporting to 8.1

**Comment by megglos** [comment]
@npepinpe : Whoever ends up backporting this, please make sure to backport https://github.com/camunda/zeebe/pull/11589 which fixed some flaky tests introduced by the feature.
