### ISSUE TITLE
Disable Rockdb WAL by default

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#11455]
**Is your feature request related to a problem? Please describe.**
We already provide a configuration flag to disable rocksdb WAL. [Our recent benchmarks](https://camunda.slack.com/archives/C037RS2JHB8/p1674200750104639) has shown that disabling rocksdb WAL provides noticeable performance (process latency)  improvement. So it would make sense to disable it by default. 

As part of this issue, also crosscheck if this is safe. See https://github.com/camunda/zeebe/issues/6161#issuecomment-771722771 more details. Bonus would be if we can test and verify our understanding of its safety is correct.

**Comment by megglos** [comment]
Quick win to be assessed as default, relates to https://github.com/camunda/product-hub/issues/642
