### ISSUE TITLE
Improve raft snapshot replication failure handling

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#11496]
**Description**

Currently, if replicating a snapshot fails due to timeout for example, the leader restarts the snapshot replication and re-sends from the first chunk. If the network is unstable and the timeouts are frequent, then the follower is less likely to receive the complete snapshot before encountering a timeout. To ensure progress in such cases, it would be better if leader/follower can identify what was the last successfully replicated chunk and continue from that point instead of restarting from the beginning.

We observed a similar situation in a [support ticket](https://jira.camunda.com/browse/SUPPORT-15739). It appears that the leader was cpu bottlenecked which resulted in InstallRequest being timed out. So follower was never able to receiving the full snapshot.

**Comment by megglos** [comment]
ZDP-Planning:
- this is even more relevant with large states

**Comment by megglos** [comment]
ZDP-Planning:
- the resulting issue is mitigated by #12793
- also relates to #12795 
- potential impact, never ending snapshot install loop
- recently affected customer

**Comment by megglos** [comment]
ZDP-Planning:
- the previous timeout config is still just considered a shortcut while this would be a better solution
