### ISSUE TITLE
Promote disable raft flush flag to non-experimental

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#11519]
**Description**

Now that #11423 is done, we can officially support this flag. 

-[ ] Properly document dangers of disabling raft flush.
-[ ] Move the flag out of non-experimental. TBD whether we can make breaking changes for this config.

Related https://github.com/camunda/product-hub/issues/642

**Comment by deepthidevaki** [comment]
Summary from discussion with @npepinpe

We would first like to evaluate #11488. On suggestion there is to flush every X seconds. In addition we can also do flush asynchronously without waiting. With a proper value for X, we might be able get similar performance as disabling raft flush, but with added guarantee that the data is flushed atleast once in X seconds. This would be better than disabling flush completely. 

If the performance with this is comparable to disabling flush, then it would be worth re-evaluating whether we should support disabling raft completely. Instead we can support configurable flush interval.

**Comment by npepinpe** [comment]
Will be split into two PRs. The first one will introduce the configuration, the various flush strategies, but will be synchronous. This is because flushing asynchronously is not safe at the moment, as the write path of the journal is not thread safe.

A second PR will look into making the delayed flush strategy asynchronous.

**Comment by npepinpe** [comment]
After the PR, the next step will be to make flushing asynchronous. So we don't forget, here's the idea we came up with during brainstorming:

- Introduce a background thread context to the journal
- Synchronize compaction, next segment creation, and flushing on that thread.
- When the last reader is closed on a segment marked for deletion, enqueue the task to delete the segment on the background context.

This approach ensures we can safely flush asynchronously without having to worry about a mapped buffer being unmapped.

After this is done, we should look into pushing down the concept of `lastFlushedIndex` to the journal.

**Comment by Zelldon** [comment]
@npepinpe does it make sense to already introduced here our actors?

**Comment by npepinpe** [comment]
I would keep it simpler and introduce the smallest possible interface, which in this case is just an `Executor`. Possibly a combination of `AutoCloseable` and `Executor`, if we decide the journal manages the thread or not (probably).
