### ISSUE TITLE
Add broker configuration for batch processing

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11545]
**Description**

part of https://github.com/camunda/zeebe/issues/11416

Add additional (new) configuration for changing the `processingBatchLimit` in the StreamProcessor. Made available via https://github.com/camunda/zeebe/pull/11527

* Per default this value should be set to `100`, currently done in the StreamProcessorContext.
* Add note that if setting to `1` it will work as previous processing.
* Potentially we need to add a new config object for processing in general (?)

**Comment by oleschoenburg** [comment]
> Potentially we need to add a new config object for processing in general (?)

We should keep in mind that we might eventually do uncommitted processing, that might influence the config schema

**Comment by Zelldon** [comment]
I guess then it makes sense to introduce a new processing config ? @oleschoenburg

**Comment by oleschoenburg** [comment]
Yeah I think so :+1:
