### ISSUE TITLE
Add new metrics for Batch processing

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11546]
**Description**

part of https://github.com/camunda/zeebe/issues/11416

With https://github.com/camunda/zeebe/issues/11416 we introduce a new feature called batch processing, which changes how much command we process at once. In order get better visibility we want to add additional metrics.

Potential metrics: 

- [x]  batch record count (how many we write as batch)
  - [x] Done via sequencer metrics
- [x]  batch size in bytes to write
  - [x] Done via sequencer metrics
- [x]  batch command count (how many commands we have processed)
  - [x] `stream_processor_batch_processing_commands`
- [x]  batch post commit tasks count
  - [x] Not possible, since this is part of the result implementation. But it is more interesting how long it tasks. So we just added a timer for that.
  - [x] `stream_processor_batch_processing_post_commit_tasks`
- [x]  batch limit (is adjusted when we reach the limit)
  - [x] We thought about it, but the problem is that we are in the hot path and the limit will change quickly back to the default. We might not notice due to our scrape interval. WE introduced a counter for retries `stream_processor_batch_processing_retry`
- [x]  time of batch processing (start of reading initial command - end when we detect no more command to process or reached limit) 
  - [x] `zeebe_stream_processor_batch_processing_duration`
- [x] Failed batch -> counted retries
- [x] How long does it take to run side effects? If it's too long, I might want to decrease the limit

A clear and concise description of what this issue is about.

**Comment by oleschoenburg** [comment]
Things I'd want to see in Grafana as a Zeebe developer: 
- How often do we do rollback & retry? If it's often, I might want to decrease the limit
- How often is the command limit not enough? If it's often, I might want to increase the limit
- How long does it take to run side effects? If it's too long, I might want to decrease the limit

**Comment by Zelldon** [comment]
> How often do we do rollback & retry? If it's often, I might want to decrease the limit
> How often is the command limit not enough? If it's often, I might want to increase the limit

This will be covered by `batch limit (is adjusted when we reach the limit)`. A separate metric for rollback is not optimal, I thought about it, and it would only be reported if it really happens, which makes visualizing quite hard. Similar issue we have with blacklisting.

> How long does it take to run side effects? If it's too long, I might want to decrease the limit

:+1:
