### ISSUE TITLE
Fix journal metrics

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11556]
**Description**

Since the journal metrics use the logname as the partition label value (e.g. `raft-partition-1`) and not the partition ID itself, filtering by partition is wrong for all journal metrics.

This should be fixed, so we can either filter by partition (preferably), or they are outside of the partition filter.

Secondly, the journal append latency graph shows the average of the log appender commit latency, and not the journal's append latency. This should be fixed.

We can decide if we'd like to also have the log appender latency or not as well as a separate graph.

**Comment by Zelldon** [comment]
Would be good to have this for raft as well.

**Comment by npepinpe** [comment]
You mean that the Raft metrics cannot be filtered by partition ID either?

**Comment by Zelldon** [comment]
Nevermind seems to be ok, I thought we don't have this label on raft metrics.
