### ISSUE TITLE
Adjust grafana dashboard to always use same rate interval

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11567]
**Description**

All over in our grafana dashboard we use different rate intervals, sometimes 30s sometimes 1m. Mostly because we don't know better in the past. Ideally I would like to see an introduction of a new variable which we use in all places. 

As default value we potentially would use `$__rate_interval` (@oleschoenburg me recently teached about). 

One StackOverflow post summaries this pretty good:

> Prometheus periodically fetches data from your application. Grafana periodically fetches Data from Prometheus. Grafana does not know, how often Prometheus polls your application for data. Grafana will estimate this time by looking at the data. The $__interval variable expands to the duration between two data points in the graph. (Note that this is only true for small time ranges and high resolution as the intended use case for $__interval is reducing the number of data points when the time range is wide. See [Approximate Calculation of $__interval](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__interval).)
> 
> If the time-distance between every two data points in each series is 15 seconds, it does not make sense to use anything less than [15s] as interval in the rate function. The rate function works best with at least 4 data points. Therefore [1m] would be much better than anything betweeen [15s] and [1m]. This is what $__rate_interval tries to achieve: guessing a minimal sensible interval for the rate function.
>
> https://stackoverflow.com/a/72374057/2165134

Ideally it makes sense to also set the prometheus scrape interval in the grafana configuration, so the calculation works better (since grafana assumes it is 15seconds). See this post https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/

**Why is this interesting:**

1. We have use everywhere the same rate interval which makes the graphs comparable
2. If you reduce the time interval to a short time frame the dashboard doesn't break, as shown [here](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/#:~:text=The%20result%20is%20very%20disappointing%3A%20%E2%80%9CNo%20data%E2%80%9D!%20The) 
3. We can play around with different interval more easily if we have a variable used everywhere

**Comment by megglos** [comment]
Notes:
- would allow to better compare graphs and correlate.
- seems like an easy pick just tedious task
