### ISSUE TITLE
ARM64 CI Jobs frequently fail due to connection resets

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11590]
Examples:
- https://github.com/camunda/zeebe/actions/runs/4134636764/jobs/7146014786
- https://github.com/camunda/zeebe/actions/runs/4130548513/jobs/7137350957

Could be related to MTU or GCP network interference. See https://github.com/zeebe-io/infra/blob/main/gcp/zeebe-io/zeebe-ci-1/runner-arm64-4.yml for the configuration we use for these runners

**Comment by megglos** [comment]
Even after runner downgrade (https://github.com/zeebe-io/infra/pull/32 ) we experienced the network issues 
https://github.com/camunda/zeebe/actions/runs/4173174037/jobs/7228803794

```
 k describe pod actions-runner-arm64-4-fjmsf-rl828                                                                                              
    Image:          summerwind/actions-runner-dind@sha256:c2fff4d42cd3cd456038dbb3372846a588dca5d26da18ac8718cb2195b767d80
```

Also checked the network interfaces mtu, actually looked fine:
```
runner@actions-runner-arm64-4-fjmsf-rl828:/$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1460
...

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1460
...
```
