### ISSUE TITLE
Apply `RecordDistribution` events

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#11658]
- `STARTED` stores the record for (re)distribution
- `FINISHED` removes the record stored for (re)distribution
- `DISTRIBUTING` stores an entry for a pending distribution
- `ACKNOWLEDGED` removes the entry for the pending distribution`

Depends on
- #11657 
- #11868

**Comment by remcowesterhoud** [comment]
This issue requires changes to the state. We will need new ColumnFamilies, and ideally a new state object. As this is will cause the PR to become rather large I have extracted this into [a separate issue](https://github.com/camunda/zeebe/issues/11868)
