### ISSUE TITLE
Introduce a new `RecordDistribution` record

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#11657]
- exists only on the partition that distributes the record
- wraps the record we want to distribute
	- ~~`partitionIds` informs about the entire distribution picture, which partitions should the record be distributed to, used in `STARTED` and `FINISHED`~~
	- `partitionId` informs about the distribution of the record to a single partition, used by `DISTRIBUTING`, `ACKNOWLEDGE`, and `ACKNOWLEDGED` 
	- `valueType` informs about the record it wraps, always used
	- `recordvalue` informs about the actual record value to distribute, only used by `STARTED` and `DISTRIBUTE`
- has intents: 
	- `STARTED`
	- `DISTRIBUTING`
	- `ACKNOWLEDGE`
	- `ACKNOWLEDGED`
	- `FINISHED`

**Comment by remcowesterhoud** [comment]
Discussed with @korthout about the value of having a list of all `partitionIds` in the record. We don't see any value in having this right now.

If we need it in the future we can still add it. For backwards compatibility we can then consider a record where this property is empty to be distributed across all partitions.
