### ISSUE TITLE
Switch `Deployment:Create` processor to new record distribution behavior

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#11661]
- Switching should be backward compatible
- We don't delete the existing processors for `Deployment` commands
- We don't delete the existing appliers for `Deployment` events
- Switching happens by changing the processor's logic
- ~~We also need to switch the logic in the `DeploymentRedistributor`~~
- `DeploymentCreateProcessor` should be idempotent

Depends on
- #11660

**Comment by remcowesterhoud** [comment]
Moving this back to the backlog or now as it got deprioritised
