### ISSUE TITLE
Zeebe system events lists 

### ISSUE THREAD

**Issue by kousher-alam** [camunda/zeebe#11680]
Hi guys, 

is zeebe create some kind of generic system event like 'INCIDENT',  'COMPLETE', 'WORKFLOW CANCELED' ? if so where should i find this list ?

**Comment by korthout** [comment]
Hi @kousher-alam 👋 Zeebe can export its internal log stream to external systems, see [architecture](https://docs.camunda.io/docs/next/components/zeebe/technical-concepts/architecture) and [exporters](https://docs.camunda.io/docs/next/self-managed/concepts/exporters/). Exporters are only available in Camund Platform 8 Self-Managed.

**Comment by kousher-alam** [comment]
hi @korthout is there any way to subscribe this events using NodeJS client ? Skipping the exporter part ?

**Comment by korthout** [comment]
Ho @kousher-alam. You cannot access this data through the clients. 

On Camunda 8 SaaS, or if you have an Operate license, you can access this data through the Operate API.

In the open source community there are tools like ZeeQS and Simple-Monitor that can help you find out the state of your process instances.
