### ISSUE TITLE
Introduce job receiver in the gateway

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11712]
**Description**

In order to push jobs from the gateway to the client, the gateway has to be able to receive them from the broker.

To do this, it should set up a receiving endpoint (i.e. subscribe to an Atomix topic). This endpoint will only receive one type of request, which will contain the job key, the job record, and the stream worker unique ID for which the job was activated.

If the gateway has no clients for this unique ID, it should make the job available again to the broker by sending a fail command (but keeping the same number of retries), much like we do in the long polling handler.

> **Note** We may want to also send a `RemoveWorker` request to be safe, in case there was some bug.

If there are some clients for the unique ID (as registered in #11713), then we should pick one of them and push the job to it.

If an error occurs when pushing (and the error indicates the job was not sent to the client), we can pick the next one, and push it to that one. If we cannot decide if the job was sent or not, we should assume it was.

> **Note** Please challenge this! Let's see what makes for the best UX here.

**Comment by deepthidevaki** [comment]
This issue can be split into two:

- [ ] Adding support for receiving and handling payloads received via a stream. This will be implemented in transport. Stream management in transport receives payload from a broker and handles it over to a registered client stream.
- [ ] Sending the activated jobs to a client. This will be implemented in gateway, which will process the payload handled over from the transport. The gateway know if the client is available or not, and should implement proper error handling such as closing the stream, marking the job re-activatable etc.

**Comment by npepinpe** [comment]
I've extracted the remaining point to a separate issue which the ZPA team will take over. So we can close this for now.
