### ISSUE TITLE
Is 8.1.8 the latest release?

### ISSUE THREAD

**Issue by ZhongRuoyu** [camunda/zeebe#11714]
**Description**

Hi! Homebrew maintainer here. We noticed that 8.1.8 has been tagged, but is not marked as latest release yet on GitHub (https://github.com/camunda/zeebe/releases). So, I'm opening this to confirm if that's intended. Thanks!

Context: https://github.com/Homebrew/homebrew-core/pull/123208

**Comment by megglos** [comment]
Hey @ZhongRuoyu ,

thanks for reaching out, it's public now https://github.com/camunda/zeebe/releases/tag/8.1.8

**Comment by ZhongRuoyu** [comment]
Thanks, @megglos!
