### ISSUE TITLE
Support GCS for Backups

### ISSUE THREAD

**Issue by Sijoma** [camunda/zeebe#11732]
**Is your feature request related to a problem? Please describe.**

Using the backup APIs of Zeebe with GCS requires to create a static credential for the `hmac key`. However, this does not fit our security requirements as we should not use static credentials. A solution for this is to use [Workload Identity Federation](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity). 

Additionally, when using the backup APIs with GCS storage, deleting backups does not work.  It seems GCS does not support the `deleteObjects` API https://issuetracker.google.com/issues/162653700. 

**Describe the solution you'd like**

Official support for GCS storage similar as it is implemented for the AWS client. 

Requirements:
- We are able to use workload identity federation on Zeebe
- Deleting backups works

**Comment by megglos** [comment]
Preliminary Assessment:
- will be considered in upcoming plannings, we have uncertainty how this balances out compared to other pending topics
- would be great to get done with 8.2 as otherwise SRE would need to workaround it (additional costs and complexity for SaaS)

**Comment by oleschoenburg** [comment]
Will be implemented here: https://github.com/camunda/zeebe/issues/11917

**Comment by oleschoenburg** [comment]
Done: https://github.com/camunda/zeebe/issues/11732 :tada:
