### ISSUE TITLE
Investigate usage of client in gateway

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11799]
**Description**

It looks like we using the Zeebe client in the gateway, which is somehow weird. It add an unnecessary dependency to the client, and makes unnecessary requests. 

This was recently discovered here https://github.com/camunda/zeebe/pull/11599#discussion_r1109846523 

Furthermore, the impact was discovered also in one of the chaos days https://zeebe-io.github.io/zeebe-chaos/2023/02/23/Recursive-call-activity/

![general](https://user-images.githubusercontent.com/2758593/220933420-06a44b51-a549-4b71-8611-6aa9d1b2d691.png)

> One interesting fact is that the topology request rate is also up to 0.400 per second, so potentially every 2.5 seconds we send a topology request to the gateway. But there is no application deployed that does this. [I have recently found out again](https://github.com/camunda/zeebe/pull/11599#discussion_r1109846523), that we have the Zeebe client usage in the gateway to request the topology. Might be worth investigating whether this is an issue.

Right now I'm not sure how problematic it is, whether it is just toil or whether this might be an actual bigger issue.

relates to https://jira.camunda.com/browse/SUPPORT-16945

**Comment by korthout** [comment]
We're unsure what this health check's expected behavior should be. We can discuss this with SRE, as they are the users of this API in SaaS. Marking this as `later` for now.

//cc @aleksander-dytko

**Comment by npepinpe** [comment]
Support related now - see https://jira.camunda.com/browse/SUPPORT-16945?focusedCommentId=285709&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

Having to configure authentication, security, etc., just overly complicates things. Then factor in things like hostname verification checks and so on - let's just get rid of it and hook in the topology manager directly.

**Comment by npepinpe** [comment]
imo this would then fall to the ZDP team to do

**Comment by megglos** [comment]
this actually overlaps with https://github.com/camunda/zeebe/issues/13431 , let's not work on it until that one is clarified
