### ISSUE TITLE
Migrate docker credentials to use new account

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#11804]
**Description**

The currenttly used credentials are about to get removed and a new account is to be used, see this [message](https://camunda.slack.com/archives/C037RS2JHB8/p1676978176227739).

**Comment by korthout** [comment]
@megglos Is there anything that we need to do for this? We read the message as if there is nothing to do for us. Please reopen the issue if there is.

**Comment by megglos** [comment]
@korthout thanks for closing, seems I misinterpreted the message that there would be action needed
