### ISSUE TITLE
Large runtime state slows down access to RocksDB

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11813]
**Describe the bug**

If Zeebe accumulates a lot of runtime state in RocksDB, at some point all access to that state becomes really slow.
To some degree this makes sense but the effect seems disproportionate, probably highlighting that we are not using RocksDB in a good way.

**To Reproduce**

See for example https://github.com/camunda/zeebe/issues/11798

Another scenario to reproduce the issue would be to start process instances of a process containing two service tasks whereby the second service task doesn't get completed. That way, Zeebe starts to build a large state in RocksDB. Eventually, it resulted in the same behavior as with #11798, i.e., after ~1 the throughput dropped and the latency started to increase.

**Observations**

When debugging the second scenario (i.e., not completing process instance), the following observations were made:

1. Fetching constantly static information
2. Point lookups with non-existing keys
3. RocksDB Iterator running out of bounds
4. Multiple Get-Update-Loops to update values in RocksDB

**Re 1- Fetching constantly static information**

Whenever a new process instance is started by process id, then Zeebe gets the latest version number of the process definition by fetching it from RocksDB

https://github.com/camunda/zeebe/blob/eb90558e367a107ace06240adbf8092d0b304b7a/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbProcessState.java#L213

Since the version number doesn't change that frequently over time, the key-value pair moves to the highest level in RocksDB. Consequently, getting the version number results in a steadily growing number of hits an L3.

To avoid the lookup with every process instance to create, the version number could be cached and only be retrieved from RocksDB when not available, see https://github.com/camunda/zeebe/commit/211a2ca30ec7c0a7031fabf16d86a9ca0298b353 That way, the hits in L3 (i.e., L2 and up) stops growing over time and remain constant.

**Re 2- Point lookups with non-existing keys**

There are different cases in which Zeebe does `get` requests in RocksDB to retrieve a certain value for a given key. But sometimes, the given does not exist (yet). Basically, there are cases in which Zeebe does a point lookup with the key `-1` or with a non-existing key in a logical column family. Anyway, this will result in going through the LSM tree when trying to find the value with the given key, i.e., RocksDB goes through the levels (from memtable to L3) to find the latest version of the value, and per level (L1 to L3), it does a binary search to find the potential SST file having the key inside, etc.

_Setting variables during process instance creation_

When a new process instance is created any given variables are set in the process instance scope. Therefore, it calls `#mergeLocalDocument()`:

https://github.com/camunda/zeebe/blob/ae6dbfc5439c889ad8b8fd24d7431b46110c7900/engine/src/main/java/io/camunda/zeebe/engine/processing/variable/VariableBehavior.java#L60-L80

This iterates over the variables to set and check if a variable with the given name already exists in the scope:

https://github.com/camunda/zeebe/blob/ae6dbfc5439c889ad8b8fd24d7431b46110c7900/engine/src/main/java/io/camunda/zeebe/engine/processing/variable/VariableBehavior.java#L186-L187

This results in unnecessary `get`s in RocksDB, because at that point could have known that it creates a new instance and set initially the variables. Instead, Zeebe could just set the variable without checking for any potential existing variables, see https://github.com/camunda/zeebe/commit/12b46995e58aeec99a6ce215961ab4487130e078

_Getting Element Instance by key `-1`_

In the case of creating getting the flow scope of a newly created process instance, it results in a point lookup with key `-1`:

https://github.com/camunda/zeebe/blob/ae6dbfc5439c889ad8b8fd24d7431b46110c7900/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementActivatingApplier.java#L54

There are also other cases in which Zeebe tries to get the parent or flow scope whose key is `-1` indicating that the current element instance represents the process instance. This could be avoided by doing a range check, i.e., is the key `< 0` then don't do the `get`, see https://github.com/camunda/zeebe/commit/95e381fc714a10e1fcf55d6ad74e740f3cfb76ef

_Getting Element Instance by a not yet persisted key_

There are cases in which Zeebe generates a new key for an element instance but didn't persist the value in RocksDB. But still, before persisting it initially it executes a `get` to find the value for the key. "Caching" the highest key (of type long) and doing a range check, i.e., if `key_to_lookup > highest_inserted_key`, then don't the `get` and return `null`, see https://github.com/camunda/zeebe/commit/3c1b8e308f9ee6903b298b071d45a9a55423d13f

_Blacklist checks_

With (almost) every command, Zeebe will check if the given process instance is blacklisted, even if the process instance is just created. Also, this check happens all the time during batch processing:

https://github.com/camunda/zeebe/blob/ae6dbfc5439c889ad8b8fd24d7431b46110c7900/engine/src/main/java/io/camunda/zeebe/engine/Engine.java#L130-L134

Just some a thoughts on how this could be improved:
* Cache the information that there is no blacklisted process instance so that Zeebe avoids the lookup in RocksDB.
* Avoid doing the check with every (follow-up) command during batch processing.
* When creating a new process instance, the check is unnecessary.
* TBD: If there are blacklisted process instances, how to make the lookup efficient.

_Variable Propagation_

When setting variables (on job completion), it will traverse the process instance tree from the local scope up to the process instance scope, until all variables are set/updated:

https://github.com/camunda/zeebe/blob/28fe054b79fcc7398a086a1576199efef01a122c/engine/src/main/java/io/camunda/zeebe/engine/processing/variable/VariableBehavior.java#L103-L146

This results in (many) point lookups with non-existing keys.

**3. RocksDB Iterator running out of bounds**

When iterating within a column family by a prefix, Zeebe controls when the iterator is out of bounds or not. This always results in `x + 1` (whereby `x >= 0`) iterations. Meaning, the `+1` iteration always happens, and doing a check if the iterator is within the expected prefix or not:

https://github.com/camunda/zeebe/blob/28fe054b79fcc7398a086a1576199efef01a122c/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java#L359-L361

This may cause reading the first key-value pair of the next logical column family (that contains data).

Potential improvements:
* Stop the iterator early to avoid `+1` iteration, for example, keep track of the last activatable job and stop once reached, see https://github.com/camunda/zeebe/commit/3ad86da6d016f1f1a96693da781b919c6c8466a0#diff-ef73a79bfa12b3c9cc862cff7aefcdc63b8cb9efaa732c6de49b842915017b20
* Avoid iterator at all, when there is no data available to iterate on. For example, when a local scope does not contain any variables, then it is not necessary to iterate at all, see https://github.com/camunda/zeebe/commit/3ad86da6d016f1f1a96693da781b919c6c8466a0#diff-0e10700c5e815f3754aae816fc4128ba69b4faabb3c1a65a89a7a818f6d9d6ad
* There are also other cases, where on element instance completion, it "unsubscribes" from events and therefore it uses an iterator. But in the most cases, there is nothing to unsubscribe from.

**4. Multiple Get-Update-Loops to update values in RocksDB**

To update the element instance state (as an example), Zeebe always does first a `get`, then changes the element instance, and `update` in RocksDB. This happens during processing multiple times on the same element instance:

https://github.com/camunda/zeebe/blob/28fe054b79fcc7398a086a1576199efef01a122c/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbElementInstanceState.java#L185-L190

There are many other examples. Also, the same happens whenever a new key is generated.

Potential improvements:
* Once fetched an element instance from RocksDB, keep it in a cache, and apply state changes to the element instance, once the processing completes flush the last element instance state to RocksDB. (At least during debugging, it showed that the number of element instances fetched from RocksDB is mostly limited, i.e., when processing a command it gets the element instance to process and the parent/flow scope element instance.)
* During batch processing, it may happen that an element instance gets created and completed at once (like a start event). In that case, it is not necessary to persist the element instance at all in RocksDB. That way, RocksDB will have fewer tombstones stored moving from memtable to the highest level (and then eventually getting deleted).

**Other considerations**

* `DeleteRange`: For example, when activating the next `x` jobs, currently the activated jobs are executed one by one from the activatable job column family. Instead, a `DeleteRange` could be used to delete a batch of activated jobs from the queue. That way, the iterator could skip the tombstone easily. (Note: `DeleteRange` is not compatible with RocksDB transactions.)
* Cache the first and last key in a queue (like jobs to activate), this could be used to optimize the RocksDB iterator to skip tombstone when executing `seek()`.

**Additional information**
[This branch](https://github.com/camunda/zeebe/compare/rs-stop-iterator-2) contains some of the "improvements" that showcased a significant gain in processing execution time. However, these changes are mostly "optimized" for the benchmark BPMN process used for testing.

**Environment:**
- Zeebe Version: 8.1.x

---

related to [SUPPORT-15959](https://jira.camunda.com/browse/SUPPORT-15959)

**Comment by romansmirnov** [comment]
@oleschoenburg, I enhanced the description with the observations/findings made when investigating a customer support case. Hope that is okay with you 😄

**Comment by megglos** [comment]
also relates to https://github.com/camunda/zeebe/issues/9862

**Comment by megglos** [comment]
Deepthi: Should actually be an epic in product hub
It can be considered a bug in relation to supporting long running instances.
@felix-mueller let's create a product hub epic for that

**Comment by megglos** [comment]
First step: determine a scope for a first iteration

**Comment by megglos** [comment]
@Zelldon do we wanna close this one being kind of superseded by https://github.com/camunda/zeebe/issues/12033 ?

**Comment by Zelldon** [comment]
No its fine lets keep this as bug, and the other the feature to implement in order to resolve this.

**Comment by megglos** [comment]
just wondering how to handle given it sits in ready but the work is done on the other issue shall we move it to backlog?

**Comment by Zelldon** [comment]
Makes sense :+1:

**Comment by Zelldon** [comment]
I would close this for now, we did some work to overcome this see #12033 we might work on further improvements, but most of the issue should be put into some boundaries. Lets reopen it if we see an issue with it again.
