### ISSUE TITLE
Intermittent invalid bucket values in Grafana

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11814]
I checked the following metric, `sum(increase(atomix_compaction_time_ms_bucket{namespace=~"np-flush-sync"}[5m])) by (le)`,  to compare in Grafana and in the Google Managed Prometheus console.

In Grafana, I get the following graph:

![image](https://user-images.githubusercontent.com/43373/221201253-dfc68229-5cf9-49f1-a166-3a1ea5c757df.png)

In Grafana metrics explorer:

![image](https://user-images.githubusercontent.com/43373/221203270-577a35b5-c67a-4884-ab71-24230d8e10a2.png)

If you Zoom in to a specific time frame, you will see the bucket values suddenly change to span from 0 to the maximum integer value (in powers of 2), even though the actual value of for those buckets were all 0 :exploding_head: :

![image](https://user-images.githubusercontent.com/43373/221203850-7f9fa012-1c87-4582-91e2-30393bcbbe6e.png)

In Google Console, I get:

![image](https://user-images.githubusercontent.com/43373/221201354-3596f8c4-590a-40c2-b1d3-dac2350814be.png)

If I zoom in in the same time frame as above, we see the weird bucket values as well:

![image](https://user-images.githubusercontent.com/43373/221204406-8dcf0bd9-ca58-4d8c-866f-5ab0ecb67271.png)

In the Prometheus console:

![image](https://user-images.githubusercontent.com/43373/221201855-9851ddfc-78c4-4cf6-a598-6621754b0690.png)

Zooming in, we get the same weird values:

![image](https://user-images.githubusercontent.com/43373/221204624-be9eb204-d17c-4ac8-b35f-c369bacaedee.png)

So it does look like Prometheus is reporting weird buckets at time. However, the values are always 0 - I'll check if this coincides with the nodes being down.

There were no pod restarts at the time, so it doesn't seem to be related to that. I double checked, and the values are not 0, but they are simply nothing. So it could be the issue we had were metrics are being aggregated from different nodes, and managed Prometheus being idiotic fills up a null sample, or something weirder. Since this is all a posteriori, I'm not sure how I would figure out if this comes from the aggregation/managed Prometheus, or if it's something from the client itself which glitches at time and returns the wrong values. I would tentatively think this is on the collection side.

One possible migration option would be the following:

1. Create a new node pool of non-preemptible nodes in the normal cluster
2. Switch all long running benchmarks to use the normal cluster but with the right node selector
3. Switch all processes which refer to the long running benchmarks to simply deploy with the right node selector
4. Delete long-running cluster
5. Deploy Prometheus Operator Helm chart in normal Zeebe cluster
6. If possible reuse the same IP we used for the Grafana deployment with the new Prometheus Operator managed Grafana. If not, we'll have to ask IT to update the DNS route for grafana.dev.zeebe.io
7. Re-enable the service monitor for ALL existing benchmarks
8. Update the benchmark set up to enable service monitor by default
9. Sunset the Google Managed Prometheus when we're sure everything is working fine

This would mean we're back to deploying and maintaining the more complicated Prometheus Operator chart.

Before that, I would like to try switching from ClusterMonitoringSpec to PodMonitoringSpec, but just timebox it (e.g. 2 hours). I think this might solve the IP reuse confusion inherent with ClusterMonitoringSpec.

_Originally posted by @npepinpe in https://github.com/camunda/zeebe/issues/11798#issuecomment-1443754815_

**Comment by npepinpe** [comment]
Due to the fact only benchmarks in the normal `zeebe-cluster` are affected, I think this is again the same issue where pods remain in failed state, and IPs are reused.

**Comment by npepinpe** [comment]
Now that we have our benchmark chart, it's very easy to add a `PodMonitoring` spec to all our benchmarks without modifying the `camunda-platform-helm` chart.

I did a quick test and it seems to work fine, including easily picking up metrics for our extra applications.

I'm going to let it run a little bit more and see if it gets affected by this bug. It seemed to occur fairly often, considering the amount of histogram we have, so hopefully over the weekend will be enough to see if it's unaffected.

It's not a fool proof test however. It might still be simpler to move back to normal Prometheus all things considered (other than the fact that the Prometheus operator upgrade path often includes breaking changes :( )

**Comment by npepinpe** [comment]
Happened again, even with the `PodMonitoring` instead of `ClusterMonitoring`, but it occurred while I was recreating the benchmark. Still, that wouldn't explain where these weird values are coming from. Things are fine once you skip that little hiccup, but it's a poor UX.

Might be that this managed Prometheus experiment was simply not worth all the trouble it gave us (even though it helped improve our infra in a way). Plus, now that I know we can't actually get any support with our plan, it's not ideal.

Anyway, before doing the switch we would obviously have to check if this doesn't happen with a normal Prometheus instance as well, just in case... :sweat_smile: We did skip multiple major versions all at once.

**Comment by npepinpe** [comment]
I've found a workaround, since the values are _always_ 0. Simply append the following at the end of your PromQL query: ` != 0`

For example, given

```
sum(increase(atomix_compaction_time_ms_bucket{namespace=~"np-flush-sync"}[5m])) by (le)
```

Simply change it to:

```
sum(increase(atomix_compaction_time_ms_bucket{namespace=~"np-flush-sync"}[5m])) by (le) != 0
```

Which will ignore all zero values and show appropriate results. So in the meantime we could implement this as a quick fix, as it doesn't hurt. Although we should verify if this would skew the scale sometimes where we have only very low values.

It still doesn't explain why this happens in the first place, of course...

**Comment by megglos** [comment]
Planning: The workaround would be something worth applying in the next iteration.

**Comment by shahamit** [comment]
I am facing a similar issue when trying to analyse the process instance execution times during a load test. The load test is executed using the [camunda-8-benchmarking](https://github.com/camunda-community-hub/camunda-8-benchmark) tool with `taskCompletionDelay` configured as 5 secs instead of few ms. Our goal is to find the cycle time when running the load tests with real time api response times which in our case could be ranging from 5-20 secs. 

When running load tests with varying `taskCompletionDelay` from 5, 10 and 20 secs we see the same process instance execution time (avg) graph having 1.68 Bil secs. Other latency panel screenshots are also displayed below. I got the link to this issue from [this forum](https://forum.camunda.io/t/how-to-calculate-cycle-time-from-grafana-dashboard/43037) discussion.

Kindly share your insights on this and let me know if there is a way to find the cycle time when it goes beyond 10 secs.

Thanks.

![image](https://user-images.githubusercontent.com/1281926/226311631-38fa9f56-467c-43c8-8baa-c77d86e2599c.png)
![image](https://user-images.githubusercontent.com/1281926/226312327-e00e7876-0996-4816-9e7e-a1e3dd00af95.png)
![image](https://user-images.githubusercontent.com/1281926/226312352-c861755f-22da-476c-bb45-c2fda80faf53.png)

**Comment by deepthidevaki** [comment]
I'm not sure about the workaround that uses `by (le) != 0` .

For ActivateJobs latency it shows some gaps with no data
![image](https://user-images.githubusercontent.com/1997478/229736327-e67e9ecf-72f7-48d5-9da9-0a0f663c35a5.png)

![image](https://user-images.githubusercontent.com/1997478/229736444-1a0b66e2-aa9b-43a7-b778-7fc169a59ad3.png)


while there is actually some new values in the buckets.
![image](https://user-images.githubusercontent.com/1997478/229737861-3d171e34-a28c-4208-8327-a3622496ad25.png)

**Comment by deepthidevaki** [comment]
@shahamit The default buckets range from 0 - 10seconds. So anything above 10 seconds, you wont' be able to see precisely in the histogram. In your case, the process execution time indeed takes longer than 10 seconds.

**Comment by npepinpe** [comment]
Hm, I thought it might be because we show the increase, but it looks like there is one between 10:05 and 10:06, so why would it return 0? :thinking:

**Comment by deepthidevaki** [comment]
It seems the workaround adding `!=0` does not work. There were some cases where the histogram showed no data, even though there was increase in the bucket. So we are not sure how to fix it.

For the alternate solution, as @npepinpe said we can try to switch back to our own managed prometheous and see if it fixes it. I will leave it to discuss later. So the workaround won't be implemented.

**Comment by megglos** [comment]
Planning feedback by @npepinpe : Intermediate we could deploy self-managed Prometheus to confirm it's only a bug with the managed service.

@olegme-camunda : we could also try grafana cloud, costs are unclear though

**Comment by npepinpe** [comment]
Done via https://github.com/zeebe-io/infra/pull/42
