### ISSUE TITLE
Zeebe java client didn't get the region from the configuration

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/zeebe#11846]
**Describe the bug**

If I set up a java client for Zeebe with the CloudClientBuilder, it will only connect to the bru-2 cluster. I cannot use this client for other regions.

**To Reproduce**

Build a client with 
```
    zeebeClientBuilder = ZeebeClient.newCloudClientBuilder()
          .withClusterId(config.getProperty(ClientProperties.CLOUD_CLUSTER_ID))
          .withClientId(config.getProperty(ClientProperties.CLOUD_CLIENT_ID))
          .withClientSecret(ClientProperties.CLOUD_CLIENT_SECRET);      
    zeebeClient = zeebeClientBuilder.withProperties(config).build();
    LOG.info("Creating ZeebeClient using {}", zeebeClientBuilder);
        
    Topology topology = zeebeClient.newTopologyRequest().send().join();
    LOG.info("Cluster Topology: {}", topology);
```
and properties
```
zeebe.client.cloud.clusterId=xxx
zeebe.client.cloud.clientId=xxx
zeebe.client.cloud.secret=xxx
zeebe.client.cloud.region=bru-3
```

**Expected behavior**
Running this should cause an exception, as `bru-3` doesn't exist (at least for Zeebe).

Instead, it returns the topology from my cluster in bru-2.

**Environment:**
- OS: Windows
- Zeebe Version: 8.1.0
- Configuration: see above

**Comment by ingorichtsmeier** [comment]
After inspecting the tests, I saw that `bru-2` is handled as the default region: https://github.com/camunda/zeebe/blob/main/clients/java/src/test/java/io/camunda/zeebe/client/ZeebeClientTest.java#L248-L265

Is this still valid as we support more regions and the default region for Free clusters is North America?

There is a property for the region missing in [io.camunda.zeebe.client.ClientProperties](https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/ClientProperties.java).

Would this be the fix to add the property?

**Comment by korthout** [comment]
This is a great issue to get started with contributing to Zeebe. It's quite clear what needs to happen: add `region` property to the client configuration properties.

It may teach you about how the java client works, and how it can be configured to connect to a cluster.

There are workarounds available: use the `.withRegion` method to set the region, or use the spring-zeebe-client.

**Comment by ogkunald** [comment]
Hello @korthout please review the PR ^_^.Thanks!

**Comment by ingorichtsmeier** [comment]
Hi @ogkunald,

I think that you should add some more tests on this topic here: https://github.com/camunda/zeebe/blob/main/clients/java/src/test/java/io/camunda/zeebe/client/ZeebeClientTest.java

What happens, if a value for your new property is given? -> The client should connect to the given region
What happens, if no value for your new property is given? -> The client should connect to bru-2

My expectation is, that especially this statement `zeebeClientBuilder.withProperties(config).build();` will work for another region than `bru-2`.

**Comment by ogkunald** [comment]
#11870 
As per the suggestion above in thread, I have added couple of tests-
1. value for cloud `region property` is provided , client will connect to region provided
2. value for cloud `region property` is not provided ,client will connect to default (bru-2) region.

Please review and revert in-case of anything.
