### ISSUE TITLE
Define maximum numbers of recipients for a correlated message 

### ISSUE THREAD

**Issue by berndruecker** [camunda/zeebe#1185]
AT:

- The max number of recipients can be set when handing in a message via API (n)
- The message can be correlated multiple times to different workflow instances up to the max number of recipients (n)
- When it is correlated again after that (n+1) an error is raised 

Context:

- Sometimes you want to define the exact number of recipients, often set to exactly 1.
- Setting the number to 1 also makes the engine BPMN compliant
- There are good examples when you want to correlate to a known amount of workflow instances (e.g. think about an "bank transfer received" being correlated to a waiting order, if this is correlated to multiple orders because of some implementation mistake it would not be such a good idea).

Probably related to https://github.com/zeebe-io/zeebe/issues/1017 (implementation wise)

**Comment by saig0** [comment]
I'm not sure about raising an error/incident. Should the incident be created for the workflow instance which entered a message catch event? How can the incident be resolved?

An option could be to delete the message after the max number is reached, similar to TTL behavior. After the message is deleted, it can't be correlated anymore.

@berndruecker , what do you think about this?

**Comment by berndruecker** [comment]
It would be probably the easiest behavior to start with and I could imagine that it is sufficient for the use cases I have in mind. And I do understand that it quickly gets complicated otherwise. 

The incident in this case would be indirect: Another workflowInstance will timeout while waiting for a message which could be again some incident - and some operator would probably find that the message was delivered earlier to a workflowInstance it shouldn't and resolve the bug.

So spontaneously I think that could be sufficient.

**Comment by berndruecker** [comment]
What's with this scenario:

- A message is sent with n=1
- Two workflow instances are already waiting

This is hard to answer - as I consider both  approaches kind of valid

- Throw an exception and correlate non of them (BPMN compliant and comparable to Camunda BPM)
- Correlate the first and do not do anything more (consistent in a way that it is the same behavior as if the second instance would have arrived a bit later than the message).

**Comment by saig0** [comment]
I would prefer the second option (correlate to the first instance only). So the first instance can continue and no manual operation is required. The second instance may continue later when a second message is received.

**Comment by berndruecker** [comment]
The downside of this approach is that it is harder to spot correlation errors (e.g. an implementation bug causing messages that should be unique be correlated to multiple instances). So I definitely also see a value in a behavior where the user can say "hey, send this message to exactly one instance, if that is not possible let me know (throw an exception) then I can sort it out". 

Not sure about all implications of this (confusing API? Implementation effort? ...?) though.

**Comment by Zelldon** [comment]
Is this still something we want to have? Or can this be closed ? @berndruecker @saig0

**Comment by saig0** [comment]
From my side, we could close the issue for now. If we see a strong need for it again, we can reopen the issue and provide more details about the use case.

**Comment by berndruecker** [comment]
I still think it is valuable, but if we don't see customer pull let's close it for now and reopen once we see it in the field...
