### ISSUE TITLE
Migrate from `GatewayStub` to `JobClient` in the `JobPoller`

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#11884]
**Is your feature request related to a problem? Please describe.**
I think that this needs to be done for basically two reasons:
1. Consistency. We will start to use a single class to gain the info and in case we need to modify the caller part - we just modify `JobClient`
2. Metrics. Source: https://camunda-platform.slack.com/archives/C6WGNHV2A/p1677234921004609. So, this continues the previous point - we need to have a single place to introduce metrics - I bet that the `JobClient` and `ZeebeClient` would be better ones.

**Describe the solution you'd like**
We implement the method `public ActivateJobsCommandStep1 newActivateJobsCommand()` in the `JobClient` and use it in the `JobPoller`.

**Describe alternatives you've considered**
We could just use the same method in the `ZeebeClient` but it feels not right to me 😅. Let all job calls will be in the `JobClient`.

**Additional context**
I could take this issue if you are okay with it. Also, I would like to take worker's metrics as well.

**Comment by aivinog1** [comment]
@npepinpe Do you mind if I take it and https://github.com/camunda/zeebe/issues/4700?

**Comment by npepinpe** [comment]
No, go for it. Ideally we should expose the same metrics as with the Go client.

It might be interesting to use a well established metrics facade here, e.g. OpenTelemetry, but I'll let someone from the automation team decide, as that would add a new dependency to our public API.

**Comment by korthout** [comment]
I think this is a great idea @aivinog1 👍 Thanks for raising it.

I see no reason to use the gateway stub directly. Note that the JobRunnerFactory already [uses the `jobClient` to fail the job](https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/impl/worker/JobRunnableFactory.java#L56) when an uncaught exception is thrown in the handler. So your suggestion would be in line with other implementation details.

👍 Feel free to go ahead with this refactoring.

I can see that this would be useful to collect metrics on the job client in a single place, but I wonder what metrics would be collected here. Would this only measure requests made with the client, or can we also use this for the metric mentioned in #4700 specifically:
>monitor the amount of jobs currently enqueued

@aivinog1 Let me know if you already have ideas to tackle that part.

@npepinpe You raise a good point about using an established metrics facade. I think I would also prefer it, but I need to read up on this topic first. @aivinog1, if you already have a  design in mind, please share it with me.

**Comment by korthout** [comment]
@aivinog1 I've assigned you. Please go ahead if you want to work on this 👍 

I've also marked this issue as `later later` as it is not among our team's priorities.

**Comment by galingerv** [comment]
When migrating Spring Boot app from 8.2 to 8.3 client (cluster 8.2), I faced an issue with increased latency of job activation.
It seems that JobPoller version 8.2 has some kind of streaming via implementing io.grpc.stub.StreamObserver (gateway streams after polling every partition). 
Whereas JobPoller 8.3 uses new API (ActivateJobs command) and does not stream jobs after polling every partition, instead it cumulates all jobs from all partitions and returns to the client. 
As a consequence, on large clusters with 30+ partitions job activation latency increased heavily regardless of how many clients are polling. 

@korthout @aivinog1 are there tests that would show this?

**Comment by korthout** [comment]
@galingerv On large clusters with 30+ partitions, you're probably better off switching to [job streaming](https://docs.camunda.io/docs/next/components/concepts/job-workers/#job-streaming).

**Comment by galingerv** [comment]
@korthout ok, that sounds very reasonable, just telling my experience of thoubleshooting the latency growth to anyone who might face the same issue. After reading the docs, the new streaming approach is proposing softly, as an alternative that is better than "old" polling strategy. But nowhere I could see that the "old" approach is working less optimal after upgrading the client.
