### ISSUE TITLE
Expire multiple messages in single command

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#11953]
**Description**

To further improve the performance of message expiration (see #11591), it would be useful if the Message TTL Checker does not write individual `Message:EXPIRE` commands for each message it visits. Instead, it could write a single `MessageBatch:EXPIRE` command to expire a batch of messages simultaneously.

**Comment by remcowesterhoud** [comment]
In ZPT we have an assertion that checks if a message is expired. This checks for the Message EXPIRED event. Depending on the solution chosen here we might have to make changes in ZPT.

**Comment by korthout** [comment]
It may be best to simply keep the events the same, and only change the command

**Comment by korthout** [comment]
Marking this as `good first issue` since we have documented how to add a new record in `./docs/`.

We think this is important to work on, but not urgent now. Marking it as `later`.

I've assigned @aleksander-dytko to keep an eye on this issue.

**Comment by abbasadel** [comment]
Hi, I'm talking over this issue to get started.
