### ISSUE TITLE
Recent version becomes more often unhealthy

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11954]
**Describe the bug**

It looks like that our recent version (main and alphas) become much more unhealthy, right now the cause it not clear. Might be related to batch processing.

**Release 8.0**

![release-8-0-x](https://user-images.githubusercontent.com/2758593/223386401-3efbc88f-0dfe-47a0-b720-2386b39490bb.png)

**Release 8.1**

![release-8-1-x](https://user-images.githubusercontent.com/2758593/223386474-b0363985-5566-427d-b4e7-0bab27298b03.png)

**Medic weeks:**

_Week 9_

![medic-9](https://user-images.githubusercontent.com/2758593/223386602-b06bdf61-9494-4ba8-8dab-4c5be72b00a7.png)

_Week 10_ 

![medic-10](https://user-images.githubusercontent.com/2758593/223386574-54cc5418-1e97-4c2d-a739-7eba85d785fd.png)

It doesn't look like that pod restarts are cause of this:

_Week 9_
![medic-9-general](https://user-images.githubusercontent.com/2758593/223392021-0a7c666f-3a80-43a1-898b-46f78c60b1e9.png)

_Week 10_
![medic-10-general](https://user-images.githubusercontent.com/2758593/223392028-872affcb-d79e-4c3b-a670-073edfa7c847.png)

**To Reproduce**

Run a benchmark and change the healthy panel to graph.

**Expected behavior**

We shouldn't become unhealthy if we can still making good progress. We need to investigate further what is happening here.

BTW would be great if we have a health graph as shown above per default to see healthiness over time.

**Environment:**
- OS: 
- Zeebe Version:main / 8.2.0-snapshot
- Configuration:

**Comment by Zelldon** [comment]
When such unhealthiness occur we see this:

```
DEBUG 2023-03-07T06:10:56.811712760Z [resource.labels.containerName: zeebe] Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=HEALTHY}, raft-partition-partition-1{status=HEALTHY}, Broker-2-Exporter-1{status=HEALTHY}, Broker-2-StreamProcessor-1{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, throwable=null, cause=null]}, Broker-2-LogStream-1{status=HEALTHY}, Broker-2-SnapshotDirector-1{status=HEALTHY}]
WARNING 2023-03-07T06:10:56.838060754Z [resource.labels.containerName: zeebe] Partition-1 failed, marking it as unhealthy: Broker-2{status=HEALTHY}
DEBUG 2023-03-07T06:10:56.838509579Z [resource.labels.containerName: zeebe] Detected 'UNHEALTHY' components. The current health status of components: [Partition-2{status=HEALTHY}, Partition-1{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=Broker-2-StreamProcessor-1{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, throwable=null, cause=null]}]}, Partition-3{status=HEALTHY}]
```

**Comment by megglos** [comment]
Might have been occurred even earlier than week 9, needs to be validated.

**Comment by Zelldon** [comment]
Still happens in week 14

![medic](https://user-images.githubusercontent.com/2758593/229811864-4edab271-4bd1-4819-8fc7-903bccd61326.png)

**Comment by Zelldon** [comment]
I checked today the metrics and somehow this is not always occurring.

![general](https://user-images.githubusercontent.com/2758593/230414207-b0520a73-ee08-49fc-8c5c-43dbf7309d41.png)

But if it starts to occur then it seems to be related to the processing and occurs more often. [Logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-y-2023-cw-14-971a677-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-y-2023-cw-14-971a677-benchmark%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22;timeRange=2023-04-06T08:50:06.603Z%2F2023-04-06T08:50:06.603Z--PT1H;pinnedLogId=2023-04-06T08:48:38.606587557Z%2Fy3p32c5vq3hsvamc;cursorTimestamp=2023-04-06T08:48:38.716178683Z?project=zeebe-io)

```
Detected 'UNHEALTHY' components. The current health status of components: [Partition-2{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=Broker-1-StreamProcessor-2{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, throwable=null, cause=null]}]}, Partition-1{status=HEALTHY}, Partition-3{status=HEALTHY}]
```

To me it is right now unclear how it can appear to be blocked, since the check is done every 5 seconds (or should be) 
https://github.com/camunda/zeebe/blob/main/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java#L278-L280


and the time is multiplied with factor 2. Interesting is that is using the ActorClock, which I'm not sure what it will return here. 

https://github.com/camunda/zeebe/blob/main/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java#L478-L495

**Comment by Zelldon** [comment]
I have added some metrics before easter holidays, https://github.com/camunda/zeebe/tree/zell-timer-metrics

Furthermore, I deployed benchmark to observe whether the timers are executed too late. 

It looks like that in the cases when the partitions become unhealthy, the timers haven't been executed after 5 seconds (as normal) they have been executed much later (10+), which causes the healthy check to become unhealthy.

Right now it is unclear why. In the batch processing metrics or processing metrics we CANT see anything
 strange that an actor is hoged 


![healthtimer](https://user-images.githubusercontent.com/2758593/232491119-f2f5049f-af14-44f7-8430-63a90d1cb344.png)

**Comment by Zelldon** [comment]
As it doesn't seem to happen so much anymore in the recent benchmarks I will move it to the backlog again, we have currently other pressing topics. 

Week 16 (last hours)
![cw16](https://user-images.githubusercontent.com/2758593/232492616-6139f0fe-cb33-4af0-ac5a-56d4aa264689.png)

Week 15 benchmark (last 24 hours)

![cw15](https://user-images.githubusercontent.com/2758593/232492637-f33cf956-59b7-458b-8fb1-ac2b72e21469.png)


\cc @megglos

**Comment by Zelldon** [comment]
As discussed with @megglos we will close this, we can reopen this when we see it to happen again.
