### ISSUE TITLE
Support Self-Signed/Elastic Certificates for connection to Elastic

### ISSUE THREAD

**Issue by abbasadel** [camunda/zeebe#11978]
## Introduction

Currently self-signed certificates are not supported when connecting to Elastic which is required by some customers

## Concept
As a Admin / SRE I can configured self-signed certificates for connection to Elastic, [similar to the support provided by Operate ](https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#settings-to-connect)

```[tasklist]
### Tasks
- [ ] Investigate and understand the scope of this requirement
- [ ] Add more tasks as needed

```
## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/583 
- https://jira.camunda.com/browse/OPT-6790

**Comment by npepinpe** [comment]
Should we close this older issue then? https://github.com/camunda/zeebe/issues/9839

**Comment by korthout** [comment]
Closing this in favor of https://github.com/camunda/zeebe/issues/9839
