### ISSUE TITLE
Where to find MemberType class?

### ISSUE THREAD

**Issue by kitepad** [camunda/zeebe#11996]
**Describe the bug**

Clone github repo, import into eclipse as maven project. But report compile error : can not find MemberType class in SerializerUtil class.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by Zelldon** [comment]
You have to build the project with maven first. These classes are auto generated.
