### ISSUE TITLE
I would like to ask why sometimes at a certain time (the probability is very small), the position is relatively large can be found, but sometimes the position is relatively small can not be found. It should be between milliseconds. The probability is very small.

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#12019]
io.camunda.zeebe.exporter.ElasticsearchExporter,I would like to ask why sometimes at a certain time (the probability is very small), the position is relatively large can be found, but sometimes the position is relatively small can not be found. It should be between milliseconds. The probability is very small.

**Comment by Zelldon** [comment]
You issue is really vague, I guess you mean something like this https://github.com/camunda/zeebe/issues/11506

Please provide next time a bit more details, like which version you're running, the type of exception with stacktrace. Ideally also something which helps to reproduce it or understand the situation you're  seeing better.

I will close this issue, as I think it is a duplicate.
