### ISSUE TITLE
Unnecessary Blacklist checks

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#12041]
**Description**

_Related to https://github.com/camunda/zeebe/issues/12035_
_Related to https://github.com/camunda/zeebe/issues/12033_
_Came up in https://github.com/camunda/zeebe/issues/11813_

> _Blacklist checks_
> 
> With (almost) every command, Zeebe will check if the given process instance is blacklisted, even if the process instance is just created. Also, this check happens all the time during batch processing:
> 
> https://github.com/camunda/zeebe/blob/ae6dbfc5439c889ad8b8fd24d7431b46110c7900/engine/src/main/java/io/camunda/zeebe/engine/Engine.java#L130-L134
> 
> Just some a thoughts on how this could be improved:
> * Cache the information that there is no blacklisted process instance so that Zeebe avoids the lookup in RocksDB.
> * Avoid doing the check with every (follow-up) command during batch processing.
> * When creating a new process instance, the check is unnecessary.
> * TBD: If there are blacklisted process instances, how to make the lookup efficient.
>

**Comment by megglos** [comment]
https://github.com/camunda/zeebe/pull/12306
covers:

- [x] Cache the information that there is no blacklisted process instance so that Zeebe avoids the lookup in RocksDB.
- [x] When creating a new process instance, the check is unnecessary.
