### ISSUE TITLE
can not update zeebe from 1.2 to 1.3 in local

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#12058]
I update zeebe from 1.2.4 to 1.3.7 in local, in the process, someone is 1.2.4,and othes are 1.3.7 in the same zeebe cluster.
I see some partitions look like unhealthy, and will miss variable when using the "jobClient.newCompleteCommand(job.getKey()).variables(variables).send()".

**Comment by korthout** [comment]
Hi @jerry123888 Thanks for reporting.

Without additional details about your situation, it is impossible to resolve your issue. I'm closing this for now. Please re-open if you can provide more details.

Some details you could provide:
- are you using Camunda Platform 8 SaaS or do you run Zeebe in Self-Managed mode?
- how do you see that your partitions are unhealthy? Do you have access to the Grafana Dashboards? If so, please provide some screenshots of this.
- what do you mean that variables are missing? Are the variables empty in the job handler or in the process? 
- If they are missing from your process, are you sure you are passing variables along with the complete command? And how do you know they are missing from you process? Do you use Operate, Simple-Monitor or something else?

**Comment by jerry123888** [comment]
> Hi @jerry123888 Thanks for reporting.
> 
> Without additional details about your situation, it is impossible to resolve your issue. I'm closing this for now. Please re-open if you can provide more details.
> 
> Some details you could provide:
> 
> * are you using Camunda Platform 8 SaaS or do you run Zeebe in Self-Managed mode?
> * how do you see that your partitions are unhealthy? Do you have access to the Grafana Dashboards? If so, please provide some screenshots of this.
> * what do you mean that variables are missing? Are the variables empty in the job handler or in the process?
> * If they are missing from your process, are you sure you are passing variables along with the complete command? And how do you know they are missing from you process? Do you use Operate, Simple-Monitor or something else?

Now  i have a online zeebe cluster with 18 pods, the version is 1.2.4 and run as well. Now I want to update these pods from 1.2.4 to 1.3.7,   how can i do? i meet some questions when upgrading 2 pods from 1.2.4 to 1.3.7 and then close 2 pods with 1.3.7 . The left 16 pods with 1.2.4 works well, but some Partition become unhealthy. So, does the zeebe supports  online upgrade from 1.2.x to 1.3.x? 

@korthout

**Comment by korthout** [comment]
Zeebe does **not** support **rolling updates** at this time. How to update an existing Zeebe cluster is documented here: https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/operations/update-zeebe/#update
