### ISSUE TITLE
mac m1 zeebe The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by stromyu520** [camunda/zeebe#12094]
zeebe The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

tasklist The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
 ⠋ operate The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested   0.0s

**Comment by megglos** [comment]
Hey @stromyu520,
from `8.2.0-alpha3` onwards we provide docker images for both arm64 and amd64.
Thus the upcoming `8.2.0` stable release will also offer images for both platforms by default.

Will thus close this issue given newer releases offer native M1 support.

**Comment by stromyu520** [comment]
Thank you for your answer

**Comment by stromyu520** [comment]
@megglos Thank you for your answer
