### ISSUE TITLE
Zeebe Support Elastic Search 8

### ISSUE THREAD

**Issue by abbasadel** [camunda/zeebe#12132]
## Introduction

- ES 8 has been out for many months already.
- ES 7 runs out of support 8/2023.
- Currently, C8 SM only supports Elastic 7.x

Since Elastic Search 8 no longer support `curator`, we need to implement `ILM` into the relevant products as a replacement.

See https://github.com/camunda/product-hub/issues/121

## Task Breakdown

- We need to define a default ILM policy and link this policy to the relevant template. Use Operate [Implementation](https://github.com/camunda/operate/issues/4161#issuecomment-1480737663) as reference

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues/4161#issue-1595061176)

## Links
[Slack Discussion](https://camunda.slack.com/archives/C050FPH27K2/p1679497868240339)  | [Elastic Docs](https://www.elastic.co/guide/en/elastic-stack/8.6/upgrading-elastic-stack.html) | [Product Hub](https://github.com/camunda/product-hub/issues/121)

**Comment by korthout** [comment]
## Being able to export :white_check_mark: 
I ran a quick local test using Docker Compose with Zeebe & Operate 8.1.9, ES & Kibana 7.17.5. After some data was exported by Zeebe and read by Operate, I used Kibana’s Upgrade Assistant (and [this guide](https://www.elastic.co/guide/en/elastic-stack/8.6/upgrading-elastic-stack.html#prepare-to-upgrade)) to check for problems. There were no reported problems. I then upgraded ES & Kibana to 8.6.2. After that, I exported some more data into ES and saw that it arrived in Kibana, and I was able to find it in Operate as well.

## About ILM as curator replacement :webex-waiting-spinner:
AFAIK, Curator was not part of Zeebe in C8 SM, and Curator in C8 SaaS is managed by SRE (please correct me if I’m wrong). So, I suggest the following:
- For Zeebe in C8.2 SM: document [how users can use ILM](https://github.com/camunda/operate/issues/4161#issuecomment-1480737663) to delete Zeebe’s exported records from ES after a self-defined retention time (or not, it’s just a part of ES8 anyways and currently undocumented as well :shrug: up to product management if you think we need this)
- For Zeebe in C8.2 SaaS: discuss with SRE whether they can set up [ILM policies and use these for the zeebe record indices](https://github.com/camunda/operate/issues/4161#issuecomment-1480737663) for all clusters using ES8
- For Zeebe in C8.3 (or later) SM: add a configuration option to Zeebe’s ES exporter that allows specifying a minimum age that, when set, creates a new policy and uses that policy in the record templates.

**Comment by korthout** [comment]
For documentation, using the steps [here](https://github.com/camunda/operate/issues/4161#issuecomment-1480737663):
- specify how to create the policy
- specify to set the policy for all Zeebe record indices: `zeebe-record*`

**Comment by korthout** [comment]
Thanks for raising this @Zelldon I'll discuss it with product-management
