### ISSUE TITLE
Support for conditional properties in FEEL

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/zeebe#12143]
**Is your feature request related to a problem? Please describe.**
It would be really helpful if we could **define a feel expression value based on conditions defined inside this same feel expression**.

In short: sometimes when we call an API update based on the http-json(rest) template we should only call it with a body containing parameters we want to change. Adding null values to these parameters are not sufficient, we should omit these entirely.

For example: I would like to create a template based on the http-json (rest) connector to call an API which will update an entity. It will do this update based on the defined properties inside the body which we will construct based on a feel expression and user input and represent it as a hidden field. In the element template we have to offer every possible property for the user, but he or she might only want to change a few of them, and leave the rest blank. 
The problem is that if we construct the body based on this, _there will be properties with null values_. The null values can be interpreted as valid values by the API backend, and upon the update, these entity properties will be deleted, even though it was not intended by the user.

**Describe the solution you'd like**
Something like this: `={if issueTitle != null then ("title": issueTitle,) if issueBody != null then ("body": issueBody,) if issueState != null then ("state": issueState)}`

**Describe alternatives you've considered**
Theoretically you could create a field for every possible permutations of the properties and use the proper hidden field, but that would cause serious headache.

**Comment by korthout** [comment]
Hi @markfarkas-camunda 👋 That is an interesting case, and I assume more users may run into it when using FEEL to define JSON objects.

One way to leave out properties of a FEEL context is to build the context dynamically using [`context put(context, key, value)`](https://camunda.github.io/feel-scala/docs/reference/builtin-functions/feel-built-in-functions-context/#context-putcontext-key-value), when the value [`is defined(value)`](https://camunda.github.io/feel-scala/docs/reference/builtin-functions/feel-built-in-functions-boolean#is-definedvalue). However, this may be cumbersome to use:

```feel
if is defined(y) then context put({}, x, y) else {}
```

Composing multiple calls becomes tedious, but it can be simplified slightly using a function property.

```feel
{
  dynamicPut: function(c, k, v) if is defined(v) then context put(c, k, v) else c
  context: dynamicPut(dynamicPut({}, y, anotherMissingVar), x, optionallyMissingVar)
}.context
```

@markfarkas-camunda Please let me know if this solves your problem.

---

AFAIK, FEEL does not support an `undefined` keyword like JSON, this could be useful to express simplify expressing the difference between a missing value `null` and an undefined value `undefined`
//cc @saig0 @nikku @falko 

```feel
{
  x: if is defined(optionallyMissingVar) then optionallyMissingVar else undefined
  y: if is defined(anotherMissingVar) then anotherMissingVar else undefined
}
```

```feel
is defined(null)
// true

is defined(undefined)
// false
```

**Comment by korthout** [comment]
@markfarkas-camunda I'm closing this issue in favor of a feature request in our FEEL engine:
- https://github.com/camunda/feel-scala/issues/622

**Comment by korthout** [comment]
@markfarkas-camunda Please have a look at the other alternative for this suggested here:
- https://github.com/camunda/feel-scala/issues/622#issuecomment-1549142442
