### ISSUE TITLE
Disable dependabot on forks

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#12182]
**Description**

I forked [zeebe](https://github.com/korthout/zeebe) and noticed that Dependabot opened a bunch of [pull requests](https://github.com/korthout/zeebe/pulls) to my fork. This is probably really annoying for anyone using a fork of zeebe.

**Comment by skayliu** [comment]
Hey, @korthout, It's not happen in my fork [zeebe](https://github.com/skayliu/zeebe).

**Comment by korthout** [comment]
Thanks for sharing that @skayliu It's very interesting

🤔 I wonder why Dependabot opens pull requests to my fork, and not yours. The craziest part is that Dependabot isn't even enabled on my fork 😆 
<img width="1514" alt="Screenshot 2023-03-31 at 12 31 31" src="https://user-images.githubusercontent.com/3511026/229096795-0aa66d4d-5f83-4287-ad16-6e84e5f0b952.png">

I see that your fork has a lot of failing Action workflows, is that bothering you or are you okay with that?

**Comment by skayliu** [comment]
@korthout, Yeah, it's a bit annoying, I'm wondering how to disable or close the Action workflows.

**Comment by korthout** [comment]
@skayliu I was able to disable Actions under: Settings > Actions > General > Action Permissions > Disable actions.

However, that disabled all actions. Are there any actions you would still like to use on your own fork? Or would it be fine just to disable all of them?

**Comment by korthout** [comment]
@skayliu Let me know if you ever need any. We could configure them to run only on the camunda/zeebe repo.

**Comment by skayliu** [comment]
`run only on the camunda/zeebe repo` is a good option.

**Comment by korthout** [comment]
Ok, I figured it out. It seems my fork is a bit older and therefore doesn't have this fix: https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/

I need to delete my fork and re-fork zeebe.
