### ISSUE TITLE
broker frequently gc

### ISSUE THREAD

**Issue by TangJiong** [camunda/zeebe#12208]
**Describe the bug**

3 brokers in our zeebe cluster are busy in gc threads, causing broker CPU high load.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
**abnormal borker: broker-12**

<img width="864" alt="broker-12" src="https://user-images.githubusercontent.com/7720306/229307471-d8edd21d-2bef-4eff-8958-e239a77cc6e9.png">

**abnormal borker: broker-14 **

<img width="877" alt="broker-14" src="https://user-images.githubusercontent.com/7720306/229307477-589e5650-8dbe-46ee-a076-5d664d431a95.png">

**abnormal borker: broker-16 **

<img width="865" alt="broker-16" src="https://user-images.githubusercontent.com/7720306/229307466-950a0da8-b784-4a1b-84fc-7d2828dbab2f.png">

**normal borker: broker-4 **

<img width="837" alt="image" src="https://user-images.githubusercontent.com/7720306/229307534-7070bb72-7e68-476e-90cf-511e351086f9.png">

</details>

**Environment:**
- OS: Linux
- Zeebe Version: 1.2.4
- Configuration:

**Comment by Zelldon** [comment]
GC is a normal event in a java application, so this might happen. Do you indicate that something doesn't work or behaves unexpectedly? Do you feel it is stuck in gc or does to many? Do you have any metrics you can share?

The configuration of the brokers would be helpful as well. Be aware that your version is quite old, I would recommend to update. There have been fixed a LOT of issues in the last years.

**Comment by korthout** [comment]
@TangJiong version 1.2.4 is no longer supported by the team. Please update to the latest patch of 8.0, 8.1, 8.2. I'll close this issue as won't fix because it may already be resolved in current versions. If you encounter the same problem on one of those versions please re-open the issue with additional details.
