### ISSUE TITLE
many many raft-partition-partition-xx.log in disk

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#12207]
![image](https://user-images.githubusercontent.com/92800459/229302333-22f69c67-8688-41f0-a7ed-47038b1f9b35.png)
zeebe-1.2.4 cluster, 18 pods, 54 partitions, and 2 pods cannot work.
In one pods, i found many many log files in /usr/local/zeebe/data/raft-partition/partitions/xx, and no found in the others pods.
can i clear these logs, because these files will use up all of the  disk.

**Comment by Zelldon** [comment]
Hey @jerry123888 

looks like the partition can't compact the log. This can have multiple reasons, like exporter is not able to export or processing is stuck or no snapshot can be taken. 

Is you disk already full? Is this the only partition with large log? Do you see any errors/warnings in the console log? Do you have any metrics which show the health of the system?

Can you share the name of the latest snapshot? Maybe also when it was last taken.

**Comment by korthout** [comment]
>can i clear these logs, because these files will use up all of the disk.

@jerry123888 No, these logs contain the log stream data that the workflow engine is built upon. When Zeebe is finished with these logs it is supposed to be cleaned up automatically, i.e. the log is compacted. This is what @Zelldon refers to as the problem you should investigate.

**Comment by megglos** [comment]
Hey @jerry123888 ,

thanks for reaching out, given the previous responses and no follow-up question yet from your side we would close this issue.
Feel free to reopen if anything is unclear.
