### ISSUE TITLE
Jobs of banned Process Instance can still be activated

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#12239]
**Describe the bug**

When a process instance is banned it is still possible to interact with the jobs of this instance. They can be activated/completed as usual.

This behavior makes it so a worker could work on jobs of a banned instance. It also means that it's possible for incidents to be created for a banned instance. This could be very confusing for users, especially if the banned instance has been marked as canceled in Operate.

**To Reproduce**

[repro.bpmn.zip](https://github.com/camunda/zeebe/files/11147242/repro.bpmn.zip) (don't try to open this in Modeler, it will crash)

To test this locally make sure to change the `DEFAULT_MAX_COMMANDS_IN_BATCH` in the `StreamProcessorContext` to 1!

Deploy the model
```
zbctl --insecure deploy resource repro.bpmn
```

Start an instance
```
zbctl --insecure create instance Process_0uh5a2g
```

Starting this instance will result in a banned process instance, with an open job. Activating the job still works
```
zbctl --insecure activate jobs jobtype
```

The job can also still be completed
```
zbctl --insecure complete job <jobkey>
```

**Expected behavior**

When a process instance is banned we should make sure the jobs that belong to this instance cannot be activated. This way a worker can't pick them up and no further incidents could occur on the banned instance.

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by korthout** [comment]
ZPA triage:
- we may want to replace the blacklist concept in 8.3
- we will first look into #8263 to understand how often this happens
- @remcowesterhoud please make an epic to co-ordinate these efforts

**Comment by abbasadel** [comment]
ZPA Team meeting:
- Changed the priority to "Upcoming" to work on this on the upcoming iterations

**Comment by npepinpe** [comment]
Also affects this customer: https://jira.camunda.com/browse/SUPPORT-17696

**Comment by megglos** [comment]
removing from upcoming as we rather want to replace banning with a different solution that also allows to recover the instance
