### ISSUE TITLE
The `newThrowErrorCommand` incorrectly handled in `8.2.0`

### ISSUE THREAD

**Issue by igpetrov** [camunda/zeebe#12326]
Hi Zeebe Team, please consider the following bug

**Describe the bug**

Given the [following code snippet](https://github.com/camunda/connector-sdk/blob/main/runtime-util/src/main/java/io/camunda/connector/runtime/util/outbound/ConnectorJobHandler.java#L145-L150).

The `newThrowErrorCommand` cannot be handled via BPMN.

**To Reproduce**

1. Clone [camunda platform docker compose repo](https://github.com/camunda/camunda-platform).
2. Keep `CAMUNDA_PLATFORM_VERSION` as `SNAPSHOT` or `8.2.0` in the `.env` [file](https://github.com/camunda/camunda-platform/blob/main/.env#L4).
3. Run any variant, e.g. core as `docker-compose -f docker-compose-core.yaml up`.
4. Deploy and start a BPMN diagram attached to this ticket: [error-handling.bpmn.txt](https://github.com/camunda/zeebe/files/11178216/error-handling.bpmn.txt).
5. See an error: `Expected to throw an error event with the code '500' with message 'Got a 500', but it was not caught. No error events are available in the scope.`

![Screenshot 2023-04-07 at 13 25 51](https://user-images.githubusercontent.com/108870003/230594417-d92ba764-6387-49a7-a9c7-b6773b66e863.png)

![Screenshot 2023-04-07 at 13 26 02](https://user-images.githubusercontent.com/108870003/230594436-9703f853-5e96-4d4f-8676-3509789e59e9.png)

**Expected behavior**

Do the same as in **To Reproduce** except change the `CAMUNDA_PLATFORM_VERSION` to `8.1.10` or `8.1.9`.

See the process works correctly.

![Screenshot 2023-04-07 at 13 23 19](https://user-images.githubusercontent.com/108870003/230594734-ef38e7b0-48ec-4632-bd62-4378e34a6fef.png)

**Log/Stacktrace**

No valuable stacktraces.

**Environment:**
- OS:  MacOS 13.3 with M1 chip; Docker Engine version 20.10.23
- Zeebe Version: `8.2.0`, `SNAPSHOT` - reproducible; `8.1.10`, `8.1.9` - not reproducible.
- Configuration: [camunda-platform docker compose repo](https://github.com/camunda/camunda-platform/blob/main/docker-compose-core.yaml).

**Comment by remcowesterhoud** [comment]
I had a first look. This was introduced when [adding support for FEEL expressions in error codes](https://github.com/camunda/zeebe/pull/10972). 

In this PR we changed the way transform errors, by either setting the `errorCodeExpression` (not support by catch events) or by setting the `errorCode` directly. We _always_ parse the error code using the FEEL engine. In this case this will result in a static expression.
Where we're going wrong is that we make the assumption that this static expression can only be of the type `String`. In this case this is not true, it is a `Number` instead.

Relevant code:

```java
  @Override
  public void transform(final Error element, final TransformContext context) {

    final var error = new ExecutableError(element.getId());
    final var expressionLanguage = context.getExpressionLanguage();

    // ignore error events that are not references by the process
    Optional.ofNullable(element.getErrorCode())
        .ifPresent(
            errorCode -> {
              final Expression errorCodeExpression = expressionLanguage.parseExpression(errorCode);

              error.setErrorCodeExpression(errorCodeExpression);
              if (errorCodeExpression.isStatic()) {
                final EvaluationResult errorCodeResult =
                    expressionLanguage.evaluateExpression(errorCodeExpression, variable -> null);

                if (errorCodeResult.getType() == ResultType.STRING) {
                  error.setErrorCode(BufferUtil.wrapString(errorCodeResult.getString()));
                }
              }

              context.addError(error);
            });
  }
```

Looking into the `StaticExpression`  can only be of type `String` or `Number`
```java
  public StaticExpression(final String expression) {
    this.expression = expression;

    try {
      treatAsNumber(expression);
    } catch (final NumberFormatException e) {
      treatAsString(expression);
    }
  }
```

We must add the case for `Number` to the transformer. Alternatively we could introduce a `getAsString` method which will parse the `Number` to a `String`. Most of all we need tests cats to cover this!
