### ISSUE TITLE
Improve error handling of ClientStreamManager

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#12385]
## Description

The `ClientStreamManager` currently receives a payload from a broker, and should forward it to the appropriate consumer. However, it currently does no error handling, assuming the consumer will not fail, and will instead handle all errors appropriately.

As there are in fact error cases to handle at that level, and that we still want the consumer to decide what to do on error, we should refactor it to:

- [ ] The consumer will not recover from errors but instead throw an exception
- [ ] The manager will handle exceptions from the consumer and pass them on to a provided error handler
- [ ] The manager will also generally use the error handler for other error cases, on receiving a pushed payload, that may arise before calling the consumer

**Comment by deepthidevaki** [comment]
* [x]  The consumer will not recover from errors but instead throw an exception

This is already handled in ClientStreamManager. Any exception thrown by `ClientStreamConsumer#push` is caught by ClientStreamManager. Any other exceptions, such as serialization errors, will be passed back to the sender.

As we discussed, we won't do the following now. We want to try a different approach, where all errors are propagated back to the broker, and broker will react to the error by either retrying with another stream or making the job re-activatable.

* [ ]  The manager will handle exceptions from the consumer and pass them on to a provided error handler
* [ ]  The manager will also generally use the error handler for other error cases, on receiving a pushed payload, that may arise before calling the consumer
