### ISSUE TITLE
RebalancingEndpointIT#shouldRebalanceCluster

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#12396]
**Summary**

- How often does the test fail? once
- Does it block your work? no 
- Do we suspect that it is a real failure? likely not

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: Condition with alias 'All brokers are leader for exactly one partition' didn't complete within 30 seconds because condition with io.camunda.zeebe.it.management.RebalancingEndpointIT was not fulfilled.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
	at io.camunda.zeebe.it.management.RebalancingEndpointIT.reachesGoodLeaderDistribution(RebalancingEndpointIT.java:85)
</pre>
</details>

**Logs**

https://github.com/camunda/zeebe/actions/runs/4685456173/jobs/8302579182

**Comment by deepthidevaki** [comment]
There were no logs from the failed tests. #12428 saves logs from Zeebe container. Please collect the logs if the test fails again.

I'm closing this issue for now as there is no useful logs to debug.

**Comment by rodrigo-lourenco-lopes** [comment]
It happened here again: https://github.com/camunda/zeebe/actions/runs/6430039005/job/17460250829?pr=14432
Reopening this issue.

[logs_96295.zip](https://github.com/camunda/zeebe/files/12829718/logs_96295.zip)

**Comment by deepthidevaki** [comment]
@rodrigo-lourenco-lopes The attached file does not contain the logs from the failed test. You should collect the artifacts for the test. Example from another failed run for a unit test. 

![image](https://github.com/camunda/zeebe/assets/1997478/624e36ee-5994-4f2d-961d-f528cdecb20b)

Similarly you would see something like `Test Run for IT QA Integration Tests` for this test. 

I will close this again. Please reopen with the logs.
