### ISSUE TITLE
Switch custom AwsSignHttpRequestInterceptor in Opensearch exporter to library

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#12427]
**Description**

I recently came across this library: https://github.com/acm19/aws-request-signing-apache-interceptor
This provides a request interceptor to take care AWS request signing. Currently we are maintaining our own interceptor. It would be great to switch it for this maintained library so we can forget about it ourselves.

**Comment by korthout** [comment]
ZPA triage:
- we like the idea, this was suggested by someone from AWS
- pretty low-hanging fruit (just switch out the used interceptor and remove our own code)
- marking as `later` not needed immediately but could be done when we work on opensearch again
