### ISSUE TITLE
Broker cannot start with S3 accessKey and secretKey not supplied 

### ISSUE THREAD

**Issue by NingyuanZhang** [camunda/zeebe#12433]
**Description**
We are configuring brokers with the S3 backup properties as follows:
- ZEEBE_BROKER_EXPERIMENTAL_FEATURES_ENABLEBACKUP: true
- ZEEBE_BROKER_DATA_BACKUP_STORE: S3
- ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME: <s3_bucket_name>
- ZEEBE_BROKER_DATA_BACKUP_S3_REGION: us-east-1
- ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT: "https://s3.us-east-1.amazonaws.com"

We don't supply credentials through environment variables as they can be pulled from aws credentials provider chain. These properties worked on old version 8.1.9 but we got errors when switching to latest version 8.2.1 and broker cannot start due to the error:

> 
> 2023-04-14T11:21:51.313-04:00 | org.springframework.boot.SpringApplication - Application run failed
> 2023-04-14T11:21:51.313-04:00 | java.lang.IllegalStateException: Failed to execute CommandLineRunner
> 2023-04-14T11:21:51.313-04:00 | at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) [spring-boot-3.0.5.jar:3.0.5]
> 2023-04-14T11:21:51.313-04:00 | at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) [spring-boot-3.0.5.jar:3.0.5]
> 2023-04-14T11:21:51.313-04:00 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-3.0.5.jar:3.0.5]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:82) [camunda-zeebe-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | Caused by: io.camunda.zeebe.broker.system.InvalidConfigurationException: Failed configuring backup store S3
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:132) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-3.0.5.jar:3.0.5]
> 2023-04-14T11:21:51.313-04:00 | ... 3 more
> 2023-04-14T11:21:51.313-04:00 | Caused by: java.lang.NullPointerException: Access key ID cannot be blank.

It looks like io.camunda.zeebe.backup.s3.S3BackupStore.buildClient still calls AwsBasicCredentials.create(credentials.accessKey(), credentials.secretKey() even we don't pass in any credentials. It might be related to this commit: https://github.com/camunda/zeebe/commit/dfd3b9e1034365b3fc1859d5e35353826e1222b3#diff-1b91d4d4e6875c0169ea56f9c35382f5f194a1af782db4879a26971fe32e6daeL72-L74
We also noticed that none of your unit or integration tests are checking for cases where ACCESS_KEY, SECRET_KEY are not passed. 

Could you please look into this issue? Thank you!

**Comment by oleschoenburg** [comment]
Thanks for reporting @NingyuanZhang, you are right that https://github.com/camunda/zeebe/commit/dfd3b9e1034365b3fc1859d5e35353826e1222b3#diff-1b91d4d4e6875c0169ea56f9c35382f5f194a1af782db4879a26971fe32e6daeL72-L74 broke this use case.

I'll provide a fix for this and see if we can test this too.
