### ISSUE TITLE
[io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager] [Broker-0-zb-actors-1] WARN io.camunda.zeebe.gateway - Failed to activate jobs for type test from partition 4

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#12435]
```
[io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager] [Broker-0-zb-actors-1] WARN 
      io.camunda.zeebe.gateway - Failed to activate jobs for type Notify from partition 4
java.util.concurrent.TimeoutException: Request type command-api-4 timed out in 15000 milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:163) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

Hello, the zeebe log has been outputting this warning, and the cpu has reached more than 700%. Please tell me what caused it. Close all clients and restart the zeebe service. There is no client connection, and the cpu also reaches more than 700%. Finally, clean up the data and restart, and the CPU will be normal. The version used by zeebe is 1.0.0。
How to obtain the stack information of zeebe, using the jvm command, will be denied access.

**Comment by korthout** [comment]
Hi @bugbugmaker. Version 1.0 is no longer supported by the team. Please update to the latest patch of 8.0, 8.1, or 8.2 to make sure you are up to date with the latest bug fixes.

I'm closing this issue as won't fix. If you encounter the same problem on a supported version please re-open the issue with additional details:
- configuration used to run this
- info about load that is there on the system when the error occurs first
- provide a minimal reproducible example

**Comment by bugbugmaker** [comment]
> The version used by zeebe is 1.0.0。
> How to obtain the stack information of zeebe, using the jvm command, will be denied access.



> Hi @bugbugmaker. Version 1.0 is no longer supported by the team. Please update to the latest patch of 8.0, 8.1, or 8.2 to make sure you are up to date with the latest bug fixes.
> 
> I'm closing this issue as won't fix. If you encounter the same problem on a supported version please re-open the issue with additional details:
> 
> * configuration used to run this
> * info about load that is there on the system when the error occurs first
> * provide a minimal reproducible example

The version used by zeebe is 1.0.0。
How to obtain the stack information of zeebe, using the jvm command, will be denied access.
