### ISSUE TITLE
gateway-protocol proto reference issue

### ISSUE THREAD

**Issue by gakkiyomi** [camunda/zeebe#12481]
i'm current to run some zeebe tests,but i got a proto reference issue,be like this 
![image](https://user-images.githubusercontent.com/41406557/233053895-d2a6eced-fe6d-48b6-8fd7-98ac93675f01.png)

so,i gen proto java source code and move to `dist/srv/main/java/io.camunda.zeebe.gateway.protocol` but still not work.
![image](https://user-images.githubusercontent.com/41406557/233052276-f69439f1-0a37-4529-9f36-7f12c8b67480.png)
who can help me !

**Comment by Zelldon** [comment]
You have to build the project, please follow https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md#build-zeebe-from-source

BTW such question can be easily answered in our community, e.g. [slack](https://www.camunda.com/slack) or forum as well.
