### ISSUE TITLE
Provide Grafana Dashboards for the Actor metrics

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#12548]
**Is your feature request related to a problem? Please describe.**
I understand that [the Actor metrics](https://github.com/camunda/zeebe/blob/a3d2002a0eb74cc701572b4e02abfeb16d6a48a8/scheduler/src/main/java/io/camunda/zeebe/scheduler/ActorMetrics.java) are in the experimental phase, but it would be nice if there exists the Actor dashboard out of the box 🙂

**Describe the solution you'd like**
A separate file, called, for example, actor.json in [the Grafana dashboards](https://github.com/camunda/zeebe/tree/a3d2002a0eb74cc701572b4e02abfeb16d6a48a8/monitor/grafana) folder.

**Describe alternatives you've considered**
Add these metrics to the existing dashboard, for example, [zeebe.json](https://github.com/camunda/zeebe/blob/a3d2002a0eb74cc701572b4e02abfeb16d6a48a8/monitor/grafana/zeebe.json). But I think that it would be more convenient if we have this in a separate dashboard (some users may decide to not enable these metrics thus the dashboard is not needed for them)

**Comment by megglos** [comment]
ZDP-Triage:
- seems like a good first issue to pickup during an upcoming onboarding
