### ISSUE TITLE
Configurable limit on processing speed

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#12560]
**Is your feature request related to a problem? Please describe.**
When Zeebe is processing at high throughput, external systems such as Elasticsearch might not be able to keep up. Even when external systems are not a bottleneck, we might want to artificially limit processing rate to save resources.

**Describe the solution you'd like**

A (runtime-)configurable limit on processing speed. I don't care that much about what exactly is being limited, it could be processed commands, written records or FNIs.

The limit should probably apply per partition and can be implemented by the `ProcessingStateMachine`.
The `ReplayStateMachine` should not be limited, we always want to replay as fast as possible.

It can be a _soft_ limit, we don't need to guarantee an exact limit.

**Describe alternatives you've considered**
- Tuning backpressure configuration. This is much more complicated and difficult to understand.
- https://github.com/camunda/zeebe/issues/6723

**Additional context**

**Comment by megglos** [comment]
ZDP-Triage:
- we would like to enable it at least for trial clusters
- we should sync with PM on this
- might be useful to enforce cluster size processing limits and enforce a load that the system can actually handle for self-managed

**Comment by megglos** [comment]
we agreed that we rather work on https://github.com/camunda/zeebe/issues/6723

**Comment by korthout** [comment]
This feature was requested again in the incident review of:
- https://docs.google.com/document/d/1o0FGmioKLO-480CDFYvSjCBho7Enj8ZOY08d7UwxpaU/edit

We have [explicit limits](https://docs.google.com/spreadsheets/d/1wbsB8-VuQITxYUx1ms31MD4kbwkgDhgzE4omL3ZbDRg/edit#gid=594635543) for our cluster plans. We can use rate limiting to avoid users to go past these limits. This would also help deal with the straight-through processing loops, and fork bombs.

**Comment by Zelldon** [comment]
@felix-mueller the potential feature request we discussed in the morning, which we could use to rate limit for certain cluster packages.

**Comment by megglos** [comment]
ZDP-Triage:
- will allow us to reduce incidents caused by overuse of a clusterplan
- will allow users to understand if they exceed their quota
- @felix-mueller let's discuss and convert this to a PDP

**Comment by megglos** [comment]
@felix-mueller will create a PDP epic next, @megglos can help to link all relevant issues on that

**Comment by megglos** [comment]
ZDP-Planning
@felix-mueller please link the epic here

**Comment by megglos** [comment]
moving to blocked as we well handle this with the overall epic on the topic https://github.com/camunda/product-hub/issues/1426

**Comment by dddpaul** [comment]
Hi.

I have an issue with Camunda 8 and long running processes. By long running process I mean:
- process has an subprocess
- subprocess has an overall timer boundary event set to 10-30 min duration

For example:

<img width="743" alt="image" src="https://github.com/camunda/issues/assets/628226/5757184f-5674-40ee-89b6-602f6f0b4e9c">

With hundreds of thousands PIs being deployed there are plenty of catch timer events could be fired in small time period. With 1 million PI being deployed it may look like this:

<img width="639" alt="image" src="https://github.com/camunda/issues/assets/628226/c6989712-ae4a-42fa-adb4-6a28939f6847">

And it's make me frustrated. I've just want to cancel execution. Instead stream processors are flooded by internal generated events and my brokers are killed by OOM.

The batch processing could help me with this, but to be combined in batch - commands should be generated from one PI, not from multiple ones.

The backpressure mechanism also could be useful - but it limits only commands from client, not internal ones.

I have some hope for a special type of compensation event https://github.com/camunda/issues/issues/56 which could be presented with 8.4. So I've ask a similar question there.

By now I have only two hopes - these two issues:
1. https://github.com/camunda/issues/issues/56 or #5134 
2. #12560.

I do not have and access to blocking https://github.com/camunda/product-hub/issues/1426, so I have no ideas when a rate limiter will be implemented or even will it helps to solve my problem. 

Could you please give me some clarifications here?

PS: I've tested on 8.3.0-alpha6.

**Comment by megglos** [comment]
ZDP-Planning:
- no capacity this iteration, to be reassessed next time

**Comment by korthout** [comment]
Our max throughput rates (max tasks/s and process instances/s, etc) are well documented for our cluster plans: https://docs.google.com/document/d/1u2L3uPUgUO9zBN34tuwh2MRMzKLLp1YLgm2er7koiG0/edit#heading=h.evh0qrmn9dbj

**Comment by oleschoenburg** [comment]
Closing in favor of #17547
