### ISSUE TITLE
Renovate fails updating docker digest

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#12577]
**Description**

For main, stable/8.1, probably also stable/8.2 renovate seems to have issues updating the digest.

```
DEBUG: Digest is not updated(packageFile="Dockerfile", branch="renovate/stable/8.1-eclipse-temurin-17.x")
{
  "baseBranch": "stable/8.1",
  "manager": "dockerfile",
  "expectedValue": "sha256:22f133769ce2b956d150ab749cd4630b3e7fbac2b37049911aa0973a1283047c",
  "foundValue": "sha256:b10df4660e02cf944260b13182e4815fc3e577ba510de7f4abccc797e93d9106"
}
WARN: Error updating branch: update failure(branch="renovate/stable/8.1-eclipse-temurin-17.x")
{
  "baseBranch": "stable/8.1"
}
```

See further logs at https://app.renovatebot.com/dashboard#github/camunda/zeebe/

**Comment by megglos** [comment]
turns out the recent introduction of JVM and JAVA_VERSION broke the updates
```
          {
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "depType": "stage",
            "replaceString": "${JVM}:${JAVA_VERSION}-jre-focal@sha256:54f64f1cf8e9b984a92d06d3ad5c10fbbb9e9869144f1f45decdf530d64a4163",
            "skipReason": "invalid-name",
            "updates": []
          },
```

**Comment by koevskinikola** [comment]
ZPA triage:
- @megglos it looks like ZDP is already working on this issue. Is there any reason why the issue is on the ZPA board as well?
- ZPA will remove it from the team board. If there is anything we need to do, please re-add it to the ZPA board.

**Comment by megglos** [comment]
changes are applied, I'm monitoring it till the next updates are applied to all branches

**Comment by Zelldon** [comment]
@megglos wondering why this is open but in the done column @megglos ? 🤔

**Comment by megglos** [comment]
thanks for raising, I somehow assumed it gets closed when moving it to done 🤔
