### ISSUE TITLE
Improve the traversing of snapshot files

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#12575]
**Is your feature request related to a problem? Please describe.**

I think that it is not a good idea to collect snapshot files in the list. 
Check it here: https://github.com/camunda/zeebe/blob/02d1df8ac1b6f5484f1e9d4c1f19c8a5712176b1/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/SnapshotChecksum.java#L41. 
Because, after a while, the amount of snapshot files should grow. So, we could instead call the `.forEachOrdered` method to calculate the snapshot. I will provide the PR soon to see this in action and benchmark this.

**Describe the solution you'd like**
We should call `Stream.forEachOrdered` instead of collecting snapshots `File`s in the list.

**Describe alternatives you've considered**
We could use `Stream.forEach` but as I can understand the order is important, so we shouldn't do this.

**Comment by aivinog1** [comment]
@Zelldon Hello 👋 
I think that this could be addressed to the ZDP Team (sorry if I am wrong 😅)
Could we assign this to someone, please? In our load test environment, we see a little degradation in creating snapshots and we are suspecting this part of the code.
Thank you in advance 🙂

**Comment by Zelldon** [comment]
Looks like @deepthidevaki will look into your PR, thanks for providing it :)
