### ISSUE TITLE
Make dashboard UIDs human-readable

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#12601]
**Description**

Came up in https://github.com/camunda-cloud/alerts/pull/91, raised by @multani 

Right now our UIDs are not human readibly see https://github.com/camunda/zeebe/blob/11c54b23ab2d567c6933cf7925327481562d0b32/monitor/grafana/zeebe.json#L14934 which means it is hard to reference them and understand what the request dashboard is about.

Benefit references like this https://github.com/camunda-cloud/alerts/blob/e2245885e6010d08de2924d0da4750be9d33bb32/generated/camunda-cloud-240911/development-worker-1/monitoring.coreos.com_v1_prometheusrule_zeebe-crashlooping.yaml#L17 would be more clear

Changing the UID would improve this, I think this would be a simple and straight forward change. Similar to https://github.com/camunda-cloud/grafana-dashboards/issues/21

**Comment by npepinpe** [comment]
Let's do it sooner than later before more things reference the old UIDs and it becomes more of a pain to change them.

Please remember to update the references (e.g. Cloud Bot, alerts - check with SREs).

**Comment by koevskinikola** [comment]
ZPA triage:
@Zelldon is something expected from ZPA on this issue?
