### ISSUE TITLE
Subprocess without end event deploy should throw error

### ISSUE THREAD

**Issue by hmeniz** [camunda/zeebe#12620]
**Is your feature request related to a problem? Please describe.**
I think every process should end with at least one end bpmn notation. But for now, subprocess which has not an end notation doesn't throw an error.

**Describe the solution you'd like**
If subprocess does not have an end notation then it should throw an error when deploying process.

**Describe alternatives you've considered**

**Additional context**
![SubprocessWithoutEndNotation](https://user-images.githubusercontent.com/27866285/235616134-941b82cb-10ed-4867-97ab-2a4e99b7a8af.png)

**Comment by lzgabel** [comment]
HI @hmeniz. Thank you for raising this up!

As we can see the following information from pages 430-431 in the [specification](https://www.omg.org/spec/BPMN/2.0.2/PDF), the **Sub-Process** is limited to only unique empty **Start Events**, and there is no limit to **End Events**. 

<img width="753" alt="image" src="https://user-images.githubusercontent.com/24605947/235620389-939dce83-658b-40d3-ae51-557939fefec0.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/24605947/235620463-5effdbc1-0b52-4d83-9b48-66d35db975d9.png">


At the same time:
> A Sub-Process instance completes when there are no more tokens in the Sub-Process and none of its Activities is still active. 

So we don't need **End Events**.

**Comment by Zelldon** [comment]
Closing this since it works as expected. 

Thanks @lzgabel for answering. It is correct that if no end event is modeled it works like an implicit end event, when reaching an activity without outgoing sequence flows.
