### ISSUE TITLE
Automatically add `support` label to support related issues

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#12655]
**Is your feature request related to a problem? Please describe.**
After a release we must send a list of fixed issues related to support tickets. For this we look at the `support` label on issues. It's easy to forget to add this label.

**Describe the solution you'd like**
Introduce a GitHub action that checks new issues and comments in issues if the text contains `SUPPORT-XXXX`. If it find any the action should add the `support` label.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by remcowesterhoud** [comment]
@abbasadel fyi 🙂

**Comment by megglos** [comment]
ZDP-Triage:
- would be great to be done for all C8 teams actually
- @megglos will take this over as part of the support/engineering collaboration
