### ISSUE TITLE
Do not write the entire command for rejection

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#12699]
In https://github.com/camunda/zeebe/issues/12591, we found that when engine rejects the deployment request it cannot write the rejection record because it was attempting to write the whole deployment which is greater than maxMessageSize. This resulted in a loop in StreamProcessor, where it repeatedly fails to write the rejection record leading to the partition being fully blocked and not making any progress. https://github.com/camunda/zeebe/issues/12591#issuecomment-1535879364 

To fix this, now we reject the request in CommandAPI before writing to the logstream https://github.com/camunda/zeebe/pull/12676. But, to be safer we should also ensure that we are not writing rejection records that are too large, to prevent such accidental cases.

Ensure that rejections records can be written reliably, even if the original command is rejected due to ExceededBatchSize. Ideally, rejection record should only have a reference to the original command, but not the full command. If possible, do not write the entire command for any type of rejections. Or atleast, trim rejection record in case of ExceededBatchSize exception.

**Comment by berkaycanbc** [comment]
ZPA Triage:

We think this is a bug. We are planning to process this in the next mob-programming session.

**Comment by korthout** [comment]
Mob programming results:
- Run `io.camunda.zeebe.it.client.command.CreateDeploymentTest::shouldRejectDeployIfResourceIsTooLarge`
- Notice that an error is logged, this should not be the case
- Make sure that [rejection is written safely](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/Engine.java#L186-L194)

**Comment by abbasadel** [comment]
ZPA planning: 
- Moving back to the backlog since we don't have time for it in the next iteration.
