### ISSUE TITLE
DirectByteBuffers size when writing logs to a file

### ISSUE THREAD

**Issue by happwrap** [camunda/zeebe#12800]
We are testing a zeebe cluster on virtual machines.
After 3-5 days of the broker's work with MaxRAMPercentage=85.0 OOM was killing the zeebe process. Used memory gradually grew from 8G to the maximum on the host 12G.
With Xmx=4G and logging enabled, the memory used by the host is 8-9G. If logging to a file is disabled, the memory used by the host does not exceed 5G.

Found that writing logs to a file consumes ~3.5G direct memory:
![image](https://github.com/camunda/zeebe/assets/98555436/2d4ed034-4353-4724-8718-0eb7d6827757)
![image](https://github.com/camunda/zeebe/assets/98555436/d71d45d3-787f-4683-b37e-44ea146dc2c8)
![image](https://github.com/camunda/zeebe/assets/98555436/99896a32-7f01-4c05-9557-54dacfe2e61f)

**Cluster configuration:**
Cluster size: 6 (8 cpu 12G RAM)
Partitions count: 35
Replication factor: 4
Version: 8.0.5
Log level: info

So, is this behavior normal? I would be grateful for advice on how to reduce memory usage for logging to a file

**Comment by megglos** [comment]
Hey @happwrap ,

this is actually the log buffer for the zeebe partition log, not to be confused with actual logging.

You can estimate the max peak usage of direct memory for the memory mapped files roughly by this formula:
`3 * number of partitions per broker * [logSegmentSize (default 128MB)](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/broker-config/#zeebebrokerdata) + (for Zeebe <8.2 only, afterwards the dispatcher was removed) dispatcher direct memory: 75MB * number of partitions per broker`

in your case this actually could lead up to about 10GB alone assuming all partitions under full load and each broker holding about 23 partitions.

May I ask about why you decided to go for such a high number of partitions?

**Comment by korthout** [comment]
It looks like this question is answered, so I'm closing it. Please re-open it if needed.
