### ISSUE TITLE
Release: Integrate update of identity version into the release process

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#12836]
**Description**

Since the merge of https://github.com/camunda/zeebe/pull/12001 zeebe depends on identity for all 8.2.0 release and later.
As an identity release may happen right before the zeebe release we need to add a step to the release process to make sure the identity version is the same as the zeebe version or if not update it.

Right now patch level version of zeebe and identity are aligned, so if zeebe 8.2.5 is released the identity version should be 8.2.5 as well. This could be automated.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/12920
- [ ] https://github.com/zeebe-io/zeebe-engineering-processes/issues/312
```

**Comment by megglos** [comment]
Release process now covers checking for an existing release and or awaiting the needed release based on a Github webhook. 
![image](https://github.com/camunda/zeebe/assets/209518/69f40751-3da0-4b51-8ef9-44e6b143a8b3)

to be tested the next days, together with @oleschoenburg

**Comment by abbasadel** [comment]
ZPA Planning: 
- @megglos is there anything still needed form ZPA to close this?

**Comment by remcowesterhoud** [comment]
@megglos I see all tasks here are closed. Can this issue be closed as well?

**Comment by megglos** [comment]
Two releases went fine with this change, closing.
