### ISSUE TITLE
Catch all error events by using empty 'errorCode' does not work

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/zeebe#12837]
**Describe the bug**
Using an error catch event (boundary or start event in Subprocess) with an empty `errorCode` results in incident with `errorType=UNHANDLED_ERROR_EVENT`. 
Also only error events with a non-empty errorCode will be reported like this: `Available error events are [boundary]`.

**To Reproduce**

1. Create a BPMN process with error catch event as boundary event or as start event in subprocess.
2. Deploy, start the process. In a job client throw an error command with an unhandled errorCode.
3. Zeebe creates an incident instead of catching the error 

Here an example process [errorProcessCatchAll.bpmn.txt](https://github.com/camunda/zeebe/files/11544062/errorProcessCatchAll.bpmn.txt)

[Slack thread](https://camunda.slack.com/archives/CSQ2E3BT4/p1684841521468159)

**Expected behavior**

The error is caught and no incident is created.

**Log/Stacktrace**

Example error message from Zeebe:
```
errorType=UNHANDLED_ERROR_EVENT, errorMessage='Expected to throw an error event with the code 'unknown' with message 'Process error', but it was not caught. Available error events are [boundary]
```

**Environment:**
- OS: MacOS
- Zeebe Version: `8.2.0-alpha3` and later
- Configuration: ElasticsearchExporter

**Comment by lzgabel** [comment]
Hi @korthout. I think I found the problem, please assign me this task, I will submit a PR to fix this problem soon. Thanks :heart:

**Comment by lzgabel** [comment]
BTW. As a workaround, user can catch all error events by removing the `errorEventDefinition`.
