### ISSUE TITLE
Cannot resolve output mapping incident on a none end event

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#12833]
**Describe the bug**

There was an incident in one of the chaos test models, where a none end event had an output mapping referencing a non-existent variable `source` to be mapped to `target`. I resolved the incident by adding a dummy variable (the mapping should not have been there anyway), but then the process was stuck on the none end event.

See https://bru-2.operate.camunda.io/eeef5734-cfd6-47a5-a2ed-5fe13269e589/processes/2251799815205221

**To Reproduce**

Add the following test case to `io.camunda.zeebe.engine.processing.incidentOutputMappingIncidentTest`:

```java
          {
            "None end event",
            ENGINE
                .deployment()
                .withXmlResource(
                    Bpmn.createExecutableProcess(PROCESS_ID)
                        .startEvent()
                        .endEvent("endEventId", b -> b.zeebeOutputExpression("foo", "bar"))
                        .done()),
            "endEventId",
            false
          },
```

**Expected behavior**

I can resolve incidents on a none end event.

**Environment:**
- Zeebe Version: 8.2.3
- Configuration: SaaS - G3 S

**Comment by korthout** [comment]
As a workaround, users can use [Process Instance Modification](https://docs.camunda.io/docs/next/components/concepts/process-instance-modification/) to re-activate the end event

**Comment by korthout** [comment]
ZPA triage:
- should be simple to resolve `good-first-issue` (just implement the `onComplete` method on `NoneEndEventBehavior` in the `EndEventProcessor`)
- since it's low-hanging fruit and may effect users we would like to tackle it sooner than later.
