### ISSUE TITLE
Add message definition extension elements

### ISSUE THREAD

**Issue by lzgabel** [camunda/zeebe#12878]
**Is your feature request related to a problem? Please describe.**
In the BPMN model API, a `send task` or `message throw event` should be able to reference a message definition.

* a `send task` or `message throw event` can have an extension element `messageDefinition` with
  * an attribute `messageName` that references the name of the message
    * has either a static value or an expression
    * must not be empty
  * an attribute `correlationKey` that references the correlation key of the message
    * has either a static value or an expression
    * must not be empty
  * an attribute `messageId` that references the id of the message
    * has either a static value or an expression
  * an attribute `timeToLive` that references the time to live of the message
    * has either a static value or an expression
*  a `send task` or `message throw event` must have either an extension element `messageDefinition` or `taskDefinition` but not both

Sample XML with static attributes:

```
<bpmn:sendTask id="send_message">
  <bpmn:extensionElements>
    <zeebe:messageDefinition 
        messageName="foo" 
        correlationKey="abc" 
        messageId="abc" 
        timeToLive="PT10S"/>
  </bpmn:extensionElements>  
</bpmn:sendTask> 


<bpmn:intermediateThrowEvent id="Event_1nqoocy">
  <bpmn:extensionElements>
    <zeebe:messageDefinition 
        messageName="foo" 
        correlationKey="abc" 
        messageId="abc" 
        timeToLive="PT10S"/>
  </bpmn:extensionElements>
  <bpmn:messageEventDefinition id="MessageEventDefinition_1wizp0b" />
</bpmn:intermediateThrowEvent>
```

Sample XML with expression attributes:

```
<bpmn:sendTask id="send_message">
  <bpmn:extensionElements>
    <zeebe:messageDefinition 
        messageName="=messageName" 
        correlationKey="=correlationKey" 
        messageId="=messageId" 
        timeToLive="=timeToLive"/>
  </bpmn:extensionElements>  
</bpmn:sendTask> 

<bpmn:intermediateThrowEvent id="Event_1nqoocy">
  <bpmn:extensionElements>
    <zeebe:messageDefinition 
        messageName="=messageName" 
        correlationKey="=correlationKey" 
        messageId="=messageId" 
        timeToLive="=timeToLive"/>
  </bpmn:extensionElements>
  <bpmn:messageEventDefinition id="MessageEventDefinition_1wizp0b" />
</bpmn:intermediateThrowEvent>
```

**Comment by korthout** [comment]
Hi @lzgabel 👋 Sorry for the delay. I wanted to look at your [pull request](https://github.com/camunda/zeebe/pull/12879), but I want to understand the big picture before reviewing it.

As I understand, this issue is one of several parts of:
- #1021?

In order to allow a user to model a process where a Send Task (or Messsage Throw Event) sends a message, we need to bind it to some Message Definition. Which is what this issue is about.

In your suggestion, the binding is achieved through a new `messageDefinition` extension element in the zeebe namespace, informing the message name, correlation key, message id and time-to-live of the message that should be published.

❓ How did you come to this design? Was there a specific reason why you chose this over any other?

For example, there already exists a `MessageEventDefinition` in the BPMN spec that we could attempt to re-use for this. Here is an example of pure BPMN.

```xml
<bpmn:definitions ...>
  <bpmn:process id="Process_02p7q4p" isExecutable="true">
    ...
    <bpmn:intermediateThrowEvent id="Event_145tbfx">
      <bpmn:messageEventDefinition id="MessageEventDefinition_0inu3y4" messageRef="Message_1nb8aa6" />
    </bpmn:intermediateThrowEvent>
    ...
  </bpmn:process>
  <bpmn:message id="Message_1nb8aa6" name="order_placed" />
  ...
</bpmn:definitions>
```

**Comment by lzgabel** [comment]
Hi @korthout. Thanks for you reply. 
> How did you come to this design? Was there a specific reason why you chose this over any other?

Actually, what I first thought was that this behavior is considered to be an internal implementation of the Zeebe engine, and should be create a new `messageDefinition` extension element in the zeebe namespace. 😄 

> there already exists a MessageEventDefinition in the BPMN spec that we could attempt to re-use for this. Here is an example of pure BPMN.

Yes. You are absolutely right. 👍  I've checked the specification document of bpmn again, I will take your suggestion to re-use `MessageEventDefinition`.  :

--- 
At the same time, I think we can also support the `message end event`. 🚀

**Comment by korthout** [comment]
> I plan to add an extension element under message

@lzgabel Thanks for checking with me. I don't know what is best. 

An argument for putting this under the message is that this allows several tasks/events to publish the same message with the same details (correlation key, TTL, message id).

But the counter-argument is that this does not allow changing any of these for tasks/events that want to publish the same message but with different details.

I'll check with our Modeling experts to see what fits best. I'll attempt to make a decision on this early next week. Is that okay for you, @lzgabel?

**Comment by nikku** [comment]
@korthout to mirror my internal comment here:

* I'd love to keep what is relevant in the _execution flow_ on the flow element (intermediate catch event in this case)

**Comment by barmac** [comment]
Hi, I'd like to add my two cents. First, it's great that you are looking into this feature, and I appreciate it a lot that you pulled in Modeler devs :)

Let's examine how we solve modeling problems with each of the solutions:

| Problem | Properties defined on shared `bpmn:Message` | Properties defined on individual events via `bpmn:MessageEventDefinition`|
|-|-|-|
| I want to add another event which publishes message of given name with the same correlation key, TTL etc. | Create a new event and select shared message | Copy existing event |
| I want to modify properties for a specific event | Create a new message with the same name but different propertie | Modify properties on the event |
| I want to modify properties on all events | Modify in single place | Modify on each event |
| I want to create an event with a different variable as correlation key | Create a new message with the same name | Change on individual event |

Setting different properties for the same message name leads to redundancy in the diagram (multiple messages of the same name but different extension elements). I believe this is not what we want, therefore I'd support setting event-related properties on the event definition.

Note that all of that can be also applied to catch event. 

---

I started writing this before Nico's comment but we discussed this in the morning and have 100% agreement :)

**Comment by barmac** [comment]
Question: What would `messageId` be used for?

**Comment by nikku** [comment]
@barmac and as we discussed, based on https://github.com/camunda/zeebe/issues/12878#issuecomment-1578613868, imagine this (attaching subscription information to the message definition, not the `bpmn:Message` as it is currently the case:

```xml
<bpmn:intermediateCatchEvent id="Message_1nb8aa6" name="order_processed">
  <bpmn:messageEventDefinition>
    <bpmn:extensionElements>
      <zeebe:subscribe correlationKey="= orderId" />
    </bpmn:extensionElements>
  </bpmn:messageEventDefinition>
</bpmn:message>
```

**Comment by lzgabel** [comment]
👋 Hi Guys. Will this [#12878 (comment)](https://github.com/camunda/zeebe/issues/12878#issuecomment-1578613868) be the final conclusion?

**Comment by korthout** [comment]
Hi @lzgabel I've asked our internal Modeling experts. @nikku and @barmac gave great input, and we'll likely take that route. However, I don't want to take the opportunity away for others to voice their opinions. I set Monday, June 12th, as the deadline for input, so let's await that. I'll update this issue on Tuesday with the outcome.

**Comment by jonathanlukas** [comment]
I would also prefer the approach @nikku proposes. While a message correlation surely is related to the message itself, the implementation details are more part of the event definition of each bpmn element.

Also, I think in Camunda 7, the message throw event was able to select a message element to refer to which still leads to confusion...

**Comment by korthout** [comment]
Thanks everyone for your input 👏 

No opinions against the proposal were raised. Let's move forward with the following:

- a new extension element that can be added to the `bpmn:messageEventDefinition` (of Intermediate Throw Event, or End Event) and/or to the `bpmn:sendTask` to specify the details of the message to publish (i.e. correlation key, time to live, message id)
- let's name this extension element `zeebe:publishMessage` to make the XML easier to understand/read for humans
- the message to publish can be referenced directly from the `bpmn:messageEventDefinition` and from the `bpmn:sendTask` according to BPMN spec using the `messageRef` attribute (the referenced message contains the message name).

Here follows an example with three different elements all publishing the same message with different message details (i.e. correlation key, time to live, message id).

```xml
<bpmn:definitions ...>
  <bpmn:process id="Process_02p7q4p" isExecutable="true">
    ...
    <bpmn:intermediateThrowEvent id="Event_145tbfx">
      <bpmn:messageEventDefinition id="MessageEventDefinition_0inu3y4" messageRef="Message_1nb8aa6">
        <bpmn:extensionElements>
          <zeebe:publishMessage correlationKey="= orderId" timeTolive="PT10S" messageId="= orderId" />
        </bpmn:extensionElements>
      </bpmn:messageEventDefinition>
    </bpmn:intermediateThrowEvent>
    ...
    <bpmn:sendTask id="Activity_1kgyl85" messageRef="Message_1nb8aa6">
      <bpmn:extensionElements>
        <zeebe:publishMessage correlationKey="= some_other_order_id" />
      </bpmn:extensionElements>
    </bpmn:sendTask>
    ...
    <bpmn:endEvent id="Message_1nb8aa6" name="order_placed">
      <bpmn:messageEventDefinition messageRef="Message_1nb8aa6">
        <bpmn:extensionElements>
          <zeebe:publishMessage correlationKey="= orderId" timeTolive="PT1H" />
        </bpmn:extensionElements>
      </bpmn:messageEventDefinition>
    </bpmn:endEvent>
    ...
  </bpmn:process>
  <bpmn:message id="Message_1nb8aa6" name="order_placed" />
  ...
</bpmn:definitions>
```

**Comment by lzgabel** [comment]
@korthout. Thanks. ❤️ 
I'll be pushing the latest commit for this feature in the next few days.
