### ISSUE TITLE
ActivatableJobsPushTest#shouldPushWhenJobCreated is flaky

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#12872]
**Summary**

- How often does the test fail? once
- Does it block your work? no
- Do we suspect that it is a real failure? Likely not

https://github.com/camunda/zeebe/actions/runs/5090792281

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
ava.lang.AssertionError: 

Expected size: 1 but was: 0 in:
[]
	at io.camunda.zeebe.engine.processing.job.ActivatableJobsPushTest.assertActivatedJob(ActivatableJobsPushTest.java:231)
	at io.camunda.zeebe.engine.processing.job.ActivatableJobsPushTest.shouldPushWhenJobCreated(ActivatableJobsPushTest.java:112)
</pre>
</details>

**Logs**

<details><summary>Logs</summary>
<pre>
12:32:27.476 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 1 from snapshot
12:32:27.477 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
12:32:27.477 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@10206b5c)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@1ee78728, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@1ad8002c, configuration: Configuration(false)]
12:32:27.485 [Broker-0-StreamProcessor-1] INFO  org.camunda.dmn.DmnEngine - DMN-Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@68286012)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@738af4b2, audit-loggers: List(), configuration: Configuration(false,false,false)]
12:32:27.485 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.dmn.NoUnpackValueMapper@7dc8cf86)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@738af4b2, clock: SystemClock, configuration: Configuration(false)]
12:32:27.487 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@2fc85937)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@3bbba900, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@10387695, configuration: Configuration(false)]
12:32:27.488 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@2bb72feb)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@46dbda4b, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@20ce9839, configuration: Configuration(false)]
12:32:27.489 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@7311ce6b)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@61cb7f95, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@79daf865, configuration: Configuration(false)]
12:32:27.491 [Broker-0-StreamProcessor-1] INFO  org.camunda.dmn.DmnEngine - DMN-Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@46b3ff04)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@738af4b2, audit-loggers: List(), configuration: Configuration(false,false,false)]
12:32:27.491 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.dmn.NoUnpackValueMapper@31ce8692)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@738af4b2, clock: SystemClock, configuration: Configuration(false)]
12:32:27.493 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.processor - Processor starts replay of events. [snapshot-position: -1, replay-mode: PROCESSING]
12:32:27.493 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.processor - Processor finished replay, with [lastProcessedPosition: -1, lastWrittenPosition: -1]
12:32:27.494 [Broker-0-LogStream-1] DEBUG io.camunda.zeebe.logstreams.impl.flowcontrol.AppenderFlowControl - Configured log appender back pressure as BackpressureCfgVegas{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
12:32:27.495 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Starting processing of migration tasks (use LogLevel.DEBUG for more details) ... 
12:32:27.495 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.engine.state.migration - Found 5 migration tasks: ProcessMessageSubscriptionSentTimeMigration, MessageSubscriptionSentTimeMigration, TemporaryVariableMigration, DecisionMigration, DecisionRequirementsMigration
12:32:27.495 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping ProcessMessageSubscriptionSentTimeMigration migration (1/5).  It was determined it does not need to run right now.
12:32:27.498 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping MessageSubscriptionSentTimeMigration migration (2/5).  It was determined it does not need to run right now.
12:32:27.500 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping TemporaryVariableMigration migration (3/5).  It was determined it does not need to run right now.
12:32:27.502 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping DecisionMigration migration (4/5).  It was determined it does not need to run right now.
12:32:27.505 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping DecisionRequirementsMigration migration (5/5).  It was determined it does not need to run right now.
12:32:27.510 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Completed processing of migration tasks (use LogLevel.DEBUG for more details) ... 
12:32:27.512 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.engine.state.migration - Executed 0 migration tasks: 
12:32:29.253 [] DEBUG io.camunda.zeebe.broker.logstreams - Close stream processor
12:32:29.253 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
12:32:29.305 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-1
12:32:29.305 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams.impl.log.Sequencer - Closing sequencer for writing
12:32:29.305 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-1 close 2 readers
12:32:29.307 [] DEBUG io.camunda.zeebe.broker.test - Clean up test files on path /tmp/junit7246822620239420202
12:32:29.308 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
12:32:29.309 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
12:32:29.310 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
12:32:29.310 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
</pre>
</details>

**Comment by koevskinikola** [comment]
The flakiness is due to a timing issue:
1. A job is created, and an event with `JobIntent.CREATED` is appended to the log.
2. Next, before the job can be pushed, the job is activated by appending a `JobBatchIntent.ACTIVATED` to the log.
3. Finally, we push out the job as a side-effect.

The flakiness happens on job creation when the `JobBatchIntent.ACTIVATED` event has already been appended to the log, but the side-effect that pushes the job hasn't been invoked yet.

The `ActivatableJobsPushTest` class was updated with #12933 and I haven't been able to reproduce the flakiness since then.

Proposals:
* I would propose to wait and see if the issue pops up again.
* In case the flakiness is still there, we can introduce a `Thread.sleep(GRACE_PERIOD);` to give the side-effect a chance to get executed.

**Comment by megglos** [comment]
@koevskinikola happened again today on `main` https://github.com/camunda/zeebe/commit/3f321e211928c60430f252729c12261fe9cfccf1

**Comment by koevskinikola** [comment]
@megglos [the PR](https://github.com/camunda/zeebe/pull/12943) that fixes #12933 (and also removes the flakiness here) is still in review. I'll rephrase my comment so that it makes this transparent. Sorry about that :sweat_smile:
