### ISSUE TITLE
Zeebe should only log as JSON, if configured to do so

### ISSUE THREAD

**Issue by multani** [camunda/zeebe#12886]
**Is your feature request related to a problem? Please describe.**

Zeebe offers a [Stackdriver](https://github.com/camunda/zeebe/tree/main/util/src/main/java/io/camunda/zeebe/util/logging/stackdriver) logging format that displays logs as JSON, formatted for Google Cloud Logging.

Not all the logs are formatted according to this format though:

* At startup, Zeebe displays a huge ASCII banner showing  `Zeebe`
* Some logs (Tomcat logs?) are not formatted as JSON:
  ```
  May 30, 2023 6:51:02 AM org.apache.coyote.AbstractProtocol init
  INFO: Initializing ProtocolHandler ["http-nio-0.0.0.0-9600"]
  May 30, 2023 6:51:02 AM org.apache.catalina.core.StandardService startInternal
  INFO: Starting service [Tomcat]
  May 30, 2023 6:51:02 AM org.apache.catalina.core.StandardEngine startInternal
  INFO: Starting Servlet engine: [Apache Tomcat/10.1.7]
  May 30, 2023 6:51:02 AM org.apache.catalina.core.ApplicationContext log
  INFO: Initializing Spring embedded WebApplicationContext
  ```

**Describe the solution you'd like**

Ideally:

* All the logs are properly formatted as JSON, instead of a mix of plain text/JSON.
* The banner can be completely removed.

This would make all the logs uniform, help to classify them correctly, and would prevent spurious parsing of plain-text only logs.

**Describe alternatives you've considered**

None

**Additional context**

A typical startup looks like this:

```
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data/java_started_1685429455.hprof
  ______  ______   ______   ____    ______     ____    _____     ____    _  __  ______   _____  
 |___  / |  ____| |  ____| |  _ \  |  ____|   |  _ \  |  __ \   / __ \  | |/ / |  ____| |  __ \ 
    / /  | |__    | |__    | |_) | | |__      | |_) | | |__) | | |  | | | ' /  | |__    | |__) |
   / /   |  __|   |  __|   |  _ <  |  __|     |  _ <  |  _  /  | |  | | |  <   |  __|   |  _  / 
  / /__  | |____  | |____  | |_) | | |____    | |_) | | | \ \  | |__| | | . \  | |____  | | \ \ 
 /_____| |______| |______| |____/  |______|   |____/  |_|  \_\  \____/  |_|\_\ |______| |_|  \_\
                                                                                                
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"logStarting","file":"StartupInfoLogger.java","line":51},"message":"Starting StandaloneBroker v8.2.3 using Java 17.0.6 with PID 7 (/usr/local/zeebe/lib/camunda-zeebe-8.2.3.jar started by root in /usr/local/zeebe)","serviceContext":{"service":"zeebe","version":"8.2.3"},"context":{"threadId":1,"threadPriority":5,"loggerName":"io.camunda.zeebe.broker.StandaloneBroker","threadName":"main"},"timestampSeconds":1685429459,"timestampNanos":42397893}
{"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"function":"logStarting","file":"StartupInfoLogger.java","line":52},"message":"Running with Spring Boot v3.0.5, Spring v6.0.8","serviceContext":{"service":"zeebe","version":"8.2.3"},"context":{"threadId":1,"threadPriority":5,"loggerName":"io.camunda.zeebe.broker.StandaloneBroker","threadName":"main"},"timestampSeconds":1685429459,"timestampNanos":128377708}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"logStartupProfileInfo","file":"SpringApplication.java","line":638},"message":"The following 1 profile is active: \"broker\"","serviceContext":{"service":"zeebe","version":"8.2.3"},"context":{"threadId":1,"threadPriority":5,"loggerName":"io.camunda.zeebe.broker.StandaloneBroker","threadName":"main"},"timestampSeconds":1685429459,"timestampNanos":130430841}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"initialize","file":"TomcatWebServer.java","line":108},"message":"Tomcat initialized with port(s): 9600 (http)","serviceContext":{"service":"zeebe","version":"8.2.3"},"context":{"threadId":1,"threadPriority":5,"loggerName":"org.springframework.boot.web.embedded.tomcat.TomcatWebServer","threadName":"main"},"timestampSeconds":1685429462,"timestampNanos":567312120}
May 30, 2023 6:51:02 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-0.0.0.0-9600"]
May 30, 2023 6:51:02 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
May 30, 2023 6:51:02 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/10.1.7]
May 30, 2023 6:51:02 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring embedded WebApplicationContext
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"prepareWebApplicationContext","file":"ServletWebServerApplicationContext.java","line":291},"message":"Root WebApplicationContext: initialization completed in 3603 ms","serviceContext":{"service":"zeebe","version":"8.2.3"},"context":{"threadId":1,"threadPriority":5,"loggerName":"org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext","threadName":"main"},"timestampSeconds":1685429462,"timestampNanos":856072455}
{"severity":"WARNING","logging.googleapis.com/sourceLocation":{"function":"overrideDiskConfig","file":"DataCfg.java","line":69},"message":"Configuration parameter data.diskUsageCommandWatermark is deprecated. Use data.disk.freeSpace.processing instead.","serviceContext":{"service":"zeebe","version":"8.2.3"},"context":{"threadId":1,"threadPriority":5,"loggerName":"io.camunda.zeebe.broker.system","threadName":"main"},"timestampSeconds":1685429463,"timestampNanos":631599523}
{"severity":"WARNING","logging.googleapis.com/sourceLocation":{"function":"overrideDiskConfig","file":"DataCfg.java","line":75},"message":"Configuration parameter data.diskUsageReplicationWatermark is deprecated. Use data.disk.freeSpace.replication instead.","serviceContext":{"service":"zeebe","version":"8.2.3"},"context":{"threadId":1,"threadPriority":5,"loggerName":"io.camunda.zeebe.broker.system","threadName":"main"},"timestampSeconds":1685429463,"timestampNanos":632382123}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"<init>","file":"EndpointLinksResolver.java","line":58},"message":"Exposing 8 endpoint(s) beneath base path '/actuator'","serviceContext":{"service":"zeebe","version":"8.2.3"},"context":{"threadId":1,"threadPriority":5,"loggerName":"org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver","threadName":"main"},"timestampSeconds":1685429465,"timestampNanos":427691130}
May 30, 2023 6:51:05 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-0.0.0.0-9600"]

[...]
```

* The banner should be removed
* Non-JSON logs should be turned to JSON
* Ideally, the `JAVA_TOOL_OPTIONS` should also be turned into JSON (or removed)

**Comment by korthout** [comment]
ZPA triage:
- relevant issue, but not a priority for us (`later`)
- good first issue for newcomers

**Comment by megglos** [comment]
ZDP-Triage:
- spring/tomcat seems to use some different logger setup or sysout
- JAVA_TOOL_OPTIONS output seems to come from the JVM => it cannot be suppressed => would require sout redirect, alternatively we could use other ways to pass these options
- @multani what's the actual impact for the logging infrastructure, I would assume these logs are ignored or not properly categorized?
- assigning later as well

**Comment by multani** [comment]
> * @multani what's the actual impact for the logging infrastructure, I would assume these logs are ignored or not properly categorized?

Impact is not huge: logs are analyzed as plain text without any extra metadata and are not really filterable / analyzable.

For instance: I never saw Tomcat errors in our systems, but it would be difficult to look them up as the log level is not parsed. If they were parsed correctly, errors would clearly stand out.

The banner is only displays as garbage into the logs and should be simply removed.

**Comment by npepinpe** [comment]
re Tomcat, tbh I've been thinking we should switch to WebFlux, but there wasn't much pressure for it. but it would remove unnecessary dependencies, since webflux is built on top of netty and we already bundle netty for our own usage (and would not do this weird logging to STDERR as well).

**Comment by npepinpe** [comment]
My proposal:

- [ ] Since we can't suppress `JAVA_TOOL_OPTIONS`, use `JAVA_OPTS` to pass options instead of `JAVA_TOOL_OPTIONS`. This would require some changes on the Helm chart and the controller though.
- [ ] Switch from Tomcat to WebFlux or Undertow (preference to WebFlux). WebFlux is Spring's reactive web server based on Netty, and as our whole system is based on Netty anyway, might as well go for that.
- [ ] The huge banner can be disabled via `SPRING_MAIN_BANNER-MODE=off` - again this is a change in the Helm chart/controller.

So from the Zeebe side, it would be just the second part. The others would be done in the controller.

**Comment by multani** [comment]
If you can't remove the `Picked up JAVA_TOOL_OPTIONS` line, would it be possible to output that line to stdout instead of stderr?

**Comment by multani** [comment]
> We have no control over that, that's the JVM directly writing this =/

Ah yes, you are right, I forgot about that :facepalm:

**Comment by npepinpe** [comment]
Done via https://github.com/camunda-cloud/camunda-operator/pull/1753

The Helm charts were not updated, so they will still print non JSON logs, but that can be fixed by essentially doing the same we did in https://github.com/camunda-cloud/camunda-operator/pull/1753.
