### ISSUE TITLE
Failing jobs with job push enabled breaks the job lifecycle

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#12933]
**Describe the bug**

With job push enabled, when a job is failed with remaining retries and no backoff, the job is first activated and then immediately marked as failed again. This results in pushing out jobs that are in failed state and presumably some data inconsistencies because the job lifecycle is not followed. 

**To Reproduce**

Run `ActivatableJobsPushTest#shouldPushAfterJobFailed` and inspect the log.

**Expected behavior**

When a job is failed with remaining retries and no backoff, the job should first transition to failed before being activated again.

**Log/Stacktrace**

<details><summary>Compact log representation</summary>
 <p>

```
C DPLY      CREATE            - #01-> -1  -1 - 
E PROC      CREATED           - #02->#01 K01 - process.bpmn -> "process" (version:1)
E DPLY      CREATED           - #03->#01 K02 - process.bpmn
E DPLY      FULLY_DISTRIBUTED - #04->#01 K02 - 
C CREA      CREATE            - #05-> -1  -1 - new <process "process"> (default start)  with variables: {a=valA, b=valB, c=valC}
E VAR       CREATED           - #06->#05 K04 - b->"valB" in <process [K03]>
E VAR       CREATED           - #07->#05 K05 - a->"valA" in <process [K03]>
E VAR       CREATED           - #08->#05 K06 - c->"valC" in <process [K03]>
C PI        ACTIVATE          - #09->#05 K03 - PROCESS "process" in <process "process"[K03]>
E CREA      CREATED           - #10->#05 K07 - new <process "process"> (default start)  with variables: {a=valA, b=valB, c=valC}
E PI        ACTIVATING        - #11->#05 K03 - PROCESS "process" in <process "process"[K03]>
E PI        ACTIVATED         - #12->#05 K03 - PROCESS "process" in <process "process"[K03]>
C PI        ACTIVATE          - #13->#05  -1 - START_EVENT "start" in <process "process"[K03]>
E PI        ACTIVATING        - #14->#05 K08 - START_EVENT "start" in <process "process"[K03]>
E PI        ACTIVATED         - #15->#05 K08 - START_EVENT "start" in <process "process"[K03]>
C PI        COMPLETE          - #16->#05 K08 - START_EVENT "start" in <process "process"[K03]>
E PI        COMPLETING        - #17->#05 K08 - START_EVENT "start" in <process "process"[K03]>
E PI        COMPLETED         - #18->#05 K08 - START_EVENT "start" in <process "process"[K03]>
E PI        SEQ_FLOW_TAKEN    - #19->#05 K09 - SEQUENCE_FLOW "sequenc..7fb902a" in <process "process"[K03]>
C PI        ACTIVATE          - #20->#05 K10 - SERVICE_TASK "task" in <process "process"[K03]>
E PI        ACTIVATING        - #21->#05 K10 - SERVICE_TASK "task" in <process "process"[K03]>
E JOB       CREATED           - #22->#05 K11 - K11 "id-ae6f81e8-dfdb-436e-a86a-d681b855a326" @"task"[K10] 3 retries, in <process "process"[K03]> (no vars)
E JOB_BATCH ACTIVATED         - #23->#05 K12 - "id-ae6f81e8-dfdb-436e-a86a-d681b855a326" 1/-1
                K11 "id-ae6f81e8-dfdb-436e-a86a-d681b855a326" @"task"[K10] 3 retries, in <process "process"[K03]> (no vars)
E PI        ACTIVATED         - #24->#05 K10 - SERVICE_TASK "task" in <process "process"[K03]>
C JOB       FAIL              - #25-> -1 K11 - K11 5 retries, in <process ?[?]> (no vars)
E JOB_BATCH ACTIVATED         - #26->#25 K13 - "id-ae6f81e8-dfdb-436e-a86a-d681b855a326" 1/-1
                K11 "id-ae6f81e8-dfdb-436e-a86a-d681b855a326" @"task"[K10] 5 retries, in <process "process"[K03]> (no vars)
E JOB       FAILED            - #27->#25 K11 - K11 "id-ae6f81e8-dfdb-436e-a86a-d681b855a326" @"task"[K10] 5 retries, in <process "process"[K03]> (no vars)
```

</p>
</details>

This is currently a (soft) blocker for https://github.com/camunda/zeebe/issues/12797

**Comment by oleschoenburg** [comment]
I think the issue is related to the _very confusing_ interplay between the `JobFailProcessor` (a `CommandProcessor`), the `CommandControl` and the `BpmnJobActivationBehavior`.
The code _seemingly_ does the right thing, first transitioning to `FAILED` and then handing over to `jobActivationBehavior` which should transition to `ACTIVATED`:
https://github.com/camunda/zeebe/blob/5bd2e1f830d8de2efb6869dc0a29d47896b51800/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobFailProcessor.java#L137-L143

If I understand correctly, the mistakes is that the commandControl does not immediately write the follow-up event but only later when the `ACTIVATED` event is already written.

**Comment by npepinpe** [comment]
Do we really need to mark the job as failed? Could we skip it entirely?

At any rate, if we have to, the log would ideally look like: ACTIVATED -> FAIL -> FAILED -> ACTIVATED. While the push has to happen as a side effect, the new ACTIVATED record should be the last one written in terms of state changes.

**Comment by koevskinikola** [comment]
This bug will also be present when pushing jobs on timeout and recur, as the corresponding processors implement the `CommandProcessor` interface as well.

The quick fix would be to move the job push to the `CommandProcessor#afterAccept` method.

The nicer fix, which would make these Processors more readable, would be to refactor them to use the `TypedRecordProcessor` interface, where it's more clear when the events are written

**Comment by npepinpe** [comment]
:+1: for the second one

**Comment by koevskinikola** [comment]
@npepinpe sorry for not replying to:
> Do we really need to mark the job as failed? Could we skip it entirely?

I think it would be good to have the following sequence of job events on the log: ACTIVATED -> FAIL -> FAILED -> ACTIVATED.

It's clearer to users that the `FAIL` command resulted in a `FAILED` event, and the job was then `ACTIVATED`.

Having ACTIVATED -> FAIL -> ACTIVATED is a bit confusing.
