### ISSUE TITLE
The zeebe task is activated but not executed, and the intent shows TIMED_OUT

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#12967]
The zeebe task is activated but the prompt task is not completed. The intent is timed_out, the JobHandler logic is not executed, and no abnormal information is displayed. What is the reason? The version of Zeebe used is 1.3.4

**Comment by korthout** [comment]
Hi @bugbugmaker. Zeebe version 1.3.4 is [no longer supported](https://github.com/camunda/zeebe#release-lifecycle). I suggest asking this question on our [forums](https://forum.camunda.io/), where our community may be able to help you troubleshoot your problem.

**Comment by bugbugmaker** [comment]
> Hi @bugbugmaker. Zeebe version 1.3.4 is [no longer supported](https://github.com/camunda/zeebe#release-lifecycle). I suggest asking this question on our [forums](https://forum.camunda.io/), where our community may be able to help you troubleshoot your problem.

Sorry, there's a problem now. I need your help

**Comment by bugbugmaker** [comment]
> Hi @bugbugmaker. Zeebe version 1.3.4 is [no longer supported](https://github.com/camunda/zeebe#release-lifecycle). I suggest asking this question on our [forums](https://forum.camunda.io/), where our community may be able to help you troubleshoot your problem.

Status is  timed_out  job has been retrying indefinitely. Can you tell me the reason?
