### ISSUE TITLE
Export number of buffered messages as metrics

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#12975]
**Is your feature request related to a problem? Please describe.**
When configuring async message TTL checking, I need to know the health of my system. A key metric here is the number of "buffered" messages. When this number is steadily climbing, I might need to configure the TTL checker differently to ensure that messages expire fast enough and don't accumulate.

**Describe the solution you'd like**
Export more message related metrics. Similar to the banned instance metrics, these should restore on recovery so that the reported counts are accurate even when brokers restart.

**Describe alternatives you've considered**
Not exposing metrics for this directly, instead relying on the exported record stream. This is more complicated and requires a separate application continously running.

**Additional context**

related to https://jira.camunda.com/browse/SUPPORT-17177

**Comment by Zelldon** [comment]
:bulb: Just as a thought we might want to consider this a general metric for all column families.

**Comment by megglos** [comment]
ZDP-Planning:
- low hanging fruit that can be done shortly
- solution needs to be discussed still though

**Comment by megglos** [comment]
@rodrigo-lourenco-lopes @oleschoenburg  we likely would need to backport this for a particular customer to make use of, is that feasible?

**Comment by rodrigo-lourenco-lopes** [comment]
> @rodrigo-lourenco-lopes @oleschoenburg we likely would need to backport this (at least back to 8.1) for a particular customer to make use of, is that feasible?

Yes it should be possible :)
