### ISSUE TITLE
Why does the job automatically perform infinite retries when it appears in a timeout state? The job record is shown in the figure 

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#12999]
Why does the job automatically perform infinite retries when it appears in a timeout state? The job record is shown in the figure 。
The same job consistently generates timeout records。
 <zeebe:taskDefinition type="abc" retries="0"/>

zeebe version is 1.3.14

```[tasklist]
### Tasks
```

**Comment by korthout** [comment]
Hi @bugbugmaker 👋 Short answer: timeouts are not considered retries, retries are related to the job worker indicating failure to handle the job.

>Specifies the number of times the job is retried when a worker signals failure 
>- ([docs](https://docs.camunda.io/docs/next/components/modeler/bpmn/service-tasks/#task-definition))

For questions like these, it is always better to open a help request topic on the Camunda forums: [https://forum.camunda.io/](https://forum.camunda.io/). By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only.

**Comment by bugbugmaker** [comment]
No, no, no, I think this should be resolved. No retry configured, but if the job status is timed_ out, the timestamp of this job will be modified periodically. But the status is always timed_ Out, this error should be resolved, closing is irresponsible.


John
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "camunda/zeebe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [camunda/zeebe] Why does the job automatically perform infinite retries when it appears in a timeout state? The job record is shown in the figure  (Issue #12999)





 
Closed #12999 as completed.

**Comment by bugbugmaker** [comment]
> > No, no, no, I think this should be resolved.
> 
> @bugbugmaker I will respond because now you make it sound like this is a bug, but it's not. **This works exactly as documented**:
> 
> [The documentation on job retries](https://docs.camunda.io/docs/next/components/modeler/bpmn/service-tasks/#task-definition) clearly state that the job retries are only used when workers signal failure (i.e. [`FailJob`](https://docs.camunda.io/docs/next/apis-tools/grpc/#failjob-rpc)):
> 
> > Specifies the number of times the job is retried when a worker signals failure
> 
> There is a feature request to decrease the number of retries on job timeout:
> 
> * [Add decreaseRetriesOnTimeout to ActivateJobsRequest #6523](https://github.com/camunda/zeebe/issues/6523)
> 
> **If you want Zeebe to respect the number of retries on job timeout, please open a feature request for it**. This would require changes to the documentation (and thus to user's expectations of Zeebe's behavior).



> 

https://github.com/camunda/zeebe/issues/13334#event-9728698616
You can refer to this question. Blocking previous tasks with sufficient threads can affect the execution of tasks for newly submitted instances. Why does this issue arise? Shouldn't different instances be executed in parallel? Task blocking causes new tasks to be unable to be processed on time, resulting in timeout. Please help to see how to configure it. Only then can we achieve the goal of not affecting instance tasks.

**Comment by bugbugmaker** [comment]
https://github.com/camunda/zeebe/issues/13334#event-9728698616
You can refer to this question. Blocking previous tasks with sufficient threads can affect the execution of tasks for newly submitted instances. Why does this issue arise? Shouldn't different instances be executed in parallel? Task blocking causes new tasks to be unable to be processed on time, resulting in timeout. Please help to see how to configure it. Only then can we achieve the goal of not affecting instance tasks.





John
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "camunda/zeebe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [camunda/zeebe] Why does the job automatically perform infinite retries when it appears in a timeout state? The job record is shown in the figure  (Issue #12999)





  
No, no, no, I think this should be resolved.
  
@bugbugmaker I will respond because now you make it sound like this is a bug, but it's not. This works exactly as documented:
 
The documentation on job retries clearly state that the job retries are only used when workers signal failure (i.e. FailJob):
  
Specifies the number of times the job is retried when a worker signals failure
  
 
There is a feature request to decrease the number of retries on job timeout:
  
#6523
  
If you want Zeebe to respect the number of retries on job timeout, please open a feature request for it. This would require changes to the documentation (and thus to user's expectations of Zeebe's behavior).

**Comment by korthout** [comment]
@bugbugmaker Zeebe is a free and open-source project where users can get community support on our [forums](https://forum.camunda.io/) and on [Slack](https://camunda.com/slack). 

For the problems you're facing, there is [documentation available about job workers](https://docs.camunda.io/docs/next/components/concepts/job-workers/#requesting-jobs), and even [documented best practices for blocking vs. non-blocking task parallelization](https://docs.camunda.io/docs/next/components/best-practices/development/writing-good-workers/#scaling-workers).

Of course, we want to understand the struggles our users face so we can build a better tool, but the engineers cannot spend all their time trying to help resolve your usage problems. We are here first and foremost to resolve bugs in Zeebe and build the features our user base needs.

If the available resources above are not enough for you, you can consider reaching out for dedicated [Consulting](https://camunda.com/services/consulting/), [Training](https://camunda.com/services/training/), and/or [Enterprise Support](https://camunda.com/services/support/) services.

**Comment by bugbugmaker** [comment]
> 

Thank you very much. That's all I need
