### ISSUE TITLE
When the service task retries parameter is set to 0, under what circumstances will infinite retries of the service task be triggered.Now it is found that the intent status of the service task is TIMED_OUT This task will retry indefinitely during TIMED_OUT. The XML configuration retry count for this task is 0.The zeebe version used is 1.3.14.

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#13010]
When the service task retries parameter is set to 0, under what circumstances will infinite retries of the service task be triggered.Now it is found that the intent status of the service task is TIMED_OUT This task will retry indefinitely during TIMED_OUT. The XML configuration retry count for this task is 0.The zeebe version used is 1.3.14.

**Comment by bugbugmaker** [comment]
@npepinpe @ceefour @nikku Can you give me some help?

**Comment by bugbugmaker** [comment]
@npepinpe @ceefour @nikku May I ask when TIMED will appear in the next job_ OUT status.
The number of retries for the design file XML has been set to 3, but this issue still occurs.

**Comment by remcowesterhoud** [comment]
Hi @bugbugmaker 👋 
For questions like these, it is always better to open a help request topic on the Camunda forums: https://forum.camunda.io/. By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.
I'm closing this issue as we aim to use the GitHub issues for development purposes only.
