### ISSUE TITLE
Remove zbctl from 8.3 images going forward

### ISSUE THREAD

**Issue by abbasadel** [camunda/zeebe#13024]
**Is your feature request related to a problem? Please describe.**
Many of the recently reported [CVEs](https://github.com/camunda/zeebe/issues/12649) were related to the `zbctl` in the docker image, which only used in debugging and troubleshooting of SaaS clusters.

**Describe the solution you'd like**
Remove `zbctl` from the docker images from 8.3 going forward. This would eliminate any CVEs reported on our docker images that are golang related.

**Comment by megglos** [comment]
ZDP-Triage:
- would be nice to get out of the way, might be worth combining it with #12959

**Comment by npepinpe** [comment]
The simplest approach is to remove it from the distribution entirely. Would that be alright? Otherwise, we can remove it only from the Dockerfile.

**Comment by megglos** [comment]
> The simplest approach is to remove it from the distribution entirely. Would that be alright? Otherwise, we can remove it only from the Dockerfile.

I guess that would be fine 🤔  we attach it as artifact on every release anyway

**Comment by npepinpe** [comment]
I've opened the PR where it's removed from the Dockerfile. It's also not that big a deal to do it then, and I guess it's a smaller breaking change :shrug:

I'm pretty 50/50 on this honestly.

**Comment by megglos** [comment]
> I've opened the PR where it's removed from the Dockerfile. It's also not that big a deal to do it then, and I guess it's a smaller breaking change 🤷
> 
> I'm pretty 50/50 on this honestly.

if it's already done on the dockerfile that's also fine then, the smaller scope would give us more flexibility to revise that decision ^^
