### ISSUE TITLE
As a Zeebe Java user, I want to complete a Job with a single variable

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/zeebe#13040]
**Is your feature request related to a problem? Please describe.**
As a programmer writing Zeebe Job Handlers, I want to complete a job returning only a single variable value.

The `newCompleteCommand` offers only a parameter `.variables()` where I have to wrap the value in a Map beforehand.

This is overhead.

**Describe the solution you'd like**
`client.newCompleteCommand(job).variable("name", value)...`

**Describe alternatives you've considered**
Promote the Java feature with `Map.of("name", value)` giving examples in the docs and Zeebe examples. 

Older programmers, that learned Java with versions older than 8 are not aware of this shortcut.

**Additional context**
It came up in a migration Workshop with a customer.

**Comment by Gireesh2002** [comment]
Acdording to [javadoc.io]https://javadoc.io/doc/io.camunda/zeebe-client-java/1.2.1/index-all.html
My Suggesstion
befor
jobClient.newCompleteCommand(job.getKey()).variables(variables);
after
System.out.println(job.getElementId());   // returns element Id (or) null
                  Map variables = job.getVariablesAsMap();  // Get variables
jobClient.newCompleteCommand(job.getKey()).variables((Map.of("newVariable","VariableFromClient"));

**Comment by korthout** [comment]
ZPA triage:
- seems like a reasonable request
- should be a good first issue
- @aleksander-dytko please consider if you want the team to work on this from PM perspective

**Comment by aleksander-dytko** [comment]
@korthout thanks for the mention. I don't see it as a priority at the moment - changing priority level to `Later`.

**Comment by megglos** [comment]
ZDP-Triage:
- not affecting ZDP
