### ISSUE TITLE
Detect health issue when partition is stuck in a transition

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#13042]
**Is your feature request related to a problem? Please describe.**
When a [partition is stuck in a transition](https://github.com/camunda/zeebe/issues/12763), it can be very difficult to figure out what went wrong. The only way is to reconstruct the transition sequence based on logs and then spot one where not all steps have finished. 

**Describe the solution you'd like**

The partition should be detected as unhealthy and a clear warning message should explain that a transition is not making progress. Ideally, the message includes the transition step name.

**Describe alternatives you've considered**
Fix https://github.com/camunda/zeebe/issues/12763 or hope that this will not happen.

**Additional context**
Related to https://jira.camunda.com/browse/SUPPORT-17178

**Comment by megglos** [comment]
ZDP-Planning:
- the goal would be to make it more clear what the issue is
- could be a smaller hanging fruit assuming it's really just adding timeout handling to the transition

**Comment by oleschoenburg** [comment]
Since we do not have a way to force close an actor and I suspect that this would be tricky to implement, I'd suggest to first focus only on the health reporting aspect.

So just a simple functionality that marks a partition as unhealthy when a single transition step has been running for more than say 60 seconds. Since it's only reporting a health issue, I don't think we need to make this configurable.
