### ISSUE TITLE
Document new Deployment Distribution logic

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#13058]
As we're switching the Deployment Distribution over on the Generalized Record Distribution (aka Command Distribution), we should document how the logic of distribution works. This description should be general, but also include a section on resource deployments.

**Comment by remcowesterhoud** [comment]
I question the value of including a section on resource deployments. Distribution is generic, it will work the same for all commands. I don't see a need to touch upon specific cases.
I could add a full example and use resource deployment for this, but other than that I wouldn't go deeper into it.
