### ISSUE TITLE
Cancel on-going remote stream registration on stream removal

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13061]
**Describe the bug**

There is currently a potential race condition which would result in a remote stream existing server side, even though the client stream has gone away.

Since we register remote streams asynchronously, a remove request may be submitted client side, which will immediately remove it there. Then asynchronous removal requests are sent to the server. However, this can be interleaved with the asynchronous registration, resulting in a stream existing server side.

The impact is additional latency during a push, or possible unnecessary job activation if it was the last stream for this type. However, the stream will eventually get removed appropriately.

**Expected behavior**

Registration/removal of remote streams is sequenced, such that a removal request would cancel registration attempts, and queue the removal after whatever in-flight requests were sent are finished.

There is still a slight edge case around time outs, of course, but I think this is acceptable for now. The other option would be introducing even more coordination in the protocol, and I'd rather avoid this.

**Comment by npepinpe** [comment]
Solution proposal would be to serialize all lifecycle operations against a stream.

**Comment by npepinpe** [comment]
The idea is to associate a `ClientStreamRegistration` state machine to each stream, which manages the current state of the remote registration. States would be:

```mermaid
graph LR;
    Registering-->Registered;
    Registering-->Removing;
    Registered-->Registering;
    Registered-->Removing;
    Removing-->Removed;
```

When a client first connects, it creates a registration state machine. The initial state is `REGISTERING`. In this state, it will send registration requests to all known brokers. It transitions to `REGISTERED` when it has been registered to all known brokers. If the client disconnects in this stage, it transitions to `REMOVING`.

In the `REGISTERED` state, it does nothing. When a new broker is discovered, it transitions to `REGISTERING`, and again only transitions back to `REGISTERED` when it is registered to all known brokers. If, however, a client disconnects in the `REGISTERED` state, it transitions to `REMOVING`.

In the `REMOVING` state, it first cancels any in-flight registration requests, if possible. It will also discard any responses from previous registration requests at that point. Then it sends a request to all known brokers to remove this stream. When it is disconnected from all brokers, it transitions to `REMOVED`. If a new broker is discovered in this state, nothing should happen.

In the `REMOVED` state, nothing happens, and ideally the registration is garbage collected. Any incoming responses should be discarded.

**Comment by npepinpe** [comment]
The above is not quite enough to catch all edge cases however. Since requests can be processed out of order, for every request to a broker per stream, we have to wait until previous requests are finished before sending the next one. Now, we still have the time out edge case - when a request to a broker times out, we can't tell if it never made it, or if it will eventually be processed. But the likelihood of a request being processed out of order in this case is very low I think. Say you send an ADD request, which times out, then a REMOVE request. It's very unlikely that the REMOVE request will somehow be received and processed before the ADD by the remote server. Whereas if you send an ADD, then immediately a REMOVE (without waiting for the ADD), the likelihood is much higher.

**Comment by deepthidevaki** [comment]
If we are not able to prevent the edge case due to REMOVE processed before ADD, we can handle it safely by ensuring that gateway sends a `NoStreamExistsException`, and the broker proactively closes the stream if it gets this error.

**Comment by npepinpe** [comment]
I think that's already the case. In a way, this issue is generally an optimization one, to avoid unnecessarily activating and pushing a job when there is nothing to receive it. It's a bit hard for me to evaluate the likelihood of this happening. I see two cases:

1. A client disconnects quickly while registration is still on-going.
2. A client disconnects around the same time a new broker was added to the topology.

I think for case 1 this is not too likely, so the second case is probably going to be the "common" one (and also how I initially observed it).

My current approach is to replace the set of servers an `AggregatedClientStream` is connected to with a map of server -> registration state. The registration state will keep track of the current state (e.g. `INITIAL`, `ADDING`, etc.), transition rules, and the single in-flight request (as we don't allow more than one at a time). Note that registrations are scoped per server.

**Comment by deepthidevaki** [comment]
> I think that's already the case.

:+1: 

> My current approach is to replace the set of servers an AggregatedClientStream is connected to with a map of server -> registration state. The registration state will keep track of the current state (e.g. INITIAL, ADDING, etc.), transition rules, and the single in-flight request (as we don't allow more than one at a time). Note that registrations are scoped per server.

This sounds good. Will AggregatedClientStream also marks if the client is closed, so that it can actively close registrations in case of out-of-order Add/Remove requests? i.e if a broker moves to ADDED state after the client is closed, how do we detect this and send a REMOVE request?

**Comment by npepinpe** [comment]
Correct, I ended up adding a CLOSED state to the registration as a short-circuit way to close any pending operations.
