### ISSUE TITLE
Backup tests are flaky

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13202]
**Summary**

- How often does the test fail? 5 times (though only checked 3 causes)
- Does it block your work? No, but it's annoying for PRs
- Do we suspect that it is a real failure? Possibly

**Context**

So while it looks like the container cannot start, it seems from the logs that the restore operation fails completely, hence why the container doesn't start up properly?

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.IllegalStateException: Container did not start correctly.
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485) ~[testcontainers-1.18.3.jar:1.18.3]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.18.3.jar:1.18.3]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) ~[testcontainers-1.18.3.jar:1.18.3]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) ~[testcontainers-1.18.3.jar:1.18.3]
	at io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT.restoreBackup(GcsRestoreAcceptanceIT.java:134) ~[test-classes/:?]
	at io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT.lambda$shouldFailForNonExistingBackup$1(GcsRestoreAcceptanceIT.java:79) ~[test-classes/:?]
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63) ~[assertj-core-3.24.2.jar:?]
	at org.assertj.core.api.ThrowableTypeAssert.isThrownBy(ThrowableTypeAssert.java:59) ~[assertj-core-3.24.2.jar:?]
	at io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT.shouldFailForNonExistingBackup(GcsRestoreAcceptanceIT.java:79) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727) ~[junit-platform-commons-1.9.3.jar:1.9.3]
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60) ~[junit-jupiter-engine-5.9.3.jar:5.9.3]
</pre>
</details>

**Hypotheses**

Looks like restore did not work due to missing backup?

**Logs**

<details><summary>Logs</summary>
<pre>
04:23:03.582 [] [ForkJoinPool-6-worker-1] INFO  org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
04:23:03.972 [] [ForkJoinPool-6-worker-1] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Testcontainers Host with tc.host=tcp://127.0.0.1:36563
04:23:03.972 [] [ForkJoinPool-6-worker-1] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is 127.0.0.1
04:23:04.005 [] [ForkJoinPool-6-worker-1] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 78+testcontainerscloud
  API Version: 1.43
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
04:23:04.047 [] [ForkJoinPool-6-worker-1] INFO  tc.testcontainers/ryuk:0.5.1 - Creating container for image: testcontainers/ryuk:0.5.1
04:23:04.154 [] [ForkJoinPool-6-worker-1] INFO  tc.testcontainers/ryuk:0.5.1 - Container testcontainers/ryuk:0.5.1 is starting: f2bf6f625e95e6eb5be4ef4425d4ba41f9129e3858431c39db5cdc28a99fdb57
04:23:04.843 [] [ForkJoinPool-6-worker-1] INFO  tc.testcontainers/ryuk:0.5.1 - Container testcontainers/ryuk:0.5.1 started in PT0.829694143S
04:23:04.848 [] [ForkJoinPool-6-worker-1] INFO  org.testcontainers.utility.RyukResourceReaper - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
04:23:04.848 [] [ForkJoinPool-6-worker-1] INFO  org.testcontainers.DockerClientFactory - Checking the system...
04:23:04.849 [] [ForkJoinPool-6-worker-1] INFO  org.testcontainers.DockerClientFactory - ?? Docker server version should be at least 1.6.0
04:23:04.856 [] [ForkJoinPool-6-worker-1] INFO  tc.fsouza/fake-gcs-server:1 - Pulling docker image: fsouza/fake-gcs-server:1. Please be patient; this may take some time but only needs to be done once.
04:23:05.532 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Starting to pull image
04:23:05.541 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
04:23:05.866 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Pulling image layers:  3 pending,  1 downloaded,  0 extracted, (32 bytes/? MB)
04:23:05.878 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Pulling image layers:  2 pending,  2 downloaded,  0 extracted, (26 KB/? MB)
04:23:05.904 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Pulling image layers:  2 pending,  2 downloaded,  1 extracted, (139 KB/? MB)
04:23:06.070 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Pulling image layers:  1 pending,  3 downloaded,  1 extracted, (3 MB/? MB)
04:23:06.587 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Pulling image layers:  1 pending,  3 downloaded,  2 extracted, (10 MB/? MB)
04:23:06.602 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Pulling image layers:  1 pending,  3 downloaded,  3 extracted, (10 MB/? MB)
04:23:06.615 [] [docker-java-stream--2340703] INFO  tc.fsouza/fake-gcs-server:1 - Pull complete. 4 layers, pulled in 1s (downloaded 10 MB at 10 MB/s)
04:23:06.620 [] [ForkJoinPool-6-worker-1] INFO  tc.fsouza/fake-gcs-server:1 - Creating container for image: fsouza/fake-gcs-server:1
04:23:06.813 [] [ForkJoinPool-6-worker-1] INFO  tc.fsouza/fake-gcs-server:1 - Container fsouza/fake-gcs-server:1 is starting: 6ee1a17c7df10fc094ff6d7b9ae7303d8dbf96b5ea17e1d737d0f8b89991c1dd
04:23:07.901 [] [ForkJoinPool-6-worker-1] INFO  tc.fsouza/fake-gcs-server:1 - Container fsouza/fake-gcs-server:1 started in PT3.051768822S
04:23:08.071 [] [ForkJoinPool-6-worker-1] INFO  tc.localhost:5000/camunda/zeebe:current-test - Creating container for image: localhost:5000/camunda/zeebe:current-test
04:23:08.162 [] [ForkJoinPool-6-worker-1] INFO  tc.localhost:5000/camunda/zeebe:current-test - Container localhost:5000/camunda/zeebe:current-test is starting: d2f58a7c25d068fdce4b239806965f5b197fe55d1e7798fc03db0f9774f575a6
04:23:08.747 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDERR: ++ hostname -i
04:23:08.747 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDERR: + HOST=172.22.0.3
04:23:08.747 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDERR: + '[' false = true ']'
04:23:08.747 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDERR: + '[' true = true ']'
04:23:08.747 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDERR: + exec /usr/local/zeebe/bin/restore --backupId=1234
04:23:13.478 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
04:23:16.870 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 
04:23:16.870 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:   .   ____          _            __ _ _
04:23:16.870 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
04:23:16.870 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
04:23:16.870 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
04:23:16.870 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:   '  |____| .__|_| |_|_| |_\__, | / / / /
04:23:16.870 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:  =========|_|==============|___/=/_/_/_/
04:23:16.911 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:  :: Spring Boot ::                (v3.1.0)
04:23:16.911 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 
04:23:17.667 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:17.645 [] [main] INFO 
04:23:17.668 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       io.camunda.zeebe.restore.RestoreApp - Starting RestoreApp v8.3.0-SNAPSHOT using Java 17.0.7 with PID 7 (/usr/local/zeebe/lib/camunda-zeebe-8.3.0-SNAPSHOT.jar started by root in /usr/local/zeebe)
04:23:17.685 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:17.684 [] [main] INFO 
04:23:17.686 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       io.camunda.zeebe.restore.RestoreApp - The following 1 profile is active: "restore"
04:23:25.736 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:25.729 [] [main] INFO 
04:23:25.753 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       io.camunda.zeebe.restore.RestoreApp - Started RestoreApp in 11.704 seconds (process running for 16.997)
04:23:25.777 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:25.775 [] [main] INFO 
04:23:25.778 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       io.camunda.zeebe.restore.RestoreApp - Starting to restore from backup 1234
04:23:25.914 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:25.910 [] [main] INFO 
04:23:25.914 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       io.camunda.zeebe.restore.RestoreManager - Restoring partitions [1]
04:23:26.002 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:25.998 [] [main] INFO 
04:23:26.002 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       io.camunda.zeebe.restore.PartitionRestoreService - Searching for a completed backup with id 1234
04:23:26.919 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:26.838 [] [ForkJoinPool-1-worker-1] ERROR
04:23:26.920 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       io.camunda.zeebe.restore.PartitionRestoreService - Could not find a valid backup with id 1234. Found [BackupStatusImpl[id=BackupIdentifierImpl[nodeId=0, partitionId=1, checkpointId=1234], descriptor=Optional.empty, statusCode=DOES_NOT_EXIST, failureReason=Optional.empty, created=Optional.empty, lastModified=Optional.empty]]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:26.942 [] [ForkJoinPool.commonPool-worker-1] ERROR
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       io.camunda.zeebe.restore.RestoreManager - Failed to restore broker. Deleting data directory /usr/local/zeebe/data
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: java.util.concurrent.CompletionException: io.camunda.zeebe.restore.BackupNotFoundException: Could not find a completed backup with id 1234.
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: Caused by: io.camunda.zeebe.restore.BackupNotFoundException: Could not find a completed backup with id 1234.
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at io.camunda.zeebe.restore.PartitionRestoreService.lambda$findValidBackup$6(PartitionRestoreService.java:238) ~[zeebe-restore-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at io.camunda.zeebe.restore.PartitionRestoreService.lambda$findValidBackup$7(PartitionRestoreService.java:232) ~[zeebe-restore-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
04:23:26.999 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	... 9 more
04:23:27.013 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:27.012 [] [main] INFO 
04:23:27.013 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger - 
04:23:27.013 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 
04:23:27.013 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 2023-06-26 04:23:27.129 [] [main] ERROR
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT:       org.springframework.boot.SpringApplication - Application run failed
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: java.lang.IllegalStateException: Failed to execute ApplicationRunner
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:764) [spring-boot-3.1.0.jar:3.1.0]
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:751) [spring-boot-3.1.0.jar:3.1.0]
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) [spring-boot-3.1.0.jar:3.1.0]
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at io.camunda.zeebe.restore.RestoreApp.main(RestoreApp.java:51) [camunda-zeebe-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: Caused by: java.util.concurrent.CompletionException: io.camunda.zeebe.restore.BackupNotFoundException: Could not find a completed backup with id 1234.
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
04:23:27.131 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: Caused by: io.camunda.zeebe.restore.BackupNotFoundException: Could not find a completed backup with id 1234.
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at io.camunda.zeebe.restore.PartitionRestoreService.lambda$findValidBackup$6(PartitionRestoreService.java:238) ~[zeebe-restore-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at io.camunda.zeebe.restore.PartitionRestoreService.lambda$findValidBackup$7(PartitionRestoreService.java:232) ~[zeebe-restore-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
04:23:27.132 [] [docker-java-stream-538814747] INFO  io.camunda.zeebe.it.backup.GcsRestoreAcceptanceIT - STDOUT: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
</pre>
</details>

**Comment by npepinpe** [comment]
Link to failed run: https://github.com/camunda/zeebe/actions/runs/5373697120/jobs/9748325717#step:10:719

**Comment by npepinpe** [comment]
Oops, so I found an issue also in zeebe-test-container where `withTopologyCheck` and `withoutTopologyCheck` will revert the default start time out from 1 minute to 30 seconds :s

**Comment by korthout** [comment]
@deepthidevaki are those fixes already available on `main`? Please link the related issues.

Opening again, as it happened again on [main](https://github.com/camunda/zeebe/actions/runs/5485173042/jobs/9993656006):
```
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 145.3 s <<< FAILURE! -- in io.camunda.zeebe.it.backup.S3RestoreAcceptanceIT
Error:  io.camunda.zeebe.it.backup.S3RestoreAcceptanceIT.shouldRunRestore -- Time elapsed: 60.69 s <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image localhost:5000/camunda/zeebe:current-test
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
```

**Comment by deepthidevaki** [comment]
This again happened in `beforeEach`
```
Error:  io.camunda.zeebe.it.backup.S3RestoreAcceptanceIT.shouldRunRestore -- Time elapsed: 60.69 s <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image localhost:5000/camunda/zeebe:current-test
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:274)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:261)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$3(TestcontainersExtension.java:76)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$4(ExtensionValuesStore.java:86)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.computeValue(ExtensionValuesStore.java:223)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:211)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.evaluate(ExtensionValuesStore.java:191)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.access$100(ExtensionValuesStore.java:171)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:89)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:53)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$startContainers$4(TestcontainersExtension.java:76)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.startContainers(TestcontainersExtension.java:76)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.findTestLifecycleAwareContainers(TestcontainersExtension.java:109)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeEach(TestcontainersExtension.java:94)
```

So test failure is not due to issues in the backup/restore operation. There were also a bunch of failures in other tests that uses containers. So I assume it is again related to testcontainers or their configuration. I will keep this issue to investigate it later.

**Comment by megglos** [comment]
ZDP-Triage:
- startup should be fixed by now be recent changes 🤞 
- Nicolas observed twice that the tests failed because of minio not getting ready
- will close this one for now and rather open a new issue for non-startup timeout related issues
