### ISSUE TITLE
JVM crash in property and engine tests

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#13205]
**Summary**

Looks like we have again a case where tests cause the JVM to crash. This happens in property tests AND engine tests.

> Try to answer the following as best as possible

- How often does the test fail? Quite often
- Does it block your work? Yes
- Do we suspect that it is a real failure? I think so

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
 Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project zeebe-workflow-engine: 
Error:  
Error:  Please refer to /runner/_work/zeebe/zeebe/engine/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/runner/_work/zeebe/zeebe/engine' && '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.10/org.jacoco.agent-0.8.10-runtime.jar=destfile=/runner/_work/zeebe/zeebe/engine/target/jacoco.exec' '-jar' '/runner/_work/zeebe/zeebe/engine/target/surefire/surefirebooter-20230626095619151_10.jar' '/runner/_work/zeebe/zeebe/engine/target/surefire' '2023-06-26T09-55-59_829-jvmRun2' 'surefire-20230626095619151_6tmp' 'surefire_1-20230626095619151_8tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.randomized.ProcessExecutionRandomizedPropertyTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/runner/_work/zeebe/zeebe/engine' && '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.10/org.jacoco.agent-0.8.10-runtime.jar=destfile=/runner/_work/zeebe/zeebe/engine/target/jacoco.exec' '-jar' '/runner/_work/zeebe/zeebe/engine/target/surefire/surefirebooter-20230626095619151_10.jar' '/runner/_work/zeebe/zeebe/engine/target/surefire' '2023-06-26T09-55-59_829-jvmRun2' 'surefire-20230626095619151_6tmp' 'surefire_1-20230626095619151_8tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.randomized.ProcessExecutionRandomizedPropertyTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:456)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:358)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:296)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1203)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1055)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:871)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
Error:  	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
Error:  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
Error:  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Error:  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Error:  	at java.base/java.lang.Thread.run(Thread.java:833)
Error:  Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/runner/_work/zeebe/zeebe/engine' && '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.10/org.jacoco.agent-0.8.10-runtime.jar=destfile=/runner/_work/zeebe/zeebe/engine/target/jacoco.exec' '-jar' '/runner/_work/zeebe/zeebe/engine/target/surefire/surefirebooter-20230626095619151_10.jar' '/runner/_work/zeebe/zeebe/engine/target/surefire' '2023-06-26T09-55-59_829-jvmRun2' 'surefire-20230626095619151_6tmp' 'surefire_1-20230626095619151_8tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.randomized.ProcessExecutionRandomizedPropertyTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$null$3(ForkStarter.java:350)
Error:  	... 4 more
Error:  -> [Help 1]
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be omitted

Maybe again an concurrency bug?

**Logs**

* https://github.com/camunda/zeebe/actions/runs/5376724922/jobs/9754264400
* https://github.com/camunda/zeebe/actions/runs/5376462300/jobs/9753647473
* https://github.com/camunda/zeebe/actions/runs/5376462518
* https://github.com/camunda/zeebe/actions/runs/5376462594

**Comment by Zelldon** [comment]
Issue with OOM?

**Comment by Zelldon** [comment]
might be duplicate of https://github.com/camunda/zeebe/issues/13164

**Comment by korthout** [comment]
I had a quick look at this while I was working on #13164. However, I don't think it's a duplicate.

The error logs are unclear to me, I cannot figure out what happened here, but I do not see the segfault reported in #13164. Therefore I don't think it's a duplicate. What actually happened here is likely an OOM because I cannot find any Error or Failure in the log artifacts.

@Zelldon If you have any ideas on how to figure this out, please share. Otherwise, I think we may have to close this as `won't fix` due to not enough info available.

**Comment by korthout** [comment]
I understand your sentiment @Zelldon. Even though I think #13164 is not a duplicate, it may be the underlying root cause. We can spend a lot of time attempting to root cause this right now, or we can see if it is resolved by the solution fixing #13164.

As root causing this is non-trivial, I would suggest closing this for now, and seeing if it pops up again afterward the fix (#13208) is merged. WDYT?

**Comment by Zelldon** [comment]
It is reproducible for me locally, which is quite bad.

```
15:52:31.883 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
15:52:31.883 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
15:52:31.883 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
double free or corruption (out)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

It just dies without more indication, it looks like there is a concurrency issue or race condition, multiple closing/freeing of buffers.

We should definitely look into this more.

**Comment by korthout** [comment]
I've ran ProcessExecutionRandomizedPropertyTest ~2000 times now without failures on `main` 45896d56361dbfb4c8f759d85bdbf61c26d00caa.

@Zelldon Are you able to reproduce this on the head of #13208?

**Comment by Zelldon** [comment]
@korthout multiple reruns seem to be fine now.

**Comment by korthout** [comment]
@Zelldon Do you see any further need to investigate this? I imagine the same root cause is at play.
