### ISSUE TITLE
Use a fixed length segment descriptor

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#13240]
Follow up #https://github.com/camunda/zeebe/pull/12839#issuecomment-1564228116 

In  PR #12839, when we added new fields to the segment descriptor the descriptor length changed. This can cause issues, when we overwrite an existing descriptor. We have to ensure that we don't accidently overwrite the first entry. This is handled in the PR. But, when ever we make changes to the descriptor this needs to be handled correctly. It is prone to errors, so it is better we use fixed size for the descriptor. We may not use the full allocated bytes, but it allows us to add new fields without the need to change the length again.

Besides, we also now have to keep track of length of each version. https://github.com/camunda/zeebe/pull/12839#discussion_r1246323206 With fixed lenght, we might be able to handle this better.

Note: Better do it before 8.3, otherwise it will be more effort to make it backward compatible.

**Comment by deepthidevaki** [comment]
@npepinpe We discussed different things previously. 
1. As described in the issue, use a fixed length for descriptor. There will be unused bytes so that we can freely add or remove fields in future with out changing the descriptor length. This means we will have three versions - V1 (old one), V2 (version until 8.2 where the length = sbe encoded length), V3 with fixed length.
2. We also discussed about removing the need to keep track of the version length because we can determine the length while decoding sbe. In this case we will have only two version - V1 (old one) and V2. In V2 depending on sbe version we may get different lengths. We can also add new fields in future which changes the length without changing the version because sbe version is updated.

I'm now thinking about which way to proceed. Any opinions?
I'm leaning towards option 2. The main problem with variable length is that a new version should not overwrite an existing descriptor with old version. But, this is already handled in the code. So I don't see any other blockers. With this, I don't see any advantage of using fixed length. What do you think?

**Comment by npepinpe** [comment]
The second one as well :+1:

**Comment by deepthidevaki** [comment]
Closing this issue as we decided not to use fixed length descriptor. Instead PR #13618 improves the handling of version in segment descriptor.
