### ISSUE TITLE
Notify Zeebe Team in Slack when an issue is labelled as critical

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#13253]
**Is your feature request related to a problem? Please describe.**
Critical issues are defined as a "stop the world" issue. This means they require immediate attention. Currently, when an issue is labeled as critical there's no way of knowing, unless the person who added the label notifies the team. If this doesn't happen, there's a good chance we won't notice until the next triage.

**Describe the solution you'd like**
We can easily add a workflow that checks if an issue gets labelled as critical. If this is the case we could send a notification to the Zeebe slack channel to notify the engineers that attention is required.

**Describe alternatives you've considered**
People could ping us manually when they do this. But that's a manual step and could be forgotten.

**Additional context**
N/A

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- Helps us identify critical bugs more quickly
- Removes a manual step that could be forgotten otherwise
- Marking it as `upcoming` as we want to be aware of critical bugs asap
- We already send slack message from our CI. Should be easy to take inspiration from these other places.
- Low effort, potentially high impact.

**Comment by megglos** [comment]
ZDP-Triage:
- could help us being faster to react
- need to clarify who reacts on it
- right now we would assume this is done by zeebe engineers who can also escalate directly when identifying a critical issue
- marking as later for now
