### ISSUE TITLE
How can i compelte the job in specific process instance key？

### ISSUE THREAD

**Issue by SpringSan** [camunda/zeebe#13271]
I create the processInstance by the code.
`zbClient, err := zbc.NewClient(&zbc.ClientConfig{
		GatewayAddress:         gatewayAddr,
		UsePlaintextConnection: plainText,
	})

	if err != nil {
		panic(err)
	}

	// deploy process
	ctx := context.Background()
	response, err := zbClient.NewDeployResourceCommand().AddResourceFile("order-process-4.bpmn").Send(ctx)
	if err != nil {
		panic(err)
	}

	fmt.Println(response.String())

	// create a new process instance
	variables := make(map[string]interface{})
	variables["orderId"] = "31243"

	request, err := zbClient.NewCreateInstanceCommand().BPMNProcessId("order-process-4").LatestVersion().VariablesFromMap(variables)
	if err != nil {
		panic(err)
	}

	result, err := request.Send(ctx)
	if err != nil {
		panic(err)
	}

	fmt.Println(result.String())`
I want to NewCompleteJobCommand to compelete this processInstance.How can i do?

**Comment by korthout** [comment]
Hi @SpringSan 👋 Short answer: job workers are decoupled from process instances, they [work on jobs of a specific type](https://docs.camunda.io/docs/next/components/concepts/job-workers/#requesting-jobs).

For questions like these, it is always better to open a help request topic on the Camunda forums: https://forum.camunda.io/. By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only.
