### ISSUE TITLE
Will the Zeebe client only actively attempt to pull tasks after one of the tasks is completed or fails?

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#13334]
Will the Zeebe client only actively attempt to pull tasks after one of the tasks is completed or fails? If there is only one task in a certain pull, the jobhandler executing this task happens to be blocked or time-consuming. Before this task fails or is completed, the zeebe client will not actively pull new tasks. Doesn't this lead to thread redundancy? Can other newly created tasks not be processed in a timely manner?

**Comment by bugbugmaker** [comment]
@npepinpe can you give me some help?

**Comment by npepinpe** [comment]
The job worker maintains a queue internally, and will pull tasks once its queue is 30% full or less. A job is freed from the queue once it's been marked as handled, i.e. the `JobHandler` you passed when building the worker returns. While it's common to perform the complete/fail as part of the job handler, it's not required, and you could complete/fail the job asynchronously.

The queue size is the configured `maxJobsActive`. So if `maxJobsActive = 30`, then the worker will keep pulling jobs until there are over 10 jobs in the queue. It will start polling again when there are 10 or less.

Hope that helps!

**Comment by bugbugmaker** [comment]
> 



> The job worker maintains a queue internally, and will pull tasks once its queue is 30% full or less. A job is freed from the queue once it's been marked as handled, i.e. the `JobHandler` you passed when building the worker returns. While it's common to perform the complete/fail as part of the job handler, it's not required, and you could complete/fail the job asynchronously.
> 
> The queue size is the configured `maxJobsActive`. So if `maxJobsActive = 30`, then the worker will keep pulling jobs until there are over 10 jobs in the queue. It will start polling again when there are 10 or less.
> 
> Hope that helps!

But I submitted two instances before and after testing, and the first jobhandler of the previous instance manually set the plunger. The handler of the second instance's job will not execute. These two jobTypes are the same.

**Comment by npepinpe** [comment]
I'm afraid I don't understand what "manually set the plunger" means in this context.

If you create a job worker like this:

```java
final var jobs = new ArrayList<ActivatedJob>();
final var worker = client.newWorker().jobType("test").handler((c, job) -> jobs.add(job)).maxJobsActive(30).open();
```

With a process like:

![image](https://github.com/camunda/zeebe/assets/43373/fef751ff-4def-4c2f-b3cb-5a6364d11242)

Then create two instances of that process, you will get two jobs in `jobs` list above, without ever completing/failing the jobs themselves. Note that if you never complete/fail them, you will keep re-activating them as well once they hit their timeout, of course.

**Comment by bugbugmaker** [comment]
> 

@Component
public class TestWorker implements JobHandler {


  @Autowired private ZeebeClient client;

  private JobWorker worker;

  @PostConstruct
  public void register() {
	  worker = client
      .newWorker()
      .jobType("test")
      .handler(this)
      .name("test")
      .open();
    log.info("Job worker test opened and receiving jobs");
  }

  @Override
  public void handle(JobClient client, ActivatedJob job) throws Exception {
	  System.err.println("currentTime:" + System.currentTimeMillis());
	  TimeUnit.MINUTES.sleep(6);
	  client.newCompleteCommand(job.getKey()).send();
  }

  @PreDestroy
  public void unregister() {
    if (!worker.isClosed()) {
      worker.close();
      log.info("test001 Job worker closed");
    }
  }
}

**Comment by bugbugmaker** [comment]
> I'm afraid I don't understand what "manually set the plunger" means in this context.
> 
> If you create a job worker like this:
> 
> ```java
> final var jobs = new ArrayList<ActivatedJob>();
> final var worker = client.newWorker()
>     .jobType("test")
>     .handler((c, job) -> jobs.add(job))
>     .maxJobsActive(30)
>     .open();
> ```
> 
> With a process like:
> 
> ![image](https://user-images.githubusercontent.com/43373/251080662-fef751ff-4def-4c2f-b3cb-5a6364d11242.png)
> 
> Then create two instances of that process, you will get two jobs in `jobs` list above, without ever completing/failing the jobs themselves. Note that if you never complete/fail them, you will keep re-activating them as well once they hit their timeout, of course.

I am executing hibernation on the handler, and the task handler method of the second instance will not enter

**Comment by npepinpe** [comment]
What is your client configuration? By default, workers share the same thread pool which only has a single thread. So if you block in the `JobHandler`, then you block all possible job handlers.

Try configuring your client via `ZeebeClientBuilder#numJobWorkerExecutionThreads` with more threads.

**Comment by bugbugmaker** [comment]
> numJobWorkerExecutionThreads

 ZeebeClientBuilder clientBuilder = ZeebeClient.newClientBuilder();
    clientBuilder.gatewayAddress("localhost:26500");
    clientBuilder.numJobWorkerExecutionThreads(10);
    clientBuilder.usePlaintext();
    clientBuilder.withInterceptors(new TraceClientInterceptor());
    ZeebeClient client = clientBuilder.build();

**Comment by npepinpe** [comment]
For questions like these, it is always better to open a help request topic on the Camunda forums: https://forum.camunda.io/. By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only. Sorry we couldn't resolve it quickly in this context.

**Comment by bugbugmaker** [comment]
> Camunda

how to solve this problem.

> For questions like these, it is always better to open a help request topic on the Camunda forums: https://forum.camunda.io/. By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.
> 
> I'm closing this issue as we aim to use the GitHub issues for development purposes only. Sorry we couldn't resolve it quickly in this context.

How to solve this problem, there is basically no response from the forum? I really need your help

**Comment by bugbugmaker** [comment]
I really need your help




John
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "camunda/zeebe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [camunda/zeebe] Will the Zeebe client only actively attempt to pull tasks after one of the tasks is completed or fails? (Issue #13334)





 
For questions like these, it is always better to open a help request topic on the Camunda forums: https://forum.camunda.io/. By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.
 
I'm closing this issue as we aim to use the GitHub issues for development purposes only. Sorry we couldn't resolve it quickly in this context.

**Comment by bugbugmaker** [comment]
> 对于此类问题，最好在 Camunda 论坛上打开帮助请求主题： https: [//forum.camunda.io/](https://forum.camunda.io/)。通过在我们的论坛上发帖，您可以从 Camunda 专家和 Camunda 社区的经验中受益。
> 
> 我将关闭此问题，因为我们的目标是仅将 GitHub 问题用于开发目的。抱歉，我们无法在这种情况下快速解决该问题。

@npepinpe Is there anything wrong with the configuration?, What caused it.
