### ISSUE TITLE
No dependabot PRs for Spring Boot updates on stable branches

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13409]
**Description**

There are new CVEs related to Spring Boot which have been fixed on all our stable branches, but for some reason dependabot hasn't opened any PRs. For example, 8.1 is on 2.7.10, but the latest is 2.7.12 - why has dependabot not opened anything?

**Comment by npepinpe** [comment]
I've opened PRs for 8.1 and 8.0, and I'll try to get dependabot to open the 8.2 one :crossed_fingers:

**Comment by npepinpe** [comment]
[Opened an issue on the Dependabot repo](https://github.com/dependabot/dependabot-core/issues/7543)

**Comment by npepinpe** [comment]
@megglos - we had another update of Spring today, with nothing on the other branches. I've gotten no comments from the dependabot repo, so I think we should consider switching Renovate on for this to avoid missing updates.

I'm going on FTO now, do you think you could make sure we do that soon?

**Comment by megglos** [comment]
ZDP-Triage:
- small scope would be just enabling renovate for spring only, but by that chance we could do it globally

**Comment by megglos** [comment]
@rodrigo-lourenco-lopes and me agreed to try it for spring-boot only first and try it out. Then raise a suggestion to the whole team on switching fully to renovate for maven and docker after.

**Comment by megglos** [comment]
PRs were created successfully

main:
https://github.com/camunda/zeebe/pull/14630

stable:
https://github.com/camunda/zeebe/pull/14629
https://github.com/camunda/zeebe/pull/14628
