### ISSUE TITLE
Indicate the type of activated/completed/terminated catch events in Grafana

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#13410]
**Is your feature request related to a problem? Please describe.**
In the past weeks, there was a support case where it reports that the Engine is lagging behind while process new records. The incident was resolved afterwards. The incident was caused by a timer catch event that keeps generating multiple new records, so that the thread pool was busy with generating new records.

While investigating in Grafana, the team were able to observe a catch event was taking the CPU time but cannot see which type of catch event was causing the issue. Therefore, cannot root cause the issue without looking at other log resources.

**Describe the solution you'd like**
The type of events should be added to Grafana `General Overview -> Current Events` view. Every element instance should contains its own type

**Describe alternatives you've considered**
Alternative way to achieve the same goal is to look at export logs which takes more time and less accessible than Grafana.

**Additional context**
It is more precise if we have activation, completion and termination information of catch events in the view.

**Comment by korthout** [comment]
Marking this as `upcoming` as it can help us troubleshoot problems faster and more easily.

It is blocked by:
- #13433
