### ISSUE TITLE
Keep track of event types in the Engine

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#13433]
**Is your feature request related to a problem? Please describe.**
As described in the issue #13410, we want to keep track of event types that triggered elements in Grafana. This is not possible without actually adding them to the job metric in the Engine.

**Describe the solution you'd like**
Update `ProcessEngineMetrics` class to event types for `element_instance_events_total` metric. Then, update their usages for activated/completed/terminated element instances.

**Describe alternatives you've considered**
As long as we want to show these metrics in Grafana, there is no a real alternative than keeping track of this metric in the Engine.

**Comment by korthout** [comment]
Alternative solution, we can add another label to the [`element_instance_events_total` metric](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/metrics/ProcessEngineMetrics.java#L55-L61) to track `eventType`

**Comment by korthout** [comment]
I'd propose to pick this up soon, so we can unblock #13410, which can help us troubleshoot issues faster and more easily.
