### ISSUE TITLE
EngineErrorHandlingTest.shouldNotBanInstanceOnJobCommand 

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#13463]
**Summary**

- How often does the test fail? 1

**Failures**

```
Error:    Run 1: EngineErrorHandlingTest.shouldNotBanInstanceOnJobCommand:464 
Expecting actual:
  [1L, 2L]
to contain exactly (and in same order):
  [1L, 2L]
but could not find the following elements:
  [2L]
```

**Logs**

[https://github.com/camunda/zeebe/actions/runs/5532447997/jobs/10094550505](https://github.com/camunda/zeebe/actions/runs/5532447997/jobs/10094550505)

[logs_77972.zip](https://github.com/camunda/zeebe/files/12028913/logs_77972.zip)

**Comment by remcowesterhoud** [comment]
Moving to ready as it's a flaky test
