### ISSUE TITLE
Add a foreign key relation from process instance to process definition

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#13495]
**Description**

Recently, we encountered [a critical bug](https://github.com/camunda/zeebe/issues/13254) where process instances were created for a process definition that was not deployed successfully.

While that bug came to be due to problems with cache invalidation, it struck me as odd that we don't have a relational data constraint between process instances and the process definition they belong to.

With #13475 merged, we already have a place where this relation is stored. But, the foreign key relation is not explicitly defined and thus not asserted.

We should consider the performance/safety trade-off to defining this as a foreign key relationship that can be asserted as part of the data consistency checks feature flag. AFAIK, the performance cost is one additional lookup per insertion at one insertion per process instance.

See: 
- https://github.com/camunda/zeebe/issues/13254#issuecomment-1617550522
- https://github.com/camunda/zeebe/pull/13373#discussion_r1261633196

**Comment by korthout** [comment]
If we want to do this, it would be an x-small effort (changing the column family to use a foreign key). 

But, before we start this, we must discuss whether we want to make this trade-off.

**Comment by korthout** [comment]
CC @remcowesterhoud @Zelldon @romansmirnov, feel free to comment your thoughts

**Comment by remcowesterhoud** [comment]
Sorry, this got lost in my notifications. I find it hard to judge how much of an impact it would have on performance. I like the idea of having it though. As it's XS effort, maybe it's worth just implementing it and running a benchmark?
