### ISSUE TITLE
Process instances are banned when trying to activate a call activity with large variables

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13521]
**Describe the bug**

If activating a call activity with large variables causes processing to exceed the batch size, the complete process instance is banned and left in limbo.

The current workaround is to ensure that we don't run into this case; however, once you hit it, there's nothing you can do but recreate the instance with smaller payloads.

Support:
-  https://jira.camunda.com/browse/SUPPORT-17661
- https://jira.camunda.com/browse/SUPPORT-17882

**To Reproduce**

Create a process with a dummy service task which leads to a call activity. Once the task is activated, separately as to not exceed the batch size, create 4 large variables, e.g. of 1MB each (using the set variable command, one at a time). Then complete the task. Activating the call activity will fail and result in a banned instance.

**Expected behavior**

An incident is raised, such that I can modify my variables to save this instance.

**Log/Stacktrace**

I've anonymized the stacktrace below. You can find more logs here: https://cloudlogging.app.goo.gl/aarrs1J5TY22X5gXA

<details><summary>Full Stacktrace</summary>
 <p>

```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE, intent=ACTIVATE_ELEMENT}, value={"bpmnElementType":"CALL_ACTIVITY","elementId":"Activity_1aba60i","bpmnProcessId":"process","version":8,"processDefinitionKey":2251800414371946,"processInstanceKey":4503599979491273,"flowScopeKey":4503599979491273,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'Can't append entry: 'RecordBatchEntry[recordMetadata=RecordMetadata{recordType=EVENT, valueType=VARIABLE, intent=CREATED}, key=4503599980117234, sourceIndex=-1, unifiedRecordValue={"name":"foo","value":"U2VkIHV0IHBlcnNwaWNpYXRpcyB1bmRlIG9tbmlzIGlzdGUgbmF0dXMgZXJyb3Igc2l0IHZvbHVwdGF0ZW0gYWNjdXNhbnRpdW0gZG9sb3JlbXF1ZSBsYXVkYW50aXVtLCB0b3RhbSByZW0gYXBlcmlhbSwgZWFxdWUgaXBzYSBxdWFlIGFiIGlsbG8gaW52ZW50b3JlIHZlcml0YXRpcyBldCBxdWFzaSBhcmNoaXRlY3RvIGJlYXRhZSB2aXRhZSBkaWN0YSBzdW50IGV4cGxpY2Fiby4gTmVtbyBlbmltIGlwc2FtIHZvbHVwdGF0ZW0gcXVpYSB2b2x1cHRhcyBzaXQgYXNwZXJuYXR1ciBhdXQgb2RpdCBhdXQgZnVnaXQsIHNlZCBxdWlhIGNvbnNlcXV1bnR1ciBtYWduaSBkb2xvcmVzIGVvcyBxdWkgcmF0aW9uZSB2b2x1cHRhdGVtIHNlcXVpIG5lc2NpdW50LiBOZXF1ZSBwb3JybyBxdWlzcXVhbSBlc3QsIHF1aSBkb2xvcmVtIGlwc3VtIHF1aWEgZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyLCBhZGlwaXNjaSB2ZWxpdCwgc2VkIHF1aWEgbm9uIG51bXF1YW0gZWl1cyBtb2RpIHRlbXBvcmEgaW5jaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYW0gYWxpcXVhbSBxdWFlcmF0IHZvbHVwdGF0ZW0uIFV0IGVuaW0gYWQgbWluaW1hIHZlbmlhbSwgcXVpcyBub3N0cnVtIGV4ZXJjaXRhdGlvbmVtIHVsbGFtIGNvcnBvcmlzIHN1c2NpcGl0IGxhYm9yaW9zYW0sIG5...' with size: 1725121 this would exceed the maximum batch size. [ currentBatchEntryCount: 18, currentBatchSize: 2874115]'.

```

</p>
</details>

**Environment:**
- OS: Ubuntu Focal
- Zeebe Version: 8.2.8
- Configuration: SaaS

**Comment by Zelldon** [comment]
Related https://github.com/camunda/zeebe/issues/13016

**Comment by korthout** [comment]
Thanks for raising this @npepinpe 

As there is no good workaround available and the chance to run into this is reasonable, I'm prioritizing this as `upcoming`.

>**Expected behavior**
>An incident is raised, such that I can modify my variables to save this instance.

To resolve this, we'll need to handle errors in the `BpmnStreamProcessor`. However, we're unable to raise an incident for every process instance element type yet. So, we either need to pass the error handling along to the respective `BpmnElementProcessor` (i.e. `CallActivityProcessor`) or have element type-specific code in the BpmnStreamProcessor.

Since this is not entirely trivial, I'm sizing this as `Medium`.
