### ISSUE TITLE
zbctl status: failed to obtain access token

### ISSUE THREAD

**Issue by goenkale** [camunda/zeebe#13531]
**Describe the bug**

I get this error when trying to connect using zbctl:

```
C:\Users\VictorGarciaPereda>zbctl status
Error: rpc error: code = Canceled desc = failed to apply token: failed to obtain access token: Post "https://login.cloud.camunda.io/oauth/token": context deadline exceeded
```

**To Reproduce**

Hard to say. I checked with a colleague of my team and it worked for her.

**Expected behavior**
A response from the cluster.

**Environment:**
- OS: Windows cmd
- Zeebe Version: 8.2.3
- Configuration: 

![image](https://github.com/camunda/zeebe/assets/11518795/08e4dd8a-a208-4b9b-a730-a6d54de9c8ad)

![image](https://github.com/camunda/zeebe/assets/11518795/61362ac8-607b-4e66-8eb1-28533aacce5a)

**Comment by korthout** [comment]
Hi @goenkale 👋 Short answer: did you create your [own client connection credentials](https://docs.camunda.io/docs/next/guides/setup-client-connection-credentials/)?

For questions like these, it is always better to open a help request topic on the Camunda forums: [https://forum.camunda.io/](https://forum.camunda.io/). By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only.
