### ISSUE TITLE
Cannot complete job failed if use long retry backoff time !

### ISSUE THREAD

**Issue by kimnamcham** [camunda/zeebe#13583]
When i use command failed job with long retry backoff time , i cannot complete job
This is my code when receivied job from gateway:

 Duration retryBackoffDuration = Duration.ofDays(365);
        zeebeClient.newWorker()
                .jobType("io.camunda.zeebe:userTask")
                .handler((client, job) -> {
                    ZeebeFuture<FailJobResponse> zeebeFuture = zeebeClient
                            .newFailCommand(job.getKey())
                            .retries(1)
                            .retryBackoff(retryBackoffDuration)
                            .send();

Error when complete job:

Command 'COMPLETE' rejected with code 'INVALID_STATE': Expected to complete job with key '2251799813693166', but it is in state 'FAILED'

Anyone resove this issuses? I need hold user task for a long time util user complete job manual.

**Comment by korthout** [comment]
Hi @kimnamcham 👋 Short answer: at the moment, it is not possible to complete failed jobs. It looks to me that you want to block the job for a long time before completing it. You can do this by activating the job with a long job timeout:

```java
zeebeClient.newWorker()
  .jobType("io.camunda.zeebe:userTask")
  .handler((client,job) -> { /* .. */})
  .timeout(Duration.ofDays(365))
  .open()
```

For questions like these, it is always better to open a help request topic on the Camunda forums: [https://forum.camunda.io/](https://forum.camunda.io/). By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only.
