### ISSUE TITLE
Tests in `ActivatableJobsPushTest` class are slow

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#13606]
**Description**

All tests in the `ActivatableJobsPushTest` class take 5~20 seconds to complete. That has a negative effect on our build time and should be improved.

**Comment by nicpuppa** [comment]
Hey @berkaycanbc, I run the test class locally multiple times and those are the numbers:

<img width="597" alt="Screenshot 2023-12-14 at 11 46 42" src="https://github.com/camunda/zeebe/assets/72783243/4b81d07a-6b8d-4e19-bca3-0688df742590">

Is not only the test mention in the title, but the whole test class that is slow
