### ISSUE TITLE
Excessive disk usage from benchmark CW30-mixed

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#13619]
**Description**

The disk usage of the mixed benchmark of CW30 is steadily increasing. It's a matter of time before it runs out of disk space:
<img width="1009" alt="image" src="https://github.com/camunda/zeebe/assets/5787702/1d7fef20-3083-4fe7-9bf5-e92dc6c07c3e">

If we compare this to CW29 we can see it remains stable there:
<img width="993" alt="image" src="https://github.com/camunda/zeebe/assets/5787702/a428c87c-dc48-4d89-8e0e-66b6d859f2b1">

We more than likely merged something in the last week that is causing this issue.

**Comment by oleschoenburg** [comment]
Possibly due to https://github.com/camunda/zeebe/issues/13598. Due dates are not getting cleaned up anymore because the checker runs into the NPE every time.

**Comment by oleschoenburg** [comment]
I'm confident that this is fixed with https://github.com/camunda/zeebe/pull/13639
