### ISSUE TITLE
Java Client: Make correlationKey step optional

### ISSUE THREAD

**Issue by aleksander-dytko** [camunda/zeebe#13649]
**Is your feature request related to a problem? Please describe.**
Currently, when you want to start a process instance with a message, you need to provide a correlationKey, even though it's not [needed](https://docs.camunda.io/docs/components/modeler/bpmn/message-events/#message-start-events).  

Customer anecdote:
"We have to set a value we don´t need, so maybe a confused developer who will search for the correlationKey if he/she don´t know this issue."

```java
final ZeebeFuture<PublishMessageResponse> send = this.client.newPublishMessageCommand()
.messageName("MessageRestartLasttest")
.correlationKey("walter")
.variables(Map.of("anzahl", anzahlLoop))
.send();
``` 

**Describe the solution you'd like**
It should be possible to skip PublishMessageCommandStep2. It is up to the coder to know if and when a correlationKey is required by the given BPMN message event.

**Describe alternatives you've considered**
It can be set to "" (empty string) if you do not need it for that purpose, e.g.:
```java
final PublishMessageResponse publishMessageResponse = client.newPublishMessageCommand()
                    .messageName("start-process")
                    .correlationKey("")
                    .variables(Map.of("variable1", "value1"))
                    .send()
                    .join();
``` 

**Additional context**
https://jira.camunda.com/browse/SUPPORT-17405

**Comment by remcowesterhoud** [comment]
Individual triage:
- Easy to fix, small UX improvement
- Very reasonable workaround, therefore I don't see any urgency at the moment. @aleksander-dytko please correct me if that's not the case because it is linked to a support case.
- Moving to the backlog as with `later` priority.

**Comment by remcowesterhoud** [comment]
Hi @AjeetNathawat. That's great! We'd love to see a contribution here.

Your idea is going in the right direction. I think we should change the current `messageName` method to return step3 instead of step2. Of course it should still be possible to set the correlationKey, so we must make this available in step3. I think we can do that by extending step2 in step3.

**Comment by jdi128** [comment]
Hi @remcowesterhoud, 
I fixed this issue locally but thought again about your solution. While it works and does not break contract it feels weird to go from step1 directly to step 2. 
I thought about a method in Step2 `PublishMessageCommandStep3 withoutCorrelationKey();`
This would still force the user to think about the correlationKey and decide whether the message needs one or not. 

What are your thoughts about this?
