### ISSUE TITLE
Configure Renovate to work with ubuntu tag versioning

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#13736]
**Description**

Since we merged https://github.com/camunda/zeebe/pull/13706 renovate logs indicate it cannot handle the ubuntu tags using a date as versioning, see the logs here
https://developer.mend.io/github/camunda/zeebe/-/job/3cdacac3-5fae-4252-83d7-23371ae59cf6

```
Dependency ubuntu has unsupported/unversioned value jammy-20230624 (versioning=ubuntu)
{
  "baseBranch": "main"
}
```

This issue indicates there seems to be a way to configure renovate to support these though
see https://docs.renovatebot.com/modules/versioning/#ubuntu-versioning
and a potential workaround here https://github.com/renovatebot/config-help/issues/633

**Comment by megglos** [comment]
ZDP-Triage:
- even though we do a package update as part of the docker build we should make sure we use the latest base

**Comment by remcowesterhoud** [comment]
Individual triage:

- We should do this
- As I can see ZDP has it in their Ready column I assume they're planning to work on it. This is why I'll put it in the backlog for ZPA, we don't need both teams working on it simultaneously. This also allows us to focus on the multi-tenancy and migration topics.

**Comment by megglos** [comment]
We ditched the date versioning and went for the plain names release tag + digest pinning, see https://github.com/camunda/zeebe/pull/14071#discussion_r1311176361
