### ISSUE TITLE
Improve ZeebePartition recovery time with large state

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13775]
**Description**

We had an incident where the liveness probes failed after 45s due to large state. This is a cluster with 3 partitions, each with a RocksDB state of over 7GB. For each partition, it took about 10 seconds purely to open the DB, which includes copying the snapshot and opening the DB. Furthermore, it seems like each partition was recovered sequentially and not in parallel, from the logs, but I haven't verified that.

The goal here would be to try and either optimize the recovery time, or have it not be w.r.t the size of the state (ideally the second one).

One issue which might be the biggest culprit in this case is this one: https://github.com/camunda/zeebe/issues/5682

**Comment by megglos** [comment]
ZDP-Triage:
- sequential partition recover prolongs startup
- such situations may require increasing the timeout for the liveness probe
- we need to double-check whether we disabled the WAL of rocksdb for all versions or just 8.2
- increased number of sst files due to partitoning is default in 8.3 => this may make it worse
- it raised the question if we aim to support such a large snapshot state
- on such snapshot sizes snapshot replication is also problematic

=> relates to the epic to support large state - maintaining consistent performance on larger states

**Comment by megglos** [comment]
realtes to another iteration on https://github.com/camunda/product-hub/issues/989

**Comment by remcowesterhoud** [comment]
Large state also proofs problematic for the Startup Probe.

```
Warning  Unhealthy  4m28s (x288 over 71m)  kubelet  Startup probe failed: HTTP probe failed with statuscode: 503
```

The snapshot size of the cluster is very large:
<img width="743" alt="image" src="https://github.com/camunda/zeebe/assets/5787702/c95535eb-da42-48b5-afa4-55ac6d18e74a">

The last log before the pod got killed:
```
RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Started receiving new snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/307189154-1021-698451241-698450032-1, snapshotStore=SnapshotStore-2, metadata=FileBasedSnapshotId{index=307189154, term=1021, processedPosition=698451241, exporterPosition=698450032}} from 1
```

My hypothesis is that receiving the snapshot takes longer than the startup probe has before it kills the pod, resulting in a startup loop.

**Comment by Zelldon** [comment]
I think in the incident above the snapshot replication was more the issue, and restarting of replications (due to pod restarts and due to new snapshots etc.). So we have multiple root causes which can have as a symptom that the broker is unable to start when the state is large.

**Comment by npepinpe** [comment]
Yeah, Remco and I talked about it, but still felt it was relevant to post here for now to highlight multiple issues with startup time and large state (even if the original issue also talks about liveness)

**Comment by megglos** [comment]
ZDP-Planning:
- initial issue was that partition startup was also sequential - this may be mitigated by parallel startup already (not intended to be backported), might be bound by IO limits then
- another case snapshot replication took a long time
- should be handled as part of the large state
- probe timeouts were increased to give more headroom (from 45s to 1m30s)
- would be worth assessing the risk for other customers and current prospects

=> just fixing recovery time might not be enough => we need to asses this in context of the epic https://github.com/camunda/product-hub/issues/1480

**Comment by npepinpe** [comment]
The issue we merged is related, but does not complete this.
