### ISSUE TITLE
Is there a way for us to know when Zeebe is about to trigger backpressure?

### ISSUE THREAD

**Issue by WlisonChan** [camunda/zeebe#13821]
We are loyal users of Zeebe. And as our business volume rapidly expands, we have encountered backpressure issues with Zeebe.

After Zeebe triggers backpressure, based on my understanding of the Vegas algorithm, the rejected requests go to line 229 of the code, causing the variable `newLimit` to decrease further, which creates a negative feedback loop that causes `newLimit` to become smaller and smaller. If we have a way to know when Zeebe is about to trigger backpressure, we can intercept the requests on the client side before Zeebe triggers it.

Regarding the above issue, we seek help from the author and the wider user community, and we are grateful!

<img width="843" alt="企业微信截图_c568fc57-ec1e-4d4f-adb6-f9d0b6156c02" src="https://github.com/camunda/zeebe/assets/54538165/4241f0d5-9e94-4fe6-af62-5eed79514205">

**Comment by deepthidevaki** [comment]
It is not currently possible to know this beforehand. You can get some information from the metrics. But this is not fast enough to help the client react to it. 

Please also note that we recently changed the default backpressure algorithm from [vegas to aimd](https://docs.camunda.io/docs/next/guides/update-guide/810-to-820/#changes-to-default-backpressure).

**Comment by WlisonChan** [comment]
Thank you very much for your answers. We have currently resolved the issue by using Zeebe's Prometheus backpressure monitoring.
