### ISSUE TITLE
Backoff on job worker poll even on success

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13846]
**Description**

Right now, when the job worker polls and receives a successful response, the back off delay is reset to the initial poll interval. Now that streaming is present, polling will only serve to back fill jobs which were created before any streams were registered.

To keep polling requests to a minimum, **if streaming is enabled**, we should also back off on poll success responses, _only if the response is empty_.

**Comment by basclaessen** [comment]
@npepinpe The backoffSupplier used to backoff job worker polls when streaming is the same backoffSupplier used to retry in case of a failed request.
When using the default backoffSuplier for example the job worker polls are executed every 5 seconds (+/- some jitter).
I would propose to keep the backoffSupplier only for failed requests (like mentioned in the javadoc) and change the implementation of the job worker poll backoff on success when streaming (this issue).
The implementation could contain a separate fixed backoff supplier or a specific backoff supplier the user can supply (using the builder or a spring bean).
Let me know what you think. I can create a PR with the implementation if needed.

**Comment by npepinpe** [comment]
That makes sense to me 👍 @megglos would be the person who makes those decisions around clients going forward though :)

**Comment by megglos** [comment]
@basclaessen your suggestions sounds good to me too, would appreciate if you can kick this off with a PR! Thank you for the initiative!

**Comment by basclaessen** [comment]
@megglos I created issue #44737 and pull request #44738 containing the java client implementation.
After the review I will create a PR containing the spring changes.
