### ISSUE TITLE
Build failed due to timeout on building docker image

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#13878]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once?
- Does it block your work? I guess it depends, how often it will happen now.
- Do we suspect that it is a real failure? Not sure.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

https://github.com/camunda/zeebe/actions/runs/5853503327/job/15867634706#step:39:488

<details><summary>Example assertion failure</summary>
<pre>
BuildKit version
Error: The operation was canceled.
</pre>
</details>

![buildtimeout](https://github.com/camunda/zeebe/assets/2758593/ed5ea4ab-9167-4364-89f1-e4ed910d80f6)

**Hypotheses**

Unclear.

**Comment by korthout** [comment]
```
Mon, 14 Aug 2023 08:26:40 GMT
  builder-b878ba93-bfc0-4da3-b7ec-4719196b879d0: v0.12.1
Mon, 14 Aug 2023 08:42:38 GMT
Error: The operation was canceled.
```

The runner seemed to have been stuck, or not doing anything and GitHub Actions then canceled the job through timeout.

@Zelldon ZPA doesn't think this is a flaky test, but infra instability. Since there are no additional logs to investigate, we'll close this.
