### ISSUE TITLE
Provide a cluster with a large state

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#13877]
## Description

When users want to do load-testing they often require a cluster with a large state. It takes time to build up this state on a cluster. It would be great if we could find a way to provide a large state on a cluster. This saves time for customers, but also helps when we want to test using a large state ourselves.

-----------

This issue was created as a follow-up to [this incident](https://app.incident.io/camunda/incidents/409).

**Comment by remcowesterhoud** [comment]
Individual triage:
- Workaround is putting some load on the cluster to create the data, this could take a while
- I think it would be very nice to have, especially to enable ourselves to test on large states. We may use it to make benchmarks more realistic as well.
- I don't see the ZPA team working on it in the near future. I will put it in the backlog and mark it as later.
- Also making it as large as it requires some designing on how we can do this.

**Comment by megglos** [comment]
ZDP-Triage:
- we could do that based on a backup 
- however for customers it may not be useful to have a `generic` large state => they may and we may care about the state particular to their processes etc.
- could be useful internally, we could create large states on demand with benchmarks - while take some hours to create though
- might be part of a related epic to optimize large state performance, but not useful in isolation
- considering this we would close this as `won't do`
