### ISSUE TITLE
Expose Zeebe cluster health

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#13876]
## Description

Currently, when one partition of Zeebe is unhealthy the entire cluster in marked as unhealthy in Console. Customer see this state and think their processing is halted. This is not true. Depending on the amount of partitions a cluster has processing can continue perfectly fine when one partition is down.

Zeebe knows best if It's unhealthy or not. We should introduce an endpoint for Console to call in order to determine the status of Zeebe.
I would propose the following values:
- **Healthy** (Everything is up and running, all partitions are healthy)
- **Degraded** (Some partitions are unhealthy. Processing is happening but at a reduced performance)
- **Unhealthy** (No processing is happening at all)

----------------

Created as an action of the post-mortem of [this incident](https://app.incident.io/camunda/incidents/409)

**Comment by megglos** [comment]
ZDP-Triage:
- we have a actuator endpoint to expose partition health
- gateway liveness indicates health already => it's healthy if there is at least one leader for one one partition
- could we make this part of the `/health` endpoint

**Comment by remcowesterhoud** [comment]
Individual triage:
- Seems to be in the Ready column for ZDP. It's not sensible to work on this simultaneously. Moving it to the ZPA backlog.
- Of course we're happy to help if necessary 🙂
