### ISSUE TITLE
How to adjust the Elasticsearch index extension to be split by month?

### ISSUE THREAD

**Issue by Lzqbest** [camunda/zeebe#13891]
**Description**

A clear and concise description of what this issue is about.

**Comment by remcowesterhoud** [comment]
Hi @Lzqbest! Let me verify that I understand you question correct.

The Elasticsearch Exporter creates its indexes as required. It does so on a daily basis. You are asking how to do this on a monthly basis instead.

I'm sorry to say that is not possible at the moment. There is no way to configure you Elasticsearch exporter to create indexes on a monthly basis. For things you can configure please refer to our [Elasticsearch exporter documentation](https://docs.camunda.io/docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter/).
