### ISSUE TITLE
Raft members can join and leave an existing cluster

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#13906]
Adding and removing members requires a configuration change of the cluster.

To change the members, Raft requires a  _joint consensus_ phase where everything needs to be committed by a quorum of the old _and_ the new configuration.

Some relevant snippets from the [Raft paper](https://raft.github.io/raft.pdf):

![Timeline of a configuration change](https://github.com/camunda/zeebe/assets/1379753/8b7465ac-526a-4079-a561-bc0d46293349)

> In order to ensure safety, configuration changes must use a two-phase approach.

> In Raft the cluster first switches to a transitional configuration we call joint consensus; once the joint consensus has been committed, the system then transitions to the new configuration. The joint consensus combines both the old and new configurations

> Agreement (for elections and entry commitment) requires separate majorities from both the old and new configurations

>  Once a given server adds the new configuration entry to its log, it uses that configuration for all future decisions (a server always uses the latest configuration in its log, regardless of whether the entry is committed).

```[tasklist]
### Support Joint Consensus
- [x] Extend `ConfigurationEntry` to remember old members
- [x] `LeaderRole` accepts `ReconfigureRequest` of new members
- [x] `RaftClusterContext` knows about joint consensus
- [x] `LeaderAppender` supports joint consensus
- [x] `RaftContext` ends joint consensus on commit
- [x] `ConfigurationRequest` propagates joint consensus configuration
```

```[tasklist]
### Making configuration changes
- [x] `RaftMember` can `join` partition
- [ ] `RaftMember` can `leave` partition
```

Because our raft layer does not replay the log, there is a small chance for committing but not applying configuration changes. This is deemed acceptable because while confusing, it does not cause an inconsistency.

**Comment by deepthidevaki** [comment]
> Problem 1 is that newly added members might take some time to catch up (they need to wait for snapshot replication and then all log entries). During this time, they cannot help the leader commit entries. During joint consensus, this might introduce unavailability. Since we are planning to limit ourselves to adding/removing only one member at a time, this is not necessarily a problem for Zeebe. If it were, we would need to make use of passive members which join as non-voting members first, replicate everything and are thus ready to join as active members immediately.

This would be relevant for Zeebe as well. It would be a nice improvement for a second iteration.

**Comment by Zelldon** [comment]
Thanks for writing this @oleschoenburg :) 

I was curious whether will also take a look at the old atomix code (which we mostly deleted but is still in the git history). I think atomix supported such config change before, at least I vaguely remember to deleted something like this 😅 


> The solution suggested by the Raft paper is to reject vote requests on members which received a valid leader heartbeat recently. We will need to check if this applies to Zeebe and if we need to implement this in the Raft layer or if this is already the case.

I guess this would also help in other cases where the leader only can't reach that specific node (avoid unnecessary disruptions), but might also be a double-edged sword because maybe there are cases when then a leader change didn't happen for a while where it would be better (not sure) 🤔

**Comment by oleschoenburg** [comment]
> I was curious whether will also take a look at the old atomix code (which we mostly deleted but is still in the git history). I think atomix supported such config change before, at least I vaguely remember to deleted something like this 😅

Yes, I looked at the PRs that removed support for leaving/joining a cluster:
https://github.com/camunda/zeebe/pull/6142 and https://github.com/camunda/zeebe/pull/6149

As far as I can tell, the old code is not very useful because it did not support a joint consensus phase.

**Comment by oleschoenburg** [comment]
As of now we have an open PR that adds support for raft members joining a cluster: https://github.com/camunda/zeebe/pull/14065

While this is being reviewed by @deepthidevaki and before adding support for _leaving_ a cluster, I'll focus on https://github.com/camunda/zeebe/issues/14085 to make sure that a broker can start a new partition at runtime.
The plan is to demonstrate that a broker can _start_ a new partition during runtime. This will allow us to find places in the broker where we assume that all partitions are know at startup and that now need to be changed to support a dynamically changing partition distribution. Until the topology module can orchestrate actual topology changes, adding a partition will be a manual, test-only operation.
Eventually we can circle back here and add support for raft members `leaving` a cluster. This should closely resemble  https://github.com/camunda/zeebe/pull/14065 and I don't expect major difficulties there.

Once we can join _and_ leave a cluster, we can also think about adding more tests for this. One idea here is to extend `RandomizedRaftTest` to occasionally add and remove members while continuously checking basic raft properties. This is easier to add once _leaving_ a cluster is also supported because otherwise we could only really test adding a couple of members before the test cluster becomes too large.

**Comment by oleschoenburg** [comment]
I've started implementing the `leave` part: https://github.com/camunda/zeebe/pull/14335.

# :warning: Summary In Progress 
One issue that I've discussed with @deepthidevaki today is what to do _after_ leaving a cluster. There are two concerns and then many scenarios which we have to consider.

## Concern 1: How to trigger shutdown

The easiest solution would be to wait for the leave request future to complete and then call shutdown. This is not ideal though because that would leave the partition manager in a state where it's holding onto a closed partition.


## Concern 2: What happens if shutdown doesn't happen

Suppose the raft member which left the cluster fails to shutdown, for example because it doesn't receive confirmation that the leave request was handled successfully. The raft member would then continue to run but not receive any heartbeats because the other members have already removed it. The member would then start to poll other members. The leader would reject the poll request because it is leader. But the other followers could accept the poll as long as the member's log is up to date.

I observed this happening in tests so we spent some time to understand how a member that has left the cluster could have an up to date log.
