### ISSUE TITLE
Integrate job worker streaming and metrics into benchmarks

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13914]
## Description

To ensure the stability of the new job push/streaming feature, we should integrate it into our long running benchmarks. This means updating the `Worker` application with the following features:

- [x] Configuration to enable streaming (i.e. call `JobWorkerBuilder#enableStreaming`)
- [x] Configuration for the stream timeout (default to 8 hours)

Let's enable streaming by default in future benchmarks as well to root out as many errors as possible, and because this is our desired end state. If we see it's too buggy, we can roll it back.

> **Note**
> When I prototyped this, I hit a bunch of performance issues with the `Worker` application itself. I don't know if this will happen again, but be wary of it.

Once https://github.com/camunda/zeebe/pull/13818 is merged, we should also:

- [x] Migrate `Worker` to use Micrometer + Prometheus (possibly migrate the `Starter` if it makes sense, since they share some code)
- [x] Enable job worker metrics
- [ ] Update the dashboard to visualize the job worker metrics

**Comment by rodrigo-lourenco-lopes** [comment]
PR https://github.com/camunda/zeebe/pull/13976 was only half of the issue, reopening this
