### ISSUE TITLE
Condition ignored on Inclusive Gateway with singular outgoing Sequence Flow

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#13936]
**Describe the bug**

It seems that an Inclusive Gateway with a single outgoing Sequence Flow ignores the Condition

<img width="974" alt="Screenshot 2023-08-17 at 09 52 07" src="https://github.com/camunda/zeebe/assets/3511026/57eb2d2d-8646-4947-b7c6-3aa05472521a">

The BPMN spec is quite clear about the expected behavior:

> A default path can optionally be identified, to be taken in the event that none of the conditional `Expressions` evaluate to `true`. If a default path is not specified and the **Process** is executed such that none of the conditional `Expressions` evaluates to `true`, a runtime exception occurs. - [10.6.3 Inclusive Gateway](https://www.omg.org/spec/BPMN/2.0.2/PDF#10.6.3%20Inclusive%20Gateway)

For C8, such a runtime exception should be represented by [an incident](https://docs.camunda.io/docs/next/components/concepts/incidents/) at the inclusive gateway.

Originally reported on the forums: https://forum.camunda.io/t/strange-behavior-with-only-one-sequence-flow-with-condition/46938

**To Reproduce**

- deploy a process with an inclusive gateway that has one outgoing sequence flow with the condition `= false`
- create an instance of it
- notice that the sequence flow is taken and that no incident is raised

**Expected behavior**

An incident is raised at the inclusive gateway

**Comment by korthout** [comment]
Mid severity, because there is a workaround: use two outgoing sequence flows - set the second one to `= false` and let it flow to a none end event

**Comment by lzgabel** [comment]
👋 Hi @korthout. Please assign this task to me. I'll take a look.
