### ISSUE TITLE
Build failed due to docker hub rate limiting

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#13947]
**Description**

Build on main failed https://github.com/camunda/zeebe/actions/runs/5892358015/job/15981438425#step:27:121

with:

```
  /usr/local/bin/docker pull tonistiigi/binfmt:latest
  Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Error: The process '/usr/local/bin/docker' failed with exit code 1
```

This was already observed before by @deepthidevaki on merging a PR https://camunda.slack.com/archives/C05DH1F5TAR/p1692282136978109

We might get throttled due to infra gha runners, [which might come all from the same IP](https://stackoverflow.com/a/76889883/2165134). 

Potential workaround https://www.project-piper.io/infrastructure/docker-rate-limit/

**Comment by koevskinikola** [comment]
ZPA triage:
- The Infra team might have resolved this already ([Slack msg src](https://camunda.slack.com/archives/C03AEFWGJ9K/p1692270413052689)). Let's see if the issue occurs again.
- @korthout confirms with Infra if the issue occurred before or after the changes were applied. If it happened before, the issue should be closed.

**Comment by megglos** [comment]
ZDP-Triage:
- backlog for now as ZPA looks into syncing with infra on this

**Comment by korthout** [comment]
Requested information from infra on [slack](https://camunda.slack.com/archives/C5AHF1D8T/p1693207891880329)

**Comment by korthout** [comment]
Infra [confirmed](https://camunda.slack.com/archives/C5AHF1D8T/p1693213935917919?thread_ts=1693207891.880329&cid=C5AHF1D8T) that their recent changes were made **before** the reported rate-limiting occurrence. 

Infra suggests we login to DockerHub before pulling an image to avoid the standard rate limits. I've [requested](https://camunda.slack.com/archives/C5AHF1D8T/p1693215861778599?thread_ts=1693207891.880329&cid=C5AHF1D8T) an account for this purpose.

**Comment by korthout** [comment]
Moving it back to inbox for triage now that the solution is clear
