### ISSUE TITLE
Add a test standalone broker class

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13968]
**Description**

> **Note**
> Blocked by #13966 

Based off of #13966, add a new class which allows launching a test instance of `StandaloneBroker`. This class should behave like any Spring application, with the following additions:

- [ ] Specify the `BROKER` profile as well
- [ ] Allow programmatic configuration via the `BrokerCfg` by injecting an `uninitializedBrokerCfg` bean
- [ ] Allow programmatic configuration of its working directory by injecting the `WorkingDirectory` bean
- [ ] Convenience method to add/remove exporters
- [ ] Convenience method to quickly register the `RecordingExporter`
- [ ] On construction, random ports should picked for the command and internal API, as well as the embedded gateway (even if it won't be enabled :shrug:)

Since the `StandaloneBroker` can also be a gateway, a common interface between this new class and the one for the gateway created by #13969 should be extracted, [something like this](https://github.com/camunda/zeebe/blob/99892d55658536ed2715b0790ac2257cbf7293c6/qa/util/src/main/java/io/camunda/zeebe/qa/util/cluster/TestGateway.java)

This interface should specify methods to:

- [ ] Provide a pre-configured client builder
- [ ] Await that the topology is complete
- [ ] A convenience method to await a single-node cluster topology is complete
- [ ] Modifying the underlying gateway configuration
- [ ] Obtaining the gateway address

See the hack day PR for an example: https://github.com/camunda/zeebe/blob/99892d55658536ed2715b0790ac2257cbf7293c6/qa/util/src/main/java/io/camunda/zeebe/qa/util/cluster/TestStandaloneBroker.java

**Comment by korthout** [comment]
@megglos This appears to be part of work that Zeebe Distributed Platform team is working on, but this issue is added to the Zeebe Process Automation team's project board. Is there something that is expected of us here?

**Comment by megglos** [comment]
apologies for the confusion will remove it from the ZPA board, see https://github.com/camunda/zeebe/issues/13969#issuecomment-1697430316
