### ISSUE TITLE
Add JUnit 5 extension to manage `AutoCloseable` resources

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13965]
**Description**

Add a new JUnit 5 extension in `test-util` which ensures that annotated static and instance fields in a test class will be closed once their respective test lifecycle is finished.

Optionally, the annotation for the fields should allow specifying a non standard close method. This would allow us to manage non-AutoCloseable resources, such as Atomix's `Managed` resources.

Three things should be produced here:

- [x] A `@AutoCloseResources` annotation, only targeting types, which will make sure any class annotated will be extended with the new extension.
- [x] A `@AutoCloseResource` annotation, which only targets fields, which will denote the resources to be managed. Optionally with a single string field called `closeMethod` (defaults to `close`.
- [x] A `AutoCloseResourcesExtension`, which implements both `BeforeAllCallback` and `BeforeEachCallback`. The extension should find all static fields annotated with `@AutoCloseResource`, and ensure they are closed when the test class is reaped. It should also find all instance fields annotated with `AutoCloseResource`, and ensure they're closed once the test is finished.

To hook into the extension lifecycle, simply create a new store for the extension in each callback. That store will then live for as long as the extension lifecycle. That means, if you create a store in `beforeAll`, then it will live for as long as the test class lives. If you create a store in `beforeEach`, then it will live for as long as the single test lives.

JUnit 5 supports storing `CloseableResource` instances into their store, and all these are closed when the store is reaped. So by wrapping the annotated field values into such a resource, we can ensure that they're properly closed as expected.

See the original hack day PR for an example: https://github.com/camunda/zeebe/blob/99892d55658536ed2715b0790ac2257cbf7293c6/test-util/src/main/java/io/camunda/zeebe/test/util/junit/AutoCloseResourceExtension.java

**Comment by korthout** [comment]
@megglos This appears to be part of work that Zeebe Distributed Platform team is working on, but this issue is added to the Zeebe Process Automation team's project board. Is there something that is expected of us here?

**Comment by megglos** [comment]
apologies for the confusion will remove it from the ZPA board, see https://github.com/camunda/zeebe/issues/13969#issuecomment-1697430316
