### ISSUE TITLE
Streams are not re-registered if a broker detects a gateway as failed but not vice-versa

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14002]
**Describe the bug**

Job streams reside purely in memory, on both the gateway and broker. This means job streams rely on the membership protocol to know when to re-open their streams. For example, if a broker is marked as dead, then comes back, a gateway will re-register its streams to it, assuming it was restarted (and not a false positive).

Similarly, when a broker detects a gateway as dead, it will remove its streams. This is done to avoid unnecessary job activation for streams with recipients that are potentially gone - if a gateway were to really restart, its connections to clients would have been severed, and when the clients would reopen the connections, it might be to a different gateway.

However, in the case of a false positive - a broker detects a gateway as gone, but it really wasn't - then the gateway never re-registers its streams to the broker, and the broker does not know of its streams, thus it will never forward jobs to it, creating clients that will end up starving.

**To Reproduce**

Here's a failing integration tests (to be added to `StreamIntegrationTest#LifecycleTest`):

```java
    @Test
    void shouldRegisterStreamsAgainInCaseOfAsymmetricPartition() {
      // given
      final var streamType = BufferUtil.wrapString("foo");
      final var properties = new TestSerializableData();
      final var streamId =
          clientStreamer
              .add(streamType, properties, p -> CompletableFuture.completedFuture(null))
              .join();
      awaitStreamAdded(streamType, streamId, server1, server2);

      // when - remove client from server's members, then add it back, and expect it to be
      // re-registered
      server1.streamService.event(
          new ClusterMembershipEvent(
              Type.MEMBER_REMOVED, client.cluster.getMembershipService().getLocalMember()));
      awaitStreamOnServer(streamType, server1, stream -> assertThat(stream).isEmpty());
      server1.streamService.event(
          new ClusterMembershipEvent(
              Type.MEMBER_ADDED, client.cluster.getMembershipService().getLocalMember()));

      // then
      awaitStreamAdded(streamType, streamId, server1, server2);
    }
```

**Expected behavior**

The gateway streams should be added back to the broker again, even if the failure was only visible from the broker's side.

**Comment by megglos** [comment]
ZDP-Triage:
- if it occurs it's hard to diagnose
- needs to be fixed for release of the feature (at least 8.4. at best already 8.3 as it may impact testing)
- broker needs to react on a gateway becoming available again
- workaround: restart the broker, but it's hard to detect to make that decision
