### ISSUE TITLE
Failed to write client request to partition X, because the writer is full

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#14003]
**Describe the bug**

This started occurring on our release-8-2-x benchmarks. The benchmark started having troubles at around 7am. This is at the same time the start and gateways restarted (multiple times). The problem got worse around 8:15 which is when the gateway and starter restarted again.

[Grafana](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=release-8-2-x&var-pod=All&var-partition=All&from=1692852757738&to=1692864277738)

<img width="1769" alt="image" src="https://github.com/camunda/zeebe/assets/5787702/e9fd0d81-5d4e-4adc-a12a-e3ef0616bcaf">.

In the logs we get the message:

```
Failed to write client request to partition '2', because the writer is full.
```

This message is thrown in the [ErrorResponseWriter](https://github.com/camunda/zeebe/blob/main/broker/src/main/java/io/camunda/zeebe/broker/transport/ErrorResponseWriter.java#L136) when an error `FULL` is received.
This `FULL` is only returned in 1 spot. This is in the [Sequencer](https://github.com/camunda/zeebe/blob/main/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Sequencer.java#L67-L113). It is thrown when we fail to offer a `sequenceBatch` to a `queue` (`queue.offer()` returns `false`).

Offering to a `Queue` only returns `false` if the `Queue` has reached capacity. This is also what the error message suggests. What confuses me is that we keep track of the size of this `Queue` in our metrics. Looking at these metrics I see at most 2 elements in the queue:
<img width="1779" alt="image" src="https://github.com/camunda/zeebe/assets/5787702/452d6797-b8cd-454d-9a06-bcb6bea1fcf7">

Potentially restarting the broker would resolve this, as it would empty the queue. I haven't tried as I want to keep the cluster in this state for any further analysations.

**To Reproduce**

No clue

**Expected behavior**

The queue doesn't get full, and if it does our metrics should reflect it properly.

**Log/Stacktrace**

[Logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22release-8-2-x%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22release-8-2-x%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22%20severity%3E%3DDEFAULT;cursorTimestamp=2023-08-24T05:10:13.623429089Z;startTime=2023-08-24T04:57:00.000Z;endTime=2023-08-24T05:13:00.000Z?hl=en&project=zeebe-io)

[Heapdump and data](https://drive.google.com/drive/folders/1jEq45iDUqyr00l0GecCxmv-vw9UtgM4o)

<details><summary>Full log entry</summary>
 <p>

```
{
  "insertId": "9afzatfqehc6c36t",
  "jsonPayload": {
    "message": "Failed to write client request to partition '2', because the writer is full.",
    "context": {
      "loggerName": "io.camunda.zeebe.broker.transport",
      "threadPriority": 5,
      "threadId": 21,
      "actor-scheduler": "Broker-2",
      "threadName": "zb-actors-2",
      "actor-name": "CommandApiRequestHandler"
    },
    "serviceContext": {
      "service": "zeebe",
      "version": "release-8-2-x"
    }
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      ...
    }
  },
  "timestamp": "2023-08-24T05:10:13.609543824Z",
  "severity": "DEBUG",
  "labels": {
    ...
  },
  "logName": "projects/zeebe-io/logs/stdout",
  "sourceLocation": {
    "file": "ErrorResponseWriter.java",
    "line": "144",
    "function": "raiseInternalError"
  },
  "receiveTimestamp": "2023-08-24T05:10:14.998700993Z"
}
```

</p>
</details>

**Environment:**
- OS: SaaS
- Zeebe Version: release-8-2-x benchmark

**Comment by remcowesterhoud** [comment]
I have restored the benchmark by stopping the starter, scaling down the workers (decreasing load) and restarting the brokers. After some time I scaled up the workers again and let them work through the backlog of jobs. Once they finished them all I restarted the starter.

**Comment by megglos** [comment]
ZDP-Triage:
- it's weird that it persisted for a long time
- might just be a symptom of the raft thread being blocked
- this error was hidden before 8.2 as this log only exists since then
- pulling into ready to investigate asap

**Comment by Zelldon** [comment]
I feel it might be related to #14275 and #14316, that we might run over our limits due to not good enough backpressure, likely to not be able to commit for shorter period of time and then filling the queues. 

I think we should fix #14316 and then close this.

**Comment by Zelldon** [comment]
With ZDB and the newest table feature https://github.com/Zelldon/zdb/pull/298

I was able to extract the log and make it easier to read https://docs.google.com/spreadsheets/d/1NDP3XeZjwGa9xjwTi870FwBiLOIImaOAbTfPR1W0wOo/edit#gid=1893174538


Interesting that there a huge batches of job timeouts and also fails which might have overwhelmed the brokers. We might need to investigate this further.

**Comment by oleschoenburg** [comment]
Here is the draft for removing the LogStorageAppender: https://github.com/camunda/zeebe/pull/11291

**Comment by deepthidevaki** [comment]
> @deepthidevaki please add the last thought you had on the sequencer limit vs. the external command backpressure limit

Sequencer limit is not aligned with the command backpressure limit. In this case, backpressure allowed the request but it could not write to sequencer. Ideally, they are more in sync.

**Comment by berkaycanbc** [comment]
Happened again:

* [GCP logs link (internal)](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CIHz29LzvayRhAE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-gateway-6c47587b6-c7549%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.container_name%3D%22zeebe-gateway%22%0Aresource.labels.namespace_name%3D%22a5005bd4-4617-449f-b6a9-b064125579f4-zeebe%22;cursorTimestamp=2024-01-29T15:39:15.701824960Z;startTime=2024-01-29T15:09:45.701Z;endTime=2024-01-29T16:09:45.701Z?project=camunda-saas-int-chaos)
* [GCP logs (internal)](https://drive.google.com/file/d/1CEnUDIVEGHpcA1ocxtxOt7wYUdTsFYUr/view)

**Comment by Farisagianda** [comment]
Happened as well in 8.4.4 causing client errors during high volume. Any suggestions on how to resolve this?

**Comment by npepinpe** [comment]
As we will not be backporting the log storage improvements, what can we do? There's [a related issue for the gateway](https://github.com/camunda/zeebe/issues/13018), and there we should handle the error better, i.e. returning `RESOURCE_EXHAUSTED` instead of `INTERNAL_ERROR`. 

Considering `RESOURCE_EXHAUSTED` should be handled by backing off, we could argue this would solve the issue of the full writer (though like with back pressure, this doesn't take into consideration internal load). Is there anything else we can do? It might be enough to return `RESOURCE_EXHAUSTED` for now?

**Comment by Zelldon** [comment]
@oleschoenburg is this fixed by your changes?

**Comment by oleschoenburg** [comment]
I'd argue it's fixed by https://github.com/camunda/zeebe/pull/18548
