### ISSUE TITLE
Should not activate link catch event in subprocess

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#14028]
**Describe the bug**

@philippfromme discovered that a link throw event can activate a link catch event inside an (event) subprocess. See the following process.  

![Screenshot from 2023-08-28 09-41-57](https://github.com/camunda/zeebe/assets/4305769/58753ebb-d565-4a25-86ab-e39e30023139)

According to the BPMN specification and the Camunda documentation, it should not be possible to activate a link catch event that is not in the same scope as the link throw event. Both events must be in the same scope.

This issue is kind of related to https://github.com/camunda/zeebe/issues/10854.

**To Reproduce**

1. Deploy the following process 
[link-event-subprocess.bpmn](https://github.com/camunda/zeebe/files/12452163/link-event-subprocess.bpmn.txt)
2. Create a new instance of the process
3. Verify that the link catch event is activated

**Expected behavior**

The link catch event inside the (event) subprocess is not activated.

The deployment of the process is rejected because there is no link catch event in the same scope.

**Log/Stacktrace**

<details><summary>Output from Zeebe-Play</summary>
 <p>

![Screenshot from 2023-08-28 10-22-54](https://github.com/camunda/zeebe/assets/4305769/cc3cbd5d-9e0e-4e7b-97b7-7645e9663265)

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: `8.2.0`
- Configuration:

**Comment by lzgabel** [comment]
Hi @saig0. You can assign this task to me and I'll take a look. :bow:

**Comment by saig0** [comment]
@lzgabel awesome. :rocket: Thank you for your engagement. :bow:
