### ISSUE TITLE
No longer move/copy snapshots

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14045]
## Description

Right now when we take snapshots we do that into a pending directory. If the snapshot is valid, meaning we reach a certain commit index OR we received all snapshot chunks, [we move (or copy depending on OS and filesystems) the snapshot to the valid snapshot directory](https://github.com/camunda/zeebe/blob/main/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java#L510).

Afterward, [we check the snapshot checksum](https://github.com/camunda/zeebe/blob/main/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java#L517) (for that we have to read the whole snapshot again). This is mostly due to the case that we might fall back to copy and some error appears during copying. Important to note is that we already validated the checksum on receiving each chunk and the complete snapshot.

What if we don't copy/move the snapshot from the pending, instead we directly write to the correct location? For that, we need a different marker when snapshots are valid. This could be a separate file, which marks the snapshot either as invalid (and removing it would mark it as valid) OR the existence of that file could mark it as valid. An example could be as soon as the checksum file exists the snapshot can be seen as valid.

### Impact

This would mean we have to add some more complexity in reading and detecting valid snapshots, but in contrast, we wouldn't need to copy/move snapshots (interesting for large states) and potentially don't need to recheck the checksums again.

### Context

When working on https://github.com/camunda/zeebe/issues/13977 and https://github.com/camunda/product-hub/issues/1480 we (@npepinpe and I) discussed several issues and potential improvements regarding snapshot replication and taking snapshots, etc.. One thing that came up was that we create checksums of the whole snapshot, of each chunk, and when persisting we recreate such checksums (re-read the snapshots, etc.)

**Comment by npepinpe** [comment]
@Zelldon - do you have time to work on it this week?

**Comment by Zelldon** [comment]
@npepinpe I can try, but can't promise since I also have two other issues assigned, game day, benchmark stuff etc. But I give my best :)

**Comment by npepinpe** [comment]
No worries. Let's sync later today to see what you can do this week.

**Comment by Zelldon** [comment]
I have run a benchmark to see what effects bring the most recent changes:

![snapshot-persist](https://github.com/camunda/zeebe/assets/2758593/671d3c38-c112-4f72-9cc0-93674f478336)

**Comment by Zelldon** [comment]
I started to replace the movement but realized that this was not straight-forward to do.

There was one thing that struck against it. It is the receiving of snapshots and where we expect multiple snapshots (and where we make directories unique) https://github.com/camunda/zeebe/blob/main/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java#L366-L372. It might happen that snapshot replication is restarted due some previous error/fault, then we want to write into a new directory.

Discussed this with @npepinpe To us it is not yet clear, why we not instead just remove the older snapshot and reuse the id or overwrite the snapshot. Since this would be part of improving the snapshot replication anyway we will defer this. We plan to make improvements like you can restart replicating snapshots at a certain position etc., which might help here as well.

After deciding that, I hoped to keep the move for the received snapshots and write the transient snapshots directly to the correct snapshot directory already. Unfortunately, it entails several further works, like detecting what is a valid snapshot (only with checksum), deleting pending snapshots (which would be now without checksum), etc.

I proposed and discussed with @npepinpe to continue with the snapshot replication improvements first, and then continue here to remove the movement. 

We already benefit from the improvements shown above https://github.com/camunda/zeebe/issues/14045#issuecomment-1709656377, not recalculating the checksums, which is likely most of the benefit we gain out of this right now anyway.

Still, it is right now weakening a bit the safety/verification, since we don't recalculate the checksum after the move. @npepinpe and I agreed that this is acceptable for now, with the plan to make rather soon progress with improving the replication and removing the move afterward.

**Comment by Zelldon** [comment]
Ok I couldn't hold back. If we would decided to just delete pending received snapshots (which would the easiest approach for now) we can go with the following PR https://github.com/camunda/zeebe/pull/14230 and can remove the move.
