### ISSUE TITLE
Under the zeebe cluster, dmn deployments generate duplicate decision requirement definition key.Is that normal?The test results show that 8.2.12 is normal

### ISSUE THREAD

**Issue by zxuanhong** [camunda/zeebe#14067]
**Describe the bug**
1. Under the zeebe cluster, dmn deployments generate duplicate decision requirement definition key.Is that normal?
![iShot_2023-08-31_11 26 56](https://github.com/camunda/zeebe/assets/62740686/69e0fe2b-6ce4-4e0f-9293-39f60502694d)
![iShot_2023-08-31_11 27 10](https://github.com/camunda/zeebe/assets/62740686/7d3135be-12e6-4c3b-b388-01c398346159)

2. How do I run the historical deployment decision information? Just like bpmn can start a specific version of the process.
3. The test results show that 8.2.12 is normal
![iShot_2023-08-31_11 24 03](https://github.com/camunda/zeebe/assets/62740686/971fad44-85dd-43f5-a24c-8f838a689640)
![iShot_2023-08-31_11 24 16](https://github.com/camunda/zeebe/assets/62740686/f3a34710-d67e-4a29-bda8-584d578c81f9)
[demo.dmn.zip](https://github.com/camunda/zeebe/files/12481931/demo.dmn.zip)

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS:  mac
- Zeebe Version:   [8.3.0-alpha4](http://localhost:9000/#!/2/docker/images/camunda~2Fzeebe%3A8.3.0-alpha4)

**Comment by lzgabel** [comment]
:wave: Hi @zxuanhong. Thanks for raising this! :heart: For more details, see here: https://github.com/camunda/zeebe/issues/13980#issuecomment-1689451937 
BTW, This issue is fixed in this PR: https://github.com/camunda/zeebe/pull/13986

**Comment by korthout** [comment]
Thanks for reporting @zxuanhong and @lzgabel for looking into it already.

We also expect that this is already resolved with 8.3.0-alpha5. Please let us know if you encounter this still after upgrading.
