### ISSUE TITLE
Support ZEEBE_GATEWAY_ADDRESS as new env var to connect with a Zeebe cluster

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14126]
**Description**

Right now we support `ZEEBE_ADDRESS` which is one of the oldest env var we support, and historically grown. In order to align our terminology and applications across the stack we should support `ZEEBE_GATEWAY_ADDRESS` and deprecate `ZEEBE_ADDRESS`.

See related docs PR https://github.com/camunda/camunda-platform-docs/pull/2518 
See related google doc https://docs.google.com/document/d/10wZ6eMszqJHEsVbprdjaC1A-vcqoxANwaMpnwGkjE8I/edit. Especially [this part](https://docs.google.com/document/d/10wZ6eMszqJHEsVbprdjaC1A-vcqoxANwaMpnwGkjE8I/edit)
See related github issue: https://github.com/camunda/camunda-platform-docs/issues/1662

**Comment by Zelldon** [comment]
Yeah for one or two versions I guess.

**Comment by dipeshsingh253** [comment]
Hello @Zelldon , I would like to work on this issue. But I am a little confused (sorry this might be a very noob doubt). I went through: https://docs.camunda.io/docs/next/apis-tools/java-client/

and in the source code: https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientBuilderImpl.java#L281

So as we can see the source code is accepting a string as a gateway address and in the docs we are using this code block : 
```java
ZeebeClient client =
    ZeebeClient.newClientBuilder()
        .gatewayAddress(System.getenv("ZEEBE_ADDRESS"))
        .build();
```
so I don't see anything related to env var in the source code at all. for example, if I create an env var MY_GATEWAY_ADDR = "gateway address". and pass it in the above code block it will work fine, right ? Or there is any validation for that? 

Once again, I am very new to open source, sorry if this sounds foolish but that was my doubt.

Thanks in advance !!!
