### ISSUE TITLE
zeebe running with relatively high idle CPU load

### ISSUE THREAD

**Issue by amalzahn** [camunda/zeebe#14187]
**Is your feature request related to a problem? Please describe.**
Zeebe has a relatively high CPU load when idle. With no processes or clients running it uses in our test installation 10% CPU. It is running in docker, 'docker run camunda/zeebe:8.2.12'. The CPU is used by 4 actor threads (ActorThead.java), each of them around 2.5% CPU. As our application runs not many processes (maybe 1-10 per day) this waists resources.

**Describe the solution you'd like**
In ActorThread.java the ActorTaskRunnerIdleStrategy is initialized with:
BackoffIdleStrategy(100, 100, 1, TimeUnit.MILLISECONDS.toNanos(1));
Therefore the ActorThread will poll for work in 1ms interval causing the CPU load.
Can all parameters or only the last parameter for BackoffIdleStrategy() be configured in environment variables of the docker image? Then we can set e.g. a 100ms polling intervall which should use 100 times less CPU.

**Describe alternatives you've considered**
Setting variables ZEEBE_BROKER_THREADS_CPUTHREADCOUNT and ZEEBE_BROKER_THREADS_IOTHREADCOUNT to 1 causes half the CPU load, but having only 1 thread in each pool does not sound right.

**Additional context**
Consider a higher the default value of the polling interval. As probably many zeebe instances are running with defaults, you can save a lot of CPU load, power consumtion and the climate!
And for production recommend the current  low interval.

**Comment by npepinpe** [comment]
It probably wouldn't hurt too much to have a default higher value in general. Whenever new work is submitted to the task, we will wake up the thread anyway (if, for example, it was parked). The one caveat is for timer tasks, as these cannot wake up the thread. So if you set the parked time to 100ms, for example, then you could miss low timeouts by 100ms.

But we could probably already increase it to 10 or even 20ms :+1:

**Comment by npepinpe** [comment]
A quick test with 20ms as the park timeout showed no noticeable performance difference on medium and high throughput, and a 1-3% (constantly fluctuating) CPU usage by the java process. So we can definitely increase this value I think.

Making it configurable is a helpful to tweak, but I don't know how useful it is in the long term - I suspect we can find a good general value for most users :shrug: Though having it configurable definitely helps in running various benchmarks :smile:

**Comment by npepinpe** [comment]
You can see in this screenshot when it flattens, this is when the system is idle:

![image](https://github.com/camunda/zeebe/assets/43373/65970f7a-9d6d-46e5-9dc9-e52d7023f24a)

And this is the normal system on idle, with a 1ms park time instead of 20ms:

![image](https://github.com/camunda/zeebe/assets/43373/45c2b6e3-4239-4bb2-9aaa-0c719c398bbe)

It's a bit hard to see, but difference is that with 1ms, CPU usage is 0.04, and with 20ms, it's 0.01-0.02, so halved. And I believe the only downside is that you risk a 20ms added delay on your timers - of course, assuming your clock is fine grained. A coarse grained clock may be sleeping for me, but then it'd also be sleeping for longer than 1ms :smile:

**Comment by amalzahn** [comment]
i guess when the threadcount is increased the low intervall will actually decrease zeebe performace as the idle threads will consume CPU load. So this intervall should be made configurable to adjust to different usecases. Maybe also different intervals for CPU and IO threads so you can have a lower interval with the timer tasks and a higher on the other. A different IdleStrategy without spinning may also increase performance with many threads, but I'm no expert here.
This is not our usecase, but I imagine some users will increase thread count.

**Comment by Zelldon** [comment]
Triage:

 * related https://github.com/camunda/zeebe/issues/4231
 * @npepinpe wants to do it!
