### ISSUE TITLE
The C8 Helm chart is expanded with gateway configuration flag for multi-tenancy

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14307]
The gateway now has a new configuration flag to enable multi-tenancy:
- `zeebe.gateway.multiTenancy.enabled`
- `zeebe.broker.gateway.multiTenancy.enabled`

The helm charts must be updated: https://github.com/camunda/camunda-platform-helm
Related: https://github.com/camunda/distribution/issues/61

**Comment by abbasadel** [comment]
I will take over this issue and reach out to the SRE team and see what I can do. Any hint is appreciated. 🙏🏼

**Comment by abbasadel** [comment]
PR in https://github.com/camunda/camunda-platform-helm/pull/890
