### ISSUE TITLE
Latency metrics should support a wider range of values

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14333]
Our processing latency metrics such as _Job Activation Time_, _Process Instance Execution Time_ and probably many more use buckets up to 10 seconds, the default for the metrics library we use.
Especially metrics that are ultimately influenced by users, 10 seconds is too limiting. Instead, we should use exponentially increasing buckets. For example, _Process Instance Execution Time_ should probably range from ~5ms to days or even more.

**Comment by megglos** [comment]
ZDP-Triage:
- especially metrics that are out of our control are prone to go beyond 10s, like job execution time but also naturally larger like instance execution time
- easy pick to adjust the metrics, a couple of buckets more should not have a significant impact
- would make sense to revisit all metrics to identify some more candidates to adjust
