### ISSUE TITLE
Actor scheduler is not running on installing partition

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14355]
**Describe the bug**
Error group https://console.cloud.google.com/errors/detail/CLib24_Bn4TaqwE;service=zeebe;time=P7D?project=camunda-cloud-240911

[Happend on two partitions: ](https://console.cloud.google.com/logs/query;query=error_group%2528%22CLib24_Bn4TaqwE%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.namespace_name%3D%2203afa218-e618-42f4-808b-3283e4a98c2f-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2023-09-19T00:56:00.347731944Z%2Fbpg45u1bg0rivww1;cursorTimestamp=2023-09-19T00:56:00.347732239Z;startTime=2023-09-19T00:26:30.347Z;endTime=2023-09-19T01:26:30.347Z?project=camunda-cloud-240911)

ERROR 2023-09-19T00:56:00.347731944Z [resource.labels.containerName: zeebe] Failed to start partition 2
ERROR 2023-09-19T00:56:00.347732239Z [resource.labels.containerName: zeebe] Failed to start partition 3

1. [First shutdown of node zeebe-2 ](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.namespace_name%3D%2203afa218-e618-42f4-808b-3283e4a98c2f-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2023-09-19T00:53:51.614720028Z%2Ffxfcmu977v3sbr0j;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2023-09-19T00:53:51.685226814Z;startTime=2023-09-19T00:26:30.347Z;endTime=2023-09-19T01:26:30.347Z?project=camunda-cloud-240911) 2023-09-19 02:53:51.614 CEST
2. [Start up of node shortly after](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.namespace_name%3D%2203afa218-e618-42f4-808b-3283e4a98c2f-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2023-09-19T00:55:48.032674120Z%2Ffdrcgmgfzxoez35n;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2023-09-19T00:55:54.951098658Z;startTime=2023-09-19T00:26:30.347Z;endTime=2023-09-19T01:26:30.347Z?project=camunda-cloud-240911) 2023-09-19 02:55:48.032 CEST
3. Closing [again](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.namespace_name%3D%2203afa218-e618-42f4-808b-3283e4a98c2f-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2023-09-19T00:55:58.973233304Z%2Fg2l1slfkyg1bkom1;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2023-09-19T00:55:59.241555305Z;startTime=2023-09-19T00:26:30.347Z;endTime=2023-09-19T01:26:30.347Z?project=camunda-cloud-240911) 2023-09-19 02:55:58.973
4. Shutdown [complete](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.namespace_name%3D%2203afa218-e618-42f4-808b-3283e4a98c2f-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2023-09-19T00:56:00.037427592Z%2Fpvbx6opdvpik8c4s;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2023-09-19T00:56:00.347732239Z;startTime=2023-09-19T00:26:30.347Z;endTime=2023-09-19T01:26:30.347Z?project=camunda-cloud-240911) (still partition starting on-going). 2023-09-19 02:56:00.037 CEST
5. [Closing actor schedule and failure on partition install ](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.namespace_name%3D%2203afa218-e618-42f4-808b-3283e4a98c2f-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2023-09-19T00:56:00.347731944Z%2Fbpg45u1bg0rivww1;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2023-09-19T00:57:39.845182165Z;startTime=2023-09-19T00:26:30.347Z;endTime=2023-09-19T01:26:30.347Z?project=camunda-cloud-240911) 2023-09-19 02:56:00.347 CEST

**To Reproduce**
I guess try to shutdown the node, fast enough.

**Expected behavior**
No race conditions with closing and opening.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Actor scheduler is not running
	at io.camunda.zeebe.scheduler.ActorScheduler.checkRunningState(ActorScheduler.java:66) ~[zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorScheduler.submitActor(ActorScheduler.java:54) ~[zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorScheduler.submitActor(ActorScheduler.java:32) ~[zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.broker.partitioning.PartitionStartup$BootstrapActor.startZeebePartition(PartitionStartup.java:124) ~[zeebe-broker-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.broker.partitioning.PartitionStartup$BootstrapActor.lambda$onActorStarted$2(PartitionStartup.java:105) ~[zeebe-broker-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:75) ~[zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) ~[zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.3.0-alpha6 
- Configuration:

**Comment by Zelldon** [comment]
This might be a regression from the partitioning refactoring \cc @oleschoenburg I think we should look into it sooner, since we still have momentum here.

**Comment by Zelldon** [comment]
A related error was reported:

**Comment by oleschoenburg** [comment]
This happened on alpha6 which used a `BootstrapActor`. On SNAPSHOT this is (again) refactored a bit and works differently now (using the `StartupProcess`). Unless we see this again on SNAPSHOT I'd close this issue as "Won't fix".
