### ISSUE TITLE
Replace usage of any Zeebe container in tests unless necessary

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14377]
## Description

The goal here is to replace unnecessary usage of container based tests with the new testing infrastructure.

Any tests which rely on specific network configurations (e.g. isolated network stack), on volumes, on older versions, should remain container based.

But the following can be migrated:

- [x] S3RestoreAcceptanceIT
- [x] GatewayAuthenticationIdentityIT
- [x] BrokerMonitoringEndpointTest
- [x] ControlledActorClockEndpointIT
- [x] S3BackupAuthenticationIT - cannot be migrated because it relies on AWS picking up isolated environment credentials via `System.getenv()` :(
- [x] SnapshotWithExportersTest
- [x] GatewayGrpcHealthIT
- [x] S3BackupAcceptanceIT
- [x] FixedPartitionDistributionIT
- [x] LongPollingIT
- [x] BanningEndpointIT
- [x] ExportingEndpointIT
- [x] RebalancingEndpointIT
- [x] AdvertisedAddressIT (local nodes can use Toxiproxy as well)

**Comment by megglos** [comment]
ZDP-Triage:
- already in progress, would be great for multiple engineers to contribute and get familiar with the new setup

**Comment by npepinpe** [comment]
For the last one - `SnapshotWithExporters` - we need functionality to acknowledge or not on demand from the exporter pov. We can either:

1. Add this to the RecordingExporter
2. Integrate `zeebe-test-container` 's debug exporter here, which is more flexible (and, may I add, fully isolated ;))
