### ISSUE TITLE
How to implement object mapping with input parameter mapping while adding attributes to the object

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#14387]
var user = {"name":"Tom"}
input mapping 
source      target
user           tempUser
10              tempUser.age
If you configure tempUser in this way, it looks like this。
{"age":10}
How to configure such tempUser data if needed
{
  "name": "Tom",
  "age": 10
}

**Comment by nicpuppa** [comment]
Hi @bugbugmaker, for questions like these, it is always better to open a help request on the Camunda forum:[https://forum.camunda.io/](https://forum.camunda.io/). 
By posting on our forums, you will benefit from the experience of Camunda experts and the whole Camunda community.
