### ISSUE TITLE
Migration could result in inconsistent data on rolling update

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#14406]
**Describe the bug**

Kudos to @romansmirnov for identifying this issue!

With https://github.com/camunda/zeebe/issues/13763, already executed migration tasks are marked as finished in the runtime state, to avoid rerunning already executed migrations with every restart.

This can lead to inconsistent states of snapshots across the brokers when a rolling update is performed. This is due to the fact that during the update brokers running an old version of zeebe are create a different state when replaying events than it would be the case when running the new version already.

**To Reproduce/Scenario**

_Given_
With 8.3 a new column family `PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY` has been introduced. It maps a process instance key to its process definition. This new column family is used when trying to delete a process definition. However, in 8.2 that specific column family `PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY` does not exist.

_When_
The user upgrades from 8.2 to 8.3, and the upgrade happens in a rolling update manner, broker by broker.

During that update, it may happen that a broker `x` (already updated to 8.3) will replicate a (already migrated) snapshot `s1` to a broker `y` which is still on version 8.2.

As the snapshot `s1` was already migrated by broker `x`, it contains an entry marking the migration task as finished.

After broker `y` installed the received snapshot `s1`, it will start to replay the events.

While replaying, it won't put anything into the column family `PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY` because broker `y` is still running the previous version where this column family didn't exist.

In the meantime, broker `y` takes a new snapshot `s2`. Eventually, broker `y` gets updated to 8.3

_Then_
, it will recover from snapshot `s2` but it won't run the migration task anymore because the respective migration task was already marked as finished in snapshot `s1`. Thus the snapshot state of broker `y` will not be consistent with the one of broker `x`. If broker `y` eventually becomes leader, the corrupted state will be used going forward.

**Expected behavior**

Migrations must be executed in a way to ensure all brokers have eventually a consistent snapshot state.

**Environment:**
- OS: 
- Zeebe Version: 8.3.x
- Configuration:

**Comment by megglos** [comment]
Thread with further discussions https://camunda.slack.com/archives/C037W9NMATG/p1695618000621469

**Comment by megglos** [comment]
ZDP-Planning:
- following-up with the ZPA team next if they have capacity in the next week

**Comment by korthout** [comment]
@remcowesterhoud I think we can close this issue right?

**Comment by remcowesterhoud** [comment]
Yes we can
