### ISSUE TITLE
ReconfigurationTest$Leaving.shouldReduceQuorumSize(Path) unstable

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14405]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once on main
- Does it block your work? not yet
- Do we suspect that it is a real failure? Likely

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

See https://github.com/camunda/zeebe/actions/runs/6262742342/job/17005640273

<details><summary>Example assertion failure</summary>
<pre>
 Completion io.atomix.primitive.PrimitiveException$Unavailable: Configuration failed
</pre>
</details>

**Hypotheses**

Haven't looked into it yet.

> List any hypotheses if you have one; can be ommitted

**Logs**
[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/12686144/Test.results.for.unit.tests.zip)

**Comment by oleschoenburg** [comment]
This can happen when a leave request is sent while the leader is not ready to reconfigure yet (e.g. it hasn't committed it's initial entry yet).
I'll improve the error message and ensure that we retry the `leave` request in these cases.
