### ISSUE TITLE
How to format the data returned by the now function into this yyyy MM dd HH: mm: ss format for FEEL-EXPRESSION

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#14489]
How to format the data returned by the now function into this yyyy MM dd HH: mm: ss format for FEEL-EXPRESSION

**Comment by Aniket-kumar404** [comment]
How to format the data returned by the now function into this yyyy MM dd HH: mm: ss format  by the help of


"java.text.SimpleDateFormat" class. 

This class is used to both parse and format dates according to a formatting pattern that we specify ourself.
When parsing dates, the Java SimpleDateFormat typically parses the date from a Java String. When formatting dates, the SimpleDateFormat typically formats a Date object into a String, although it can also format the date into a StringBuffer.


For Instance:
String pattern = "EEEEE dd MMMMM yyyy HH:mm:ss.SSSZ";
SimpleDateFormat simpleDateFormat =
        new SimpleDateFormat(pattern, new Locale("da", "DK"));
String date = simpleDateFormat.format(new Date());

**Comment by berkaycanbc** [comment]
A short answer: you can extract date and time from `now()` using `date(now())` and `time(now())`.
 
@bugbugmaker Please consider asking such questions in the forum [https://forum.camunda.io/c/camunda-platform-8-topics/40](https://forum.camunda.io/c/camunda-platform-8-topics/40), you should get answers faster there.

Closing this as I assume you now received the answer. Please re-open the issue if you think this is a bug.
