### ISSUE TITLE
Adjust event-based gateway validation to allow attached signal catch event

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14487]
It seems we forgot to adjust the event-based gateway validation to allow attaching signal catch events.

https://github.com/camunda/zeebe/blob/0ddd72ddd198649ea908e6c381ceea0b46186b04/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/EventBasedGatewayValidator.java#L36-L40

This means that we reject the deployment of processes with a signal catch event attached to an event-based gateway currently.

>ERROR: Event-based gateway must not have an outgoing sequence flow to other elements than message/timer intermediate catch events.

<details><summary>Example testcase</summary>
<p>

```java
@Test
public void shouldTriggerSignalCatchEventAttachedToEventBasedGateway() {
  // given
  final var process =
      Bpmn.createExecutableProcess(PROCESS_ID)
          .startEvent()
          .eventBasedGateway("eventbased")
          .intermediateCatchEvent(ELEMENT_ID)
          .signal(SIGNAL_NAME)
          .endEvent()
          .moveToLastGateway()
          .intermediateCatchEvent()
          .timerWithDuration(Duration.ofMinutes(10))
          .endEvent()
          .done();

  ENGINE.deployment().withXmlResource(process).deploy();

  final var processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID).create();

  assertThat(
          RecordingExporter.signalSubscriptionRecords(SignalSubscriptionIntent.CREATED)
              .withSignalName(SIGNAL_NAME)
              .exists())
      .isTrue();

  // when
  signalClient.broadcast();

  // then
  assertThat(
          RecordingExporter.processInstanceRecords()
              .withProcessInstanceKey(processInstanceKey)
              .limitToProcessInstanceCompleted())
      .extracting(r -> r.getValue().getElementId(), Record::getIntent)
      .containsSubsequence(
          tuple(ELEMENT_ID, ProcessInstanceIntent.ELEMENT_COMPLETING),
          tuple(ELEMENT_ID, ProcessInstanceIntent.ELEMENT_COMPLETED),
          tuple(PROCESS_ID, ProcessInstanceIntent.ELEMENT_COMPLETING),
          tuple(PROCESS_ID, ProcessInstanceIntent.ELEMENT_COMPLETED));
}
```

</p>
</details>

**Comment by korthout** [comment]
@lzgabel Is this something you're willing to pick up?

**Comment by lzgabel** [comment]
💯 @korthout. Please assign this task to me. Thanks.

**Comment by abbasadel** [comment]
Hi @lzgabel, thanks again for all your contributions and the great work you did in signal catch events ❤️ 

Just wanted to point out that we are going to have a code freeze tomorrow 6PM CET for the upcoming release and it would be great if we could have this last PR part of the next release. 

If this does not fit your schedule, just let us know and we will take care of it.
