### ISSUE TITLE
Switch to 8.3.0 release of Identity SDK

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14499]
To add support for multi-tenancy over Identity, we're currently depending on unreleased features of the Identity SDK, i.e. `8.3.0-alpha6`.

Before releasing 8.3.0, we should update this dependency to `8.3.0`.

**Comment by korthout** [comment]
https://github.com/camunda/zeebe/blob/ad11ffad83552783335a72f025bb5abf1dfdbd3b/parent/pom.xml#L62

**Comment by abbasadel** [comment]
This should happen automatically during the release process. Let's keep this issue until we get done with the release

**Comment by megglos** [comment]
To not delay any investigations if the CI may become unstable we could already do that by running the update action manually https://github.com/camunda/zeebe/actions/workflows/update-identity.yml targeting the release branch.

Wdyt @abbasadel @korthout ?

**Comment by megglos** [comment]
On the [dependabot PR to update to the new identity release on main](https://github.com/camunda/zeebe/actions/runs/6401359773/job/17376337191?pr=14585) we already have test issues

**Comment by megglos** [comment]
I will change the dependabot PR to point to the release branch to check if the issue occurs there too, if so we can look into resolving it.

**Comment by remcowesterhoud** [comment]
Closing this as the version is set in the release branch, which needs to be merged back anyways.
