### ISSUE TITLE
Allow using the default tenant even when no tenant associated to requester

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14497]
All clients should be able to use the default tenant. Even the client is not associated to any tenants in Identity.

```java
@Test
@Disabled("Not yet supported: https://github.com/camunda/zeebe/issues/14497")
void shouldDenyDeployProcessWhenNoTenantAssociated() {
  // given
  try (final var client = createZeebeClient(ZEEBE_CLIENT_ID_WITHOUT_TENANT)) {
    // when
    final Future<DeploymentEvent> result =
        client.newDeployResourceCommand().addProcessModel(process, "process.bpmn").send();

    // then
    assertThat(result)
        .describedAs("Expect that process can be deployed for the default tenant")
        .succeedsWithin(Duration.ofSeconds(10));
  }
}
```

**Comment by remcowesterhoud** [comment]
We shouldn't implement this, details https://camunda.slack.com/archives/C05Q0EXE9V4/p1696235964583069

**Comment by korthout** [comment]
For those reading this and wonder what's in the internal slack thread:

The use-case would be:
- Team A utilized a 8.2 cluster
- They want to onboard Team B on the same cluster
- They update to 8.3, activate MT, all their data is owned by the default (`<default>`) tenant
- Team B should not be able to see data from Team A that already used the cluster, so they should not be able to access the default tenant
- This can be configured explicitly in Identity
