### ISSUE TITLE
NPE in `PendingMessageSubscriptionChecker`

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14588]
**Describe the bug**

There appears to be a race condition in the `PendingMessageSubscriptionChecker`. It can run concurrently to the stream processor, where the two access a shared in-memory state (aka transient state). Access to this state is threadsafe, but not spread over multiple calls.

The race condition appears to exist here: The entries are first retrieved from the transient state, before we `get` the subscription from the persisted state. The transient state may have been modified before, leading to both states not being in-sync.

https://github.com/camunda/zeebe/blob/d928ba2ed6321b3e613320e9c7fcdd0bc0decc44/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageSubscriptionState.java#L229-L236

**To Reproduce**

This may be hard to reproduce, as it's a race condition. It may be possible to set up by calling the associated method in a specific order where the order can be controlled.

**Expected behavior**

The checker should be able to run concurrently to the stream processor without issues.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.message.MessageSubscription.getRecord()" because "subscription" is null
    at io.camunda.zeebe.engine.processing.message.PendingMessageSubscriptionChecker.sendCommand(PendingMessageSubscriptionChecker.java:36) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
    at io.camunda.zeebe.engine.state.message.DbMessageSubscriptionState.visitPending(DbMessageSubscriptionState.java:253) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
    at io.camunda.zeebe.engine.processing.message.PendingMessageSubscriptionChecker.run(PendingMessageSubscriptionChecker.java:32) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
    at io.camunda.zeebe.stream.api.scheduling.SimpleProcessingScheduleService.lambda$runAtFixedRate$0(SimpleProcessingScheduleService.java:35) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
```

</p>
</details>

[Link to log](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-10-02T13:01:28.455354092Z;endTime=2023-10-02T14:54:41.744537Z;query=error_group%2528%22CKOmuvKMwLOtvAE%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.namespace_name%3D%2228dc004a-c9eb-4ee4-bd43-122d19470705-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Atimestamp%3D%222023-10-02T13:01:28.455354092Z%22%0AinsertId%3D%22t5z8oevltfufcaqu%22;startTime=2023-10-02T12:54:41.744Z?project=camunda-saas-int-chaos)

**Comment by korthout** [comment]
We don't consider this to be a blocker for the 8.3.0 release.

- The cluster recovered after the leader, that encountered the NPE, stepped down. The new leader did not run into the same race condition.
- The race condition has already been around since 8.3.0-alpha3, and did not occur in our extensive testing. It's a rare occurrence.
- Lastly, users that do run into this too often can disable the checker from running concurrently to stream processor by setting `zeebe.broker.processing.enableAsyncScheduledTasks: false`. This will completely mitigate this issue.

Having said that, this issue is high severity as it disrupts regular processing, causing a drop in availability.

**Comment by korthout** [comment]
It's possible that this is similar to this issue for timers:
- https://github.com/camunda/zeebe/issues/13598

**Comment by berkaycanbc** [comment]
@korthout do you think we can move this one to ready so that it can be picked up? I can take a look at it.

**Comment by berkaycanbc** [comment]
We can add a null check and log that subscription removed from the state if it is not found. Since message subscription record either correlated or deleted from the state, it should be safe to skip that record. WDYT? @korthout
