### ISSUE TITLE
Zeebe doesn't reconnect to hazelcast if the hazelcast pod restarts

### ISSUE THREAD

**Issue by shahamit** [camunda/zeebe#14589]
**Describe the bug**

We are deploying zeebe version 8.2.12 on kubernetes cluster through helm. We have a one node zeebe broker along with elasticsearch and hazelcast exporters. Hazelcast is deployed as a standalone cluster with one pod. 

If the hazelcast pod crashes and automatically restarts, zeebe broker does not re-establish the connection to the hazelcast cluster. We had to restart zeebe too for the hazelcast connection to be established

**To Reproduce**

1. Deploy hazelcast as a standalone one pod cluster
2. Deploy zeebe with elasticsearch and hazelcast as exporters.
3. Delete the hazelcast pod to reproduce the issue simulating an error like OOM
4. Hazelcast pod should be recreated by kubernetes
5. View the zeebe logs to see that zeebe has lost the connection to hazelcast

**Expected behavior**

Zeebe should re-establish the connection to hazelcast if hazelcast cluster restarts

**Environment:**
- OS: Linux
- Zeebe Version: 8.2.12
- Hazelcast Version - 5.3.2

**Comment by npepinpe** [comment]
Hi @shahamit, this sounds like a resilience issue with the Hazelcast exporter which does not reconnect once the external Hazelcast is down.
