### ISSUE TITLE
Corrupted snapshot with empty checksum file 

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#14594]
**Describe the bug**

Before restart 
```
INFO 2023-09-29T17:15:27.761440072Z Committed new snapshot 83963263-7-721140446-721041977
DEBUG 2023-09-29T17:15:27.762075175Z Deleting previous snapshot 83914148-7-720621193-720600203
DEBUG 2023-09-29T17:15:27.764267075Z raft-partition-partition-3 - Deleting log up from 83911728 up to 83956125 (removing 9 segments)
````
Shortly after committing the snapshot, the pod was restarted. After restart
```
Expected snapshot /usr/local/zeebe/data/raft-partition/partitions/3/snapshots/83963263-7-721140446-721041977 to have checksum 0, but the actual checksum is 124239095; the snapshot is most likely corrupted. The startup will fail if there is no other valid snapshot and the log has been compacted.
```
Looks like checksum file was not flushed when committing the snapshot.

**To Reproduce**

No idea.

**Log/Stacktrace**

[link to logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-y-2023-cw-39-706f1b0-benchmark%22%0Aresource.labels.pod_name%3D%22medic-y-2023-cw-39-706f1b0-benchmark-zeebe-0%22%0A%2283963263-7-721140446-721041977%22;pinnedLogId=2023-09-29T17:15:27.761440072Z%2Fbd7dtxklwy3vobo9;cursorTimestamp=2023-10-02T01:33:09.499778768Z;duration=P7D?project=zeebe-io)

**Environment:**
- Zeebe Version: medic-cw-39 benchmark

**Comment by deepthidevaki** [comment]
Possible related to https://github.com/camunda/zeebe/issues/14486 The error is observed in a version before this is fixed.

**Comment by megglos** [comment]
ZDP-Triage:
- we need to validate if this is already fixed by https://github.com/camunda/zeebe/issues/14486

**Comment by megglos** [comment]
ZDP-Planning:
- there is no easy way to validate this => we rather need to mark the error as resolved and act if it occurs again on a newer version

**Comment by deepthidevaki** [comment]
This was not shown in the error reporting. This was observed because the partition was reported as unhealthy in grafana dashboard.
