### ISSUE TITLE
zeebe-client-java requests support for multiple IP links

### ISSUE THREAD

**Issue by WlisonChan** [camunda/zeebe#14635]
We are loyal users of Zeebe and we use Spring Boot microservices to connect to the Zeebe cluster. The current architecture diagram is as follows:

<img width="1094" alt="image" src="https://github.com/camunda/zeebe/assets/54538165/90922256-ab35-48a9-90dc-67b25c5a76dd">

Currently, the number of job executions we have per day has reached the level of millions. In the above architecture, if the CLB is unavailable in extreme cases, the consequences will be catastrophic. Therefore, we need to provide a more reliable and available architecture to ensure the operation of the process. We recently designed a disaster recovery plan for CLB across multiple availability zones, but the official Zeebe-client-java configuration does not support filling in multiple IP addresses (zeebe.client.gateway.address). Therefore, we made modifications in the SDK to switch the CLB for work using round-robin load balancing when an Error exception occurs in Grpc, as shown in the figure below.

<img width="1200" alt="image" src="https://github.com/camunda/zeebe/assets/54538165/8f7af91e-d993-478d-a112-31d4576146be">

However, we are currently facing a problem where every time the official zeebe-client-java version is released, we need to modify the official code to be compatible with our architecture. Therefore, we kindly request if the official could provide a branch for us to commit code and merge with the new version of zeebe-client-java.

**Comment by nicpuppa** [comment]
Hi @WlisonChan,

Unfortunately we are unable to provide the requested solution. Instead, what you can do is, [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the zeebe project on GitHub into your own organization. With this solution you can create a branch with all your `java-client` updates but still keep the other branches in sync with the upstream repository. 

I'm going to close this issue, but if you have any question please ask here or post a question on our [forum](https://forum.camunda.io/), here you can find not only camundi but also camunda experts that can help with your questions
