### ISSUE TITLE
Replace Dependabot with Renovate

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/zeebe#14701]
**Is your feature request related to a problem? Please describe.**

Currently we have Dependabot and Renovate in our repo, makes sense to only use one, and Renovate seems to cover all our use cases, unlike Dependabot (see https://github.com/camunda/zeebe/issues/13409).

**Describe the solution you'd like**

Change renovate.json to also cover the maven and docker updates. Remove the Dependabot tool for these (do we have other things being updated by Dependabot?).

The following command can be used to test renovate locally:
```
npx renovate --token=$GITHUB_TOKEN --schedule="" --require-config=ignored --dry-run=full camunda/zeebe 

```

Also helps to set the env var LOG_LEVEL=debug, so that the previous command produces more information.

**Comment by npepinpe** [comment]
Triage:

Let's discuss it in planning later and see if we have time for it, but we shouldn't postpone it too much to avoid missing out on dependency updates and losing momentum (since Rodrigo has worked on it recently).

**Comment by megglos** [comment]
One hint: we also need to check how we can update go dependencies, we could keep dependabot for this for a first scope as well.

**Comment by rodrigo-lourenco-lopes** [comment]
https://github.com/camunda/zeebe/pull/14909 is merged. The requirements from the dependabot were added to renovate and dependabot.yml removed.  
Now we are going to be validating the next PRs that get created.
If all is correct then we still need to remove the "Dependabot auto-merge updates" workflow.

**Comment by oleschoenburg** [comment]
@rodrigo-lourenco-lopes We are now getting maven dependency PRs from Renovate, which is great :rocket: 
But the PR title and commit message is a bit wrong. https://github.com/camunda/zeebe/pull/14962 for example uses "deps(deps)" as the topic, it should be "deps(maven)". Could you fix this as a follow up? :pray:

**Comment by remcowesterhoud** [comment]
@rodrigo-lourenco-lopes Thanks for doing this 🚀 As the PR is merged, are you okay with closing this issue?

**Comment by rodrigo-lourenco-lopes** [comment]
> @rodrigo-lourenco-lopes Thanks for doing this 🚀 As the PR is merged, are you okay with closing this issue?
> 
> Either way I will remove it from the ZPA board cause we don't need to take any action here.

@remcowesterhoud we still need to remove the dependabot github related actions, I will do this, and then close it.
