### ISSUE TITLE
Flaky CancelProcessInstanceConcurrentlyTest#shouldCancelAfterElementCompleting 

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#14893]
**Summary**

- How often does the test fail? 1
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

Multiple tests failed. Test failed for
1. sequence flow
2. parallel flow
3. subprocess
4. multi instance

`Run 1: CancelProcessInstanceConcurrentlyTest.init:131 » Execution Actor is closed`

**Logs**

https://github.com/camunda/zeebe/actions/runs/6669178419

[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/13202219/Test.results.for.unit.tests.zip)

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- Flaky test, moving to ready for further analysation.

**Comment by megglos** [comment]
Given there haven't been reports since 4 months and I could run 10k iterations locally without a failure I will close this. Please reopen if you see one in the wild :)
