### ISSUE TITLE
BackupErrorResponseTest$RequestTimeoutTest.shouldReturn is flaky

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#14906]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? no
- Do we suspect that it is a real failure? no

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Paste the failure here
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

```
Error:    Run 1: BackupErrorResponseTest$RequestTimeoutTest.shouldReturn504:157 
expected: 504
 but was: 400
 ```

CI [link](https://github.com/camunda/zeebe/actions/runs/6693823209/job/18185810373)

**Comment by Zelldon** [comment]
https://github.com/camunda/zeebe/actions/runs/7180143632/job/19551785574?pr=15420
