### ISSUE TITLE
IOPS doubled in CW44

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14924]
**Describe the bug**

While this is not always the case, in CW44 (and new benchmarks), I've seen that some nodes sometimes end up doing up to 8000 IOPS, instead of the ~4000 from the previous benchmarks. 

Note that some nodes still do 4000, and this issue is intermittent. But it's unclear in our benchmarks why one node would do so much more IOPS. Leadership is well balanced, each partition is doing ~50 PI/s, the journal append rate is similar, the leader commit rate is similar, etc.

Yet somehow, one or more nodes is doing _way_ more I/O than the others.

**Log/Stacktrace**

Here's CW43 when one node is leader for 2 partitions:

![image](https://github.com/camunda/zeebe/assets/43373/0e2450e1-747d-44f2-89fd-fbe9232c943a)

Here's CW43 when leadership is well balanced:

![image](https://github.com/camunda/zeebe/assets/43373/446f502a-9dc8-4afc-90ce-8c0127d6d04d)

Now, it's still weird that one node is doing way less I/O than the others, but we're still at the 4000 mark.

Here's CW44 with leadership well balanced: 

![image](https://github.com/camunda/zeebe/assets/43373/1f6d1c99-cf5c-4279-afd1-1317b6466ac3)

**Comment by Zelldon** [comment]
Triage:

We should take a look asap and asses the current state/issue.

**Comment by npepinpe** [comment]
Timebox root causing in the next 2 weeks. First check CW45, if doesn't happen then we can consider it a fluke and close. Otherwise root cause, and put it back into planning to discuss priority on the fix.

**Comment by oleschoenburg** [comment]
I just stumbled over this again and I think it's likely that we are counting some metrics twice.

Just querying for the raw data shows two almost identical entries for zeebe-0 writing to /dev/sdb.

```promql
rate(container_fs_writes_bytes_total{cluster=~"$cluster", namespace=~"$namespace", pod=~"$pod"}[$__rate_interval])
```

```js
{container="zeebe", device="/dev/sdb", endpoint="https-metrics", id="/kubepods/burstable/podb8b5b883-fb5f-4da2-933a-7cb778cd3a91/d2ef05d2d8f8442992842479db4d7b2558106a1c53d44c1fac69b76865be8a67", image="gcr.io/zeebe-io/zeebe:medic-y-2023-cw-45-322236a-benchmark-322236a", instance="10.132.0.158:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="d2ef05d2d8f8442992842479db4d7b2558106a1c53d44c1fac69b76865be8a67", namespace="medic-y-2023-cw-45-322236a-benchmark", node="gke-zeebe-cluster-n2-standard-2-d2e6c783-rw8j", pod="medic-y-2023-cw-45-322236a-benchmark-zeebe-0", service="monitoring-kube-prometheus-kubelet"}
{device="/dev/sdb", endpoint="https-metrics", id="/kubepods/burstable/podb8b5b883-fb5f-4da2-933a-7cb778cd3a91", instance="10.132.0.158:10250", job="kubelet", metrics_path="/metrics/cadvisor", namespace="medic-y-2023-cw-45-322236a-benchmark", node="gke-zeebe-cluster-n2-standard-2-d2e6c783-rw8j", pod="medic-y-2023-cw-45-322236a-benchmark-zeebe-0", service="monitoring-kube-prometheus-kubelet"}
```

**Comment by Zelldon** [comment]
![iops](https://github.com/camunda/zeebe/assets/2758593/79d970ab-7757-47e5-a127-b3c5c0f56c8b)

It is the same what we had with the memory a while ago

**Comment by Zelldon** [comment]
It seems to be even quadrupled. 

We have two different containers empty and zeebe AND two services: monitoring and metrics.
![iops](https://github.com/camunda/zeebe/assets/2758593/ea5fad0a-2ba8-495b-b16d-283ac2aaf588)
