### ISSUE TITLE
Process Instance Migration - Define Zeebe API

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#14923]
Prepare a proposal for Process Instance Migration API definitions required for other clients and specifically Operate to interact with Zeebe. This is needed to unblock other teams. Once we define the API, other teams can already start implementing their logic by mocking the Zeebe interaction.

**Comment by berkaycanbc** [comment]
The API definition documentation is created here: https://docs.google.com/document/d/1r2RwJ9uvTv1oHzAsc9iqhvvxKkP-8kqXUHHmbwwNmnQ/edit

**Comment by korthout** [comment]
The last two open questions have been clarified. We're considering the API Definition Document to be completed for this first iteration.
