### ISSUE TITLE
Add value type and intent labels to stream processing metrics

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14925]
**Description**

In the last incident, I needed to understand what was happening in the brokers - essentially, what was the engine processing. The cluster was writing more commands/events than it could process, and it was all internal load (i.e. not user commands).

In the end, I had to get the user to send me a snapshot of their data (44GB :exploding_head:) and use zdb to analyze this. While that works, it would be great to have a quick overview of what's happening in the broker.

> **Note**
> It's a great use case for the future to have ephemeral "exporters", and I noted this [here](https://github.com/camunda/product-hub/issues/805).

~A quick solution would be to take the existing stream processor metrics, specifically:~

- ~`stream_processor_records_total`~
- ~`stream_processor_latency`~
- ~`stream_processor_processing_duration`~

~And add the `valueType` and `intent` labels, so we could understand what kind of records are being written/processed/skipped, how long they take, and group them by the actual command being processed.~

- Add new metric in the `LogStorageAppender` which records how many records are written for a given record type, value type, and intent.
- Add value type and intent labels to the `stream_processor_processing_duration` metric.

I understand this splits the cardinality of these metrics, but keep in mind that they are still bounded.

I've added this to the ZPA board, not for you do it, but only in case you have input on this.

**Comment by npepinpe** [comment]
So, an alternative would be to add `LogStorageAppender` and count how often we write a specific `valueType.intent` combination. Since we have to process all records anyway, this would give us an idea of what the system is doing (e.g. writing a million timer trigger commands :upside_down_face:)

**Comment by npepinpe** [comment]
New proposal:

- Add new metric in the `LogStorageAppender` which records how many records are written for a given record type, value type, and intent.
- Add value type and intent labels to the `stream_processor_processing_duration` metric.

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- Seems @npepinpe already made a solution.
- You proposal makes sense to us.
- Will remove it from our board as ZDP has got this covered.
