### ISSUE TITLE
8.3.x Release Benchmark gateways pods were stuck in restart

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#15000]
**Describe the bug**

We notice that the gateways pod of the release 8.3.x benchamark were stuck in a sort of limbo due to OOM error. The pods were not completely shutdown and k8s was not able to reschedule it.

We fix the problem by manually restarting the pods.

<img width="2048" alt="Screenshot 2023-11-03 at 10 11 46" src="https://github.com/camunda/zeebe/assets/72783243/4f220e28-6794-4d6d-8a20-5c64bacbb346">

Here the link to the [logs](https://console.cloud.google.com/logs/query;query=resource.labels.namespace_name%3D%22release-8-3-x%22%0A-resource.labels.container_name%3D%22worker%22%0A-resource.labels.container_name%3D%22starter%22%0Aresource.labels.container_name%3D%22zeebe-gateway%22%0Aresource.labels.pod_name%3D%22release-8-3-x-zeebe-gateway-7fc776bf9c-c7swq%22;pinnedLogId=2023-11-03T02:31:13.057611510Z%2F5wzyepuemlsb6sgi;cursorTimestamp=2023-11-03T02:31:12.112984345Z;startTime=2023-11-03T00:10:00.000Z;endTime=2023-11-03T03:03:00.000Z?project=zeebe-io), you can find it also on [drive](https://drive.google.com/drive/folders/1jWQuF-KGRjNq0g6aup5wVtv4O0bMwaCV)

**Comment by nicpuppa** [comment]
I try to disable the stream in order to make the pods running.

Since this, the pods are running correctly. Just after the restart I encounter a lot of 

```
io.camunda.zeebe.gateway.cmd.BrokerErrorException: Received error from broker (INTERNAL_ERROR): Failed to write client request to partition '2', because the writer is full.
	at io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse(BrokerRequestManager.java:194) ~[zeebe-gateway-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:143) ~[zeebe-gateway-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-scheduler-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) [zeebe-scheduler-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [zeebe-scheduler-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.3.1.jar:8.3.1]
```

Followed by a lot of

<img width="1690" alt="Screenshot 2023-11-03 at 11 35 14" src="https://github.com/camunda/zeebe/assets/72783243/67283bc3-efb2-49be-810d-2e842953b6c5">

The pods are running, but somehow they failed the continously membership probe (could be related to #14845), logs are here [stream-disable-log.json](https://drive.google.com/drive/folders/1jWQuF-KGRjNq0g6aup5wVtv4O0bMwaCV)

I'll try to enable again the stream

**Comment by nicpuppa** [comment]
Just after enable again the stream this is the situation:

<img width="2051" alt="Screenshot 2023-11-03 at 11 44 12" src="https://github.com/camunda/zeebe/assets/72783243/9eab0e43-7cf3-4d32-afd4-eb12b37877ce">

I'll continue to monitoring

**Comment by nicpuppa** [comment]
After 20 minutes the situation looks like this:

<img width="2014" alt="Screenshot 2023-11-03 at 12 00 38" src="https://github.com/camunda/zeebe/assets/72783243/dde2b341-2ea5-49fa-8a31-4075db7dd17b">

The pods are now stopped to fail the probe, now everything seems healthy 🤞

**Comment by nicpuppa** [comment]
This pod `release-8-3-x-zeebe-gateway-7fc776bf9c-pd6h5` continously failed the probe

<img width="2037" alt="Screenshot 2023-11-03 at 12 17 11" src="https://github.com/camunda/zeebe/assets/72783243/83277d39-830d-44b6-9e23-3337d6fcda19">

**Comment by deepthidevaki** [comment]
First OOM started around 1:40am. Here it was due to Out of Heap. Before this error, there were several probe failures. 

```
WARNING 2023-11-03T00:38:55.630372430Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc - Failed to probe 0
INFO 2023-11-03T00:38:55.742719111Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc - Failed all probes of Member{id=0, address=release-8-3-x-zeebe-0.release-8-3-x-zeebe.release-8-3-x.svc:26502, properties={brokerInfo=EADJAAAABAAAAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGlBAAAAcmVsZWFzZS04LTMteC16ZWViZS0wLnJlbGVhc2UtOC0zLXgtemVlYmUucmVsZWFzZS04LTMteC5zdmM6MjY1MDEFAAMBAAAAAQIAAAABAwAAAAEMAAAFAAAAOC4zLjEFAAMBAAAAAQIAAAABAwAAAAE=}}. Marking as suspect.
DEBUG 2023-11-03T00:38:57.744878461Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] Received REACHABILITY_CHANGED for broker 1, do nothing.
DEBUG 2023-11-03T00:38:57.800633839Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] Received metadata change from Broker 0, partitions {1=FOLLOWER, 2=FOLLOWER, 3=FOLLOWER}, terms {} and health {1=HEALTHY, 2=HEALTHY, 3=HEALTHY}.
DEBUG 2023-11-03T00:38:58.241156358Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] Received new broker BrokerInfo{nodeId=2, partitionsCount=3, clusterSize=3, replicationFactor=3, partitionRoles={1=FOLLOWER, 2=FOLLOWER, 3=FOLLOWER}, partitionLeaderTerms={}, partitionHealthStatuses={1=HEALTHY, 2=HEALTHY, 3=HEALTHY}, version=8.3.1}.
DEBUG 2023-11-03T00:38:58.302945908Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] Received REACHABILITY_CHANGED for broker 0, do nothing.
DEBUG 2023-11-03T00:38:58.312045078Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] Received REACHABILITY_CHANGED for broker 1, do nothing.
DEBUG 2023-11-03T00:38:58.758481558Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] Received metadata change from Broker 2, partitions {1=FOLLOWER, 2=FOLLOWER, 3=LEADER}, terms {3=3} and health {1=HEALTHY, 2=HEALTHY, 3=HEALTHY}.
WARNING 2023-11-03T00:38:58.800984927Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] Failed to activate jobs for type benchmark-task from partition 2
INFO 2023-11-03T00:39:01.065874142Z [resource.labels.podName: release-8-3-x-zeebe-gateway-7fc776bf9c-77kvc] Terminating due to java.lang.OutOfMemoryError: Java heap space
```

Then the pod was restarted, it went OOM with in a minute (Don't see anything in the logs, the pod was crash restarted. So I assume OOM). There were a couple of probe failures here too. 
After a couple of restarts following the same pattern, we see a bunch of `o.camunda.zeebe.gateway.cmd.BrokerErrorException: Received error from broker (INTERNAL_ERROR): Failed to write client request to partition '3', because the writer is full.`, and then OOM logged by Netty. 

Once in a while we see `LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more`.

Sometime it fails again by Out of heap space.

The only common logs before out of heap/memory is logs related to Failed to probe and Added new client stream

Memory usage spikes of one gateway during the repeated OOM kills.
![image](https://github.com/camunda/zeebe/assets/1997478/16ee5a07-a13a-44a5-978e-20352686089d)


To follow up:
- Memory leaks when probe failed
- Memory leaks/spikes caused by job stream when a member is added/removed.

**Comment by megglos** [comment]
ZDP-Triage:
- we decided to increase the gateway, @megglos will do it
