### ISSUE TITLE
Remove compensation subscriptions when the process instance ends

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#15064]
## Description

During the execution of a process instance, we create compensation subscriptions to keep track of activities that can be compensated. When a process instance is completed or terminated, we should remove the compensation subscriptions. They are not needed anymore and should not pollute the state. 

requires #15063 
requires #14970

**Comment by nicpuppa** [comment]
Closed by: https://github.com/camunda/zeebe/pull/15761
