### ISSUE TITLE
ScaleDownBrokersTest.shouldScaleDownClusterAgain is flaky

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#15118]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 1
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

```
ScaleDownBrokersTest.shouldScaleDownClusterAgain:124 » ConditionTimeout Condition with alias 'until cluster topology is complete' didn't complete within 10 seconds because assertion condition with alias until cluster topology is complete 
Expecting all elements of:
  [TestStandaloneGateway{nodeId = gateway-0}]
to satisfy given requirements, but these elements did not:

TestStandaloneGateway{nodeId = gateway-0}
error: Expected cluster size to be <1> but was <2>.
```

[logs_103432.zip](https://github.com/camunda/zeebe/files/13309818/logs_103432.zip)

**Comment by deepthidevaki** [comment]
@nicpuppa Thanks for reporting the flaky test. But the log files do not contain the logs from the test. Do you have a link to the failed run?

**Comment by nicpuppa** [comment]
Yes, [https://github.com/camunda/zeebe/actions/runs/6813697254/job/18528872756?pr=15117](https://github.com/camunda/zeebe/actions/runs/6813697254/job/18528872756?pr=15117)

**Comment by deepthidevaki** [comment]
Thanks. For future you have to download `Test Results for XXX`  which you can find in the summary page.

![image](https://github.com/camunda/zeebe/assets/1997478/cc307fd9-f32b-4528-8496-2e6966db9021)
