### ISSUE TITLE
Support `UpdateJobTimeout` RPC in Java Client

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#15120]
## Description

Add `Job Update Timeout` command to the Java Client.
This command is very similar to the `Job Update Retries` command.

**Comment by akeller** [comment]
We didn't get an alert in the #ask-developer-experience channel from Zeebot on this issue closing (aka, the Java client getting updated). We only found out about this via https://camunda.slack.com/archives/C0484UFR2VA/p1702534372752029.

Does anyone know why this wouldn't have triggered Zeebot in our channel?

**Comment by oleschoenburg** [comment]
@akeller Because the issue wasn't [labeled as a java client issue](https://github.com/camunda/zeebe/blob/8fc4e73b42c66cc4b462e48df9e1f6622f7e17eb/.github/workflows/java-client-issue.yaml#L11)

**Comment by akeller** [comment]
I added it retroactively and will check other issues with "Java client" in the title to ensure the tag is applied.
