### ISSUE TITLE
Avoid executing process according to unprocessed commands referring to source process definition

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15129]
If we allow the migration of process instances not entirely in a wait state, Zeebe would wrongly execute the process instance after the migration.

In short, unprocessed commands referring to the source process definition may exist on the log stream with a position higher than the process instance migration command. When we process these commands, the engine wrongly attempts to continue the processing on the source process definition as if the migration didn't occur. For a complete discussion, please read 'How should we deal with process instances in non-wait states?' in the epic's 'Discussions and Decisions' section. 

We can either:
1. Reject process instance migration if we know the process instance is not entirely in a wait state.
2. Don't trust the process definition key in such commands, but rather look up the process definition from the state when processing commands.

A downside to option 1 is: We don't know what commands exist on the log with a higher position than the command being processed. It may be that this solution is not water tight, requiring us to investigate option 2.

A downside to option 2 is: Some commands may refer to elements that no longer exist in the target process. These will be rejected.

**Comment by korthout** [comment]
Labelling this as a bug because it is if we don't resolve this.

**Comment by korthout** [comment]
Estimated as medium, because it's not entirely clear how to resolve this yet. Estimate might be lower when this becomes clear.

**Comment by korthout** [comment]
Let's consider the different options.

1. Reject process instance migration if we know the process instance is not entirely in a wait state.

This raises the question: Can we detect that the process instance is currently not entirely in a wait state? 

Let's start with regular process instance execution over sequence flows. Each flow scope element instance keeps track of the number of sequence flows that are currently taken inside it for which the target element has not yet been activated. So, we can use this. 

If the sequence flow has not yet been taken, an element instance is always active (i.e. activating, activated, completing, or terminating). 

This is the case irrespective of unprocessed `ProcessInstance` and `ProcessInstanceBatch` commands on the log.

However, other unprocessed commands referring to the process definition on the log may continue the process execution. This leads us to consider option 2: 

2. Don't trust the process definition key in such commands, but rather look up the process definition from the state when processing commands.

Option 2 is actually a requirement for any command in our system because of the async nature of Zeebe's engine. Typically, the state is different when the command is appended to the log than when it is processed because other commands may been executed in between. Therefore, we can never trust all data in commands. This rule follows naturally from our stream processing design, and is why we've build things like [ProcessInstanceStateTransitionGuard](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/ProcessInstanceStateTransitionGuard.java).

Commands that refer to data that may have changed due to migration are:
- `Timer:TRIGGER` refers to `targetElementId` and `processDefinitionKey` 
- `ProcessMessageSubscription:CORRELATE` refers to `bpmnProcessId` and `elementId`
- ~~`Signal:BROADCAST`~~ does not refer to properties that may have changed due to migration
- `Incident:Resolve` refers to `bpmnProcessId`, `processDefinitionKey`, and `elementId`
- `Job:*` (multiple intents) refers to `bpmnProcessId`, `processDefinitionVersion`, `processDefinitionKey`, and `elementId`
- `UserTask:*` (multiple intents) refers to `bpmnProcessId`, `processDefinitionVersion`, `processDefinitionKey`, and `elementId`

In addition, the following commands also continue the process execution but could be covered by rejection of the command (option 1) if we follow that approach:
- `ProcessInstance:*` (multiple intents) refers to `bpmnProcessId`, `elementId`, `version`, and `processDefinitionKey`
- `ProcessInstanceBatch:*` (multiple intents)

Lastly, some commands don't directly continue the process execution but still refer to data that may have changed:
- `MessageSubscription:*` (multiple intents) refers to `bpmnProcessId`

----

I want to focus on option 2 for two reasons:
- it should be a design requirement for any command processor in the first place. By applying this requirement to all command processors, we simplify reasoning about the system and bring consistency to implementation. This requirement should be documented in our developer documentation.
- it is less restrictive than option 1, allowing for migrations of process instances in active execution rather than only those in a complete wait state.

**Comment by korthout** [comment]
The number of affected commands is strongly reduced for the first iteration due to the supported scope of instance migration MVP.

However, in later iterations. These problems may surface when more is supported.

**Comment by romansmirnov** [comment]
@korthout and @saig0 ,

a potential option: Would it be possible to bookmark that a current "active path" (aka element instance or similar) has an outstanding follow-up command (to bring that in a valid - or wait - state)? While migrating an active path, the processor could check for this bookmark/flag being set or not. And if there is an outstanding command, it stops migrating, rolls back, and rejects the migration command.

Or the instance itself could bookkeeping all outstanding commands? So there all in one place stored, and once a command is being executed it is removed from that.

Details would need to be defined, but would this resolve the issue? If not, what is missing?

**Comment by korthout** [comment]
@romansmirnov Sorry I did not find the time to answer anymore before my FTO. I believe @saig0 will consider your proposal.

@saig0 If you manage to resolve this bug, please notify @berkaycanbc that we can remove the `@ExperimentalAPI` annotation from the java-client **and** the danger banner in the [concept docs](https://github.com/camunda/camunda-docs/pull/3000#issuecomment-1847526591)

**Comment by saig0** [comment]
@romansmirnov I will follow your idea. :+1:  

The required data about the active "outstanding" command should be available already. I will check the data in the migration processor to reject the migration command.
