### ISSUE TITLE
Add an endpoint to cancel a stuck topology change

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#15147]
We are already checking for all pre-conditions before accepting a topology change request such as scaling request or partition join or leave request. However, it may still fail when applying the operation due to unforeseen reasons. In this case, we should be able to recover from it by cancelling the topology change.  

Note that cancelling an operation which has already applied some intermediate steps won't be rolled back. We expect that the cluster will be still functional, but a manual intervention might be required to bring the cluster to a previous configuration.

**Comment by deepthidevaki** [comment]
@oleschoenburg I'm thinking of `DELETE cluster/change/{changeId}` or `DELETE cluster/operation/{changeId}` as the endpoint. wdyt?

**Comment by oleschoenburg** [comment]
I like the first one 👍
