### ISSUE TITLE
Could not update new leader for partition

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15188]
**Describe the bug**

A leader update on a partition wasn't successful.

No further details could be seen from the log.

**To Reproduce**

**Expected behavior**

A partition leader is successfully updated.

**Log/Stacktrace**

* [GCP log](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.namespace_name%3D%2207ed94ef-cfa9-445f-b755-37d1e5c8f2ea-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22;pinnedLogId=2023-11-13T17:12:02.726497982Z%2Fuwqxje0gquvak55g;cursorTimestamp=2023-11-13T17:12:35.079051138Z;startTime=2023-11-13T16:42:32.726Z;endTime=2023-11-13T17:42:32.726Z?project=camunda-saas-int-chaos) / [downloaded logs](https://drive.google.com/file/d/1SUX9Nb4LMKVs0CV3akvbcxH3hG-j0vxw/view?usp=sharing)

```
Could not update new leader for partition X at term Y. Expected to have a non-null value for current leader term, but found null
```

**Environment:**
- OS:  Linux (SaaS Int - chaos)
- Zeebe Version:  `8.4.0-alpha1`
- Configuration:

**Comment by npepinpe** [comment]
Triage:

We're having some difficulty assigning a severity and priority to this without more details.

- What was the impact on the cluster? 
- Did it cause any processing delays? 
- Was the cluster unavailable for a period of time? 
- Did it eventually recover? If so, after how long?

**Comment by deepthidevaki** [comment]
I will look into it, as I observed it in a qa test.
