### ISSUE TITLE
Process definition that has running instances can be deleted via zbctl 

### ISSUE THREAD

**Issue by esraagamal6** [camunda/zeebe#15221]
**Describe the bug**

**some** processes  could be deleted although there are running instances using `zbctl delete resource --insecure` 

https://github.com/camunda/zeebe/assets/129334285/464fe1d5-0579-4a15-9e6f-525c27724a84

**To Reproduce**

- Deploy a process on tasklist - xml provided below the steps
- Take note of the processDefinitionKey
- Start the process
- Run zbctl delete resource ${processDefinitionKey} --insecure

`<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1pg20dm" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.10.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.3.0">
  <bpmn:process id="startedByFormWithoutPublic" name="startedByFormWithoutPublic" isExecutable="true">
    <bpmn:extensionElements>
      <zeebe:userTaskForm id="userTaskForm_1isk9gd">{
  "components": [
    {
      "label": "Field 13",
      "type": "textfield",
      "layout": {
        "row": "Row_15ghdy6",
        "columns": null
      },
      "id": "Field_0ibsmz4",
      "key": "field_1lfayry"
    },
    {
      "label": "Field 2",
      "type": "textfield",
      "layout": {
        "row": "Row_1klibf9",
        "columns": null
      },
      "id": "Field_0msuoi3",
      "key": "field_1prtdvl"
    }
  ],
  "type": "default",
  "id": "Field1",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.3.0",
  "exporter": {
    "name": "Camunda Modeler",
    "version": "5.10.0"
  },
  "schemaVersion": 8
}</zeebe:userTaskForm>
      <zeebe:userTaskForm id="testForm">{
  "components": [
    {
      "label": "Field 1",
      "type": "textfield",
      "layout": {
        "row": "Row_15ghdy6",
        "columns": null
      },
      "id": "Field_0ibsmz4",
      "key": "field_1lfayry"
    },
    {
      "label": "Field 2",
      "type": "textfield",
      "layout": {
        "row": "Row_1klibf9",
        "columns": null
      },
      "id": "Field_0msuoi3",
      "key": "field_1prtdvl"
    }
  ],
  "type": "default",
  "id": "Field1",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.3.0",
  "exporter": {
    "name": "Camunda Modeler",
    "version": "5.10.0"
  },
  "schemaVersion": 8
}</zeebe:userTaskForm>
    </bpmn:extensionElements>
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:extensionElements>
        <zeebe:formDefinition formKey="camunda-forms:bpmn:testForm" />
      </bpmn:extensionElements>
      <bpmn:outgoing>Flow_15vkolf</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_15vkolf" sourceRef="StartEvent_1" targetRef="humanTask" />
    <bpmn:userTask id="humanTask" name="humanTask">
      <bpmn:extensionElements>
        <zeebe:formDefinition formKey="camunda-forms:bpmn:userTaskForm_1isk9gd" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_15vkolf</bpmn:incoming>
      <bpmn:outgoing>Flow_1i3gdwk</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:sequenceFlow id="Flow_1i3gdwk" sourceRef="humanTask" targetRef="Event_07rdhb7" />
    <bpmn:endEvent id="Event_07rdhb7">
      <bpmn:incoming>Flow_1i3gdwk</bpmn:incoming>
    </bpmn:endEvent>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="startedByForm">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="99" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_087m3l3_di" bpmnElement="humanTask">
        <dc:Bounds x="270" y="77" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_07rdhb7_di" bpmnElement="Event_07rdhb7">
        <dc:Bounds x="612" y="212" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_15vkolf_di" bpmnElement="Flow_15vkolf">
        <di:waypoint x="215" y="117" />
        <di:waypoint x="270" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1i3gdwk_di" bpmnElement="Flow_1i3gdwk">
        <di:waypoint x="370" y="117" />
        <di:waypoint x="491" y="117" />
        <di:waypoint x="491" y="230" />
        <di:waypoint x="612" y="230" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>`
-->

**Expected behavior**

Deletion command should be rejected because of the running instance

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.4.0-alpha1
- Configuration:

**Comment by berkaycanbc** [comment]
ZPA Triage:

- There might be a case where the process instance is running on a `partition 1`. When resource deletion command is sent for related process definition, the process definition can be removed from other partitions but not from `partition 1`. The way operate uses Zeebe exported data might be interpreted wrong by the Tasklist.
- Still, we need to check if the behaviour works correctly in Zeebe.

**Comment by berkaycanbc** [comment]
We took these steps to reproduce the issue:
* Check out camunda-platform repo [8.4.0-alpha1 tag](https://github.com/camunda/camunda-platform/releases/tag/8.4.0-alpha1)
* Change `CAMUNDA_PLATFORM_VERSION` environment variable to `8.4.0-alpha1`. (Because it was [`8.3.1`](https://github.com/camunda/camunda-platform/blob/8a2c2fb136445b0a9c4c1572228eb9c04b3d819c/.env#L4))
* Run `docker-compose` locally
* Follow steps with `zbctl`
```sh
bcan@Bs-MacBook-Pro diagrams % zbctl deploy resource diagram_2.bpmn --insecure
{
  "key":  "2251799813686654",
  "deployments":  [
    {
      "process":  {
        "bpmnProcessId":  "startedByFormWithoutPublic",
        "version":  1,
        "processDefinitionKey":  "2251799813686653",
        "resourceName":  "diagram_2.bpmn"
      }
    }
  ]
}
bcan@Bs-MacBook-Pro diagrams % zbctl create instance 2251799813686653 --insecure
{
  "processDefinitionKey":  "2251799813686653",
  "bpmnProcessId":  "startedByFormWithoutPublic",
  "version":  1,
  "processInstanceKey":  "2251799813686715"
}
```
We verified the process instance and the form is created by checking it in Operate and Tasklist.

Attempt to delete process instance:
```sh
bcan@Bs-MacBook-Pro diagrams % zbctl delete resource 2251799813686653 --insecure
Error: rpc error: code = FailedPrecondition desc = Command 'DELETE' rejected with code 'INVALID_STATE': Expected to delete resource with key `2251799813686653` but there are still running instances
```
### Result

We cannot re-produce the issue with provided instructions. We think, the issue might be relate to the local setup variables. Could you please share more information about your setup? For example, similar to how we described the steps of reproduction.
@esraagamal6
