### ISSUE TITLE
Convert `StreamJobsActivated` RPC to bi-directional stream

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15294]
**Description**

In order to allow capacity tracking by the gateway, the client (the source of truth) will need to report its capacity back to the gateway whenever there is more. 

We could do this with multiple calls, but then we need some stream ID to communicate between the server and the client, and we would need to somehow guarantee the capacity update request goes to the same gateway the stream call is on, which may or may not be true if load balancing is involved.

To simplify things, we'll convert the `StreamActivatedJobs` call to a bi-directional stream, **which is a breaking change**. As job push/streaming is an experimental feature in general, we think this is acceptable in order to stabilize it and make it production ready.

So the criteria here is purely converting to a bi-directional stream, and introducing a new control message type which allows for different "request" message types (request in the sense of client -> server messages), which for now will only be the initial stream registration request.

**Comment by Zelldon** [comment]
@npepinpe and I started a discussion about why we need to do this what are the actual challenges when are facing.

We both tried to question in general whether this might be not necessary right now, as we could potentially also add a new stream later, and deprecate the old. 




## Scenarios 

_**Brain DUMP**_


I thought a bit more about it and tried to summarize our current scenarios we are facing to understand whether we actually have an issue we need to solve (and whether bi-directional streaming is really the answer)

### One slow worker (n worker)

- Job gets pushed to gw, gw can't push since worker is not Rdy
- Job gets pushed to other worker
- There might be one worker which handles more jobs then other because of resources. Might be fine?
- 

### Single worker 

- Jobs get pushed until capacity++
- Jobs are no longer pushed
- There is a buffer on server side which is filled before
- Other workers are tried, on not existence go back to broker
- Broker tries different gw (here maybe already timeout?)
- Gw has no workers
- Back to broker
- Broker yields

### Many slow workers

- Similar above but distributed to multiple workers and trying different worker before returning back to broker
- Broker exhausting gws 
- Yielding back

If we have different types and one type is slow to process/handle can this cause issues?

### Slow worker for type y and rest x, z is fast:

- Slow worker of course will impact general pi execution time
- If instances created and x is keeping up
- Instances are moved to y
- Jobs pushed to y worker
- Can handle maybe limit amount, rest will be blocked
- Coming back due to yield, natural backpressure
- Slowing general processing down as we have to process also more yields
- Impact on begin of instance (x task) but also on other PI

Can be handled, by increasing resources for worker y, scaling worker y to not slow down system

**Comment by npepinpe** [comment]
:+1: Let's use this issue to discuss it, it's as good a place as any.

As @Zelldon mentioned, now that we started on this properly (as opposed to just hacking), it's apparent that there's some downsides with this approach we hadn't considered. The main one is complexity being pushed to the client/API consumers.

I'm also just going to brain-dump right now, and we can shape it later.

## Motivation

Let's ignore the bi-directional stream stuff. Why do capacity tracking at all? The main reason is to prevent activating jobs unnecessarily. The idea is that if a client says I can handle 5 jobs, we only activate 5 jobs _until the client says you can activate more_. This means we're not wasting time/work on activating in-engine, pushing to the gateway, realizing the client is full, trying others unsuccessfully (worst case scenario), yielding back to broker, trying other gateways unsuccessfully (worst case scenario), yielding back to engine.

### Latency problem

Over-activation adds latency because of the following:

Detecting a worker is full is "optimistic", meaning we push as much as possible until the worker blocks.

> Note this implies the worker blocks, which is not necessarily true in every client implementation, but should be simple enough to implement.

Some jobs are still going to be buffered, which incurs a latency penalty as they spend more time in the buffer, but this should be quick-ish since the threshold is hard-coded as 32KB in the gRPC library.

So we add latency due to jobs being buffered, potentially unnecessarily. If we block on in the worker, the timed out job is not passed onto the worker. However, if we then unblock, we may have buffered up to 32KB on the gateway side, and it's very likely those jobs have timed out, but _they will be passed onto the worker_. 

> Note that this is fix-able by checking the deadline in the worker and refusing to pass it if the job is already expired - however this could be prone to clock skew, so should be an opt-in flag.

Once the stream is detected as blocked, we try with the next stream. This is typically negligible in terms of added latency, unless you have a very, very high number of streams, or very high resource contention on the actor scheduler (but then you have high latency for all kinds of things).

> Could this add more burden on the actors themselves if we suddenly have to retry a lot? Could this impact other things in the gateway?

If no streams can receive the job, we send it back to the broker. This adds some latency of course. Then the broker tries another gateway, which also adds some latency. The process above repeats (i.e. trying the different clients). Worst case scenario, this come backs to the broker multiple times, adding latency each time, and gets yielded to the engine.

> Note that we might yield jobs that have timed out. A quick/easy optimization would be to check that engine side, where we don't risk clock skew, and simply omit yielding timed out jobs.

Yielding to the engine needs to be processed, and yielded jobs _are not pushed out again_, meaning they will have to polled, which also adds latency. On top, yielding many jobs consecutively may impact the performance of the system since we have to process each command individually, taking time away from the rest of the processing.

So we have the following:

- Unnecessary activation adds processing latency
- Every network hop adds latency, and we have at least `2` hops (gateway + client), at worst `2 * gatewayCount` (where the 2 is gateway then back to broker).
- Yielding is processed individually, which adds latency
- Yielding may add overall latency by clogging the log

However, I don't have real numbers of how much latency is added for each step, _and the assumption is still that yielding is an exceptional case, not the norm_.

## Remedial

Since we expect yielding to be an uncommon case, we need to provide ways to remedy the situation.

### Auto scaling

The current metrics available for scale, i.e. the worker's queue rate, are based on the fixed worker capacity (i.e. `maxJobsActive`) and the observed queue size. However, this might be a poor metric, since it doesn't really tell you about the performance of workers. 

So the question is, are the current metrics sufficient? Do we need a better one, i.e. yield rate per job type, or handling rate per job type?

#### Concern

Is it enough to just say "auto scale"? What if it's not possible because you depend on a third party resource, and you can't scale that one? Can we minimize the impact without requiring workers to auto scale by simply throttling the push rate? Can we observe that server side without requiring complex client side logic?

### Others

Are there any other ways we can avoid yielding? Can we provide other metrics or tools to help tune the workers, pro-actively and re-actively?

#

So that's the gist about why I think/thought capacity tracking was useful. It would help the server self-throttle based on client reports, which specifically helps cases where auto-scaling is not possible or not good enough.

Initially when we prototyped it, it seemed like a great idea because when you're just hacking, it's pretty quick to get started and working. But now that we started an actual implementation,  I think it may be adding too much complexity to clients, primarily around error handling. What we're building is in fact a protocol on-top of the protocol. To illustrate, you open the bi-directional stream, then:

- You send the initial registration request (e.g. the existing `ActivateJobsRequest`)
- After that, you only send the new `SetWorkerCapacityRequest`.

Sounds simple enough, but what's the expected error handling here? What if someone sends a negative capacity? Do we kill the whole stream? What if someone sends the initial registration request again later on? Do we kill the whole stream?

Gut feeling is yes, but the protocol is not self-describing anymore, and requires more involvement. To me it doesn't seem that much more complex, but we've already heard many times that gRPC is complex enough, so what do I know...

That said, maybe we can talk a little bit about the advantages of capacity tracking.

## Pros

By using a bi-directional stream, the one nice part is that we have more control over the stream from the client side. You can now close it properly via `onCompleted` using your own side, and you can properly report errors from your side via `onError`.

Reporting the capacity means we have more observability, server side, into the state of each worker. This brings other benefits, such as routing jobs to workers with less load. 

Using a bi-directional stream, we could later more easily implement exactly-once semantics via acknowledgements of jobs/handshake.

Tracking capacity (assuming it's done accurately) means we're not activating jobs unnecessarily _except in edge cases_ (e.g. the client dies, the client suddenly becomes very slow, polling interferes with capacity). So in prolonged cases where the stream is blocked (e.g. auto scaling not possible because workers are limited by third party system), the theory is that the server itself will self-throttle, thus greatly reducing the impact of slow workers on the overall system (less yielding, freeing up resources for other workloads).

Tracking capacity this way lends itself very nicely to asynchronous use cases where users will track the worker capacity themselves, _as opposed to assuming a job is handled every time the job handler returns_. [See this related FR](https://github.com/camunda/product-gaps/issues/138).

> Note that with Java, we could turn off the automatic flow control and use the `request(int)` method to support asynchronous use case (as described [here](https://grpc.io/docs/guides/flow-control/)). However, keep in mind that for a long time this was a Java-only feature, so I have no idea if this is then feasible in other languages =/

## Cons

Added complexity client side. So in Java, previously, opening a stream using the plain gRPC API looked like this:

```java
GatewayStub stub = asyncStub;
stub.streamActivatedJobs(request, new StreamObserver<> {
  @Override
  public void onNext(final ActivatedJob job) {
    // do something with the job
  }

  @Override
  public void onError(final Throwable t) {
    LOGGER.error("Error from server on job stream", t);
  }

  @Override
  public void onCompleted() {
    LOGGER.info("Server closed job stream");
  }
});
```

Now, with a bi-directional stream, we now introduce a new message type:

```protobuf
message StreamJobsRequest {
  oneof request {
    ActivateJobsRequest registration = 1;
    AddJobStreamCapacity capacity = 2;
  }

  message AddJobStreamCapacity {
    int32 delta = 1;
  }
}
```

```java
GatewayStub stub = asyncStub.withWaitForReady();
final StreamObserver<StreamActivatedJobsRequest> clientObserver = stub.streamJobs(new StreamObserver<> {
  @Override
  public void onNext(final ActivatedJob job) {
    // do something with the job
  }

  @Override
  public void onError(final Throwable t) {
    LOGGER.error("Error from server on job stream", t);
  }

  @Override
  public void onCompleted() {
    LOGGER.info("Server closed job stream");
  }
});

// where request is the initial request containing all activation properties
clientObserver.onNext(StreamJobsRequest.newBuilder().setRequest(request).build());

// we can now use clientObserver.onError(Throwable) to report client side errors, which will close the stream, or clientObserver.onCompleted() to close the stream from the client
```

That's the "simple way". But since this is a bi-directional stream, we also have to worry about possibly overflowing the server side :upside_down_face: So we should also respect the `isReady` of the server side. So to safely update capacity (or send any message back, really), we'd do something like:

```java
public final class CapacityUpdater {
  private final AtomicInteger currentDelta = new AtomicInteger(0);
  private final StreamObserver<StreamJobsRequest> clientObserver;

  public CapacityUpdate(final StreamObserver<StreamJobsRequest> clientObserver) {
    this.clientObserver = clientObserver;
    clientObserver.setOnReadyHandler(() -> updateCapacity(0));
  }

  public void updateCapacity(final int delta) {
    final var actualDelta = currentDelta.addAndGet(delta);
    if (clientObserver.isReady()) {
      final AddJobStreamCapacity capacityRequest = AddJobStreamCapacity
        .newBuilder()
        .setDelta(actualDelta)
        .build();
      clientObserver.onNext(StreamJobsRequest.newBuilder().setRequest(capacityRequest).build());
      currentDelta.addAndGet(-actualDelta);
    }
  }
}
```

> Note that I'm not familiar enough with all implementations of gRPC in different languages to know if this gets easier or more complex.

#

Alright, I'm tired, I'll keep going tomorrow :smile:

**Comment by npepinpe** [comment]
After stress testing the existing state, we opted to not move forward with this. While it seems likely it would provide some performance optimizations, we'd rather stabilize and harden the job push feature before moving on to these. So for now, we'll close this.
