### ISSUE TITLE
Support ElasticSearch 8.9+

### ISSUE THREAD

**Issue by abbasadel** [camunda/zeebe#15306]
**Is your feature request related to a problem? Please describe.**
ElasticSearch provides frequent minor updates. Many bug-fixes are provided via minors (and not via patches).
Due to bugs and CVEs we are upgrading our ElasticSearch instances to 8.9+.

**Describe the solution you'd like**

- [x] Update Zeebe's ElasticSearch dependencies to 8.9+
- [ ] Update zeebe-analytics dependency 
- [x] Make sure tests run successfully

**Additional context**
PDP Epic: https://github.com/camunda/product-hub/issues/1902

**Comment by korthout** [comment]
@abbasadel The linked [supported environments specification](https://confluence.camunda.com/display/HAN/Camunda+8+Supported+Environments) mentions ES 8.8+ for the 8.4 instead of 8.9. Are we sure we want to upgrade to 8.9? This should be aligned across the components.

**Comment by korthout** [comment]
ZPA triage:
- If the rest of the platform is upgrading, we should as well
- We should update the dependencies by hand (I believe auto-updates are disabled for ES client)
- We should also update the dependency in zeebe-analytics
- Marking it as upcoming

**Comment by abbasadel** [comment]
@korthout yes, all components are aligned to upgrade to 8.9, as mentioned in https://github.com/camunda/product-hub/issues/1902
