### ISSUE TITLE
A list property gets overridden by a variable within a FEEL filter expression

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#15321]
**Describe the bug**

A filter expression can access the properties of a list item by the property name. In the following example, the list is filtered by the property `loanId`. The variable `id` is provided by a process variable. 

```
sum({"loans" : [
  {"loanId" : "AAA001", "amount" : 10},
  {"loanId" : "AAA002", "amount" : 20},
  {"loanId" : "AAA001", "amount" : 50}
]}.loans[loanId = id].amount)
```

Since version `8.2.18`, Zeebe evaluates the expression differently if there is a process variable `loanId`. The property `loanId` gets overridden by the variable `loanId`. As a result, the filter returns all items. 

![Screenshot from 2023-11-21 13-22-32](https://github.com/camunda/zeebe/assets/4305769/157754c1-7377-4544-a923-9964a8aa49f3)

Caused by: https://github.com/camunda/feel-scala/issues/765.

Reported by support: https://jira.camunda.com/browse/SUPPORT-19328.

**To Reproduce**

1. Deploy the following process: [filter-error-v2.bpmn](https://github.com/camunda/zeebe/files/13426160/filter-error-v2.bpmn.txt) (rename to _.bpmn_)
2. Create a new instance with the variables: `{"loanId" : "AAA002"}`
3. Verify that the variable `total` is equal to `80`. But it should be `20`.

**Expected behavior**

In a list filter expression, the properties of a list item are not overridden by process variables.

**Log/Stacktrace**

![Screenshot from 2023-11-21 13-26-39](https://github.com/camunda/zeebe/assets/4305769/86503551-f463-410b-a11b-f30515a727a5)

**Environment:**
- OS: 
- Zeebe Version: `8.2.18`
- Configuration:

**Comment by korthout** [comment]
A workaround is available by accessing the item's property explicitly `loans[item.loanId = id]` instead of `loans[loanId = id]`:
```
sum({"loans" : [
  {"loanId" : "AAA001", "amount" : 10},
  {"loanId" : "AAA002", "amount" : 20},
  {"loanId" : "AAA001", "amount" : 50}
]}.loans[item.loanId = id].amount)
```

**Comment by korthout** [comment]
ZPA triage:
- severity `mid` matches the description, there is a workaround, and there is a noticeable impact
- issue exists in feel-scala engine, when resolved there all we have to do is update
- we see a need to resolve this, but we need to prioritize other work first. Marking it as `later`
