### ISSUE TITLE
Document and verify local Camunda setup

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/zeebe#15380]
**Description**

Why:

Currently we don't have clear steps for the local setup of Camunda platform. It will be useful to have these documented and available as local setup allows to better understand the system, to test changes locally and to troubleshoot.

How:

Set up and run Camunda platform locally, create a step-by-step guide and document issues as well as their solutions. 
QA the documentation afterwards.

**Comment by Zelldon** [comment]
@ana-vinogradova-camunda are you really in the whole platform or just zeebe?

**Comment by ana-vinogradova-camunda** [comment]
@nicpuppa it will help big time, thank you! It actually looks like the thing I needed. I will read through the wiki page and follow the instructions. Might just update it in case if I find something new.

**Comment by Zelldon** [comment]
Fyi https://github.com/camunda/camunda-platform-local

**Comment by ana-vinogradova-camunda** [comment]
[This page](https://github.com/camunda/zeebe/wiki/How-to-test-workflow-engine-changes-manually) already contains everything that is needed. My only addition would be that if someone is using Colima then it is better to start it with `colima start --memory 8` to give it enough resource (particularly if running with `--profile kibana`)

**Comment by abbasadel** [comment]
Thanks for the input. I think what you discovered is worth documenting [here](https://github.com/camunda/zeebe/wiki/How-to-test-workflow-engine-changes-manually)
