### ISSUE TITLE
Allow setting `scope` parameter for OAuth2 authentication

### ISSUE THREAD

**Issue by dlavrenuek** [camunda/zeebe#15391]
**Is your feature request related to a problem? Please describe.**
To add support for authentication via [Microsoft Entra ID (Azure AD) and generic OpenID Connect](https://github.com/camunda/product-hub/issues/739) it is required to set the `scope` parameter in the token request, see [Microsoft Entra ID docs](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret). Currently the Zeebe java client does not support setting the `scope` parameter.

**Describe the solution you'd like**
The Zeebe client supports setting the `scope` parameter in the token request (for example in https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsProvider.java#L125)

**Describe alternatives you've considered**
Use Identity-sdk which supports creating auth tokens.

**Additional context**
- When using Microsoft Entra ID, the scope parameter has to contain the client api in a specific format, for example `scope=4393964b-2273-4b23-94fa-98c3d2396b1e/.default`
- The additional parameter has to also be integrated into [`spring-zeebe`](https://github.com/camunda-community-hub/spring-zeebe) since it is used by Connectors

**Comment by megglos** [comment]
> The additional parameter has to also be integrated into [spring-zeebe](https://github.com/camunda-community-hub/spring-zeebe) since it is used by Connectors

@dlavrenuek from my understanding, having the env var support in the client which you added with https://github.com/camunda/zeebe/pull/15404 will be enough to make use of it in spring-zeebe, right?

**Comment by 1nb0und** [comment]
Are we also considering adding the `scope` soon to other components as well (operate, optimize, etc) ?

**Comment by megglos** [comment]
@1nb0und best reach out on the product-hub issue https://github.com/camunda/product-hub/issues/739 to the PM and engineering DRI
