### ISSUE TITLE
Reject process instance migration if event subscriptions exist

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15405]
In the `ProcessInstanceMigration` command processor, reject the command if:
- an element is active that is currently subscribed to an event

Rejecting a command includes both appending a rejection with the rejection writer, as well as responding the rejection with the response writer.

Some tests must showcase this behavior.

Blocked by:
- https://github.com/camunda/zeebe/issues/15111

**Comment by korthout** [comment]
We don't have to do this task if we implement:
- https://github.com/camunda/zeebe/issues/15407

**Comment by berkaycanbc** [comment]
https://github.com/camunda/zeebe/issues/15407 is merged, we do not need to implement this issue.

**Comment by berkaycanbc** [comment]
Re-opening this issue since we will revert the changes of #15407. (See the revert issue #15659 )
