### ISSUE TITLE
Migrate task instances with recreated event subscriptions

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15407]
When migrating a process instance:
- there may exist event subscriptions in the process instance
- there may be events that must be subscribed to in the target process

Migrating the existing event subscriptions is difficult, because they can exist on other partitions than the process instance, e.g. message subscription.

We can deal with this by unsubscribing each active element instance in the process instance **and** subscribing to new events in the target process for each migrated element instance.

# Breakdown

There are three general cases:

1. a process instance is currently subscribed to a message, and will be subscribed to that message again in the target process
2. a process instance is currently subscribed to a message, but no longer in the target process
3. a process instance is not subscribed to a message, but will be subscribed to a message in the target process

We cannot support case 1 by unsubscribing and re-subscribing because it leads to a [bug](https://github.com/camunda/zeebe/issues/15659). Cases 2 and 3 can be supported though.

> I'm ignoring a fourth case 'a process instance is currently subscribed to a message, and will be subscribed to **another** message in the target process', as this is a combination of cases 2 and 3.

To support case 1, we must communicate the migration over partitions using command distribution. This will require other efforts that we can split up. We can start by detecting the three cases and reject them individually for iterative development (we can remove the rejection independently later).

- [x] #16380
- [x] #16381
- [x] #16382
- [x] #16383
- [x] #16384
- [ ] #16385
- [ ] #16386

**Comment by berkaycanbc** [comment]
@korthout should we keep this one in the backlog?

**Comment by korthout** [comment]
Sorry @berkaycanbc, I missed your question. 🙇 

Let's keep this in the backlog, we'll get to it at some point in phase 2 of #14907

**Comment by korthout** [comment]
The team discussed this approach and decided against this behavior as the first to be implemented. Instead, we'll work only on:
- #16386 

We take this step because of how we want to shape the default experience: by default, we preserve the entire context of the process instance. Just like jobs that keep the `type` they had before the migration and user tasks that keep the `assignee` they had before the migration, so too will the process instance continue to be subscribed to any events it was subscribed to in the source process definition. Even when that event no longer exists in the target process definition.

Additionally, the process instance will not magically subscribe to events in the target process definition that did not exist in the source process definition. That means that the user knows what to expect. The process instance stays as it was but will continue execution in the process definition it was migrated to.

I'm moving this issue out of scope for now.

**Comment by korthout** [comment]
I'm closing this issue as it is covered by other issues like:
- #16383
- #16384 
- #16386
