### ISSUE TITLE
Extend Zeebe Task API definition with new actions and events

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#15528]
**Description**

Extend the [Zeebe Task API definition](https://docs.google.com/document/d/1W4XA74hmD8mpRucIBeupBe3KoTfAYR2iQ57n_Pf43U8) with the following actions and events:
* Assign (action)
* Claim (action)
* Update (action)
* ASSIGNING & ASSIGNED (events)
* UPDATING & UPDATED (events)

**Comment by tmetzke** [comment]
@koevskinikola, can you please review the API definitions? 🙂

**Comment by koevskinikola** [comment]
@tmetzke the current API definitions make sense to me.

There are still some open questions that me and Nicolas (ZDP) will try to answer in the Zeebe REST API spike. But these are technical details and don't impact the behaviors that you defined in the document.

I have some concerns about [this UPDATE endpoint discussion](https://docs.google.com/document/d/1W4XA74hmD8mpRucIBeupBe3KoTfAYR2iQ57n_Pf43U8/edit?disco=AAABCG7qiDw), but it doesn't impact the document definitions. Please see my reply in that thread.

**Comment by ana-vinogradova-camunda** [comment]
@tmetzke the suggested endpoints look good to me. I had a comment on `claim` command when an empty assignee is provided, but @koevskinikola already added one.

**Comment by tmetzke** [comment]
Thanks, @ana-vinogradova-camunda and @koevskinikola, for the input. That helped a lot 👍
I'll put this back to `In progress` since we're not completely done yet with the API definition.

**Comment by tmetzke** [comment]
### API definition update

* Removed "claim" endpoint
* Moved to nouns for endpoints (completion and assignment)
* Added "unassign" (`DELETE user-task/{key}/assignee`)
* Aligned task data with Tasklist API

**Comment by tmetzke** [comment]
Closing this as complete. APIs have been defined and synced with HTO, Operate, and Optimize teams. Their input has been incorporated.
