### ISSUE TITLE
Process user task claim command

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#15531]
**Description**

* Implement a processor for the `UserTaskIntent.CLAIM` command issued for the `UserTask` value type.
* Ensure the user task can be claimed, i.e. it is in the internal state CREATED and the task's assignee is either ~`null`~ an empty String or the same as the assignee provided by the command. Otherwise, write a rejection for the command.
* For adjusting the assignee, reuse the `assign` command functionality provided with https://github.com/camunda/zeebe/issues/15529

@koevskinikola: I updated the description to state that the assignee can be an empty String instead of `null` since gRPC doesn't allow `null` values.

**Comment by abbasadel** [comment]
Thanks @tmetzke for preparing this for @ana-vinogradova-camunda.
