### ISSUE TITLE
set replica count to 1 inside ES HA setup

### ISSUE THREAD

**Issue by thomas-polnik** [camunda/zeebe#15547]
Currently replica count for zeebe indices inside an ES HA setup is `0`
This leads to an ES red state, when one node, where a zeebe index is stored, is restarted.

To avoid this, replica count should be set to 1.

**Comment by romansmirnov** [comment]
Zeebe already offers an option `numberOfReplicas` to configure the number of replicas:

https://github.com/camunda/zeebe/blob/181d222916464081d17f20e9b1bf4f44645f67dd/dist/src/main/config/broker.standalone.yaml.template#L754

By default, the number of replicas is set to 0. However, I would not recommend changing that default to 1 (or anything >0). In a non-HA setup (i.e., with only one ES node) the ES state would remain "yellow", meaning, there are still some unassigned shards which might be confusing for users.

In my opinion, the number of replicas should be set by the controller when running an ES HA setup in our SaaS offering. Setting the number of replicas should be possible via environment variables.

**Comment by thomas-polnik** [comment]
issue created for operator
