### ISSUE TITLE
`SetVariables` is not always retryable

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#15549]
With https://github.com/camunda/zeebe/pull/15230 we introduced a default service configuration that marks the `SetVariables` call as retryable on `UNAVAILABLE`, `RESOURCE_EXHAUSTED`, and `DEADLINE_EXCEEDED`:

https://github.com/camunda/zeebe/blob/f80144b951c9bd6b40d82dc10a428a1fcb4485bd/gateway-protocol-impl/src/main/resources/gateway-service-config.json#L3-L25

Since `SetVariables` is an _imperative_ command that simply sets the variables for a given element instance, it should not be retried without the user knowing. After the first `SetVariables` was processed but the response timed out with `DEADLINE_EXCEEDED`, the process instance may make progress and change state such that a retried `SetVariables` may not be correct. 

`SetVariables` stands out compared to the other methods currently marked as retryable such as `CompleteJob`, `ResolveIncident`, which are idempotent such that an accidental retry simply has no effect. It is more like `PublishMessage` or `ModifyProcessInstance` which can't always be retried.

**Comment by nicpuppa** [comment]
ZPA Triage:
- Size `small` as the implementation seems straight forward
- Priority `upcoming` as seems to be bad for the java client
- Severity is `mid` because there are multiple workarounds
- Is a good candidate for mob-programming
