### ISSUE TITLE
ClusterTopologyManagementIntegrationTest.shouldInitializeCoordinatorFromPeers unstable

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#15567]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? maybe
- Do we suspect that it is a real failure? maybe

**Failures**

https://github.com/camunda/zeebe/actions/runs/7180143632/job/19551784799?pr=15420

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Warning:  io.camunda.zeebe.topology.ClusterTopologyManagementIntegrationTest.shouldInitializeCoordinatorFromPeers
Error:    Run 1: ClusterTopologyManagementIntegrationTest.shouldInitializeCoordinatorFromPeers:156->lambda$shouldInitializeCoordinatorFromPeers$5:162 
Expecting actual:
  {10=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=1]}], 11=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=2]}], 12=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=3]}]}
to contain only following keys:
  [1, 2, 0]
keys not found:
  [1, 2, 0]
and keys not expected:
  [12, 11, 10]

</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/13647551/Test.results.for.unit.tests.zip)

**Comment by deepthidevaki** [comment]
What happens here is that a valid topology is overwritten by an uninitialized one received later. This is because of the different ordering of actor tasks than what I expected. To demonstrate 

```
    schedulerRule.submitActor(actor);
    actor
        .actorControl()
        .run(
            () -> {
              LOG.info("Received topology version 1");
              final ActorFuture<Void> processedOne = new CompletableActorFuture<>();
              actor
                  .actorControl()
                  .run(
                      () -> {
                        processedOne.complete(null);
                        LOG.info("Processed topology version 1");
                      });
              processedOne.onComplete(
                  (ignore, error) -> {
                    LOG.info("Mark as initialized and updated local topology to version 1");
                    initialized.set(true);
                  });
            });
    actor
        .actorControl()
        .run(
            () -> {
              LOG.info("Received uninitialized topology");
              final ActorFuture<String> processedOne = new CompletableActorFuture<>();
              actor
                  .actorControl()
                  .run(
                      () -> {
                        if (!initialized.get()) {
                          LOG.info("Processed uninitialized topology");
                          processedOne.complete("uninitialized");
                        } else {
                          processedOne.complete("valid");
                        }
                      });
              processedOne.onComplete(
                  (returned, error) -> LOG.info("Update local topology to {} topology", returned));
            });
    schedulerRule.workUntilDone();
```

The expectation was that uninitialized topology is processed after initialized is set to true. But the result is:

```
10:08:53.094 [zb-actors-0] [] INFO  io.camunda.zeebe.scheduler.ordering.RunnableOrderingTests - Received topology version 1
10:08:53.097 [zb-actors-0] [] INFO  io.camunda.zeebe.scheduler.ordering.RunnableOrderingTests - Processed topology version 1
10:08:53.097 [zb-actors-0] [] INFO  io.camunda.zeebe.scheduler.ordering.RunnableOrderingTests - Received uninitialized topology
10:08:53.097 [zb-actors-0] [] INFO  io.camunda.zeebe.scheduler.ordering.RunnableOrderingTests - Processed uninitialized topology
10:08:53.097 [zb-actors-0] [] INFO  io.camunda.zeebe.scheduler.ordering.RunnableOrderingTests - Mark as initialized and updated local topology to version 1
10:08:53.102 [zb-actors-0] [] INFO  io.camunda.zeebe.scheduler.ordering.RunnableOrderingTests - Update local topology to uninitialized topology
```
As a result, the valid topology got overwritten by an uninitialized one.

The runnable on the future.onComplete is submitted to the end of the queue (which makes sense) so the order of execution. The fix is to refactor the code to ensure that received messages are processed in the expected order.
