### ISSUE TITLE
Intermediate signal throw event should not send a response out

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15649]
**Describe the bug**

It seems the signal broadcast command is always sending responses out. Possibly other commands do the same. This has little impact right now on Zeebe itself because the transport essentially "swallows" the error, e.g. if you send a response with a request ID and stream ID that it doesn't recognize, it simply does nothing. This is still additional, unnecessary work though, copying the response around, serializing it, etc.

This also causes an error in `zeebe-process-test`, where the transport behaves differently and _always_ expects a request for every response sent out, causing [the following error](https://github.com/camunda/zeebe-process-test/issues/1011).

In my opinion, this should be fixed in both places, although the severity is quite low in Zeebe. But the command response writer should simply not add pending responses if the associated command has no request metadata. For example, see the old `CommandProcessImpl`, which does this check.

**To Reproduce**

Add the following to the engine test `SignalIntermediateThrowEventTest.java`:

```java
  @Test
  public void shouldNotSendResponseWhenPartOfBatch() {
    // given
    final var processId = Strings.newRandomValidBpmnId();
    final var process =
        Bpmn.createExecutableProcess(processId)
            .startEvent()
            .intermediateCatchEvent(
                "start", b -> b.message(m -> m.name("start").zeebeCorrelationKey("=businessKey")))
            .intermediateThrowEvent("signal", b -> b.signal("signal"))
            .endEvent()
            .done();
    ENGINE.deployment().withXmlResource(process).deploy();
    final var piKey =
        ENGINE
            .processInstance()
            .ofBpmnProcessId(processId)
            .withVariables(Map.of("businessKey", "42"))
            .create();
    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
                .withProcessInstanceKey(piKey)
                .withElementId("start")
                .limit(1)
                .exists())
        .isTrue();

    // when
    ENGINE.message().withName("start").withCorrelationKey("42").publish();
    assertThat(
            RecordingExporter.signalRecords(SignalIntent.BROADCASTED)
                .withSignalName("signal")
                .limit(1)
                .exists())
        .isTrue();

    // then
    Mockito.verify(ENGINE.getCommandResponseWriter(), Mockito.never())
        .intent(SignalIntent.BROADCASTED)
        .tryWriteResponse(-1, -1);
  }
```

This basically creates a process consisting of `start -> message catch -> signal throw -> end`. The message catch will cause the signal throw to send out a response.

**Expected behavior**

Responses are not sent out if the command has no request metadata.

**Environment:**
- Zeebe Version: 8.3+

**Context**
Support issue: https://jira.camunda.com/browse/SUPPORT-19727

**Comment by npepinpe** [comment]
I've assigned it to the ZPA team because I think the fix could be modifying the `ResultBuilderBackedTypedResponseWriter` basically to simply omit writing responses that have no request metadata, avoiding putting them in the writer in the first place :+1:

**Comment by nicpuppa** [comment]
ZPA Triage:
-  Priority is `upcoming`, because we want to resolve first the issue on zeebe side, before moving on with [ZPT related issue](https://github.com/camunda/zeebe-process-test/issues/1011)
- We think size is `small`
