### ISSUE TITLE
when a partition Prepare transition from LEADER  to FOLLOWER,it will cause jvm crash.

### ISSUE THREAD

**Issue by yitizi** [camunda/zeebe#15657]
**Describe the bug**

here is the hs_err_log:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3d39511172, pid=6, tid=57
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.9+9 (17.0.9+9) (build 17.0.9+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (17.0.9+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# J 10720 c2 org.agrona.concurrent.UnsafeBuffer.getIntVolatile(I)I (30 bytes) @ 0x00007f3d39511172 [0x00007f3d39511120+0x0000000000000052]
#
# Core dump will be written. Default location: /usr/local/camunda-zeebe-8.1.9/core.6
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -XX:ErrorFile=/usr/local/zeebe/data/hs_err_pid%p.log -XX:+UnlockExperimentalVMOptions -Xms8192m -Xmx8192m -Duser.timezone=Asia/Shanghai -Xms128m -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dapp.name=broker -Dapp.pid=6 -Dapp.repo=/usr/local/zeebe/lib -Dapp.home=/usr/local/zeebe -Dbasedir=/usr/local/zeebe io.camunda.zeebe.broker.StandaloneBroker

Host: Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz, 24 cores, 10G, CentOS Linux release 8.5.2111
Time: Tue Dec 19 09:43:00 2023 CST elapsed time: 1122.005443 seconds (0d 0h 18m 42s)

---------------  T H R E A D  ---------------

Current thread (0x00007f3d49717e20):  JavaThread "Broker-1-zb-actors-2" [_thread_in_Java, id=57, stack(0x00007f3d101e2000,0x00007f3d102e3000)]

Stack: [0x00007f3d101e2000,0x00007f3d102e3000],  sp=0x00007f3d102e1570,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 10720 c2 org.agrona.concurrent.UnsafeBuffer.getIntVolatile(I)I (30 bytes) @ 0x00007f3d39511172 [0x00007f3d39511120+0x0000000000000052]
J 9859 c1 io.camunda.zeebe.dispatcher.impl.log.LogBuffer.getActivePartitionIdVolatile()I (11 bytes) @ 0x00007f3d320e11d4 [0x00007f3d320e1140+0x0000000000000094]
j  io.camunda.zeebe.dispatcher.Dispatcher.offer(Ljava/util/function/BiFunction;II)J+25
J 12465 c2 io.camunda.zeebe.logstreams.impl.log.LogStreamWriterImpl.tryWrite()J (221 bytes) @ 0x00007f3d398015cc [0x00007f3d39801100+0x00000000000004cc]
J 12352 c2 io.camunda.zeebe.broker.transport.commandapi.CommandApiRequestHandler.writeCommand(JLio/camunda/zeebe/protocol/impl/record/RecordMetadata;Lio/camunda/zeebe/msgpack/UnpackedObject;Lio/camunda/zeebe/logstreams/log/LogStreamRecordWriter;)Z (70 bytes) @ 0x00007f3d397d652c [0x00007f3d397d6340+0x00000000000001ec]
J 12194 c2 io.camunda.zeebe.broker.transport.commandapi.CommandApiRequestHandler.handleExecuteCommandRequest(IJLio/camunda/zeebe/broker/transport/commandapi/CommandApiRequestReader;Lio/camunda/zeebe/broker/transport/commandapi/CommandApiResponseWriter;Lio/camunda/zeebe/broker/transport/ErrorResponseWriter;)Lio/camunda/zeebe/util/Either; (391 bytes) @ 0x00007f3d397ae224 [0x00007f3d397adde0+0x0000000000000444]
J 11843 c2 io.camunda.zeebe.broker.transport.AsyncApiRequestHandler$$Lambda$1792+0x00007f3cc4916228.run()V (32 bytes) @ 0x00007f3d3911e3e0 [0x00007f3d3911d460+0x0000000000000f80]
J 9096 c2 io.camunda.zeebe.scheduler.ActorJob.execute(Lio/camunda/zeebe/scheduler/ActorThread;)V (199 bytes) @ 0x00007f3d393e6bd8 [0x00007f3d393e6040+0x0000000000000b98]
J 10521 c2 io.camunda.zeebe.scheduler.ActorTask.execute(Lio/camunda/zeebe/scheduler/ActorThread;)Z (195 bytes) @ 0x00007f3d394f0fb4 [0x00007f3d394f0ea0+0x0000000000000114]
J 9299 c2 io.camunda.zeebe.scheduler.ActorThread.doWork()V (153 bytes) @ 0x00007f3d390f003c [0x00007f3d390efa60+0x00000000000005dc]
J 6930% c2 io.camunda.zeebe.scheduler.ActorThread.run()V (61 bytes) @ 0x00007f3d3926110c [0x00007f3d39261040+0x00000000000000cc]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x829765]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*)+0x315
V  [libjvm.so+0x82af5b]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, JavaThread*)+0x1cb
V  [libjvm.so+0x8f7843]  thread_entry(JavaThread*, JavaThread*)+0xa3
V  [libjvm.so+0xe5ef76]  JavaThread::thread_main_inner()+0x196
V  [libjvm.so+0xe629b0]  Thread::call_run()+0xc0
V  [libjvm.so+0xc23e91]  thread_native_entry(Thread*)+0xe1

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007f3accfff510

Registers:
RAX=0x00007f3d0af8de68, RBX=0x00007f3d0af8de68, RCX=0x0000000603299808, RDX=0x0000000000000080
RSP=0x00007f3d102e1570, RBP=0x00007f3d102e1658, RSI=0x0000000603299a08, RDI=0x00007f3d0bb32dd0
R8 =0x0000000000000000, R9 =0x00007f3c34027dd2, R10=0x00007f3accfff510, R11=0x0000000000000000
R12=0x0000000000000000, R13=0x00007f3d102e15f8, R14=0x00007f3d0bb3b8f8, R15=0x00007f3d49717e20
RIP=0x00007f3d39511172, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Register to memory mapping:

RAX={method} {0x00007f3d0af8de68} 'getActivePartitionIdVolatile' '()I' in 'io/camunda/zeebe/dispatcher/impl/log/LogBuffer'
RBX={method} {0x00007f3d0af8de68} 'getActivePartitionIdVolatile' '()I' in 'io/camunda/zeebe/dispatcher/impl/log/LogBuffer'
RCX=0x0000000603299808 is an oop: io.camunda.zeebe.dispatcher.impl.log.LogBuffer 
{0x0000000603299808} - klass: 'io/camunda/zeebe/dispatcher/impl/log/LogBuffer'
 - ---- fields (total size 4 words):
 - protected final 'partitionSize' 'I' @12  8388608 (800000)
 - protected final 'rawBuffer' 'Lio/camunda/zeebe/util/allocation/AllocatedBuffer;' @16  a 'io/camunda/zeebe/util/allocation/AllocatedDirectBuffer'{0x0000000603299828} (c0653305)
 - protected final 'partitions' '[Lio/camunda/zeebe/dispatcher/impl/log/LogBufferPartition;' @20  a 'io/camunda/zeebe/dispatcher/impl/log/LogBufferPartition'[3] {0x00000006032998c8} (c0653319)
 - protected final 'metadataBuffer' 'Lorg/agrona/concurrent/UnsafeBuffer;' @24  a 'org/agrona/concurrent/UnsafeBuffer'{0x0000000603299a08} (c0653341)
RDX=0x0000000000000080 is an unknown value
RSP=0x00007f3d102e1570 is pointing into the stack for thread: 0x00007f3d49717e20
RBP=0x00007f3d102e1658 is pointing into the stack for thread: 0x00007f3d49717e20
RSI=0x0000000603299a08 is an oop: org.agrona.concurrent.UnsafeBuffer 
{0x0000000603299a08} - klass: 'org/agrona/concurrent/UnsafeBuffer'
 - ---- fields (total size 4 words):
 - private 'capacity' 'I' @12  260 (104)
 - private 'addressOffset' 'J' @16  139890524157072 (ccfff490 7f3a)
 - private 'byteArray' '[B' @24  NULL (0)
 - private 'byteBuffer' 'Ljava/nio/ByteBuffer;' @28  a 'java/nio/DirectByteBuffer'{0x0000000603299840} (c0653308)
RDI=0x00007f3d0bb32dd0 is pointing into metadata
R8 =0x0 is NULL
R9 =0x00007f3c34027dd2 points into unknown readable memory: 00 00 00 00 00 00
R10=0x00007f3accfff510 is an unknown value
R11=0x0 is NULL
R12=0x0 is NULL
R13=0x00007f3d102e15f8 is pointing into the stack for thread: 0x00007f3d49717e20
R14=0x00007f3d0bb3b8f8 is pointing into metadata
R15=0x00007f3d49717e20 is a thread

**To Reproduce**

i install zeebe 8.1.9 version in a k8s cluster and store the data directory to a remote nfs system.
when i curl the rebalance admin interface,the broker crash.and it happens in raft selection,when leader changes.
curl --location --request POST 'http://172.36.10.163:9600/actuator/rebalance'

**Expected behavior**

i just want the partition balance,and the broker can stable.

**Log/Stacktrace**
2023-12-19 09:43:00.168 [Broker-1-LogStream-3] [Broker-1-zb-actors-1] INFO \n\n      io.camunda.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-3 close 2 readers\n
2023-12-19 09:43:00.169 [Broker-1-ZeebePartition-3] [Broker-1-zb-actors-1] INFO \n\n      io.camunda.zeebe.broker.system - Preparing transition from LEADER on term 30011 completed\n
2023-12-19 09:43:00.169 [Broker-1-ZeebePartition-3] [Broker-1-zb-actors-1] INFO \n\n      io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 30011 starting\n
2023-12-19 09:43:00.169 [Broker-1-ZeebePartition-3] [Broker-1-zb-actors-1] INFO \n\n      io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 30011 - transitioning LogStorage\n
2023-12-19 09:43:00.169 [Broker-1-ZeebePartition-3] [Broker-1-zb-actors-1] INFO \n\n      io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 30011 - transitioning LogStream\n
2023-12-19 09:43:00.168 [Broker-1-ZeebePartition-3] [Broker-1-zb-actors-1] INFO \n\n      io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 30011 to FOLLOWER - preparing LogStorage\n
2023-12-19 09:43:00.169 [Broker-1-ZeebePartition-3] [Broker-1-zb-actors-1] INFO \n\n      io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 30011 - transitioning ZeebeDb\n
2023-12-19 09:43:00.185 [Broker-1-LogStream-1] [Broker-1-zb-actors-0] INFO \n\n      io.camunda.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-1 close 2 readers\n
2023-12-19 09:43:00.185 [logstream-raft-partition-partition-1-write-buffer] [Broker-1-zb-actors-0] DEBUG\n\n      io.camunda.zeebe.dispatcher - Dispatcher closed\n\n#\n\n# A fatal error has been detected by the Java Runtime Environment:\n\n#\n\n#  SIGSEGV (0xb) at pc=0x00007f3d39511172, pid=6, tid=57\n\n#\n\n# JRE version: OpenJDK Runtime Environment Temurin-17.0.9+9 (17.0.9+9) (build 17.0.9+9)\n\n# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (17.0.9+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)\n\n# Problematic frame:\n\n# J 10720 c2 org.agrona.concurrent.UnsafeBuffer.getIntVolatile(I)I (30 bytes) @ 0x00007f3d39511172 [0x00007f3d39511120+0x0000000000000052]\n\n#\n\n# Core dump will be written. Default location: /usr/local/camunda-zeebe-8.1.9/core.6\n\n#\n

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: CentOS Linux release 8.5.2111
- Zeebe Version: 8.1.9
- Configuration: {
  "network" : {
    "host" : "zeebe-1.zeebe.dev.svc.cluster.local",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "zeebe-1.zeebe.dev.svc.cluster.local",
    "commandApi" : {
      "host" : "zeebe-1.zeebe.dev.svc.cluster.local",
      "port" : 26501,
      "advertisedHost" : "zeebe-1.zeebe.dev.svc.cluster.local",
      "advertisedPort" : 26501,
      "address" : "zeebe-1.zeebe.dev.svc.cluster.local:26501",
      "advertisedAddress" : "zeebe-1.zeebe.dev.svc.cluster.local:26501"
    },
    "internalApi" : {
      "host" : "zeebe-1.zeebe.dev.svc.cluster.local",
      "port" : 26502,
      "advertisedHost" : "zeebe-1.zeebe.dev.svc.cluster.local",
      "advertisedPort" : 26502,
      "address" : "zeebe-1.zeebe.dev.svc.cluster.local:26502",
      "advertisedAddress" : "zeebe-1.zeebe.dev.svc.cluster.local:26502"
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "zeebe-0.zeebe.dev.svc.cluster.local:26502", "zeebe-1.zeebe.dev.svc.cluster.local:26502", "zeebe-2.zeebe.dev.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 1,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster",
    "heartbeatInterval" : "PT0.25S",
    "electionTimeout" : "PT2.5S",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    },
    "raft" : {
      "enablePriorityElection" : true
    },
    "messageCompression" : "NONE"
  },
  "threads" : {
    "cpuThreadCount" : 3,
    "ioThreadCount" : 1
  },
  "data" : {
    "directory" : "/usr/local/zeebe/data",
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT12M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "backup" : {
      "store" : "NONE",
      "s3" : {
        "bucketName" : null,
        "endpoint" : null,
        "region" : null,
        "accessKey" : null,
        "secretKey" : null,
        "apiCallTimeout" : "PT3M"
      }
    },
    "logSegmentSizeInBytes" : 536870912,
    "freeDiskSpaceCommandWatermark" : 59423242322,
    "freeDiskSpaceReplicationWatermark" : 19807747441
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.camunda.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : "http://192.168.1.25:9201",
        "bulk" : {
          "delay" : 5,
          "size" : 1000
        },
        "index" : {
          "prefix" : "zeebe-record",
          "createTemplate" : true,
          "command" : false,
          "event" : true,
          "rejection" : false,
          "deployment" : true,
          "incident" : true,
          "job" : true,
          "message" : true,
          "messageSubscription" : true,
          "raft" : false,
          "workflowInstance" : true,
          "workflowInstanceSubscription" : true
        }
      },
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "zeebe-gateway",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "initialContactPoints" : [ "172.36.10.163:26502" ],
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "advertisedHost" : "0.0.0.0",
      "port" : 26502,
      "advertisedPort" : 26502,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      },
      "security" : {
        "enabled" : false,
        "certificateChainPath" : null,
        "privateKeyPath" : null
      },
      "messageCompression" : "NONE"
    },
    "threads" : {
      "managementThreads" : 1
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "interceptors" : [ ],
    "initialized" : true,
    "enable" : false
  },
  "backpressure" : {
    "enabled" : false,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "32KB",
    "disableExplicitRaftFlush" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "enableStatistics" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1,
      "maxWriteBufferNumber" : 6,
      "minWriteBufferNumberToMerge" : 3,
      "ioRateBytesPerSecond" : 0,
      "disableWal" : false
    },
    "raft" : {
      "requestTimeout" : "PT5S",
      "maxQuorumResponseTimeout" : "PT0S",
      "minStepDownFailureCount" : 3,
      "preferSnapshotReplicationThreshold" : 100,
      "preallocateSegmentFiles" : true
    },
    "partitioning" : {
      "scheme" : "FIXED",
      "fixed" : [ {
        "partitionId" : 1,
        "nodes" : [ {
          "nodeId" : 0,
          "priority" : 3
        }, {
          "nodeId" : 1,
          "priority" : 2
        }, {
          "nodeId" : 2,
          "priority" : 1
        } ]
      }, {
        "partitionId" : 2,
        "nodes" : [ {
          "nodeId" : 0,
          "priority" : 1
        }, {
          "nodeId" : 1,
          "priority" : 3
        }, {
          "nodeId" : 2,
          "priority" : 2
        } ]
      }, {
        "partitionId" : 3,
        "nodes" : [ {
          "nodeId" : 0,
          "priority" : 1
        }, {
          "nodeId" : 1,
          "priority" : 2
        }, {
          "nodeId" : 2,
          "priority" : 3
        } ]
      } ]
    },
    "queryApi" : {
      "enabled" : false
    },
    "consistencyChecks" : {
      "enablePreconditions" : false,
      "enableForeignKeyChecks" : false,
      "settings" : {
        "enablePreconditions" : false,
        "enableForeignKeyChecks" : false
      }
    },
    "engine" : {
      "messages" : {
        "ttlCheckerBatchLimit" : 2147483647,
        "ttlCheckerInterval" : "PT1M"
      }
    },
    "features" : {
      "enableYieldingDueDateChecker" : false,
      "enableActorMetrics" : false,
      "enableBackup" : false,
      "enableMessageTtlCheckerAsync" : false
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "executionMetricsExporterEnabled" : false,
  "processing" : {
    "maxCommandsInBatch" : 1
  }
}

**Comment by oleschoenburg** [comment]
Hey @yitizi, this error was often observed when memory usage was high. It's fixed in https://github.com/camunda/zeebe/issues/10906 and shouldn't occur again if you upgrade to 8.2 or newer.
