### ISSUE TITLE
EvaluateDecisionTest.shouldMapRequestAndResponse is flaky

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15662]
**Summary**

- How often does the test fail? 
  - So far twice
- Does it block your work?
  - No
- Do we suspect that it is a real failure?
  - No

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
 Error:    Run 1: EvaluateDecisionTest.shouldMapRequestAndResponse:92 
expected: 1
 but was: 17
Error:    Run 2: EvaluateDecisionTest.shouldMapRequestAndResponse:92 
expected: 1
 but was: 19
Error:    Run 3: EvaluateDecisionTest.shouldMapRequestAndResponse:92 
expected: 1
 but was: 20
Error:    Run 4: EvaluateDecisionTest.shouldMapRequestAndResponse:92 
expected: 1
 but was: 21
</pre>
</details>

**Hypotheses**

Can't tell, not my area of expertise :upside_down_face: 

**Logs**

https://github.com/camunda/zeebe/actions/runs/7261544437/job/19782956153

**Comment by npepinpe** [comment]
Happened again here: https://github.com/camunda/zeebe/actions/runs/7298151284/job/19888606516

**Comment by Zelldon** [comment]
This is failing quite often, for me at least.

The failures are also quite "funny" looks like we accumulating state?

```
Error:  Failures: 
Error:  io.camunda.zeebe.gateway.api.decision.EvaluateDecisionTest.shouldMapRequestAndResponse
Error:    Run 1: EvaluateDecisionTest.shouldMapRequestAndResponse:93 
expected: 1
 but was: 17
Error:    Run 2: EvaluateDecisionTest.shouldMapRequestAndResponse:93 
expected: 1
 but was: 19
Error:    Run 3: EvaluateDecisionTest.shouldMapRequestAndResponse:93 
expected: 1
 but was: 20
Error:    Run 4: EvaluateDecisionTest.shouldMapRequestAndResponse:93 
expected: 1
 but was: 21
```

**Comment by megglos** [comment]
looking at the log it seems the object used for the response is mutated by something, with every run the getEvaluatedDecisionsCount value increases :smile: 
![image](https://github.com/camunda/zeebe/assets/209518/4017a6d9-b332-458e-9576-7f670c174f97)
