### ISSUE TITLE
Do not always run migration 

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#15678]
**Description**

Right now we run migrations every time we restart or change a transition, this can become quite a problem if we add more and more migrations, especially since it is often not easy to determine whether migration needs to be run or not (not based on the data we store in the column families).

The newest example is https://github.com/camunda/zeebe/pull/15443 where we always run the migration on failed jobs, to create missing job backoff entries.

I think this can be easily avoided if we simply write the Broker version into the state when this state was last time touched. 

Example:

Running at 8.3.5 we write into the state (default CF) the version 8.3.5. When upgrading we check the version in the state against our current broker version, if we see a mismatch we execute the migration if they are equal we don't need to run the migrations.

This can be done in the MigrationTransitionStep https://github.com/camunda/zeebe/blob/main/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/MigrationTransitionStep.java

If we find no version, we know we need to migrate as well. After migration we always write the newest version to the state.

Additionally: We can avoid to start the follower with a newer snapshot, this might corrupt the data of the state and currently we have no way to detect this, but with the version we could stop the transition.

**Comment by npepinpe** [comment]
From our side, this is something that is within the engine domain. We're happy to support any solution there though. My understanding is this can impact availability as it may slowdown the recovery process on transition if we have to re-run expensive migrations.

**Comment by korthout** [comment]
> we simply write the Broker version into the state 

This sounds like a good idea and something that we've tried before, but it led to issues. See:
- https://github.com/camunda/zeebe/issues/13763
- https://github.com/camunda/zeebe/pull/13780
- https://github.com/camunda/zeebe/issues/14406
- https://github.com/camunda/zeebe/pull/14574

We should carefully consider how to store this information in a way that ensures leaders and followers deterministically replay events.

**Comment by oleschoenburg** [comment]
In my opinion the underlying issue of https://github.com/camunda/zeebe/issues/14406 was that brokers happily use snapshots that were modified by newer broker, even though there's no guarantee that the old broker can actually use the data in that snapshot.

I'd suggest that we start versioning the runtime state and use that version to:
1. Decide which migrations need to run
2. Decide if a broker can work with the runtime state or not
