### ISSUE TITLE
Earlier join and leave responses to reduce risk of unavailability

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#15679]
Currently, responses to joining and leaving a partition are only sent out once the final configuration (after joint consensus) is committed. This is too late, increasing the risk of unavailability during joint consensus.

We should be able to send the response as soon as the joint consensus configuration is committed.

**Comment by oleschoenburg** [comment]
It's not as easy as I first thought, as explained by @deepthidevaki here: https://github.com/camunda/zeebe/pull/15686#issuecomment-1867350216

As an alternative, we could improve the retry logic when trying to join. Currently, when the leader stops, the join request will simply fail, leading to a partition shutdown and eventual retry. Instead we could handle a leader shutdown gracefully be responding with a useful error code and then handling this on the newly joining member by giving it more time for the join to be successful.

**Comment by megglos** [comment]
ZDP-Planning:
* was considered a low hanging fruit first but turned out not to be
* closing as not considered urgent enough
