### ISSUE TITLE
RaftServer Looping on Receiving Snapshots Causing Partitions to Become Inactive

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#15732]
**Describe the bug**

In `release-8-4-0-alpha2` release benchmark cluster, partitions put to inactive. As seen in the [GCP logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22release-8-4-0-alpha2%22%0Aresource.labels.pod_name%3D%22release-8-4-0-alpha2-zeebe-0%22%20severity%3E%3DDEFAULT;pinnedLogId=2023-12-28T10:25:52.656046705Z%2Fnqs2gn25l1c5bnh9;cursorTimestamp=2023-12-28T10:26:01.638857086Z;duration=PT3H?project=zeebe-io) it is because of looping on receiving snapshot:

1) Started receiving snapshot
2) Rolling back snapshot
3) Aborting received snapshot
4) Go to step 1

**Expected behavior**

Snapshots should be applied successfully.

**Log/Stacktrace**

No errors but consecutive warnings:

<details><summary>Full Stacktrace</summary>
 <p>

```
INFO 2023-12-28T10:25:52.656046705Z [resource.labels.containerName: zeebe] RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Started receiving new snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/376317134-1-3378576618-3378574702, snapshotStore=SnapshotStore-2, metadata=FileBasedSnapshotId{index=376317134, term=1, processedPosition=3378576618, exporterPosition=3378574702}} from 1
INFO 2023-12-28T10:25:57.103184610Z [resource.labels.containerName: zeebe] RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Rolling back snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/376317134-1-3378576618-3378574702, snapshotStore=SnapshotStore-2, metadata=FileBasedSnapshotId{index=376317134, term=1, processedPosition=3378576618, exporterPosition=3378574702}}
DEBUG 2023-12-28T10:25:57.109941836Z [resource.labels.containerName: zeebe] Aborting received snapshot in dir /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/376317134-1-3378576618-3378574702
INFO 2023-12-28T10:25:57.137087534Z [resource.labels.containerName: zeebe] RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Started receiving new snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/376317134-1-3378576618-3378574702, snapshotStore=SnapshotStore-2, metadata=FileBasedSnapshotId{index=376317134, term=1, processedPosition=3378576618, exporterPosition=3378574702}} from 1

```

</p>
</details>

**Environment:**
- OS:  Linux (zeebe-io)
- Zeebe Version:  8-4-0-alpha2
- Configuration:

**Comment by npepinpe** [comment]
I checked, and we have a bunch of files between 50-100MB, so it might be the time out issue we've faced in the past. https://github.com/camunda/zeebe/issues/11496
