### ISSUE TITLE
Migrate embedded sub process instance

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15923]
### Out of Scope:
- Migrating event subprocesses
- Changing the scope of subprocess. E.g. migrating service task A to B is not possible for the following example:
<img width="564" alt="Screenshot 2024-03-06 at 15 10 07" src="https://github.com/camunda/zeebe/assets/124141078/d78d44f0-2480-44f1-896c-58d70bb2ff3d">
<img width="448" alt="Screenshot 2024-03-06 at 15 10 15" src="https://github.com/camunda/zeebe/assets/124141078/fc0340e0-5d61-486b-86ba-2aea5cb62b4d">

### Update supported elements for subprocess:

In the migration implementation, we treat subprocesses as any other element in the process. That means, adding subprocess as supported element type should work out of the box.
- Add `BpmnElementType.SUB_PROCESS` to supported elements in `ProcessInstanceMigrationPreconditionChecker` class

### Add test cases:
- Migrating subprocess for the same flow scope
- Migrating nested subprocesses
- Migrating subprocess with boundary events in the source (assert boundary event deleted during the migration)
- Expect migration rejection for subprocess with boundary events in the target process definition
- Expect migration rejection for unmapped active subprocess

### Documentation:
- Add a section that shows migrating a subprocess to [process instance migration documentation](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration)
- Mention that subprocess ids should also be included in the migration command.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/16744
- [ ] https://github.com/camunda/camunda-docs/issues/3417
```

**Comment by korthout** [comment]
When we add support for this, please remember that boundary event checks currently don't consider subprocesses.

We only require that the migrated element instance does not have boundary events. We don't check the sub-process(es) it is nested in.

**Comment by berkaycanbc** [comment]
@korthout could you please take a look at the description I filled? Would be good to hear your thoughts especially for possible additional test cases.

**Comment by korthout** [comment]
Thanks @berkaycanbc, for this great breakdown!

I'd like to see the following test cases:
1. Expect migration rejection for unmapped active subprocess
2. Expect migration rejection for unmapped new subprocess in the target
   - This is probably already covered by an existing test somewhere, but good to mention
3. Expect migration rejection for mapped subprocess with boundary events in the target process
   - You appear to cover this in your draft PR already

About the documentation, what would we describe there? It's good to consider this first. Is there a specific case we can highlight with this? Or is there any new information for the user? Otherwise, I'd reduce this to changing the limitations.

**Comment by berkaycanbc** [comment]
@korthout Thanks for the feedback!

I assumed, the first 2 test cases you mentioned are covered already with the current rejections but not for subprocesses. I agree, it makes sense to be more explicit and test those rejections against subprocess migration. 👍 

As we did for the incident migration, we can demonstrate migrating a simple subprocess and mention the limitations for changing scope and event subprocesses. Additionally, in the existing documentation, there is no limitation mentioned for embedded subprocess migration, so nothing to change. WDYT?

**Comment by berkaycanbc** [comment]
> Expect migration rejection for unmapped new subprocess in the target

@korthout As you mentioned, this case should already be covered with the test case where we assert the scope change:

https://github.com/camunda/zeebe/blob/f02b6cbfc681d8a15911e7745a3395c991364300/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/MigrateProcessInstanceRejectionTest.java#L310

so, I will skip it.

**Comment by korthout** [comment]
>As we did for the incident migration, we can demonstrate migrating a simple subprocess and mention the limitations for changing scope and event subprocesses. 

Makes sense to me

>Additionally, in the existing documentation, there is no limitation mentioned for embedded subprocess migration, so nothing to change. WDYT?

Good point 👍
