### ISSUE TITLE
Support User Tasks in Instance Migration API Definition

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15961]
We must describe in the API definition how we communicate to Operate/Optimize/Tasklist that a native User Task is migrated.

**Comment by korthout** [comment]
[A short section regarding native User Tasks](https://docs.google.com/document/d/1V_sZQmr6KHFuAxovkxCLY4Kb38t3_r68TihCnHqhIbw/edit#heading=h.f552tpml2wzy) has been added to the API Definition.

**Comment by berkaycanbc** [comment]
@korthout Nice and short description! 🚀 

🔧 One addition would be to mention migration for existing user tasks. Basically a very short summary of what you've described here https://github.com/camunda/zeebe/issues/15919#issue-2081612738.

**Comment by korthout** [comment]
Great point @berkaycanbc, I've added it
