### ISSUE TITLE
Disbalanced processing in Zeebe partitions

### ISSUE THREAD

**Issue by aanodin** [camunda/zeebe#16011]
We have a Zeebe 8.2.19 cluster with 4 brokers and 32 partitions. All of our processes are created using PublishMessage command and Start Events, not CreateProcessInstance command. 

Documentation says that, on the one hand:
https://docs.camunda.io/docs/components/concepts/messages/
`When a client publishes a message to trigger a message start event, the message is forwarded to a partition based on the correlation key of the message. The process instance is created on the same partition where the message is published.`

On the other hand, message correlation rules say that we must use correlation key to have only one process instance created for one message:
https://docs.camunda.io/docs/components/concepts/messages/#message-correlation-overview
https://docs.camunda.io/docs/components/concepts/messages/#single-instance

The correlation key used is GUID. 

So the question is how to achieve all partitions to process as much as possible equal count of messages per seconds, and we not to lose single instance guarantee at the same time.

**Comment by oleschoenburg** [comment]
> So the question is how to achieve all partitions to process as much as possible equal count of messages per seconds, and we not to lose single instance guarantee at the same time.

This should already be the case if you create your processes with MessageStartEvent and use a random GUID as correlation key. Zeebe hashes the correlation key to decide on which partition to create the process. As long as you keep using the same GUID as correlation key, all further messages will be published on the same partition where the process instance was created.

**Comment by aanodin** [comment]
@oleschoenburg of course our GUIDs are randomly generated using standard algorithms. 
Can you please describe what hash algorithm is used inside Zeebe? Does it provide good enough linear distribution? How the result of hashing is used to determine partition number?

**Comment by oleschoenburg** [comment]
Here's the code for it: https://github.com/camunda/zeebe/blob/1edfe4f762ef700885859bf87e1370963d3448a1/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/SubscriptionUtil.java#L46-L45

as you can see we use a hashcode calculation similar to `java.lang.String#hashCode` and then map it over all partitions with a simple modulo.

**Comment by aanodin** [comment]
@oleschoenburg ok, I've checked this algorithm and see that it gives good distribution.
![image](https://github.com/camunda/zeebe/assets/6254014/2c8a01a0-0906-49f6-98b3-86970a920ec7)
Looks like that our problem is somewhere else.
