### ISSUE TITLE
Respect quiet period before shutting down the gateway

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#16024]
**Description**

At the moment, the gateway will shutdown immediately when it receives a SIGTERM. This doesn't allow for graceful handling of client connections, often resulting in 502s if a load balancer is set up in front of the gateway.

We should instead respect a configurable quiet period when we receive a SIGTERM, and refusing new connections but giving a timeout for on-going ones to finish, before shutting down.

**Related**
[SUPPORT-20158](https://jira.camunda.com/browse/SUPPORT-20158)
[SUPPORT-20232](https://jira.camunda.com/browse/SUPPORT-20232)

**Comment by Zelldon** [comment]
Related https://app.slack.com/client/T0PM0P1SA/C06EVGFDMB7

**Comment by hisImminence** [comment]
Hi team, the customer was asking for an ETA on this one. Do you have an estimate? Will it be in 8.5 or do you plan a patch for 8.4?

**Comment by npepinpe** [comment]
The plan was to have it done for 8.5 (and backported to 8.4 but released at the same time). Has the urgency changed?

**Comment by hisImminence** [comment]
Thanks @npepinpe!

> Has the urgency changed?

Nope, I just think support missed the estimate of the fix timeline ;) will report back in case (but assume that everything is clear now)!

**Comment by npepinpe** [comment]
Possibly related to https://github.com/camunda/zeebe/issues/16063

**Comment by oleschoenburg** [comment]
Ideally we'd first stop accepting new gRPC requests while still being able to respond to requests. This would help to avoid failed job activation that can occur when gRPC is already stopped but the gateway is still receiving responses from the broker.

**Comment by oleschoenburg** [comment]
Somewhat related to https://jira.camunda.com/browse/SUPPORT-20232

**Comment by megglos** [comment]
ZDP-Planning:
- no capacity this iteration, rough estimate is 1 full-day of work
- grace/quiet period needs to be configurable

**Comment by megglos** [comment]
was mentioned to be released for 8.5.0 in this uspport case jira.camunda.com/browse/SUPPORT-20158
