### ISSUE TITLE
Add `Complete task` REST endpoint

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#16118]
**Description**

* Add REST endpoint `POST v1/user-tasks/{userTaskKey}/completion`.
* Validate the input data
  * The `userTaskKey` is required and must be a positive number.
  * The `variables` are optional and a JSON document that can contain any key-value pairs.
  * The `action` is optional and can be any String value.
* Create a `UserTaskRecord` with the `userTaskKey`, `variables`, and `action` attributes from the invocation.
* Create a `UserTask.COMPLETE` command with the created user task record.
* Return a 204 without content in case of success.
* Return a 404 if the user task is not found (does not exist or insufficient tenant access).

**Comment by tmetzke** [comment]
@npepinpe and @koevskinikola, the REST endpoint definition for the COMPLETE user task. Let me know if anything is missing or not specific enough.

The `variables` would ideally be a proper JSON object, so users can provide a real JSON instead of a String representing an escaped JSON document. But I don't know if this is possible with out REST infrastructure.

**Comment by npepinpe** [comment]
It's not a problem in theory, but it's very ugly with the OpenAPI generator to pass a free-form JSON, it ends up as a plain `Object`. I think we can work around it though :+1:

**Comment by tmetzke** [comment]
OK, I see 👍 Let's use this as the "guinea pig" endpoint then to try and see how well that works.
