### ISSUE TITLE
Zeebe restore uses the same nodeId for all nodes

### ISSUE THREAD

**Issue by jpan8866** [camunda/zeebe#16151]
**Describe the bug**
I have a Camunda stack deployed using Helm on OpenShift with 3 Zeebe brokers. I am trying to trace an error where after a successful restore of a newly deployed stack, I am unable to create new instances of restored workflows, failing with the error: `io.grpc.StatusRuntimeException: NOT_FOUND: Command 'CREATE' rejected with code 'NOT_FOUND': Expected to find process definition with process ID 'Process_0ph32h2' and version '2', but none found`

The situation of the cluster post-restore is as follows:

Success points:

- Restored workflows and previous instances are visible in operate and optimize
- Restored workflows can be listed using connector’s inbound endpoint (Does this reach Zeebe to retrieve the workflows?)

Failure points:

- Deploying a new workflow to Zeebe returns 200 successful, but it does not appear in operate.
- Creating an instance of the above new workflow returns successful, but the instances do not appear in operate and optimize.
- Creation of an instance of an existing workflow (i.e. one that was restored from the backup) fails even though it can be listed by the inbound endpoint

Other info:
The cluster size, partitions count and replication factor are identical to that in the backup
All 3 partitions are up and healthy after restoration

![zeebe_partitions](https://github.com/camunda/zeebe/assets/79892196/e041b922-0746-4acb-bc01-01b4619e8490)

**To Reproduce**

Restore a newly deployed Camunda stack. The backup and restore steps are followed exactly as provided in official Camunda documentation

Zeebe is restored using the following initScript:

zeebe:
  env:
    - name: ZEEBE_BROKER_DATA_BACKUP_STORE
      value: S3
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME
      value: YOUR_BUCKET_NAME
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_BASEPATH
      value: YOUR_S3_BUCKET_BASEPATH #zeebe-backup
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT
      value: YOUR_S3_BUCKET_ENDPOINT #https://s3.eu-central-1.amazonaws.com/
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_REGION
      value: YOUR_S3_BUCKET_REGION #eu-central-1
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY
      value: YOUR_S3_BUCKET_ACCESS_KEY
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY
      value: YOUR_S3_BUCKET_SECRET_KEY
  extraInitContainers:
    - name: zeebe-restore
      image: camunda/zeebe
      command: [ "/bin/bash"]
      args: [ "-c" ,"export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_NAME##*-}};
                   env;
                   echo ClusterId is $ZEEBE_BROKER_CLUSTER_NODEID;
                   if [ ${ZEEBE_RESTORE} = true ];
                   then
                     ls -laR /usr/local/zeebe/data;
                     rm -rf /usr/local/zeebe/data/lost+found;
                     exec /usr/local/zeebe/bin/restore --backupId=${ZEEBE_RESTORE_FROM_BACKUP_ID};
                   fi"]
      env:
        - name: K8S_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
          value: "3"
        - name: ZEEBE_BROKER_CLUSTER_CLUSTERSIZE
          value: "3"
        - name: ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
          value: "3"
        - name: ZEEBE_BROKER_DATA_BACKUP_STORE
          value: S3
        - name: ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME
          value: YOUR_BUCKET_NAME
        - name: ZEEBE_BROKER_DATA_BACKUP_S3_BASEPATH
          value: YOUR_S3_BUCKET_BASEPATH #zeebe-backup
        - name: ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT
          value: YOUR_S3_BUCKET_ENDPOINT #https://s3.eu-central-1.amazonaws.com/
        - name: ZEEBE_BROKER_DATA_BACKUP_S3_REGION
          value: YOUR_S3_BUCKET_REGION #eu-central-1
        - name: ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY
          value: YOUR_S3_BUCKET_ACCESS_KEY
        - name: ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY
          value: YOUR_S3_BUCKET_SECRET_KEY
        - name: ZEEBE_RESTORE_FROM_BACKUP_ID
          value: "1"
        - name: ZEEBE_RESTORE
          value: "true"

**Expected behavior**

Able to create new instances of restored workflows. Able to deploy new workflows and see them in operate and optimize

**Log/Stacktrace**

One thing I noticed is that the restore process always uses `nodeId=1` for all three of the brokers. Please advise on whether this is normal. It would seem that ZEEBE_BROKER_CLUSTER_NODEID is not being picked up by the restore script.

```
Restoring BackupIdentifierImpl[nodeId=1, partitionId=3, checkpointId=1706486410] to /usr/local/zeebe/data/raft-partition/partitions/3/restoring-1706486410
```

</p>
</details>

**Environment:**
- OS: Linux
- Zeebe Version: 8.3.2
- Configuration: cluster size = partitions count = replication factor = 3

**Comment by oleschoenburg** [comment]
One issue here is that the init container you are using to restore is not mounting the Zeebe disks. Effectively you are restoring data into temporary disks and throwing away the result. After this, the Zeebe brokers start with an empty state which is why you are not able to use previously deployed process models.

Regarding your second point where the nodeId appears to be set wrongly: I suspect that this expression is not correct: ` "export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_NAME##*-}}`.
I see that you added an echo of the `ZEEBE_BROKER_CLUSTER_NODEID` variable, could you confirm that this is set correctly, i.e. has values from 1 to 3?

**Comment by jpan8866** [comment]
Thank you @oleschoenburg for pointing that out, that is indeed the root cause. I've been scratching my head for a while. Everything worked after adding the following to my init container:
```
volumeMounts:
        - name: config
          mountPath: /usr/local/bin/startup.sh
          subPath: startup.sh
        - name: data
          mountPath: /usr/local/zeebe/data
        - name: exporters
          mountPath: /exporters
        - name: tmp
          mountPath: /tmp
```

I had values 0 to 2 for Cluster Node ID. But even for ZEEBE_BROKER_CLUSTER_NODEID=2, it restored with nodeId=1.
Everything is working but there is the following behaviour which I am not sure if unexpected:

- For a given node, backups of two different nodeId's are downloaded and restored:

![image](https://github.com/camunda/zeebe/assets/79892196/97fc8fec-4bdd-4a7c-99a0-9bf10f38748d)

- For one of my nodes, nothing is restored at all:

![image](https://github.com/camunda/zeebe/assets/79892196/50f5b52e-b0b9-4d47-8753-11a2529a69b0)



Also, can you please advise as to why I am able to list the workflow using Connector's inbound endpoint when it has not been restored? I suppose the list action retrieves the workflows from elasticsearch then.

**Comment by oleschoenburg** [comment]
> I had values 0 to 2 for Cluster Node ID. But even for ZEEBE_BROKER_CLUSTER_NODEID=2, it restored with nodeId=1.

Oh I see. The configuration is applied correctly but the restore app is free to choose an appropriate backup from any node. That's because leadership can change and the backup may be taken by any of the replicas for a partition. So this works just as expected and isn't an issue.

> Also, can you please advise as to why I am able to list the workflow using Connector's inbound endpoint when it has not been restored? I suppose the list action retrieves the workflows from elasticsearch then.
I'm not sure how this is connected and it's not really something that I can investigate. If you think this is an issue, I'd suggest you open a support issue or report a bug with connectors.

**Comment by oleschoenburg** [comment]
Since the restore is working correctly now, I'll close this issue. Feel free to re-open if you encounter any other issues.
