### ISSUE TITLE
can not find the docker compose file to deploy Zeebe Cluster and Operate

### ISSUE THREAD

**Issue by Jngwl** [camunda/zeebe#16158]
i want to use docker compose to create a 3 nodes cluster, but i can not find the file

https://github.com/zeebe-io/zeebe/blob/develop/docker/compose/docker-compose.yaml

**Comment by oleschoenburg** [comment]
We don't provide a docker-compose file anymore. The closest alternative would be this: https://github.com/camunda/camunda-platform

**Comment by Jngwl** [comment]
您的邮件我已收到，愿您生活愉快:-)                ----来自GWL的自动回复
