### ISSUE TITLE
During incidents as an Operator of a Zeebe cluster I need a way of skipping records on processing or exporting 

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#16177]
**Is your feature request related to a problem? Please describe.**

We had no multiple occurrences in the past weeks were a single record was either preventing processing or exporting to continue.

* [Error in rejection serialization blocks exporting](https://github.com/camunda/zeebe/issues/15989)
* ["Faulty" DMN causes on rejection partition one to be stuck](https://github.com/camunda/zeebe/issues/14929)

All these clusters running into these errors were not recoverable until a new patch was released. This might have an enormous impact on business availability. We need a faster and better way to recover such clusters running into these kind of issues. 

In the cases above it would have helped if we could simply skip the problematic record. 

> [!Important]
>
> This of course needs to be decided on a case-by-case basis and needs to be done with care.

**Describe the solution you'd like**

I would like to be able to skip certain specific records for example via position or if necessary a chunk of records via key (?). I think this can be discussed what is best here.

**Describe alternatives you've considered**

Right now we have no way to do this, users have to wait for new patches to recover.

**Additional context**

This could be quite severe depending when this happens in production so prepare something like this would be beneficial.

I see this as a ZDP topic as it is on the ExporterDirector and StreamProcessor level.

Related incidents:

 * https://app.slack.com/client/T0PM0P1SA/C06F3FDRFHU
 * https://app.slack.com/client/T0PM0P1SA/C06E5CBS20G

**Comment by npepinpe** [comment]
:smile: I forgot I assigned it to you and created one too https://github.com/camunda/zeebe/issues/16175

I'll close mine in favor of this, thanks :pray:

**Comment by npepinpe** [comment]
ZDP Triage:

- We see value here in that it would help unblock customers faster (so reduce MTTR) and lower the severity of the incident, which would be especially useful for on-call engineers.
- Also useful for community users who can then unblock themselves.
- I'll put it in the inbox, and we can look at it during planning.

**Comment by megglos** [comment]
ZDP-Planning:
* moving back to inbox as we don't have capacity for it this iteration

**Comment by megglos** [comment]
ZDP-Planning:
* skipping on processing is done
* exporting is left, @rodrigo-lourenco-lopes takes this
