### ISSUE TITLE
Improve visibility of stream processor status

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#16176]
**Description**

It should be easier to detect if the stream processor is in an invalid status, ideally via metrics or an actuator. We should be able to quickly tell if the processor is:

- In an error handling loop (and for how long)
- Making progress (i.e. processing new records within a window of time)

**Comment by npepinpe** [comment]
ZDP triage: let's wait until #16107 is merged before tackling this, so let's put it in inbox and hopefully we'll have it in the next 2 weeks.

**Comment by megglos** [comment]
ZDP-Planning:
* goal would be to add a metric
