### ISSUE TITLE
Actuator date-time values are not compliant with rfc3339

### ISSUE THREAD

**Issue by richardbizik** [camunda/zeebe#16256]
Hi,
we are currently working on a custom k8s operator for zeebe and during the implementation of automatic scaling https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/cluster-scaling/ I encountered an issue with date-time values having bad formatting. For example here: https://github.com/camunda/zeebe/blob/9b2059f6e3439f4642d49a1195c5a4c267861c98/dist/src/main/resources/api/cluster-api.yaml#L270
the response contains value `-999999999-01-01T00:00:00+18:00`
According to RFC3339 the year should be a 4 digit number https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
The operator is implemented in Go and Go has a pretty strict parsing of rfc3339.

full response for GET http://localhost:9600/actuator/cluster:
```json
{
	"version": 2,
	"brokers": [
		{
			"id": 0,
			"state": "ACTIVE",
			"version": 0,
			"lastUpdatedAt": "-999999999-01-01T00:00:00+18:00",
			"partitions": [
				{
					"id": 1,
					"state": "ACTIVE",
					"priority": 1
				}
			]
		}
	],
	"pendingChange": {
		"id": 2,
		"status": "IN_PROGRESS",
		"completed": [],
		"pending": [
			{
				"operation": "BROKER_ADD",
				"brokerId": 1
			}
		]
	}
}
```

**Comment by npepinpe** [comment]
ZDP: let's do it next week as it's a simple thing, and it makes sense to provide a more user friendly default value.
