### ISSUE TITLE
I can set a retry timeout for failed tasks

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#164]
AT:
* when a task is marked as failed, I can set a timespan after this the task can be locked again
* if no time is set then the task can be locked immediately

**Comment by sergeylebed** [comment]
When we can expect this feature to be implemented?

**Comment by Zelldon** [comment]
@npepinpe

**Comment by npepinpe** [comment]
This issue was opened before I'd even heard of Zeebe (:sweat_smile:), so let me recap to make sure I understand the intent:

Once a task exhausts its retries and is marked as failed (so not activatable/lockable anymore), we want to set a timeout such that the related incident is automatically resolved by increasing the number of retries?

**Comment by Zelldon** [comment]
I think it is not about incident resolving. What I understood was that it is about to make it available again after an `X` timeout. Currently it is immediately available again for activation after one worker failed it and there are retries left, but this is problematic if the reason is an external system which might be down for a while. This will cause then an incident, since it will directly fail again. If we had back off retries we would avoid some of these cases.

**Comment by npepinpe** [comment]
Ah, so it's not when the task is marked as failed (e.g. its state is failed) but just when we get a fail command?

**Comment by aivinog1** [comment]
@npepinpe @Zelldon Hi! I would like to take this one. As I understand needs to make a task available after some backoff policy configured to it, am I right? :)

**Comment by npepinpe** [comment]
Both @Zelldon and @saig0 can help you out there (if one is too busy)

**Comment by aivinog1** [comment]
Hi @Zelldon @saig0! Can you give me some insights into this? :) 
> As I understand needs to make a task available after some backoff policy configured to it, am I right? :)

And maybe you know some pitfalls or helpers for me? :)

**Comment by saig0** [comment]
Yes, correct. The idea is that a client (Java/Go/Zbctl) can specify an optional backoff time when sending a [JobFailed command](https://github.com/zeebe-io/zeebe/blob/develop/gateway-protocol/src/main/proto/gateway.proto#L187-L196). If a backoff time is set then the job will be available after the backoff time. Otherwise, the job will be available immediately (current behavior).

The internal logic in the broker can be implemented in a similar way as [DueDateTimerChecker](https://github.com/zeebe-io/zeebe/blob/develop/engine/src/main/java/io/zeebe/engine/processing/timer/DueDateTimerChecker.java#L22). 

The fail command is handled by the [FailProcessor](https://github.com/zeebe-io/zeebe/blob/bb04a16a721081d53e951407172c44b755e0d618/engine/src/main/java/io/zeebe/engine/processing/job/FailProcessor.java#L38).

You can see how a job a marked as activated again, for example, in the [TimeOutProcessor](https://github.com/zeebe-io/zeebe/blob/bb04a16a721081d53e951407172c44b755e0d618/engine/src/main/java/io/zeebe/engine/processing/job/TimeOutProcessor.java#L34).

Please ask questions if the requirement or the code is unclear. Thank you :cookie: 

Since this is a bigger change, I would suggest splitting the broker part and the different client parts into separate PRs.

**Comment by aivinog1** [comment]
@saig0 Thanks, I got it :) I think there will be three PRs for that issue.

**Comment by npepinpe** [comment]
I'm downgrading this for now as we're refactoring our engine and it doesn't make sense to do this at the moment.

**Comment by aivinog1** [comment]
Hey @npepinpe and @saig0! Is the engine's refactoring ended? May I return to this task? :)

**Comment by saig0** [comment]
@aivinog1 yes, it's done :tada: Feel free to work on it :rocket:

**Comment by saig0** [comment]
The feature is available but not exposed to the clients yet. We should implement #5629 to complete the feature.

**Comment by aivinog1** [comment]
@saig0 I guess we can close this since #5629 closed and it was implemented in the Java and Go clients.

**Comment by saig0** [comment]
@aivinog1 yes :tada: Good job :medal_military: 
 
I'll create an issue to document the feature more prominent :rocket:
