### ISSUE TITLE
Add new metric to indicate StreamProcessor or Exporter are paused

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#16418]
**Description**

Either resuse something existing like make the partition as unhealthy or paused or add a new metric to indicate that the processor/exporter is running/paused. 

This would help to detect whether exporter has been paused still (happened on backups, etc.) or whether the processor has been paused used for incident resolvement see https://confluence.camunda.com/display/HAN/2024-02-15+Game+Day

**Comment by oleschoenburg** [comment]
Include soft-pause once it's done: #16344

**Comment by megglos** [comment]
ZDP-Planning:
* should be an easy improvement

**Comment by Sijoma** [comment]
This would be great to have to be able to create alerts ❤️ .
