### ISSUE TITLE
Does Zeebe Support a Active / Passive Setup for Replication

### ISSUE THREAD

**Issue by ChrisJBurns** [camunda/zeebe#16428]
I've been reading some documentation around [multi-region setups with Camunda 8](https://camunda.com/blog/2022/06/how-to-achieve-geo-redundancy-with-zeebe/). But I'm not entirely certain that the Zeebe replication works in an Active / Passive setup?

I also saw [a question asked on the forum](https://forum.camunda.io/t/camunda-8-cross-cluster-replication-of-zeebe-data/48052) around supporting an Active / Passive setup, but it was described that it was not possible via Zeebe. However we see as part of the Helm Chart that [`failOver`](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml#L258) is mentioned which suggests that an Active / Passive setup is possible?

Our scenario is the following. We have two regions, in an Active / Passive setup, whereby in the event of a disaster, failover is triggered and the passive site becomes the primary until the former is recovered back to normal operations. The factor that determines whether this is possible for us with Camunda 8 is how replication happens. Is it possible to have one Camunda 8 installation inside of a Kubernetes cluster in SiteA, replicate it's data to a Camunda 8 installation that exists inside of a Kubernetes cluster in SiteB?
I should add, we are not using any Cloud provider, so we are constrained to strictly 2 sites. I see on the article linked above 2 sites is more challenging, however we're trying to figure out if it's a non-starter for us because Zeebe only offers an Active / Active setup. Apologies if this is not the correct place to raise this question?

**Comment by tmetzke** [comment]
@berkaycanbc, I guess you meant @camunda/zeebe-distributed-platform?

**Comment by berkaycanbc** [comment]
Ah yeah, wrong tagging 🤦

**Comment by deepthidevaki** [comment]
@ChrisJBurns An Active/Passive setup is not currently supported. We are now working to support a stretched Zeebe cluster across two regions. #16126. You will then be able to manually trigger a failover to the surviving region. More details about how to use will be available once the feature is tested and documented.

The parameter you saw in helm chart is part of this feature. But it is not production ready yet.

**Comment by ChrisJBurns** [comment]
Hi @deepthidevaki do you know what currently isn't achievable in an Active/Passive setup? Or are you saying it's possible at the moment with the current Charts, just not recommended by yourselves due to it not being production ready?

**Comment by deepthidevaki** [comment]
It depends on what you actually mean by Active/Passive setup. There are multiple definitions - even with in Camunda - that we are trying to decide how to name it :smile:  

With the current charts (with non-production ready feature), you can deploy a stretched cluster in two regions. That means both regions are "Active". Replication across regions are synchronous. You can run your clients on any of the region or both. If one region is down, it is guaranteed that no data is lost. (assuming the deployment follows our recommendation, which is not yet documented.).  The tricky part is how to do failover/failback when one region is down. This is what is being implemented in the issue mentioned above.

By Active/Passive if you mean Site B is passively/asynchronously replicating with no active leaders for any partitions, we have no way to support that. Zeebe doesn't have a concept of a passive replica that acts like a backup.

**Comment by ChrisJBurns** [comment]
Hi @deepthidevaki  thanks for your reply. I've managed to install an Active Camunda install in one namespace, and then a Passive one (Helm Chart set to `failOver` for `installationType`) in a separate namespace, and can confirm that by hardcoding the `ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS` to point to each of the nodes in both namespaces, this works. Even using the Grafana dashboard I can see the leader for partitions are spread across all nodes.

I understand that there is no way to really force where the leader is in a deterministic way, other than to set a preference using priority elections. Although to be honest, I don't think it is an issue for us with regards to which region the leader is in, the primary thing for us is that we can replicate data across regions and failover in the event of a disaster.

I will be attempting a cross cluster setup next (when one of our other environments are available). For our scenario / definitions, when I say Active / Passive, we have one site that has all applications scaled up and communicating with Camunda, and the other site, only has the data replicated to it, there are no apps on the passive site that will be performing read/write operations on Camunda.

At the moment, my primary task is to understand what the work looks like for us to get that replication to happen as well as understanding what we need to do in the event of a failover, because as you mentioned, the failover is the tricky part :D. For our scenario, we don't really have a failback. A failover is only ever performed when the Active site (SiteA) goes down, to which the Passive site (SiteB) becomes our new main Active site long-term, until of course something goes wrong with it, which will then trigger a failover back to our original site (SiteA).

Hope that makes sense :)

**Comment by deepthidevaki** [comment]
>  and then a Passive one (Helm Chart set to failOver for installationType) in a separate namespace,

This is not how that parameter is supposed to be used. I would suggest you to wait until the feature is fully documented. 

Base on your comment, #16126 would help your usecase.

**Comment by deepthidevaki** [comment]
I assume your questions are answered. I'm closing this issue.

**Comment by ChrisJBurns** [comment]
Hi @deepthidevaki  yep my questions are answered. I had an extra couple of days left on my ticket internally and got something to work towards the end with regards to the stretch Zeebe Cluster across two regions with failover working by adding the extra node. We will await the official documentation before progressing anymore, but I think I understand what the `failOver` value is for now :)
