### ISSUE TITLE
Merge groups still get merged on CI failure

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#16458]
**Description**

I've seen multiple merge groups where the CI failed, but the group still got merged. Here are some examples:

| Workflow run | Commit | PR | Target |
|--------|--------|--------|--------|
| https://github.com/camunda/zeebe/actions/runs/7933608401 | 13eb0668f5216686085cd6a388259090fa5e50f3 | https://github.com/camunda/zeebe/pull/16423 | `main`
| https://github.com/camunda/zeebe/actions/runs/7933607057 | 55a7d7fc79723bc25aa239b4622ce3d6ca8efde2 | https://github.com/camunda/zeebe/pull/16420 | `stable/8.3`
| https://github.com/camunda/zeebe/actions/runs/7931765376 | 623ca7f74c98b7ebad9cfb3a47d0bd446f4e5c3d | https://github.com/camunda/zeebe/pull/16416 | `stable/8.1`
| https://github.com/camunda/zeebe/actions/runs/7890163583 | ab7701b12044584df1660d5509f441ba53546081 | https://github.com/camunda/zeebe/pull/16332 | `main`
| https://github.com/camunda/zeebe/actions/runs/7803091308| f2acfa0340f3652289c9f17ef8fb066e6ef556b8 | https://github.com/camunda/zeebe/pull/16248 | `main`
| https://github.com/camunda/zeebe/actions/runs/7788441086 | 803f574c47e1fababf459b98fb03fff6e6042470 | https://github.com/camunda/zeebe/pull/16162 | `stable/8.3`

**Comment by oleschoenburg** [comment]
My hypothesis is that if the PR is up to date with the target branch, the CI running for PRs produces successful check results for the same commit hash as the CI running for the merge queue. And I think these results are then treated as the same, leading to a successful merge even though the CI run for the merge queue failed.

Let's take https://github.com/camunda/zeebe/pull/16423 as an example:
1. There is a failed merge queue CI run: https://github.com/camunda/zeebe/actions/runs/7933608401
2. There is also a successful PR CI run: https://github.com/camunda/zeebe/actions/runs/7932700138


Clicking through the GH UI to show us the successful Checks that allowed this merge takes us to the PR CI run ![image](https://github.com/camunda/zeebe/assets/1379753/cf37b20a-44c6-40af-8198-7e359fef430d) here: https://github.com/camunda/zeebe/actions/runs/7932700138

**Comment by korthout** [comment]
>the CI running for PRs produces successful check results for the same commit hash as the CI running for the merge queue

🤔 I don't think this is the case.

> 2\. There is also a successful PR CI run: https://github.com/camunda/zeebe/actions/runs/7932700138

I believe this checkout commit 9e2c2181fe7c36585c8dbc20f0dd972e63048b82 while the failed merge queue CI run ran on commit 13eb0668f5216686085cd6a388259090fa5e50f3

Neither is an ancestor of the other:
```sh
ganc -h
'anc' is aliased to '! git merge-base $1 --is-ancestor $2 && echo yes || echo no'

ganc 13eb0668f5216686085cd6a388259090fa5e50f3 9e2c2181fe7c36585c8dbc20f0dd972e63048b82
no 13eb0668f5216686085cd6a388259090fa5e50f3 9e2c2181fe7c36585c8dbc20f0dd972e63048b82

ganc 9e2c2181fe7c36585c8dbc20f0dd972e63048b82 13eb0668f5216686085cd6a388259090fa5e50f3
no 9e2c2181fe7c36585c8dbc20f0dd972e63048b82 13eb0668f5216686085cd6a388259090fa5e50f3
```

**Comment by oleschoenburg** [comment]
Ohhhh is this it?! https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks

> If, however, a job within a workflow is skipped due to a conditional, it will report its status as "Success". For more information, see "[Using conditions to control job execution](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution)."

The test summary job is skipped on previous failures. It seems that Merge Queues simply ignore this and treat it as success :exploding_head:

**Comment by korthout** [comment]
Soooo, we'll need to set it to run always and then fail if a previous job failed?

**Comment by oleschoenburg** [comment]
Yep, I think so :+1:
