### ISSUE TITLE
Build on main fails even when it is actually green

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#16543]
**Summary**

![2024-02-24_17-23](https://github.com/camunda/zeebe/assets/2758593/21dc4921-d194-4737-b1a5-1976458519d2)

The problem is that the action of approving the PR is still executed on the main branch, which of course fails. This causes the main build to fail all the time.

**Comment by korthout** [comment]
ZPA triage:
- Seems @Zelldon already has a fix coming in #16544
