### ISSUE TITLE
Introduce `fold` method to `Either` interface for unified value transformation

### ISSUE THREAD

**Issue by ce-dmelnych** [camunda/zeebe#16561]
### Summary:
The current `Either<L, R>` interface provides a powerful paradigm for handling operations that can result in either a success (`Right`) or an error (`Left`). However, transforming an `Either` instance into a common type, regardless of whether it is `Left` or `Right`, requires conditional checks and separate handling for each case. This proposal aims to introduce a `fold` method to the `Either` interface, enabling a more fluent and concise way to transform `Either` instances into a unified type without explicit conditional logic.

### Background:
In many scenarios within the Zeebe, operations can result in success or failure, represented as `Right` or `Left` respectively. Transforming these results into a common type, such as for generating a response or performing further computations, often necessitates cumbersome and error-prone conditional checks.

### Proposal:
Introduce a new method, `fold` (inspired by a similar concept in [Scala](https://www.scala-lang.org/api/2.13.6/scala/util/Either.html#fold%5BC%5D(fa:A=%3EC,fb:B=%3EC):C) `Either` object), to the `util/src/main/java/io/camunda/zeebe/util/Either.java` interface. This method will accept two function parameters: one for transforming a `Right` value and another for transforming a `Left` value. The `fold` method will then apply the appropriate function based on the `Either` instance's current state, returning a unified result.

The method signature would be as follows:
```java
// Keep the following order of transformer functions to be consistent with the
// void ifRightOrLeft(final Consumer<R> rightAction, final Consumer<L> leftAction) method
<T> T fold(Function<? super R, ? extends T> rightFn, Function<? super L, ? extends T> leftFn); 
```

### Implementation notes:
- Implement the `fold` method in both the `Left` and `Right` classes that represent the possible states of an `Either` instance.
- Add comprehensive unit tests (`util/src/test/java/io/camunda/zeebe/util/EitherTest.java`) to validate the behaviour of the `fold` method in various scenarios.
- Identify and refactor existing Zeebe codebase areas where the new fold method could simplify or enhance the handling of `Either` instance.
   - first candidate: [zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/UserTaskController.java](https://github.com/camunda/zeebe/pull/16537/files#diff-54b7ecc6f741b6eea7dd749370e895880a25961167e459c09075d3e6eca08dfaR122-R126)
- Add JavaDoc for the `fold` method to include examples and best practices for using it. 

This enhancement seeks to make the `Either` interface more versatile and user-friendly, aligning with functional programming best practices.

**Comment by korthout** [comment]
ZPA triage:
- Either was added for functional style in our processors, idea was to keep it simple and add features when we have a need for them
- this is a wonderful feature to add
- not high prio but if needed for some planned task, then just take this along
- also possible as a good first issue if someone wants to add a useful feature to our Either type

**Comment by korthout** [comment]
@tmetzke If you can add it along with your current work, go ahead
