### ISSUE TITLE
CI runs out of heap when analyzing Propery Test

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#16604]
**Summary**

- How often does the test fail? very often

The actual test seems to have passed. But the step `Analyze Test Runs` fails due to out of heap. 

```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by deepthidevaki** [comment]
I see @korthout has already raised this issue https://github.com/test-summary/action/issues/45 :bow:

**Comment by koevskinikola** [comment]
Happened again [here](https://github.com/camunda/zeebe/actions/runs/8155349990/job/22290685755).

**Comment by koevskinikola** [comment]
And another time [here](https://github.com/camunda/zeebe/actions/runs/8157713867/job/22298010745).

**Comment by megglos** [comment]
There is an existing old issue open that test-summary isn't supporting large test suites https://github.com/test-summary/action/issues/5. Given this is open since nearly 2 years I have low hopes something will happen.

**Comment by megglos** [comment]
again here https://github.com/camunda/zeebe/actions/runs/8175116441/job/22351502358

**Comment by megglos** [comment]
As a workaround I created https://github.com/camunda/zeebe/pull/16764 to skip the summary action for property tests, is that an acceptable workaround? wdyt?
