### ISSUE TITLE
Update documentations for migration element instances with incidents

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#16622]
#### Update [API Definition document](https://docs.google.com/document/d/1V_sZQmr6KHFuAxovkxCLY4Kb38t3_r68TihCnHqhIbw/edit#heading=h.9xhvuj8z66v5):
- Add an incident section to the API definition so we can inform Operate about the upcoming changes. They'll need to consume the `zeebe-records_incident` index that has an intent `MIGRATED` for changes to incidents.

**Comment by berkaycanbc** [comment]
@korthout I added incidents section to the bottom of the [API definition document](https://docs.google.com/document/d/1V_sZQmr6KHFuAxovkxCLY4Kb38t3_r68TihCnHqhIbw/edit). Could you please take a look?

**Comment by korthout** [comment]
@berkaycanbc Sorry for not checking this sooner 🙇  It slipped through.

👍 LGTM

🔧 I made a small adjustment to the text (adding the ES index name).
