### ISSUE TITLE
Partition Transition reported as stuck even if it doesn't take long

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#16633]
**Describe the bug**

We see following logs from a customer
```
2024-02-28 10:13:17.915 [ZeebePartition-14] [zb-actors-2] WARN 
      io.camunda.zeebe.broker.system - ZeebePartition-14 failed, marking it as unhealthy: ZeebePartition-14{status=UNHEALTHY, issue=HealthIssue[message=Transition from LEADER on term 47 appears blocked, step ZeebeDb has been running for PT0.144S, throwable=null, cause=null]}
```

The message says that the transition is stuck for only less than a second. 

With in a short time the partition is marked as healthy, because the transition is completed.

**Expected behavior**

It is marked as unhealthy, only if the transition takes longer than 60 seconds.

**Analysis**

Initially I thought it might be a concurrency issue. But this information is updated and accessed in the same actor. The root cause is the condition that we use to check the duration is wrong. 
https://github.com/camunda/zeebe/blob/40b719cbad10a93d51679b8dec90b3b021a653d0/zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java#L216

**Environment:**
- Zeebe Version: > = 8.2

**Comment by megglos** [comment]
ZDP-Triage:
- might also be in older releases, needs to be checked
