### ISSUE TITLE
Update commit message guidelines in contribution guide

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#16675]
**Description**

* Update the https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md guide to reflect the latest [team decision](https://docs.google.com/document/d/1TO4Lq0trdFhOhMZwK0aPOMg9_smJu-CW4NUPz4qNXpY/edit#heading=h.ufyfh0qjaa4i) on omitting the **scope** element from commit message headers.
* We favor consistent messages and small, comprehensive commits that reveal the scope inherently.
* We don't use commit messages for release note creation, thus the scope is merely an overhead.

**Comment by tmetzke** [comment]
Reopened since we should also adjust the [commitlint](https://github.com/camunda/zeebe/blob/main/commitlint.config.js) configuration.

**Comment by tmetzke** [comment]
Thanks, @korthout 👍 
Looking at the [related PR](https://github.com/camunda/zeebe/pull/16712), could I merge that now although it has a failing commitlint check? Only the required check `Zeebe CI / Test summary (pull_request)` needs to pass to allow merging?

If that is so, I think the impact is a nice middle ground since it's not blocking anything but also indicating strongly that something is off with the failed check in a PR 👍

**Comment by korthout** [comment]
@tmetzke I believe that's how it currently works. This is why I think it's a good idea to change the config along with the new rules we want to apply. It nudges people in the right direction without being super cereal about it.

**Comment by tmetzke** [comment]
Thanks, @korthout, totally agree 👍 I'll fixup the PR then and put it up for review 🙂
