### ISSUE TITLE
Retention policy is not applied to existing zeebe indices when enabled

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#16720]
**Describe the bug**

If you run the zeebe exporter with ilm disabled and enable it later on, previosuly existing indices don't get the policy applied. This leads to those indices staying "forever" and require manual intervention, e.g. reapplication of the policy to those.

**To Reproduce**

1. run zeebe with the elastic/opensearch exporter and disabled ilm:
```
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_RETENTION_ENABLED=false
```
2. Let it run and create indices
3. Enable the retention and restart
```
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_RETENTION_ENABLED=true
```
4. Already existing indices lack the policy

**Expected behavior**

The policy needs to applied to all existing zeebe indices

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.2.0+
- Configuration: elasticsearch or opensearch exporter is used

**Comment by megglos** [comment]
Manual workaround, apply the policy on all zeebe indices via:

```
PUT http://localhost:9200/<zeebeIndexPrefix>*/_settings
{
    "index": {
        "lifecycle": {
            "name": "<zeebeRetentionPolicyName>"
        }
    }
}
```

With the default values for `zeebeIndexPrefix` being `zeebe-record` and for `zeebeRetentionPolicyName` being `zeebe-records-retention-policy` the call would be
```
PUT http://localhost:9200/zeebe-record*/_settings
{
    "index": {
        "lifecycle": {
            "name": "zeebe-records-retention-policy"
        }
    }
}
```

**Comment by korthout** [comment]
We should also consider the counter case: disabling the retention policy -> remove the policy from the indices. We can do this in a follow-up issue.

**Comment by korthout** [comment]
Should be straightforward to implement (use step 2 on exporter startup), but has a good win.

**Comment by mustafadagher** [comment]
To have the same fix for opensearch, we need to use the following APIs:
1. [Add policy](https://opensearch.org/docs/latest/im-plugin/ism/api/#add-policy)
2. [Remove policy from index](https://opensearch.org/docs/latest/im-plugin/ism/api/#remove-policy-from-index)

Unlike the Elasticsearch API, we can't reuse one endpoint for both purposes.
