### ISSUE TITLE
Support Azure UAMI for backup storage authentication

### ISSUE THREAD

**Issue by Boboltus** [camunda/zeebe#16736]
**Is your feature request related to a problem? Please describe.**
In feature #14927 Azure backup storage was introduced. This works for implementations that use authentication based on StorageSharedKeyCredential or ConnectionString. Azure however also has the option to use UAMI (User Assigned Managed Identity) for authentication against a Azure Storage Account (and other resources). I would like to see that functionality (UAMI support) also introduced. That would be very useful in our environment because it doesn't require the configuration of authentication details (like SAS-tokens or other credentials).

**Describe the solution you'd like**
Implement the Azure Identity Library (com.azure - azure-identity) to allow access to Azure using UAMI for Azure Backup storage.

**Describe alternatives you've considered**
There are non at this time.

**Additional context**
This is the Microsoft documentation that is related to this topic [MS Azure AD authentication](https://learn.microsoft.com/en-us/azure/storage/blobs/authorize-access-azure-active-directory). Using this documentation the authentication options using the DefaultCredentialBuilder can be used to authenticate in multiple ways (from multiple sources)

**Comment by rodrigo-lourenco-lopes** [comment]
Hi @Boboltus we created a new PR with your commits, with some changed logic and added documentation to use a config to decide whether to use the the `DefaultAzureCredential` .
https://github.com/camunda/zeebe/pull/16958
Let me know if you agree with the changes.

**Comment by Boboltus** [comment]
Hi @rodrigo-lourenco-lopes . Looks better then my implementation :). Looking forward to using this as it will solve some Azure security exemptions I currently have alerts from!
