### ISSUE TITLE
Migrate spring client and remove deprecated code

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/zeebe#16875]
**Description**
- Add `spring-zeebe-client`
- Remove unused code from `spring-zeebe-client`
- Remove deprecated annotations if any

**Comment by megglos** [comment]
@ana-vinogradova-camunda let's rename the module to `zeebe-client-spring` this follows the same naming as the client and this way we also avoid conflict with the old artifact from the community repo.
