### ISSUE TITLE
Zeebe Metrics shows partition as unhealthy while zbctl shows healthy

### ISSUE THREAD

**Issue by ashprojects** [camunda/zeebe#16932]
**Description**
Hi there,
We recently setup Zeebe in production with following configuration
Cluster: 5
Replicas: 3
Partitions: 16

Recently we added updated cluster from 4 to 5 and ran scale up api from Zeebe.
zbctl shows following
```
Cluster size: 5
Partitions count: 16
Replication factor: 3
Gateway version: 8.4.1
Brokers:
  Broker 0 - camunda-zeebe-0.camunda-zeebe.camunda.svc:26501
    Version: 8.4.1
    Partition 1 : Follower, Healthy
    Partition 4 : Follower, Healthy
    Partition 5 : Follower, Healthy
    Partition 6 : Follower, Healthy
    Partition 9 : Follower, Healthy
    Partition 10 : Follower, Healthy
    Partition 11 : Follower, Healthy
    Partition 14 : Follower, Healthy
    Partition 15 : Follower, Healthy
    Partition 16 : Follower, Healthy
  Broker 1 - camunda-zeebe-1.camunda-zeebe.camunda.svc:26501
    Version: 8.4.1
    Partition 1 : Leader, Healthy
    Partition 2 : Follower, Healthy
    Partition 5 : Follower, Healthy
    Partition 6 : Follower, Healthy
    Partition 7 : Follower, Healthy
    Partition 10 : Follower, Healthy
    Partition 11 : Leader, Healthy
    Partition 12 : Follower, Healthy
    Partition 15 : Follower, Healthy
    Partition 16 : Follower, Healthy
  Broker 2 - camunda-zeebe-2.camunda-zeebe.camunda.svc:26501
    Version: 8.4.1
    Partition 1 : Follower, Healthy
    Partition 2 : Leader, Healthy
    Partition 3 : Follower, Healthy
    Partition 6 : Leader, Healthy
    Partition 7 : Follower, Healthy
    Partition 8 : Follower, Healthy
    Partition 11 : Follower, Healthy
    Partition 12 : Leader, Healthy
    Partition 13 : Follower, Healthy
    Partition 16 : Leader, Healthy
  Broker 3 - camunda-zeebe-3.camunda-zeebe.camunda.svc:26501
    Version: 8.4.1
    Partition 2 : Follower, Healthy
    Partition 3 : Leader, Healthy
    Partition 4 : Leader, Healthy
    Partition 7 : Leader, Healthy
    Partition 8 : Follower, Healthy
    Partition 9 : Leader, Healthy
    Partition 12 : Follower, Healthy
    Partition 13 : Leader, Healthy
    Partition 14 : Leader, Healthy
  Broker 4 - camunda-zeebe-4.camunda-zeebe.camunda.svc:26501
    Version: 8.4.1
    Partition 3 : Follower, Healthy
    Partition 4 : Follower, Healthy
    Partition 5 : Leader, Healthy
    Partition 8 : Leader, Healthy
    Partition 9 : Follower, Healthy
    Partition 10 : Leader, Healthy
    Partition 13 : Follower, Healthy
    Partition 14 : Follower, Healthy
    Partition 15 : Leader, Healthy
```

But Grafana - promethues shows
![image](https://github.com/camunda/zeebe/assets/15957226/6510a7f0-1d18-438a-a056-b9c2ccf71f4c)

What are we missing? When cluster size was 4, we were getting all as healthy in Grafana but now story shows 4 partitions as unhealthy

Zeebe version: 8.4.1

**Comment by megglos** [comment]
ZPA-Triage:
- the topology response only contains broker/partition state distributed via gossip - it is only eventually consistent
- the grafana metrics are based of broker metrics - it's not fully clear if the state is based on the exact same criteria
- would also await the ZDP triage here, as it may be a better fit there => at least the criteria should be the same, we may accept eventual consistency of the state in the topology response, would flag it as bug now until we have this clarified

**Comment by oleschoenburg** [comment]
@ashprojects This is a known "issue" after scaling up. Because scaling up redistributes partitions, some brokers will report partitions that it no longer runs as "inactive" which is interpreted as unhealthy. This goes away as soon as the broker is restarted because then it resets all metrics and no longer reports "inactive" for those partitions.

You can either do nothing or restart the brokers.

**Comment by ashprojects** [comment]
Thanks @oleschoenburg It worked, I had to restart all pods, one by one.

**Comment by oleschoenburg** [comment]
While this looks a bit bad and can be confusing, I don't see how we can fix this easily. One reason for this is that we don't have a way to unregister metrics from partitions that are no longer active.
