### ISSUE TITLE
Streamline component REST APIs

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#16947]
## Description

* As part of the [🔒 architecture streamlining](https://docs.google.com/presentation/d/15DW6tCmhJC21BOutv8-R2av4En6Nx70US-x8kLRMGiM), align the existing components' REST APIs regarding the following:
  * Search experience (request, response)
  * Realtime search
  * Path naming
  * Single contact point
  * Intra communication
  * Date format
  * HTTP status codes
  * Management APIs
  * Health endpoints

## Proposal

* Detailed proposals for the topics mentioned above: [🔒 C8 REST API](https://docs.google.com/presentation/d/1QcOXizpKQBmFE5ZMiNYnHFdEKIw4gyvEr1HCS_rf-ic)

### Search experience

* We stick to POST request-based search for now.
 If you see a priority for GET-based search, please specify [the proposal](https://github.com/camunda/zeebe/issues/16994).
* We consistently use indirections in requests and responses to separate concerns and structure the data.
  * Request structure:
  ```js
  {
    "filter": { <entity-specific filter options>},
    "sort": [
      { "<field>": "<order>" },
      { "<field>": "<order>" }
    ],
    "page": {
      "searchAfter": [ … , … ],
      "searchAfterOrEqual": [ … , … ],
      "searchBefore": [ … , … ],
      "searchBeforeOrEqual": [ … , … ],
      "limit": <limit>
    }
  }
  ```
  * Response structure:
  ```js
  {
    "items": [
      { "state": "CREATED", "startTime": … }
      { "state": "COMPLETED", "startTime": … }
    ],
    "page": {
      "totalItems": <total hits>,
      "sortValues": [ …, … ]
    }
  }
  ```
* We support Keyset-based Pagination for search as offered by Elasticsearch. We don’t offer cursor-based or offset-based pagination on top as of now.

### Realtime search

* We provide mixed realtime and near-realtime search
* Direct resource access routes to Zeebe (realtime “get/search”)
  * GET /v2/process-instances/252123123
  * `404 Not Found` is returned when the instance is not available (anymore because it’s completed/canceled)
* Search routes to Elasticsearch (near-realtime search)
  * POST /v2/process-instances/search
  * Returns an array of instances of all states (active, completed, cancelled, …)

### Path naming

* Versioning of API via consistent URI naming: **/v1/…**, e.g. `GET /v1/process-definitions/<key>`
* We do API versioning, not endpoint versioning, i.e., the version changes for all endpoints if there is a breaking change in any endpoint.
  * Adding attributes and endpoints is not a breaking change
  * See [GitHub’s REST documentation](https://docs.github.com/en/rest/about-the-rest-api/breaking-changes?apiVersion=2022-11-28#about-breaking-changes-in-the-rest-api) for a summary of breaking changes
* The _unified C8 REST API_ starts with version **/v2/…** to allow for better migration

### Single contact point

* We promote a single contact point, one C8 REST API.
* We deprecate current public component REST APIs (Tasklist, Operate, Optimize).
* For a grace period, users can still use them to migrate to the single contact point.
* Tooling support promotes the single contact point to help users migrate.

### Intra communication

* We keep component backends for frontends (BFFs) for now.
* Over time, we remove BFFs and frontends use the C8 REST API.

### Monitoring API

* Overall, we want to streamline existing monitoring capabilities into the unified C8 REST API, e.g., have one Prometheus, one execution metrics, and one health endpoint in the API, not multiple.
* We decouple the applications’ health status from Elasticsearch’s health status.

### Misc

* We align [🔒 date formats](https://github.com/camunda/product-hub/issues/2090), [🔒 HTTP status codes](https://docs.google.com/spreadsheets/d/1rj_erO5VyM2Huvd4wKzIVNw4pEGWtgSVZZr-0klJIsY/edit#gid=0), and [🔒 terminologies](https://docs.google.com/spreadsheets/d/1rj_erO5VyM2Huvd4wKzIVNw4pEGWtgSVZZr-0klJIsY/edit#gid=0) across components.
* We extract a common baseline from the [🔒 initial API assessment](https://docs.google.com/document/d/1pnyuL1BQRYtmWBu_hn-RfA3JZMjLXFl0OXjxYKEsvl8/).

**Comment by aleksander-dytko** [comment]
Adding the document here for reference: 🔒 [C8 REST API guidelines](https://docs.google.com/document/d/1G9AmmNac-4QLGZ0LXQXa3FyeCrSJdIboaPt3-R6dWNw/edit#heading=h.8q7op21dien3)

**Comment by tmetzke** [comment]
✅ Documented in the guidelines
