### ISSUE TITLE
Large DMN decision tables are not showing bottom rows and bottom panel is not visible

### ISSUE THREAD

**Issue by pedesen** [camunda/zeebe#17023]
Support Case: https://jira.camunda.com/browse/SUPPORT-21229

### Describe the bug

In Decision instance view showing a large decision table (>300 rows), the bottom panel is not visible and the last rows of the table are not reachable.

### To Reproduce

1. Deploy a DMN definition containing a decision table with >300 rows (for example: [performance.dmn)](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-decision-table/test/spec/performance.dmn)
2. Open the decisions view
3. Select a decision instance from the list to go to decision instance view

### Current behavior

- The decision table only shows the first couple of entries (depending on the resolution of the monitor)
- It does not show last entries and it doesn’t show the bottom panel containing the results

### Expected behavior

- The bottom panel is always visible
- The decision table is scrollable so all entries can be reached

### Environment

- OS: [e.g. MacOS]
- Browser: [e.g. chrome, safari]
- Operate Version: [e.g. 8.1]

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by sdorokhova** [comment]
Tested for big literal expressions also.
