### ISSUE TITLE
Zeebe Grafana dashboard uses angular that has been deprecated

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#17097]
**Description**

Opening the grafana dashboard in SaaS we are getting greeted with the following:

![grafana](https://github.com/camunda/zeebe/assets/2758593/46f0657d-9b90-4e50-9227-00284b59c1a0)

Looks like angular was deprecated in Grafana and our dashboard still uses it (?)

https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

**Comment by npepinpe** [comment]
ZDP: low hanging fruit, just updating the panels. Let's just do it
