### ISSUE TITLE
Tasklist is part of the Zeebe Mono Repository

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/zeebe#17117]
Same as for Operate https://github.com/camunda/c8as-mono-repo-playground/issues/1

**Goals**
* Engineers of Tasklist team should be able to push code changes to the Zeebe Mono Repository.
* Tasklist CI/CD and release pipelines are moved to the Zeebe Mono Repository.
  * CI/CD applies path filtering, so that for example when changes to Tasklist happen only the current Tasklist CI/CD pipeline runs.
  * Zeebe, Operate and Tasklist can be released independently (? it depends if Single Jar is delivered in alpha1)
* License headers are updated accordingly.

[Decisions document](https://docs.google.com/document/d/1oKnL1SpCzVWJ_sQ38nzm3VxlXKNyWETd5D8mWvyHQdo/edit#heading=h.mpo7cmwfhhm)
```[tasklist]
### Make Tasklist ready for import and import it into the monorepo
- [x] Adjust Tasklist to sub-folder structure https://github.com/camunda/tasklist/pull/4775
- [x] Use name prefix like `tasklist-xy.yml` for workflows: https://github.com/camunda/tasklist/pull/4604
- [x] Align formatting and checkstyle https://github.com/camunda/tasklist/pull/4582 https://github.com/camunda/tasklist/pull/4603
- [x] Add path filters on CI https://github.com/camunda/tasklist/pull/4836
- [x] Rename Dockerfile in Tasklist to tasklist.Dockerfile https://github.com/camunda/tasklist/pull/4793
- [x] Apply license headers to source code https://github.com/camunda/tasklist/pull/4794
- [x] Adjust WebApp terms and conditions https://github.com/camunda/tasklist/pull/4811
- [x] Secret scanning with trufflehog https://github.com/camunda/tasklist/pull/4819
- [x] Update Tasklist GH issues and pull request templates https://github.com/camunda/tasklist/pull/4846
- [x] Merge Renovate configuration with the one from monorepo
- [x] Simulate Tasklist merge into mono-repo with some test PRs https://github.com/camunda/zeebe/pull/17417
- [ ] Validate that Tasklist can be released with dry runs and RC release (to be confirmed , it depends if Single Jar is ready before alpha1)
- [x] Add component label for tasklist
- [x] Extend labeler to mark PRs as tasklist related
- [ ] Run spotbugs analysis
```

**Comment by Zelldon** [comment]
@houssain-barouni we also need to think about whether we want to add the Tasklist CI to the merge queue. Right now it already causes some issues that Operate is not part of the merge queue.

**Comment by houssain-barouni** [comment]
@cmur2 I ran `trufflehog git https://github.com/camunda/tasklist` to scan for secrets
```json
{"chunks": 46721, "bytes": 21688034, "verified_secrets": 0, "unverified_secrets": 2, "scan_duration": "7.037782417s"}
```
the two unverified secrets:
- https://github.com/camunda/tasklist/blob/master/config/docker-compose.iam-backend.yml#L18 It is just used for local setup ( I am sure we don't use this anymore)
- https://github.com/camunda/tasklist/blob/master/qa/integration-tests/src/test/resources/certs/zeebe-test-server.key.pem  used in one integration test

I think we are safe to keep them both, WDYT?

**Comment by cmur2** [comment]
> I think we are safe to keep them both, WDYT? I can also remove the first one as it not used anymore, and generate the second one on the fly when tests are run.

In general both look like secrets that are part of test data and thus should be fine. Let's remove the first one if it is not needed anymore, one less thing to worry about 👍🏼

**Comment by houssain-barouni** [comment]
I removed the secrets here https://github.com/camunda/tasklist/pull/4819

**Comment by houssain-barouni** [comment]
@cmur2 Regarding Renovate configuration , I think we can apply on [Tasklist](https://github.com/camunda/tasklist/blob/master/.github/renovate.json) the same configuration as the existing one in the mono-repo https://github.com/camunda/zeebe/blob/main/.github/renovate.json
we may just need to skip updating "tasklist.Dockerfile" to avoid updating the wrong digest (I will create a ticket to refactor the Dockerfile to make platform agnostic)
```
  {
    "matchFileNames": ["tasklist.Dockerfile"],
    "enabled": false
  },
```

**Comment by cmur2** [comment]
> @cmur2 Regarding Renovate configuration , I think we can apply on [Tasklist](https://github.com/camunda/tasklist/blob/master/.github/renovate.json) the same configuration as the existing one in the mono-repo https://github.com/camunda/zeebe/blob/main/.github/renovate.json we may just need to skip updating "tasklist.Dockerfile" to avoid updating the wrong digest 

On a first glance that look plausible :+1:

**Comment by houssain-barouni** [comment]
I will create other tickets for the releasing and spotbugs

**Comment by houssain-barouni** [comment]
For spotbugs https://github.com/camunda/zeebe/issues/17598
