### ISSUE TITLE
Add README to spring-boot-starter-camunda-sdk

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/zeebe#17123]
**Description**

Add README to spring-boot-starter-camunda-sdk:

- Copy README file from the community project
- Adjust if needed

**Comment by megglos** [comment]
will be added to the docs right away https://github.com/camunda/camunda-docs/pull/3552

**Comment by ana-vinogradova-camunda** [comment]
Closing as the above PR was merged.
