### ISSUE TITLE
V1 vs V2 API

### ISSUE THREAD

**Issue by aleksander-dytko** [camunda/zeebe#17177]
## Proposal
> [!NOTE] 
> Provide a clear cut for the new API - leave the current "old" API as it is, with no changes. Build "new" API `V2` with changes in schema and behavior. Users can use old APi until it's removed, giving them time to migrate to new API.

### General
Separation between the "old" (i.e., current) API and the "new" (upcoming Unified C8 REST) API on the REST path level, for example:

- `/v1/... `is the "old" API
- `/v2/...` is the "new" API

The "old" API will behave as it is now, i.e., GET requests will execute search requests in Elasticsearch/Opensearch. And in comparison, the "new" API will execute a realtime GET by retrieving the latest state from Zeebe.

With having a clear cut between the "old" and "new" API already on the path level, this would mean for users:

- When upgrading to 8.6, their clients can still use the "old" API as it is now with the given guarantees, paths, requests, and responses.
- Some documentation explains the migration path from the "old" API path to the "new" API path. (Which would be there in any case)
- The users clearly understand what is "old," "new," and the differences.
- Based on that, they can gradually migrate their implementation to the "new" API and new guarantees regarding GET requests. They could apply the adjustments to their implementation better or more in a way they are not immediately forced to do.

### User Tasks
- Leave APIs v1 the same as it is today - no migration effort needed
   - Job-based user tasks can be used with Tasklist API
   - Zeebe-based user tasks can be used with Tasklist API (query) and Zeebe API (management)
   - No migration needed until 8.8 - later this API is removed
- Build unified Camunda 8 REST API v2 with changes from the [document](https://docs.google.com/presentation/d/1QcOXizpKQBmFE5ZMiNYnHFdEKIw4gyvEr1HCS_rf-ic/edit#slide=id.p) (including changes in request/response schema, GET endpoints)
   - Clean cut - the new C8 API works only with Zeebe-based User Tasks
   - Migration will be needed to upgrade to 8.8

![image](https://github.com/camunda/zeebe/assets/56470362/9cb7cddf-685a-4826-926e-dce1231507f0)

## Decisions

* The component APIs are accessible under `/v1/...`, the unified API will start at `/v2/...`.
* The component APIs' behavior remains unchanged to allow for a migration period.
* The unified API will only work for Zeebe user tasks

**Comment by tmetzke** [comment]
Regarding
> (BTW, the same would also apply then to the search APIs, and endpoints, etc.)

Does that imply that search requests would also query Zeebe (runtime state) directly? I think that is currently not planned, as far as I know. Just wanted to clarify this.

**Comment by aleksander-dytko** [comment]
Removed to clarify the message

**Comment by tmetzke** [comment]
@aleksander-dytko, the proposal was accepted as outlined 🎉 
The core of the proposal has been added as a hint to the [C8 API guidelines](https://docs.google.com/document/d/1G9AmmNac-4QLGZ0LXQXa3FyeCrSJdIboaPt3-R6dWNw/edit#heading=h.5i01aikei7pr) in the **General API strategy**.

Please create any follow-up issues for documentation you'd like to see for 8.6 so we don't forget about them, e.g. migration considerations from `v1` to `v2`. I don't see them in the scope of the general API guidelines since they are only temporary.
