### ISSUE TITLE
Enable auto-merge for Operate renovate PR's

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#17170]
We want to enable the auto-merging of Operate renovate PRs after 8.5 release

See related discussion on [slack](https://camunda.slack.com/archives/C06HTSPD5AP/p1711091253406079?thread_ts=1711040114.746319&cid=C06HTSPD5AP)

**Comment by cmur2** [comment]
The feature was enabled but is yet not working fully due to configuration problems and permission issues that I'm now sorting out.

**Comment by cmur2** [comment]
The Renovate automerge feature is now enabled and working smoothly as requested with this ticket, see e.g. https://github.com/camunda/zeebe/pull/17536
