### ISSUE TITLE
Document decisions from C8 REST API streamlining proposal

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#17233]
**Description**

* [x] Add the decisions from https://github.com/camunda/zeebe/issues/16947 to the C8 REST API baseline document

**Comment by tmetzke** [comment]
@aleksander-dytko, I added you here for transparency since you're reviewing the documented decisions.

**Comment by aleksander-dytko** [comment]
Adding the document here for reference: 🔒 [C8 REST API guidelines](https://docs.google.com/document/d/1G9AmmNac-4QLGZ0LXQXa3FyeCrSJdIboaPt3-R6dWNw/edit#heading=h.8q7op21dien3)

**Comment by tmetzke** [comment]
Decisions are documented in the guidelines and reviewed by @aleksander-dytko
