### ISSUE TITLE
Run Spotbugs plugin on the Operate codebase and fix related issues

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#17331]
### Description

Came up during integration Operate into the maven multi-module project, see here https://github.com/camunda/zeebe/pull/17280

It seems spotbugs were not executed before, for Operate. This leads to build errors when enabled.

Spotbugs allows us to detect several kind of bugs (based on [configuration](https://github.com/camunda/zeebe/blob/a2b58bb9041b8127ce336ca8c921b5ccac7e87b8/build-tools/src/main/resources/spotbugs/spotbugs-include.xml)) The current configuration is currently limited to [CORRECTNESS](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#correctness-correctness) and [MT_CORRECTNESS](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#multithreaded-correctness-mt-correctness)

One we for example detected was #17316 but there are more. 

### TODO

Run spotbugs on the Operate code base and fix the related issues.

### Additional Information

Please reach out if you have any questions related to the tool.

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by matt-whiteman** [comment]
We are not able to obtain a full report of all issues at once. Spotbugs will only fail on the first one it finds, so we would have to fix issues one at a time until we get a clean report.
