### ISSUE TITLE
Add CONTRIBUTION.md file

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#17345]
Create a CONTRIBUTION.md file for recognize all the contributors of the community project. We should follow this [template](https://github.com/cezaraugusto/github-template-guidelines/blob/master/.github/CONTRIBUTORS.md).

We should collect all the contributors name from the log of the community project:

`git shortlog -sne --all`

**Comment by Zelldon** [comment]
This can't be true 😆 😎 
```
$ git shortlog -sne --all
  3865  zeebe-bors-camunda[bot] <101703512+zeebe-bors-camunda[bot]@users.noreply.github.com>
  2818  Nicolas Pepin-Perreault <nicolas.pepin-perreault@camunda.com>
  2696  Christopher Zell <zelldon91@googlemail.com>
  2496  dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
  2464  Ole Schönburg <ole.schoenburg@gmail.com>
  2460  Deepthi Devaki Akkoorath <deepthidevaki@gmail.com>
```

**Comment by nicpuppa** [comment]
> This can't be true 😆 😎
> 
> ```
> $ git shortlog -sne --all
>   3865  zeebe-bors-camunda[bot] <101703512+zeebe-bors-camunda[bot]@users.noreply.github.com>
>   2818  Nicolas Pepin-Perreault <nicolas.pepin-perreault@camunda.com>
>   2696  Christopher Zell <zelldon91@googlemail.com>
>   2496  dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
>   2464  Ole Schönburg <ole.schoenburg@gmail.com>
>   2460  Deepthi Devaki Akkoorath <deepthidevaki@gmail.com>
> ```

Did you run the command on zeebe or on the community project ?

**Comment by Zelldon** [comment]
Haha I did on Zeebe just out of curiosity
