### ISSUE TITLE
Rolling release benchmark workflow does not get triggered by release

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/zeebe#17362]
**Describe the bug**

Rolling release benchmark does not get triggered by release. 

It is still possible to trigger it manually. 

This might have to do with the fact that the release process is created from a workflow.

https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. For more information, see "Automatic token authentication."

And the solution seems to be to:

> If you do want to trigger a workflow from within a workflow run, you can use a GitHub App installation access token or a personal access token instead of GITHUB_TOKEN to trigger events that require a token.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by npepinpe** [comment]
We could also do the same as we do for the QA task and use a connector. I think we have some known solutions, so I would propose to do it sooner than later to avoid adding work during the next release, but only if we have capacity, so tentatively adding it to inbox.
