### ISSUE TITLE
`ActivatableJobsPushTest.shouldPushAfterJobFailed` is flaky

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#17456]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? At least once
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Expected size: 2 but was: 1 in:
[{"key":2251799813685272,"record":{"deadline":1712926185476,"timeout":-1,"worker":"test","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"id-4b76546e-c86e-473d-87b0-988eebc44593","customHeaders":[packed value (length=1)],"variables":"3wAAAAOhYaR2YWxBoWKkdmFsQqFjpHZhbEM=","errorMessage":"","errorCode":"","bpmnProcessId":"process","processDefinitionVersion":2,"processDefinitionKey":2251799813685262,"processInstanceKey":2251799813685264,"jobKind":"BPMN_ELEMENT","elementId":"task","elementInstanceKey":2251799813685271,"tenantId":"<default>"}},
    {"key":2251799813685272,"record":{"deadline":1712926185479,"timeout":-1,"worker":"test","retries":5,"retryBackoff":0,"recurringTime":-1,"type":"id-4b76546e-c86e-473d-87b0-988eebc44593","customHeaders":[packed value (length=1)],"variables":"3wAAAAOhYaR2YWxBoWKkdmFsQqFjpHZhbEM=","errorMessage":"","errorCode":"","bpmnProcessId":"process","processDefinitionVersion":2,"processDefinitionKey":2251799813685262,"processInstanceKey":2251799813685264,"jobKind":"BPMN_ELEMENT","elementId":"task","elementInstanceKey":2251799813685271,"tenantId":"<default>"}}]
	at io.camunda.zeebe.engine.processing.job.ActivatableJobsPushTest.assertActivatedJobsPushed(ActivatableJobsPushTest.java:280)
	at io.camunda.zeebe.engine.processing.job.ActivatableJobsPushTest.shouldPushAfterJobFailed(ActivatableJobsPushTest.java:204)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

From https://github.com/camunda/zeebe/actions/runs/8662240967: [Test results for unit tests.zip](https://github.com/camunda/zeebe/files/14959010/Test.results.for.unit.tests.3.zip)

**Comment by nicpuppa** [comment]
Happened again [here](https://github.com/camunda/zeebe/actions/runs/8688635401/job/23824694846)

**Comment by rodrigo-lourenco-lopes** [comment]
Happened again https://github.com/camunda/zeebe/actions/runs/8702524348/job/23867160953
