### ISSUE TITLE
GHA: Fix Operate Weekly internal docker images workflow

### ISSUE THREAD

**Issue by sdorokhova** [camunda/zeebe#17616]
### Description

Currently [Operate benchmarks](https://confluence.camunda.com/display/HAN/Operate+Benchmarks) are failing because of outdated Operate image.
The reason is:
1. [New job in Zeebe repository](https://github.com/camunda/zeebe/actions/workflows/operate-weekly-internal-docker-images.yaml) is failing.
2. [Older job in Operate repository](https://github.com/camunda/operate/actions/workflows/operate-weekly-internal-docker-images.yaml) continues producing outdated Docker images every week.

### TODO

* Research and fix new job in Zeebe repo
* Remove (or disable) job in Operate repo

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by Zelldon** [comment]
We have to adjust the worfklow fedoration, as it is still referencing the old Operate repo. We have to change it to either the zeebe repo.

@cmur2 mentioned there is also a more stable configuration to use a UID, which might be worth to do if we plan to rename the repo and this might break this again.

**Comment by cmur2** [comment]
> @cmur2 mentioned there is also a more stable configuration to use a UID, which might be worth to do if we plan to rename the repo and this might break this again.

The OIDC attribute mapping on the Google Cloud side can use the `repository_id` field from GitHub to be safe against renames etc as recommended in the [GCP documentation](https://cloud.google.com/iam/docs/workload-identity-federation-with-deployment-pipelines#github-actions_1): https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-token-claims

**Comment by Zelldon** [comment]
Right now we have this 
![2024-04-22_14-01](https://github.com/camunda/zeebe/assets/2758593/d7e2f183-7503-4f96-a97d-030b3d110dde)
