### ISSUE TITLE
If the code is not commercially available. No need to open source at all. It is easy to understand that it is inducing users to use, and then charging for illegal use

### ISSUE THREAD

**Issue by zxuanhong** [camunda/zeebe#18141]
**Description**

1. If the code is not commercially available. No need to open source at all. It is easy to understand that it is inducing users to use, and then charging for illegal use.

**Comment by nloding** [comment]
Hi @zxuanhong - this is a fair question. First I'd like to clarify one point: Camunda will have a free license for development and testing, and Camunda will offer free production licenses to non-profits, academic institutions, and personal or non-commercial use-cases (for instance, hobby projects). This is a common model in the software world, even for products where the source code is made available (free for personal use but requiring a license for commercial use).

Additionally, the availability of source code aligns with our commitment to transparency and collaboration. By making the code available, developers can continue to review, understand, and trust the underlying mechanics of Camunda's platform. We continue our commitment to developers and encourage experimentation, learning, sharing, and feedback which are essential aspects of product development and innovation.

**Comment by zxuanhong** [comment]
@nloding Thank you very much for your answer
