### ISSUE TITLE
Fix changelog for alpha1

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#18451]
_See related [thread](https://camunda.slack.com/archives/C05DH1F5TAR/p1715235879152049?thread_ts=1715152077.892199&cid=C05DH1F5TAR)_ 

**Problem:**

The changelog contains right now old issues that were not part of the release.

**Root cause:**

We have merged tasklist (and operate) git history into our repo. Tasklist is a younger project and referencing younger issues (lower issues numbers) with having these commits in our history our ZCL (changelog tool) gets confused and produces a wrong changelog.

**Comment by Zelldon** [comment]
Discussed during planning with @npepinpe and @felix-mueller 

We will time-box this, and whether it is easy to fix. If **not** we plan to write at least a note on the release notes, to mark the changelog as containing some old issues.

This issue will likely come back on 8.6.0, as this will be the next minor containing the Tasklist commits again in the changelog. BUT DevEx is currently working on a new way to visually represent our release notes in the docs, which makes our release notes maybe obsolete.

**Comment by Zelldon** [comment]
Taking a look at the zcl and where the magic is done https://github.com/zeebe-io/zeebe-changelog/blob/main/pkg/gitlog/gitlog.go

We can see that it is essential similar to: `$ git log -c 8.5.0..8.6.0-alpha1 --` and doing some regex magic to filter out the right commits and issue numbers.

As we now merge always with the merge commit, which contains the PR description and issue reference we actually can easily also use `git log --merges` To show [only merge commits](https://softwareengineering.stackexchange.com/questions/368373/easily-exclude-commits-on-a-merge-based-on-some-condition).

Furthermore, as Tasklist before didn't used merge commits this will help us to exclude this from the history/changelog.

@npepinpe what do you think about this approach? This would help us for upcoming release I think. 

Now we have the case that we already have issues marked. That we want to undo. Maybe we just delete the label and relabel them again?

**Comment by Zelldon** [comment]
Happy for input from @romansmirnov @houssain-barouni @cmur2 as well here (to the idea above)

**Comment by npepinpe** [comment]
Considering this is only to handle previous changes, it should work fine. Meaning, if Tasklist decides to use merge commits now, it shouldn't break anyway since they will sequence their issues with ours, so there won't be any collisions. The only issue is breaking things if we drop merge commits, but I don't foresee this since we use the merge queues.

**Comment by Zelldon** [comment]
# Update

I deleted the alpha1 label from the repo and recreated it.
Furthermore, I used the [modified](https://github.com/zeebe-io/zeebe-changelog/pull/16) version of `zcl` to reassign the labels and regenerate the changelog.

## Before

Around ~160 issues are referenced:

![2024-05-14_05-28](https://github.com/camunda/zeebe/assets/2758593/a48c3bce-1930-4483-aae6-5d9af7a6050e)

In the changelog we see a lot of old issues

![2024-05-14_05-29](https://github.com/camunda/zeebe/assets/2758593/a9d914d9-40bf-4c65-ab02-2159d1bf3b3f)

## After

![2024-05-14_05-35](https://github.com/camunda/zeebe/assets/2758593/72ab013f-d633-4f3c-8dd6-8e21e6af6332)

With the change only half of them were valid, and have been updated again.

![2024-05-14_05-46](https://github.com/camunda/zeebe/assets/2758593/45940d6f-95eb-40b2-ae8a-e2c3e1c69b0e)

![2024-05-14_05-56](https://github.com/camunda/zeebe/assets/2758593/b1d446e4-a1b0-467d-aff0-b9a3634762e1)

**Comment by Zelldon** [comment]
I created a new release of zcl https://github.com/zeebe-io/zeebe-changelog/releases/tag/v0.8.0

**Comment by Zelldon** [comment]
Ok looks like that Operate uses merge commits at the begin:

```
Author: Patrick Dehn <pedesen@users.noreply.github.com>
Date:   Tue Feb 25 09:30:46 2020 +0100

    Merge pull request #325 from camunda/OPE-887-flow-node-icon-names
    
    Align flow-node icon names

--
Author: Svetlana Dorokhova <svetlana.dorokhova@camunda.com>
Date:   Tue Feb 25 09:19:46 2020 +0100

    Merge pull request #318 from camunda/OPE-866-cloud-logging-nodeploy
    
    Implement JSON logging layout to be used in GCloud.
    
--
Author: Patrick Dehn <pedesen@users.noreply.github.com>
Date:   Mon Feb 24 16:40:23 2020 +0100

    Merge pull request #324 from camunda/OPE-883-select-all
    
    feat(List): add select all instances
```

This means this solution doesn't work well enough for 8.5.0 (it excludes already some but not all necessary old issues)

**Comment by Zelldon** [comment]
I might have found an solution based on the time of when the tag has been created 

```
git -C "./" log 8.4.0..8.5.0 --merges --since="$(git log -1 --format=%ai 8.4.0)" 
```

Git magic.

**Comment by Zelldon** [comment]
# Update 

Got it working with zcl and 8.5.0 as well.


We had around 880 issues marked with our 8.5.0 label.

![2024-05-14_09-47](https://github.com/camunda/zeebe/assets/2758593/c33ebb0b-5d85-487c-afd9-f16d505c31d8)

When the recent version 0.8.0 with using only merge commits, we came down to ~570 issues, but we were still referencing old issues.


![2024-05-14_09-54](https://github.com/camunda/zeebe/assets/2758593/797a1e65-e508-4574-bc36-4b67bff6e110)

The problem was [as described above that Operate used at the begin merge commits as well](https://github.com/camunda/zeebe/issues/18451#issuecomment-2109608543)

I was able to use the start tag date as filter with the `--since` flag in order to exclude old commits this reduced it down to ~440 issues.

![2024-05-14_10-51](https://github.com/camunda/zeebe/assets/2758593/c8e2d085-9fd0-4ce1-b215-1907c311e395)

**Comment by Zelldon** [comment]
Changelogs have been cleaned up. We now have a persistent solution, [release for ZCL as well](https://github.com/zeebe-io/zeebe-changelog/releases/tag/0.9.0). This should work for the upcoming release (8.6.0) as well.

**Comment by Zelldon** [comment]
Changelogs have been cleaned up. We now have a persistent solution, [release for ZCL as well](https://github.com/zeebe-io/zeebe-changelog/releases/tag/0.9.0). This should work for the upcoming release (8.6.0) as well. 

With this I will close this issue.
