### ISSUE TITLE
Allow to use DNS for cluster membership

### ISSUE THREAD

**Issue by menski** [camunda/zeebe#1930]
https://atomix.io/docs/latest/user-manual/configuration/reference/

**Comment by npepinpe** [comment]
Here the idea is to allow users to use a DNS SRV record - such as the one Kubernetes provides with services - which would replace the bootstrap discovery protocol, where the user has to specify the nodes addresses beforehand.

**Comment by Zelldon** [comment]
I think we can reopen this if we really want to work on this, not a priority at the moment.
