### ISSUE TITLE
Replace TopologyListeners with Atomix Pub-Sub mechanics

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#2463]
Currently in the DeploymentDistributor and SubscriptionCommandSender we use the Topology, more specific a TopologyPartitionListener to determine the leader for a partition. If we could remove these listener usage we would be able to remove the complete Topology stuff from the broker, since the topology request is now directly answered on the gateway with the help of atomix.

To remove the partition listener we could use atomix Pub-Sub mechanics. We could create for each partition a subscription topic. On the subscription command sending we will then send direct to the specific partition subscription and for  deployment distribution we need only one subscription, where the first node distributes this deployment over the specific topic.

**Comment by Zelldon** [comment]
Since we only listen or subscribe to the specific topics on the leader we do not need to know which is the leader for a partition.

**Comment by npepinpe** [comment]
I think this is done for DeploymentDistributor but not yet for the other.

**Comment by aivinog1** [comment]
@npepinpe @Zelldon Hello! I can try to do this one. As I understand the main issue goal is to replace `io.zeebe.broker.clustering.topology.TopologyPartitionListenerImpl` to the Atomix Pub-Sub mechanism. That sound to not so complicated to me :) If you know some pitfalls on this, please let me know :)

**Comment by npepinpe** [comment]
Hey @aivinog1, if I read this correctly, this is about changing the `PartitionCommandSenderImpl` to use the Atomix pub-sub facilities - which means we can then remove all the `Topology` stuff from the broker. So there's nothing to change in the `TopologyManager` itself :+1:

**Comment by npepinpe** [comment]
Random question, maybe someone can give more input:

1. Why are we not using the command API to send commands between brokers? Is it because it's not per partition but per broker? It would simplify the code to some extent, but it might be problematic to deal with stuff like back pressure...maybe we make too many assumptions in the command API about __user__ commands.
1. What about subscribing to a single topic for inter-broker communication (a bit like the command API, but on a per partition basis when you become leader), and just handling them like we do for the command API? i.e. wrap it in an `ExecuteCommandRequest` and just write it to the dispatcher. i.e. `InternalCommandApi` or something? Terrible name but you get the idea

**Comment by Zelldon** [comment]
As I wrote in slack, regarding to point one.

>I think @saig0 can also give you guys input on this, but just shortly from my side.
> 
> I think it is historically related, mostly. In the past we had several endpoints/ports for internal, external traffic etc. We differentiated between them and at some point we removed more and more. The only left things are deployments and message subscriptions. Be also aware that we already had three different deployment replication strategies etc. Message subscriptions was implemented and after that the deployment distribution again refactored and implemented similar to the message subscription stuff.
> 
> Off the top of my head I find nothing what speaks against moving to command api, just the back pressure topic, which need to be handled then. But shouldn't be a blocker. The implementations are anyway implemented in a resilient way, which means they will retry after some time etc. The different partitions have different DeploymentProcessor and handle the CREATE differently so this should also be fine.

Regarding to point 2, not sure what you mean this is how the command api works. If the broker becomes leader the command api subscribes to the specific topic.

**Comment by npepinpe** [comment]
Yeah this is what I meant, but just not going over the command API (so not mixing user/internal commands) - I added that in case there were major concerns about reusing the command API.

**Comment by Zelldon** [comment]
I think this issue is out dated, we still need the topology in the broker to publish the changes via SWIM + we have replaced the DeploymentDistributor with InterPartitionCommandSender
