### ISSUE TITLE
Refactor the DeploymentDistributorImpl

### ISSUE THREAD

**Issue by MiguelPires** [camunda/zeebe#2764]
Currently the DeploymentDistributorImpl has a few problems. Namely, it might fail if a retry happens after another push is made (https://github.com/zeebe-io/zeebe/issues/2735) but also related logic is split is different places which might make this component hard to understand. For instance, there are two handlers that handle responses. One that handles a response sent after the CREATE is "written" and the second that handles a response after the CREATE is processed (this is necessary because when the first response happens, the event wasn't written to persistent storage and might be lost). For these reasons, the distributor should be refactored

**Comment by MiguelPires** [comment]
The DeploymentDistributorImpl is very tightly coupled with Atomix and ActorControl which makes it hard to test the retry logic at a unit test level. An integration test is also not an option, since we have to send a deployment request and then close a leader, which creates a race condition and, in turn, a flaky test (you can't be sure that a new leader isn't elected before the deployment in pushed). The bugs in issues https://github.com/zeebe-io/zeebe/issues/2818 and https://github.com/zeebe-io/zeebe/issues/2735 are consequences of the under-testing of the deployment/retry logic.

**Comment by npepinpe** [comment]
The next time we have a bug in the deployment distributor, please do this issue first. I understand that's difficult to keep track of, but unfortunately there're more pressing issues for us to achieve our current goals for Camunda Cloud.

**Comment by Zelldon** [comment]
I think this was replaced with the InterPartitionCommandSender, correct me if I'm wrong @oleschoenburg
