### ISSUE TITLE
Mapping on a target overwrites previous mapping

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#297]
If we have the following scenario:

```
{
  'x': {
    'a': 1
  },
  'y': 2
}
```

Mapping:
```
x -> z
y -> z.b
```

We would expect the following:
```
{
  'z': {
    'a': 1,
    'b': 2
  }
}
```

Currently, the first mapping will be overwritten with the second mapping, which means the result is:

```
{
  'z': {
    'b': 2
  }
}
```

**Comment by saig0** [comment]
The bug still exists in 0.22.0. I updated the examples to the current variable mapping.

**Comment by Zelldon** [comment]
@saig0 this is fixed due to feel usage or?

**Comment by saig0** [comment]
No, this is still the case with version 0.23.0.

Workaround with magical FEEL expression: :mage: 
```
source: =appendTo(x,{b:y})
target: z
```

**Comment by kbakk** [comment]
It took some testing out to understand the above example, here's another:

|Workflow Instance Variables (initial)|Job/Message Variables|Output Mappings|Workflow Instance Variables (after)|
| --- | --- | --- | --- | 
| `x: {a: 1}` | `result: {b: 2}` | `=appendTo(x, result)` | `x: {a: 1, b: 2}` |

**Comment by kbakk** [comment]
I think it's worth pointing out that `appendTo` function isn't actually part of feel-scala (thus it's not documented here https://camunda.github.io/feel-scala/), but an extension (?) to feel-scala defined in Zeebe.

https://github.com/zeebe-io/zeebe/blob/dfa79fa0e85015b35f401a2bb29e14c1fb5a83cf/expression-language/src/main/scala/io/zeebe/el/impl/feel/FeelFunctionProvider.scala#L19

There's an open issue to implement this "natively" in feel-scala: https://github.com/camunda/feel-scala/issues/169

**Comment by korthout** [comment]
After discussing the topic internally, I'd like to add that the `appendTo` function in Zeebe is an internal function and purposely undocumented. When camunda/feel-scala#169 is implemented, the `appendTo` function in Zeebe will be replaced. Please keep this in mind when using this function.

**Comment by Zelldon** [comment]
I think we can close this. There is a clear workaround, and no one complained since this existed. Feel free to reopen.

**Comment by saig0** [comment]
**Reproducer**

CPT test case to reproduce the behavior:

```java
    @Test
    void shouldMergeOutputMappings() {
      // given
      final BpmnModelInstance process =
          Bpmn.createExecutableProcess("process")
              .startEvent()
              .userTask("userTask", u -> u.zeebeUserTask())
              .zeebeOutputExpression("x", "z")
              .zeebeOutputExpression("y", "z.b")
              .done();

      client.newDeployResourceCommand().addProcessModel(process, "process.bpmn").send().join();

      // when
      final Map<String, Object> processVariables = new HashMap<>();
      processVariables.put("x", Collections.singletonMap("a", 1));
      processVariables.put("y", 2);
      final ProcessInstanceEvent processInstance =
          client
              .newCreateInstanceCommand()
              .bpmnProcessId("process")
              .latestVersion()
              .variables(processVariables)
              .send()
              .join();

      final Map<String, Object> userTaskVariables = new HashMap<>();
      processTestContext.completeUserTask(
          UserTaskSelectors.byElementId("userTask"), userTaskVariables);

      // then
      final Map<String, Object> expectedVariables = new HashMap<>();
      expectedVariables.put("a", 1);
      expectedVariables.put("b", 2);
      CamundaAssert.assertThatProcessInstance(processInstance)
          .isCompleted()
          .hasVariable("z", expectedVariables);
    }
```
