### ISSUE TITLE
Investigate why backpressure is too pessimistically dropping requests

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#3137]
**Description**

Broker is dropping some requests even if it hasn't reached the maximum throughput it can handle. If we gradually increase the load on the broker, we can observe that at some point, a few requests are getting dropped due to back-pressure. But if we increase the load further, we can still see an increase in throughput without higher latency.

**Comment by deepthidevaki** [comment]
One reason for this behavior is that the requests rate is not uniform across the time. Sometimes the brokers receive many requests when the back-pressure queue is already full, other times the queue is empty. We should handle these short "bursts" of requests without aggressively dropping them.

One way which many systems handle this is by having LIFO queue in CommandApiHandler. When the backpressure queue is full, instead of dropping the requests they can be put in the queue. If there is a constant high rate of incoming requests, the requests will be timed out and can be dropped. But if it was a short burst of requests, we will be able to process them with in a short delay.

- https://blogs.dropbox.com/tech/2018/03/meet-bandaid-the-dropbox-service-proxy/
- https://queue.acm.org/detail.cfm?id=2839461

**Comment by npepinpe** [comment]
> Bandaid queueing can also support dropping requests once the queue reaches a configurable maximum capacity threshold. However, we don’t recommend this since it’s hard to distinguish whether a queue is full due to system overload or because of bursty traffic.

I'm not sure what to make of this for our use case.

**Comment by deepthidevaki** [comment]
It is the similar case as we have now. We drop requests when the back-pressure queue is full. But that doesn't mean the system is constantly under overload. But in our case we cannot accept more requests until back-pressure queue has space. Instead we should probably have another queue in front of the back-pressure to buffer the requests. Whether the max capacity of it should be restricted or not, I don't know yet.

**Comment by npepinpe** [comment]
> Whether the max capacity of it should be restricted or not, I don't know yet.

This is what I meant; they recommend against, which may make sense for a HA service like Dropbox, but I don't know if this makes sense for us, we probably don't want the queue to grow infinitely as it could be a DDoS vector.

**Comment by Zelldon** [comment]
@deepthidevaki I think we can close this right?

**Comment by deepthidevaki** [comment]
We can close this. With #10747 the situation would have improved. It does not handle "bursts" as I explained in https://github.com/camunda/zeebe/issues/3137#issuecomment-553415001 But that is a different problem.
