### ISSUE TITLE
Feature: Start workflow from an arbitrary point (enables migrate workflow instance)

### ISSUE THREAD

**Issue by jwulf** [camunda/zeebe#3254]
**Is your feature request related to a problem? Please describe.**
When you want to migrate to different cluster, it would be useful to be able to rehydrate running processes from a previous instance. This could also be used to migrate running processes to a new process version on the same cluster.

**Describe the solution you'd like**
An extension to the CreateWorkflowInstance command that allows you to specify the element to start at. This allows you to take the variables from one running instance and pass them to the command, along with the process version, and start the new process instance at an arbitrary point.

**Comment by StephenOTT** [comment]
Any timeline on this?  It's a major blocker for anyone that has any level of need for recoverable processes

**Comment by B-Stefan** [comment]
For our use case this a must-have for long-running tasks or tasks that are waiting for some messages. We evaluate Zebee to start processes based on messages and wait for specific messages during the process.

The time between the start of the process and the end can be up to 2 years, so the process definition will change over time.

**Comment by jwulf** [comment]
A complete implementation of this is complex. It needs to handle multiple states - subprocesses, running timers - and mapping those states onto states that may or may not exist in the new process, depending on the degree and nature of the change.

But maybe we could provide a simple, limited-scope feature that would support 80% of cases.

This could be a `createWorkflowInstanceAtElement` command.

It would be like `createWorkflowInstance`, but additionally it would take a start element to begin from.

This would allow rigging of migration of instances in some scenarios.

It would allow effective migration of processes that have only a main process state and are waiting on a timer or a message correlation event.

If it were waiting at a running timer, the timer would be reset.

A consideration is the window in which both process instances are running. It would be best to wrap it in a transction:

* Suspend execution of the initial workflow instance
* Create a new workflow instance
* Terminate the previous instance

This could be managed client-side to begin with, if there were a `suspendInstance` command.

**Comment by B-Stefan** [comment]
@jwulf 
Thanks for the idea and you are right to implement this 100% would be really complicated. 

I think the solution to create a new instance from a starting point with `createWorkflowInstanceAtElement` would work great for linear processes but as soon as you use the non-interrupting error events or any other parallel structure this will could some problems.

What do you think about a solution where we can create a new Instance in a suspended status and create tokens and add variables more granularly and flexible.  

Something like: 

```
createWorkflowInstance(..., { suspend: true })
addToken(workflowInstance, nodeId, state)
addToken(workflowInstance, nodeId, state)
resumeWorkflowInstance(workflowInstance)
```

This would support more use cases and provide a flexible solution for developers. 

Just to summarize our use case in more detail: 

1. Create a workflow instance 
2. Instance waits for 5 days 
3. A new version of workflow e.g. email template got changed
4. The instance from step two should use the new template

**Comment by menski** [comment]
We are currently working on a concept for this feature.

**Comment by jwulf** [comment]
> We are currently working on a concept for this feature.

Any more information on this?

**Comment by tahasabih** [comment]
@menski will this be on the release roadmap soon?

**Comment by cen1** [comment]
What are the currently recommended steps for workflow versioning and migration? Is it the easiest and safest choice to simply deploy the newer workflow version in parallel and let the old workflow tasks naturally come to a close before removing the old workflow?

**Comment by jwulf** [comment]
You cannot remove process definitions. If you deploy a newer version, then any commands to start a process instance that do not specify a version will use the latest version. Existing process instances will keep using the version of the definition they started with. New process instances can be started using the older process definition by specifying its version number.

**Comment by jwulf** [comment]
There is no easy or standard way to do this. 

You would have to design your process and the implementation to facilitate it. It would increase your system complexity significantly.

**Comment by aivinog1** [comment]
Hey @npepinpe @jwulf @menski! I would like to take this one if you don't mind :) So, if you have already sketches of design, vision, or other stuff of this I will be glad to hear it :)

**Comment by saig0** [comment]
> I would like to take this one if you don't mind :)

@aivinog1 thank you for your offering :+1: 

However, this is a pretty big and complex feature. It must be implemented for all BPMN elements and extends the core workflow engine with completely new concepts.

Unfortunately, I think this feature is not suitable for external contributions. But the feature is on our roadmap for the next quarter(s) and the Zeebe team will work on it soon :rocket:

**Comment by aivinog1** [comment]
@saig0 Cool, thanks! :)

**Comment by wooyea** [comment]
@saig0  Are you working on it? I need this feature to migrate zeebe from 0.26 to 1.31+ in product env.  I would make a emergency patch before march if official version not existed by then.

**Comment by saig0** [comment]
> Are you working on it?

**Comment by korthout** [comment]
As we're shifting focus towards this feature, please find #9366 for progress details.

**Comment by korthout** [comment]
🚀 This feature is scheduled to be released with [`8.1.0-alpha3`](https://github.com/camunda/zeebe/releases/tag/8.1.0-alpha3), so I'm closing this issue.

**Comment by knji** [comment]
Does anyone know if this feature was ever released? I do not see a mention of this in the above release notes.

**Comment by korthout** [comment]
Hi @knji. It's available. Please see the related documentation https://docs.camunda.io/docs/components/concepts/process-instance-creation/#create-and-start-at-a-user-defined-element
