### ISSUE TITLE
Support for pre and post deployment hooks

### ISSUE THREAD

**Issue by ysaakpr** [camunda/zeebe#3342]
We are evaluating zeebe in our org, as end to end orchestration of micro services. Planning to use zeebe as central orchestration service. We found its promising all the features that we needed, but lacking one, the ability to validate the process and workflow definitions. The only way that one can define how to drive the process is by defining workflows. The exporter pattern is not useful to validate the workflows getting deployed.

We evaluated there are couple of way to achieve it. One could be override the client and modify the clients to validate the deployments, with custom logic's. But still a user can use and talk to Zeebe service and upload. 
Another way is to add a proxy in front of the Zeebe cluster and route the specific Deployment command to another service and internally call the service once validated.
I believe both of these approaches are not that convenient for a a bigger user base.

I was thinking of writing validator hooks, very similar to how exporters work. Which gives high flexibility for customizing the workflow validations.

For eg: the conf will look like:
```
[[hooks]]
deployment.pre_hook: [ "com.org.hooks.DeploymentPreHook" ]
deployment.post_hook: [ "com.org.hooks.DeploymentPostHook" ]
otherevent.post_hook: [ "com.org.hooks.OtherEventPostHook" ]
```

Another option would be to support Validation over grpc service calls, instead of jar, but i believe the exporter pattern would be nice according to me.

**Comment by saig0** [comment]
@ysaakpr, thank you for raising this up. It is an interesting idea. 

What concrete validations do you want to perform?
Do you just want to validate the workflow or modify it?
Please share more details about your use case :)

**Comment by jwulf** [comment]
The broker will return an error response if you attempt to deploy an invalid BPMN file.

Doing a PR against a client lib would be one way to get it further forward. I put some functionality along those lines in the Node client to support generating type information from the BPMN file. See https://github.com/creditsenseau/zeebe-client-node-js/blob/master/src/lib/BpmnParser.ts

**Comment by ysaakpr** [comment]
We are using zeebe as organization-wide micro service orchestrator. And hence multiple teams will be creating workflows in the system. So the task types can be conflicted between teams. We need to ensure that the task types are following a certain naming strategy and task names have to be registered in the central task type registry in order to identify who owns a task and enable discovery for tasks types. Which will be usable for Product teams to define the workflow.

As @jwulf mentioned, which can be achieved by modifying the client library, but I think this can be improved further to validate(I am not meant to validate the BPMN grammar, rather few businesses and org level custom validations around the conventions to be followed)

**Comment by ysaakpr** [comment]
Implementing this at client level cause all the language stack to implement the validation, and ensure migrations are also doing for the clients. I believe adding validation hooks at the server-side would be more lean-approach.

**Comment by jwulf** [comment]
You could do this in git hooks? Then you have it further forward in your CI, and for free.

**Comment by jwulf** [comment]
There are at two separate features here - it may be worth splitting them out.

1. Task type validation pre-deploy (could be done in CI)
2. Authorization of different Zeebe gRPC commands - for example green list `createWorkflowInstance` command, red list `deployWorkflow` command for a user.

**Comment by jwulf** [comment]
2. You might be able to do in an nginx route by redirecting unauthorized calls to `deployWorkflow`. See: https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-3-publishing-grpc-services/

**Comment by ysaakpr** [comment]
@jwulf As you mentioned,
1. BPMN lint or [Validator](https://github.com/camundacloud/workflow-validator) is a pre-deploy solution and mostly does the validation as per BPMN standard. In my case, we are using Zeebe as an org level microservice orchestration framework, and because of this, we need to attain certain regulations, which is custom logics, beyond the scope of standard validators. And same time different teams following different deployment process pretty much difficult to enforce the process to each team to do the validations at the user side. 
2. Using a proxy in front of zeebe cluster, like nginx or envoy, gives the ability to route the request. Given that a feature like this adds more flexibility to the zeebe users to extend zeebe functionality beyond this simple validation as well. And the one thing that I read in the documentation, zeebe is a standalone system without zero other components. I still believe that providing the hooks to do certain actions on specific events are useful for the extensibility of the service.

**Comment by ysaakpr** [comment]
> 1. You might be able to do in an nginx route by redirecting unauthorized calls to `deployWorkflow`. See: https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-3-publishing-grpc-services/
> 
> This is a nearer-term solution than getting an authorization framework in the broker. That's a complex feature.

At first, we don't need to aim for a fully capable Authorization framework inside the broker, but an ability to add custom decision logics will help the users to do certain validations, that can be even authorization, validations, handling notifications etc.

**Comment by jwulf** [comment]
I like the deploy hooks idea. Although my vote is for a webhook. It's decoupled and language-independent.

**Comment by ysaakpr** [comment]
I agree, if we can define GRPC protocols/protobuf structs for services for defining deploy hooks, it will be more structured and users can implement the functionalities easily.

**Comment by ysaakpr** [comment]
If you all agree with, What should be the next step? If everyone agrees to go with WebHook, I could start working on a prototype, by which a user can register pre and post-deploy WebHooks

**Comment by ysaakpr** [comment]
Any update on this? Can we confirm if this is possible?

**Comment by saig0** [comment]
Using a WebHook in the validation phase of the deployment would be a bigger topic. Since this calls an external system, the validation step must be done asynchronously. It would need new gRPC commands for communication and it should care about security.

An easier solution would be an extension point for a Java validator. The validator can be included similar to an exporter. While processing the deployment, the validator can be called directly/synchronously. Since the validator is written in Java, it can use the model API to read the workflow model easily.

@ysaakpr, what do you think about the alternative?

**Comment by ysaakpr** [comment]
A java validator idea I have tried, but immediately got into the issue of forcing all teams to updations the. the library that we shared, with a couple of services itself it caused an issue and we stopped it and making a validator to call an external service now, I think java validator based validation is good if the evolution is minimal to validation and small usage, for multi team usage, its not possible.

**Comment by Zelldon** [comment]
I will close this, since it became stale. Feel free to reopen it. Just want to mention we have listeners which you can register on the gateway to intercept grcp requests this might help your use case.
