### ISSUE TITLE
Provide some sort of exception or visual indicator to indicate that a task has no workers polling for it

### ISSUE THREAD

**Issue by Klaus-Nji-sp** [camunda/zeebe#3352]
**Is your feature request related to a problem? Please describe.**
If I start a workflow with a service task of type _task-not-deployed_ , execution stops or halts at this service task if it has not yet been registered with the broker without any visual clue or a message indicating that the task named _task-not-deployed_ is not reachable or available.

**Describe the solution you'd like**
I imagine that when a task is registered using 

`client.newWorker().jobType("my-task-name").handler(jobHandler).open();`

the broker keeps an account of these tasks somewhere.  During execution, when the broker is attempting to resolve a task to execute based on the name, what does it do when it cannot resolve this task?  

I propose the broker throw some sort of exception indicating that a task in the flow is not reachable (not known), possibly triggering an incident.  Users can respond to the incident by dealing with the external circumstance after which the incident can be resolved.  I imagine this to be similar to dealing with an HTTP 404.

**Describe alternatives you've considered**

**Additional context**
During a demo, I had an executing workflow stuck at an http task.  Execution was stuck because the Java application which registers this http task with the broker was not launched.  If there was some sort of indication in operate or simple monitor indicating that the http task cannot be reached, this would have given me indication that a service is not defined.  Please note that this is a similar experience to an unreachable service.

**Comment by Zelldon** [comment]
It is an old issue but I guess it is still relevant to some users, right now this is not possible with the current implementation. The broker nor the engine knows whether there have been any workers registered, the workers do ask for jobs but there is not a registry or the like. 

You can model this in your process via timer boundary event, which cancels the task if it was not completed in X minutes.

I will close this issue for now.
