### ISSUE TITLE
Customize input/output mapping of nested variables

### ISSUE THREAD

**Issue by road21** [camunda/zeebe#3436]
When we have some variables in context like:
`{ "a": { "x": "x", "y": "y" }, "z": "z" }`
and input mapping of the worker like: `z -> a.x`, we get worker context:
`{ "a": {"x":"z"} }`.
But sometimes user wants just to change single nested field and keep other nested fields:
`{ "a":{"x":"z","y":"y"} }`.
Now to get this user has to list all nested variables: 
`z -> a.x and a.y -> a.y`.
It can be very complex and error prone when `a` has a lot of fields.

May be we need some other way to get this?

**Comment by npepinpe** [comment]
Related to #297

**Comment by Zelldon** [comment]
Please see the workaround here https://github.com/camunda/zeebe/issues/297#issuecomment-736545351

I will close this for now. If it doesn't fulfill your needs we can reopen the issue
