### ISSUE TITLE
Define an error code statically or as expression 

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#3801]
**Is your feature request related to a problem? Please describe.**
For an error event (boundary/event subprocess/end), I can define the `errorCode` as a string or dynamically as an expression.

**Describe the solution you'd like**
Same as in #3792.

**Additional context**
Currently, error catch events are not materialized as subscriptions in the state. When an error is thrown then the handler walks through the scope hierarchy and checks the error codes. In order to be consistent with timer and message events, the `errorCode` expression must be evaluated when the event scope is activated.

**Comment by menski** [comment]
@npepinpe I would propose that we finish this topic if someone has some time to spare

**Comment by menski** [comment]
@felix-mueller we need an epic in product hub to organize the collaboration with other teams for this

**Comment by remcowesterhoud** [comment]
This issue also mentions expressions for the catch events. This won't be part of the PR #10972.

It requires too much extra effort for something that has a questionable use-case. I propose we will close this issue when #10972 is merged. We can create a new issue if we get requests for expressions on the catch events.
