### ISSUE TITLE
Harmonize java client API

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#3819]
**Description**

There are several inconsistencies in the java client API, which could be harmonized:
* `UpdateRetriesJobCommand` (java client API, and ZeebeClient) vs. `JobUpdateRetriesCommandImpl` (java client impl) vs. `UpdateJobRetriesRequest` (gRPC)
* `Topology` (java client API) vs. `ToplogyResponse` (gRPC); also this request doesn't follow the naming convention of the other commands. It doesn't have a verb in the title. 
* `ZeebeClient.newDeployCommand()` vs. `DeployWorkflowCommand`
* `ZeebeClient.newCreate/CancelInstanceCommand` vs. `Create/CancelWorkflowInstanceCommand`

**Comment by Zelldon** [comment]
Due to backwards compatibility we can't change the api
