### ISSUE TITLE
Write unit tests for ExporterConfiguration and then replace GSON with Jackson

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#4037]
**Description**

* Increase unit tests for exporter configuration and concrete exporter configuration users (e.g. ElasticsearchExporter, Debug Exporter etc.)
* Identify data types used for existing exporters
* Refactor implementation of data binding mechanism to use Jackson instead of GSON
* Verify that the behavior did not change

**Background**
* `ExporterConfiguration` is one of the last places where we use GSON, whereas in many other places we use Jackson consistently
* It is used to bind settings from a configuration source to instances of a exporter configuration classe´
* Ideally we would only use Jackson consistently throughout the codebase
* Changing the implementation is a bit risky. The default output of GSON and Jackson are not identical (e.g. for classes like Duration, DataSize), so changing the implementation will likely change behavior

**Comment by npepinpe** [comment]
Done in #9854
