### ISSUE TITLE
Update variables on BPMN error

### ISSUE THREAD

**Issue by jwulf** [camunda/zeebe#4080]
At the moment you can't implement a retry loop with a timer that is entered via a BPMN error throw and has decrementing retries:

<img width="286" alt="Screen Shot 2020-03-20 at 1 24 26 am" src="https://user-images.githubusercontent.com/406975/77083787-c5afa180-6a49-11ea-985d-8f1143342714.png">

What I'd like to be able to do is this: 

<img width="564" alt="Screen Shot 2020-03-20 at 1 25 52 am" src="https://user-images.githubusercontent.com/406975/77083796-c8aa9200-6a49-11ea-8ace-7c6b53a1b81e.png">

However, there is no opportunity to mutate anything when throwing a bpmn error from the client....

**Comment by jwulf** [comment]
If you could mutate with the error throw, you could even do a back-off retry in the worker.

**Comment by saig0** [comment]
Is this request only about providing a timeout before a failed job is retried?
If yes then this may be better implemented directly as part of the `FailJob` command (#164) instead of modelling it (maybe multiple times) in the workflow.

**Comment by berndruecker** [comment]
For the issue at hand I do agree, that the increasing retry interval should be baked in the retrying of the service task itself (but probably we could have out-of-the-box support for that in future). It is not an error with any business reaction (that's what BPMN error events are for), but a technical problem that will probably be solved by retrying or end up with an incident. This should in general not be modeled. I thought I can easily point to a BP - but I think we should probably add this rule of thumb there: https://camunda.com/best-practices/dealing-with-problems-and-exceptions/#_distinguishing_between_strong_exceptions_strong_and_strong_results_strong

Adding payload alongside the error seems like an interesting option - but not related to this problem IMHO.

**Comment by ezolnbl** [comment]
:+1: +1

**Comment by skayliu** [comment]
![image](https://user-images.githubusercontent.com/26370117/198682678-6c02e5d5-b8bc-4be1-ba56-cb19f7dd2b00.png)
