### ISSUE TITLE
zbctl does not support custom CredentialProviders (extra http header for grpc messages)

### ISSUE THREAD

**Issue by arfejes** [camunda/zeebe#4119]
**Description**

There is a feature in the java and go libraries of zeebe where I can create my own CredentialProvider which would allow me to put extra headers in the http header of the grpc messages between the client and the gateway. [Documentation here.](https://docs.zeebe.io/operations/authorization.html?highlight=credentialProvider#credentials-provider) I can't put the same stuff into the header using zbct because it is only prepared to use one specific implementation of the CredentialProvider, the oauth one provided by you.

**Comment by Zelldon** [comment]
Looks like the issue became stale, as far as I know this is not a priority right now and tbh I see no need for it. Correct me if I'm wrong, but I will close it for now. If anyone is still interested in this feel free to reopen it.
