### ISSUE TITLE
Clean up pending or invalid snapshots in StateControllerImpl

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#4671]
**Description**

Currently the `StateControllerImpl` receives the snapshot chunks and hold an reference for each received snapshot. If the snapshot is valid and all chunks have been received it is removed from the in memory map. If the snapshot is invalid then it is marked as invalid in the hash map, but it is never removed from there. Furthermore if we not receive all snapshot chunks we never remove the corresponding snapshot from the map. We should clean up the map after we received and validated a snapshot.

**Comment by npepinpe** [comment]
Is this still the case after the refactoring? I think we now abort previous replications, so I think this would be fixed? In either case, I don't see this as high priority in my opinion, as it does not immediately help us with our current OKRs.

**Comment by Zelldon** [comment]
It is still the case.

**Comment by npepinpe** [comment]
We can close this since we don't replicate snapshots other than in Raft now, I think. Reopen if this isn't the case.
