### ISSUE TITLE
Signal Events not supported in Zeebe

### ISSUE THREAD

**Issue by arpitagarwal78** [camunda/zeebe#4680]
**Description**
Currently Zeebe only supports single message event to be correlated inspite of multiple identical message events defined.

Ex.

![StartMe](https://user-images.githubusercontent.com/37263155/84031771-e71e8a80-a9b3-11ea-8883-82b29688e062.png)

In the above figure we have a scenario having 2 `StartMe` event but on posting `StartMe` message only one of them is honoured 

PFA StartMe.bpmn file

[StartMe.bpmn.txt](https://github.com/zeebe-io/zeebe/files/4745984/StartMe.bpmn.txt)

Note:
This is not only limited to just the `Intermediate Throw Event` but can also be the case with `Boundary Events` as

![BoundaryEvent](https://user-images.githubusercontent.com/37263155/84032121-7461df00-a9b4-11ea-8f31-10932b993599.png)

Irrespective from any case all the identical events should be honoured at one go (`Signal Events`).

**Comment by Zelldon** [comment]
superseded by EPIC https://github.com/camunda/zeebe/issues/10777 this feature will be implemented.
