### ISSUE TITLE
Vendor Go build tools instead of using go get/downloading them

### ISSUE THREAD

**Issue by MiguelPires** [camunda/zeebe#4908]
**Description**

It's possible to use go modules to vendor the tools we use in our development process. The advantage of vendoring the build tools would be mostly that is simplifies our interaction with them (especially for devs who don't usually use Go and might not have the tools installed) and simplifies our CI scripts as well. Managing the version of these tools would also be easier, since it'd be centralized and automatically downloaded by `go mod`.

https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by Zelldon** [comment]
I don't see us doing that in the near future, so I will close this. Tbh I hope we can move the client out at some point.
