### ISSUE TITLE
Log reason for shutdown

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#5108]
**Is your feature request related to a problem? Please describe.**
Looking at the logs it is not immediately obvious if Zeebe performed a shutdown due to an external event or an internal error condition.

**Describe the solution you'd like**
I would like to have a clear log message at the begin of the shutdown whether it is an orderly shutdown, or an error.

**Comment by npepinpe** [comment]
Please add a log statement when we receive a shutdown signal (e.g. Runtime shutdown hook)

**Comment by pihme** [comment]
@korthout I think I will close this issue as won't do. I would like to hear your opinion first, though.

I want to close it as won't do, because currently it doesn't add value.

I was expecting to find something like this in the code base:
```
// this does exist
...
    getRuntime()
        .addShutdownHook(
            new Thread("Broker close Thread") {
              @Override
              public void run() {
                  LOG.info("Received shutdown signal via runtime shutdown hook");
                  broker.close();
              }
            });
...

//this does not exist
...
    Thread.setDefaultUncaughtExceptionHandler((thread, throwable) -> {
      if (exceptionAnalzer.canWeRecoverFromThis(throwable)) {
        // run recovery operation
      } else {
        Log.INFO("Shutting down due to unhandled exception " + throwable);
        broker.close();
      }
    });
...
```

So basically, we only shutdown the broker orderly when we receive a shutdown hook. Worse even, a shutdown hook is also triggered when somebody calls `System.exit`. So that log message will not tell me whether the shutdown was initiated by the application internally, or whether it was triggered externally.

Now, we don't have any calls to `System.exit` in our code base. Maybe calls exist in dependencies, but I would consider it unlikely.

Then I looked for a way to intercept and log `System.exit` calls. This would be helpful if we see a stack trace and know who called `System.exit`. The only way I found to implement this is to register our own `SecurityManager` and overwrite the `checkExit` method. 

Now, this is doable. But playing around with it I found that registering our own `SecurityManager` comes with unexpected side effects. It is possible to implement around them. But by and large I didn't want to mess with `SecurityManagers` just for the small chance that maybe `System.exit` gets called someday.

So after all this, I think it's not worth adding a log message for the shutdown. I think it makes more sense to revisit this topic when we shut down the system actively in response to unrecoverable failures.

Please let me know your thoughts.

**Comment by korthout** [comment]
Shortly discussed f2f. Please document what needs to be done to achieve this

**Comment by pihme** [comment]
After discussing it with Nico, we decided to put it back into the backlog.

Implementing this will only make sense and add value after we have cases where we shut down the system ourselves - e.g. in response to an unrecoverable failure. Then it will be interesting to know the reason for the shutdown.

**Comment by Zelldon** [comment]
I think we can close this for now. This is nothing we will do in the near future, and if we see the need we can easily add it (or reopen the issue)
