### ISSUE TITLE
Startup failure of one raft partition server affects the availability of other healthy partition

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#5209]
**Description**
Currently we start zeebe partition services only after atomix is fully started. That means if a node has 3 partitions, we wait until all 3 partitions has successfully started their raft servers. In some benchmarks it was observed that sometimes 2 partitions in a node succesfuly starts and become the raft leaders. But the third partition did not join, or took long (hours) to join (due to #5208 ). During this time, this node is the raft leader for 2 partitions, but no processing is happening because we don't install stream processor and other leader services until the atomix start is completed. As a result, the service is unavailable or only partially available even though there are leaders for all partitions.

**Comment by Zelldon** [comment]
I think this goes in hand with removing the complete atomix wrapper and bootstrap logic, which wanted to do anyway at some point. I think it makes sense to remove it and have independent starters for each partition.

**Comment by deepthidevaki** [comment]
Is there an issue for it already? If so, let's link it here.

**Comment by Zelldon** [comment]
Unfortunately I haven't found it in the backlog. That's why I just commented it :smile:

**Comment by npepinpe** [comment]
Do we see any blockers to starting partitions in parallel without waiting for the others to be started?

**Comment by Zelldon** [comment]
I see no blockers. Maybe @deepthidevaki has some thoughts?

**Comment by deepthidevaki** [comment]
No real blockers that I know. We would have to refactor atomix interface. There should be a way to detect when an individual partition is started and ready. For a single partition, the steps in bootstrap are the following in order.
1. RaftPartitionServer is created
2. Become follower
3. Leader election happens
4. Join completes
5. Catch up if needed
6. Marked as Ready -> Startup complete.

We have to ensure that zeebe services are installed only after step 6. Currently, we do `atomix.start().join()`, this is guaranteed.

**Comment by Zelldon** [comment]
What we could to instead is: to split already at step 6 for each partition in sub steps. The other steps can also be started

**Comment by npepinpe** [comment]
Would love to improve the bootstrapping logic next quarter - let's see if we can make it happen.

**Comment by megglos** [comment]
planning: affects higher partition count setups more heavily, risk of incidents,
let's time-box the investigation to 2h

**Comment by oleschoenburg** [comment]
I looked into this, mostly to understand the startup process.
To me it looks like we have two "barriers" that wait for all partitions before continuing the startup process:
1. `RaftPartitionGroup#join` waits for all raft partitions [to become `READY`](https://github.com/camunda/zeebe/blob/f574c79929f01e51f33a3d5902fc651aa15c3d46/atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java#L191-L197). This is [called by the PartitionManger](https://github.com/camunda/zeebe/blob/6a454eedc03e14d4f7fa56e5560c4febfbe57f89/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java#L128-L129) before scheduling `ZeebePartition`s. 
2.  `PartitionManagerImpl#start` waits for all `ZeebePartition`s to start. This blocks at least the installation of `AdminApiRequestHandler`

The first one is the crux I think, we don't want to wait for the partition _group_ to start, we just want to wait for each partition individually.

The second one appears to be trivial to solve:

```patch
diff --git a/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java b/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java
--- a/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java	(revision 4fa6c0dc0009f5faedb987b09a055f9135629495)
+++ b/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java	(revision 6a454eedc03e14d4f7fa56e5560c4febfbe57f89)
@@ -127,7 +127,7 @@
 
     return partitionService
         .start()
-        .thenApply(
+        .thenApplyAsync(
             ps -> {
               LOGGER.info("Registering Partition Manager");
 
@@ -158,12 +158,10 @@
                       topologyManager,
                       brokerCfg.getExperimental().getFeatures().toFeatureFlags()));
 
-              final var futures =
-                  partitions.stream()
-                      .map(partition -> CompletableFuture.runAsync(() -> startPartition(partition)))
-                      .toArray(CompletableFuture[]::new);
+              for (final var partition : partitions) {
+                CompletableFuture.runAsync(() -> startPartition(partition));
+              }
 
-              CompletableFuture.allOf(futures).join();
               return null;
             });
   }
```
