### ISSUE TITLE
Add metric in gateway to determine what kind of client send requests

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#5245]
**Description**

We could add a metric in the gateway which counts which client, which version etc has send a requests. This would make it possible, in the cloud, to determine at which version the customers currently are and which client they are using more etc.

**Comment by npepinpe** [comment]
This to me feels more like a product metric that should be in Mixpanel - I can bring it up with Menski or Felix, but I don't think it's particularly useful for us devs. So for now I'll move it to needs product review.

**Comment by Zelldon** [comment]
We have this part of our saas offering and data in mixpanel. I think it would be useful to have this knowledge on support as well, but we can also just ask the customer which client they use. 

The issue here is that having the information as labels will explode the stored data see the warning from prometheus docs

https://prometheus.io/docs/practices/naming/#labels
> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
