### ISSUE TITLE
Test rollback, in case an update introduces new bugs

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#5603]
(e.g. Run upgrade test with reversed versions to test rollba

**Comment by npepinpe** [comment]
Same as #5602, postponed until the new engine is here and we re-enable the update tests.

**Comment by npepinpe** [comment]
AFAIK we don't support rolling back, so I would close this and reopen issues when we do support such a feature. Do object and reopen if I misunderstood the goal here.
