### ISSUE TITLE
Refactor BrokerInfo and TopologyManagerImpl to meet Sonar requirements

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#5640]
**Description**

In #5529 after adding a `partitionHealth`, I've added some tech debt that needs to be fixed.

1. Remove `@SuppressWarnings` that I added in `BrokerInfo` and `TopologyManagerImpl`
2. Refactor these classes to meet Sonar requirements.

For some insights see: https://github.com/zeebe-io/zeebe/pull/5529#issuecomment-709984132

**Comment by npepinpe** [comment]
Closing as we dropped SonarCloud for now. We will have other issues to tackle CodeQL warnings and the likes.
