### ISSUE TITLE
Sonar configuration should meet Zeebe's code style

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#5646]
**Description**

For now, in [Sonar](https://sonarcloud.io/dashboard?branch=develop&id=io.zeebe%3Azeebe-root) there is plenty of different code smells, bugs, security vulnerabilities. Some of them could be resolved by updating Sonar's config that should reflect Zeebe's code style.

**Comment by npepinpe** [comment]
Not a blocker as Sonar analyses mostly new code, but a nice to have :slightly_smiling_face:

**Comment by npepinpe** [comment]
We've dropped SonarCloud
