### ISSUE TITLE
Migrate Atomix to ActorScheduler

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#5652]
## Description

Currently atomix uses own ThreadPools for several things, like RAFT and SWIM. 

### Current Challenges:

 * resource usage (CPU but also Memory) isn't fully under control
   * We have no possibility to configure the thread pools in atomix
   * The job queue of the used scheduler is unbound ( caused issues like https://github.com/zeebe-io/zeebe/issues/4664)
 * hard to test
   * we have no control over the execution nor the time
  * synchronization is not easy - possible race conditions exist
  * different used models make it harder to understand and write code
 * It makes it hard to switch our actor scheduler if we have several approaches

### Proposed Solution:

Replace all used SingleThreadSchedulers and ThreadPools to our own ActorScheduler. 

#### Prerequisite work

First we need to decouple the Atomix starting, and should move that to several starting steps in the Broker. This makes it later easier to inject the scheduler and other necessary dependencies.

#### Migration

After we replaced the bootstrap logic, we can start with migrating each service one by one. It probably makes sense to start with SWIM https://github.com/zeebe-io/zeebe/issues/4829, since it seems to be easier then RAFT. We should try to trim down the work into smaller issues if possible and necessary.

**Comment by Zelldon** [comment]
@npepinpe @oleschoenburg do we want to close this? I guess at the end we still want this but potentially we will migrate to something else

**Comment by oleschoenburg** [comment]
I'm in favor of closing. It's something we won't just forget about, if we have the opportunity to something here, we will.
