### ISSUE TITLE
Use controllable clock in Atomix/Raft

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#5668]
**Description**
PR #5622 added randomized test for raft. However, due to a non-determinism with in raft, it is not easy to reproduce a failed test even if we have reproduce the sequence of operation from the seed. We haven't yet figured out what is causing the non-determinism. But there is a good chance that the reason is the use of `System.currentTimeMillis` with in raft roles to make some decisions. To be able to reproduce failing tests, we should be able to control all aspects of execution. So we should wrap clock usage within raft and also other modules in atomix so that they can be controlled in a test. 

Alternatively, if we move raft executors to `ActorScheduler` #5652 , then we can use `ActorClock`.

**Comment by npepinpe** [comment]
Let's have it along with moving to the ActorScheduler - however, if we find bugs with the randomized tests, and it makes us lose time that they are not easily reproduceable, let's revise this as a more urgent matter.

**Comment by deepthidevaki** [comment]
I will close this for now. We don't see any issues in the randomized test after being able to inject `Random` generator in to the raft context in the tests.
