### ISSUE TITLE
Benchmark startup initialisation logs at Error level 

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#5698]
**Description**

When zeebe pods in our benchmark restart their initialisation logs are logged at ERROR level, while these are not errors. We should change these to INFO level

Example: [Logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22korthout-0-26-0-alpha1%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22korthout-0-26-0-alpha1%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0Aresource.labels.pod_name%3D%22korthout-0-26-0-alpha1-zeebe-1%22%0Aseverity%3DERROR;timeRange=2020-10-27T00:29:40.218Z%2F2020-10-27T00:29:40.218Z--PT1H?authuser=1&project=zeebe-io)

**Comment by npepinpe** [comment]
I assume you mean the shell script stuff - as they don't show up in the error reporting tool, I don't see it as a big impact, but let me know if you think otherwise, happy to review this

**Comment by korthout** [comment]
Agreed, impact is small but it helps to be able to filter logs on level when investigating an issue or error

**Comment by Zelldon** [comment]
Not sure what this refers to. The env vars which are logged? This is done in the helm charts here https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/charts/zeebe/templates/configmap.yaml#L20 but here we have no control over the log level

**Comment by Zelldon** [comment]
It is not in the java process logged. So how would you set the logging level? We would need to log it as JSON so stackdriver can properly parse it, but tbh I see no issue and explicit need currently for this.

Alternatively, we remove the `env` call and print the environments in the broker. In general, i like to see in which environment we are running and what is set. It helped in the past. 

BTW the same applies to the controller https://github.com/camunda-cloud/zeebe-controller-k8s/blob/main/templates/zeebe_configmap.yaml#L28

**Comment by Zelldon** [comment]
I will close this for now. Feel free to reopen it if you see a need for it, or create a PR at the appropriate places, but right now I don't see us working on this.
