### ISSUE TITLE
Add graph to visualize why containers are terminated to Grafana dashboard

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#5710]
**Is your feature request related to a problem? Please describe.**
It's quite frustrating to figure out why a container was terminated after the fact - was it OOM killed (then look into GCP logs), did it complete, was it evicted, etc. It's useful to be able to correlate certain behaviours (i.e. latency spike on eviction) that are expected, and react on events that aren't (e.g. oom killed).

**Describe the solution you'd like**
We can use the `kube_pod_container_status_last_terminated_reason` metric to show the last reason a container was terminated (documented here: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md). At the moment I figured a simple graph that can be filtered by namespace and pod is good enough, but if someone has a better visualization idea I'm happy to hear it.

**Describe alternatives you've considered**
Trawling through the logs after the fact to make sure the pod was not terminated unexpectedly for negative reasons (e.g. OOM).

**Additional context**
Metric docs: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md

**Comment by Zelldon** [comment]
@deepthidevaki added this to the overview dashboard
