### ISSUE TITLE
Deployments are stored in state even when one workflow is rejected

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#5723]
**Describe the bug**

Scenario:

 * Deployment with multiple workflows
 * One of the workflows is broken
 * If you send the deploy command you get an rejection back
 * If you fix the related workflow and deploy it again you can see that the other workflows have an higher version then the fixed one

![deployerror](https://user-images.githubusercontent.com/2758593/97574348-62c4b680-19eb-11eb-9a09-2ad2f8c92634.png)

This means they are stored in the state, even if we reject the deployment. I'm not sure whether this makes really sense. Especially since the deployment is not distributed, this means the succeed workflow's are only existing at partition one and the exporter (+operate and simple monitor) doesn't know about them.
 

**To Reproduce**
See above.

**Expected behavior**
When it is rejected nothing is stored in the state.

**Environment:**
 - OS: k8s
 - Zeebe Version: snapshot
 - Configuration: simple monitor

**Support**
- https://jira.camunda.com/browse/SUPPORT-15590

**Comment by npepinpe** [comment]
Verify as well why the version was incremented when deploying the same processes, which should already be handled.

**Comment by aivinog1** [comment]
@npepinpe Hi! I'm thinking about taking this one to deep dive into the workflow processing (and maybe even Simple monitor :)). What do you think about it? :)

**Comment by npepinpe** [comment]
@saig0 / @korthout Is this still the case post 1.0? I would think possibly not, as we removed the intermediate cache, but I could be wrong, and the version may still be incremented (although that's pretty harmless).

**Comment by korthout** [comment]
Able to reproduce with current develop 535bf40a8. Tested using a broken-process (task with message boundary event without a message defined) and the one_task process (from benchmark project)
```
zbctl deploy broker-process.bpmn one_task.bpmn
Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'/Users/korthout/dev/zeebe-io/examples/broken-process.bpmn': - Element: MessageEventDefinition_0cexyyq
    - ERROR: Must reference a message
- Element: Event_02m9w1r
    - ERROR: Must have at least one outgoing sequence flow
```

This was deploying to my personal Camunda Cloud cluster running 1.1.0. Checked operate and saw that the one_task process was deployed.

Then, fixed the `broken-process.bpmn` file and tried again:
```
zbctl deploy broker-process.bpmn one_task.bpmn
{
  "key": "2251799813802427",
  "processes": [
    {
      "bpmnProcessId": "Process_1dn6fqc",
      "version": 1,
      "processDefinitionKey": "2251799813802426",
      "resourceName": "/Users/korthout/dev/zeebe-io/examples/broken-process.bpmn"
    },
    {
      "bpmnProcessId": "benchmark",
      "version": 1,
      "processDefinitionKey": "2251799813801841",
      "resourceName": "/Users/korthout/dev/zeebe-io/examples/one_task.bpmn"
    }
  ]
}
```

Looks like the one task process does not receive a new version in the accepted deployment

**Comment by saig0** [comment]
Marking priority as `upcoming` because it should be easy to fix with the new engine abstraction.

**Comment by korthout** [comment]
We still see this as `upcoming` but we have no space for it in the next iteration.

**Comment by korthout** [comment]
Link to the support case https://jira.camunda.com/plugins/servlet/samlsso?redirectTo=%2Fbrowse%2FSUPPORT-15590
