### ISSUE TITLE
[Operate] Variable visibility

### ISSUE THREAD

**Issue by cmrenus** [camunda/zeebe#5727]
Currently when looking at operate during workflows, it is tough to visualize the variables at each step unless the input and output is specified (transformations). Since variables are available at each task, I think it would provide more visibility to show all available inputs/outputs at each step regardless of what is passed.
to me it would help in truly seeing what happens at each step. Otherwise when looking at the overall workflow, you just have variables that have come in and out and that doesnt make it easy to see where they came from since you cannot see that anywhere within the pipeline.

**Comment by saig0** [comment]
@cmrenus thank you for raising this up!

I don't understand your requirement completely. Assuming that you have a workflow with 2 service tasks in sequence. 

The workflow instance is created with a variable "x". The first service task has an input mapping that creates a local variable "y". The job is completed with a variable "z". 

When you open the workflow instance in Operate then you see both variables "x" and "z". When you click on the service task then you see the variable "y". 

Please describe your expectations. Adding some screenshots may help.

**Comment by felix-mueller** [comment]
@cmrenus do you have more feedback around this?

**Comment by pihme** [comment]
@menski (with your hat as Operate EM) seems to be more related to Operate than Zeebe

**Comment by menski** [comment]
I will close because of inactivity, and we are aware of the variable visibility topic in the Operate project.
