### ISSUE TITLE
Feel exceptions not cause any incidents

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#5880]
**Describe the bug**
During our hack day we played around with feel expressions and had some issues regarding the right format of a date etc.
The values has always falled back to null and was just logged as warning. But we can't see any problems in operate it just moved on, with a variable which is set to null. For an camunda cloud user this might get quite confusion and hard to find out what is the exact problem.

**To Reproduce**

Example expression which can cause problems:

**First Example**
```
  // =date(releaseDate) - duration(P7D)
```

[Error in stack driver](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2020-11-19T14:01:56.482000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22fe00577d-ac32-4615-a780-090f22281d3f-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22&scrollTimestamp=2020-11-19T13:59:53.162175000Z&pinnedLogId=184pf4hf1c10hi&pinnedLogTimestamp=2020-11-19T13:59:53.162175Z)
```
  // Expand all | Collapse all{
  // insertId: "184pf4hf1c10hi"
  // jsonPayload: {
  //  context: {
  //   actor-name: "Broker-0-StreamProcessor-1"
  //   loggerName: "org.camunda.feel.FeelEngine"
  //   threadId: 28
  //   threadName: "Broker-0-zb-actors-0"
  //   threadPriority: 5
  //  }
  //  logger: "org.camunda.feel.FeelEngine"
  //  message: "Suppressed failure: no variable found for name 'P7D'"
  //  serviceContext: {
  //   service: "zeebe"
  //   version: "0.25.0"
  //  }
  //  thread: "Broker-0-zb-actors-0"
  // }
  // labels: {…}
  // logName: "projects/camunda-cloud-240911/logs/zeebe"
  // receiveTimestamp: "2020-11-19T13:59:55.020230668Z"
  // resource: {…}
  // severity: "WARNING"
  // sourceLocation: {…}
  // timestamp: "2020-11-19T13:59:53.162175Z"
  //}
```

**Second Example**

```
  // date("01-01-1970")
```

```
/// W 2020-11-19T14:03:54.202530Z Failed to parse date from '01-01-1970'
  //  undefined
  //W 2020-11-19T14:03:54.204435Z Suppressed failure: expected Number, Date, Time or Duration but found 'ValNull'
```

**Third Example**

Feel expression as output mapping
```
  // =date(releaseDate) - duration("P7D")
```

```
  // 2020-11-19 15:08:22.891 CET
  //No FEEL to MessagePack transformation for 'ValDate(2020-11-19)'. Using 'null' instead.
```

**Expected behavior**

An incident is created for these kind of failures that the user can fix this.

**Environment:**
 - OS: 0.25.0 production s
 - Zeebe Version: 0.25.0
 - Configuration: cloud

**Comment by npepinpe** [comment]
@saig0 - do you remember why we suppress such failures?

**Comment by saig0** [comment]
Currently, the FEEL engine itself suppresses these kinds of failures (i.e. the first two cases). In the specification, the error handling is described as "you may log the error and continue with a null value". 

I'm aware that this behavior is maybe not always what we want here. We can think of a different mode of the FEEL engine that fails faster or returns any suppressed failures while evaluating. In Zeebe, we may create an incident if there was a failure. But this is a bigger topic.

The third case is a different story. It is just not implemented in Zeebe yet. The solution here would be to return the result as a string.

BTW: reading the documentation would help you in the first place :stuck_out_tongue_closed_eyes:

**Comment by Zelldon** [comment]
> BTW: reading the documentation would help you in the first place 😝

Classic

**Comment by npepinpe** [comment]
I'm changing this to needs stakeholder input, as this is the current implementation - user feedback would be needed to know if it's wrong, and that to me needs a product decision.

**Comment by Zelldon** [comment]
Happened btw in the last Game day https://confluence.camunda.com/display/ZEEBE/Game+Day+16.03.2021
