### ISSUE TITLE
Remove go-bindata after Go1. 16

### ISSUE THREAD

**Issue by MiguelPires** [camunda/zeebe#6034]
**Description**

Go 1.16 will have native support for embedding files so, after updating, we can use that and remove go-bindata as a dependency.
https://tip.golang.org/doc/go1.16

**Comment by Zelldon** [comment]
I think this should be a quick thing to do, we already moved to go 1.17

**Comment by abbasadel** [comment]
We already moved to 1.19 in #12633. Does this issue still make sense?

**Comment by npepinpe** [comment]
Yes :) The idea is to migrate off of using the go-bindata utility and use the built-in compiler capabilities via the `go:embed` annotation. Definitely worth doing to reduce our dependencies on external projects which may eventually prevent us from, say, migrating to another Go version.

**Comment by npepinpe** [comment]
Actually, I might take a crack a it, because I think we can solve this without either go-bindata or go:embed, and just via build flags.
