### ISSUE TITLE
Some Snapshot panels seem to be broken or not working correctly

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#6125]
**Describe the bug**

In the last days I had the feeling that some of the snapshot panels are not working as expected.

For example the snapshot duration shows only from time to time some metrics:

**Snapshot Duration Example 1**
![snapshot-duration](https://user-images.githubusercontent.com/2758593/104888469-11ceb980-596d-11eb-8e28-d6d8293b210e.png)
**Snapshot Duration Example 2**
![snapshot-duration2](https://user-images.githubusercontent.com/2758593/104888467-109d8c80-596d-11eb-929f-b981ad39d54c.png)

Furthermore the snapshot replication metric seem also not work really well.

![snapshot-repl](https://user-images.githubusercontent.com/2758593/104888547-2c089780-596d-11eb-9e96-98b6f330f396.png)

**To Reproduce**
Create a Benchmark and open grafana.

**Expected behavior**

Duration is reported on each snapshot.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.26.0+
 - Configuration: [e.g. exporters etc.]

**Comment by Zelldon** [comment]
Related https://zeebe-io.github.io/zeebe-chaos/chaos_experiment/broker/network/2021/01/19/network-partition.html

In the chaos day I had also the feeling that it is not really clear which panel shows now what, maybe it makes more sense to just merge them into one section and remove some of them.

For example snapshot replication panel in atomix section shows always zero

![atomix-snapshot-metrics](https://user-images.githubusercontent.com/2758593/105135568-8aaa4e80-5af0-11eb-867d-ff06e7426875.png)

**Comment by pihme** [comment]
@Zelldon Can this be closed?

**Comment by Zelldon** [comment]
I guess thanks
