### ISSUE TITLE
Remove unused RaftError's

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#6133]
**Description**

In the atomix last clean up's I was not able to remove RaftError's, because this would be a breaking change. I'm talking about this
https://github.com/zeebe-io/zeebe/blob/develop/atomix/cluster/src/main/java/io/atomix/raft/RaftError.java#L74-L232
Since we now plan with some breaking changes we might consider of doing this as well.

**Comment by npepinpe** [comment]
Remind me why this is a breaking change? Because of Kryo serialization?

**Comment by Zelldon** [comment]
I think so yes

**Comment by npepinpe** [comment]
To be honest I would rather ignore this for now and focus on replacing our transport in the future. wdyt? I don't think it adds a lot of complexity or anything if we leave it for now.

**Comment by Zelldon** [comment]
Fine for me :) just want to make you aware

**Comment by Zelldon** [comment]
As @npepinpe mentioned we might replace the transport entirely so no need to keep this issue open.
