### ISSUE TITLE
Adding arm/multiarch Docker images

### ISSUE THREAD

**Issue by ko1N** [camunda/zeebe#6155]
Since a lot of hardware (even on the cloud) now shifts to the arm architecture it would be great if zeebe would also provide multiarch docker images supporting arm.

This would allow us to run zeebe on arm based servers or even in a small raspberry pi cluster.

**Comment by aivinog1** [comment]
Hey @npepinpe! I've taken a quick look at this and I see that we can build the image for `linux/amd64`, `linux/arm64`, but if we want this we should change CI for a bit. Actually, there is a single command for that: 
```
docker buildx build --no-cache --platform linux/amd64,linux/arm64 --push --build-arg DISTBALL=dist/target/camunda-cloud-zeebe*.tar.gz -t camunda/zeebe:current-test --target app .
```
See [this](https://www.docker.com/blog/multi-arch-images/) and [this](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images) for reference. But as you can see [there](https://github.com/docker/buildx/issues/59) we have to squash build and push stages to one. So, WDYT? Should I create a PR with CI changes? :)

**Comment by ko1N** [comment]
I managed to get zeebe to run on my pi kubernetes cluster as well. Apart from building with buildx the Dockerfile needs to be changed as well:

```
-ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini ${TMP_DIR}/bin/tini
+ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-arm64 ${TMP_DIR}/bin/tini
```

**Comment by npepinpe** [comment]
Two concerns here:

1. How do we ensure we don't break it? Our CI runs on Google Cloud, which afaik has no ARM offering.
2. Offering official ARM images implies that we support them - but as mentioned, we run all our tests on Google Cloud, so we wouldn't really ever test them (without some effort to further develop our testing infrastructure). What's the risk of anything other than the container having issues on ARM and requiring additional tests? Should we run the whole acceptance test suite a second time on ARM? How do we ensure compiled components run well (RocksDB, zbctl, netty-tcnative-boringssl-static)?

**Comment by aivinog1** [comment]
@npepinpe Good points! Actually, you are right about native things (like RocksDB and something like that). So, I see two options here:
1. We should create a separate community project, that supplies multiarch builds. And this project should concern about native things worked as expected but reuse a Zeebe distribution (for example) and that Zeebe is actually working on different architectures (tests included).
2. We add some sort of warning that we build multiarch image but right now we can't guarantee that it works on different than x86 architecture. And we will continue thinking and improving our CI to make it works with different architectures. After decent level support, we will admit that the official image could work on different architectures.
3. It is like both of them. We start a community project after it became robust and decent we will include it as part of the official image. 
WDYT?

**Comment by akkie** [comment]
I am also interested in support for ARM-based platforms. Apple will finish its transition to ARM based CPUs this year. This means that a lot more developer machines will be ARM based. Apple supports currently AMD based emulation on ARM chips. But that's really buggy and doesn't work for each docker image. Docker currently displays a warning when running amd64 based images on Apple Silicon chips: Image may have poor performance, or fail, if run via emulation.

Today, not supporting ARM also means that Zeebe is not available to many developers using Apple Silicon based machines.

**Comment by npepinpe** [comment]
I'll bring it up again to our product meetings. Right now, keep in mind that cross platform compatibility is only for minimal development support - i.e. developers should be able to run Zeebe locally on their machine (but potentially with worse performance or some non critical features disabled depending on your OS). I can see us extending this kind of support for multiple arch, but it's another thing to have complete support for multiple arch (i.e. same features, performance, etc.).

**Comment by akkie** [comment]
@npepinpe Is it possible that you can provide the commands to build Zeebe locally? I currently have problems to get Zeebe running stable on my M1 Mac and I need it asap.

I know how I can build the docker image for ARM. The problem is the zeebe build.

**Comment by akkie** [comment]
For me, running Zeebe in emulation on a M1 Mac doesn't really work. Containers were shutdown by docker or Zeebe crashed. Building it natively on the local machine works now smooth.

Thanks to the hint from @ko1N I was able to run the build locally. I have also used the [arm64v8/eclipse-temurin:17](https://hub.docker.com/r/arm64v8/eclipse-temurin/) image.


Here is my docker file:
```
ARG APP_ENV=prod

# Building builder image
FROM alpine:latest as builder
ARG DISTBALL

ENV TMP_ARCHIVE=/tmp/zeebe.tar.gz \
    TMP_DIR=/tmp/zeebe \
    TINI_VERSION=v0.19.0

COPY ${DISTBALL} ${TMP_ARCHIVE}

RUN mkdir -p ${TMP_DIR} && \
    tar xfvz ${TMP_ARCHIVE} --strip 1 -C ${TMP_DIR} && \
    # already create volume dir to later have correct rights
    mkdir ${TMP_DIR}/data

ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-arm64 ${TMP_DIR}/bin/tini
COPY docker/utils/startup.sh ${TMP_DIR}/bin/startup.sh
RUN chmod +x -R ${TMP_DIR}/bin/
RUN chmod 0775 ${TMP_DIR} ${TMP_DIR}/data

# Building prod image
FROM arm64v8/eclipse-temurin:17 as jre-build

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
   --add-modules ALL-MODULE-PATH \
   --strip-debug \
   --no-man-pages \
   --no-header-files \
   --compress=2 \
   --output jre17-with-all-modules

# Define your base image
FROM ubuntu:focal as prod
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-build /jre17-with-all-modules $JAVA_HOME

# Building dev image
FROM arm64v8/eclipse-temurin:17 as dev
RUN echo "running DEV pre-install commands"
RUN apt-get update
RUN curl -sSL https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.7.1/async-profiler-1.7.1-linux-x64.tar.gz | tar xzv

# Building application image
FROM ${APP_ENV} as app

ENV ZB_HOME=/usr/local/zeebe \
    ZEEBE_BROKER_GATEWAY_NETWORK_HOST=0.0.0.0 \
    ZEEBE_STANDALONE_GATEWAY=false
ENV PATH "${ZB_HOME}/bin:${PATH}"

WORKDIR ${ZB_HOME}
EXPOSE 26500 26501 26502
VOLUME ${ZB_HOME}/data

RUN groupadd -g 1000 zeebe && \
    adduser -u 1000 zeebe --system --ingroup zeebe && \
    chmod g=u /etc/passwd && \
    chown 1000:0 ${ZB_HOME} && \
    chmod 0775 ${ZB_HOME}

COPY --from=builder --chown=1000:0 /tmp/zeebe/bin/startup.sh /usr/local/bin/startup.sh
COPY --from=builder --chown=1000:0 /tmp/zeebe ${ZB_HOME}

ENTRYPOINT ["tini", "--", "/usr/local/bin/startup.sh"]
```

The commands to build the image:

```
 mvn dependency:get -B \
    -DremoteRepositories="camunda-nexus::::https://app.camunda.com/nexus/content/repositories/public" \
    -DgroupId="io.camunda" -DartifactId="camunda-cloud-zeebe" \
    -Dversion="1.3.0" -Dpackaging="tar.gz" -Dtransitive=false

mvn dependency:copy -B \
    -Dartifact="io.camunda:camunda-cloud-zeebe:1.3.0:tar.gz" \
    -DoutputDirectory=./ \
    -Dmdep.stripVersion=true

docker build --no-cache --build-arg DISTBALL=camunda-cloud-zeebe.tar.gz -t zeebe:latest --target app .
```

**Comment by Benjoyo** [comment]
There is a big shift towards ARM and with Apple's lineup completely switched over to M1/ARM there is an increasingly high number of developers using ARM machines who shouldn't have to manually modify and build multiple images to get going with Camunda Cloud. In 2022 multi arch images are a necessity imho.

**Comment by falko** [comment]
See also this branch for how we built images to run on AWS Arm CPUs: https://github.com/camunda-cloud/zeebe/commits/dd-mulit-arch-docker

**Comment by falko** [comment]
@deepthidevaki maybe you have input here based on our Hackdays project?

**Comment by deepthidevaki** [comment]
> @deepthidevaki maybe you have input here based on our Hackdays project?

This is what we changed for multi-arch images https://github.com/camunda-cloud/zeebe/commit/a62503394cf702b24a1fa194fd5332c7689dbe8a . It is not different from what is already discussed here in this issue. 

Building multi-arch image is not difficult. But as @npepinpe said, the question is about how much we can support them officially.

**Comment by Benjoyo** [comment]
> Building multi-arch image is not difficult. But as @npepinpe said, the question is about how much we can support them officially.

I think for the time being support is not necessary. But it would be great if the images existed at all. Not only Zeebe but also Operate and Tasklist.

**Comment by sirmonin** [comment]
Any updates on this?
It quite painful to use Zeebe with M1 in my team.

**Comment by sirmonin** [comment]
I've created a public docker image for arm64. It is built from stable/8.0 branch. It is not by any means production ready, however it helps with local development a lot.
https://hub.docker.com/r/sirmonin/zeebe

**Comment by akkie** [comment]
Google provides now ARM based cloud VMs: https://cloud.google.com/blog/products/compute/tau-t2a-is-first-compute-engine-vm-on-an-arm-chip

**Comment by megglos** [comment]
will be handled with this feature request https://github.com/camunda/zeebe/issues/10986 going forward
