### ISSUE TITLE
No space left on device while receiving snapshot leads to unhealthy followers

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#6232]
**Describe the bug**
The following [error](https://console.cloud.google.com/errors/CKjN-8qmwNKc0wE?service=zeebe&time=P30D&project=camunda-cloud-240911&authuser=1) was reported `IOException: No space left on device`. This has been reported on other versions in the past (see https://github.com/zeebe-io/zeebe/issues/6038), but that problem was already resolved. 

The cluster producing this error was part of the [28-01-2020 game day](https://docs.google.com/document/d/1uX1N2jzvURhd8-L-uu90AqXO6KONRTY5btmdqNjMA3s/edit), for which the customer was triggering https://github.com/zeebe-io/zeebe/issues/6207. This lead to very a large snapshot state (>5GB).

The following morning, the error was reported, due to a short moment of not enough space left on pvc. Disk space recovered quickly, but 2 out of 3 brokers (the followers) have unhealthy partitions, that did not recover from this incident.

**Expected behavior**
Followers should become healthy again after disk space recovered

**Log/Stacktrace**
<details><summary>Logs diskspace</summary>
<p>

[link to logs](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%223ba69e11-1785-4b14-929d-7534736f175a-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22;timeRange=2021-01-29T06:58:54.320Z%2F2021-01-29T08:58:54.320Z?authuser=1&project=camunda-cloud-240911)

```
Error 
2021-01-29 08:28:24.320 CET 
"Unexpected error on writing the received snapshot chunk SnapshotChunkImpl{snapshotId=602799-290-1611905228412-689596-689597, totalCount=671, chunkName='002801.sst', checksum=3874943013, snapshotChecksum=770344077} io.atomix.raft.snapshot.impl.SnapshotChunkImpl@25db7a97"
Debug
2021-01-29 08:28:24.346 CET
"Abort snapshot 602799-290-1611905228412-689596-689597 and mark it as invalid."
Debug
2021-01-29 08:28:24.346 CET
"DELETE dir /usr/local/zeebe/data/raft-partition/partitions/1/pending/602799-290-1611905228412-689596-689597-1"
Info
2021-01-29 08:28:25.236 CET
"Disk space available again. Current available 5464420352 bytes"
Debug
2021-01-29 08:28:25.238 CET
"Broker has disk space available again. All requests with topic subscription will be accepted."
Debug
2021-01-29 08:28:25.238 CET
"Broker has disk space available again. All requests with topic subscription will be accepted."
Debug
2021-01-29 08:28:25.238 CET
"Broker has disk space available again. All requests with topic deployment will be accepted."
```
</p>
</details>

<details><summary>Logs partition health</summary>
<p>

[link to logs](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%223ba69e11-1785-4b14-929d-7534736f175a-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Ahealthy;timeRange=2021-01-29T06:58:54.320Z%2F2021-01-29T08:58:54.320Z?authuser=1&project=camunda-cloud-240911)

```
Error
2021-01-29 08:27:41.572 CET
"ZeebePartition-1 failed, marking it as unhealthy"
Debug
2021-01-29 08:27:41.596 CET
"Detected unhealthy components. The current health status of components: {ZeebePartition-1=UNHEALTHY, Raft-1=HEALTHY}"
Error
2021-01-29 08:27:41.597 CET
"Partition-1 failed, marking it as unhealthy"
Debug
2021-01-29 08:27:41.598 CET
"Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY}"
Debug
2021-01-29 08:27:41.756 CET
"Received metadata change from Broker 2, partitions {1=FOLLOWER}, terms {} and health {1=UNHEALTHY}."
```

</p>
</details>

<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.IOException: No space left on device
at sun.nio.ch.FileDispatcherImpl.write0 (Native Method)
at sun.nio.ch.FileDispatcherImpl.write (Unknown Source)
at sun.nio.ch.IOUtil.writeFromNativeBuffer (Unknown Source)
at sun.nio.ch.IOUtil.write (Unknown Source)
at sun.nio.ch.FileChannelImpl.write (Unknown Source)
at java.nio.channels.Channels.writeFullyImpl (Unknown Source)
at java.nio.channels.Channels.writeFully (Unknown Source)
at java.nio.channels.Channels$1.write (Unknown Source)
at java.nio.file.Files.write (Unknown Source)
at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.writeReceivedSnapshotChunk (FileBasedReceivedSnapshot.java:175)
at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.apply (FileBasedReceivedSnapshot.java:132)
at io.zeebe.broker.system.partitions.impl.StateControllerImpl$ReplicationContext.apply (StateControllerImpl.java:343)
at io.zeebe.broker.system.partitions.impl.StateControllerImpl.consumeSnapshotChunk (StateControllerImpl.java:226)
at io.zeebe.broker.system.partitions.impl.StateReplication.lambda$consume$1 (StateReplication.java:70)
at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept (DefaultClusterCommunicationService.java:308)
at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept (DefaultClusterCommunicationService.java:297)
at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$3 (NettyMessagingService.java:186)
at java.util.concurrent.ThreadPoolExecutor.runWorker (Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (Unknown Source)
at java.lang.Thread.run (Unknown Source)
```

</p>
</details>

**Environment:**
 - Env: Camunda Cloud Int
 - Zeebe Version: 0.26.0

Relates to https://jira.camunda.com/browse/SUPPORT-17326

**Comment by korthout** [comment]
I gave this `Severity: Mid` because it affects system recovery and availability.

**Comment by Zelldon** [comment]
related to https://github.com/zeebe-io/zeebe/issues/6230

**Comment by npepinpe** [comment]
Please verify if this affects only followers, but the expected behaviour is once we have enough disk space again, normal operation should resume.

**Comment by Zelldon** [comment]
@npepinpe this seems to be not planned nor it is part of the Zeebe Project board?

It was seen again as part of the chaos day we did yesterday. See here https://zeebe-io.github.io/zeebe-chaos/chaos_experiment/broker/disk/2021/06/08/Full-Disk.html#general-metric-section

**Comment by npepinpe** [comment]
I wonder if this isn't related to https://github.com/camunda/zeebe/issues/5280 - in SaaS, even with dynamic resizing, the thresholds are calculated once at startup, so even if you have more disk space eventually Zeebe will still think it has too little.

**Comment by Zelldon** [comment]
This week I had a medic benchmark which went out of disk space, because elastic curator was not well configured for the new disk sizes. After fixing this brokers recovered performed better then before but the healthy status never went back.

![overview](https://user-images.githubusercontent.com/2758593/209908502-edf9d404-dcd7-43c8-8c2a-dbc720e163a0.png)
![overview-brokers](https://user-images.githubusercontent.com/2758593/209908504-5d56ee3e-530b-4952-8f2b-e9013004d6af.png)


We should take a look at this.

**Comment by megglos** [comment]
planning: might be an easy fix, let's time-box this to 2h for investigation

**Comment by deepthidevaki** [comment]
Related to https://jira.camunda.com/browse/SUPPORT-17326

**Comment by megglos** [comment]
Planning:
- this is noise/confusion for the user, the partition is actually healthy
- functional wise every thing is fine
- might be a low hanging fruit
- customers rely on the cluster health indicator to be correct for operations
- @Zelldon could you take a look this iteration already so we could deliver it with the July patch still?
