### ISSUE TITLE
On start-up leaders should be balanced evenly between brokers

### ISSUE THREAD

**Issue by menski** [camunda/zeebe#6265]
**Is your feature request related to a problem? Please describe.**

If a new Zeebe cluster is started there is a probability that leaders are unevenly distributed in the cluster. 

**Describe the solution you'd like**

After a cluster was started leaders are evenly distributed in most of the cases.

**Describe alternatives you've considered**

- Restarting the cluster/brokers until leadership is evenly distributed
- Adding an API to force a leader election for partition to manually influence the leader distribution

**Additional context**

I don't assume we can guarantee the leadership balancing 100%, but an best effort approach would already improve the situation.

**Comment by Zelldon** [comment]
As I mentioned already to @npepinpe and @deepthidevaki I think this is possible via sending polls on start up. Similar to what we had before, but previous we went immediately to candidate which caused some issues. But I think if a node starts and and knows for what partition it should be leader it can send polls, which means it ask whether there is a leader. If there is a leader it is fine, if not it becomes candidate. 

**Example** 
```
Distribution:
P\N|	N 0|	N 1|	N 2
P 1|	L  |	F  |	F  
P 2|	F  |	L  |	F  
P 3|	F  |	F  |	L  
```

Broker 0 will send a poll on bootstrap for partition one. Broker 1 will send poll for partition 2 etc.

**Comment by falko** [comment]
Will this also work when individual brokers get restarted or only at the first start of a cluster? Or does one have to restart the entire cluster to rebalance?

**Comment by npepinpe** [comment]
You would have to restart the whole cluster. You wouldn't it to work when restarting a single broker, since it would cause unnecessary failover, leading to small windows of unavailability (at least until we have a super amazing fast, constant time failover :smile:).

**Comment by menski** [comment]
@falko the first goal would not be to have a constant rebalancing, as this is more complex and also has downsides to interrupt an healthy cluster to balance leaders, especially as long as we don't have processing on followers to reduce the failover time

**Comment by deepthidevaki** [comment]
> But I think if a node starts and and knows for what partition it should be leader it can send polls, which means it ask whether there is a leader. If there is a leader it is fine, if not it becomes candidate.

This would work only if all nodes were started at the same time, right? If a node starts a few seconds late, there will be a leader already.

**Comment by Zelldon** [comment]
Since we have the priority election I guess we can close this @deepthidevaki ?

**Comment by deepthidevaki** [comment]
> Since we have the priority election I guess we can close this @deepthidevaki ?

I would vote for closing it. We cannot guarantee even leader distribution at startup. But priority election + api to trigger manual leader balance will more or less achieve this.
