### ISSUE TITLE
Reduce test pipeline time

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#6477]
**Description**

I have the feeling that our pipeline takes to long and it seems to be increasing over time. 

![build](https://user-images.githubusercontent.com/2758593/109767455-df64dd00-7bf7-11eb-9ba0-863808a28e33.png)

If we take a look at the avg. it is around 29 min. If we add QA then it is even more. I would like to see us in improving the pipeline again that we get faster feedback from the pipeline.

Currently it takes quite long until something is merged (PR) or that I see that my branch is healthy and I can open the PR or something else. Would be awesome if we can improve here.

**Comment by npepinpe** [comment]
We can try increasing the parallelism, but I'm not super confident this will help. I would propose to look at the end of the quarter into what are the slowest tests and see if we have any low hanging fruits.

**Comment by pihme** [comment]
@Zelldon Could this maybe be closed after the changes related to GHA?

**Comment by Zelldon** [comment]
Souds good :+1:
