### ISSUE TITLE
Restore/Rework old stream processor tests

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#6712]
**Description**

On migrating the start event processors we deleted some of the old StreamProcessor unit tests, which are quite fragile to stream processing changes. They used the stream processor rule instead of the engine rule and were hard to maintain.

After discussion with @npepinpe and @saig0 we decided to delete/ignore them for now and restore them later after we are done with the migration. We then can rewrite them with engine rule most properly.

Related/deleted classes:

https://github.com/camunda-cloud/zeebe/blob/74c07cb83ff49b4acd96c2cf2e915ffada297af0/engine/src/test/java/io/zeebe/engine/processing/bpmn/ProcessInstanceStreamProcessorTest.java

<details>
<summary>ProcessInstanceStreamProcessorTest.java</summary>
<pre>
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.1. You may not use this file
 * except in compliance with the Zeebe Community License 1.1.
 */
package io.zeebe.engine.processing.bpmn;

import static io.zeebe.protocol.Protocol.START_PARTITION_ID;
import static io.zeebe.test.util.MsgPackUtil.asMsgPack;
import static io.zeebe.test.util.TestUtil.waitUntil;
import static io.zeebe.util.buffer.BufferUtil.wrapString;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.timeout;
import static org.mockito.Mockito.verify;

import io.zeebe.engine.processing.message.MessageObserver;
import io.zeebe.engine.util.StreamProcessorRule;
import io.zeebe.model.bpmn.Bpmn;
import io.zeebe.model.bpmn.BpmnModelInstance;
import io.zeebe.protocol.impl.record.value.job.JobRecord;
import io.zeebe.protocol.impl.record.value.message.ProcessMessageSubscriptionRecord;
import io.zeebe.protocol.impl.record.value.processinstance.ProcessInstanceRecord;
import io.zeebe.protocol.impl.record.value.timer.TimerRecord;
import io.zeebe.protocol.record.Assertions;
import io.zeebe.protocol.record.Record;
import io.zeebe.protocol.record.RecordType;
import io.zeebe.protocol.record.RejectionType;
import io.zeebe.protocol.record.intent.JobIntent;
import io.zeebe.protocol.record.intent.ProcessInstanceIntent;
import io.zeebe.protocol.record.intent.ProcessMessageSubscriptionIntent;
import io.zeebe.protocol.record.intent.TimerIntent;
import io.zeebe.util.buffer.BufferUtil;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import org.agrona.DirectBuffer;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.RuleChain;
import org.junit.rules.Timeout;
import org.mockito.ArgumentCaptor;

public final class ProcessInstanceStreamProcessorTest {

  private static final String PROCESS_ID = "process";
  private static final BpmnModelInstance SERVICE_TASK_PROCESS =
      Bpmn.createExecutableProcess(PROCESS_ID)
          .startEvent("start")
          .sequenceFlowId("flow1")
          .serviceTask("task", b -> b.zeebeJobType("taskType"))
          .sequenceFlowId("flow2")
          .endEvent("end")
          .done();
  private static final BpmnModelInstance SUB_PROCESS_PROCESS =
      Bpmn.createExecutableProcess(PROCESS_ID)
          .startEvent()
          .subProcess("subProcess")
          .embeddedSubProcess()
          .startEvent()
          .serviceTask("task", b -> b.zeebeJobType("taskType"))
          .endEvent()
          .subProcessDone()
          .endEvent()
          .done();
  private static final BpmnModelInstance MESSAGE_CATCH_EVENT_PROCESS =
      Bpmn.createExecutableProcess(PROCESS_ID)
          .startEvent()
          .intermediateCatchEvent(
              "catch-event",
              c ->
                  c.message(m -> m.name("order canceled").zeebeCorrelationKeyExpression("orderId")))
          .done();
  private static final BpmnModelInstance TIMER_BOUNDARY_EVENT_PROCESS =
      Bpmn.createExecutableProcess(PROCESS_ID)
          .startEvent()
          .serviceTask("task1", b -> b.zeebeJobType("type"))
          .boundaryEvent("timer1")
          .cancelActivity(true)
          .timerWithDuration("PT1S")
          .endEvent("timer1End")
          .moveToActivity("task1")
          .endEvent("end")
          .done();
  @Rule public Timeout timeoutRule = new Timeout(2, TimeUnit.MINUTES);
  private final StreamProcessorRule envRule = new StreamProcessorRule();
  private final ProcessInstanceStreamProcessorRule streamProcessorRule =
      new ProcessInstanceStreamProcessorRule(envRule);
  @Rule public RuleChain chain = RuleChain.outerRule(envRule).around(streamProcessorRule);

  @Test
  public void shouldRejectCancellationInDirectSuccession() {
    // given
    streamProcessorRule.deploy(SERVICE_TASK_PROCESS);

    final Record<ProcessInstanceRecord> createdEvent =
        streamProcessorRule.createAndReceiveProcessInstance(r -> r.setBpmnProcessId(PROCESS_ID));
    waitUntil(() -> envRule.events().onlyJobRecords().withIntent(JobIntent.CREATE).exists());

    // when
    envRule.writeCommand(
        createdEvent.getKey(), ProcessInstanceIntent.CANCEL, createdEvent.getValue());
    envRule.writeCommand(
        createdEvent.getKey(), ProcessInstanceIntent.CANCEL, createdEvent.getValue());

    // then
    streamProcessorRule.awaitElementInState("process", ProcessInstanceIntent.ELEMENT_TERMINATED);

    final List<ProcessInstanceIntent> processInstanceLifecycle =
        envRule.events().onlyStatesOf("process").collect(Collectors.toList());

    LifecycleAssert.assertThat(processInstanceLifecycle).compliesWithCompleteLifecycle();

    final Record<ProcessInstanceRecord> rejection =
        envRule.events().onlyProcessInstanceRecords().onlyRejections().findFirst().get();

    Assertions.assertThat(rejection)
        .hasIntent(ProcessInstanceIntent.CANCEL)
        .hasRejectionReason(
            "Expected to cancel a process instance with key '"
                + createdEvent.getKey()
                + "', but no such process was found");
  }

  @Test
  public void shouldCancelActivityInStateReady() {
    // given
    streamProcessorRule.deploy(SERVICE_TASK_PROCESS);

    final Record<ProcessInstanceRecord> createdEvent =
        streamProcessorRule.createAndReceiveProcessInstance(r -> r.setBpmnProcessId(PROCESS_ID));
    waitUntil(
        () ->
            envRule
                .events()
                .onlyProcessInstanceRecords()
                .withIntent(ProcessInstanceIntent.ELEMENT_COMPLETED)
                .filter(
                    w -> w.getValue().getElementIdBuffer().equals(BufferUtil.wrapString("start")))
                .exists());

    // when
    envRule.writeCommand(
        createdEvent.getKey(), ProcessInstanceIntent.CANCEL, createdEvent.getValue());

    // then
    streamProcessorRule.awaitElementInState(PROCESS_ID, ProcessInstanceIntent.ELEMENT_TERMINATED);

    final List<Record<ProcessInstanceRecord>> records =
        envRule.events().onlyProcessInstanceRecords().collect(Collectors.toList());

    final List<ProcessInstanceIntent> processInstanceLifecycle =
        envRule.events().onlyStatesOf("process").collect(Collectors.toList());

    final List<ProcessInstanceIntent> taskLifecycle =
        envRule.events().onlyStatesOf("task").collect(Collectors.toList());

    LifecycleAssert.assertThat(processInstanceLifecycle)
        .compliesWithCompleteLifecycle()
        .endsWith(ProcessInstanceIntent.ELEMENT_TERMINATED);
    LifecycleAssert.assertThat(taskLifecycle).compliesWithCompleteLifecycle();

    ProcessInstanceAssert.assertThat(records).doesNotEvaluateFlowAfterTerminatingElement("process");
  }

  @Test
  public void shouldCancelAndCompleteJobConcurrentlyIbProcess() {
    // given
    streamProcessorRule.deploy(SUB_PROCESS_PROCESS);
    final Record<ProcessInstanceRecord> createdEvent =
        streamProcessorRule.createAndReceiveProcessInstance(r -> r.setBpmnProcessId(PROCESS_ID));
    waitUntil(() -> envRule.events().onlyJobRecords().withIntent(JobIntent.CREATE).exists());

    // when
    envRule.writeCommand(
        createdEvent.getKey(), ProcessInstanceIntent.CANCEL, createdEvent.getValue());
    streamProcessorRule.completeFirstJob();

    // then
    streamProcessorRule.awaitElementInState("process", ProcessInstanceIntent.ELEMENT_TERMINATED);

    final List<ProcessInstanceIntent> processInstanceLifecycle =
        envRule.events().onlyStatesOf("process").collect(Collectors.toList());
    final List<ProcessInstanceIntent> subProcessLifecycle =
        envRule.events().onlyStatesOf("subProcess").collect(Collectors.toList());
    final List<ProcessInstanceIntent> taskLifecycle =
        envRule.events().onlyStatesOf("task").collect(Collectors.toList());

    LifecycleAssert.assertThat(processInstanceLifecycle)
        .compliesWithCompleteLifecycle()
        .endsWith(ProcessInstanceIntent.ELEMENT_TERMINATED);

    LifecycleAssert.assertThat(subProcessLifecycle).compliesWithCompleteLifecycle();

    LifecycleAssert.assertThat(taskLifecycle).compliesWithCompleteLifecycle();
  }

  @Test
  public void shouldRetryToOpenMessageSubscription() {
    // given
    streamProcessorRule.deploy(MESSAGE_CATCH_EVENT_PROCESS);
    streamProcessorRule.createProcessInstance(
        r -> r.setBpmnProcessId(PROCESS_ID).setVariables(asMsgPack("orderId", "order-123")));

    final Record<ProcessInstanceRecord> catchEvent =
        streamProcessorRule.awaitElementInState(
            "catch-event", ProcessInstanceIntent.ELEMENT_ACTIVATED);

    // when
    envRule
        .getClock()
        .addTime(
            MessageObserver.SUBSCRIPTION_CHECK_INTERVAL.plus(MessageObserver.SUBSCRIPTION_TIMEOUT));

    // then
    verify(streamProcessorRule.getMockSubscriptionCommandSender(), timeout(5_000).times(2))
        .openMessageSubscription(
            START_PARTITION_ID,
            catchEvent.getValue().getProcessInstanceKey(),
            catchEvent.getKey(),
            catchEvent.getValue().getBpmnProcessIdBuffer(),
            wrapString("order canceled"),
            wrapString("order-123"),
            true);
  }

  @Test
  public void shouldRejectDuplicatedOpenProcessMessageSubscription() {
    // given
    streamProcessorRule.deploy(MESSAGE_CATCH_EVENT_PROCESS);
    streamProcessorRule.createProcessInstance(
        r -> r.setBpmnProcessId(PROCESS_ID).setVariables(asMsgPack("orderId", "order-123")));

    final Record<ProcessInstanceRecord> catchEvent =
        streamProcessorRule.awaitElementInState(
            "catch-event", ProcessInstanceIntent.ELEMENT_ACTIVATED);

    // when
    final ProcessMessageSubscriptionRecord subscription = subscriptionRecordForEvent(catchEvent);

    envRule.writeCommand(ProcessMessageSubscriptionIntent.CREATE, subscription);
    envRule.writeCommand(ProcessMessageSubscriptionIntent.CREATE, subscription);

    // then
    final Record<ProcessMessageSubscriptionRecord> rejection =
        streamProcessorRule.awaitAndGetFirstSubscriptionRejection();

    assertThat(rejection.getIntent()).isEqualTo(ProcessMessageSubscriptionIntent.CREATE);
    assertThat(rejection.getRejectionType()).isEqualTo(RejectionType.INVALID_STATE);
  }

  @Test
  public void shouldRejectDuplicatedCorrelateProcessMessageSubscription() {
    // given
    streamProcessorRule.deploy(MESSAGE_CATCH_EVENT_PROCESS);

    streamProcessorRule.createProcessInstance(
        r -> r.setBpmnProcessId(PROCESS_ID).setVariables(asMsgPack("orderId", "order-123")));

    final Record<ProcessInstanceRecord> catchEvent =
        streamProcessorRule.awaitElementInState(
            "catch-event", ProcessInstanceIntent.ELEMENT_ACTIVATED);

    final ProcessMessageSubscriptionRecord subscription = subscriptionRecordForEvent(catchEvent);
    envRule.writeCommand(ProcessMessageSubscriptionIntent.CREATE, subscription);
    waitUntil(
        () ->
            envRule
                .events()
                .onlyProcessMessageSubscriptionRecords()
                .withIntent(ProcessMessageSubscriptionIntent.CREATED)
                .exists());

    // when
    envRule.writeCommand(ProcessMessageSubscriptionIntent.CORRELATE, subscription);
    envRule.writeCommand(ProcessMessageSubscriptionIntent.CORRELATE, subscription);

    // then
    final Record<ProcessMessageSubscriptionRecord> rejection =
        streamProcessorRule.awaitAndGetFirstSubscriptionRejection();

    assertThat(rejection.getIntent()).isEqualTo(ProcessMessageSubscriptionIntent.CORRELATE);
    assertThat(rejection.getRejectionType()).isEqualTo(RejectionType.NOT_FOUND);

    final ArgumentCaptor<DirectBuffer> captor = ArgumentCaptor.forClass(DirectBuffer.class);

    verify(streamProcessorRule.getMockSubscriptionCommandSender(), timeout(5_000))
        .correlateMessageSubscription(
            eq(subscription.getSubscriptionPartitionId()),
            eq(subscription.getProcessInstanceKey()),
            eq(subscription.getElementInstanceKey()),
            eq(subscription.getBpmnProcessIdBuffer()),
            captor.capture());
    BufferUtil.equals(captor.getValue(), subscription.getMessageNameBuffer());

    verify(streamProcessorRule.getMockSubscriptionCommandSender(), timeout(5_000))
        .rejectCorrelateMessageSubscription(
            eq(subscription.getProcessInstanceKey()),
            eq(subscription.getBpmnProcessIdBuffer()),
            eq(subscription.getMessageKey()),
            captor.capture(),
            any());

    BufferUtil.equals(captor.getValue(), subscription.getMessageNameBuffer());
  }

  @Test
  public void shouldRejectCorrelateProcessMessageSubscription() {
    // given
    streamProcessorRule.deploy(MESSAGE_CATCH_EVENT_PROCESS);

    final Record<ProcessInstanceRecord> createdEvent =
        streamProcessorRule.createAndReceiveProcessInstance(
            r -> r.setBpmnProcessId(PROCESS_ID).setVariables(asMsgPack("orderId", "order-123")));

    final Record<ProcessInstanceRecord> catchEvent =
        streamProcessorRule.awaitElementInState(
            "catch-event", ProcessInstanceIntent.ELEMENT_ACTIVATED);

    final ProcessMessageSubscriptionRecord subscription = subscriptionRecordForEvent(catchEvent);
    envRule.writeCommand(ProcessMessageSubscriptionIntent.CREATE, subscription);

    waitUntil(
        () ->
            envRule
                .events()
                .onlyProcessMessageSubscriptionRecords()
                .withIntent(ProcessMessageSubscriptionIntent.CREATED)
                .exists());

    envRule.writeCommand(
        createdEvent.getKey(), ProcessInstanceIntent.CANCEL, catchEvent.getValue());
    streamProcessorRule.awaitElementInState(PROCESS_ID, ProcessInstanceIntent.ELEMENT_TERMINATED);

    // when
    envRule.writeCommand(ProcessMessageSubscriptionIntent.CORRELATE, subscription);

    // then
    final Record<ProcessMessageSubscriptionRecord> rejection =
        streamProcessorRule.awaitAndGetFirstSubscriptionRejection();

    assertThat(rejection.getIntent()).isEqualTo(ProcessMessageSubscriptionIntent.CORRELATE);
    // since we mock the message partition, we never get the acknowledged CLOSE command, so our
    // subscription remains in closing state
    assertThat(rejection.getRejectionType()).isEqualTo(RejectionType.INVALID_STATE);
  }

  @Test
  public void shouldRetryToCloseMessageSubscription() {
    // given
    streamProcessorRule.deploy(MESSAGE_CATCH_EVENT_PROCESS);

    final Record<ProcessInstanceRecord> createdEvent =
        streamProcessorRule.createAndReceiveProcessInstance(
            r -> r.setBpmnProcessId(PROCESS_ID).setVariables(asMsgPack("orderId", "order-123")));

    final Record<ProcessInstanceRecord> catchEvent =
        streamProcessorRule.awaitElementInState(
            "catch-event", ProcessInstanceIntent.ELEMENT_ACTIVATED);

    final ProcessMessageSubscriptionRecord subscription = subscriptionRecordForEvent(catchEvent);

    envRule.writeCommand(
        createdEvent.getKey(), ProcessInstanceIntent.CANCEL, catchEvent.getValue());

    streamProcessorRule.awaitElementInState(PROCESS_ID, ProcessInstanceIntent.ELEMENT_TERMINATED);

    // when
    envRule
        .getClock()
        .addTime(
            MessageObserver.SUBSCRIPTION_CHECK_INTERVAL.plus(MessageObserver.SUBSCRIPTION_TIMEOUT));

    // then
    verify(streamProcessorRule.getMockSubscriptionCommandSender(), timeout(5_000).times(2))
        .closeMessageSubscription(
            subscription.getSubscriptionPartitionId(),
            subscription.getProcessInstanceKey(),
            subscription.getElementInstanceKey(),
            subscription.getMessageNameBuffer());
  }

  @Test
  public void shouldRejectDuplicatedCloseProcessMessageSubscription() {
    // given
    streamProcessorRule.deploy(MESSAGE_CATCH_EVENT_PROCESS);
    streamProcessorRule.createProcessInstance(
        r -> r.setBpmnProcessId(PROCESS_ID).setVariables(asMsgPack("orderId", "order-123")));

    final Record<ProcessInstanceRecord> catchEvent =
        streamProcessorRule.awaitElementInState(
            "catch-event", ProcessInstanceIntent.ELEMENT_ACTIVATED);

    final ProcessMessageSubscriptionRecord subscription = subscriptionRecordForEvent(catchEvent);
    envRule.writeCommand(ProcessMessageSubscriptionIntent.CREATE, subscription);

    waitUntil(
        () ->
            envRule
                .events()
                .onlyProcessMessageSubscriptionRecords()
                .withIntent(ProcessMessageSubscriptionIntent.CREATED)
                .exists());

    // when
    envRule.writeCommand(ProcessMessageSubscriptionIntent.DELETE, subscription);
    envRule.writeCommand(ProcessMessageSubscriptionIntent.DELETE, subscription);

    // then
    final Record<ProcessMessageSubscriptionRecord> rejection =
        streamProcessorRule.awaitAndGetFirstSubscriptionRejection();

    assertThat(rejection.getIntent()).isEqualTo(ProcessMessageSubscriptionIntent.DELETE);
    assertThat(rejection.getRejectionType()).isEqualTo(RejectionType.NOT_FOUND);
  }

  @Test
  public void shouldNotTriggerBoundaryEventIfTaskIsCompleted() {
    // given
    streamProcessorRule.deploy(TIMER_BOUNDARY_EVENT_PROCESS);
    streamProcessorRule.createProcessInstance(r -> r.setBpmnProcessId(PROCESS_ID));

    // when
    final Record<TimerRecord> timerRecord =
        streamProcessorRule.awaitTimerInState("timer1", TimerIntent.CREATED);
    final Record<JobRecord> jobRecord =
        streamProcessorRule.awaitJobInState("task1", JobIntent.CREATED);

    envRule.writeCommand(jobRecord.getKey(), JobIntent.COMPLETE, jobRecord.getValue());
    envRule.writeCommand(timerRecord.getKey(), TimerIntent.TRIGGER, timerRecord.getValue());
    streamProcessorRule.awaitElementInState(PROCESS_ID, ProcessInstanceIntent.ELEMENT_COMPLETED);

    // then
    assertThat(envRule.events().onlyTimerRecords().collect(Collectors.toList()))
        .extracting(r -> tuple(r.getRecordType(), r.getIntent()))
        .containsSubsequence(
            tuple(RecordType.COMMAND, TimerIntent.CREATE),
            tuple(RecordType.EVENT, TimerIntent.CREATED),
            tuple(RecordType.COMMAND, TimerIntent.TRIGGER),
            tuple(RecordType.COMMAND_REJECTION, TimerIntent.TRIGGER));
    // ensures timer1 node never exists as far as execution goes
    assertThat(
            envRule.events().onlyProcessInstanceRecords().onlyEvents().collect(Collectors.toList()))
        .noneMatch(r -> r.getValue().getElementIdBuffer().equals(wrapString("timer1")));
  }

  @Test
  public void shouldIgnoreSecondConsecutiveBoundaryEventTrigger() {
    // given
    final BpmnModelInstance process =
        Bpmn.createExecutableProcess(PROCESS_ID)
            .startEvent()
            .serviceTask("task", b -> b.zeebeJobType("type"))
            .boundaryEvent("timer1")
            .timerWithDuration("PT1S")
            .endEvent("timer1End")
            .moveToActivity("task")
            .boundaryEvent("timer2")
            .timerWithDuration("PT2S")
            .endEvent("timer2End")
            .done();

    streamProcessorRule.deploy(process);
    streamProcessorRule.createProcessInstance(r -> r.setBpmnProcessId(PROCESS_ID));

    // when
    final Record<TimerRecord> timer1Record =
        streamProcessorRule.awaitTimerInState("timer1", TimerIntent.CREATED);
    final Record<TimerRecord> timer2Record =
        streamProcessorRule.awaitTimerInState("timer2", TimerIntent.CREATED);

    envRule.writeCommand(timer1Record.getKey(), TimerIntent.TRIGGER, timer1Record.getValue());
    envRule.writeCommand(timer2Record.getKey(), TimerIntent.TRIGGER, timer2Record.getValue());
    streamProcessorRule.awaitElementInState(PROCESS_ID, ProcessInstanceIntent.ELEMENT_COMPLETED);

    // then
    assertThat(
            envRule
                .events()
                .onlyProcessInstanceRecords()
                .skipUntil(r -> r.getValue().getElementIdBuffer().equals(wrapString("task")))
                .withIntent(ProcessInstanceIntent.ELEMENT_COMPLETING)
                .map(Record::getValue)
                .map(ProcessInstanceRecord::getElementIdBuffer)
                .map(BufferUtil::bufferAsString))
        .containsExactly("timer1", "timer1End", "process");
  }

  private ProcessMessageSubscriptionRecord subscriptionRecordForEvent(
      final Record<ProcessInstanceRecord> catchEvent) {
    return new ProcessMessageSubscriptionRecord()
        .setSubscriptionPartitionId(START_PARTITION_ID)
        .setProcessInstanceKey(catchEvent.getValue().getProcessInstanceKey())
        .setElementInstanceKey(catchEvent.getKey())
        .setMessageKey(3L)
        .setMessageName(wrapString("order canceled"));
  }
}
</pre>
</details>

https://github.com/camunda-cloud/zeebe/blob/74c07cb83ff49b4acd96c2cf2e915ffada297af0/engine/src/test/java/io/zeebe/engine/processing/bpmn/ParallelGatewayStreamProcessorTest.java

<details>
<summary>ParallelGatewayStreamProcessorTest.java</summary>
<pre>
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.1. You may not use this file
 * except in compliance with the Zeebe Community License 1.1.
 */
package io.zeebe.engine.processing.bpmn;

import io.zeebe.engine.util.StreamProcessorRule;
import io.zeebe.model.bpmn.Bpmn;
import io.zeebe.model.bpmn.BpmnModelInstance;
import io.zeebe.model.bpmn.instance.ExclusiveGateway;
import io.zeebe.model.bpmn.instance.ParallelGateway;
import io.zeebe.model.bpmn.instance.Process;
import io.zeebe.model.bpmn.instance.SequenceFlow;
import io.zeebe.protocol.impl.record.value.processinstance.ProcessInstanceRecord;
import io.zeebe.protocol.record.Record;
import io.zeebe.protocol.record.intent.ProcessInstanceIntent;
import io.zeebe.util.buffer.BufferUtil;
import java.util.Optional;
import org.agrona.DirectBuffer;
import org.assertj.core.api.Assertions;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.RuleChain;

public final class ParallelGatewayStreamProcessorTest {

  public static final String PROCESS_ID = "process";
  public static final DirectBuffer PROCESS_ID_BUFFER = BufferUtil.wrapString("process");

  public final StreamProcessorRule envRule = new StreamProcessorRule();
  public final ProcessInstanceStreamProcessorRule streamProcessorRule =
      new ProcessInstanceStreamProcessorRule(envRule);

  @Rule public RuleChain chain = RuleChain.outerRule(envRule).around(streamProcessorRule);

  @Test
  public void shouldNotCompleteScopeWhenATokenWaitsAtAGateway() {
    // given
    final BpmnModelInstance process =
        Bpmn.createExecutableProcess(PROCESS_ID)
            .startEvent()
            .parallelGateway("fork")
            .sequenceFlowId("flowToJoin")
            .parallelGateway("join") // process should deadlock here
            .endEvent()
            .moveToNode("fork")
            .serviceTask("waitState", b -> b.zeebeJobType("type"))
            .sequenceFlowId("flowToEnd")
            .endEvent()
            .done();

    final ExclusiveGateway deadBranch = process.newInstance(ExclusiveGateway.class);
    final ParallelGateway join = process.getModelElementById("join");
    final SequenceFlow connectingFlow = process.newInstance(SequenceFlow.class);

    final Process processElement = process.getModelElementsByType(Process.class).iterator().next();
    processElement.addChildElement(deadBranch);
    processElement.addChildElement(connectingFlow);

    connectingFlow.setSource(deadBranch);
    deadBranch.getOutgoing().add(connectingFlow);
    connectingFlow.setTarget(join);
    join.getIncoming().add(connectingFlow);

    streamProcessorRule.deploy(process);

    streamProcessorRule.createProcessInstance(r -> r.setBpmnProcessId(PROCESS_ID));
    streamProcessorRule.awaitElementInState(
        "flowToJoin", ProcessInstanceIntent.SEQUENCE_FLOW_TAKEN);

    // when
    // waiting until the end event has been reached
    streamProcessorRule.completeFirstJob();

    // then
    // there should be no scope completing event
    final Optional<Record<ProcessInstanceRecord>> processCompleting =
        envRule
            .events()
            .onlyProcessInstanceRecords()
            .withIntent(ProcessInstanceIntent.ELEMENT_COMPLETING)
            .filter(r -> PROCESS_ID_BUFFER.equals(r.getValue().getElementIdBuffer()))
            .findFirst();

    Assertions.assertThat(processCompleting).isNotPresent();
  }
}
</pre>
</details>

**Comment by Zelldon** [comment]
@saig0 can your team verify whether this is still necessary if not close it?

I can see that the last test `shouldNotCompleteScopeWhenATokenWaitsAtAGateway` is for example not tested.

But some are like:

```
shouldRejectCancellationInDirectSuccession   -> ProcessInstanceCommandRejectionTest#shouldRejectTerminateIfElementIsTerminating

shouldCancelActivityInStateReady -> CancelProcessInstanceTest#shouldCancelProcessInstance

shouldCancelAndCompleteJobConcurrentlyIbProcess -> CancelProcessInstanceConcurrentlyTest#shouldCancelAfterJobComplete
```

There are several MessageSubscription tests which I think are tested but at some I'm not 100% sure.

**Comment by Zelldon** [comment]
BTW: All these tests I can tell are related to engine functionality and not really related to StreamProcessor logic itself, which is why I don't see it in the scope of the ZDP (streamprocessor module). Correct me if I'm wrong.

**Comment by saig0** [comment]
These are really old test cases. I don't see a value in recreating them. 

I'm closing the issue. Let's add new test cases later if needed.
