### ISSUE TITLE
New engine with high throughput produces too many events for the exporter to keep up

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#6747]
**Describe the bug**

I have seen it in the last benchmarks already, but we thought it is related to elastic going out of disk space, but it is clearly not.
With https://github.com/camunda-cloud/zeebe/pull/6746 I tested different curator settings and it was able to keep elastic clean.

![elastic](https://user-images.githubusercontent.com/2758593/113967368-20709280-9831-11eb-8c41-ac379eb7aa15.png)

There seems to be a problem with deleting existing segments

![segments](https://user-images.githubusercontent.com/2758593/113967449-4ac25000-9831-11eb-93b0-ed1b15cbb0f1.png)

Which ofc makes then problems in our disk usage.

![pvc](https://user-images.githubusercontent.com/2758593/113967495-63326a80-9831-11eb-9993-028c597dfa95.png)

Snapshot seem to happen ? :thinking: But the count is broken, related #6125 

![snapshot](https://user-images.githubusercontent.com/2758593/113967605-9674f980-9831-11eb-9251-1bdc39d20ac9.png)

Compacting as well

![compacting](https://user-images.githubusercontent.com/2758593/113967637-aab8f680-9831-11eb-969c-f6244b418880.png)

If we take a closer look at the number of segments view then we can see that

![segmentsleak](https://user-images.githubusercontent.com/2758593/113967722-e227a300-9831-11eb-9491-9c1ea2293ac1.png)

If this would be the java heap I would say we have a leak.

[The log is flooded with journal creation statements, Idk whether this is really helpful.](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-04-07T14:17:30.000000000Z&customFacets=jsonPayload.context.actor-name,jsonPayload.thread&limitCustomFacetWidth=false&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-curator%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-curator%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22&scrollTimestamp=2021-04-07T14:19:23.320337000Z&dateRangeUnbound=forwardInTime&dateRangeStart=2021-04-07T13:17:30.000Z&dateRangeEnd=2021-04-07T15:17:30.000Z&pinnedLogId=3wdr4bg19u2mkq&pinnedLogTimestamp=2021-04-07T14:19:04.891579Z)
```
D 2021-04-07T14:19:03.944790Z raft-server-2-raft-partition-partition-3 Created segment: JournalSegment{id=69, version=1, index=3492389}   raft-server-2-raft-partition-partition-3
D 2021-04-07T14:19:04.891579Z raft-server-1-raft-partition-partition-3 Created segment: JournalSegment{id=146, version=1, index=3586836}   raft-server-1-raft-partition-partition-3
D 2021-04-07T14:19:04.928109Z raft-server-0-raft-partition-partition-3 Created segment: JournalSegment{id=146, version=1, index=3586836}   raft-server-0-raft-partition-partition-3
D 2021-04-07T14:19:05.529966Z raft-server-2-raft-partition-partition-1 Created segment: JournalSegment{id=69, version=1, index=3483601}   raft-server-2-raft-partition-partition-1
D 2021-04-07T14:19:07.743145Z raft-server-1-raft-partition-partition-1 Created segment: JournalSegment{id=146, version=1, index=3586959}   raft-server-1-raft-partition-partition-1
D 2021-04-07T14:19:07.795552Z raft-server-0-raft-partition-partition-1 Created segment: JournalSegment{id=146, version=1, index=3586959}   raft-server-0-raft-partition-partition-1
D 2021-04-07T14:19:10.748703Z raft-server-1-raft-partition-partition-2 Created segment: JournalSegment{id=146, version=1, index=3585289}   raft-server-1-raft-partition-partition-2
D 2021-04-07T14:19:10.844844Z raft-server-0-raft-partition-partition-2 Created segment: JournalSegment{id=146, version=1, index=3585289}   raft-server-0-raft-partition-partition-2
D 2021-04-07T14:19:11.999116Z raft-server-2-raft-partition-partition-2 Created segment: JournalSegment{id=79, version=1, index=3485006}   raft-server-2-raft-partition-partition-2
D 2021-04-07T14:19:20.721155Z raft-server-1-raft-partition-partition-3 Created segment: JournalSegment{id=147, version=1, index=3611502}   raft-server-1-raft-partition-partition-3
D 2021-04-07T14:19:20.762181Z raft-server-0-raft-partition-partition-3 Created segment: JournalSegment{id=147, version=1, index=3611502}   raft-server-0-raft-partition-partition-3
D 2021-04-07T14:19:22.515222Z raft-server-2-raft-partition-partition-3 Created segment: JournalSegment{id=70, version=1, index=3517085}   raft-server-2-raft-partition-partition-3
D 2021-04-07T14:19:23.256731Z raft-server-1-raft-partition-partition-1 Created segment: JournalSegment{id=147, version=1, index=3611539}   raft-server-1-raft-partition-partition-1
D 2021-04-07T14:19:23.320337Z raft-server-0-raft-partition-partition-1 Created segment: JournalSegment{id=147, version=1, index=3611539}   raft-server-0-raft-partition-partition-1

```

**To Reproduce**
Run the cluster

**Expected behavior**

Data is deleted

**Environment:**
 - OS: k8
 - Zeebe Version: snapshot
 - Configuration: benchmark

**Comment by deepthidevaki** [comment]
Are the exporters up to speed?

**Comment by Zelldon** [comment]
Further investigation shows that journal deletes some segments, but not enough.

We see statements like `
2021-04-07 17:28:24.885 CEST
raft-server-0-raft-partition-partition-2
raft-partition-partition-2 - Deleting log up from 7815309 up to 8236055 (removing 18 segments)`

In the metrics we can see that the segment count drops for the partition from 59 to 42, which means it deletes some but not enough. The question is why.


I checked the metrics again and we can see in general the exporting is twice as fast as the processing


![exportinggeneral](https://user-images.githubusercontent.com/2758593/113975136-5a489580-983f-11eb-9320-2c40a3d4da35.png)


But it is still hanging 14 million records behind

![exportingback](https://user-images.githubusercontent.com/2758593/113975153-63396700-983f-11eb-8fd3-3fef0b8e2889.png)

The issue I think is that we need to export all records, where we on processing only process migrated commands and records for not migrated processors. This was also mentioned by @pihme last week already. I think we need to fix this otherwise we will always have these problems in our benchmarks. 

One solution would be this https://github.com/camunda-cloud/zeebe/issues/6749

**Comment by Zelldon** [comment]
I checked the code and we already skip commands for the elastic search exporter. https://github.com/camunda-cloud/zeebe/issues/6749#issuecomment-815472818 They are filtered out or at least they should be.

If I think more about it I think it is related to how many follow up events we now generate, which we are not process but immediately apply to our state. The exporter needs to still export them.

**Comment by Zelldon** [comment]
Running for ~ 10 min means already lagging ~100k records behind

![export](https://user-images.githubusercontent.com/2758593/113980588-f6c26600-9846-11eb-8f61-c01ab6777b73.png)

**Comment by Zelldon** [comment]
Seems to be related to restarts https://github.com/camunda-cloud/zeebe/pull/6757#issuecomment-815923053

**Comment by Zelldon** [comment]
I think this issue is outdated, we haven't seen issues in our recent benchmarks
