### ISSUE TITLE
In the stream processor, avoid sending no response when adding side-effects

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#6919]
**Description**
A stream processor can implement the following method to add side-effects (e.g. like scheduling a timer).

```
@Override
  public void processRecord(
      final TypedRecord<DeploymentRecord> command,
      final TypedResponseWriter responseWriter,
      final TypedStreamWriter streamWriter,
      final Consumer<SideEffectProducer> sideEffect) 
```

By default, the response is written as a side-effect. If the side-effects are overridden by using `sideEffects::accept` then no response is sent implicitly. The response needs to be added explicitly. 

It is easy to fall into this trap and forget to add the response as a side-effect. Making the usage more safe could save us from bugs (like #6918).

**Comment by npepinpe** [comment]
So essentially reusing the `SideEffectQueue` everywhere?

**Comment by saig0** [comment]
Yes. That's the current idea. 
We can also get rid of some usage of side effects (e.g. when using the message subscription endpoint).

**Comment by saig0** [comment]
My assumption is that we could remove the side effects in most cases. We need to look deeper into timers. But for responses and message subscriptions it should be okay (the commands are processed eventually). 

If we can't remove it completely then we may find a way that fits better to the needs (i.e. less general).

**Comment by Zelldon** [comment]
Correct me if I'm wrong @saig0 but I think this is no longer an issue. We use widely the side effect queue and have the post commit task introduced with the newest abstraction.
