### ISSUE TITLE
Exporters catch up faster after restart or leader change

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#7088]
**Is your feature request related to a problem? Please describe.**
Each exporter reports the position of the last exported record back to the broker. The broker stores this position per exporter in the state (i.e. RocksDB). On a restart or leader change, it restores the last snapshot and loads the positions from the state. The exporters receive records that have a higher position compared to the state.

Since the positions are stored only in the state, it depends on the last snapshot of how many records the exporter receives again. If the last snapshot is up-to-date then the exporter receives no or just a few records again. If the last snapshot is a bit older or there are many records on the stream then the exporter receives many records again. 

The behavior itself is correct because the exporters should be idempotent. However, it can impact the memory consumption of the broker (i.e. the log stream can't be compacted until the records are exported), and the integration of other services/applications that consumes from the exporter's sink (i.e. outdated until the exporter caught up).

**Describe the solution you'd like**
The positions of the exporters are also stored on the log stream. So, the positions are replicated to the followers like other records in a much faster way.

In order to reduce the overhead, the records with the positions can be written periodically (e.g. every minute) and should be filtered out for the exporters themselves.

**Describe alternatives you've considered**
Every exporter manages the position themself outside of the broker. On restart or leader change, it restores the position and continues with the next record.

**Additional context**
This topic is relevant when building the state on followers. If we don't replicate the snapshots anymore (or less often) then we need a way to replicate/synchronize the exporter positions.

**Comment by Zelldon** [comment]
Just as comment: There is a ZEP which handles a bit this topic https://github.com/zeebe-io/enhancements/pull/2 and we thought about distributing the exporter position via gossip OR running exporters everywhere 

> In order to delete the log we need determine the last common position, based on the stream processor position and lowest exporter position. If the followers build there own state, they need to know the current lowest exporter position for this partition. The probably easiest way would be to distribute this position via gossip. We will introduce a new component called RemoteExporterStation, the name is discussable. This component is called by the ExporterDirector, when the export position is updated. This component will then share this information via gossip and store the position also in the corresponding ExporterState.

https://github.com/zeebe-io/enhancements/pull/2/files?short_path=efff10f#diff-efff10f9d865cdad6bfbff560d19b523be01a3babdf80c2e22f6301272cf66b6

**Comment by saig0** [comment]
Currently, we don't see any need to change the behavior. I'm closing the issue for now.
