### ISSUE TITLE
Improve error message in case of uncovered BPMN features

### ISSUE THREAD

**Issue by nitram509** [camunda/zeebe#7282]
**Is your feature request related to a problem? Please describe.**
I did report issue #7279, where I thought I found a bug because the error message did not let me think of missing feature implementation, but rather XML-related issues. So I spend some time to validated the XML file against many validators.

```
Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'/Users/maki/Downloads/hello_world.bpmn': - Element: Activity_1yyow37
    - ERROR: Elements of this type are not supported
``` 

**Describe the solution you'd like**
When Zeebe only covers a few BPMN features
(as described https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage#tasks)
I would prefer to see an error message, which better guides me as a user.
Considering the fact, the error message is shown in CLI tool, simple monitor, and others,
this should be much as possible self-describing.

**Describe alternatives you've considered**
May I propose an error message with more content and guidance?

Proposal
```
Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'/Users/maki/Downloads/hello_world.bpmn': - Element: Activity_1yyow37
    - ERROR: An un-supported element found. The XML is valid, but currently, just a sub-set of BPMN elements are supported, see the documentation for more details: https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage
```

**Additional context**
See #7279

**Comment by sccalabr** [comment]
I could pick this up
