### ISSUE TITLE
Camunda Platform BPMN models are rejected with a meaningful exception

### ISSUE THREAD

**Issue by berndruecker** [camunda/zeebe#7375]
**Is your feature request related to a problem? Please describe.**
We see examples of users that try to deploy BPMN models created for Camunda Platform to Camunda Cloud. There is some effort to improve situation in the docs or modeler, but it would also help to see a very clear exception message during deployment - as this would hint users into the right direction (see e.g. https://github.com/camunda/camunda-modeler/issues/2322 for a user stumbling over it). I expect this to happen more frequently in the future. Wrong models can be spotted by the Zeebe namespace missing but the Camunda Platform namespace being there.

**Describe the solution you'd like**
As a user I get a clear "can't deploy a BPMN made for Camunda Platform on Camunda Cloud" (or similar)

**Comment by jwulf** [comment]
This is related to https://github.com/camunda-cloud/zeebe/issues/7282

**Comment by Zelldon** [comment]
Should be resolved or improved with https://github.com/camunda/zeebe/issues/7282
