### ISSUE TITLE
Use profiles to configure CI and integration/unit tests execution

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#7432]
**Description**

We have several scripts which run tests (it-java.sh, test-java.sh, test-java8.sh) which currently run the same command, but specify different options. Most of these options can actually be configured via maven profiles, and it would simplify the CI pipeline if we leveraged these instead of having scripts with a high level of duplication (which makes it harder to maintain the pipeline).

It may be that this is not possible, so we should prototype it first, but it would be a big win if we could simplify our pipeline.

**Comment by Zelldon** [comment]
I think this can be closed @npepinpe or?
