### ISSUE TITLE
Improve benchmark setup script

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#7491]
**Description**

The benchmark setup script (in branch `medic-cw-benchmark`) has some shortcomings which could be improved upon:
* It downloads all dependencies for the benchmark starter, worker etc. because it runs inside a Docker container
* It builds starter, worker, simpleStarter individually, although they are the same code, just different artifacts
* It relies on a parent-pom:[version]-SNAPSHOT being published to Nexus beforehand

What would be better would be:
- map `.m2` folder into Docker container to speed up build
- This would also ensure that it uses the parent pom from that build, not the one published to Nexus
- build benchmark code only once and then extract the three artifacts out of it.

**Comment by npepinpe** [comment]
Just a note, I tried this before (for something else), and mapping the .m2 is a bit of a pain. To get it inside the builder container, you need to have it part of your build context, so you need to either set your build context to ~/.m2 (which transfers a lot and means you need to change all the paths in the Dockerfile to match that), or you need to symlink it locally, or use a local repository via `-DlocalRepositoryPath`. I think it might be easier to use Jib instead and drop building in the Docker container?

**Comment by Zelldon** [comment]
I don't think we will work on this, since we moved to GHA and the benchmark helm charts
