### ISSUE TITLE
Allow ES exporter records to be configured by intent

### ISSUE THREAD

**Issue by RomanJRW** [camunda/zeebe#7529]
**Is your feature request related to a problem? Please describe.**
Optimize uses the ES exporter to access Zeebe data. Currently, the exporter is configured to only export the records we care about in Optimize (`processes` and `process-instances`). However, this still results in more data being exported than we "care" about, because we get all records of that type, regardless of intent. Optimize only uses records of each type depending on their intent, so records that have any intent that Optimize doesn't care about never get read and are instead ignored. This is redundant storage, which would be nice to remove.

**Describe the solution you'd like**
The ES exporter is configurable in a way that each record type can also be filtered by their intent.

**Describe alternatives you've considered**
Optimize currently just reads the records with a given intent. Eventually there may be some concept of data archiving after it has been read - I believe Operate has something similar.

**Additional context**
This configuration would probably be useful to Operate too

**Comment by Zelldon** [comment]
@RomanJRW do you think this is still relevant? In our Camunda Platform 8 setup the elastic export is shared by all web apps so not sure whether it makes sense.

**Comment by Zelldon** [comment]
Ok thanks @RomanJRW than I will close it for now.
