### ISSUE TITLE
debugHttp exporter should update the exported record position by default

### ISSUE THREAD

**Issue by sergeylebed** [camunda/zeebe#7592]
**Is your feature request related to a problem? Please describe.**
I'm using debugHttp for in moment troubleshooting and debugging in a test environment. 
The test Zeebe run for days and then restarted. As records are not exported, the restart take 10th of minutes (15-20) before Zeebe becomes operable (reach the "Processor finished ..."  message in the log).

**Describe the solution you'd like**
I want that by default the debugHttp exporter update the exported record position. But it should be possible to change this behavior by setting the option in the configuration file. 

**Describe alternatives you've considered**
Drop of all data before restarting Zeebe. It works for some cases but not very useful for everyday. I would prefer to keep the test data as long as I need it.
Disable and enable the exporter all the time. It does not help to do in moment troubleshooting as I don't know before hand when I need it. I wish it is always enabled, so I can see all recent records at any moments.

**Comment by npepinpe** [comment]
We're planning on replacing the DebugHttpExporter with a more lightweight IPC exporter soon, where you would essentially just tail a file to consume exported records. I wouldn't put more effort into the existing one at the moment. I'm happy to accept a PR for this specific feature in the mean time however.

**Comment by npepinpe** [comment]
Exporter has been removed.
