### ISSUE TITLE
debugHttp exporter should display "Time Stamp" column

### ISSUE THREAD

**Issue by sergeylebed** [camunda/zeebe#7593]
**Is your feature request related to a problem? Please describe.**
When you see at the main view, it hard to say if you are looking at the recent or old records.

**Describe the solution you'd like**
A "Time stamp" column should be added, so you can easily distinguish records by human readable time stamp. 
For simplicity, I'm Ok if it is just record exported time.

**Describe alternatives you've considered**
I will be cool if set of displayed column be customizable. Including an ability to display values from event content.

**Comment by npepinpe** [comment]
As I mentioned in the other issue, we were thinking of replacing the DebugHttpExporter for a simpler IPC exporter based around files. If the front end is what you care about, it shouldn't be too hard to start the server externally and plug in the consumer of these files to feed it. But I don't plan on allocating any resources to it at the moment.

I am however curious to hear about why/how you're using it - we expected this exporter to be really only useful for Zeebe devs, or people who build exporter based applications. Could you tell us a bit more about your use case?

**Comment by npepinpe** [comment]
Exporter has been removed
