### ISSUE TITLE
Remove PartitionGroup or add state information

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#7598]
**Description**
The partition group has caused several hours of troubleshooting.

It is a modifiable object and has two states that are relevant in bootstrapping:
* Initial (without members)
* Opened (with members)

The state should either be explicit in the interface or type system so that components which require a partition group with members can check for the state.

Or the partition group needs to be replaced with something else.

**Comment by Zelldon** [comment]
Not 100% sure what is meant by this issue but sounds like a duplicate of https://github.com/camunda/zeebe/issues/7078
