### ISSUE TITLE
Introduce better abstraction for ActorScheduler

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#7689]
**Description**

We played already several times with the idea to replace our current actor scheduler with something else, like akka actors or another framework. In order to be able to do this we need a better abstraction around our current actor scheduler. The current implementation and usage is too tightly coupled, which makes it nearly impossible to replace without rewriting/touching everything.

**Comment by oleschoenburg** [comment]
I guess we can close it. We have enough issues regarding this already and it's not something we will just forget :laughing:

**Comment by npepinpe** [comment]
I would close this - if we do end up deciding to invest in our own non-blocking infrastructure, then that will probably get its own issues/epic.
