### ISSUE TITLE
Consider mutation testing

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#7876]
**Description**

I think that the crucial parts of logic should be tested well. But we can measure how well it tested using [mutation testing](https://pitest.org/), e.g. how many tests fail after we "broke" some parts of the logic. 

I know that you are pretty busy, so if you are okay with trying this concept - I'm ready to propose a PR with an example on some small but crucial scope :)

**Comment by pihme** [comment]
Feel free to give it a try. Would be interesting to learn about your experiences. I have used mutation testing in a smaller project: https://github.com/zeebe-io/zeebe-cluster-testbench/blob/1588797e0bc6f33df4fc531682aed97de9c030e7/pom.xml#L285

Feel free to use these mutators as a starting point. It gave me the most helpful hints in the other project. 

As for Zeebe, I will be curious how it effects build and test time, as this is already quite high.

**Comment by Zelldon** [comment]
I will close this issue is too general, for now. Feel free to reopen a more specific issue, with more details to act on.
