### ISSUE TITLE
Job activiation time is abnormal high with 1.2

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#7954]
**Describe the bug**

Based on the metrics it seems that the job activation latency is quite high, not measurable. This causes that the process instance execution time, becomes high as well.

![latency](https://user-images.githubusercontent.com/2758593/136511223-c2595ed9-84e2-4fde-b8f5-bcfb2f0732b3.png)

Weird is that it seems to recover sometimes, but goes back to high activation at some point. Not sure what the cause here is. Can it be the worker configuration? The setup of the benchmark?

**To Reproduce**

Run a benchmark with 1.2, one partition, one starter and worker.

**Expected behavior**

Normal latency as on previous version (1.1) 
![latency11](https://user-images.githubusercontent.com/2758593/136511494-655f53ae-80fe-4828-b74b-2e177245ad0c.png)
BTW here we see also sometimes such spikes, but not for such a long period of time.

**Environment:**
 - OS: k8
 - Zeebe Version: 1.2
 - Configuration: [benchmark.zip](https://github.com/camunda-cloud/zeebe/files/7309119/benchmark.zip)

**Comment by npepinpe** [comment]
Let's assume this is related to #7955, so let's focus on that one and leave this issue in the back log for now - if we find the cause of #7955 and it doesn't fix the job activation latency, then we can re-prioritize this.

**Comment by Zelldon** [comment]
Haven't seen this again and it might be related to #8551
