### ISSUE TITLE
Avoid access if ProcessingContext is not initialized completely

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#8009]
**Description**

We use the `ProcessingContext` for the stream processors to bundle components that are commonly used (e.g. writers). But at the moment, there is no guarantee that the context is initialized completely before reading from it. And it creates new objects when calling a getter.

We should ensure that the context is initialized before it is used by design. For example, by using a builder or another object.

**Comment by Zelldon** [comment]
Currently also stumbled again over the context, and I feel it is really messy how it is used. See [related comment](https://github.com/camunda/zeebe/issues/9602#:~:text=Passing%20always%20the%20processing%20context%20and%20updating%20and%20getting%20data%20out%20feels%20so%20odd%2C%20I%20would%20like%20to%20replace%20this%20with%20actually%20method%20arguments%2C%20so%20dependencies%20come%20also%20clearer.)

**Comment by Zelldon** [comment]
I think we improved here with the engine abstraction, I will close this feel free to correct me if I'm wrong
