### ISSUE TITLE
Enable sortpom on the bom module

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#8037]
It seems the sortpom-plugin is not enabled on the bom/pom.xml. Let's enable it

_Originally posted by @korthout in https://github.com/camunda-cloud/zeebe/pull/8032#discussion_r733723046_

**Comment by npepinpe** [comment]
Do you remember why we don't use the spotless built-in `sortPom`?

https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md#sortpom

**Comment by npepinpe** [comment]
Anyway, the biggest blocker here is that profile inheritance is sketchy in Maven. You don't actually inherit profiles, but they can be activated for child modules. What this means is, if you have a profile `autoFormat` defined in `zeebe-bom`, you can activate it and it will be enabled for `zeebe-parent`. However, you cannot extend it or modify it in `zeebe-parent`.

In our case, this means we would need to move the licensing configuration into the `bom` as well, not just spotless. This could be a good push for us to consider using spotless for licensing first, that way all we need is, well, spotless.

**Comment by korthout** [comment]
> Do you remember why we don't use the spotless built-in `sortPom`?

Historical. No time spend on it when we switched to spotless.
