### ISSUE TITLE
In the Java client, I can deploy DMN resources

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#8075]
**Description**

In the Java client, I should be able to deploy DMN resources. The deployment itself should work with the current state. But we need to switch to the new gRPC deploy request to receive the deployed decisions.

* switch to the new gRPC deploy request and response
* extend the command response object by adding the deployed decisions 
* adjust the JavaDoc to make it clear that DMN resources are supported

blocked by #8067 
blocked by #8074

**Comment by korthout** [comment]
The Java client offers support to deploy a process where the resource can be provided in multiple ways, including as an instance of `io.camunda.zeebe.model.bpmn.BpmnModelInstance`. Do we want to offer something similar for DMN resources?

**Comment by saig0** [comment]
> Do we want to offer something similar for DMN resources?

No. As far as I know, it is not common to create a DMN via the model API. If users request this feature then we could add it later.

The existing methods should be sufficient to deploy DMN files.
