### ISSUE TITLE
All partitions become followers

### ISSUE THREAD

**Issue by kumar-shantanu** [camunda/zeebe#8085]
**Describe the bug**
All of a sudden all the partitions become followers, 

➜  ~ zbctl status --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 1.1.0
Brokers:
  Broker 0 - zeebe-cluster-zeebe-0.zeebe-cluster-zeebe.services-1.svc.cluster.local:26501
    Version: 1.1.0
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Follower, Healthy
  Broker 1 - zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.services-1.svc.cluster.local:26501
    Version: 1.1.0
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Follower, Healthy
  Broker 2 - zeebe-cluster-zeebe-2.zeebe-cluster-zeebe.services-1.svc.cluster.local:26501
    Version: 1.1.0
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Follower, Healthy

When we restart all the pods, 3 partitions become leader, (After restart)
➜  ~ zbctl status --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 1.1.0
Brokers:
  Broker 0 - zeebe-cluster-zeebe-0.zeebe-cluster-zeebe.services-1.svc.cluster.local:26501
    Version: 1.1.0
    Partition 1 : Leader, Healthy
    Partition 2 : Leader, Healthy
    Partition 3 : Follower, Healthy
  Broker 1 - zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.services-1.svc.cluster.local:26501
    Version: 1.1.0
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Follower, Healthy
  Broker 2 - zeebe-cluster-zeebe-2.zeebe-cluster-zeebe.services-1.svc.cluster.local:26501
    Version: 1.1.0
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Leader, Healthy

**To Reproduce**

**Expected behavior**
There always should be 3 leaders with the current setup

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 1.1.0
 - Configuration: 3 nodes statefulset on k8s cluster

**Comment by megglos** [comment]
closing as stale
