### ISSUE TITLE
Single Broker commit latency is unreasonably high

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8132]
**Describe the bug**

In order to investigate https://github.com/camunda-cloud/zeebe/issues/7955 I run a new experiment with ONE broker and one partition. I started the starter with a rate of 100 pi/s and it was only able to start instances at a rate of 50 pi/s, whereas it was before able to start 100 pi/s in a replicated setup see here https://zeebe-io.github.io/zeebe-chaos/2021/10/29/Throughput-on-big-state

![general](https://user-images.githubusercontent.com/2758593/140073891-1499853c-e59c-45f1-8eff-92778df17e6d.png)

Resources are enough available, but there are even not used much.
![res](https://user-images.githubusercontent.com/2758593/140073886-63117f51-5efa-4420-80ef-da576a55483d.png)

In the latency metrics we can see that it is quite high ~500ms. 
![commit](https://user-images.githubusercontent.com/2758593/140074108-c4e60156-9239-4553-a4fb-ed4a69be2ede.png)

In comparison to a normal benchmark it is ~ 50 times higher

![repl-commit](https://user-images.githubusercontent.com/2758593/140074158-dc707cce-f2cf-4664-b5c8-19ce6317ada6.png)

**To Reproduce**

Run a single broker.

**Expected behavior**

The leader should be able to immediately commit.

**Log/Stacktrace**

**Environment:**
 - OS: 
 - Zeebe Version: develop
 - Configuration: 
[starter.yaml.txt](https://github.com/camunda-cloud/zeebe/files/7468077/starter.yaml.txt)
[zeebe-values.yaml.txt](https://github.com/camunda-cloud/zeebe/files/7468078/zeebe-values.yaml.txt)

**Comment by npepinpe** [comment]
Can we confirm which versions are affected by this?

**Comment by Zelldon** [comment]
@npepinpe I can run the experiment for the both last supported version is this something you're looking for?

**Comment by npepinpe** [comment]
I'd like to know when this started, basically, so we can narrow down our efforts.

**Comment by deepthidevaki** [comment]
I think this was always the case :thinking: When no replication, the leader flushes to disk for every append. But with replication, we flush only when we have a quorum, so flush in a batch. I thought this is why we introduced the experimental flag to disable flush :thinking:

**Comment by Zelldon** [comment]
> I'd like to know when this started, basically, so we can narrow down our efforts.

This doesn't necessarily answer my question :laughing: I will start with two new benchmarks for 1.1 and 1.2. I don't think it is worth to test it before (1.1) if we not creating patch releases for earlier versions.

> I think this was always the case thinking When no replication, the leader flushes to disk for every append. But with replication, we flush only when we have a quorum, so flush in a batch. I thought this is why we introduced the experimental flag to disable flush thinking

Interesting point @deepthidevaki ! Wasn't aware (or forgot about it). Couldn't we flush also in batches on single leader if this is better?

**Comment by deepthidevaki** [comment]
> Interesting point @deepthidevaki ! Wasn't aware (or forgot about it). Couldn't we flush also in batches on single leader if this is better?

Yes. We can do it. Question is do we mark the record as committed after it is flushed or before. When disable flush flag is set, it is marked as committed before it is flushed.

**Comment by npepinpe** [comment]
Related: https://github.com/camunda-cloud/zeebe/issues/4695

**Comment by Zelldon** [comment]
Seems to be as @deepthidevaki said already the case before, but with 1.2 it got a bit worse so less throughput (higher latency on commit)


![compare](https://user-images.githubusercontent.com/2758593/140083994-30bb7dde-6791-480a-a6f5-18d12be2872b.png)
![compare2](https://user-images.githubusercontent.com/2758593/140083997-9276ef65-63db-44fb-af8f-4adc2184aacf.png)

**Comment by npepinpe** [comment]
Hm, so this test doesn't really tell us much as to why it got worse with replication?

**Comment by Zelldon** [comment]
> Hm, so this test doesn't really tell us much as to why it got worse with replication?

Not 100% sure what you mean, sorry. If the question is whether it helps in regards to #7955 than the answer is no :D

**Comment by npepinpe** [comment]
You understood me perfectly :smile:

**Comment by npepinpe** [comment]
Under the assumption that focus for production is still a cloud/replicated deployment, then this is less of a focus for us at the moment than the other issue this came from, so I'll leave it in the backlog.

**Comment by npepinpe** [comment]
The blocker in the issue seems to be something else, no? Or did I misunderstand the issue?

**Comment by Zelldon** [comment]
> The blocker in the support issue seems to be something else, no? Or did I misunderstand the issue? Are they blocked by the performance?

It is about performance, they highlight this in one of the shared docs.

**Comment by falko** [comment]
Setting `ZEEBE_BROKER_EXPERIMENTAL_DISABLEEXPLICITRAFTFLUSH=true` should solve this issue, right? Use cases without replication are usually very short-running processes, where it is more efficient to re-run failed instances from start than investing the effort of replication for all instances.

**Comment by megglos** [comment]
Planning outcome:
- makes sense to look into this as part of https://github.com/camunda/product-hub/issues/642
=> moving to ready

**Comment by megglos** [comment]
ZDP-Planning:
- can me mitigated by new flush config
closing for now
