### ISSUE TITLE
Show blacklisting in the Grafana Dashboard

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8263]
**Is your feature request related to a problem? Please describe.**
Came up in a recent [incident review ](https://docs.google.com/document/d/1E03kB3UCfM3l8X0xU7RjzqvOnX8dk4GtKAmH5-_vY60/edit) that it would be nice to see whether instances are blacklisted or not, maybe also the rate of blacklisting.

I realized that we added a while ago the metrics for that, but never added this to the dashboard, see https://github.com/camunda-cloud/zeebe/pull/6715. 

**Describe the solution you'd like**

Either show a graph of blacklisted instance count or just some indication whether instances are blacklisted.

I had yesterday a **hard time**  to find a good visualization, since the count is only exported if there was a new blacklisted instance. If the pod is restarted the metric is not exported. _It might make sense to refill the metric on restart_ OR we need to work with it, but this would mean we can only show limited data, see below.

**Example A - Show an indication that instances are blacklisted**

![gauge-blacklisted](https://user-images.githubusercontent.com/2758593/143187841-3f9d4a4c-50b9-49de-95b0-43650d479103.png)
![gauge-blacklisted-general](https://user-images.githubusercontent.com/2758593/143187843-2c6c629b-0687-463a-82de-970f39a4e372.png)

In general I like this, since it shows directly whether there is something wrong.
The problem here is if the time frame is smaller (were no instances are blacklisted) than this indication is green. :-1: 

**Example B - Graph**

Showing a graph is not that fruitful, since as described above the metric is not always exported. 
![graph-blacklisted](https://user-images.githubusercontent.com/2758593/143187948-f6d36e3e-1b15-48a6-82ba-872d58592ca5.png)

Showing zero for null values
![graph-zero-blacklisted](https://user-images.githubusercontent.com/2758593/143188265-1b85b331-2306-40d2-94df-0132255c767c.png)

**Example C - Rate**

The rate of such metric is also not really useful, since the change is too rare.

![graph-rate-blacklisted](https://user-images.githubusercontent.com/2758593/143188214-3b44348e-3b0c-4464-85ed-5ccbb62ed60f.png)

**Example D - Table**
![table-blacklisted](https://user-images.githubusercontent.com/2758593/143188772-b439d832-b192-47ed-8b6e-dbe31842a7b9.png)

Other alternative would be to show in a table the recent count, but this is also very limited (to the time frame) and other

**Describe alternatives you've considered**.

Ideally we would export the metric always, this would simplify things enormous. Then we can choose better one or more of the possible visualization from above.

**Additional context**

Blacklisting always shows that something problematic happened in the process execution (processing). An exception was thrown during the execution, which mostly an indication of a bug. 

I would like to find a good way how we can visualize it and hope someone has some comments, opinion or ideas.

\cc @pihme

**Comment by pihme** [comment]
What about exposing the metric as a rate and visualizing it with a heat map?

**Comment by npepinpe** [comment]
Prioritized as planned for now under the assumption we won't work on a better long term alternative to blacklisting in the next quarter, and this will already be an improvement in terms of visibility. Before opening a PR for this, please discuss and decide on the visualization/metric that we want.

**Comment by Zelldon** [comment]
The question for me is really what we want to achieve with the metric.

Do we want to know really how many (exact) are blacklisted? Then Prometheus might be not the best fit, but if we just want to have an indicator that SOMETHING is blacklisted then this could work:
 
![blacklist](https://user-images.githubusercontent.com/2758593/148549724-9548b692-0f78-44a6-9783-0692e0bd9919.png)

Here we could change the colors and shown values to something like Blacklisted (if x > 0) and nothing (if x <= 0).I think this is similar what I have shown above with example A. This would potentially already help.

**Comment by pihme** [comment]
What about exposing the metric as a rate and visualizing it with a heat map?

**Comment by Zelldon** [comment]
This wouldn't help since the metric is not exported all the time.

**Comment by pihme** [comment]
I would expect to see a change in the blacklisting rate.

Kinda like here:
![image](https://user-images.githubusercontent.com/14032870/148551718-06e323ce-d576-4e46-bd78-130a9e97a4d5.png)

If it is not exported for some time, I will just see a black column, but I can always make the time scale wider and then I should see data pretty much for all the time, because each export would be aggregated in the rate (I hope).

Then I could look at a big enough time scale and if my blacklisting suddenly jumps from 2 per day to 200 per day, that would be my signal. And if the jump is correlated to e.g. the point there was an update or a pod restart, that would also be interesting.

This is all speculation though, one would have to see what it actually looks like.

**Comment by Zelldon** [comment]
Thanks @pihme 

yeah so it would look like this

15 mins
![heatmap](https://user-images.githubusercontent.com/2758593/148553374-792367bc-f419-43cf-a476-70b9f9244280.png)

90 days
![heatmap2](https://user-images.githubusercontent.com/2758593/148553377-ae5ce979-9e40-4134-a8c1-76a636c77043.png)

Problem is that we not store data long enough on our prometheus server. So there can be data deleted which contained some blacklisting, which is why I ask what we want to see. The real count or just an indication all in all I think our current metric doesn't work well. Ideally we would report always or on bootstrap with the current value of blacklisted instances.

**Comment by pihme** [comment]
Thanks @Zelldon. Yeah I regularly forget we forget data. I think 90 days would be good enough, and yes, the visualization looks like what I had in mind. But if the history is 30 days or less, it becomes less useful. So I see your point.

**Comment by Zelldon** [comment]
I think the best would be as described as alternative above:

> **Describe alternatives you've considered.**
> Ideally we would export the metric always, this would simplify things enormous. Then we can choose better one or more of the possible visualization from above.

This means at least on restart we export the metric at least once.

**Comment by Zelldon** [comment]
@remcowesterhoud since you mentioned to me that you had to look at a cluster with zdb to find out whether something was blacklisted might be useful for you to just have this in the metrics :)

**Comment by menski** [comment]
Right now we don't see value to implement this, we have other ways to identify blacklisted instances, which also allow us to see the corresponding process instance keys, i.e. logs or zdb.

Hopefully at one point we can get rid of blacklisting

**Comment by korthout** [comment]
ZPA triage:
- we want to gain more insights into the frequency of blacklisting before choosing to replace the concept

**Comment by remcowesterhoud** [comment]
Attaching this to the "Blacklisting replacement" as having insights in these metrics may be useful for this epic.

**Comment by Zelldon** [comment]
Reopening since we still need panels on the dashboard.

**Comment by koevskinikola** [comment]
ZPA triage:
- @Zelldon you mentioned [HERE](https://github.com/camunda/zeebe/pull/12606#issuecomment-1528862192) that you'll add the Grafana dashboards. Is this still your plan, or ZPA should do something from our side?
