### ISSUE TITLE
Follower not receiving snapshot after a restart

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#8264]
In a cluster, we observed the following:

- Zeebe-1 is not able to complete bootstrap
- Bootstrap of partition-28 is stuck. All other partitions have started. [logs](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=camunda-cloud-240911&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-11-22T14%3A09%3A44.865233000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%2210a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.cluster_name%3D%22prod-worker-2%22%0Aresource.labels.container_name%3D%22zeebe%22%0Atimestamp%3D%222021-11-22T14%3A07%3A55.035042000Z%22%0AinsertId%3D%22gh902uh0iw9dcwq8%22&scrollTimestamp=2021-11-22T14%3A07%3A55.035042000Z)
- Zeebe-0 is leader of partition 28
- Zeebe-0 is not able to send snapshot to zeebe-1. `No remote message handler registered for this message` [logs](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=camunda-cloud-240911&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-11-22T14%3A09%3A44.865233000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.cluster_name%3D%22prod-worker-2%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%2210a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe%22%0Atimestamp%3D%222021-11-22T14%3A08%3A08.121037000Z%22%0AinsertId%3D%228ev5u2qhrecz5wpl%22&scrollTimestamp=2021-11-22T14%3A08%3A10.625593000Z)

This was resolved automatically when the leader (zeebe-0) was restarted. 

Similar to #7339 But the root cause is different.

**To Reproduce**

Don't know how to reproduce this.

**Expected behavior**

A restarted node should be able to receive events and snapshots from the leader.

**Environment:**
 - Camunda cloud
 - Zeebe Version: 1.2.4

**Comment by deepthidevaki** [comment]
Links
- [Heap dumps](https://drive.google.com/drive/folders/13_U3VT7gqX9k_42pwl_LCJZMfk0TzPwO)
- [Grafana](https://grafana-worker-2.internal.camunda.io/d/I4lo7_EZk/zeebe?orgId=1&from=1637581298953&to=1637650255742&var-DS_PROMETHEUS=Prometheus&var-namespace=10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe&var-pod=zeebe-5&var-partition=All)
- [Logs](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=camunda-cloud-240911&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-11-22T14%3A09%3A44.865233000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.cluster_name%3D%22prod-worker-2%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%2210a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe%22%0Atimestamp%3D%222021-11-22T14%3A08%3A08.121037000Z%22%0AinsertId%3D%228ev5u2qhrecz5wpl%22&scrollTimestamp=2021-11-22T14%3A08%3A10.625593000Z)

**Comment by deepthidevaki** [comment]
On analyzing the heapdump zeebe-1 has a registered handler for message type`raft-partition-partition-28-install`. Hence this error `No remote message handler registered for this message` is not expected.

Together with @oleschoenburg we looked into it a bit. We observed the following:

Observed : Sending message to 5 failed, but channel information says R:zeebe-1.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 
Similarly later we see logs saying message to 1 failed with channel info for zeebe-5.
[logs](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&project=camunda-cloud-240911&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-11-22T12%3A35%3A27.071000000Z&customFacets&limitCustomFacetWidth=true&scrollTimestamp=2021-11-22T14%3A55%3A48.346660000Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-2%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.namespace_name%3D%2210a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.container_name%3D%22zeebe%22%0Atimestamp%3D%222021-11-22T10%3A39%3A00.927254000Z%22%0AinsertId%3D%22ucem426ek12x8lu8%22)

```
W 2021-11-22T10:39:00.926677Z RaftServer{raft-partition-partition-20} - AppendRequest{term=32, leader=0, prevLogIndex=65475006, prevLogTerm=31, entries=0, commitIndex=65475132} to 5 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0x24ccdefe, L:/10.64.20.3:38784 ! R:zeebe-1.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 
W 2021-11-22T10:39:00.927031Z RaftServer{raft-partition-partition-20} - ConfigureRequest{term=32, leader=0, index=0, timestamp=1636483959404, members=[DefaultRaftMember{id=6, type=ACTIVE, updated=2021-11-09T18:52:39.404Z}, DefaultRaftMember{id=5, type=ACTIVE, updated=2021-11-09T18:52:39.404Z}, DefaultRaftMember{id=0, type=ACTIVE, updated=2021-11-09T18:52:39.404Z}]} to 5 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0x3b890531, L:/10.64.20.3:42876 ! R:zeebe-1.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 
W 2021-11-22T10:39:00.927254Z RaftServer{raft-partition-partition-13} - InstallRequest{currentTerm=30, leader=0, index=65527679, term=30, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1891055740}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1686987390}, data=HeapByteBuffer{position=0, remaining=893330, limit=893330, capacity=893330, mark=java.nio.HeapByteBuffer[pos=0 lim=893330 cap=893330], hash=841568655}, initial=true, complete=false} to 5 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0xb0bbd3da, L:/10.64.20.3:38662 ! R:zeebe-1.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 
W 2021-11-22T10:39:00.927258Z RaftServer{raft-partition-partition-48} - ConfigureRequest{term=34, leader=0, index=0, timestamp=1636483958720, members=[DefaultRaftMember{id=6, type=ACTIVE, updated=2021-11-09T18:52:38.720Z}, DefaultRaftMember{id=5, type=ACTIVE, updated=2021-11-09T18:52:38.720Z}, DefaultRaftMember{id=0, type=ACTIVE, updated=2021-11-09T18:52:38.720Z}]} to 5 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0x3b890531, L:/10.64.20.3:42876 ! R:zeebe-1.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 
W 2021-11-22T10:39:00.928270Z RaftServer{raft-partition-partition-6} - AppendRequest{term=30, leader=0, prevLogIndex=64805822, prevLogTerm=30, entries=3, commitIndex=64805825} to 5 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0x10236207, L:/10.64.20.3:42880 ! R:zeebe-1.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 
W 2021-11-22T12:49:16.094711Z RaftServer{raft-partition-partition-42} - AppendRequest{term=27, leader=0, prevLogIndex=65582963, prevLogTerm=27, entries=0, commitIndex=65582970} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0x1feae3be, L:/10.64.20.3:55456 ! R:zeebe-5.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 
W 2021-11-22T12:49:16.096059Z RaftServer{raft-partition-partition-1} - AppendRequest{term=34, leader=0, prevLogIndex=67876795, prevLogTerm=34, entries=0, commitIndex=67876795} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0xa9e98629, L:/10.64.20.3:55084 ! R:zeebe-5.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 
W 2021-11-22T13:03:48.377513Z RaftServer{raft-partition-partition-42} - AppendRequest{term=27, leader=0, prevLogIndex=65583175, prevLogTerm=27, entries=0, commitIndex=65583175} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0xc7c61a7f, L:/10.64.20.3:37912 ! R:zeebe-1.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed 

```

Later at 2021-11-23 22:30:24.400 CET we see again similar logs when zeebe-1 and zeebe-5 is restarted.

```
RaftServer{raft-partition-partition-15} - InstallRequest{currentTerm=38, leader=0, index=64918537, term=38, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1632469860}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1661099011}, data=HeapByteBuffer{position=0, remaining=9306641, limit=9306641, capacity=9306641, mark=java.nio.HeapByteBuffer[pos=0 lim=9306641 cap=9306641], hash=-33970287}, initial=true, complete=false} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0x4b660af5, L:/10.64.19.2:54200 ! R:zeebe-5.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed
2021-11-23 22:30:27.677 CET
RaftServer{raft-partition-partition-14} - ConfigureRequest{term=48, leader=0, index=0, timestamp=1636483959444, members=[DefaultRaftMember{id=6, type=ACTIVE, updated=2021-11-09T18:52:39.444Z}, DefaultRaftMember{id=0, type=ACTIVE, updated=2021-11-09T18:52:39.444Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2021-11-09T18:52:39.444Z}]} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0x254de0d1, L:/10.64.19.2:54288 ! R:zeebe-5.zeebe-broker-service.10a34d81-f44a-4c02-a3d5-65d6666b4310-zeebe.svc.cluster.local/10.64.16.4:26502]} was closed
```
However at this time restart was successful.

It seems it is using the wrong channel to communicate to a broker. In this case, zeebe-5 is not replicating partition 28. If the leader is sending install requests for zeebe-1 to zeebe-5, then that explains why it received "No remote message handler" error. If a message is send to a different broker than expected, this may create other unexpected issues. So it would be good to investigate this asap.

We looked into code a bit more. Although we couldn't root cause it yet:
1. When we create channels, they are added to a channel pool. When clientconnection is it is recorded in a map 
https://github.com/camunda-cloud/zeebe/blob/381c72f2c2b4524edf7fef23c9912342597198c4/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java#L617
When the channel is closed it is removed from the connections. But it seems it is never removed from the channelpool.

2. Equality of InetSocketAddress is based on the ip. If IP matches, but host is different it will return the channel created for a different host but with same ip. A host with different IP can happen because of pod restarts in kubernetes. 
https://github.com/camunda-cloud/zeebe/blob/cb0a7330d6b301f3403eca6bdc5ec4565e5ab394/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/ChannelPool.java#L52

3. We don't know yet what happens if an old channel is re-used. It could be nothing, it cannot talk to the correct pod. Or it could be that it re-connects to the correct node but the channel info wrong, leading to the confusing log that we observed. But it will be good to investigate this further.

**Comment by menski** [comment]
Another candidate to be prioritized for next quarter
