### ISSUE TITLE
Periodically evict the github-action's maven cache

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#8273]
**Description**

Recently, we've had [an issue](https://github.com/camunda-cloud/zeebe/issues/8265) with the cached maven repository in our smoke-test github actions. 

As [a temporary fix](https://github.com/camunda-cloud/zeebe/pull/8270), the specific broken parts are removed from the cache every time.

To improve further, we could [create a workflow to periodically](https://github.com/camunda-cloud/zeebe/pull/8270#pullrequestreview-815662511) (e.g. weekly) clear out the cache. We could also consider to allow running this workflow on demand with the [workflow-dispatch](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch) event.

To resolve this issue, [the workaround](https://github.com/camunda-cloud/zeebe/blob/korthout-8265-clear-broken-cache-parts/.github/workflows/os-smoke-test.yml#L26-L33) should also be deleted from the smoke-test workflow.

Additional info: https://github.com/camunda-cloud/zeebe/pull/8270#issuecomment-978942434

**Comment by menski** [comment]
Alternative we could also disable caching totally as the smoke test is run in parallel to our CI pipeline which will take longer anyway

**Comment by Zelldon** [comment]
@oleschoenburg can we close this? since we disabled the caching?

**Comment by oleschoenburg** [comment]
Yes, let's do that for now. If we ever re-enable caching we'll have to think about it then.
