### ISSUE TITLE
Delete HTTP Debug Exporter

### ISSUE THREAD

**Issue by menski** [camunda/zeebe#8286]
**Description**

The HTTP debug exporter contains old versions of the Javascript libraries jquery and bootstrap. The exporter is not used by any developer anymore and should be deleted.

related to https://jira.camunda.com/browse/SEC-63

**Comment by npepinpe** [comment]
As discussed, let's just remove the front end for now and we can figure out a replacement next quarter for 1.4 where we don't have to start an HTTP server in the exporter :slightly_smiling_face:

**Comment by npepinpe** [comment]
Let me know if you're still going to work on the rest of this, otherwise I'll reprioritize it.

**Comment by Zelldon** [comment]
Done via https://github.com/camunda/zeebe/commit/ed964a0093596b92f5e4347cbb4a9abc8e2246ed
