### ISSUE TITLE
Introduce a less pessimistic backpressure algorithm

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#8298]
**Is your feature request related to a problem? Please describe.**
Users have quite often complained that they get "RESOURCE_EXHAUSTED" errors too frequent, even if the system is not supposed to be in high load.  The default backpressure algorithm is vegas. The limits calculated by vegas is a bit a pessimistic. Moreover it is also difficult to tune to a specific latency/throughput requirement.

AIMD, another backpressure algorithm available in Zeebe, is easy to configure. You can configure a RequestTimeout and the limit is calculated based on this value. The RequestTimeout is the expected latency of a single request. The limit is maintained in such a way that most of the requests are completed within the configured RequestTimeout. The limit is adjusted based on the observed latency. This sounds ideal. But the implementation of AIMD is not optimal. In high load scenario, aimd limit always fluctuates between minLimit to 2 * optimalLimit. As a result we never get a stable limit and throughput is usually below optimal.

**Describe the solution you'd like**
 Calculating limit based on a configured RequestTimeout is a good idea. This is also easy to configure as there are not many parameters to consider. Since AIMD does not work well, I propose a new algo which fixes some of the issues with the original AIMD.

Updating the limit in AIMD algorithm based on the oberved `rtt` of a request:
```
	if (didDrop || rtt > timeout) {
            currentLimit = (int) (currentLimit * backoffRatio);
        } else if (inflight * 2 >= currentLimit) {
            currentLimit =  currentLimit + 1;
        }
```

Updating the limit in New-aimd algorithm based on the oberved `rtt` of a request:
```
   if ((didDrop || rtt > timeout)) {
      if (inflight <= currentLimit) { // this check ensures that if it is already at the optimal limit, we don't reduce the limit further
        currentLimit = (int) (currentLimit * backoffRatio);
      }
    } else if (inflight * 2 >= currentLimit) {
      currentLimit = currentLimit + 1;
    }
```
This additional check `if (inflight <= currentLimit)` is all that is needed to fix AIMD algo. This check ensures that we don't reduce the limit further if we have already found an optimal limit. Here `inflight` is the number of inflight request at the time this request was sent. Let's say if the inflight was 10, and the rtt > timeout; then it indicates that 10 is too many requests. So we reduce the currentLimit only if it is more than 10. On the other hand, if the inflight was 20 and rtt > timeout, and if the currentLimit is 10, we do not reduce it further because at this point we already know that 20 is too many requests, that is why the currentLimit is 10. But we don't have any indication that 10 is too many, so we leave it as it is. 

**Describe alternatives you've considered**

Completely rethink backpressure approach.

**Additional context**
I ran some benchmark to evaluate to new-aimd implementation.
Note: Only ran with a single configuration/load. The results may change in different settings.

TLDR: 
* New-aimd has less number of request rejected due to backpressure compared to default
* New-aimd has slightly better throughput than default
* New-aimd has **higher process completion latency** compared to default
* It reacts well to change in processing latency => Limit is reduced when there is an increase in processing latency and vice-versa.

Configuration:
```
clusterSize: 3
partitionCount: 1
replicationFactor: 3

-Dapp.starter.rate=100

-Dapp.worker.capacity=50
-Dapp.worker.pollingDelay=1ms
-Dapp.worker.completionDelay=50ms
 worker.replicas = 6
 ```
New-aimd config:
```
  - name: ZEEBE_BROKER_BACKPRESSURE_AIMD_REQUESTTIMEOUT
    value: "200ms"
  - name: ZEEBE_BROKER_BACKPRESSURE_USEWINDOWED
    value: "true"
```

| New-aimd  | Default |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/1997478/144069988-b1c6678f-5008-4918-8e2b-359a05685394.png) | ![image](https://user-images.githubusercontent.com/1997478/144070078-dd544ce3-29a8-4949-86e8-dd5f72733dcb.png)  |

New-aimd:

Backpressure limit is higher than default. Meaning less requests are rejected due to backpressure. This result in slightly better throughput. Note that the result will be different, if we double the load to stress test the system. 

The avg process completion latency (Process Instance Execution time) is higher. This is because the number of un-processed records in logstreams is higher due to higher backpressure queue limit. 

The overall processing latency (~latency of a single request) stays on avg between 100-250ms, which is the configured RequestTimeout (200ms) for new-aimd. 

To see how it reacts to unexpected fluctuations in the system, we added some stress to the cpu, by running the `stress -c 4 -d 2`.

| New-aimd  | Default |
| ------------- | ------------- |
|![image](https://user-images.githubusercontent.com/1997478/144070452-233f3d3e-58f2-4779-b621-3fbbd78d9a09.png)  |  ![image](https://user-images.githubusercontent.com/1997478/144070508-ea9dfb45-f0f3-43ca-8d5a-0fc952146a36.png) |

We can observe that new-aimd reacts to the stress quite fast and reduce the limit. The overall processing latency was maintained between 100-500ms, not too distance from the configured RequestTimeout (200ms). 

# Support:
- SUPPORT-15888

**Comment by npepinpe** [comment]
Let's see if we find time this quarter, but otherwise definitely planned for Q1. Part of the criteria would be to confirm that it solves the following issues:

- [x] intuitive to understand/configure
- [ ] better initial/startup experience

**Comment by megglos** [comment]
reopened for backporting to 8.1

**Comment by deepthidevaki** [comment]
Backported.
