### ISSUE TITLE
Export missing records to ES

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#8337]
**Is your feature request related to a problem? Please describe.**
Currently, the Zeebe Elasticsearch exporter doesn't allow to export all records. The following records are missing:
* `timer`
* `message_start_event_subscription`
* `process_event`
* `deployment_distribution`

At the moment, these records are not consumed by a specific application. But they could be useful for debugging a behavior in Zeebe. Sometimes the records can't be read from the log stream because the log is compacted already (default: every 5 minutes). 
 
**Describe the solution you'd like**
Add the ES indexes for the missing record types. 
Extend the exporter configuration to enable/disable the exporting of these records. 

**Describe alternatives you've considered**
No export to ES for these records.

**Additional context**
This request was raised as an action item of the following incident: https://docs.google.com/document/d/1xQPZbGUG57VOi-u4MI8CZF_I6FbBh0nc_ukSFiZwsNk

**Comment by npepinpe** [comment]
I've put it at the back of the ready queue so that it gets done soon-ish, as this can be very helpful when dealing with incidents or debugging other bugs (as described in #8338).

**Comment by sdorokhova** [comment]
Hi @saig0 ,
why exactly did we decide to enable these records by default? For debugging purposes?

**Comment by Almaviva-ComuneME** [comment]
also Errors

**Comment by saig0** [comment]
@sdorokhova yes, correct. These records may help if something goes wrong.

Do you face any issues?

**Comment by sdorokhova** [comment]
We had issues on CI. We had an impression that it's performance related as we started getting more indices in ELS than before. But I disabled them in our tests, so should not be a problem any more.

I would say that in SaaS we may also observe more data usage because of these additional indices, but probably it's fine.
