### ISSUE TITLE
In metrics, I can distinguish the partition health of the leader from the followers

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#8352]
**Is your feature request related to a problem? Please describe.**
Currently, we have metrics in the broker that reports the health of each partition. Both as a leader of the partition and as a follower.

In the Zeebe Grafana dashboard, we use this metric to show the health of the partitions. Since it reads the status of the leader and followers, it may show a partition as unhealthy even if the leader is healthy. But this is confusing because we can make progress if the leader is healthy (and the majority of followers).  

**Describe the solution you'd like**
I would like to see in the metric if a partition is healthy and can make progress or not.

For example, by introducing 3 states of partition health:
- red - the leader is unhealthy 
- yellow - at least one follower is unhealthy
- green - on all nodes are healthy

Idea: extend the current partition health metric by the partition role of the broker (i.e. `<partion-id>.<partition-role>:<health-status>`).

**Describe alternatives you've considered**
In the Grafana dashboard, show the partition health of each node. In order to determine if a partition can make progress then this list must be joined with the partition leader list. 

**Additional context**
The issue was raised as an action item of the [game day 2021-12-06](https://confluence.camunda.com/pages/viewpage.action?spaceKey=ZEEBE&title=2021-12-06+Game+Day).

**Comment by Zelldon** [comment]
This was removed because it increases the cognitive load, especially on many nodes and partitions. See related PR https://github.com/camunda-cloud/zeebe/pull/7065 please consider this on implementing.

I think the suggested idea regarding the different colors is in general cool, but I'm not sure how easy it is to implement such view. The health metric doesn't give any information about the role and the role metric has no information about the health, so this would need to be combined somehow.

**Comment by npepinpe** [comment]
I think you can use value mappings to map aggregated values to a single value, which can be a color for example. I'm not an expert but AFAIK that's what value mappings are for. Don't know how easy it would be though :slightly_smiling_face: 

Upgrading to Grafana 8 would give us the state timeline view, which is perfect for such things - https://grafana.com/docs/grafana/latest/visualizations/state-timeline/

I think it's something to consider if we have a goal for next quarter related to this. If not, then I'll try to plan it as part of non-OKR work.

**Comment by Zelldon** [comment]
with the new overview dashboard we have that https://github.com/camunda/zeebe/pull/9067
