### ISSUE TITLE
Flaky test statistics reports nonsensical names

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#8374]
**Describe the bug**

It happens sometimes, looking at the flaky test dashboard, that some builds report nonsensical names for their failures. The top reported failing test is simply `No`, for example. It's unclear if the error is in the Jenkins pipeline or in the plugin, but in order to properly understand how often a test fails, we need to collect the right data.

**To Reproduce**

I unfortunately couldn't find an existing build with this as we only keep 10 builds, but run a branch, or just develop, and it will eventually happen.

**Expected behavior**

We report the right flaky tests in order to collect statistics properly.

**Comment by npepinpe** [comment]
This is important to be able to detect if certain features or modules are flakier in general, and to properly prioritize which flaky tests should be tackled first (if there's more than a few). However it's less urgent than other things this close to the end of the quarter.

**Comment by Zelldon** [comment]
@npepinpe do we know how to fix it? Or what the error/issue is?

**Comment by npepinpe** [comment]
No, but I think we could find out. That would require us to save the `FlakyTests.txt` file we analyze to extract the names on failure, so we can check when it happens and see what was the text input. That would help figure out if the issue is with the plugin generating the text file, or with the bash script parsing it (more likely :smile:)
