### ISSUE TITLE
Deployment response subscription is not closed after a successful response.

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#8524]
**Describe the bug**

When a new deployment is distributed, the distributor opens a subscription to receive the response.
https://github.com/camunda-cloud/zeebe/blob/d89a46ebadbdeb1b3f947fe8d955dbce84eca420/broker/src/main/java/io/camunda/zeebe/broker/engine/impl/DeploymentDistributorImpl.java#L166-L170

However this is never unsubscribed. This can cause multiple problems:
1. Memory leak. The subscription is forever kept in the event service. The impact is low, as we don't expect many such subscriptions existing.
2. Consider the following scenario:
    - Node was leader
    - Created this subscription
    - Did not receive a successful deployment response
    - Became follower
    - Became leader
    - Retry deployment
    - A previous subscription already exists. What would happen in this case? I guess then the future is never completed, as a result deployment is never marked as fully distributed even though it has. (I have not verified this behavior.)

**To Reproduce**

**Expected behavior**

Opened subscriptions are closed.

**Environment:**
 - Zeebe Version: 1.3.0

**Comment by npepinpe** [comment]
Let's do it for 1.4, but as neither we nor users have observed this (that we know of), let's focus on the other OOM issues first.

**Comment by romansmirnov** [comment]
Just observed that in a benchmark I was running recently:

![image](https://user-images.githubusercontent.com/2368139/150504461-d87d9bcc-9817-4f9e-9798-9c280d4877e0.png)

Basically, it happened what @deepthidevaki described in the issue. The `DeploymentDistributor` holds a reference to an already closed `StreamProcessor` which references the log stream and also the dispatcher. This results in one of the biggest objects in the heap.

**Comment by korthout** [comment]
Since there is no known workaround, the severity should be `high`

**Comment by korthout** [comment]
Marking priority as `later`, because the issue states:
>The impact is low, as we don't expect many such subscriptions existing

Please comment if you think this should have a higher priority.

**Comment by deepthidevaki** [comment]
This may not be a problem anymore because of the recent refactoring done by @oleschoenburg #9858

**Comment by korthout** [comment]
That's a good point. I believe you're right, as the inter-partition communication no longer subscribes to a response. The responding partition simply sends a new command to the receiving partition. There is no response subscription anymore. Do I have that correct @oleschoenburg?

**Comment by oleschoenburg** [comment]
Yep, closed by #9858

**Comment by korthout** [comment]
Thanks @oleschoenburg ❤️
