### ISSUE TITLE
InstallRequests are sent almost everytime a new snapshot is taken by the leader

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8565]
**Describe the bug**

Looking at the code I found this https://github.com/camunda-cloud/zeebe/blob/develop/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java#L358 For me it looks like that almost every time when the Leader has taken a snapshot and compacted the corresponding log he needs to send a snapshot to a follower, if this lags a bit behind.

I felt this would be quite likely to be the case. Taking a look at the current benchmarks we can see that this is indeed the case.
![installreq](https://user-images.githubusercontent.com/2758593/148766744-0def58a9-427d-44f0-a9e4-61a3f60a6909.png)

We see that every 5 minutes on all partitions a snapshot is sent. This cause multiple things, we need the time to send snapshots instead of using time for replicating entries and processing events. We need to transition to inactive and follower again on the Follower nodes, unnecessary work we need to do.

**To Reproduce**

Run a benchmark.

**Expected behavior**

We don't need to sent a snapshot all the time, just in rare cases I would expect.

**Environment:**
 - OS: 
 - Zeebe Version: 1.3.0, 1.2.x
 - Configuration:

**Comment by npepinpe** [comment]
May be related to #8566. Let's see if we have time this quarter to work on this, and come up with an improved heuristic of when to send the snapshot to a follower (possibly delaying compaction).

**Comment by oleschoenburg** [comment]
I was able to run [a benchmark](http://34.77.165.228/d/I4lo7_EZk/zeebe?orgId=1&from=now-2d&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=os-delayed-compaction-2&var-pod=All&var-partition=All) that didn't send install requests for >2 days until one of the brokers got preempted. The changes I've made:

1. max appends per follower: 2 -> 8
2. max append batch size 32KiB -> 64KiB
3. prefer snapshot replication threshold: 100 -> 10000
4. delay compaction by 1 minute
5. confirm append result synchronously: (see "Next steps" in https://github.com/camunda-cloud/zeebe/issues/8551#issuecomment-1008888797)

**Comment by npepinpe** [comment]
Are we sure that it's safe to complete synchronously? The callback is executed in the thread that completed the future - can we really guarantee that it's always the right thread context? I'm afraid this seems somewhat error prone, but I could be wrong, and maybe it's set up in a way that we can guarantee that it's always completed in the right thread context.

How did you delay compaction? I thought we postponed building this - do we already have this as a configuration setting?

**Comment by oleschoenburg** [comment]
> How did you delay compaction

In `LogDeletionService`: 
```patch
   @Override
   public void onNewSnapshot(final PersistedSnapshot newPersistedSnapshot) {
-    actor.run(() -> delegateDeletion(newPersistedSnapshot));
+    actor.call(
+        () -> {
+          actor.runDelayed(Duration.ofMinutes(1), () -> delegateDeletion(newPersistedSnapshot));
+        });
   }
```

> Are we sure that it's safe to complete synchronously

I had a quick glance and I think the append future is always completed by the `LeaderAppender` after checking the thread with `raft.checkThread()`

**Comment by npepinpe** [comment]
Moving to the backlog for now, probably until Q2. See the last comment in https://github.com/camunda-cloud/zeebe/issues/8425.
