### ISSUE TITLE
Add Anti-affinity to Benchmarks

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8613]
**Description**

Discussing some performance issues with @oleschoenburg we conclude it might make sense to add anti affinity rules to our current benchmarks. This should help to get comparable performance results and will gives us better availability.

Here https://github.com/camunda-cloud/zeebe/issues/8551#issuecomment-1016182449 we saw some issues related to this which made it hard to compare the performance results.

Possible rule we can see in the controller:  https://github.com/camunda-cloud/zeebe-controller-k8s/pull/788

**Comment by npepinpe** [comment]
Let's do it.

**Comment by npepinpe** [comment]
Is this still do-able with the new Helm charts?

**Comment by oleschoenburg** [comment]
Yes, the zeebe helm chart allows setting pod affinity rules: https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/README.md#zeebe

**Comment by Zelldon** [comment]
This is on per default
