### ISSUE TITLE
Need information on Partitions

### ISSUE THREAD

**Issue by awesomeankur** [camunda/zeebe#8709]
**Description**

I have configured,3 brokers with 5 partitions each, my client was making parallel calls @150tps and zeebe was throwing errors as partitions were getting exhausted.
I went to reconfigure the partitions to 12 ,and now I don't see any error .
Questions :-

- Is there any relation between number of brokers and partitions configured.
- Is there a metric to measure the load on each partition.

**Comment by deepthidevaki** [comment]
@awesomeankur 

> Questions :-
> 
>     * Is there any relation between number of brokers and partitions configured.

In general, No.  Only condition is that there should be atleast as many brokers as the `replicationFactor`. You can configure any number of partitions and brokers, although too many partitions in a broker can impact performance and resource usage.

>     * Is there a metric to measure the load on each partition.

You can look at the [provided grafana dashboards.](https://github.com/camunda/zeebe/tree/main/monitor/grafana) There are many metrics that provide insight into the partitions load. As a first step you can look at the Zeebe Overview dashboard.

**Comment by npepinpe** [comment]
I'll consider this answered :)
