### ISSUE TITLE
On each metadata change, the topology of partition followers grows in the Gateway's broker topology

### ISSUE THREAD

**Issue by romansmirnov** [camunda/zeebe#8724]
**Describe the bug**

In a long-running scenario, where the Gateway is up and running for a long time, the heap memory consumption of `BrokerTopologyManager` grows over time:

![image](https://user-images.githubusercontent.com/2368139/152310684-505b7001-4f39-4f5e-b25d-fc3fe29cce49.png)

Especially, the property `partitionFollowers` grows the most:

![image](https://user-images.githubusercontent.com/2368139/152311041-8b0caa54-0b2b-410c-a520-3ef3add2336b.png)

Whenever there is a metadata change, the Gateway gets notified about it by the respective broker. The Gateway will update the topology information accordingly. Thereby, it will update the list of followers for a specific partition every time. Basically, it will always add the broker to the list of followers for a partition:

https://github.com/camunda-cloud/zeebe/blob/df800d41fcc307817b692d17d9c87247f2825516/gateway/src/main/java/io/camunda/zeebe/gateway/impl/broker/cluster/BrokerClusterStateImpl.java#L90-L97

It only removes the broker from the list of followers for a specific partition if the broker transitions to another role then `FOLLOWER`. Meaning, if a broker remains all the time as `FOLLOWER` for a specific partition but other metadata changes (like terms or the healthy state) overtime frequently, the broker is added multiple times to the list of followers for that specific partition:

![image](https://user-images.githubusercontent.com/2368139/152312097-c60ce8c9-db9e-46ec-8c2e-5c74952d3724.png)

The same applies to the property `partitionInactiveNodes`:

https://github.com/camunda-cloud/zeebe/blob/df800d41fcc307817b692d17d9c87247f2825516/gateway/src/main/java/io/camunda/zeebe/gateway/impl/broker/cluster/BrokerClusterStateImpl.java#L99-L106

**To Reproduce**
* Let the cluster with a Gateway run for a long period whereby the metadata changes over time frequently

**Expected behavior**
* The followers are listed only once for each partition so that the retained size of the object of `BrokerTopologyManager` doesn't grow over time.

**Environment:**
- Zeebe Version: 1.4.0-SNAPSHOT

**Comment by npepinpe** [comment]
Thanks for the clear report, seems like a low hanging fruit and we should do it (under the assumption it's a quick fix).
