### ISSUE TITLE
Various CI stages are regenerating sources

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#8766]
**Description**

It seems some CI stages are regenerating sources, and possibly doing other things which may cause issues when done in parallel. For example, the test stage will regenerate the assertj protocol assertions.

Ideally this is done once at the beginning, and then never again to avoid parallel stages overwriting each other's work and causing issues.

**Comment by npepinpe** [comment]
We should do it soon, but the idea is that when/if it happens, it should be quite obvious, as the code would fail to compile past the build phase.

**Comment by Zelldon** [comment]
I think we can close this as we moved to GHA
