### ISSUE TITLE
As a user I want to configure `LongPollingActivateJobsHandler`

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#8777]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to customize `LongPollingActivateJobsHandler`. Like timeouts, minimal empty responses, etc.

**Describe the solution you'd like**
I think that these settings should be added via Spring Boot configuration **and** environment variables.

**Describe alternatives you've considered**
Maybe these should be configured via environment variables **or** Spring Boot configuration.

**Additional context**
You can find the source of this issue here: https://camunda-cloud.slack.com/archives/C6WGNHV2A/p1644477175720079

**Comment by npepinpe** [comment]
Seems reasonable. These should indeed be done via the normal gateway configuration. There's already a `LongPollingCfg`, so we can piggyback on that. I don't think we will focus on this for now, but I'm happy to receive a PR for it.

**Comment by Abhi-vashisth** [comment]
hello is anyone assign to this issue or i can work on it

**Comment by aivinog1** [comment]
Hey @Abhi-vashisth, 

I'm already working on it, but feel free to provide your solution 🙂

**Comment by npepinpe** [comment]
With job streaming making use of polling under the hood, increasing the long polling timeout becomes more and more useful to reduce the amount of unnecessary requests. So I would push a bit to allow at least configuring the timeout.
