### ISSUE TITLE
`StreamProcessor` health check shouldn't fail when actor is busy

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#8783]
**Description**

The `StreamProcessor` tries to detect if an actor is stuck by periodically scheduling jobs that update `lastTickTime`. If the `lastTickTime` was not recently updated, the `StreamProcessor` reports as unhealthy.

This is somewhat brittle when the actor is busy with other jobs, causing the `StreamProcessor` to report as unhealthy for a moment until recovering. In one case where we lost the timer job due to #8776, the `StreamProcessor` is stuck reporting unhealthy. 

We could implement this differently by also checking that `ProcessingStateMachine#getLastSuccessfulProcessedRecordPosition` is increasing. This is not enough because this would trigger in cases where no work is being performed so we need to bring in additional data such as "does the logstream have more events" or "does a newly scheduled job get completed" (which is similar to the original check).

**Comment by npepinpe** [comment]
It's worth challenging, and it seems to be annoying for both the team when investigating/debugging as well as customers due to how noisy it can be, so let's look into it in the near future.

**Comment by deepthidevaki** [comment]
> This is somewhat brittle when the actor is busy with other jobs, causing the StreamProcessor to report as unhealthy for a moment until recovering. In one case where we lost the timer job due to https://github.com/camunda-cloud/zeebe/issues/8776, the StreamProcessor is stuck reporting unhealthy.

It became unhealthy because clearly there was a problem. A timer task was lost. So I wouldn't say that it reporting unhealthy is a noise.

I also think that if the StreamProcessor is too busy to execute this task, then there is a problem which we should look into. So reporting unhealthy in this case is probably useful.

**Comment by deepthidevaki** [comment]
Would you like to change this behavior or keep this? I would say to keep this behavior as it is useful to detect issues and close this issue.

**Comment by Zelldon** [comment]
I will close this issue, due to lack of activity and I agree with Deepthi here. Feel free to reopen this
