### ISSUE TITLE
Move all Spring specific integration code to the distribution and QA

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#8845]
**Description**

Any Spring specific code should go in the distribution module for production code, and in the QA module for tests as well. This means removing Spring extensions and the likes from the `util` module and the likes.

The motivation here is to keep our integration with Spring as light as possible, and keep it as our configuration layer and management server only. It should be used to startup the application, but afterwards should not be referred to internally. As the distribution code grows over time, it might mean we will need to split the gateway and broker artifacts, but I think that's something we probably need to do eventually anyway.

This will also avoid things like the client module pulling in `util`, which then pulls in Spring, something that is more than unexpected when pulling in our client.

**Comment by menski** [comment]
@npepinpe I'm not aware if anyone will find time to work on this, therefore I removed it from the board for now. Feel free to re-add it

**Comment by megglos** [comment]
@npepinpe what's the state of this? are you actively working on it or shall we move this back into backlog for now as priorities have changed?

**Comment by npepinpe** [comment]
We can move back into the backlog for now, I will close it soon this week

**Comment by Zelldon** [comment]
@npepinpe any update? You wanted to close this issue?

**Comment by npepinpe** [comment]
Yes, I forgot to close it. I had some thoughts about next steps, but honestly it's hard to find the motivation to work on this, so I'll close it.
