### ISSUE TITLE
Replace usages of JSR305 from FindBugs with SpotBugs annotations

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#8846]
**Description**

As we use SpotBugs ourselves, and the FindBugs project is dormant, we should replace any and all usage of its annotations with SpotBugs. This means replacing:

```xml
<dependency>
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
</dependency>
```

With:

```xml
<dependency>
  <groupId>com.github.spotbugs</groupId>
  <artifactId>spotbugs-annotations</artifactId>
</dependency>

<dependency>
  <groupId>net.jcip</groupId>
  <artifactId>jcip-annotations</artifactId>
</dependency>
```

The source here is the SpotBugs documentation itself. And as we do rely on SpotBugs, I would encourage us exploring making better use of their annotations to leverage the tool.

NOTE: this might also mean replacing usages of any other `javax.annotation` or JSR305 implementations with SpotBugs's own, if possible. I don't think we use any other, but I could be wrong.

**Comment by menski** [comment]
Potential topic for the weeks around the next release for someone to pick-up, no urgency right now, therefore I removed it from the board.
