### ISSUE TITLE
Introduce daily release dry run for all supported versions

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8859]
**Description**

I would like to have a recurring job for each stable branch, which we currently support (the latest two minor). This job should run every night and build the release without pushing. This should help us to maintain the release pipeline and fix it early. Fixing a failed build, would be part of the medic duty.

Currently, It is annoying to be a release manager and fix every time the pipeline.

**Comment by Zelldon** [comment]
Talking about that maybe we can also have a nightly build/image which we just retag on the release day so we skip the complete magic process. I mean QA and tests etc are anyway run every night, there is no real value at least I see none to do it again.

**Comment by menski** [comment]
Makes total sense to me, but nothing I guess we can achieve in Q1 anymore, maybe something to prioritize for Q2

**Comment by npepinpe** [comment]
Would this supersede https://github.com/camunda/zeebe/issues/6249?

**Comment by Zelldon** [comment]
This have been done by @megglos
