### ISSUE TITLE
Add NewThrowErrorCommand function to the Go JobClient interface 

### ISSUE THREAD

**Issue by RedUno** [camunda/zeebe#8870]
**Is your feature request related to a problem? Please describe.**
I'm implementing a Go Worker that instead of sending a JobFailed command if something wrong happened, it will send a ThrowError command so it can be handle on the process side. To do that i'm implementing a [`JobHandler`](https://github.com/camunda-cloud/zeebe/blob/clients/go/v1.3.5/clients/go/pkg/worker/jobWorker.go#L29)  which take a `JobClient` as first argument, however the [JobClient](https://github.com/camunda-cloud/zeebe/blob/clients/go/v1.3.5/clients/go/pkg/worker/jobWorker.go#L27) interface doesn't provide the `NewThrowErrorCommand` function unlike the C# Client that expose this [method](https://github.com/camunda-community-hub/zeebe-client-csharp/blob/master/Client/Api/Worker/IJobClient.cs#L117).

**Describe the solution you'd like**
Add `NewThrowErrorCommand` to `JobClient` interface on the Go Client

**Describe alternatives you've considered**

Is it safe to create a new zeebe client inside of my handler function to throw the error since the [ZeebeClient](https://github.com/camunda-cloud/zeebe/blob/clients/go/v1.3.5/clients/go/pkg/zbc/client.go#L123) implement it ?  if yes, should i send a `FailJobCommand` or `CompleteJobCommand` before exiting the function ?

**Comment by RedUno** [comment]
Hello,
I tried the **alternative** solution by creating a new ZeebeClient inside my handler function to throw an error,  then just exiting the function and it **works**. But i prefer the first solution instead if the feature will be added in an upcoming release.
thanks

**Comment by menski** [comment]
Hey @RedUno, thanks for raising this issue. The feature is valid and is also aligned with the Java client which already offers this. Would you be interested in providing a PR to resolve this issue?

**Comment by RedUno** [comment]
Hi @menski 
Can you give me please permission to push my branch please ?

**Comment by menski** [comment]
Hi @RedUno sorry for the late response. I cannot give you access to the Zeebe repository. What would be the correct approach is to fork the repository to your personal account and then develop your changes in your personal fork. After that you would create a pull request from your personal fork to the main repository. You can read more about this flow in this guide https://docs.github.com/en/get-started/quickstart/contributing-to-projects
