### ISSUE TITLE
Several links in the "Recommended Docs Entries for New Users"-section of the README is broken

### ISSUE THREAD

**Issue by FritjofH** [camunda/zeebe#8889]
Several of the links to the internal Camunda documentation is broken as they contain non-working "/index". 

There is also one "non-index" link that is broken due to a broken link to a sub-section.

- https://docs.camunda.io/docs/guides/getting-started/create-camunda-cloud-account
- https://docs.camunda.io/docs/components/zeebe/technical-concepts/index
- https://docs.camunda.io/docs/self-managed/zeebe-deployment/index
- https://docs.camunda.io/docs/apis-clients/java-client/index
- https://docs.camunda.io/docs/apis-clients/go-client/index

All of the above leads to:
```
Not Found
The requested URL was not found on this server.

Apache Server at docs.camunda.io Port 443
```
Using Chrome Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by FritjofH** [comment]
For some reason I can't push my local branch to the repo for a pull request, getting issues with permission denied, but the links should be changed to the following:
* [What is Camunda Cloud?](https://docs.camunda.io/docs/product-manuals/concepts/what-is-camunda-cloud)
* [Getting Started Tutorial](https://docs.camunda.io/docs/guides/getting-started/#create-camunda-cloud-account)
* [Technical Concepts](https://docs.camunda.io/docs/product-manuals/zeebe/technical-concepts/)
* [BPMN Processes](https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-primer)
* [Configuration](https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/)
* [Java Client](https://docs.camunda.io/docs/product-manuals/clients/java-client/)
* [Go Client](https://docs.camunda.io/docs/product-manuals/clients/go-client/)

**Comment by Zelldon** [comment]
We resolved the broken links and added a check to the documentation repo to verify the link from external sources.
