### ISSUE TITLE
As a Zeebe broker, make activated jobs re-activatable which were not send to the gateway

### ISSUE THREAD

**Issue by romansmirnov** [camunda/zeebe#8917]
**Description:**

When the broker activates jobs and before sending them back to the gateway, the gateway potentially could close its connection (e.g., the request timed out, network interruption, gateway died, etc.). As a result, the jobs being marked as activated remain to be activated, and thereby cannot be picked up again until the specified job timeout. In the case of having high job timeouts, this might result in high latency between the time a job is created and completed.

**Potential Solution:**

Whenever the broker cannot send back the activated jobs to the gateway, the activated jobs are made re-activatable by submitting a fail command:

- [ ] Get notified if responding with the activated jobs to the gateway was successful or not
- [ ] If the sending response failed, make the jobs re-activatable by submitting a fail job command

---

related to #3631

**Comment by menski** [comment]
@romansmirnov is this solved by #3631 or still relevant?

**Comment by Zelldon** [comment]
done by https://github.com/camunda/zeebe/pull/8879
