### ISSUE TITLE
Use Foreign Keys in `Db*State`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#8930]
Let's go over each `Db*State` and see where we can use foreign keys.

- [x] [DbDecisionState](https://github.com/camunda-cloud/zeebe/pull/8939)
- [ ] #8957
- [x] [DbProcessState](https://github.com/camunda/zeebe/pull/8970)
- [x] [DbElementInstanceState](https://github.com/camunda/zeebe/pull/8969)
- [x] `DbEventScopeInstanceState`, nothing to do.
- [x] [DbIncidentState](https://github.com/camunda-cloud/zeebe/pull/8932)
- [x] [DbJobState](https://github.com/camunda-cloud/zeebe/pull/8933)
- [x] [DbTimerInstanceState](https://github.com/camunda/zeebe/pull/8971)
- [x] `DbMessageStartEventSubscriptionState`, nothing to do. 
- [x] [DbMessageState](https://github.com/camunda-cloud/zeebe/pull/8950)
- [x] ~~`DbMessageSubscriptionState`~~, see https://github.com/camunda-cloud/zeebe/issues/8930#issuecomment-1075275686
- [x] `DbMigrationState`, nothing to do.
- [x] `DbBlackListState`, nothing to do.
- [x] `DbLastProcessedPositionState`, nothing to do.
- [x] `DbVariableState`, nothing to do.

relates to #8884

**Comment by oleschoenburg** [comment]
Changing `DbTimerInstanceState` to use a foreign key to element instances will be tricky. If I understand correctly, the timer is created before the element is created. Actually, the elementInstanceKey is first set to -1. I'm not sure if and how we could change this.

**Comment by oleschoenburg** [comment]
There's not much to do for `DbProcessState` except that `ZbColumnFamilies.PROCESS_CACHE_DIGEST_BY_ID` should use a `processId` that exists in `ZbColumnFamilies.PROCESS_CACHE_BY_ID_AND_VERSION`. But `ZbColumnFamilies.PROCESS_CACHE_BY_ID_AND_VERSION` uses a composite key (process id and version), which is not expressible with `DbForeignKey`.

**Comment by oleschoenburg** [comment]
For `DbElementInstance` there are two problems:

In `ZbColumnFamilies.ELEMENT_INSTANCE_PARENT_CHILD`, `parentKey` should point to an existing element instance so we could use a foreign key there _except_ if there is no parent which is represented with a `-1`.

`ZbColumnFamilies.AWAIT_WORKLOW_RESULT` should also use a foreign key to point to an existing element instance but it can't because (apparently) the await metadata is set before the coresponding process instance is created.

**Comment by pihme** [comment]
> I think for `DbMessageSubscriptionState`'s `elementInstanceKey` we can't use a foreign key that points to `ZbColumnFamilies.ELEMENT_INSTANCE_KEY`. If I try that, there are a lot of failing tests. From the look of it, the message subscription is created before the element instance is inserted. Does that make sense to you @pihme?

Can you verify that these failing tests are based on a multi partition setup? If that is the case, it does make sense, because then the element instance of that key lives in another partition. If the tests are single partition, we should look deeper what is going on.

**Comment by oleschoenburg** [comment]
> Can you verify that these failing tests are based on a multi partition setup?

That seems to be the case :+1: So my reasoning was wrong, but the result is the same: we can't use foreign keys for `DbMessageSubscriptionState`'s `elementInstanceKey`.

**Comment by oleschoenburg** [comment]
@pihme Almost done! I'm lacking a bit of context to assess whether we could or should foreign keys in `DbMigrationState`. Is that something you could look into for me? :bow:

**Comment by pihme** [comment]
> @pihme Almost done! I'm lacking a bit of context to assess whether we could or should foreign keys in `DbMigrationState`. Is that something you could look into for me? bow

Let's discuss this together. I had a look. I don't think we need to do anything. I am also reluctant to make any changes here, because this happens before normal stream processing. So exceptions here, and their escalation would be fatal.

At the same time, we need to make sure not to add inconsistencies during the migration. 

In any case, I want to discuss it with, state my reasoning and then you can play devil's advocate.
