### ISSUE TITLE
Batch upload with zbctl does not initiate message subscriptions

### ISSUE THREAD

**Issue by sebakerckhof** [camunda/zeebe#8934]
**Describe the bug**

If I do a batch upload with zbctl, and some of the processes have a start message, no message subscriptions are made.
If I do a single upload with zbctl, it works correctly

**To Reproduce**
Have a couple of bpmn's, at least one with a message start event.

Upload them with zbctl using a glob pattern:
`zbctl deploy *.bpmn`.

They are getting deployed successfully, but there are no message subscriptions for the message start events.

**Expected behavior**

There should be subscriptions for the message start events.

**Environment:**
- OS: Ubuntu 21.10 
- Zeebe Version: 1.3.0 / zbctl 1.3.3

**Comment by npepinpe** [comment]
@remcowesterhoud - please reproduce and do minimal root causing as other medic issues (~2h)

**Comment by Zelldon** [comment]
I would close this because we were not able to reproduce it and lack of activity
