### ISSUE TITLE
Feel error are causing bad user experiences

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8938]
**Describe the bug**

I run into this issue now several time. This time again I created a feel expression and deployed the model successfully. 

Expression:

```
=date an time ("2022-03-21T11:15:00@Europe/Berlin") - now()
```

Creating the instance works, but cause an incident. From the incident message it is totally unclear what is going on or what is wrong.

```
Expected result of the expression 'date an time ("2022-03-21T11:15:00@Europe/Berlin") - now()' to be one of '[DURATION, PERIOD, STRING]', but was 'NULL'
```

If we take a look in the google console log we can see the real issue, [which is simply ignored](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22integration-worker-1%22%0Aresource.labels.namespace_name%3D%22061e827f-c1f1-486e-b9f7-263a1efdaedb-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22;cursorTimestamp=2022-03-21T10:06:05.543376569Z?project=camunda-cloud-240911) :imp: 

```
 "Suppressed failure: no function found with name 'date an time' and 1 parameters"
```

Here it might be easy to spot, but if users have bigger feel expression or more complex ones it might be not that simple. It is frustrating to find that issue, especially if an user has no access to the logs. 

This is also more problematic if this values is later only consumes by some jobs and cause more issues, and is not visible as incident.

**To Reproduce**

Create process model with an invalid feel expression.

**Expected behavior**

We create incidents for failed feel expression evaluation with a clear message, similar to the log message.

**Environment:**
- Zeebe Version: 1.3.5
- Configuration:

**Comment by Zelldon** [comment]
This caused for example also this https://camunda.slack.com/archives/C034N0E5YCX/p1647857272889399

**Comment by saig0** [comment]
Related feature request in the FEEL engine: https://github.com/camunda/feel-scala/issues/260

**Comment by saig0** [comment]
With the new version of the FEEL engine (1.17.0), we could improve the UX. The new API doesn't return only the evaluation result but also potential warnings. We could append these warnings in the incident message to help the user to solve the problem. 

For example, instead of creating an incident with the message:

```
Expected result of the expression 'date an time ("2022-03-21T11:15:00@Europe/Berlin") - now()' to be one of '[DURATION, PERIOD, STRING]', but was 'NULL'
```

We could create an incident with the following message:

```
Expected result of the expression 'date an time ("2022-03-21T11:15:00@Europe/Berlin") - now()' to be one of '[DURATION, PERIOD, STRING]', but was 'NULL'. 
The evaluation reported the following warnings:  [NO_FUNCTION_FOUND] No function found with name 'date an time' and 1 parameters; [INVALID_TYPE] Can't subtract '2023-09-25T12:00:43.591630872@Etc/UTC' from 'null'
```

---

cc: @aleksander-dytko
