### ISSUE TITLE
How to start exporting from a specified position?

### ISSUE THREAD

**Issue by wuchuanron** [camunda/zeebe#8951]
Whenever the zeebe engine restarts, the export will start from scratch, which will seriously affect the startup speed. I try to use the "controller.updateLastExportedRecordPosition" method to set the latest successful export position. I hope that the next startup can start exporting from this position, but it has no effect. What should I do?

**Comment by Zelldon** [comment]
Hey @wuchuanron 

in order to be able to restart from the last position the broker need to take a snapshot first. Did you configured a snapshot interval or do you use the default?

**Comment by wuchuanron** [comment]
![image](https://user-images.githubusercontent.com/52146014/159449876-c32a436b-1de5-4b84-904b-d8fee563ed97.png)
Here is my config file, are you talking about the "zeebe.broker.data.snapshotPeriod" parameter?

**Comment by Zelldon** [comment]
Hey @wuchuanron this is exactly the property I meant sorry for the confusion. 

The value you're using is not valid. Please take a look here regarding the time format https://github.com/camunda-cloud/zeebe/blob/main/dist/src/main/config/broker.standalone.yaml.template#L22-L27

Is there anything logged regarding the value? Errors? Can you share the begin of your log? Normally the config is printed again.

**Comment by wuchuanron** [comment]
At present, the snapshot can be generated normally, but the setting of the last update location still does not take effect.
![image](https://user-images.githubusercontent.com/52146014/159634291-8b90e6c2-dd17-49b8-8741-2ee16a892b75.png)

**Comment by Zelldon** [comment]
@deepthidevaki how can it happen that the term and index is zero look at https://github.com/camunda-cloud/zeebe/issues/8951#issuecomment-1075952706  ? :thinking:

**Comment by deepthidevaki** [comment]
>  how can it happen that the term and index is zero look at [#8951 (comment)](https://github.com/camunda-cloud/zeebe/issues/8951#issuecomment-1075952706) ? thinking

This is to allow taking snapshots when nothing is exported. See https://github.com/camunda-cloud/zeebe/issues/7978#issuecomment-963102498

**Comment by Zelldon** [comment]
But this speaks about export position right? Which is the last number or not? I would somehow expect index and term (which are the two numbers at the begin) are set. What am I missing?

**Comment by deepthidevaki** [comment]
> But this speaks about export position right? Which is the last number or not? I would somehow expect index and term (which are the two numbers at the begin) are set. What am I missing?

The index must be 0 because we shouldn't compact anything. Term is 0 because we cannot get a valid term without having a valid index. So as long as nothing is exported snapshot Id will be 0-0-processedPosition-0.

**Comment by Zelldon** [comment]
Good to know. The linked comment  made this not really clear to me thanks @deepthidevaki. :+1: Ok so we need to find out way the exporter position is not updated.

@wuchuanron can you give us more details on your exporter? Maybe share the code? Do you see any errors in the logs? Can you see that the exporter was configured and started at the begin?

**Comment by wuchuanron** [comment]
Here is the code for my exporter.No other errors are seen in the log, the exporter can also export the data, but it starts from the first position each time.
`package com.sw.cs.zeebe;

import com.google.common.base.Strings;
import io.camunda.zeebe.exporter.api.Exporter;
import io.camunda.zeebe.exporter.api.context.Context;
import io.camunda.zeebe.exporter.api.context.Controller;
import io.camunda.zeebe.protocol.record.Record;
import io.camunda.zeebe.protocol.record.intent.DeploymentIntent;
import io.camunda.zeebe.protocol.record.intent.ProcessInstanceCreationIntent;
import io.camunda.zeebe.protocol.record.intent.ProcessInstanceIntent;
import io.camunda.zeebe.protocol.record.value.JobRecordValue;
import io.camunda.zeebe.protocol.record.value.ProcessInstanceRecordValue;
import models.com.sw.cs.flow.runtime.ElementInstance;
import models.com.sw.cs.flow.runtime.FlowInstance;
import models.com.sw.cs.flow.runtime.InstanceExt;
import models.com.sw.cs.flow.runtime.Job;
import org.hibernate.cfg.Configuration;
import org.reflections.Reflections;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.persistence.*;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import static io.camunda.zeebe.protocol.Protocol.DEPLOYMENT_PARTITION;
import static io.camunda.zeebe.protocol.record.RecordType.EVENT;
import static io.camunda.zeebe.protocol.record.ValueType.*;
import static models.com.sw.cs.flow.runtime.FlowInstance.*;

public class DbExporter implements Exporter {

    Logger logger = LoggerFactory.getLogger(DbExporter.class);

    private EntityManagerFactory emf;
    private Controller controller;

    private long lastPosition = -1;

    @Override
    public void configure(Context context) {
        logger.info("====== zeebe DbExporter.configure");

        Map<String, Object> args = context.getConfiguration().getArguments();

        if (args != null) {
            emf = (EntityManagerFactory) args.get("EC_EMF");
        }

        if (emf == null) {
            logger.info("EntityManagerFactory not set, start init jpa env");

            String cfgPath = (String) args.get("cfg");
            if (Strings.isNullOrEmpty(cfgPath)) {
                throw new RuntimeException("zeebe DbExporter arg cfg not set");
            }
            Configuration config = new Configuration().configure(Path.of(cfgPath).toFile());
            // FIXME: liuji use play config instead of hard coded refs packages
            Reflections refs = new Reflections("models", this.getClass().getClassLoader());
            refs.getTypesAnnotatedWith(Entity.class)
                    .forEach(c -> {
                        if (logger.isTraceEnabled()) {
                            logger.trace("+++ load entity: {}", c.getName());
                        }
                        config.addAnnotatedClass(c);
                    });

            emf = Persistence.createEntityManagerFactory("default");
        }
    }

    @Override
    public void open(Controller controller) {
        logger.info("====== zeebe open");
        this.controller = controller;
    }

    @Override
    public void close() {
        logger.info("====== zeebe close");
        try {
            flush();
        } catch (final Exception e) {
            logger.error("Failed to flush records before closing exporter.", e);
        }

    }

    @Override
    public void export(Record record) {
//        logger.info("====== zeebe export, record type:{}, value type:{}", record.getRecordType(), record.getValueType());

        if (record.getRecordType().equals(EVENT)
                && record.getValueType().equals(DEPLOYMENT)
                && record.getIntent().equals(DeploymentIntent.CREATED)
                && record.getPartitionId() == DEPLOYMENT_PARTITION) {
            if (logger.isTraceEnabled()) {
                logger.trace("record type {}, valueType {}, intent {}, intent value {}",
                        record.getRecordType(), record.getValueType(), record.getIntent(), record.getIntent().value());
                logger.trace("record {}", record.toJson());
            }

            exportDeploy(record);

        }
        if (record.getRecordType().equals(EVENT)
                && record.getValueType().equals(PROCESS_INSTANCE_CREATION)
                && record.getIntent().equals(ProcessInstanceCreationIntent.CREATED)) {
            if (logger.isTraceEnabled()) {
                logger.trace("record type {}, valuetype {}, intent {}, intent value {}",
                        record.getRecordType(), record.getValueType(), record.getIntent(), record.getIntent().value());
                logger.trace("record {}", record.toJson());
            }

//                exportFlowInstance(record);

        }
        if (record.getRecordType().equals(EVENT)
                && record.getValueType().equals(PROCESS_INSTANCE)) {
            if (logger.isTraceEnabled()) {
                logger.trace("record type {}, valuetype {}, intent {}, intent value {}",
                        record.getRecordType(), record.getValueType(), record.getIntent(), record.getIntent().value());
                logger.trace("record {}", record.toJson());
            }

            exportInstance(record);

        }
        if (record.getValueType().equals(JOB)) {
            if (logger.isDebugEnabled()) {
                logger.debug("record type {}, valuetype {}, intent {}, intent value {}",
                        record.getRecordType(), record.getValueType(), record.getIntent(), record.getIntent().value());
                logger.debug("record {}", record.toJson());
            }
            exportJob(record);
        } else {
            logger.debug("ignore record type {}, valueType {}", record.getRecordType(), record.getValueType());
        }

        lastPosition = record.getPosition();
    }

    private void flush() {
        logger.info("====== zeebe update lastPosition:{}", lastPosition);
        controller.updateLastExportedRecordPosition(lastPosition);
    }

    private void exportJob(Record record) {
        if (logger.isTraceEnabled()) {
            logger.trace("====== exportJob");
        }

        logger.info("====== export job, position:{}", record.getPosition());

        JobRecordValue value = (JobRecordValue) record.getValue();

        Job job = new Job();
        job.setId(record.getKey());
        job.setElementInstanceKey(value.getElementInstanceKey());
        job.setJobType(value.getType());
        job.setState(record.getIntent().name().toLowerCase());
        job.setTimestamp(record.getTimestamp());
        job.setRetries(value.getRetries());
        job.setWorker(value.getWorker());
        job.setWorkflowInstanceKey(value.getProcessInstanceKey());
        job.setElementId(value.getElementId());
        job.setWorkflowKey(value.getProcessDefinitionKey());
        Map<String, String> headers = value.getCustomHeaders();
        for(Map.Entry<String, String> entry : headers.entrySet()){
            String mapKey = entry.getKey();
            if (Objects.equals(mapKey,"description")){
                job.setElementName(entry.getValue());
            }
        }
        addOrUpdateEntity(Job.class, job, job.getId());
//        if (Objects.equals(job.getState(),"activated") && Objects.equals(value.getType(),"archive")){
//            updateInstanceExt(record);  //更新流程实例当前环节
//        }
    }

    private void updateInstanceExt(Record record){
        JobRecordValue value = (JobRecordValue) record.getValue();
        EntityManager entityManager = emf.createEntityManager();
        EntityTransaction transaction = entityManager.getTransaction();
        final Map<String, String> customHeaders = value.getCustomHeaders();
        final String description = customHeaders.getOrDefault("description", "");
        final String externalUrl =  customHeaders.getOrDefault("externalUrl", null);
        transaction.begin();
        try {
            Query query = entityManager.createQuery("select f from InstanceExt f where f.instanceKey="+ value.getProcessInstanceKey() +"");
            List instanceExts = query.getResultList();
            if (!instanceExts.isEmpty()){
                InstanceExt instanceExt = (InstanceExt) instanceExts.get(0);
                instanceExt.setCurrentStepName(value.getElementId());
                instanceExt.setCurrentStepDescription(description);
                instanceExt.setCurrentStepExternalUrl(externalUrl);
                instanceExt.setCurrentTaskKey(record.getKey());
                instanceExt.setCurrentTaskId(null);
                entityManager.merge(instanceExt);
                entityManager.flush();
            }

            transaction.commit();
        }
        catch (Exception e) {
            logger.error("updateInstanceExt failed", e);
            transaction.rollback();
        }
    }

    private void exportInstance(Record record) {

        ProcessInstanceRecordValue value = (ProcessInstanceRecordValue) record.getValue();
        if (record.getKey() == value.getProcessInstanceKey()) {
            exportFlowInstance(record);
        } else {
            exportElement(record);
        }
    }

    private <T, k> void addOrUpdateEntity(Class<T> clazz, T entity, k id) {


        EntityManager entityManager = emf.createEntityManager();
        EntityTransaction transaction = entityManager.getTransaction();

        try {
            transaction.begin();

            T existedEntity = entityManager.find(clazz, id);
            if (existedEntity == null) {
                entityManager.persist(entity);
            } else {
                entityManager.merge(entity);
            }

            transaction.commit();
        } catch (Exception e) {
            logger.error("export to db failed", e);
            transaction.rollback();
        } finally {
            entityManager.close();
        }

    }

    private void exportElement(Record record) {
        logger.info("====== export element, position:{}", record.getPosition());

        ProcessInstanceRecordValue value = (ProcessInstanceRecordValue) record.getValue();
        if (Objects.equals(value.getElementId(),"ryba_submit"))
            logger.trace("");
        ElementInstance ei = new ElementInstance();
        ei.setId(record.getPosition());
        ei.setBpmnElementType(value.getBpmnElementType().name());
        ei.setElementId(value.getElementId());
        ei.setIntent(record.getIntent().name());
        ei.setWorkflowInstanceKey(value.getProcessInstanceKey());
        ei.setFlowScopeKey(value.getFlowScopeKey());
        ei.setWorkflowKey(value.getProcessDefinitionKey());
        ei.setPartitionId(record.getPartitionId());
        ei.setTimestamp(record.getTimestamp());

        addOrUpdateEntity(ElementInstance.class, ei, ei.getId());
    }

    private void exportFlowInstance(Record record) {
        logger.info("====== export flow instance, position:{}", record.getPosition());

        ProcessInstanceRecordValue value = (ProcessInstanceRecordValue) record.getValue();

        EntityManager entityManager = emf.createEntityManager();
        EntityTransaction transaction = entityManager.getTransaction();

        transaction.begin();

        try {
            FlowInstance dbInstance = entityManager.find(FlowInstance.class, value.getProcessInstanceKey());
            FlowInstance fi = new FlowInstance();
            fi.setId(value.getProcessInstanceKey());
            fi.setBpmnProcessId(value.getBpmnProcessId());
            fi.setWorkflowKey(value.getProcessDefinitionKey());
            fi.setVersion(value.getVersion());
            fi.setParentElementInstanceKey(value.getParentElementInstanceKey());
            fi.setParentWorkflowInstanceKey(value.getParentProcessInstanceKey());
            if (dbInstance!=null){
                fi.setStartTime(dbInstance.getStartTime());
            }
            if (record.getIntent().equals(ProcessInstanceIntent.ELEMENT_ACTIVATED)) {
                fi.setState(STATE_ACTIVITE);
                fi.setStartTime(record.getTimestamp());
            } else if (record.getIntent().equals(ProcessInstanceIntent.ELEMENT_COMPLETED)) {
                fi.setState(STATE_COMPLETED);
                fi.setEndTime(record.getTimestamp());
            } else if (record.getIntent().equals(ProcessInstanceIntent.ELEMENT_TERMINATED)) {
                fi.setState(STATE_TERMINATED);
                fi.setEndTime(record.getTimestamp());
            }

            addOrUpdateEntity(FlowInstance.class, fi, fi.getId());

            transaction.commit();
        } catch (Exception ex) {
            logger.error("");
            transaction.rollback();
        }


    }

    private void exportDeploy(final Record record) {

        logger.trace("====== exportDeploy");
// 流程发布时有维护flow表，这里不再重复导出
//        DeploymentRecordValue value = (DeploymentRecordValue) record.getValue();
//
//        EntityManager entityManager = emf.createEntityManager();
//        EntityTransaction transaction = entityManager.getTransaction();
//
//        transaction.begin();
//
//        try {
//            value.getResources().forEach(r -> {
//                value.getDeployedWorkflows().stream().filter(f -> f.getResourceName().equals(r.getResourceName()))
//                        .forEach(f -> {
//                            Query query = entityManager.createQuery("select f from Flow f where f.workflowKey="+f.getWorkflowKey()+"");
//                            List<Flow> list = query.getResultList();
//                            if (list.size() == 0){
//                                Flow flow = new Flow();
//                                flow.setBpmnProcessId(f.getBpmnProcessId());
//                                if (f.getResourceName().indexOf(".") > 0){
//                                    flow.setName(f.getResourceName().substring(0,f.getResourceName().indexOf(".")));
//                                }
//                                else
//                                    flow.setName(f.getResourceName());
//                                flow.setDefKey(f.getBpmnProcessId());
//                                flow.setDefVersion(f.getVersion());
//                                flow.setPosition(record.getPosition());
//                                flow.setResourceName(f.getResourceName());
//                                flow.setResource(new String(r.getResource(), Charset.forName("UTF-8")));
//                                flow.setTimestamp(record.getTimestamp());
//                                flow.setWorkflowKey(f.getWorkflowKey());
//                                flow.setVersion(f.getVersion());
//                                entityManager.persist(flow);
//                            }
//                        });
//            });
//
//            transaction.commit();
//        } catch (Exception e) {
//            logger.error("export to db failed", e);
//            transaction.rollback();
//        }
    }
}
`

**Comment by romansmirnov** [comment]
@Zelldon, I hope that's okay if I chime in here.

@wuchuanron, thanks for sharing the exporter code. According to the code, the last exported record position is only updated, when the exporter gets closed:

```
    @Override
    public void close() {
        logger.info("====== zeebe close");
        try {
            flush();
        } catch (final Exception e) {
            logger.error("Failed to flush records before closing exporter.", e);
        }
    }

    private void flush() {
        logger.info("====== zeebe update lastPosition:{}", lastPosition);
        controller.updateLastExportedRecordPosition(lastPosition);
    }
```

As a consequence, as long as the exporter is running the last exported position is never updated in the controller, and hence in the runtime database. That means, whenever a snapshot is created, the last exported snapshot position remains `-1` resulting in a snapshot id `0-0-xyz-0`.

Additionally, whenever Zeebe restarts it will install the last snapshot, but that last snapshot still has set `-1` as the last exported snapshot position. That means, updating the last exported record position on close does not have any effect.

A solution to this would be to update the last exported record position regularly, for example, as it is done with elasticsearch exporter:

https://github.com/camunda/zeebe/blob/8ed6a5012d63155659ff8e4c79a6fba53d351955/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java#L134-L137

and 

https://github.com/camunda/zeebe/blob/8ed6a5012d63155659ff8e4c79a6fba53d351955/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java#L51-L58

In addition to it, the exporter to the DB should be idempotent because after a restart it might happen that already exported records are exported once again.

Does it help?

**Comment by wuchuanron** [comment]
Finally, it can be updated correctly, and the snapshot can be created normally. @romansmirnov Your method is very effective, thank you for everyone's help.

**Comment by Zelldon** [comment]
Thanks @romansmirnov :) had no time yesterday to check the code so thanks that you did it :) :+1: 

Happy that it works now @wuchuanron thanks for coming back to us :) So I will close this issue.
