### ISSUE TITLE
Split grafana dashboard into two

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#8998]
**Description**

This came up as part of  [the game day](https://confluence.camunda.com/pages/viewpage.action?spaceKey=ZEEBE&title=2022-03-23+Game+Day)

1. [x] To reduce the cognitive overload we should provide a dashboard with only a general overview. It should be easy for some one without internal knowledge of zeebe to understand the overall health of the system. For example, a support engineer can use this to get an initial understanding before delegating it to the right team.
2. The second dashboard will contain more detailed metrics which a zeebe engineer can make sense of. (Optionally, we can also split this further into multiple dashboards -- for example rocksdb metrics or latency metrics are mostly useful if we are investigating performance issues). 

This would be helpful in maintaining the right balance between reducing the cognitive overload and providing necessary metrics for detailed investigation.

**Comment by RobertRad** [comment]
Such a split would also help people, who are getting deeper and deeper into Zeebe.
After understanding all the parts of the first dashboard, one would be able to track down, how its data relates to the detail data from the second dashboard.

At the moment the information on the dashboard is kind of overwhelming :)

**Comment by Zelldon** [comment]
@RobertRad might make sense for you to use the overview dashboard which was created recently to not overwhelm people :)

**Comment by RobertRad** [comment]
Ok, it seems I have to get more into that

**Comment by Zelldon** [comment]
I would say this is done via https://github.com/camunda/zeebe/pull/9067 please reopen if you see that we need to improve it.
