### ISSUE TITLE
Potential memory leak in CW 12/13

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9023]
**Describe the bug**

Taking a look at the current week benchmark it looks like we have a potential memory leak. 

![memory-leak](https://user-images.githubusercontent.com/2758593/160775822-ce6b518b-ae5a-478c-be47-9db1f480c391.png)

It seems that we can free up some memory from time to time, but it is never smaller than the previous bump (it is slowly increasing). 

In general the memory usage is unexpected high and near to the limits

![memoryhigh](https://user-images.githubusercontent.com/2758593/160775955-d0d54946-8abc-4588-8714-36b0f4156fcb.png)

This seems to happen already on previous weekly benchmarks, but was not detected ? :thinking: 

I think it is related to followers, the graphs I checked were from followers at least. 

**To Reproduce**

Run a benchmark over a longer period of time.

**Expected behavior**

Memory can be freed and the graphs are not increasing over time.

**Environment:**
- OS: 
- Zeebe Version: cw 12 + 13
- Configuration:

**Comment by Zelldon** [comment]
It shows also in the latest stable benchmarks (1.3.x), which has been updated to our recent release candidate. 

![mem](https://user-images.githubusercontent.com/2758593/161001767-c7e087b1-56a2-4e90-b010-aa14d724345a.png)

We have a different memory pattern, which also causes to kill our pods. Interesting is that we use less java memory, but we see more GC's.

**Comment by romansmirnov** [comment]
Might be related to #8509

**Comment by npepinpe** [comment]
I would propose to focus on #8509 as we have some idea of the causes before tackling this.

**Comment by deepthidevaki** [comment]
OOMKills are happening in CW16 benchmark. 

![image](https://user-images.githubusercontent.com/1997478/164619866-cb3b8e0a-d9f5-4b2b-a4e2-d38855b2c958.png)

zeebe-1 was leader before the pod went OOM.
![image](https://user-images.githubusercontent.com/1997478/164619910-8cda73f8-f939-418b-9277-c42b27d3d5a7.png)
![image](https://user-images.githubusercontent.com/1997478/164619934-5dfa021c-77b3-46df-b7e7-777ef0efbfdb.png)
![image](https://user-images.githubusercontent.com/1997478/164624653-246982a4-fbec-4799-a835-438bac28020e.png)
