### ISSUE TITLE
GHA: Publish test reports

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9035]
**Description**

It'd be nice to collect and publish the test results of running integration and unit tests from our GHA workflow so that developers can see exactly which tests are failing.

There are multiple actions that implement this:
1. https://github.com/marketplace/actions/publish-unit-test-results
2. https://github.com/marketplace/actions/surefire-report
3. https://github.com/marketplace/actions/junit-report-action

I've tried all three of them already. The first one is probably our best bet since it is the most feature complete. Two and three run into OOM for some of our tests.

follow-up of https://github.com/camunda/zeebe/pull/8968

**Comment by oleschoenburg** [comment]
There's also this new feature to generate markdown job summaries: https://github.blog/changelog/2022-05-09-github-actions-enhance-your-actions-with-job-summaries/

**Comment by korthout** [comment]
@oleschoenburg that would be great to have. I propose to not spend time to build that ourselves, but instead let the GHA implement that part. Seems our test reporter of choice is also already aware of the new functionality. https://github.com/EnricoMi/publish-unit-test-result-action/issues/264
