### ISSUE TITLE
Make new overview dashboard available in zeebe [+long running] cluster

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9075]
**Description**

We created a new overview dashboard here https://github.com/camunda/zeebe/pull/9067 and we should make it available in our clusters. I was not able to update the prometheus operator. This is blocked by https://github.com/camunda/zeebe/issues/9074

**Comment by npepinpe** [comment]
This should be easy to add next to the existing dashboard, and probably isn't blocked by #9074
