### ISSUE TITLE
Backport grpc version update (to 1.45.1) to 8.0.x

### ISSUE THREAD

**Issue by berndruecker** [camunda/zeebe#9085]
With grpc 1.45.0 there is a bug in grpc-netty which hits spring-zeebe + embedded in-memory test engine. Currently I manually updated the lib there(https://github.com/camunda-community-hub/spring-zeebe/blob/master/test/embedded/pom.xml#L48), but it would be better fixed in 8.0.1 of the zeebe-client.

**Comment by npepinpe** [comment]
Fixed by with #9086 - it will be released next month with 8.0.1.
