### ISSUE TITLE
Analysis fails in stable/1.0 and 1.1

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9090]
**Description**

In these two stable branches the analysis fails, because `analyse-java.sh` still references `develop` branch.

Not sure if this is supposed to be fixed, or if those branches get reitred.

**Comment by npepinpe** [comment]
That's a good question. I would say to keep them in case we need to build anything...however, we have the tags should we ever need to recreate a build - we could create a new stable branch on demand from a tag, update the version, and build a new release (if we really needed it). Would that be enough? In that case we could delete these branches.

I wonder if I'm forgetting anything... :thinking:

**Comment by npepinpe** [comment]
Self assigning but I'll leave it in the backlog - my proposal would be to delete the branches themselves for unsupported versions. I'll bring it up to the team - if we go with this we can close this issue.

**Comment by menski** [comment]
@menski to check if this is still an issue and how to move forward

**Comment by Zelldon** [comment]
These versions are no longer supported. I will close this, since we also moved to gha
