### ISSUE TITLE
License Maven Plugin doesn't accept header with 2022 copyright

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9102]
**Description**
* Create a new file in `protocol/test/java/io.camunda.zeebe.protocol.record.intent;` (probably also other paths; 
* This will get a header test which looks ok. And it has the year 2022 as copyright year
* Run `mvn com.mycila:license-maven-plugin:4.1:check`
* The plugin will mark it as failure
* Change 2022 to 2017 
* Now it will pass

**Comment by npepinpe** [comment]
It looks like by default the year property of the license header is replaced with the project's inception year, see:

https://github.com/mathieucarbou/license-maven-plugin/blob/08bf43233b51e377ae4609ef09eb3b3bb384ecc0/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java#L753

So whenever it does a check, the license header is compared against one which would have 2017 in its header. So any other value will always fail, not just 2022. 

I have asked legal about this (i.e. keep inception year or use file creation). If we need to use the file creation year then this could be an issue as mycila doesn't easily support this out of the box without using the git plugin. Let's see.

**Comment by npepinpe** [comment]
So we will stay with the inception year. The only place we update copyright years are in the `NOTICE.txt` in the root of the project. So with this, it makes sense for me that the check fails when the inception year is different. The one difference is with Atomix files, which are dual licensed, so they have the old Onos license and ours from 2020 (when we added the new notice for them).
