### ISSUE TITLE
Understand consistency requirements of Operate backup

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9105]
* Understand the consistency requirement of operate data alone
* Understand the consistency between zeebe and operate data

This would help us if we can rely on elasticsearch snapshot, what should be coordinated between zeebe backups and operate backups.

**Comment by sdorokhova** [comment]
Since import in Operate works similar to Optimize, these two comments are also valid for Operate:
https://github.com/camunda/zeebe/issues/9106#issuecomment-1097684586
https://github.com/camunda/zeebe/issues/9106#issuecomment-1097688129

**Comment by sdorokhova** [comment]
**Taking snapshot during version upgrade**

Operate stores data migration progress in `migration-steps-repository` index. Therefore potential inconsistency during snapshot creation can happen, when we recorded some migration step as performed but the real migration is not reflected in the snapshot. E.g.:
* backup of index `entity-x.y` is taken
* Operate creates index with new version `entity-x.y+1`, reindexes the data and removes old index `entity-x.y`
* Operate records in `migration-steps-repository` that migration of index `entity` was successfully performed
* backup of index `migration-steps-repository` happens

After restoring of such snapshot, Operate will create the new index on startup, but won't migrate the data as migration is kind of already performed. I would expect then that Operate will fail to start up complaining that there are two indices of different versions for `entity`.

**Comment by sdorokhova** [comment]
*Creating of batch operation*

When the user performs some operation (cancel/retry) on one or several process instances, we create records in indices `batch-operation` and `operation` and also update `list-view` index to store the reference to the operation. Potential inconsistency may happen in case of partial data snapshot (e.g. references are stored in `list-view`, but not represented in `operation` and `batch-operation` index, or `operation` contains data, but not the other indices). These king of inconsistencies may lead to some glitches in UI, e.g. infinite spinners, never finished operation etc., but should not affect the functionality seriously.

**Comment by deepthidevaki** [comment]
> **Case 3. Data duplication**
> 
>     * backup of "main" index from IndexList, e.g. `variable`
> 
>     * archive the data, e.g. reindex/delete data from `variable` to `variable_2022-04-27`
> 
>     * backup of dated index index
>       If restoring from such a snapshot. we will have data duplicated in "main" and dated indices, which may break some read queries, as both "main" and dated indices are included in one alias and we will have 2 records with one id inside such an alias.

@sdorokhova How bad is this situation? This scenario can happen now also if the system crashes during the archiving operation, right? As far as I understood it archiving is not a single operation, so the system can crash in between.

**Comment by deepthidevaki** [comment]
> Taking snapshot during version upgrade

Is the migration idempotent? If the record exists in both version, is that a problem?

**Comment by deepthidevaki** [comment]
> **Post import for incidents**
> 
> Import of incidents is performed in two steps:
> 
> 1. Store/update incident with `pending=true` and report successful import (write import position)
> 
> 2. Process pending incidents, updating several indices (`list-view`, `flow-node-instance` and `incident`) and marking incidents with `pending=false`

Here do you update anything else in `incident` other than marking it as `pending=false`?

**Comment by deepthidevaki** [comment]
> I actually wanted to discuss this "restart" topic once again. Regarding the system crashing, you mean on Elasticsearch side, right? I had a feeling that we don't need to worry about this and Elastic should take care of such cases. Am I too naïve? I mean if on Operate side we received the response, that some data was successfully stored, I would expect it to be there even after ELS crashing. The opposite - when data was stored but we did not receive the answer should be also safe, as most of our operations are idempotent and we will just retry.

@sdorokhova 

If Operate receives a response, it is guaranteed that the data was successfully stored. I'm considering the following scenario:
For archiving, you have to do multiple operations. For example, to move a document from one index to another, you have to add the document to the new index and then delete from the old. After executing the first operation (add to new index), the system - either Elasticsearch or Operate can crash/restart. In that case the document is both in the new index and old index. This would not happen if deleting or reindexing is a single or atomic operation.

> Currently we adapted the system to be able to process some of the duplications

:+1:

**Comment by sdorokhova** [comment]
@deepthidevaki 

> If Operate receives a response, it is guaranteed that the data was successfully stored. I'm considering the following scenario:
> For archiving, you have to do multiple operations. For example, to move a document from one index to another, you have to add the document to the new index and then delete from the old. After executing the first operation (add to new index), the system - either Elasticsearch or Operate can crash/restart. In that case the document is both in the new index and old index. This would not happen if reindexing is a single or atomic operation.

Ah, yeah, I see your point. But such duplications are kind of temporary, as we always perform the delete of finished process instance as a last step. This means that after the system recovered the same process instances will be picked again by archiver and all the duplications will be "fixed".

In case of some "wrong" order of snapshot taking process, we may have the process instance deleted from "main" index, but other data duplicated. Is it possible? May be I described the case not precisely enough. Let me try.
* backup of "main" index from IndexList, e.g. `variable`
* archive the data, e.g. reindex/delete data from `variable` to `variable_2022-04-27`
* (ADDED) archive the process instance, e.g. eindex/delete data from `list-view` to `list-view_2022-04-27`
* backup of `list-view` and dated indices

Since the `list-view` index was included in backup after `delete` query, data duplication won't be fixed ever.

**Comment by deepthidevaki** [comment]
Thanks @sdorokhova. I got it now.

**Comment by deepthidevaki** [comment]
I will try to summarize the above requirements here:

**Post import for incidents:**
The dependency between indices are as follows. 

If the incident is marked as `pending=false` in `incident`, then the corresponding updated should be in `flownode-instance` and `list-view`. There are no dependency between flownode-instance and list-view. Also the reverse order is fine, if flownode-instance is updated and the `incident` is still `pending=true` this is fine because it will be processed again.

So if we take the backups in the order of these dependencies (downwards in the diagram), it would be consistent.

![image](https://user-images.githubusercontent.com/1997478/166897449-c0144caa-751f-4388-a0be-a3bbea614661.png)


**Archiving:**

If the instance is deleted from `list-view` then it should have added to `list-view-Dated`, and also should have deleted from the other indexLists and archived.

![image](https://user-images.githubusercontent.com/1997478/166897491-dd81dcdc-d926-424e-8199-6b99b57fa97e.png)

And the reverse order is ok. i.e If variable is already archived, but list-view is not updated, it is ok. Or if the record is added to `variable-dated` but not deleted from `variable` this is also ok. 


**Batch operations:**
I don't quite understand dependency between `batch-operations`, `operation` and `list-view`. @sdorokhova

**Comment by sdorokhova** [comment]
@deepthidevaki 
Just to make it clear, for archiving we will also backup from top to bottom on your diagram, right?

Regarding **batch operations**, I don't think that we can avoid some inconsistencies, as we don't have any retry logic there. But I would propose to backup `batch-operations` as a last step, this way we will definitely have all the operations in Operations list even if they will be "empty" at the end. May be we should document possible inconsistencies in this part of software after data restore?

**Comment by deepthidevaki** [comment]
@sdorokhova I'm just summarizing our discussion here:

If we take backup in the order presented above, we have a circular dependency between `list-view` and `incident`. This is a Blocker!
- One way to solve this would be by pausing "archiving" during the backup process. But archiving is a critical to the performance of Operate. So pausing "archiving" may have an impact on Operate performance. 
- Other solution would involve removing this dependency with in Operate - that means changing how Operate manages its data.

**Comment by deepthidevaki** [comment]
@sdorokhova I guess now we have covered everything that affects the consistency of data in Operate backup. So I will close this issue. Next step is to find solutions for the problems we found.
