### ISSUE TITLE
Understand consistency requirements of Optimize backup

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9106]
- [ ] Understand the consistency requirement of Optimize data alone
 - [x] Understand the consistency between zeebe and Optimize data

This would help us to evaluate if we can rely on elasticsearch snapshot, what should be coordinated between zeebe backups and optimize backups

**Comment by deepthidevaki** [comment]
Here are the notes from discussion with @RomanJRW 

- There is an importer per partition per record type.
- Imported record is transformed into Optimize entities and stored in a seperate index.
- `last imported position` per importer is stored in a specific index.
- Importing is idempotent. It is ok to import the same record twice.
- Currently both exported zeebe records and optimize entities are stored in the same elasticsearch instance (although this can change in future.)

#### Potential causes of inconsistency in Optimize backup:
Note:- This won't be a problem if ElasticSearch snapshots guarantees any kind of consistency among multiple indices when taking a snapshot. But, from our basic knowledge there is no such guarantee. So we should assume that the following scenarios are possible. 

- Backup contains newer `last imported position`, but indices that store transformed optimize entities contains older data.
  This can happen if the following happens in the order
  1. Imports and transforms record X
  1. Backup of optimize entities is done
  1. Imports and transforms record X+1
  1. Update `last imported position` to X+1
  1. Backup of `last imported position` index is taken
  
    :warning:  This is problematic. If Optimize recovers from this backup, the entities for record X+1 does not exists in the state, but record X+1 is already marked as imported and won't be re-imported.

- Backup contains older `last imported position`, but indices that store transformed process instance data contains newer data.
  This can happen if the backup of `last imported position` index is taken *before* the backup of transformed data.
  1. Imports and transforms record X
  2. Backup of `last imported position` index is taken
  3. Imports and transforms record X+1
  4. Backup of transformed data is done
 
  :heavy_check_mark:  This is not problematic if the zeebe records in the backup is same as that are already processed. This is because Optimize importing is idempotent. It can re-import record X+1 without any issues.
  :warning: This is problematic if the backup does not contain the zeebe records that are already processed. In this case Optimize has some additional data, that is not there in zeebe. (See following comment about inconsistency between zeebe records and exported records)
  
Currently we don't see any potential cause for inconsistency among the indices for Optimize entities. But @RomanJRW will look into it and verify this.

**Comment by RomanJRW** [comment]
@deepthidevaki - Thanks for the excellent summary. This looks all correct to me. Some other points to note:

- If a snapshot is taken during an upgrade, this could result in Optimize breaking/unexpected behaviour resulting from the same presumed lack of guarantees from ES
- Optimize has more than one import index that would need be synchronised with other data. One is position based and relates to Zeebe data importing. The other is timestamp based and would be used (in cloud modes) for internal Optimize data processing

**Comment by deepthidevaki** [comment]
Thanks @RomanJRW 

> * If a snapshot is taken during an upgrade, this could result in Optimize breaking/unexpected behaviour resulting from the same presumed lack of guarantees from ES

Didn't you mention that there is already some check in Optimize to prevent this? 

> * Optimize has more than one import index that would need be synchronised with other data. One is position based and relates to Zeebe data importing. The other is timestamp based and would be used (in cloud modes) for internal Optimize data processing

Thanks. This is very important when taking backups.

**Comment by deepthidevaki** [comment]
I think we can close this now. @RomanJRW Please add new comments if you have any other insights or information.
