### ISSUE TITLE
Dependency error when running `mvn clean install`

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9116]
**Description**

When checking out a recent main (e.g. 16d0e6811228fa51e36ea96bc8fac4af6a78fb20) and running `mvn clean install` the build fails with a dependency error.
```
[INFO] --- maven-dependency-plugin:3.3.0:analyze-only (analyze-dependencies) @ zeebe-atomix-cluster ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[WARNING]    org.junit.vintage:junit-vintage-engine:jar:5.8.2:test
```
However, the same commit passes on Jenkins.

**Comment by npepinpe** [comment]
I think I know what the issue is. On Jenkins we build with the prepare offline profile which adds these to be ignored when unused (since it adds them to the list of dependencies for all projects).

I'll take a look.
