### ISSUE TITLE
Removing `Subscription` consumer re-registers the consumer instead of removing

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9123]
**Describe the bug**

https://github.com/camunda/zeebe/blob/1edfe4f762ef700885859bf87e1370963d3448a1/dispatcher/src/main/java/io/camunda/zeebe/dispatcher/Subscription.java#L83-L86

this should obviously be a call to `removeConsumer`, not `registerConsumer`. As far as I can tell this bug has existed since at least 2018. 

Removing a subscription consumer is triggered when an ActorTask is closed (successfully or due to failure).

**Comment by Zelldon** [comment]
Lol :laughing:

**Comment by npepinpe** [comment]
Love it :smile:

**Comment by npepinpe** [comment]
Seems like an low hanging fruit, let's just go ahead and fix it (unless there's no `actorConditions.removeConsumer`, or worse, we actually rely on this behavior :scream:)
