### ISSUE TITLE
GHA: Archive JVM dumps

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9129]
Since we are loading and using native code with RocksDB, the JVM can segfault and then generate dumps that we should archive for investigations. In our Jenkins Pipeline this seems to be implemented here: https://github.com/camunda/zeebe/blob/7abb2c0b1dfd7f20181848aee365658cd6e0d327/Jenkinsfile#L325

**Comment by oleschoenburg** [comment]
@npepinpe The `hs_err_*.log` files are the one you were talking about, right?

**Comment by npepinpe** [comment]
Yes, exactly. These are dumped when a segfault occurs, for example, and contain the stack trace so we can find what it was doing when it crashed. This hasn't happened in a while, but it can happen when playing with native memory/RocksDB.
