### ISSUE TITLE
GHA: Ensure that flaky tests fail the pipeline

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9134]
Since we've setup the flaky test detection in GHA a bit different compared to Jenkins, we should make sure that the pipeline fails if any flaky test was encountered.

We are using the great [flaky-test-extractor](https://github.com/zeebe-io/flaky-test-extractor-maven-plugin) plugin by @pihme to detect and label flaky tests. Let's make sure that `failBuild` is always enabled and the pipeline actually fails.

See also: https://github.com/zeebe-io/flaky-test-extractor-maven-plugin#how-can-i-configure-this-plugin

**Comment by oleschoenburg** [comment]
Here is a run that (I think) shows that flaky tests already fail the pipeline: https://github.com/camunda/zeebe/runs/6125043826?check_suite_focus=true

**Comment by remcowesterhoud** [comment]
This is what I was thinking as well, because we follow the default configuration which should fail the build. I guess we can close this issue?

**Comment by oleschoenburg** [comment]
Yeah, this seems fine to me. I think it was @npepinpe who was unsure if that's really the default behavior :+1:
