### ISSUE TITLE
Disable the Jenkins CI Pipeline

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9137]
Once we've made the switch to GHA, we should disable the Jenkins builds to save some resources :deciduous_tree: 
This might be configured on this GitHub repository or on Jenkins itself. We might also need assistance from the infrastructure team.

blocked by #9136

**Comment by Zelldon** [comment]
@oleschoenburg @npepinpe is this something we really want to do right now ? Afaik we wanted to use jenkins for releases until gha self-hosted is out of beta right? If this is the case I would propose to move it to the backlog.

**Comment by npepinpe** [comment]
We will still want to remove the testing pipeline, as it will needlessly run tests which still cost money/hardware. But it's not a blocker, and we'll probably want to run both pipelines in parallel for a little bit.

**Comment by npepinpe** [comment]
This issue is to disable automatically running the test pipeline in Jenkins, not Jenkins completely :smile: 

And running both in parallel, I would say, at least til the end of the quarter, just so we build some confidence and are sure we don't need to temporarily roll back.

**Comment by Zelldon** [comment]
Not sure the title is: Disable the Jenkins CI Pipeline :shrug: 

Ok thanks

**Comment by menski** [comment]
Notes from my sync with Ole:

We can only disable the check for the pull requests which go against `main` branch, as older branches are not supported by GitHub actions.

Alternative backport GitHub actions to stable branches, at least 1.3 and 8.0.

Right now GitHub actions only run on PRs, and special branches `stable`, `staging` etc., Assumption nobody cares.

Release job still in Jenkins, no plans to move right now, but in long term the goal is to get rid of it.
