### ISSUE TITLE
Remove Jenkins CI Pipeline leftovers

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9138]
We can clean up our Jenkins configuration, for example the Jenkinsfile and various scripts in the `.ci` folder.
We'll have to be a bit careful since some of the scripts might be used for other Jenkins pipelines that we haven't replaced yet, such as the release builds or QA runs.

blocked by #9137

**Comment by menski** [comment]
Notes from my meeting with Ole:

Goal would be to remove all files from the `.ci` folder which are not needed anymore, but concern is that as long as any branch needs the Jenkins jobs these have to stay on `main` as Jenkins generates the jobs out of it.
