### ISSUE TITLE
Overview of `ActorScheduler` capabilities

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9145]
# Description

This contains a growing list of capabilities that are offered by our current `ActorScheduler` system. Ideally, each capability should include a description, links to implementation code, and examples how this feature is used. 

# Capabilities

Overall, if used correctly, the actor scheduler allows writing concurrent, lock-free code without introducing data races. It's also supposed to do fair scheduling and reliable scheduling of delayed or repeating jobs. 

## Execution Model

Actor threads execute a simple loop:

```mermaid
stateDiagram-v2
    direction LR
    state "Idle" as Idle
    state "Run task" as Run
    state "Get next task" as Next
    state "Update clock" as Clock
    state "Process expired timers" as Timer
    state NextState <<choice>>
    [*] --> Idle
    Idle --> Clock
    Run --> Clock
    Clock --> Timer
    Timer --> Next
    Next --> NextState
    NextState --> Run : Has a next task
    NextState --> Idle : No tasks available
```

Actor threads can steal tasks from each other. Each thread has a queue of tasks and if one thread's queue is empty, it will try to acquire a task from the end of another thread's queue.

When running a task, the task is responsible for polling subscriptions and it's two queues to acquire jobs and run them.

### Queues & Ordering

Each actor task has two queues: `fastLane` and `submittedJobs`. Jobs that are added by the actor itself are generally added to the fast lane directly while tasks scheduled externally are added to the submitted jobs queue.

There are multiple methods in `ActorControl` that can schedule jobs:

| method | usage |
|-----------|----------|
|`ActorControl#run`| Internally, submit a job to the fast lane. Externally, same as `ActorControl#submit` |
|`ActorControl#call`| Only externally, submits to the regular job queue of another actor |
|`ActorControl#submit`| Submits to the end of the regular job queue of the corresponding actor |
|`ActorControl#runUntilDone`| Resubmits jobs until `ActorControl#done` is called |
|`ActorControl#runDelayed`| Submits a job with an initial delay |
|`ActorControl#runAtFixedRate`| Submits a repeating job |
|`ActorControl#runOnCompletion`| Subscribes to an actor future, when the future is completed the job is added to the fast lane |
|`ActorControl#runOnCompletionBlockingCurrentPhase`| Prevent the actor from transitioning to the `CLOSE_REQUESTED` phase until the job is done |
|`ActorControl#consume`| Subscribes to a channel and submits a job to the fast lane whenever there is something to consume from the channel |

Overall, the two queues allow for some control over ordering of jobs. Once a job has been added to a queue, order within that queue does not change and jobs are executed in the order they were added. Presumably, some usages of `submit` over `run` or similar were consciously chosen because ordering of jobs was important.

### Lifecycle

Actors are always in one of the following lifecycle phases:
- `STARTING`
- `STARTED`
- `CLOSE_REQUESTED`
- `CLOSING`
- `CLOSED`
- `FAILED`

Actor's can implement listeners (`Actor#onActorStarted` etc.) to be notified when the actor transitions to a new phase, for example to acquire/release resources or update health reports when the actor failed. 

Jobs that are submitted via `ActorControl#runOnCompletionBlockingCurrentPhase` prevent the actor from transitioning away from the current phase or into the `CLOSE_REQUESTED` phase.

## Scheduling

**IO/CPU-bound specialization**
There are two different thread groups: `IoThreadGroup` and `CpuThreadGroup` which use different scheduler implementations and are supposed to execute tasks that are either CPU or IO bound. This allows users to configure how many resources (i.e. threads) are available for IO or CPU bound tasks.
Currently, there are only two actors that are marked as IO-bound, the `ExporterDirector` and the `FileBasedSnapshotStore`.

## Asynchronous Callbacks

Probably the most used capability of the actor framework. Jobs can be scheduled via `ActorFuture#onComplete` or `ActorControl#runOnCompletion` to be added to the fast lane once a given actor future is completed. This is essentially the same functionality that is also available for Java's regular `CompletableFuture`.

## Subscriptions

There are four implementations of `ActorSubscription`:
- `ActorConditionImpl`
Only used by the dispatcher to run housekeeping code whenever a dispatcher subscription is used. 
- `ActorFutureSubscription`
Used throughout Zeebe, implements the asynchronous callback functionality of actor futures.
- `TimerSubscription`
Used throughout Zeebe, implements timers
- `ChannelConsumerCondition`
Only used by the `LogStorageAppender` to get notified when new the dispatcher has write buffer space available.

## Timers

Each actor thread comes with a `ActorTimerQueue` which is uses agrona's `DeadlineTimerWheel` internally. It is used to schedule delayed or fixed-rate repeating jobs.

Timer jobs are always scheduled from an actor, on the current actor thread, via the `ActorControl` class.
Polling the timer queue is part of the actor thread loop and is done whenever more than once millisecond has passed since the last clock update.

If a timer expires, it will wake up the actor task that corresponds to the actor control that was used to schedule the timer and mark the job as available. Eventually, the task will be picked up by an actor thread and the available job will be executed.

Zeebe uses timers for a lot of different things that fall into two broad categories: internal such as periodic health checks and delayed retries and external such as BPMN timer events.

## Actor Clock

Zeebe has two `ActorClock` implementations, the `DefaultActorClock` and the `ControlledActorClock`. 
The clock is always updated externally, by actor threads, when a task is being executed or the thread is idling.

Much of Zeebe's code assumes that an actor clock is available in the current thread and calls the static method `ActorClock#currentTimeMillis`. If no actor clock is available, this calls silently falls back to a regular call of `System#currentTimeMillis`.

The `ActorClock#update` method retrieves the `System#nanoTime`, uses it to update the clock, and returns a boolean indicating if more than one millisecond has passed since the last update. If more than one millisecond has passed, the actor thread that updated the clock checks if any timers have expired.

The `ControlledActorClock` is used for testing, both internally in our own test code, as well as externally, for example if Zeebe is used as a test container. It allows arbitrary control of the clock, for example pinning it to a given timestamp or shifting it by some  duration.

**Comment by Zelldon** [comment]
@oleschoenburg maybe this helps to understand the capabilities or gives you a quick start https://docs.google.com/presentation/d/1qkFEI_Lf552I_U31-MNykuPESeigwdGdQJDM6FS4Fd0/edit?usp=sharing

**Comment by oleschoenburg** [comment]
Awesome @Zelldon, looks like I'm done with this issue then :laughing: But seriously, that's very helpful!

**Comment by deepthidevaki** [comment]
One more thing to consider for the list is the execution model.  The tasks are executed in different order depending on whether they are submitted using `actor::run`, `actor::call` or `actor::submit`. I think this is different from a typical actor model. We might be relying on this order of execution to get the desired semantics.

**Comment by pihme** [comment]
On my wish list: Make sure that code using the actor scheduler can be tested.

One problem we run into over and over again, is to figure out when the engine has stopped processing. Since everything is asynchronous this is trickier. We get close to solving this problem by methods like `hasReachedEndOfProcessing()` But this is usually not enough, because there could be scheduled tasks that have not executed yet, which add new records. 

So what would help would be something like "wait until end of processing has been reached, and all scheduled tasks have been executed"

Making the scheduler deterministic would also be great, but might be too much to ask.

**Comment by pihme** [comment]
Also the CPU vs. IO bound threads never made much sense to me. If we were to use non blocking IO, wouldn't that make all threads CPU bound?
