### ISSUE TITLE
How to display details of the health indicators?

### ISSUE THREAD

**Issue by aisong** [camunda/zeebe#9157]
Zeebe version: 8.0.0
Related configuration:

management.health.defaults.enabled: true
management.endpoint.health.show-details: always

Question:
I followed this guide: [https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/gateway-health-probes/](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/gateway-health-probes/)

I want to get these details:
 {zeebe-gateway}:8080/actuator/health
{zeebe-gateway}:8080/actuator/health/startup
{zeebe-gateway}:8080/actuator/health/liveness

but:
when: 
GET http://10.8.1.155:9600/actuator/health
{
    "status": "UP"
}

It hasn't any details.

when:
GET http://10.8.1.155:9600/actuator/startup
or http://10.8.1.155:9600/actuator/liveness
{
    "timestamp": "2022-04-16T08:53:29.003+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/actuator/startup"
}

What's wrong with me?

**Comment by npepinpe** [comment]
Are you running the standalone gateway or the broker with embedded gateway? The documentation above relates to the standalone gateway. When running:

```shell
docker run --rm -e ZEEBE_GATEWAY_NETWORK_HOST=0.0.0.0 -e ZEEBE_STANDALONE_GATEWAY=true -p 9600:9600 camunda/zeebe:latest
```

Then calling `http://localhost:9600/actuator/health` would get you:

```json
{
  "status": "DOWN",
  "components": {
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 1022488477696,
        "free": 850985574400,
        "threshold": 10485760,
        "exists": true
      }
    },
    "gatewayClusterAwareness": {
      "status": "DOWN"
    },
    "gatewayPartitionLeaderAwareness": {
      "status": "DOWN"
    },
    "gatewayResponsive": {
      "status": "UP",
      "details": {
        "timeOut": "PT0.5S"
      }
    },
    "gatewayStarted": {
      "status": "UP"
    },
    "livenessGatewayClusterAwareness": {
      "status": "DOWN",
      "details": {
        "derivedFrom": "ClusterAwarenessHealthIndicator",
        "wasEverUp": false,
        "maxDowntime": "PT5M",
        "lastSeenDelegateHealthStatus": {
          "status": "DOWN"
        }
      }
    },
    "livenessGatewayPartitionLeaderAwareness": {
      "status": "DOWN",
      "details": {
        "derivedFrom": "PartitionLeaderAwarenessHealthIndicator",
        "wasEverUp": false,
        "maxDowntime": "PT5M",
        "lastSeenDelegateHealthStatus": {
          "status": "DOWN"
        }
      }
    },
    "livenessGatewayResponsive": {
      "status": "UP",
      "details": {
        "derivedFrom": "ResponsiveHealthIndicator",
        "wasEverUp": true,
        "maxDowntime": "PT10M",
        "lastSeenDelegateHealthStatus": {
          "status": "UP",
          "details": {
            "timeOut": "PT5S"
          }
        }
      }
    },
    "livenessMemory": {
      "status": "UP",
      "details": {
        "threshold": 0.01
      }
    },
    "ping": {
      "status": "UP"
    }
  },
  "groups": [
    "liveness",
    "readiness",
    "startup"
  ]
}
```

However, these actuators (the ones from the documentation) are not loaded when running the broker with embedded gateway, so it's normal you would not see any details.

Hope this helps!
