### ISSUE TITLE
Some Prometheus Metrics missing?

### ISSUE THREAD

**Issue by inghak** [camunda/zeebe#9191]
Description of Observation:

Trying out the Zeebe Grafana Metrics board at https://github.com/camunda/zeebe/blob/main/monitor/grafana/zeebe.json

A lot of the metrics work, but some dont.  Further investigation of the Grafana panels that do not work shows that the Prometheus metrics required for the panel is not exposed by zeebe (my claim...).

An example is the Latency panel` Process Instance Execution Time.` It uses metric `zeebe_process_instance_execution_time_bucket`. This metric is not exposed by Zeebe according to Queries in Prometheus Admin UI (Graph query).  When querying `zeebe_process_instance_execution_time_bucket`, it does not exist.

The way I have activated Zeebe metrics, is in config to ccsm-helm-0.0.29 app version 1.3.4  :
```
prometheusServiceMonitor:
  enabled: true

```
In Kubernetes I have a service monitor matching label so that the Zeebe metrics are exposed.
This give me prometheus /metrics targets for gateway pod and each broker pod:
zeebe-zeebe-gateway
zeebe-zeebe-0
zeebe-zeebe-1
zeebe-zeebe-3
They are all UP and exposing metrics. They are green in Prometheus GUI Status -> targets. I can query most Zeebe metrics in Prometheus UI. Most of the Grafana board works nicely.

But (at least) the following metrics are missing:
- zeebe_snapshot_replication_duration_milliseconds
- zeebe_snapshot_replication_count
- zeebe_process_instance_execution_time_bucket
- zeebe_process_instance_execution_time_sum
- zeebe_process_instance_execution_time_count
- zeebe_job_activation_time_bucket
- zeebe_job_life_time_bucket

Expected:
The metrics listed above should be available and queryable in Prometheus Admin GUI Graph query.  The Panels using them in Grafana should work.

Reproduce:
- Install Zeebe with HELM ccsm-helm-0.0.29 app version 1.3.4
- Activate Zeebe monitoring in HELM config prometheusServiceMonitor: enabled: true
- Get your Prometheus instance to discover targets for zeebe gateway and broker. In Prometheus UI you should find them under Status - > Targets
- Install some zeebe process and create some activity.
- Query the claimed missing metrics listed above. Do they return data? 
- Import the Zeebe Grafana board from  https://github.com/camunda/zeebe/blob/main/monitor/grafana/zeebe.json and check if all panels are working. Particularly Latency group.

Do some metrics not work or am I missing something here?

**Comment by Zelldon** [comment]
The execution metrics are created by an exporter which you can enabled via env var see https://github.com/camunda/zeebe/blob/main/benchmarks/setup/default/zeebe-values.yaml#L48-L49

```
- name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
  value: "true"
```

I guess the snapshot metrics do not exist anymore.

**Comment by npepinpe** [comment]
Correct, the snapshot metrics remaining are the Atomix ones, so these above have been removed. Do we still attempt to show them in the dashboard?
