### ISSUE TITLE
Partition is healthy is logged unnecessarily

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9207]
**Describe the bug**

Partition is logged as healthy repeatedly. However we do not see it becoming unhealthy. This is just noise. We should log only if there is a change in the health status.

![image](https://user-images.githubusercontent.com/1997478/164627932-ad8a99aa-da2a-4d34-bc48-682c41ffec15.png)

**Comment by npepinpe** [comment]
Yes! I also noticed it, it's very regular every minute or so :open_mouth:
