### ISSUE TITLE
Discuss proposals on how to take backup of camunda cluster

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9222]
This is the place to collect ideas and discuss them.

Related to #9103

**Comment by deepthidevaki** [comment]
### Proposal 1

Here is a high level proposal to take backup of a camunda 8 cluster. Note:- This is not a complete solution. The details are yet to be defined.

To take backup of a Camunda 8 cluster, do the following operations in order:

1. In parallel
	- Backup Optimize data
	- Backup Operate data
	- Backup Tasklist data
1. Pause exporting in Zeebe
1. In parallel
	- 	Backup zeebe-records in elastic search
	- 	Backup Zeebe data
1. Resume exporting in Zeebe (only after all backups are completed)

*Note: How to backup Optimize data, Operate data, tasklist and Zeebe data **is to be defined.*** 

Cons:
Since exporting is paused
* the data visible to operate/optimize is not up-to-date during the backup process.
* It will take time to be up-to-date after the exporting is resumed. 
If backups are taken frequently this may affect the user experience (depending on how long the backup process last).

Pros:
* This will significantly simplify the solution and easier to implement.
* Less coordination needed between backups of zeebe and the other apps.

**Why do we have to pause exporting?**
To prevent the possible inconsistencies in the backup. For details read the following:
* [Potential inconsistency between zeebe and exported records in ElasticSearch](https://github.com/camunda/zeebe/issues/9106#issuecomment-1097688129)
* [Potential inconsistency among shards of zeebe-records in ElasticSearch backup](https://github.com/camunda/zeebe/issues/9104#issuecomment-1099075498)

**Can we find a solution without pausing exporting?**
Probably Yes. But it would be more complex, given the [limitations we found with ElasticSearch snapshots](https://github.com/camunda/zeebe/issues/9104#issuecomment-1099075498).

**Comment by npepinpe** [comment]
I think I'm missing something. If we backup Operate/Optimize/Tasklist data first, then pause exporting, presumably they will keep importing the newer data, right? Whatever Zeebe managed to export before that was paused.

But if I understand correctly, then after pausing, we would backup zeebe-records (which is presumably immutable at this point - I assume a backup forces a refresh operation on all shards), which means on restore Optimize/Tasklist/Operate would re-import whatever's in zeebe-records, which wouldn't have been deleted between their initial backup and when we backed up zeebe-records (not sure if we need some guarantees there).

I think the scope of the first "con" is a bit bigger. As we're still processing while exporting is paused, we might be building a considerable backlog of records which need to be flushed. Catching up may prove difficult depending on how long the backup took.

So I guess we want to minimize the time exporting is paused, right? Possibly restore time is not super important at the moment.

P.S.: this made me realize that again, if we got rid of exporters, things would be much simpler all around :smile:

**Comment by deepthidevaki** [comment]
Taking backup of the app first and pausing the exporting is ok because on restore, the apps have "older" data and "zeebe-records" may have new records that are not processed by the apps' backup. This is ok, because the apps can process the new records without violating any gurantees. 
To be more precise:
1. Optimize imports record X
2. Optimize takes backup until this state
3. zeebe export new record X+1
4. Optimize continue importing X+1
5. Pause exporting
6. Backup of zeebe 
7. Backup of zeebe-records in ElasticSearch
8. Resume exporting

On restore:
- Optimize has imported records until X
- Zeebe-record has new records X+1
- Optimize can resume importing from X+1
This does not violate any assumptions.

**Comment by deepthidevaki** [comment]
> I think the scope of the first "con" is a bit bigger. As we're still processing while exporting is paused, we might be building a considerable backlog of records which need to be flushed. Catching up may prove difficult depending on how long the backup took

The impact of this in Zeebe will be minimal I guess. As far as I know Zeebe is resilient to slow exporting. As long as the backup process does not take several hours, it should be fine. 

The impact will be more on the Operate side. As the data in Operate is not real time during the backup process. 

Since we don't know yet how long the backup process last, it is difficult to estimate how much will be the impact. We can probably test the ElasticSearch snapshots now to estimate how long the backup takes in a reasonable scenario. But estimating how long Zeebe backup takes is not possible now, as we don't have a solution for that yet.

**Comment by deepthidevaki** [comment]
> So I guess we want to minimize the time exporting is paused, right? Possibly restore time is not super important at the moment.

One approach would be to let the backup be inconsistent. Then detect it during restore and fix them. For example, during restore we realize that ElasticSearch has more records that are not in the zeebe backup. On restore, we can somehow detect it and delete those records from ElasticSearch index before Operate/Optimize reads them. But I haven't figured out how we can achieve it.

**Comment by pihme** [comment]
> On restore:
> 
>     * Optimize has imported records until X
> 
>     * Zeebe-record has new records X+1

Continuing on the issue that Nicolas raised. Zeebe has marked records X+1 already as exported (to the old Optimize/Operate) maybe even deleted the records. So why does Zeebe export them again? I must be missing something

**Comment by deepthidevaki** [comment]
> Continuing on the issue that Nicolas raised. Zeebe has marked records X+1 already as exported (to the old Optimize/Operate) maybe even deleted the records. So why does Zeebe export them again? I must be missing something

Zeebe doesn't have to export them again. They are already in the backup of ElasticSearch index that stores exported zeebe-records. Operate or Optimize never delete those records. Zeebe-records are deleted by the curator.

**Comment by deepthidevaki** [comment]
May be one this is not clear for you. There are mulitple "types" of data in ElasticSearch.
1. Exported zeebe records - stored in a specific indices (say zeebe-records).
2. Operate data - stored in operate-* indices
3. Optimize data - stored in  optimize-* indices

When we take backup of operate or optimize, we only take backup of the corresponding indices. We take backup of zeebe-records index after pausing the exporting. ElasticSearch allows to snapshot each index independently.

**Comment by deepthidevaki** [comment]
## Proposal 2

Following are some rough ideas. It is even less complete than [Proposal 1](https://github.com/camunda/zeebe/issues/9222#issuecomment-1108209245). 

### Uncoordinated backups

The general idea is that we let the backups be inconsistent. On restore we identify the inconsistencies and either fix them or roll back to a previous consistent backup.
The questions to be answered are:
- Whether we can identify and fix the inconsistencies
- If we rollback to a previous backups until we find a consistent one, is there an upper bound on how long in the past we will have to rollback (preventing domino effect).

It would be interesting to see if we can do this for the entire C8 cluster or only for specific components or parts.

Impact: If we can do this backup process will be simplified and will have less impact on user experience, but restore process will be more complex. Assuming we don't have to restore from backups often, this would be a good trade-off.


### Uncoordinated backup to prevent the need to pause exporting while taking backups.

We don't pause exporting when taking the backup. Then the backup process will be as follows:

1. In parallel
	- Backup Optimize data
	- Backup Operate data
	- Backup Tasklist data
1. In parallel:
	1. Backup Zeebe data
	2. Backup zeebe-records in elastic search

This can lead to following inconsistencies. (*Note:- If we do all 5 steps in parallel, this will lead to more inconsistencies. So we enforce some ordering to keep it simple. *)

A. [ElasticSearch backup has data that zeebe doesn't know about](https://github.com/camunda/zeebe/issues/9106#issuecomment-1097688129)
- Zeebe data has records until X
- zeebe-records in ES has record X+1 which is not in Zeebe

B. [Zeebe has more records that won't be re-exported](https://github.com/camunda/zeebe/issues/9106#issuecomment-1097688129)
- Zeebe data has records until X+1 marked as exported
- zeebe-records in ES has records until X

C. [ElasticSearch backup has some gaps](https://github.com/camunda/zeebe/issues/9104#issuecomment-1099075498)
- zeebe-records in ES has record X, and X+2, but not X+1
- zeebe data has records until X+2 (zeebe may or may not re-export these records)

We can prevent A  if we take backups of zeebe-records first and then zeebe data. We can prevent B if the backups are taken in the opposite order. C can happen in both cases due to weak guarantees from ElasticSearch.

**How to fix these inconsistencies?**
Assuming we can detect these inconsistencies during restore, we can fix them as follows.

In case A, we can delete record X+1 before Operate or Optimize imports them.

In case B, zeebe should re-export all records from the last record in zeebe-record backup. In this case zeebe should not have compacted the logs.

In case C, zeebe should re-export all missing records before Operate/Optimize imports them. In this case zeebe should not have compacted the logs.

**Questions to be answered:**
* Can we detect these inconsistencies on restore? What would be the complexity of it?
* Can we ensure that the logs are not compacted in the backups so that they can be re-exported if necessary?

**Comment by pihme** [comment]
Since we are already at rough ideas:

### Backup Log Stream

**Backup**

* export every record 
* Add information to the exported records with which version of the software the record was processed

**Optional log grooming**
Periodically eliminate all records from backup that will no longer be needed on restore (e.g. process instances that have completed/terminated and have fallen outside the history window of Operate/Optimize/Tasklist)

**Restore**

* Restore Zeebe by replaying from the start of the log (including export to ElasticSearch) - restore is a bit tricky, because it would require updating the software alongside replaying the commit log. 
* Then start up Operate/Optimize to ingest data from ElasticSearch

**Comment by Zelldon** [comment]
> > I think the scope of the first "con" is a bit bigger. As we're still processing while exporting is paused, we might be building a considerable backlog of records that need to be flushed. Catching up may prove difficult depending on how long the backup took
> 
> The impact of this in Zeebe will be minimal I guess. As far as I know Zeebe is resilient to slow exporting. As long as the backup process does not take several hours, it should be fine.
> 
> The impact will be more on the Operate side. As the data in Operate is not real time during the backup process.
> 
> Since we don't know yet how long the backup process last, it is difficult to estimate how much will be the impact. We can probably test the ElasticSearch snapshots now to estimate how long the backup takes in a reasonable scenario. But estimating how long Zeebe backup takes is not possible now, as we don't have a solution for that yet.

Maybe we can think of doing this procedure partition-wise? Like pausing the exporter of partition N and backup zeebe-data of partition N and if done resume and continue with N+1. In this way operate/optimize will still see data and the user will not realize that there is something going on in the background :thinking: But then I guess the web apps backup will not work, only if this is also partition aware. Furthermore, we would need a partition aware be elastic indexes, which is currently not the case. So maybe not a solution, but just wanted to share my thoughts.

**Comment by deepthidevaki** [comment]
Thanks @pihme . This is an interesting idea.

The main challenge I see here is the need to keep the history for a longer period. How practical that would be? If we have to keep the history for 1 year, can we restore the state with in a reasonable time? If we prune the logs, will Zeebe be able to restore its state?

**Comment by Zelldon** [comment]
Maybe we can think also about a similar strategy as we do with our zeebe snapshots.

Like taking a backup of zeebe and checking what was last exported position. Mark this only as valid if the last export position is also in Elasticsearch. If this is the case take a backup of elastic, mark this only valid if this is part of all web app indexes. But I guess since we have aggregated data in the other indexes this is currently not possible, but could be implemented I guess.

**Comment by Zelldon** [comment]
> > Furthermore, we would need a partition aware be elastic indexes, which is currently not the case. So maybe not a solution, but just wanted to share my thoughts.
> 
> I have also thought about it - to make partition specific elastic indices. But now I cannot remember what problem it would solve thinking

I guess with everything partition aware we could do backups partition-wise.

**Comment by npepinpe** [comment]
What about pausing updating the last exported position instead of pausing exporting? So let's say we:

1. Backup Operate/Tasklist/Optimize
2. Pause acknowledging the exported position (but not exporting itself)
3. Backup zeebe data (which has the "old" acknowledged position)
4. Resume acknowledging
5. Backup zeebe-records (which may contain records past the "old" acknowledge position)

The key here is mostly to prevent compacting the log until after the backup, that we always re-export more records than necessary so we don't need to worry about gaps in zeebe-records, assuming we can guarantee that zeebe data has record X and later, and zeebe-records has all required records up to X without gaps.

The advantage is we don't stop exporting so as far as the user is aware, "nothing" happened. It might be that on restore we need to drop records X+1 from zeebe-records, especially if we don't know if there might be gaps (i.e. X, X+2, X+5, etc.), so it'd be safer to drop all ]X,inf+] and just re-export from X :man_shrugging: 

Now, pausing/resuming acknowledging is probably not easy to do, and also it means we're limited by the in memory buffer, so it's almost the same as pausing exporting depending on how long it takes to backup zeebe data. I wonder if we couldn't get over this limit somehow - using an out of band, disk-backed memory mapped buffer instead of purely in memory buffer? Not great, I know.

**Comment by pihme** [comment]
> Thanks @pihme . This is an interesting idea.
> 
> The main challenge I see here is the need to keep the history for a longer period. How practical that would be? If we have to keep the history for 1 year, can we restore the state with in a reasonable time? If we prune the logs, will Zeebe be able to restore its state?

All good questions. Don't have an answer.

It would be interesting to know how much size we really need, if we take incremental backups and compress them. It feels to me like our data stream would be well suited for compression.

I think there might also be hybrid approaches. E.g. we take incremental backups and at the end of each quarter, we replay the backup of the last quarter, then take a copy of the state in Zeebe/Operate/Benchmark which is then an official snapshot.

Some of the "need to pause the world" problems you mentioned in the other proposals could possibly be solved if you have a clean copy of the SSOT and can run all the backup procedures in the background, without interfering with the running system.

**Comment by deepthidevaki** [comment]
> What about pausing updating the last exported position instead of pausing exporting? So let's say we:

With the current exporter implementation, what is the behavior if the positions are not updated? Would it continue exporting or retry with the same records (ignoring failovers/restarts)?

> 
> Now, pausing/resuming acknowledging is probably not easy to do, and also it means we're limited by the in memory buffer, so it's almost the same as pausing exporting depending on how long it takes to backup zeebe data. I wonder if we couldn't get over this limit somehow - using an out of band, disk-backed memory mapped buffer instead of purely in memory buffer? Not great, I know.

Why is it limited by memory?

**Comment by npepinpe** [comment]
I like Peter's idea though - provide a single data lake for all the apps, and compact that whenever we take a backup of the apps (assuming we can guarantee some lower bound position for all of them). So it's basically applying Zeebe's compaction logic but on a wider scale. Definitely simpler, but it adds operational complexity. Is this something we can ask of users? :thinking: 

(correct me if I misunderstood the idea though)

If we're going into more divergent ideas, I still think getting rid of exporters would be great for the overall system. Instead, provide a consumer API for the log, where you can register consumers with some guarantees (i.e. same as the exporters: once registered, no data can be deleted until it's been consumed by the consumer), which is stored in the state. Have the importers import directly from that (the reading can happen on followers to offload some work) - all the apps are writing their own importers anyway. In this case, backup is greatly simplified - the importers can stop acknowledging anything while we backup, and resume acknowledging after. This guarantees data remains in Zeebe and can be re-imported after a restore. It greatly simplifies the coordination between Zeebe and the other apps.

Regarding the memory limit - we clear the ES exporter's in memory buffer only when positions have been acknowledged. But now I realize, we can clear it as long as we know data was ingested, even if we're not updating the position - as long as we track that position to resume acknowledging, that's probably good enough :+1: I was thinking about it much like if we didn't acknowledge due to, say, failure. But that's my mistake :slightly_smiling_face:

**Comment by deepthidevaki** [comment]
> I think there might also be hybrid approaches. E.g. we take incremental backups and at the end of each quarter, we replay the backup of the last quarter, then take a copy of the state in Zeebe/Operate/Benchmark which is then an official snapshot.

That means there will be a separate application (or copy of zeebe, operate, optimize) to replay for the backup? 

Just wondering one more thing. Can the state of Operate and Optimize be rebuilt entirely from the zeebe logstream? Are there other data generated by other external triggers?

**Comment by deepthidevaki** [comment]
To solve the problems in [Proposal 2](https://github.com/camunda/zeebe/issues/9222#issuecomment-1108633509), we can modify the backup process as follows:

1. In parallel
	- Backup Optimize data
	- Backup Operate data
	- Backup Tasklist data
2. Backup Zeebe data
3. Backup zeebe-records in elastic search

In this case inconsistencies case A and case C can happen. Both of the them can be fixed during restore as follows:
1. Start ElasticSearch and restore it from the backup
2. Restore Zeebe from the backup - but do not start processing or exporting.
1. Read the lastExportedPosition in Zeebe (from each partition's snapshot)
2. Delete extra records in ElasticSearch - for each partition records with position greater than lastExportedPosition
3. Restart zeebe normal operations
4. Start the webapps

This will also prevent case C, where there are missing records because : The missing records are the records that may have been written concurrently to the elasticsearch backup process. The `lastExportedPosition` will be written before we starts ES's backups. So if we delete all records after that position, we can guarantee that there are no gaps. 

This way we don't have to pause exporting. The complexity has been moved to the "Restore" operation.

**Comment by deepthidevaki** [comment]
### Summary

We have two competing ideas.
1. [Proposal 1](https://github.com/camunda/zeebe/issues/9222#issuecomment-1108209245) where we have to pause exporting while taking backups.
    - Cons:
           - No realtime data in operate/optimize/tasklist during backup 
       _Strategy_: Users can schedule the backup when they expect low load so that catchup after the backup is done fast
    - Pros:
           - Simple to prototype and evaluate
 
2. [Proposal 2](https://github.com/camunda/zeebe/issues/9222#issuecomment-1110697976) where we do not pause, instead we fix the inconsistencies during restore
    - Cons:
           - More complex restore process.
    - Pros:
           - No need to pause. So no or minimal impact on user experience during the backup.


For either for these approaches, the rest of the steps are similar. We can work on the backups of each applications independent of these approaches.  We can decide later which solution to chose. 

I will close this issue, as I would not explore more ideas. However, feel free to add comments, concerns or questions further.
