### ISSUE TITLE
source code consulting

### ISSUE THREAD

**Issue by zqs4449** [camunda/zeebe#9252]
**Description**

issues #5673 ， I can't understand why the source code  io.camunda.zeebe.protocol.record.ExecuteCommandRequestDecoder  doesn't exist 。Does the source code have to be compiled to generate it？

**Comment by Zelldon** [comment]
Exactly these are generated classes, which happens during an `mvn generate-sources`

**Comment by zqs4449** [comment]
the module protocol ，doing mvn generate-sources ？
