### ISSUE TITLE
Update Go client to use 1.17

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#9270]
**Description**

Our Go client is now built against 1.15, which is not supported anymore. We should start building against Go 1.17, which is the lowest support version.

**Comment by npepinpe** [comment]
Our CI will have to be updated to account for this.

**Comment by aivinog1** [comment]
Also, needs to keep in mind, that `go get ...` [is deprecated in the Go 1.17](https://go.dev/doc/go-get-install-deprecation#:~:text=Starting%20in%20Go%201.17%2C%20installing,the%20%2Dd%20flag%20were%20enabled.), and needs to update [this instruction](https://github.com/camunda/zeebe/tree/main/gateway-protocol-impl#prerequisite), for example

**Comment by oleschoenburg** [comment]
Please backport this to 1.3 as well to resolve https://github.com/camunda/zeebe/issues/9427
