### ISSUE TITLE
Dependency convergence error

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9280]
**Describe the bug**

When building `zeebe-process-test` with 8.1.0-alpha1, we get the following error.

```
Dependency convergence error for org.camunda.bpm.model:camunda-dmn-model:jar:7.16.0:compile paths to dependency are:
+-io.camunda:zeebe-process-test-engine:jar:8.0.1-SNAPSHOT
  +-io.camunda:zeebe-workflow-engine:jar:8.1.0-alpha1:compile
    +-io.camunda:zeebe-dmn:jar:8.1.0-alpha1:compile
      +-org.camunda.bpm.extension.dmn.scala:dmn-engine:jar:1.7.1:compile
        +-org.camunda.bpm.model:camunda-dmn-model:jar:7.16.0:compile
and
+-io.camunda:zeebe-process-test-engine:jar:8.0.1-SNAPSHOT
  +-io.camunda:zeebe-workflow-engine:jar:8.1.0-alpha1:compile
    +-io.camunda:zeebe-dmn:jar:8.1.0-alpha1:compile
      +-org.camunda.bpm.model:camunda-dmn-model:jar:7.17.0:compile
```

zeebe-worlflow-engine pulls in the `camunda-dmn-model` 2 times with different versions. However, zeebe builds fine. We can temporarily fix it in zeebe-process-test. But the issue seems to be in zeebe itself. 

**Expected behavior**

No conflicting versions in published artifacts.

**Comment by npepinpe** [comment]
Is it possible the log is truncated? I would expect another `org.camunda.bpm.model:camunda-dmn-model:jar:7.x.y:compile` statement.

**Comment by deepthidevaki** [comment]
> Is it possible the log is truncated? I would expect another `org.camunda.bpm.model:camunda-dmn-model:jar:7.x.y:compile` statement.

Yes. Sorry. Edited the issue description.

**Comment by npepinpe** [comment]
It works fine in Zeebe because `camunda-dmn-model` is a direct dependency for which we fix the version, but for ZPT it's a transitive dependency, so it does need to fix the version. That said, I would've thought Maven would resolve it via the shortest path, so it should be OK :thinking:

**Comment by npepinpe** [comment]
If that's OK, I would close it here and propose to fix it on the ZPT side. I think this is an unfortunate side effect of how Maven performs its dependency resolution. Do object if you disagree, as of course I might be biased or may have missed something!

**Comment by remcowesterhoud** [comment]
I agree, lets close this one.
