### ISSUE TITLE
Consider adding deploy workflow / cancel process instance to whitelisted commands (which will be accepted when backpressure is high)

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9283]
**Is your feature request related to a problem? Please describe.**
This came up during an investigation for https://github.com/camunda/zeebe/issues/8991 and then follow up discussions in https://github.com/camunda/zeebe/issues/9276 

Currently, we allow to complete / fail jobs under backpressure. 

However, some processes like fork bombs can bring the cluster into a non-productive state. Remedies in this situation include: 
* ability to cancel a process instance
* ability to deploy a newer version of a faulty workflow

**Describe the solution you'd like**
Whitelist these two commands as well

**Comment by saig0** [comment]
We agree with the suggestion. The goal is to implement the change for the next minor version.
