### ISSUE TITLE
Defect links in readme.md

### ISSUE THREAD

**Issue by dennisfabri** [camunda/zeebe#9295]
A lot of links in the readme.md are dead (HTTP 404)

**Comment by Zelldon** [comment]
To be more specific:

 * https://docs.camunda.io/docs/guides/getting-started/create-camunda-cloud-account
 * https://docs.camunda.io/docs/components/zeebe/technical-concepts/index
 * https://docs.camunda.io/docs/self-managed/zeebe-deployment/index
 * https://docs.camunda.io/docs/apis-clients/java-client/index
 * https://docs.camunda.io/docs/apis-clients/go-client/index

**Comment by Zelldon** [comment]
Seems to be fixed via https://github.com/camunda/zeebe/commit/93ed43dd590d6e431fa6ca2afb9417d8be89355a :sweat_smile:
