### ISSUE TITLE
Starting Process in camunda 8 By Message Event Python

### ISSUE THREAD

**Issue by Rajput612** [camunda/zeebe#9335]
Hi everyone ,
My BPMN is as below.
![image](https://user-images.githubusercontent.com/50611037/167346912-9c748db8-b105-497d-894c-a976bcca1b54.png)
Expected Flow

1. an order is created and subsequently a message is created ("In customer lane the process should stop at “Receive the Goods” task.
2. Message is used to check whether the goods are available or not
3. if they are available the goods are deliver to the user and he can receive the goods
4. if the user is happy with the product then the process is completed.
5. if the user is not satisfied then user communicates with us and we try to resolve the issue
6. if we are unable to resolve the issue we pass it on to the seller.

Problems I’m Facing

1. I’m unable to follow the path of Step 2 and Step 6 in both the process i’m trying to move into different lanes and do some stuff 

What i have tried

```
from pyzeebe import ZeebeTaskRouter
from pyzeebe import ZeebeWorker, create_insecure_channel,Job
import asyncio
import random
import nest_asyncio
nest_asyncio.apply()


async def main():
    worker = ZeebeWorker(channel)
    router = ZeebeTaskRouter()
#     ProcessOrderMsg

    async def my_exception_handler(exception: Exception, job: Job) -> None:
        print(exception)
        await job.set_error_status(message= 'itemsOutOfStock', error_code='itemsOutOfStock') 

    @router.task(task_type="Order", exception_handler=my_exception_handler)
    async def Order():
        await client.publish_message(name="ProcessOrderMsg", correlation_key="ProcessOrderMsg")
        return {}

    @router.task(task_type="ProcessOrder", exception_handler=my_exception_handler)
    def ProcessOrder():
        return {}


    @router.task(task_type="DeliverTheGoods", exception_handler=my_exception_handler)
    def DeliverTheGoods():

        return {}
# testMessage
    @router.task(task_type="ReceiveTheGoods", exception_handler=my_exception_handler)
    async def ReceiveTheGoods():
        return {"status":"complain","msg":"success"}

#     EndMsgEvent
    @router.task(task_type="Complain", exception_handler=my_exception_handler)
    async def Complain(msg: str):    

        await client.publish_message(name="ComplaintMessage", correlation_key="ComplaintMessage")


    @router.task(task_type="ProcessComplaint", exception_handler=my_exception_handler)
    async def ProcessComplaint(cool: str):    
        return {"EndMsgEvent1":"EndMsgEvent1"}
    worker.include_router(router)
    await worker.work()
asyncio.run(main())
```
Any Help or guidance will be great help and for any clearification please feel free to ask.

**Comment by remcowesterhoud** [comment]
Hi @Rajput612 thank you for reaching out to us.

First things first, I'd like to make you aware of the [Camunda Platform Forum](https://forum.camunda.io). These kind of questions are more fitting on the forum and you could expect a faster answer there. Nonetheless I will try and provide you with a solution for your problem.

I can see a couple of issues in your process model which could explain the strange behaviour. In your model we can see that there are 2 processes. The customer process and the seller process. An important thing to know about BPMN is that the dashed arrows are just for modelling purposes. They don't provide any functionality when executing the process. Let's have a look at the flow of these processes as you have them modelled currently:

1. An instance is started of the customer process
2. The order service task is activated and a `ProcessOrderMsg` message is published, creating an instance of the seller process

From here on we will have 2 process instances. These instances are executed in parallel.

**Customer process**
1. After completing the order task it will immediately continue with the Receive the good task
2. If the customer is satisfied the process ends here
3. If the customer is unsatisfied a `ComplaintMessage` is published. No process instance will be actively waiting for this message, so it will not get correlated at this time.
4. The Complain task is completed and the process instance is finished.

**Seller process**
1. A `ProcessOrderMsg` is received which created the Seller process instance
2. The process order task is completed
3. The deliver the goods task is completed
4. The deliver the goods task has no outgoing sequence flows. In BPMN this is considered to be an [implicit end event](https://forum.camunda.io/t/can-we-have-a-bpmn-diagram-without-endevent/7853). This means that after this task the seller process instance will be finished.
5. The message catch event is never reached so the `ComplaintMessage` is never correlated and we never reach the process complaint task.


As you can see there is some unexpected behaviour in this model. I believe the key points are:
- The Customer process does not wait for messages from the Seller process before continuing execution
- The Seller process has an implicit end event after the deliver the goods task, causing the second half of this process to never be reached.


**How can you fix these issues?**
- You want to wait between the Order and the Receive the goods task until the goods are delivered. We can achieve this by introducing a [message catch event](https://docs.camunda.io/docs/components/modeler/bpmn/message-events/#intermediate-message-catch-events). The process instance will wait until this message has been received before it continues with its execution.
- You don't want the Seller process to end after delivering the goods. You'll have to add a sequence flow from the Deliver the goods task to the message catch event later in this process.

Fixing these things would result in a process like this:
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/5787702/168026147-6fa79cce-cb15-4977-8122-1708328c9333.png">

There's some things to note about this process. First of all I have changed the Order, Deliver the goods, and Complain task from service tasks to [send tasks](https://docs.camunda.io/docs/components/modeler/bpmn/send-tasks/). These tasks behave exactly the same way as a service task, but for modelling purposes it's easier to see that these tasks are publishing a message.
Second is that the Seller process will now always wait for a complaint message. If the customer is satisfied the Seller process will never receive this message and will never complete. I would recommend turning the complaint part of the Seller process into a separate process.
Last thing of note is that I can see in your code that you are publishing the `ProcessOrderMsg` with a correlation key of `ProcessOrderMsg`. Correlation keys in message start events work in a special way. Zeebe will make sure that only 1 instance of a process with a specific correlation key can be running at once. You can read more about this [here](https://docs.camunda.io/docs/components/modeler/bpmn/message-events/#message-start-events). I would suggest turning into a dynamic value, e.g. an order number.


Hope this answers helps you, if not feel free to reach out again.
