### ISSUE TITLE
As a user, I want to be able to override Zeebe client properties in the `gatewayResponsive` health check

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#9346]
**Is your feature request related to a problem? Please describe.**
I'm the author of the [Zeebe Keycloak project](https://github.com/camunda-community-hub/zeebe-keycloak-interceptor) so, when I'm using my interceptor Zeebe Gateway's health check is always down, because the `gatewayResponsive` component is down.

**Describe the solution you'd like**
Add some properties to customize Zeebe client in health checks.

**Describe alternatives you've considered**
We can add [spring-zeebe](https://github.com/camunda-community-hub/spring-zeebe) support if it will ease configuration.

**Comment by saig0** [comment]
@aivinog1 we are not sure about the actual problem and the expected solution. Please provide more details. 

Why does the gateway not work if you add interceptors?
What do you need to make it work?

**Comment by aivinog1** [comment]
@saig0 For example, I have an interceptor that checks the headers of the request for authentication info. And if it can't find it - it rejects the request. Also, this is fully compatible with authentication that provides Java client or `zbctl`. But I get constant info about failed health checks from `gatewayResponsible` part of them. So, I want to be able to customize Java client in the `gatewayResponsible` component so it can call Zeebe Gateway with token.

**Comment by aivinog1** [comment]
Also, I can propose a PR, how can I see it. Basically, I want to add additional configuration properties about Java client (right now, there is property about request timeout) that allows me to configure authentication properties.

**Comment by aivinog1** [comment]
Hey @remcowesterhoud! 

I'm writing the docs about this right now and I want to write the migration guide (because the `readTimeout` property is deprecated and users have to use properties inside `HealthZeebeClientProperties`). So, in which version the resolution of this issue will appear? Is there any chance to `8.2.0`? :)

**Comment by remcowesterhoud** [comment]
Hi @aivinog1! Yes this will be part of `8.2.0`
