### ISSUE TITLE
Run GHA on PRs created by backport-action

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#9365]
**Description**

When the backport-action creates pull requests, then our GHA workflows are not triggered/started.

This might be ok, because we can merge using bors, which will anyways run the CI again. But, we might want to receive feedback about the changes in the created PR as well.

If we want the GHA workflows to run for PRs created by the backport-action, then we should user a PAT (bot-user) for the backport action.

> **Why didn’t some event trigger my workflow?**
> When you use the repository’s GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs, as highlighted in [this topic 52](https://github.community/t/github-action-trigger-on-release-not-working-if-releases-was-created-by-automation/16559). If you would like to trigger a workflow from a workflow run, you can [trigger the event using a personal access token 208](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token).

See https://github.community/t/the-github-actions-guidepost/168114

**Comment by oleschoenburg** [comment]
Sounds good @korthout. If I understand correctly I can assign this to you then?
