### ISSUE TITLE
Enable default export of `process-message-subscription` record type

### ISSUE THREAD

**Issue by sdorokhova** [camunda/zeebe#9370]
**Description**

Operate starts to import data from index `process-message-subscription` (related issue https://github.com/camunda-cloud/operate/issues/2750), therefore we need to have export for this index enabled by default.

**Comment by Zelldon** [comment]
I think this will be done via https://github.com/camunda/zeebe/issues/8338 

@sdorokhova could you please clarify whether you want to see events only or are you also interested in commands?

**Comment by sdorokhova** [comment]
Currently we only need CORRELATED events from `process-message-subscription` index. 
And in general I would say that we import only events, not command.

Do you know when the issue #8338 will be addressed? We need it to be implemented for https://github.com/camunda-cloud/operate/issues/2750.

**Comment by Zelldon** [comment]
I guess @remcowesterhoud @korthout can tell you :)

**Comment by sdorokhova** [comment]
Thanks, @Zelldon !

As an idea. May be we can decouple these two tasks: enable one additional index for Operate purposes and enabling them all within #8338 ?

**Comment by remcowesterhoud** [comment]
@sdorokhova Is this severely blocking you? I was going to look at it next week, which would not be earlier than Thursday because I'll be on holiday. If it's blocking you someone else should take over for me.

**Comment by remcowesterhoud** [comment]
:+1: That should be fine then.

**Comment by sdorokhova** [comment]
I gave it a second thought:) 
In case it's not in alpha2, we would need to adjust (at least temporary) Zeebe configuration in Camunda Cloud. So I would need to know for sure, whether it's included in alpha2 or not. Could you give me such information?

**Comment by sdorokhova** [comment]
@remcowesterhoud and another question. Should we close this issue then?

**Comment by remcowesterhoud** [comment]
I'll be able to get it done before alpha2 so it'll be included. Yes, I'll close this issue and progress can be tracked in #8338
