### ISSUE TITLE
Extend ProcessInstanceCreation record with start instructions

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#9388]
The `ProcessInstanceCreation` records are sent by the gateway to the broker. The broker processes it to start the process instance. We'll need to extend it with start instructions to allow starting a process instance from an arbitrary point in the process. 

In the future, we may add support for local variables and instruction types (e.g. `startBeforeElement`, `startAfterElement`, etc), so the design should take this into account.

Make sure to document how we can extend records.

## Out of scope
- `localVariables` (root scope variables are already available)
- `type` (only `startBeforeElement` will be implemented in the first iteration)
- the created element instance keys in the `CREATED` event (not necessary in first iteration)

**Comment by korthout** [comment]
To take local variables into account, I see multiple options:

1. The `startInstructions` property is a list of objects with the following properties:
- `targetElementId` - a string containing an element ID or an empty string
- `localVariables` -  an object where each property is a variable name, and each value is an object with the following properties: `value` (any), `local` (boolean that describes whether this is a local variable or not). 

2. The `startInstructions` property is a list of objects with the following properties:
- `targetElementId` - a string containing an element ID or an empty string
- `localVariables` -  an object where each property is a variable name, and each value is the variable value (this variable needs to be created at the element specified by `targetElementId`

3. The `startInstructions` property is an object with the following properties:
- `targetElementIds` - a list of element id strings
- `localVariables` - an object where each property is an element id (at which point the variable is placed) and each value is an object where each property is a variable name, and each value is the variable value

Option 1 is an adaption of the C7 API (filtering out the non-relevant properties). It allows specifying start instructions for each element. The variables can be local or not. However, if the variables are not local, they overwrite the root-scope process variables. This means that variables may change multiple times during the construction of the process instance. First variables are created at the root scope for the provided `variables`, then for the first start instruction, the second, etc.

Option 2 removes the ability for these variables to be non-local, which avoids the overwriting issue with option 1. However, it does not allow specifying local variables at any of the flow scopes of the specified `targetElementId`. Note that C7 also does not support this. 

Option 3 adds this flexibility which might be useful for the testing use case. It would allow the user full control over the variables. However, specifying how to start each element becomes difficult in this option.

When starting this issue, please carefully consider the design.

**Comment by pihme** [comment]
The option 3 was the preferred choice in our discussion: https://camunda.slack.com/archives/C03C0HS85BL/p1652879080614909
