### ISSUE TITLE
“Re-activate jobs” failed to take effect

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#9457]
**Describe the bug**

The bug about https://github.com/camunda/zeebe/issues/8759 has been resolved in zeebe-1.3.6:[https://github.com/camunda/zeebe/issues?q=label%3Arelease%2F1.3.6+is%3Aclosed。](https://github.com/camunda/zeebe/issues?q=label%3Arelease%2F1.3.6+is%3Aclosed%E3%80%82)
![image](https://user-images.githubusercontent.com/92800459/170737993-8462455c-c55e-44fb-98d4-f991fd0ccbc5.png)
But in my test, I can find the log about "Failed to send xx activated jobs for type xx to client..." in my gateway ,but it didn't take effect, client still missed some one job.

Gateway Log:
![image](https://user-images.githubusercontent.com/92800459/170738843-0bb794d6-c3e1-4417-9ec5-392c8bb11538.png)

Source code:
![image](https://user-images.githubusercontent.com/92800459/170739062-e4f19b14-f801-4a11-a9f3-bf2e5b360926.png)
![image](https://user-images.githubusercontent.com/92800459/170739121-809dbf4f-70cc-4e9d-ab88-92f8568f25f7.png)
![image](https://user-images.githubusercontent.com/92800459/170739332-733b8979-58e2-4c91-9193-c8962fb5f122.png)

From the above log and source code, you can see the gateway failed to send job to client and success to do reactivate, but in reality this didn't work because the client still miss  jobs.

**Environment:**
zeebe 1.3.7
java-client sdk
PARTITIONSCOUNT=54
BROKER_CLUSTER_CLUSTERSIZE=18

Relate to issue https://github.com/camunda/zeebe/issues/9221.

**Comment by jerry123888** [comment]
Can i know the current progress?  Looking forward to the solution of this problem.Thanks
@menski @Zelldon @npepinpe

**Comment by korthout** [comment]
Hi @jerry123888 Can you help me reproduce this issue? 

It would be great if you could provide a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) (which I understand might be difficult).

Otherwise, can you explain how you verified that the client still missed some jobs?

**Comment by jerry123888** [comment]
> Hi @jerry123888 Can you help me reproduce this issue?
> 
> It would be great if you could provide a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) (which I understand might be difficult).
> 
> Otherwise, can you explain how you verified that the client still missed some jobs?

Thanks for your response. You can get the detail information at:https://github.com/camunda/zeebe/issues/9221.

**Comment by romansmirnov** [comment]
@jerry123888, I am closing this issue in favor of https://github.com/camunda/zeebe/issues/9221#issuecomment-1209309904.
