### ISSUE TITLE
Move Java client samples into a dedicated repository

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#9500]
**Description**

Currently, the Zeebe repo contains some examples for the Java client. We want to move these examples into a dedicated repository. 
Reasoning:
* better separation from production code
* better visibility for the community
* easier to contribute for the community or consultants

There is an existing repo (https://github.com/camunda-community-hub/camunda-8-examples) where we could merge the examples into. The repo should be similar to the one from Camunda Platform 7(https://github.com/camunda/camunda-bpm-examples).

**Comment by pihme** [comment]
Waiting for changes in other repos before removing it from this one

**Comment by berndruecker** [comment]
@pihme I merged your PR into https://github.com/camunda-community-hub/camunda-8-examples/ just now

**Comment by pihme** [comment]
@korthout I think this repo will be a cooperation between DevRel and all the other teams. Not aware of any plans to move it to camunda org

**Comment by ingorichtsmeier** [comment]
There are links in the docs to the examples that should be adjusted. See https://forum.camunda.io/t/zeebe-git-examples-unaccessible/38459.

**Comment by berndruecker** [comment]
Thanks for flagging - created an own issue fpr adjusting the docs: https://github.com/camunda/camunda-platform-docs/issues/1001
