### ISSUE TITLE
Writer timer triggered event with process instance key

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#9519]
**Is your feature request related to a problem? Please describe.**
I deployed a process with a timer start event. If the timer is triggered then a new process instance is created and an event of type `timer` with intent `triggered` is written. 

As a monitoring application, I want to track which process instance was created by this timer. But currently, the `timer: triggered` event doesn't contain the key of the created process instance. 

**Describe the solution you'd like**
The `timer: triggered` event contains the key of the created process instance.

**Describe alternatives you've considered**
Add a reference of the timer to the created process instance. But this option seems not practical because a process instance can be created by different triggers, for example, a message.

**Additional context**
In a monitoring application, I want to track that a process instance was created by a triggered timer start event.

**Comment by saig0** [comment]
@skayliu interesting question. But no, the element instance key would not fit in my mind. The timer creates a new process instance but the rest (e.g. activation of the start event) happens later. So what should be the element instance key? The timer is not bound to an element instance.

**Comment by skayliu** [comment]
@saig0 Thank you ,I get it .
