### ISSUE TITLE
Maven generated go protobuf code is not copied to destination

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9534]
**Describe the bug**

Recently had to regenerate the Go code based on `gateway.proto`. For some unknown reason, the call to `mvn generate-sources -P golang` does not copy the generated file to the correct destination.

**To Reproduce**
* Make dummy changes in `gateway.proto`
* Run `mvn generate-sources -P golang`
* Updated files is generated in `gateway-protocol-impl/target/generated-sources/protobuf/go` but not copied to destination

**Expected behavior**

Generated file is copied to destination.

**Comment by npepinpe** [comment]
I had to do this recently for the hack day project with multi tenancy, and for me this worked perfectly :shrug:
