### ISSUE TITLE
Allow unsupported BPMN elements in non executable pools

### ISSUE THREAD

**Issue by berndruecker** [camunda/zeebe#9542]
**Is your feature request related to a problem? Please describe.**

Customers following our BPMN methodology described also in Real-Life BPMN might create collaboration diagrams that contain executable and non-executable Pools (for example a model like in https://camunda.com/bpmn/examples/#bpmn-examples-four-eyes-principle). 

In https://github.com/camunda-community-hub/camunda-7-to-8-migration/issues/19 Stephan raised the problem that Zeebe rejects deployments containing unsupported elements, even if in a nonexecutable pool (e.g.  `Element: ConditionalEventDefinition_0lvmueg ERROR: Event definition of this type is not supported` ).

**Describe the solution you'd like**

Zeebe does not need to check elements in non-executable pools - as they are not executed and are ignored anyway. 
This would allow using all BPMN elements for documentation purposes.

**Comment by menski** [comment]
Question: How do we handle non-executable processes? Are we rejecting them or ignoring them?

**Comment by berndruecker** [comment]
@menski Ignoring them - as they are not executable the engine does not need to care at all

**Comment by skayliu** [comment]
> Zeebe does not need to check elements in non-executable pools - as they are not executed and are ignored anyway.
> This would allow using all BPMN elements for documentation purposes.

Hi, @berndruecker,@saigo, I think I've implemented this feature in my computer. 

`pools` means there are more the one process in a bpmn definition. 

One thing to confirm, if there is only one non-executable process in a bpmn definition, it will be blocked by  ["Must contain at least one executable process"](https://github.com/camunda/zeebe/blob/main/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/DefinitionsValidator.java#L37) , So do we keep block or non-block?

**Comment by saig0** [comment]
> One thing to confirm, if there is only one non-executable process in a bpmn definition, it will be blocked by ["Must contain at least one executable process"](https://github.com/camunda/zeebe/blob/main/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/DefinitionsValidator.java#L37) , So do we keep block or non-block?

Yes, keep. We don't want to deploy a process without any executable pool. :+1: 

> Another thing, may be we need to add a new property in ProcessRecord (e.g. includeNonExecutables, with value true or int 1 ) to tell user there are non-executable pools / non-executable process.

Interesting idea. Currently, I don't see a need to store non-executable pools. I would suggest ignoring any non-executable pool (i.e. no storing in the state, no process record).

**Comment by skayliu** [comment]
Hi, @saig0, May i make a PR for this?
