### ISSUE TITLE
zeebe-client-java' version: '8.1.0-alpha2  conflict at protoparser

### ISSUE THREAD

**Issue by heerzhang** [camunda/zeebe#9546]
I use  both  'zeebe-client-java' version: '8.1.0-alpha2' and infinispan-spring-boot-starter-embedded and 'infinispan-hibernate-cache-v53' 12.1.0.Final;
Spring boot cannot be started, and the error is as follows:

Syntax error in timestamp.proto at 140:8: unexpected label: int64 at protostream.com.squareup.protoparser.ProtoParser.unexpected
...
Finally, I changed the 'zeebe-client-java' version to the '8.0.3' version to solve the problem，and just run  OK。
I can not use 'zeebe-client-java' version: '8.1.0-alpha2', something conflict? java version is 18.0.1.1 and spring boot version is 2.7.0

**Comment by korthout** [comment]
Hi @heerzhang, please have a look at the [spring-zeebe](https://github.com/camunda-community-hub/spring-zeebe/) client. This should work without issues when combining Zeebe and Spring.
