### ISSUE TITLE
`expression-language` module shouldn't depend on `scheduler`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9609]
**Description**

The `zeebe-expression-language` depends on the `scheduler` module because it accepts an `ActorClock` as it's source of time. This is a bit inelegant and we should make changes so that  `zeebe-expression-language` doesn't have a direct dependency on `scheduler`, for example by injecting `ZeebeFeelEngineClock` instead of `ActorClock`.

See related discussion here: https://github.com/camunda/zeebe/pull/9597#discussion_r907021048

**Comment by Zelldon** [comment]
I see this on our plate, since we are in charge of the scheduler, we should provide an interface that fulfills all needs and that we can use in expression-language.
