### ISSUE TITLE
Refactor inter-partition communication to use a common sender and receiver

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9625]
Currently deployment commands and message correlation commands are send and received via different handlers.

* `DeploymentDistributorImpl` in Broker sends deployment distribution command and retries it.
* `PushDeploymentRequestHandler` in Broker handles deployment distribution command and sends the acknowledment back. It uses ClusterEventService directly.
* `LeaderManagementRequestHandler` which receives deployment distribution command
* `SubscriptionApiCommandMessageHandlerService` which receives message subscription commands.
* `SubscriptionCommandSender ` sends message subscription commands. It uses `PartitionCommandSender` abstraction. Retry is handled in engine by `PendingMessageSubscriptionChecker`.

Having several places for inter-partition communication is difficult to maintain. For backups we have to send additional information with these messages. To allow that, we should first centralize inter-partition communication. 

Goal: 
 - `PushDeploymentRequest` retries and acknowledgment should be handled in engine similarly to message subscription commands.
 - One PartitionCommandSender to send messages to other partitions.
 - One PartitionCommandReceiver to receive all messages from other partitions.
 - Engine uses this new PartitionCommandSender interface to send messages to other partitions.
 - Engine can register handlers to this receiver to process each message.

**Comment by saig0** [comment]
For the engine, we could simplify the communication by focusing on the major part: sending a command to a remote partition. 

Currently, the sender builds an SBE message and the receiver writes a record to the stream based on the SBE message. But the SBE message in the middle is not needed. It would be more direct if the sender could build the record by itself and transmit it to the remote partition directly. We could get rid of some boring transformation code.

**Comment by deepthidevaki** [comment]
> Currently, the sender builds an SBE message and the receiver writes a record to the stream based on the SBE message. But the SBE message in the middle is not needed. It would be more direct if the sender could build the record by itself and transmit it to the remote partition directly. We could get rid of some boring transformation code.

:+1: 

So the receiver directly writes the command to the logstream with out doing any additional processing. Right? This is good. Then everything on the receiver can be handled in the "distribution layer" itself. No need to pass it through engine.
