### ISSUE TITLE
Reject the modification command if the variables for activation are not valid

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#9662]
## Description

When we receive a gRPC request in the Gateway to modify a process instance then we should verify in the Gateway that the variables of the activate instructions are valid. If one of the variables is not valid (i.e. not a valid JSON string) then we should reject the command. Currently, we do the same for other commands, see [RequestMapper](https://github.com/camunda/zeebe/blob/main/gateway/src/main/java/io/camunda/zeebe/gateway/RequestMapper.java#L172-L197).

* in the gateway, verify that the variables of the activate instruction(s) are valid
* reject the modify command if one variables are not valid

Blocked by 
- #9659

**Comment by remcowesterhoud** [comment]
@saig0 We already do this here: https://github.com/camunda/zeebe/blob/main/gateway/src/main/java/io/camunda/zeebe/gateway/impl/broker/request/BrokerModifyProcessInstanceRequest.java#L59-L64

Or do you mean something different?

**Comment by saig0** [comment]
@remcowesterhoud nice :+1: Then, it is already implemented :rocket: 

But I don't see any test cases in the gateway yet. We should add a test class similar to [SetVariablesTest](https://github.com/camunda/zeebe/blob/main/gateway/src/test/java/io/camunda/zeebe/gateway/api/process/SetVariablesTest.java), including a test case for an invalid JSON (this kind of tests doesn't exist at the moment).
