### ISSUE TITLE
Engine abstraction - Investigate side effects

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9686]
This issue is to summarize findings related to side effects.

The vision for the side effects would be something like this (pseudocode):
**This is outdated** the new goal is documented here: https://github.com/camunda/zeebe/issues/9723#issuecomment-1177371393
```
(platform)

processRecords() {
   engine.init(reducedProcessingContext);

  while (true) {
   try (tx = createTx()) {
     record = stream.nextRecord();
     processingResult = engine.process(record);    
     transaction.commit();
     stream.writeRecords(processingResult.getRecords());
     processingResult.sideEffects().produce(sideEffectContext);
  } 
}
```  
Where `reducedProcessingContext` is the current context split up into whatever is needed for processing and whatever is needed for the side effects.

To answer whether such a vision is achievable, we need to answer a couple of questions:
1. What are the current side effects?
2. Can the platform execute the side effects? In other words, can we remove this code out of the engine completely?
3. Can we split up processing context as described above?
4. Are there any "hidden" side effects. I.e. code in the engine that does something similar than a side effect, but does not explicitly add a side effect for that code?
5. What exactly is the split of responsibilities between platform and engine with respect to side effects?

**Comment by pihme** [comment]
# What are current side effects?
* CloseMessageSubscriptionSideEffectProducer
* CloseProcessMessageSubscriptionSideEffectProducer
* CorrelateMultipleProcessMessageSubscriptionsSideEffectProducer
* FlushResponseWriterSideEffectProducer
* OpenMessageSubscriptionSideEffectProducer
* OpenProcessMessageSubscriptionSideEffectProducer
* ScheduleBackOffSideEffectProducer
* SendCorrelateCommandSideEffectProducer
* TypedResponseWriterImpl

**Comment by pihme** [comment]
# Can the platform execute the side effects? 

Not yet known. There are a couple of places where the engine flushes the side effect queue on its own:
* `io.camunda.zeebe.engine.processing.common.EventTriggerBehavior#unsubscribeEventSubprocesses`
* `io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnProcessResultSenderBehavior#sendResult(io.camunda.zeebe.engine.processing.bpmn.BpmnElementContext, io.camunda.zeebe.engine.state.instance.AwaitProcessInstanceResultMetadata)` This one might be a false positive. It doesn't flush the side effect queue, it only flushes the respose writer, which happens to implement the interface. In any case, if sending a response is supposed to be a side effect controlled by the platform, this is a deviation.
* `io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceProcessor#activateElementsForStartInstructions`

If we can find solution for these places, then the question could be answered with yes.

**Comment by pihme** [comment]
# Can we split up processing context as described above

Pending

**Comment by pihme** [comment]
# Are there any "hidden" side effects?

Pending

**Comment by Zelldon** [comment]
This topic is done afaik see https://github.com/camunda/zeebe/issues/9723#issuecomment-1245047603
