### ISSUE TITLE
Modify a process instance by terminating an element instance and activating an element within the same scope instance

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#9709]
## Description

A modification command can contain activate and terminate instructions. Both instructions can target the same flow scope. For example, the element to activate and the element instance to terminate are both in the process scope or in the scope of a subprocess. If the terminate instructions would terminate all active element instances of the flow scope then we need to take care of the order of the instructions/operations.  

If the element should be activated in the same flow scope then it should be activated in the existing instance of the flow scope. So, the flow scope should not be terminated. As a result, the new element instance that is activated can access the existing local variables of this flow scope (i.e. if it is a subprocess).

This behavior could be achieved by first applying all activate instructions and then applying the terminate instructions. If the new element instances are created first then the flow scope is not terminated by the termination instructions because it contains the (pending) activations of the new elements (i.e. the active sequence flow counter).   

For example:
![image](https://user-images.githubusercontent.com/4305769/177498217-7d8e2c13-42d1-4f22-9ecf-30b422d50519.png)

* apply all activate instructions of the modification command before applying the terminate instructions
* activate the new elements in the exiting flow scope instance
* avoid that the flow scope instance is terminated by the terminate instructions 
* verify that
  * the process instance is not terminated if all element instances are terminated and a new element is activated
  * the process instance can be completed after terminating all element instances and activating a new element
  * the flow scope is not terminated if all element instances are terminated and a new element is activated
  * the new element can access local variables of the flow scope if all element instances are terminated

Blocked by 
- #9642
- #9691

**Comment by remcowesterhoud** [comment]
The solution mentioned in this issue is unfortunately not possible, as the activation of an element needs to be done through a command, whereas the termination needs to be done using events.

The solution implemented in #10329 will make it so that when we activate an element we return the element instance key of the activated element, as well as a Set of keys of its flow scopes. This Set will be used by the termination to determine whether or not the scope can be terminated, or if it's still required later for an activation.
