### ISSUE TITLE
Dead code in metrics exporter

### ISSUE THREAD

**Issue by falko** [camunda/zeebe#9760]
After @korthout added a `RecordFilter` in https://github.com/camunda/zeebe/commit/db64a954391d8b14d5cf0741d165f113e7973eef the following code block should be dead code because no other record types would arrive in the exporter
https://github.com/camunda/zeebe/blob/2c52c6a764ed6d9bcc19428d9a2592a3888ed741/broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java#L92

**Comment by npepinpe** [comment]
I think we can close this now.

**Comment by falko** [comment]
The same code is still there:
https://github.com/camunda/zeebe/blob/90911096a1e21b1ece3c181ea4c42151faafcf73/zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java#L109-L112

and can still not be reached due to:
https://github.com/camunda/zeebe/blob/90911096a1e21b1ece3c181ea4c42151faafcf73/zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java#L82-L85

It looks to me like a cleanup or potential performance optimization to immediately advance the exporter position after ignoring a record and allowing for log compaction. On the other hand, such a behavior should be part of the generic `RecordFilter` mechanism anyway and thus make this code unnecessary in exporter implementations.

**Comment by npepinpe** [comment]
No, this is likely an artifact from before we had record filters :+1: I'll remove it. That said, I would expect the JVM to eventually optimize this code and make this almost a noop.
