### ISSUE TITLE
Support resource delete command in Java client

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#9792]

**Comment by megglos** [comment]
input for triage, is this lacking?

**Comment by nicpuppa** [comment]
> is this lacking?

I think this command is already implemented in Zeebe, see https://github.com/camunda/zeebe/blob/main/zeebe/clients/java/src/main/java/io/camunda/zeebe/client/impl/command/DeleteResourceCommandImpl.java

**Comment by megglos** [comment]
done with https://github.com/camunda/zeebe/issues/9793
