### ISSUE TITLE
Extend `RandomizedRaftTest` with snapshot and data loss operations

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9837]
[Recent issues](https://github.com/camunda/zeebe/issues/9820) with snapshots have highlighted a need to improve test coverage. We can extend the `RandomizedRaftTest` by adding additional operations for taking snapshots and for losing data.

**Comment by menski** [comment]
marked it with the hot backup epic as it might be valuable to verify the system

**Comment by npepinpe** [comment]
Is this done via #10183 ?

**Comment by deepthidevaki** [comment]
> Is this done via #10183 ?

No. It only added snapshot. We still have to add restarts and restarts with dataloss.
