### ISSUE TITLE
Pausing a partition should pause all processing, not just the processing state machine

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#9962]
**Describe the bug**

When pausing processing of a partition which is already processing, it pauses only the processing state machine. Anything outside of it but running in the same actor may still be working, e.g. the distribution behavior is still redistributing. 

**To Reproduce**

Start a cluster with a least two partition, and make sure you have different leaders for each. Then pause processing on the second partition, and deploy a BPMN on the first. You will see that it keeps retrying since there is no answer.

Now pause processing of partition 1, and you will see it still keeps retrying.

**Expected behavior**

Pausing processing pauses the complete engine, not just the processing state machine. That includes redistributing deployments, timer triggers, message subscriptions, etc. We cannot pause the complete actor obviously since we may need to resume, but no work should be done in general.

**Comment by Zelldon** [comment]
In my opinion we will get this with the engine abstraction proposal and the new scheduling service.

**Comment by menski** [comment]
should be fixed by #9600
